P_ENV = struct();
P_ENV.location.latitude_ref_deg = ...
    4.60;
P_ENV.location.longitude_ref_deg = ...
    -74.07;
P_ENV.location.altitude_ref_m = ...
    2640;
P_ENV.gravity.magnitude_m_s2 = gravitywgs84( ...
    P_ENV.location.altitude_ref_m, ...
    P_ENV.location.latitude_ref_deg, ...
    'TaylorSeries', ...
    'Error');
P_ENV.gravity.world_vector_m_s2 = [ ...
    0 ...
    0 ...
   -P_ENV.gravity.magnitude_m_s2];
P_ENV.atmosphere.model = ...
    "ISA";
P_ENV.atmosphere.units = ...
    "Metric (MKS)";
P_ENV.atmosphere.reference_air_density_kg_m3 = ...
    1.225;
P_ENV.air.density_kg_m3 = ...
    P_ENV.atmosphere.reference_air_density_kg_m3;
P_ENV.ground.contact.stiffness_N_m = ...
    5e4;
P_ENV.ground.contact.damping_N_s_m = ...
    100;
P_ENV.ground.contact.transition_width_m = ...
    1e-3;
P_ENV.ground.contact.static_friction = ...
    0.6;
P_ENV.ground.contact.dynamic_friction = ...
    0.5;
P_ENV.ground.contact.critical_velocity_m_s = ...
    0.05;
P_ENV.wind.gust.start_time_s = ...
    20.0;
P_ENV.wind.gust.length_m = [ ...
    25 ...
    25 ...
    15];
P_ENV.wind.gust.amplitude_m_s = [ ...
    0.8 ...
    0.8 ...
    0.5];
P_ENV.wind.shear.speed_6m_m_s = ...
    1.5;
P_ENV.wind.shear.direction_6m_deg = ...
    0;
P_ENV.wind.turbulence.speed_6m_m_s = ...
    1.5;
P_ENV.wind.turbulence.direction_6m_deg = ...
    0;
P_ENV.wind.turbulence.scale_length_m = ...
    533.4;
P_ENV.wind.turbulence.sample_time_s = ...
    0.1;
P_ENV.wind.turbulence.noise_seeds = [ ...
    23341 ...
    23342 ...
    23343 ...
    23344];
P_ENV.wind.turbulence.speed_epsilon_m_s = ...
    eps;
P_ENV.location.heading_ref_deg = ...
    0;
P_ENV.location.flat_earth_href_m = ...
    -P_ENV.location.altitude_ref_m;
