this_file = mfilename('fullpath');
if isempty(this_file)
    project_root = pwd;
else
    project_root = fileparts(this_file);
end
cad_folder = fullfile( ...
    project_root, ...
    'CAD');
if ~exist(cad_folder, 'dir')
    error( ...
        'QuadrotorFramework:MissingCADFolder', ...
        'CAD folder was not found.');
end
addpath(cad_folder);
cache_folder = fullfile( ...
    project_root, ...
    'cache_folder');
simulink_cache_folder = fullfile( ...
    cache_folder, ...
    'simulink_cache');
codegen_folder = fullfile( ...
    cache_folder, ...
    'codegen');
autosave_folder = fullfile( ...
    cache_folder, ...
    'autosave');
asv_folder = fullfile( ...
    cache_folder, ...
    'asv');
temp_folder = fullfile( ...
    cache_folder, ...
    'temp');
results_folder = fullfile( ...
    project_root, ...
    'results');
folders_to_create = { ...
    cache_folder, ...
    simulink_cache_folder, ...
    codegen_folder, ...
    autosave_folder, ...
    asv_folder, ...
    temp_folder, ...
    results_folder};
for i = 1:numel(folders_to_create)
    if ~exist(folders_to_create{i}, 'dir')
        mkdir(folders_to_create{i});
    end
end
Simulink.fileGenControl( ...
    'set', ...
    'CacheFolder', simulink_cache_folder, ...
    'CodeGenFolder', codegen_folder, ...
    'createDir', true);
setenv( ...
    'TMP', ...
    temp_folder);
setenv( ...
    'TEMP', ...
    temp_folder);
asv_files = dir( ...
    fullfile( ...
        project_root, ...
        '*.asv'));
for i = 1:numel(asv_files)
    source_file = fullfile( ...
        project_root, ...
        asv_files(i).name);
    target_file = fullfile( ...
        asv_folder, ...
        asv_files(i).name);
    if exist(source_file, 'file')
        movefile( ...
            source_file, ...
            target_file, ...
            'f');
    end
end
if ~exist('UAV_MODEL', 'var')
    UAV_MODEL = 1;
end
if ~isscalar(UAV_MODEL) || ...
        ~isnumeric(UAV_MODEL) || ...
        ~isfinite(double(UAV_MODEL)) || ...
        ~ismember(double(UAV_MODEL), [1 2 3])
    error( ...
        'QuadrotorFramework:InvalidUAVModel', ...
        ['UAV_MODEL must be a finite numeric scalar with value ', ...
         '1 (L1), 2 (L2), or 3 (L3).']);
end
if ~exist('DIST_ENABLE', 'var')
    DIST_ENABLE = true;
end
SAVE_METRICS_REQUESTED = false;
BENCHMARK_METRICS = ...
    struct();
BENCHMARK_METRICS.schemaVersion = ...
    '1.0';
BENCHMARK_METRICS.sampleRate_Hz = ...
    200.0;
BENCHMARK_METRICS.samplePeriod_s = ...
    1.0 / ...
    BENCHMARK_METRICS.sampleRate_Hz;
BENCHMARK_METRICS.windows = ...
    struct();
BENCHMARK_METRICS.windows.physicalMission = ...
    struct( ...
        'startEvent','TAKEOFF', ...
        'endEvent','LANDED');
BENCHMARK_METRICS.windows.navigationTracking = ...
    struct( ...
        'startEvent','TAKEOFF', ...
        'endEvent','CGS_COMPLETE');
BENCHMARK_METRICS.windows.landing = ...
    struct( ...
        'startEvent','LAND', ...
        'endEvent','LANDED');
BENCHMARK_METRICS.windows.estimator = ...
    struct( ...
        'startEvent','MAX_TAKEOFF_ESTIMATOR_READY', ...
        'endEvent','LANDED', ...
        'readinessSource', ...
        'ESTIMATOR.validation.metricStartTime_s');
BENCHMARK_METRICS.computationalCost = ...
    struct();
BENCHMARK_METRICS.computationalCost.enabled = ...
    true;
BENCHMARK_METRICS.computationalCost.measureExecutionWallClock = ...
    true;
BENCHMARK_METRICS.computationalCost.measureInitializationSeparately = ...
    true;
BENCHMARK_METRICS.computationalCost.measureSolverStatistics = ...
    true;
BENCHMARK_METRICS.computationalCost.computeRealTimeFactor = ...
    true;
BENCHMARK_METRICS.computationalCost.computeComputationalTimeFactor = ...
    true;
BENCHMARK_METRICS.computationalCost.requirePacingDisabled = ...
    true;
BENCHMARK_METRICS.computationalCost.executionScope = ...
    'SIMULATION_EXECUTION_ONLY';
BENCHMARK_METRICS.computationalCost.initializationScope = ...
    'MODEL_UPDATE_COMPILE_INITIALIZATION';
BENCHMARK_METRICS.computationalCost.rtfDefinition = ...
    'simulatedMissionTime_s / executionWallClockTime_s';
BENCHMARK_METRICS.computationalCost.ctfDefinition = ...
    'executionWallClockTime_s / simulatedMissionTime_s';
if ~isscalar(BENCHMARK_METRICS.sampleRate_Hz) || ...
        ~isfinite(BENCHMARK_METRICS.sampleRate_Hz) || ...
        BENCHMARK_METRICS.sampleRate_Hz <= 0
    error( ...
        'QuadrotorFramework:InvalidBenchmarkSampleRate', ...
        'BENCHMARK_METRICS.sampleRate_Hz must be finite and > 0.');
end
if ~isscalar(BENCHMARK_METRICS.samplePeriod_s) || ...
        ~isfinite(BENCHMARK_METRICS.samplePeriod_s) || ...
        BENCHMARK_METRICS.samplePeriod_s <= 0
    error( ...
        'QuadrotorFramework:InvalidBenchmarkSamplePeriod', ...
        'BENCHMARK_METRICS.samplePeriod_s must be finite and > 0.');
end
if abs( ...
        BENCHMARK_METRICS.samplePeriod_s - ...
        1.0/BENCHMARK_METRICS.sampleRate_Hz) > ...
        100*eps
    error( ...
        'QuadrotorFramework:InconsistentBenchmarkSamplePeriod', ...
        ['BENCHMARK_METRICS.samplePeriod_s must equal ', ...
         '1/BENCHMARK_METRICS.sampleRate_Hz.']);
end
requiredBenchmarkWindows = { ...
    'physicalMission', ...
    'navigationTracking', ...
    'landing', ...
    'estimator'};
for benchmarkWindowIndex = ...
        1:numel(requiredBenchmarkWindows)
    benchmarkWindowName = ...
        requiredBenchmarkWindows{benchmarkWindowIndex};
    if ~isfield( ...
            BENCHMARK_METRICS.windows, ...
            benchmarkWindowName)
        error( ...
            'QuadrotorFramework:MissingBenchmarkMetricWindow', ...
            ['BENCHMARK_METRICS.windows.%s is missing.'], ...
            benchmarkWindowName);
    end
end
clear benchmarkWindowIndex ...
      benchmarkWindowName ...
      requiredBenchmarkWindows;
requiredComputationalCostFields = { ...
    'enabled', ...
    'measureExecutionWallClock', ...
    'measureInitializationSeparately', ...
    'measureSolverStatistics', ...
    'computeRealTimeFactor', ...
    'computeComputationalTimeFactor', ...
    'requirePacingDisabled', ...
    'executionScope', ...
    'initializationScope', ...
    'rtfDefinition', ...
    'ctfDefinition'};
for computationalCostFieldIndex = ...
        1:numel(requiredComputationalCostFields)
    computationalCostFieldName = ...
        requiredComputationalCostFields{ ...
            computationalCostFieldIndex};
    if ~isfield( ...
            BENCHMARK_METRICS.computationalCost, ...
            computationalCostFieldName)
        error( ...
            'QuadrotorFramework:MissingComputationalCostConfiguration', ...
            ['BENCHMARK_METRICS.computationalCost.%s is missing.'], ...
            computationalCostFieldName);
    end
end
clear computationalCostFieldIndex ...
      computationalCostFieldName ...
      requiredComputationalCostFields;
OPERATOR_MODE_MANUAL = ...
    uint8(0);
OPERATOR_MODE_AUTOMATIC = ...
    uint8(1);
if ~exist('OPERATOR_MODE','var') || ...
        isempty(OPERATOR_MODE)
    OPERATOR_MODE = ...
        OPERATOR_MODE_MANUAL;
else
    OPERATOR_MODE = ...
        uint8(OPERATOR_MODE);
end
if ~isscalar(OPERATOR_MODE) || ...
        (OPERATOR_MODE ~= OPERATOR_MODE_MANUAL && ...
         OPERATOR_MODE ~= OPERATOR_MODE_AUTOMATIC)
    warning( ...
        'QuadrotorFramework:InvalidOperatorMode', ...
        ['Invalid OPERATOR_MODE detected. ', ...
         'Resetting to MANUAL mode.']);
    OPERATOR_MODE = ...
        OPERATOR_MODE_MANUAL;
end
trajectory_file = ...
    fullfile( ...
        project_root, ...
        'UAV_trajectories.m');
if ~exist(trajectory_file,'file')
    error( ...
        'QuadrotorFramework:MissingTrajectoryLibrary', ...
        ['Required trajectory library was not found:\n%s\n\n', ...
         'UAV_trajectories.m is now the single source of truth for ', ...
         'benchmark trajectories.'], ...
        trajectory_file);
end
clear TRAJECTORY_LIBRARY ...
      TRAJECTORY ...
      TRAJECTORY_CONFIG ...
      TRAJECTORY_DEFAULTS ...
      MAX_WAYPOINTS ...
      AUTO_PROTOCOL;
try
    run(trajectory_file);
catch ME
    error( ...
        'QuadrotorFramework:TrajectoryLibraryInitializationFailed', ...
        ['Unable to initialize UAV_trajectories.m.\n\n', ...
         'Original error:\n%s'], ...
        ME.message);
end
requiredTrajectoryVariables = { ...
    'TRAJECTORY_ID', ...
    'TRAJECTORY_LIBRARY', ...
    'TRAJECTORY', ...
    'TRAJECTORY_CONFIG', ...
    'MAX_WAYPOINTS', ...
    'AUTO_PROTOCOL'};
for trajectoryVariableIndex = ...
        1:numel(requiredTrajectoryVariables)
    trajectoryVariableName = ...
        requiredTrajectoryVariables{ ...
            trajectoryVariableIndex};
    if ~exist( ...
            trajectoryVariableName, ...
            'var')
        error( ...
            'QuadrotorFramework:IncompleteTrajectoryInterface', ...
            ['UAV_trajectories.m did not create required variable ', ...
             '"%s".'], ...
            trajectoryVariableName);
    end
end
clear trajectoryVariableIndex ...
      trajectoryVariableName ...
      requiredTrajectoryVariables;
if ~isstruct(TRAJECTORY_LIBRARY) || ...
        isempty(TRAJECTORY_LIBRARY)
    error( ...
        'QuadrotorFramework:InvalidTrajectoryLibrary', ...
        'TRAJECTORY_LIBRARY must be a nonempty structure array.');
end
if ~isstruct(TRAJECTORY) || ...
        ~isscalar(TRAJECTORY)
    error( ...
        'QuadrotorFramework:InvalidSelectedTrajectory', ...
        'TRAJECTORY must be one selected trajectory structure.');
end
if ~isstruct(TRAJECTORY_CONFIG) || ...
        ~isscalar(TRAJECTORY_CONFIG)
    error( ...
        'QuadrotorFramework:InvalidTrajectoryConfiguration', ...
        'TRAJECTORY_CONFIG must be a scalar structure.');
end
if ~isscalar(MAX_WAYPOINTS) || ...
        ~isfinite(double(MAX_WAYPOINTS)) || ...
        double(MAX_WAYPOINTS) < 1 || ...
        double(MAX_WAYPOINTS) ~= round(double(MAX_WAYPOINTS))
    error( ...
        'QuadrotorFramework:InvalidMaximumWaypointCount', ...
        'MAX_WAYPOINTS must be a finite positive integer.');
end
if ~isfield(TRAJECTORY,'numWaypoints') || ...
        ~isscalar(TRAJECTORY.numWaypoints) || ...
        double(TRAJECTORY.numWaypoints) < 1 || ...
        double(TRAJECTORY.numWaypoints) > double(MAX_WAYPOINTS)
    error( ...
        'QuadrotorFramework:InvalidSelectedWaypointCount', ...
        ['Selected trajectory numWaypoints must satisfy ', ...
         '1 <= numWaypoints <= MAX_WAYPOINTS.']);
end
if ~isfield(TRAJECTORY,'missionPlanRelative') || ...
        size(TRAJECTORY.missionPlanRelative,1) ~= 4 || ...
        size(TRAJECTORY.missionPlanRelative,2) ~= ...
            double(TRAJECTORY.numWaypoints)
    error( ...
        'QuadrotorFramework:InvalidSelectedMissionPlan', ...
        ['TRAJECTORY.missionPlanRelative must have dimensions ', ...
         '[4 x numWaypoints].']);
end
if any(~isfinite( ...
        double( ...
            TRAJECTORY.missionPlanRelative(:))))
    error( ...
        'QuadrotorFramework:NonFiniteSelectedMissionPlan', ...
        'Selected trajectory MissionPlan contains NaN or Inf.');
end
if ~isstruct(AUTO_PROTOCOL) || ...
        ~isfield(AUTO_PROTOCOL,'schedule_s') || ...
        ~isfield(AUTO_PROTOCOL,'trajectoryNames') || ...
        ~isfield(AUTO_PROTOCOL,'column') || ...
        ~isfield(AUTO_PROTOCOL,'selected')
    error( ...
        'QuadrotorFramework:InvalidAutomaticOperatorInterface', ...
        ['UAV_trajectories.m must provide the backward-compatible ', ...
         'AUTO_PROTOCOL interface required by the current GUI/model.']);
end
number_of_protocols = ...
    size( ...
        AUTO_PROTOCOL.schedule_s, ...
        1);
if number_of_protocols ~= ...
        numel(TRAJECTORY_LIBRARY)
    error( ...
        'QuadrotorFramework:TrajectoryProtocolCountMismatch', ...
        ['AUTO_PROTOCOL.schedule_s must contain one row for every ', ...
         'trajectory in TRAJECTORY_LIBRARY.']);
end
if numel(AUTO_PROTOCOL.trajectoryNames) ~= ...
        number_of_protocols
    error( ...
        'QuadrotorFramework:OperatorProtocolNameMismatch', ...
        ['AUTO_PROTOCOL.trajectoryNames and AUTO_PROTOCOL.schedule_s ', ...
         'must contain the same number of trajectories.']);
end
requiredProtocolColumns = { ...
    'arm', ...
    'run', ...
    'disarm', ...
    'stop'};
for protocolColumnIndex = ...
        1:numel(requiredProtocolColumns)
    protocolColumnName = ...
        requiredProtocolColumns{ ...
            protocolColumnIndex};
    if ~isfield( ...
            AUTO_PROTOCOL.column, ...
            protocolColumnName)
        error( ...
            'QuadrotorFramework:MissingOperatorProtocolColumn', ...
            'AUTO_PROTOCOL.column.%s is missing.', ...
            protocolColumnName);
    end
end
clear protocolColumnIndex ...
      protocolColumnName ...
      requiredProtocolColumns;
for protocol_index = 1:number_of_protocols
    arm_time_s = ...
        AUTO_PROTOCOL.schedule_s( ...
            protocol_index, ...
            AUTO_PROTOCOL.column.arm);
    run_time_s = ...
        AUTO_PROTOCOL.schedule_s( ...
            protocol_index, ...
            AUTO_PROTOCOL.column.run);
    disarm_time_s = ...
        AUTO_PROTOCOL.schedule_s( ...
            protocol_index, ...
            AUTO_PROTOCOL.column.disarm);
    stop_time_s = ...
        AUTO_PROTOCOL.schedule_s( ...
            protocol_index, ...
            AUTO_PROTOCOL.column.stop);
    if ~( ...
            isfinite(arm_time_s) && ...
            isfinite(run_time_s) && ...
            isfinite(disarm_time_s) && ...
            isfinite(stop_time_s) && ...
            arm_time_s >= 0 && ...
            run_time_s >= arm_time_s && ...
            disarm_time_s > run_time_s && ...
            stop_time_s > disarm_time_s)
        error( ...
            'QuadrotorFramework:InvalidOperatorProtocol', ...
            ['Invalid automatic operator protocol in row %d. ', ...
             'Expected 0 <= ARM <= RUN < DISARM < STOP.'], ...
            protocol_index);
    end
end
clear protocol_index ...
      arm_time_s ...
      run_time_s ...
      disarm_time_s ...
      stop_time_s;
selected_trajectory_index = ...
    double( ...
        TRAJECTORY_ID);
if selected_trajectory_index < 1 || ...
        selected_trajectory_index > ...
            numel(TRAJECTORY_LIBRARY)
    error( ...
        'QuadrotorFramework:InvalidSelectedTrajectoryID', ...
        'TRAJECTORY_ID is outside TRAJECTORY_LIBRARY.');
end
if double(TRAJECTORY.id) ~= ...
        selected_trajectory_index
    error( ...
        'QuadrotorFramework:SelectedTrajectoryMismatch', ...
        ['TRAJECTORY.id does not match the currently selected ', ...
         'TRAJECTORY_ID.']);
end
if ~isfield(TRAJECTORY_CONFIG,'selectedID') || ...
        double(TRAJECTORY_CONFIG.selectedID) ~= ...
            selected_trajectory_index
    error( ...
        'QuadrotorFramework:TrajectoryConfigurationMismatch', ...
        ['TRAJECTORY_CONFIG.selectedID does not match ', ...
         'TRAJECTORY_ID.']);
end
clear selected_trajectory_index ...
      number_of_protocols;
environment_file = fullfile( ...
    project_root, ...
    'Environment.m');
if exist(environment_file, 'file')
    run(environment_file);
else
    warning( ...
        'QuadrotorFramework:MissingEnvironment', ...
        'Environment.m was not found.');
end
sensor_file = fullfile( ...
    project_root, ...
    'UAV_sensors.m');
if exist(sensor_file, 'file')
    run(sensor_file);
else
    warning( ...
        'QuadrotorFramework:MissingSensorParameters', ...
        'UAV_sensors.m was not found.');
end
state_estimator_file = fullfile( ...
    project_root, ...
    'UAV_state_estimator.m');
if exist(state_estimator_file, 'file')
    if exist('P_ENV','var') && exist('SENSOR','var')
        run(state_estimator_file);
    else
        warning( ...
            'QuadrotorFramework:EstimatorDependenciesMissing', ...
            ['UAV_state_estimator.m was not executed because ', ...
             'P_ENV and/or SENSOR are missing.']);
    end
else
    warning( ...
        'QuadrotorFramework:MissingStateEstimatorParameters', ...
        'UAV_state_estimator.m was not found.');
end
analytical_file = fullfile( ...
    project_root, ...
    'UAV_analytical.m');
if exist(analytical_file, 'file')
    run(analytical_file);
else
    warning( ...
        'QuadrotorFramework:MissingAnalyticalModel', ...
        'UAV_analytical.m was not found.');
end
autopilot_file = fullfile( ...
    project_root, ...
    'UAV_autopilot.m');
if exist(autopilot_file, 'file')
    if exist('P_ENV','var') && ...
            exist('SENSOR','var') && ...
            exist('A_UAV','var')
        run(autopilot_file);
    else
        warning( ...
            'QuadrotorFramework:AutopilotDependenciesMissing', ...
            ['UAV_autopilot.m was not executed because ', ...
             'P_ENV, SENSOR and/or A_UAV are missing.']);
    end
else
    warning( ...
        'QuadrotorFramework:MissingAutopilotParameters', ...
        'UAV_autopilot.m was not found.');
end
block_file = fullfile( ...
    project_root, ...
    'UAV_block.m');
if exist(block_file, 'file')
    run(block_file);
else
    warning( ...
        'QuadrotorFramework:MissingBlockModel', ...
        'UAV_block.m was not found.');
end
simscape_file = fullfile( ...
    project_root, ...
    'UAV_simscape.m');
if exist(simscape_file, 'file')
    run(simscape_file);
else
    warning( ...
        'QuadrotorFramework:MissingSimscapeModel', ...
        'UAV_simscape.m was not found.');
end
switch double(UAV_MODEL)
    case 1
        if ~exist('A_UAV_CONTACT','var') || ...
                ~isstruct(A_UAV_CONTACT)
            error( ...
                'QuadrotorFramework:MissingL1ContactParameters', ...
                ['UAV_MODEL = 1 requires the numerical contact ', ...
                 'parameter structure A_UAV_CONTACT from ', ...
                 'UAV_analytical.m.']);
        end
        UAV_CONTACT = ...
            A_UAV_CONTACT;
        UAV_CONTACT_SOURCE = ...
            'A_UAV_CONTACT';
    case 2
        if ~exist('B_UAV_CONTACT','var') || ...
                ~isstruct(B_UAV_CONTACT)
            error( ...
                'QuadrotorFramework:MissingL2ContactParameters', ...
                ['UAV_MODEL = 2 requires the numerical contact ', ...
                 'parameter structure B_UAV_CONTACT from UAV_block.m.']);
        end
        UAV_CONTACT = ...
            B_UAV_CONTACT;
        UAV_CONTACT_SOURCE = ...
            'B_UAV_CONTACT';
    case 3
        if exist('B_UAV_CONTACT','var') && ...
                isstruct(B_UAV_CONTACT)
            UAV_CONTACT = ...
                B_UAV_CONTACT;
        elseif exist('A_UAV_CONTACT','var') && ...
                isstruct(A_UAV_CONTACT)
            UAV_CONTACT = ...
                A_UAV_CONTACT;
        else
            error( ...
                'QuadrotorFramework:MissingContactCompatibilityData', ...
                ['No numerical UAV contact structure is available for ', ...
                 'inactive L1/L2 variant compatibility.']);
        end
        UAV_CONTACT_SOURCE = ...
            'L3_NATIVE_SIMSCAPE_CONTACT';
end
requiredContactFields = { ...
    'arm_body_m', ...
    'ground_down_m', ...
    'stiffness_N_m', ...
    'damping_N_s_m', ...
    'static_friction', ...
    'dynamic_friction', ...
    'critical_velocity_m_s'};
for contactFieldIndex = ...
        1:numel(requiredContactFields)
    contactFieldName = ...
        requiredContactFields{contactFieldIndex};
    if ~isfield(UAV_CONTACT,contactFieldName)
        error( ...
            'QuadrotorFramework:IncompleteUAVContactInterface', ...
            'UAV_CONTACT.%s is missing.', ...
            contactFieldName);
    end
end
if ~isnumeric(UAV_CONTACT.arm_body_m) || ...
        size(UAV_CONTACT.arm_body_m,2) ~= 3 || ...
        isempty(UAV_CONTACT.arm_body_m) || ...
        any(~isfinite(double(UAV_CONTACT.arm_body_m(:))))
    error( ...
        'QuadrotorFramework:InvalidUAVContactGeometry', ...
        ['UAV_CONTACT.arm_body_m must be a finite numeric ', ...
         '[N x 3] matrix.']);
end
scalarContactFields = { ...
    'ground_down_m', ...
    'stiffness_N_m', ...
    'damping_N_s_m', ...
    'static_friction', ...
    'dynamic_friction', ...
    'critical_velocity_m_s'};
for contactFieldIndex = ...
        1:numel(scalarContactFields)
    contactFieldName = ...
        scalarContactFields{contactFieldIndex};
    contactFieldValue = ...
        UAV_CONTACT.(contactFieldName);
    if ~isnumeric(contactFieldValue) || ...
            ~isscalar(contactFieldValue) || ...
            ~isfinite(double(contactFieldValue))
        error( ...
            'QuadrotorFramework:InvalidUAVContactParameter', ...
            'UAV_CONTACT.%s must be a finite numeric scalar.', ...
            contactFieldName);
    end
end
if UAV_CONTACT.stiffness_N_m <= 0 || ...
        UAV_CONTACT.damping_N_s_m < 0 || ...
        UAV_CONTACT.static_friction < 0 || ...
        UAV_CONTACT.dynamic_friction < 0 || ...
        UAV_CONTACT.critical_velocity_m_s <= 0
    error( ...
        'QuadrotorFramework:InvalidUAVContactValues', ...
        ['UAV_CONTACT requires stiffness > 0, damping >= 0, ', ...
         'friction coefficients >= 0, and critical velocity > 0.']);
end
clear contactFieldIndex ...
      contactFieldName ...
      contactFieldValue ...
      requiredContactFields ...
      scalarContactFields;
gui_file = fullfile( ...
    project_root, ...
    'uav_remote_gui.m');
if ~exist(gui_file, 'file')
    warning( ...
        'QuadrotorFramework:MissingGUI', ...
        'uav_remote_gui.m was not found.');
end
estimator_plot_file = fullfile( ...
    project_root, ...
    'plot_estimator_results.m');
trajectory_plot_file = fullfile( ...
    project_root, ...
    'plot_trajectory_3d.m');
controller_plot_file = fullfile( ...
    project_root, ...
    'plot_controller_results.m');
mission_plot_file = fullfile( ...
    project_root, ...
    'plot_mission_results.m');
touchdown_plot_file = fullfile( ...
    project_root, ...
    'plot_touchdown_diagnostics.m');
if ~exist(estimator_plot_file, 'file')
    warning( ...
        'QuadrotorFramework:MissingEstimatorPlots', ...
        'plot_estimator_results.m was not found.');
end
if ~exist(trajectory_plot_file, 'file')
    warning( ...
        'QuadrotorFramework:MissingTrajectoryPlots', ...
        'plot_trajectory_3d.m was not found.');
end
if ~exist(controller_plot_file, 'file')
    warning( ...
        'QuadrotorFramework:MissingControllerPlots', ...
        'plot_controller_results.m was not found.');
end
if ~exist(mission_plot_file, 'file')
    warning( ...
        'QuadrotorFramework:MissingMissionPlots', ...
        'plot_mission_results.m was not found.');
end
if ~exist(touchdown_plot_file, 'file')
    warning( ...
        'QuadrotorFramework:MissingTouchdownPlots', ...
        'plot_touchdown_diagnostics.m was not found.');
end
model_file = fullfile( ...
    project_root, ...
    'UAV_Research_Environment.slx');
if ~exist(model_file, 'file')
    warning( ...
        'QuadrotorFramework:MissingModel', ...
        'UAV_Research_Environment.slx was not found.');
end
disp(' ');
disp( ...
    '==============================================================');
disp( ...
    ' Quadrotor Multi-Fidelity Framework initialized successfully.');
disp( ...
    '==============================================================');
fprintf( ...
    'Project root:             %s\n', ...
    project_root);
fprintf( ...
    'Cache folder:             %s\n', ...
    cache_folder);
fprintf( ...
    'Simulink cache folder:    %s\n', ...
    simulink_cache_folder);
fprintf( ...
    'Code generation folder:   %s\n', ...
    codegen_folder);
fprintf( ...
    'Autosave folder:          %s\n', ...
    autosave_folder);
fprintf( ...
    'ASV backup folder:        %s\n', ...
    asv_folder);
fprintf( ...
    'Temporary folder:         %s\n', ...
    temp_folder);
fprintf( ...
    'Results folder:           %s\n', ...
    results_folder);
disp( ...
    '--------------------------------------------------------------');
fprintf( ...
    'UAV model selected:       L%d\n', ...
    UAV_MODEL);
if UAV_MODEL == 3
    fprintf( ...
        'UAV contact model:        L3 native Simscape\n');
else
    fprintf( ...
        'UAV contact parameters:   %s -> UAV_CONTACT\n', ...
        UAV_CONTACT_SOURCE);
end
if DIST_ENABLE
    fprintf( ...
        'Disturbances:             ON\n');
else
    fprintf( ...
        'Disturbances:             OFF\n');
end
if OPERATOR_MODE == OPERATOR_MODE_AUTOMATIC
    operator_mode_text = ...
        'AUTOMATIC';
else
    operator_mode_text = ...
        'MANUAL';
end
fprintf( ...
    'Operator mode:            %s\n', ...
    operator_mode_text);
fprintf( ...
    'Trajectory ID:            %d\n', ...
    TRAJECTORY_ID);
fprintf( ...
    'Trajectory:               %s\n', ...
    char(TRAJECTORY.name));
fprintf( ...
    'Trajectory waypoints:     %d\n', ...
    double(TRAJECTORY.numWaypoints));
fprintf( ...
    'Framework MAX_WAYPOINTS:  %d\n', ...
    double(MAX_WAYPOINTS));
if isfield(TRAJECTORY,'metrics') && ...
        isstruct(TRAJECTORY.metrics) && ...
        isfield(TRAJECTORY.metrics,'nominalPathLength3D_m')
    fprintf( ...
        'Nominal path length:     %.3f m\n', ...
        TRAJECTORY.metrics.nominalPathLength3D_m);
end
fprintf( ...
    ['Auto protocol [s]:       ARM %.1f | RUN %.1f | ', ...
     'DISARM %.1f | STOP %.1f\n'], ...
    AUTO_PROTOCOL.selected.armTime_s, ...
    AUTO_PROTOCOL.selected.runTime_s, ...
    AUTO_PROTOCOL.selected.disarmTime_s, ...
    AUTO_PROTOCOL.selected.stopTime_s);
fprintf( ...
    'Metric evaluation rate:   %.1f Hz\n', ...
    BENCHMARK_METRICS.sampleRate_Hz);
fprintf( ...
    'Metric evaluation period: %.4f s\n', ...
    BENCHMARK_METRICS.samplePeriod_s);
if BENCHMARK_METRICS.computationalCost.enabled
    fprintf( ...
        'Computational cost:      ENABLED\n');
else
    fprintf( ...
        'Computational cost:      DISABLED\n');
end
if BENCHMARK_METRICS.computationalCost.requirePacingDisabled
    fprintf( ...
        'Official cost pacing:    MUST BE OFF\n');
else
    fprintf( ...
        'Official cost pacing:    unrestricted\n');
end
if SAVE_METRICS_REQUESTED
    fprintf( ...
        'Save metrics request:     ACTIVE\n');
else
    fprintf( ...
        'Save metrics request:     OFF\n');
end
disp( ...
    '--------------------------------------------------------------');
if exist(environment_file, 'file')
    fprintf( ...
        'Environment parameters:   OK\n');
else
    fprintf( ...
        'Environment parameters:   MISSING\n');
end
if exist(sensor_file, 'file')
    fprintf( ...
        'Sensor parameters:        OK\n');
else
    fprintf( ...
        'Sensor parameters:        MISSING\n');
end
if exist(state_estimator_file, 'file') && ...
        exist('ESTIMATOR','var')
    fprintf( ...
        'Estimator parameters:     OK\n');
else
    fprintf( ...
        'Estimator parameters:     MISSING\n');
end
if exist(analytical_file, 'file') && ...
        exist('A_UAV','var')
    fprintf( ...
        'L1 Analytical model:      OK\n');
else
    fprintf( ...
        'L1 Analytical model:      MISSING\n');
end
if exist(autopilot_file, 'file') && ...
        exist('AUTOPILOT','var')
    fprintf( ...
        'Autopilot parameters:     OK\n');
else
    fprintf( ...
        'Autopilot parameters:     MISSING\n');
end
if exist(block_file, 'file')
    fprintf( ...
        'L2 Simulink model:        OK\n');
else
    fprintf( ...
        'L2 Simulink model:        MISSING\n');
end
if exist(simscape_file, 'file')
    fprintf( ...
        'L3 Simscape model:        OK\n');
else
    fprintf( ...
        'L3 Simscape model:        MISSING\n');
end
if exist('UAV_CONTACT','var') && ...
        isstruct(UAV_CONTACT) && ...
        exist('UAV_CONTACT_SOURCE','var')
    if UAV_MODEL == 3
        fprintf( ...
            'UAV contact interface:     L3 NATIVE / COMPATIBILITY OK\n');
    else
        fprintf( ...
            'UAV contact interface:     OK [%s]\n', ...
            UAV_CONTACT_SOURCE);
    end
else
    fprintf( ...
        'UAV contact interface:     MISSING\n');
end
if exist(trajectory_file,'file') && ...
        exist('TRAJECTORY_LIBRARY','var') && ...
        exist('TRAJECTORY','var') && ...
        exist('TRAJECTORY_CONFIG','var') && ...
        exist('MAX_WAYPOINTS','var')
    fprintf( ...
        'Trajectory library:      OK\n');
else
    fprintf( ...
        'Trajectory library:      MISSING\n');
end
if exist('AUTO_PROTOCOL','var') && ...
        isstruct(AUTO_PROTOCOL) && ...
        exist('OPERATOR_MODE','var') && ...
        exist('TRAJECTORY_ID','var')
    fprintf( ...
        'Operator protocols:       OK\n');
else
    fprintf( ...
        'Operator protocols:       MISSING\n');
end
if exist('BENCHMARK_METRICS','var') && ...
        isstruct(BENCHMARK_METRICS) && ...
        isfield(BENCHMARK_METRICS,'sampleRate_Hz') && ...
        isfield(BENCHMARK_METRICS,'computationalCost')
    fprintf( ...
        'Benchmark metrics config: OK\n');
else
    fprintf( ...
        'Benchmark metrics config: MISSING\n');
end
if exist(estimator_plot_file, 'file')
    fprintf( ...
        'Estimator post-process:   OK\n');
else
    fprintf( ...
        'Estimator post-process:   MISSING\n');
end
if exist(trajectory_plot_file, 'file')
    fprintf( ...
        'Trajectory post-process:  OK\n');
else
    fprintf( ...
        'Trajectory post-process:  MISSING\n');
end
if exist(controller_plot_file, 'file')
    fprintf( ...
        'Controller post-process:  OK\n');
else
    fprintf( ...
        'Controller post-process:  MISSING\n');
end
if exist(mission_plot_file, 'file')
    fprintf( ...
        'Mission post-process:     OK\n');
else
    fprintf( ...
        'Mission post-process:     MISSING\n');
end
if exist(touchdown_plot_file, 'file')
    fprintf( ...
        'Touchdown diagnostics:    OK\n');
else
    fprintf( ...
        'Touchdown diagnostics:    MISSING\n');
end
if exist(model_file, 'file')
    fprintf( ...
        'Simulink model:           OK\n');
else
    fprintf( ...
        'Simulink model:           MISSING\n');
end
if exist(gui_file, 'file')
    fprintf( ...
        'Remote controller GUI:    OK\n');
else
    fprintf( ...
        'Remote controller GUI:    MISSING\n');
end
disp( ...
    '==============================================================');
disp(' ');
