WINDOW_BEFORE_TOUCHDOWN_S = ...
    2.0;
WINDOW_AFTER_TOUCHDOWN_S = ...
    2.0;
CONTACT_AGL_TOLERANCE_M = ...
    0.003;
STABLE_AGL_TOLERANCE_M = ...
    0.020;
STABLE_SPEED_M_S = ...
    0.15;
STABLE_VERTICAL_SPEED_M_S = ...
    0.08;
STABLE_ROLL_DEG = ...
    10;
STABLE_PITCH_DEG = ...
    10;
STABLE_ANGULAR_RATE_RAD_S = ...
    0.35;
STABLE_DURATION_S = ...
    0.50;
if ~exist('out','var')
    error( ...
        'QuadrotorFramework:MissingSimulationOutput', ...
        ['Simulation output "out" was not found. ', ...
         'Run UAV_Research_Environment first.']);
end
if ~isa(out,'Simulink.SimulationOutput')
    error( ...
        'QuadrotorFramework:InvalidSimulationOutput', ...
        '"out" must be a Simulink.SimulationOutput object.');
end
availableLogs = ...
    who(out);
requiredLogs = { ...
    'liveTelemetryLog', ...
    'trueStatesLog', ...
    'controlAxesLog', ...
    'omegaLog'};
for k = 1:numel(requiredLogs)
    if ~ismember( ...
            requiredLogs{k}, ...
            availableLogs)
        error( ...
            'QuadrotorFramework:MissingTouchdownLog', ...
            'Missing simulation output: out.%s', ...
            requiredLogs{k});
    end
end
LIVE = ...
    out.liveTelemetryLog;
TRUE = ...
    out.trueStatesLog;
CONTROL_AXES = ...
    out.controlAxesLog;
OMEGA_LOG = ...
    out.omegaLog;
[t,Telemetry] = ...
    extractSignalTouchdown( ...
        LIVE);
if size(Telemetry,2) < 14
    error( ...
        'QuadrotorFramework:InvalidLiveTelemetry', ...
        ['liveTelemetryLog must contain at least 14 columns. ', ...
         'Found %d.'], ...
        size(Telemetry,2));
end
t = ...
    double( ...
        t(:));
if numel(t) < 2 || ...
        any(~isfinite(t)) || ...
        any(diff(t) < 0)
    error( ...
        'QuadrotorFramework:InvalidTouchdownTime', ...
        ['liveTelemetryLog must contain a finite monotonically ', ...
         'nondecreasing time vector.']);
end
Phase = ...
    round( ...
        Telemetry(:,2));
MissionActive = ...
    Telemetry(:,3) > 0.5;
CGSComplete = ...
    Telemetry(:,4) > 0.5;
FlightMode = ...
    Telemetry(:,5);
Armed = ...
    Telemetry(:,6) > 0.5;
FlightMissionComplete = ...
    Telemetry(:,7) > 0.5;
Landed = ...
    Telemetry(:,8) > 0.5;
PositionRef = ...
    Telemetry(:,9:11);
[genericTelemetry,maxWaypointsTelemetry] = ...
    detectGenericTouchdownTelemetry( ...
        size(Telemetry,2));
if genericTelemetry
    NumWaypointsSignal = ...
        round( ...
            double( ...
                Telemetry(:,59)));
else
    NumWaypointsSignal = ...
        7 * ...
        ones( ...
            size(t));
    maxWaypointsTelemetry = ...
        7;
end
[tPosition,PositionTrueRaw] = ...
    extractBusFieldTouchdown( ...
        TRUE, ...
        {'Position'});
[tVelocity,VelocityTrueRaw] = ...
    extractBusFieldTouchdown( ...
        TRUE, ...
        {'Velocity'});
[tAcceleration,AccelerationTrueRaw] = ...
    extractBusFieldTouchdown( ...
        TRUE, ...
        {'Acceleration'});
[tEuler,EulerTrueRaw] = ...
    extractBusFieldTouchdown( ...
        TRUE, ...
        {'Attitude','Euler'});
[tAngularRate,AngularRateTrueRaw] = ...
    extractBusFieldTouchdown( ...
        TRUE, ...
        {'AngularRate'});
validateThreeColumnsTouchdown( ...
    PositionTrueRaw, ...
    'trueStatesLog.Position');
validateThreeColumnsTouchdown( ...
    VelocityTrueRaw, ...
    'trueStatesLog.Velocity');
validateThreeColumnsTouchdown( ...
    AccelerationTrueRaw, ...
    'trueStatesLog.Acceleration');
validateThreeColumnsTouchdown( ...
    EulerTrueRaw, ...
    'trueStatesLog.Attitude.Euler');
validateThreeColumnsTouchdown( ...
    AngularRateTrueRaw, ...
    'trueStatesLog.AngularRate');
PositionTrue = ...
    resampleMatrixTouchdown( ...
        tPosition, ...
        PositionTrueRaw, ...
        t);
VelocityTrue = ...
    resampleMatrixTouchdown( ...
        tVelocity, ...
        VelocityTrueRaw, ...
        t);
AccelerationTrue = ...
    resampleMatrixTouchdown( ...
        tAcceleration, ...
        AccelerationTrueRaw, ...
        t);
EulerTrue = ...
    resampleMatrixTouchdown( ...
        tEuler, ...
        EulerTrueRaw, ...
        t);
AngularRateTrue = ...
    resampleMatrixTouchdown( ...
        tAngularRate, ...
        AngularRateTrueRaw, ...
        t);
[tThrust,thrustRaw] = ...
    extractBusFieldTouchdown( ...
        CONTROL_AXES, ...
        {'thrustAxis'});
[tRollAxis,rollAxisRaw] = ...
    extractBusFieldTouchdown( ...
        CONTROL_AXES, ...
        {'rollAxis'});
[tPitchAxis,pitchAxisRaw] = ...
    extractBusFieldTouchdown( ...
        CONTROL_AXES, ...
        {'pitchAxis'});
[tYawAxis,yawAxisRaw] = ...
    extractBusFieldTouchdown( ...
        CONTROL_AXES, ...
        {'yawAxis'});
thrustAxis = ...
    resampleMatrixTouchdown( ...
        tThrust, ...
        thrustRaw, ...
        t);
rollAxis = ...
    resampleMatrixTouchdown( ...
        tRollAxis, ...
        rollAxisRaw, ...
        t);
pitchAxis = ...
    resampleMatrixTouchdown( ...
        tPitchAxis, ...
        pitchAxisRaw, ...
        t);
yawAxis = ...
    resampleMatrixTouchdown( ...
        tYawAxis, ...
        yawAxisRaw, ...
        t);
thrustAxis = ...
    thrustAxis(:,1);
rollAxis = ...
    rollAxis(:,1);
pitchAxis = ...
    pitchAxis(:,1);
yawAxis = ...
    yawAxis(:,1);
[tOmega,OmegaRaw] = ...
    extractSignalTouchdown( ...
        OMEGA_LOG);
if size(OmegaRaw,2) ~= 4
    error( ...
        'QuadrotorFramework:InvalidOmegaLog', ...
        'omegaLog must contain [omega1 omega2 omega3 omega4].');
end
Omega = ...
    resampleMatrixTouchdown( ...
        tOmega, ...
        OmegaRaw, ...
        t);
previousPhase = [ ...
    NaN; ...
    Phase(1:end-1)];
missionStartIndices = ...
    find( ...
        Phase == 1 & ...
        previousPhase ~= 1);
if isempty(missionStartIndices)
    error( ...
        'QuadrotorFramework:NoMissionDetected', ...
        'No TAKEOFF phase transition was detected.');
end
firstMissionStartIdx = ...
    missionStartIndices(1);
preflightIndices = ...
    1:max(1,firstMissionStartIdx-1);
preflightDown = ...
    PositionTrue( ...
        preflightIndices, ...
        3);
preflightDown = ...
    preflightDown( ...
        isfinite(preflightDown));
if isempty(preflightDown)
    error( ...
        'QuadrotorFramework:GroundDatumUnavailable', ...
        'Unable to infer the physical ground datum.');
end
groundCGDown_m = ...
    median( ...
        preflightDown);
AltitudeAGL_m = ...
    groundCGDown_m - ...
    PositionTrue(:,3);
ReferenceAltitudeAGL_m = ...
    groundCGDown_m - ...
    PositionRef(:,3);
Speed_m_s = ...
    sqrt( ...
        sum( ...
            VelocityTrue.^2, ...
            2));
VerticalVelocityDown_m_s = ...
    VelocityTrue(:,3);
AccelerationMagnitude_m_s2 = ...
    sqrt( ...
        sum( ...
            AccelerationTrue.^2, ...
            2));
VerticalAccelerationDown_m_s2 = ...
    AccelerationTrue(:,3);
Roll_deg = ...
    rad2deg( ...
        EulerTrue(:,1));
Pitch_deg = ...
    rad2deg( ...
        EulerTrue(:,2));
Yaw_deg = ...
    rad2deg( ...
        EulerTrue(:,3));
AngularRateMagnitude_rad_s = ...
    sqrt( ...
        sum( ...
            AngularRateTrue.^2, ...
            2));
TrajectoryIDValue = ...
    touchdownBaseScalar( ...
        'TRAJECTORY_ID', ...
        NaN);
TrajectoryNameValue = ...
    touchdownTrajectoryName();
UAVModelValue = ...
    touchdownBaseScalar( ...
        'UAV_MODEL', ...
        NaN);
numberOfMissions = ...
    numel( ...
        missionStartIndices);
Mission = ...
    (1:numberOfMissions).';
UAVModel = ...
    repmat( ...
        UAVModelValue, ...
        numberOfMissions, ...
        1);
TrajectoryID = ...
    repmat( ...
        TrajectoryIDValue, ...
        numberOfMissions, ...
        1);
TrajectoryName = ...
    repmat( ...
        string(TrajectoryNameValue), ...
        numberOfMissions, ...
        1);
NumWaypoints = ...
    NaN(numberOfMissions,1);
LandingPhase = ...
    NaN(numberOfMissions,1);
CompletePhase = ...
    NaN(numberOfMissions,1);
AbortedPhase = ...
    NaN(numberOfMissions,1);
FailsafeAborted = ...
    false(numberOfMissions,1);
LandingToTouchdown_s = ...
    NaN(numberOfMissions,1);
LandingToLandedArmed_s = ...
    NaN(numberOfMissions,1);
LandingStartTime_s = ...
    NaN(numberOfMissions,1);
TouchdownTime_s = ...
    NaN(numberOfMissions,1);
StableTime_s = ...
    NaN(numberOfMissions,1);
LandedArmedTime_s = ...
    NaN(numberOfMissions,1);
LandingDuration_s = ...
    NaN(numberOfMissions,1);
TouchdownToStable_s = ...
    NaN(numberOfMissions,1);
TouchdownToLandedArmed_s = ...
    NaN(numberOfMissions,1);
VerticalContactVelocity_m_s = ...
    NaN(numberOfMissions,1);
ContactSpeed_m_s = ...
    NaN(numberOfMissions,1);
PeakVerticalAcceleration_m_s2 = ...
    NaN(numberOfMissions,1);
PeakTotalAcceleration_m_s2 = ...
    NaN(numberOfMissions,1);
PeakAbsThrustAxis = ...
    NaN(numberOfMissions,1);
PeakAbsRollAxis = ...
    NaN(numberOfMissions,1);
PeakAbsPitchAxis = ...
    NaN(numberOfMissions,1);
PeakAbsYawAxis = ...
    NaN(numberOfMissions,1);
PeakAngularRate_rad_s = ...
    NaN(numberOfMissions,1);
PeakMotorSpeed_rad_s = ...
    NaN(numberOfMissions,1);
GroundPenetration_m = ...
    NaN(numberOfMissions,1);
BounceHeight_m = ...
    NaN(numberOfMissions,1);
TouchdownDetected = ...
    false(numberOfMissions,1);
StableDetected = ...
    false(numberOfMissions,1);
LandedArmedDetected = ...
    false(numberOfMissions,1);
for missionIndex = 1:numberOfMissions
    missionStartIdx = ...
        missionStartIndices(missionIndex);
    if missionIndex < numberOfMissions
        missionEndIdx = ...
            missionStartIndices(missionIndex+1) - 1;
    else
        missionEndIdx = ...
            numel(t);
    end
    missionIndices = ...
        missionStartIdx:missionEndIdx;
    missionNumWaypoints = ...
        NumWaypointsSignal(missionStartIdx);
    if ~isfinite(missionNumWaypoints) || ...
            missionNumWaypoints < 3
        missionNumWaypoints = ...
            touchdownWorkspaceNumWaypoints();
    end
    if ~isfinite(missionNumWaypoints) || ...
            missionNumWaypoints < 3
        missionNumWaypoints = ...
            3;
    end
    missionNumWaypoints = ...
        round( ...
            missionNumWaypoints);
    NumWaypoints(missionIndex) = ...
        missionNumWaypoints;
    landingPhase = ...
        2*missionNumWaypoints - ...
        3;
    completePhase = ...
        2*missionNumWaypoints - ...
        2;
    abortedPhase = ...
        2*missionNumWaypoints - ...
        1;
    LandingPhase(missionIndex) = ...
        landingPhase;
    CompletePhase(missionIndex) = ...
        completePhase;
    AbortedPhase(missionIndex) = ...
        abortedPhase;
    FailsafeAborted(missionIndex) = ...
        any( ...
            Phase(missionIndices) == ...
            abortedPhase);
    relativeLandingStart = ...
        find( ...
            Phase(missionIndices) == landingPhase, ...
            1, ...
            'first');
    if isempty(relativeLandingStart)
        warning( ...
            'Mission %d: LAND phase was not detected.', ...
            missionIndex);
        continue;
    end
    landingStartIdx = ...
        missionIndices(relativeLandingStart);
    LandingStartTime_s(missionIndex) = ...
        t(landingStartIdx);
    landingIndices = ...
        landingStartIdx:missionEndIdx;
    nearGround = ...
        AltitudeAGL_m(landingIndices) <= ...
        CONTACT_AGL_TOLERANCE_M;
    relativeTouchdown = ...
        firstPersistentTrueTouchdown( ...
            nearGround, ...
            2);
    if isempty(relativeTouchdown)
        warning( ...
            ['Mission %d: no physical touchdown was detected using ', ...
             'AGL <= %.4f m.'], ...
            missionIndex, ...
            CONTACT_AGL_TOLERANCE_M);
        continue;
    end
    touchdownIdx = ...
        landingIndices(relativeTouchdown);
    TouchdownDetected(missionIndex) = ...
        true;
    TouchdownTime_s(missionIndex) = ...
        t(touchdownIdx);
    LandingDuration_s(missionIndex) = ...
        t(touchdownIdx) - ...
        t(landingStartIdx);
    LandingToTouchdown_s(missionIndex) = ...
        LandingDuration_s(missionIndex);
    VerticalContactVelocity_m_s(missionIndex) = ...
        VerticalVelocityDown_m_s(touchdownIdx);
    ContactSpeed_m_s(missionIndex) = ...
        Speed_m_s(touchdownIdx);
    stableCondition = ...
        AltitudeAGL_m <= STABLE_AGL_TOLERANCE_M & ...
        Speed_m_s <= STABLE_SPEED_M_S & ...
        abs(VerticalVelocityDown_m_s) <= STABLE_VERTICAL_SPEED_M_S & ...
        abs(Roll_deg) <= STABLE_ROLL_DEG & ...
        abs(Pitch_deg) <= STABLE_PITCH_DEG & ...
        AngularRateMagnitude_rad_s <= STABLE_ANGULAR_RATE_RAD_S;
    postTouchdownIndicesForStability = ...
        touchdownIdx:missionEndIdx;
    postTouchdownStableCondition = ...
        stableCondition( ...
            postTouchdownIndicesForStability);
    postTouchdownTimesForStability = ...
        t( ...
            postTouchdownIndicesForStability);
    relativeStable = ...
        firstPersistentTrueForDurationTouchdown( ...
            postTouchdownStableCondition, ...
            postTouchdownTimesForStability, ...
            STABLE_DURATION_S);
    if ~isempty(relativeStable)
        stableIdx = ...
            touchdownIdx + ...
            relativeStable - ...
            1;
        StableDetected(missionIndex) = ...
            true;
        StableTime_s(missionIndex) = ...
            t(stableIdx);
        TouchdownToStable_s(missionIndex) = ...
            t(stableIdx) - ...
            t(touchdownIdx);
    else
        stableIdx = ...
            NaN;
    end
    postTouchdownIndices = ...
        touchdownIdx:missionEndIdx;
    relativeLandedArmed = ...
        find( ...
            Armed(postTouchdownIndices) & ...
            Landed(postTouchdownIndices) & ...
            round(FlightMode(postTouchdownIndices)) == 2, ...
            1, ...
            'first');
    if isempty(relativeLandedArmed)
        relativeLandedArmed = ...
            find( ...
                Armed(postTouchdownIndices) & ...
                Landed(postTouchdownIndices), ...
                1, ...
                'first');
    end
    if ~isempty(relativeLandedArmed)
        landedArmedIdx = ...
            postTouchdownIndices(relativeLandedArmed);
        LandedArmedDetected(missionIndex) = ...
            true;
        LandedArmedTime_s(missionIndex) = ...
            t(landedArmedIdx);
        TouchdownToLandedArmed_s(missionIndex) = ...
            t(landedArmedIdx) - ...
            t(touchdownIdx);
        LandingToLandedArmed_s(missionIndex) = ...
            t(landedArmedIdx) - ...
            t(landingStartIdx);
    else
        landedArmedIdx = ...
            NaN;
    end
    windowStartTime = ...
        max( ...
            t(landingStartIdx), ...
            t(touchdownIdx) - ...
            WINDOW_BEFORE_TOUCHDOWN_S);
    windowEndTime = ...
        min( ...
            t(missionEndIdx), ...
            t(touchdownIdx) + ...
            WINDOW_AFTER_TOUCHDOWN_S);
    windowIndices = ...
        find( ...
            t >= windowStartTime & ...
            t <= windowEndTime);
    PeakVerticalAcceleration_m_s2(missionIndex) = ...
        finiteMaximumTouchdown( ...
            abs( ...
                VerticalAccelerationDown_m_s2(windowIndices)));
    PeakTotalAcceleration_m_s2(missionIndex) = ...
        finiteMaximumTouchdown( ...
            AccelerationMagnitude_m_s2(windowIndices));
    PeakAbsThrustAxis(missionIndex) = ...
        finiteMaximumTouchdown( ...
            abs( ...
                thrustAxis(windowIndices)));
    PeakAbsRollAxis(missionIndex) = ...
        finiteMaximumTouchdown( ...
            abs( ...
                rollAxis(windowIndices)));
    PeakAbsPitchAxis(missionIndex) = ...
        finiteMaximumTouchdown( ...
            abs( ...
                pitchAxis(windowIndices)));
    PeakAbsYawAxis(missionIndex) = ...
        finiteMaximumTouchdown( ...
            abs( ...
                yawAxis(windowIndices)));
    PeakAngularRate_rad_s(missionIndex) = ...
        finiteMaximumTouchdown( ...
            AngularRateMagnitude_rad_s(windowIndices));
    PeakMotorSpeed_rad_s(missionIndex) = ...
        finiteMaximumTouchdown( ...
            Omega(windowIndices,:));
    if isfinite(landedArmedIdx)
        contactEndIdx = ...
            landedArmedIdx;
    else
        contactEndIdx = ...
            missionEndIdx;
    end
    contactIndices = ...
        touchdownIdx:contactEndIdx;
    GroundPenetration_m(missionIndex) = ...
        max( ...
            0, ...
            -finiteMinimumTouchdown( ...
                AltitudeAGL_m(contactIndices)));
    BounceHeight_m(missionIndex) = ...
        max( ...
            0, ...
            finiteMaximumTouchdown( ...
                AltitudeAGL_m(contactIndices)));
    figureTag = sprintf( ...
        'UAV_TOUCHDOWN_11_M%d', ...
        missionIndex);
    delete( ...
        findall( ...
            groot, ...
            'Type','figure', ...
            'Tag',figureTag));
    fig11 = figure( ...
        'Name',sprintf( ...
            '11 - Touchdown Diagnostics - Mission %d', ...
            missionIndex), ...
        'Tag',figureTag, ...
        'Color','w');
    tl11 = tiledlayout( ...
        fig11, ...
        4, ...
        2, ...
        'TileSpacing','compact', ...
        'Padding','compact');
    title( ...
        tl11, ...
        sprintf( ...
            'Touchdown Diagnostics - Mission %d - %s', ...
            missionIndex, ...
            char(TrajectoryName(missionIndex))));
    ax1 = ...
        nexttile( ...
            tl11);
    hold( ...
        ax1, ...
        'on');
    plot( ...
        ax1, ...
        t(windowIndices), ...
        AltitudeAGL_m(windowIndices), ...
        'LineWidth',1.5, ...
        'DisplayName','TRUE AGL');
    plot( ...
        ax1, ...
        t(windowIndices), ...
        ReferenceAltitudeAGL_m(windowIndices), ...
        '--', ...
        'LineWidth',1.3, ...
        'DisplayName','Reference AGL');
    yline( ...
        ax1, ...
        0, ...
        ':', ...
        'HandleVisibility','off');
    addTouchdownEventLines( ...
        ax1, ...
        LandingStartTime_s(missionIndex), ...
        TouchdownTime_s(missionIndex), ...
        StableTime_s(missionIndex), ...
        LandedArmedTime_s(missionIndex));
    grid(ax1,'on');
    box(ax1,'on');
    ylabel( ...
        ax1, ...
        'AGL [m]');
    title( ...
        ax1, ...
        'Altitude');
    legend( ...
        ax1, ...
        'Location','best');
    ax2 = ...
        nexttile( ...
            tl11);
    hold( ...
        ax2, ...
        'on');
    plot( ...
        ax2, ...
        t(windowIndices), ...
        VerticalVelocityDown_m_s(windowIndices), ...
        'LineWidth',1.5, ...
        'DisplayName','V_D');
    yline( ...
        ax2, ...
        0, ...
        ':', ...
        'HandleVisibility','off');
    addTouchdownEventLines( ...
        ax2, ...
        LandingStartTime_s(missionIndex), ...
        TouchdownTime_s(missionIndex), ...
        StableTime_s(missionIndex), ...
        LandedArmedTime_s(missionIndex));
    grid(ax2,'on');
    box(ax2,'on');
    ylabel( ...
        ax2, ...
        'V_D [m/s]');
    title( ...
        ax2, ...
        sprintf( ...
            'Vertical Velocity - Contact = %.3f m/s', ...
            VerticalContactVelocity_m_s(missionIndex)));
    ax3 = ...
        nexttile( ...
            tl11);
    hold( ...
        ax3, ...
        'on');
    plot( ...
        ax3, ...
        t(windowIndices), ...
        AccelerationTrue(windowIndices,1), ...
        'LineWidth',1.1, ...
        'DisplayName','a_N');
    plot( ...
        ax3, ...
        t(windowIndices), ...
        AccelerationTrue(windowIndices,2), ...
        'LineWidth',1.1, ...
        'DisplayName','a_E');
    plot( ...
        ax3, ...
        t(windowIndices), ...
        AccelerationTrue(windowIndices,3), ...
        'LineWidth',1.3, ...
        'DisplayName','a_D');
    addTouchdownEventLines( ...
        ax3, ...
        LandingStartTime_s(missionIndex), ...
        TouchdownTime_s(missionIndex), ...
        StableTime_s(missionIndex), ...
        LandedArmedTime_s(missionIndex));
    grid(ax3,'on');
    box(ax3,'on');
    ylabel( ...
        ax3, ...
        'Acceleration [m/s^2]');
    title( ...
        ax3, ...
        'TRUE Acceleration');
    legend( ...
        ax3, ...
        'Location','best');
    ax4 = ...
        nexttile( ...
            tl11);
    hold( ...
        ax4, ...
        'on');
    plot( ...
        ax4, ...
        t(windowIndices), ...
        thrustAxis(windowIndices), ...
        'LineWidth',1.2, ...
        'DisplayName','thrustAxis');
    plot( ...
        ax4, ...
        t(windowIndices), ...
        rollAxis(windowIndices), ...
        'LineWidth',1.2, ...
        'DisplayName','rollAxis');
    plot( ...
        ax4, ...
        t(windowIndices), ...
        pitchAxis(windowIndices), ...
        'LineWidth',1.2, ...
        'DisplayName','pitchAxis');
    plot( ...
        ax4, ...
        t(windowIndices), ...
        yawAxis(windowIndices), ...
        'LineWidth',1.2, ...
        'DisplayName','yawAxis');
    yline( ...
        ax4, ...
        0, ...
        ':', ...
        'HandleVisibility','off');
    addTouchdownEventLines( ...
        ax4, ...
        LandingStartTime_s(missionIndex), ...
        TouchdownTime_s(missionIndex), ...
        StableTime_s(missionIndex), ...
        LandedArmedTime_s(missionIndex));
    grid(ax4,'on');
    box(ax4,'on');
    ylabel( ...
        ax4, ...
        'Control axis');
    title( ...
        ax4, ...
        'Control Commands');
    legend( ...
        ax4, ...
        'Location','best');
    ax5 = ...
        nexttile( ...
            tl11);
    hold( ...
        ax5, ...
        'on');
    plot( ...
        ax5, ...
        t(windowIndices), ...
        AngularRateTrue(windowIndices,1), ...
        'LineWidth',1.2, ...
        'DisplayName','p');
    plot( ...
        ax5, ...
        t(windowIndices), ...
        AngularRateTrue(windowIndices,2), ...
        'LineWidth',1.2, ...
        'DisplayName','q');
    plot( ...
        ax5, ...
        t(windowIndices), ...
        AngularRateTrue(windowIndices,3), ...
        'LineWidth',1.2, ...
        'DisplayName','r');
    yline( ...
        ax5, ...
        0, ...
        ':', ...
        'HandleVisibility','off');
    addTouchdownEventLines( ...
        ax5, ...
        LandingStartTime_s(missionIndex), ...
        TouchdownTime_s(missionIndex), ...
        StableTime_s(missionIndex), ...
        LandedArmedTime_s(missionIndex));
    grid(ax5,'on');
    box(ax5,'on');
    ylabel( ...
        ax5, ...
        'Rate [rad/s]');
    title( ...
        ax5, ...
        'TRUE Angular Rates');
    legend( ...
        ax5, ...
        'Location','best');
    ax6 = ...
        nexttile( ...
            tl11);
    hold( ...
        ax6, ...
        'on');
    plot( ...
        ax6, ...
        t(windowIndices), ...
        Omega(windowIndices,1), ...
        'LineWidth',1.1, ...
        'DisplayName','\omega_1');
    plot( ...
        ax6, ...
        t(windowIndices), ...
        Omega(windowIndices,2), ...
        'LineWidth',1.1, ...
        'DisplayName','\omega_2');
    plot( ...
        ax6, ...
        t(windowIndices), ...
        Omega(windowIndices,3), ...
        'LineWidth',1.1, ...
        'DisplayName','\omega_3');
    plot( ...
        ax6, ...
        t(windowIndices), ...
        Omega(windowIndices,4), ...
        'LineWidth',1.1, ...
        'DisplayName','\omega_4');
    addTouchdownEventLines( ...
        ax6, ...
        LandingStartTime_s(missionIndex), ...
        TouchdownTime_s(missionIndex), ...
        StableTime_s(missionIndex), ...
        LandedArmedTime_s(missionIndex));
    grid(ax6,'on');
    box(ax6,'on');
    ylabel( ...
        ax6, ...
        '\omega [rad/s]');
    title( ...
        ax6, ...
        'Motor Speeds');
    legend( ...
        ax6, ...
        'Location','best');
    ax7 = ...
        nexttile( ...
            tl11);
    yyaxis( ...
        ax7, ...
        'left');
    stairs( ...
        ax7, ...
        t(windowIndices), ...
        Phase(windowIndices), ...
        'LineWidth',1.4, ...
        'DisplayName','Phase');
    ylabel( ...
        ax7, ...
        'Mission phase');
    phaseTicks = ...
        [ ...
            landingPhase, ...
            completePhase];
    phaseLabels = { ...
        'LAND', ...
        'COMPLETE'};
    if FailsafeAborted(missionIndex)
        phaseTicks(end+1) = ...
            abortedPhase;
        phaseLabels{end+1} = ...
            'ABORT';
    end
    ylim( ...
        ax7, ...
        [ ...
            min(phaseTicks)-0.5, ...
            max(phaseTicks)+0.5]);
    yticks( ...
        ax7, ...
        phaseTicks);
    yticklabels( ...
        ax7, ...
        phaseLabels);
    yyaxis( ...
        ax7, ...
        'right');
    hold( ...
        ax7, ...
        'on');
    stairs( ...
        ax7, ...
        t(windowIndices), ...
        double(Landed(windowIndices)), ...
        'LineWidth',1.2, ...
        'DisplayName','Landed');
    stairs( ...
        ax7, ...
        t(windowIndices), ...
        double(Armed(windowIndices)), ...
        '--', ...
        'LineWidth',1.1, ...
        'DisplayName','Armed');
    stairs( ...
        ax7, ...
        t(windowIndices), ...
        double(FlightMissionComplete(windowIndices)), ...
        ':', ...
        'LineWidth',1.2, ...
        'DisplayName','FM Complete');
    ylabel( ...
        ax7, ...
        'Logic');
    ylim( ...
        ax7, ...
        [-0.1 1.1]);
    addTouchdownEventLines( ...
        ax7, ...
        LandingStartTime_s(missionIndex), ...
        TouchdownTime_s(missionIndex), ...
        StableTime_s(missionIndex), ...
        LandedArmedTime_s(missionIndex));
    grid(ax7,'on');
    box(ax7,'on');
    xlabel( ...
        ax7, ...
        'Time [s]');
    title( ...
        ax7, ...
        'LANDING \rightarrow LANDED ARMED');
    legend( ...
        ax7, ...
        'Location','best');
    ax8 = ...
        nexttile( ...
            tl11);
    axis( ...
        ax8, ...
        'off');
    summaryLines = { ...
        sprintf('Trajectory: %s', ...
            char(TrajectoryName(missionIndex))), ...
        sprintf('NumWaypoints / LAND phase: %d / %d', ...
            missionNumWaypoints, ...
            landingPhase), ...
        sprintf('t_1 LAND start: %.3f s', ...
            LandingStartTime_s(missionIndex)), ...
        sprintf('t_2 touchdown: %.3f s', ...
            TouchdownTime_s(missionIndex)), ...
        sprintf('V_D at contact: %.4f m/s', ...
            VerticalContactVelocity_m_s(missionIndex)), ...
        sprintf('Total speed at contact: %.4f m/s', ...
            ContactSpeed_m_s(missionIndex)), ...
        sprintf('Peak |a_D|: %.2f m/s^2', ...
            PeakVerticalAcceleration_m_s2(missionIndex)), ...
        sprintf('Peak ||a||: %.2f m/s^2', ...
            PeakTotalAcceleration_m_s2(missionIndex)), ...
        sprintf('Peak |rollAxis| / |pitchAxis|: %.3f / %.3f', ...
            PeakAbsRollAxis(missionIndex), ...
            PeakAbsPitchAxis(missionIndex)), ...
        sprintf('Ground penetration: %.4f m', ...
            GroundPenetration_m(missionIndex)), ...
        sprintf('Bounce height: %.4f m', ...
            BounceHeight_m(missionIndex)), ...
        sprintf('t_3 stable: %s', ...
            formatTimeTouchdown( ...
                StableTime_s(missionIndex))), ...
        sprintf('t_4 LANDED ARMED: %s', ...
            formatTimeTouchdown( ...
                LandedArmedTime_s(missionIndex))), ...
        sprintf('Touchdown -> LANDED ARMED: %s s', ...
            formatNumberTouchdown( ...
                TouchdownToLandedArmed_s(missionIndex)))};
    text( ...
        ax8, ...
        0.02, ...
        0.98, ...
        summaryLines, ...
        'Units','normalized', ...
        'VerticalAlignment','top', ...
        'FontName','Consolas', ...
        'FontSize',10);
    title( ...
        ax8, ...
        'Diagnostic Summary');
    timeAxes = [ ...
        ax1, ...
        ax2, ...
        ax3, ...
        ax4, ...
        ax5, ...
        ax6, ...
        ax7];
    for ax = timeAxes
        xlim( ...
            ax, ...
            [windowStartTime windowEndTime]);
    end
end
TouchdownMetrics = ...
    table( ...
        Mission, ...
        UAVModel, ...
        TrajectoryID, ...
        TrajectoryName, ...
        NumWaypoints, ...
        LandingPhase, ...
        CompletePhase, ...
        AbortedPhase, ...
        FailsafeAborted, ...
        TouchdownDetected, ...
        StableDetected, ...
        LandedArmedDetected, ...
        LandingStartTime_s, ...
        TouchdownTime_s, ...
        StableTime_s, ...
        LandedArmedTime_s, ...
        LandingDuration_s, ...
        LandingToTouchdown_s, ...
        TouchdownToStable_s, ...
        TouchdownToLandedArmed_s, ...
        LandingToLandedArmed_s, ...
        VerticalContactVelocity_m_s, ...
        ContactSpeed_m_s, ...
        PeakVerticalAcceleration_m_s2, ...
        PeakTotalAcceleration_m_s2, ...
        PeakAbsThrustAxis, ...
        PeakAbsRollAxis, ...
        PeakAbsPitchAxis, ...
        PeakAbsYawAxis, ...
        PeakAngularRate_rad_s, ...
        PeakMotorSpeed_rad_s, ...
        GroundPenetration_m, ...
        BounceHeight_m);
fprintf('\n');
fprintf( ...
    '============================================================\n');
fprintf( ...
    ' UAV GENERIC TOUCHDOWN / CONTACT DIAGNOSTICS\n');
fprintf( ...
    '============================================================\n');
fprintf( ...
    'Physical ground CG Down datum: %.6f m\n', ...
    groundCGDown_m);
fprintf( ...
    'Contact AGL tolerance:         %.4f m\n', ...
    CONTACT_AGL_TOLERANCE_M);
fprintf( ...
    'Stable duration requirement:   %.3f s\n', ...
    STABLE_DURATION_S);
fprintf( ...
    'Detected missions:             %d\n', ...
    numberOfMissions);
fprintf( ...
    '============================================================\n\n');
disp( ...
    TouchdownMetrics);
fprintf('\n');
for missionIndex = 1:numberOfMissions
    fprintf( ...
        'Mission %d — %s\n', ...
        missionIndex, ...
        char(TrajectoryName(missionIndex)));
    fprintf( ...
        '  NumWaypoints / LAND phase:     %d / %d\n', ...
        round(NumWaypoints(missionIndex)), ...
        round(LandingPhase(missionIndex)));
    fprintf( ...
        '  Failsafe / aborted:            %s\n', ...
        logicalToTextTouchdown( ...
            FailsafeAborted(missionIndex)));
    fprintf( ...
        '  LAND start:                    %s s\n', ...
        formatNumberTouchdown( ...
            LandingStartTime_s(missionIndex)));
    fprintf( ...
        '  Physical touchdown:            %s s\n', ...
        formatNumberTouchdown( ...
            TouchdownTime_s(missionIndex)));
    fprintf( ...
        '  Vertical contact velocity V_D: %s m/s\n', ...
        formatNumberTouchdown( ...
            VerticalContactVelocity_m_s(missionIndex)));
    fprintf( ...
        '  Total contact speed:           %s m/s\n', ...
        formatNumberTouchdown( ...
            ContactSpeed_m_s(missionIndex)));
    fprintf( ...
        '  Peak |vertical acceleration|:  %s m/s^2\n', ...
        formatNumberTouchdown( ...
            PeakVerticalAcceleration_m_s2(missionIndex)));
    fprintf( ...
        '  Peak total acceleration:       %s m/s^2\n', ...
        formatNumberTouchdown( ...
            PeakTotalAcceleration_m_s2(missionIndex)));
    fprintf( ...
        '  Peak |thrustAxis|:             %s\n', ...
        formatNumberTouchdown( ...
            PeakAbsThrustAxis(missionIndex)));
    fprintf( ...
        '  Peak |rollAxis|:               %s\n', ...
        formatNumberTouchdown( ...
            PeakAbsRollAxis(missionIndex)));
    fprintf( ...
        '  Peak |pitchAxis|:              %s\n', ...
        formatNumberTouchdown( ...
            PeakAbsPitchAxis(missionIndex)));
    fprintf( ...
        '  Peak |yawAxis|:                %s\n', ...
        formatNumberTouchdown( ...
            PeakAbsYawAxis(missionIndex)));
    fprintf( ...
        '  Peak angular-rate norm:        %s rad/s\n', ...
        formatNumberTouchdown( ...
            PeakAngularRate_rad_s(missionIndex)));
    fprintf( ...
        '  Peak motor speed:              %s rad/s\n', ...
        formatNumberTouchdown( ...
            PeakMotorSpeed_rad_s(missionIndex)));
    fprintf( ...
        '  Maximum ground penetration:    %s m\n', ...
        formatNumberTouchdown( ...
            GroundPenetration_m(missionIndex)));
    fprintf( ...
        '  Maximum bounce height:         %s m\n', ...
        formatNumberTouchdown( ...
            BounceHeight_m(missionIndex)));
    fprintf( ...
        '  Stable condition:              %s s\n', ...
        formatNumberTouchdown( ...
            StableTime_s(missionIndex)));
    fprintf( ...
        '  LANDED ARMED:                  %s s\n', ...
        formatNumberTouchdown( ...
            LandedArmedTime_s(missionIndex)));
    fprintf( ...
        '  Touchdown -> LANDED ARMED:     %s s\n', ...
        formatNumberTouchdown( ...
            TouchdownToLandedArmed_s(missionIndex)));
    fprintf( ...
        '  LAND -> LANDED ARMED:          %s s\n', ...
        formatNumberTouchdown( ...
            LandingToLandedArmed_s(missionIndex)));
    fprintf('\n');
end
fprintf( ...
    '============================================================\n');
fprintf( ...
    ['Interpretation guide:\n', ...
     '  1) Large V_D at contact -> inspect LAND descent command.\n', ...
     '  2) Small V_D but huge acceleration -> inspect contact stiffness/damping.\n', ...
     '  3) Spike mainly after touchdown -> inspect control/mode transition.\n', ...
     '  4) Large penetration/bounce -> inspect contact parameters.\n', ...
     '  5) Long touchdown->LANDED_ARMED delay -> inspect Landed Detector.\n', ...
     '  6) ABORT detected -> interpret touchdown values as a failed-run diagnostic.\n']);
fprintf( ...
    '============================================================\n');
function [genericTelemetry,maxWaypoints] = ...
        detectGenericTouchdownTelemetry(numberOfColumns)
    genericTelemetry = ...
        numberOfColumns >= (59 + 4*3) && ...
        mod(numberOfColumns-59,4) == 0;
    if genericTelemetry
        maxWaypoints = ...
            (numberOfColumns-59) / ...
            4;
    elseif numberOfColumns == 58
        maxWaypoints = ...
            7;
    else
        maxWaypoints = ...
            NaN;
    end
end
function numWaypoints = touchdownWorkspaceNumWaypoints()
    numWaypoints = ...
        NaN;
    try
        if evalin( ...
                'base', ...
                'exist(''TRAJECTORY_CONFIG'',''var'')')
            configuration = ...
                evalin( ...
                    'base', ...
                    'TRAJECTORY_CONFIG');
            if isstruct(configuration) && ...
                    isfield( ...
                        configuration, ...
                        'selectedNumWaypoints')
                candidate = ...
                    double( ...
                        configuration.selectedNumWaypoints);
                if isscalar(candidate) && ...
                        isfinite(candidate) && ...
                        candidate >= 3 && ...
                        abs(candidate-round(candidate)) < 1e-9
                    numWaypoints = ...
                        round(candidate);
                end
            end
        end
    catch
    end
end
function value = touchdownBaseScalar(variableName,defaultValue)
    value = ...
        defaultValue;
    try
        exists = ...
            evalin( ...
                'base', ...
                sprintf( ...
                    'exist(''%s'',''var'')', ...
                    variableName));
        if ~exists
            return;
        end
        candidate = ...
            double( ...
                evalin( ...
                    'base', ...
                    variableName));
        if isscalar(candidate) && ...
                isfinite(candidate)
            value = ...
                candidate;
        end
    catch
    end
end
function name = touchdownTrajectoryName()
    name = ...
        "Unknown";
    try
        if evalin( ...
                'base', ...
                'exist(''TRAJECTORY'',''var'')')
            trajectory = ...
                evalin( ...
                    'base', ...
                    'TRAJECTORY');
            if isstruct(trajectory) && ...
                    isfield(trajectory,'name')
                candidate = ...
                    string( ...
                        trajectory.name);
                if isscalar(candidate) && ...
                        ~ismissing(candidate) && ...
                        strlength(candidate) > 0
                    name = ...
                        candidate;
                end
            end
        end
    catch
    end
end
function firstIndex = firstPersistentTrueForDurationTouchdown( ...
    logicalVector, ...
    timeVector, ...
    durationRequired_s)
    logicalVector = ...
        logical( ...
            logicalVector(:));
    timeVector = ...
        double( ...
            timeVector(:));
    firstIndex = ...
        [];
    if isempty(logicalVector) || ...
            numel(logicalVector) ~= numel(timeVector) || ...
            ~isfinite(durationRequired_s) || ...
            durationRequired_s < 0
        return;
    end
    if any(~isfinite(timeVector)) || ...
            any(diff(timeVector) < 0)
        return;
    end
    runStart = ...
        0;
    for k = 1:numel(logicalVector)
        if logicalVector(k)
            if runStart == 0
                runStart = ...
                    k;
            end
            if timeVector(k) - ...
                    timeVector(runStart) >= ...
                    durationRequired_s
                firstIndex = ...
                    runStart;
                return;
            end
        else
            runStart = ...
                0;
        end
    end
end
function text = logicalToTextTouchdown(value)
    if logical(value)
        text = ...
            'YES';
    else
        text = ...
            'NO';
    end
end
function [t,X] = extractSignalTouchdown(signal)
    if isa( ...
            signal, ...
            'Simulink.SimulationData.Signal')
        signal = ...
            signal.Values;
    end
    if ~isa( ...
            signal, ...
            'timeseries')
        error( ...
            'Expected a logged timeseries signal.');
    end
    t = ...
        signal.Time(:);
    X = ...
        timeseriesDataToMatrixTouchdown( ...
            signal.Data, ...
            numel(t));
end
function [t,X] = extractBusFieldTouchdown(bus,path)
    value = ...
        bus;
    for k = 1:numel(path)
        fieldName = ...
            path{k};
        if isa( ...
                value, ...
                'Simulink.SimulationData.Signal')
            value = ...
                value.Values;
        end
        if isstruct(value)
            if ~isfield( ...
                    value, ...
                    fieldName)
                error( ...
                    'Logged bus does not contain field "%s".', ...
                    fieldName);
            end
            value = ...
                value.(fieldName);
        elseif isobject(value)
            if ~isprop( ...
                    value, ...
                    fieldName)
                error( ...
                    'Logged bus does not contain field "%s".', ...
                    fieldName);
            end
            value = ...
                value.(fieldName);
        else
            error( ...
                'Unable to access logged bus field "%s".', ...
                fieldName);
        end
    end
    [t,X] = ...
        extractSignalTouchdown( ...
            value);
end
function validateThreeColumnsTouchdown(X,name)
    if size(X,2) ~= 3
        error( ...
            'QuadrotorFramework:InvalidTouchdownSignal', ...
            '%s must contain exactly three columns.', ...
            name);
    end
end
function Xquery = resampleMatrixTouchdown(tSource,XSource,tQuery)
    tSource = ...
        double( ...
            tSource(:));
    tQuery = ...
        double( ...
            tQuery(:));
    XSource = ...
        double(XSource);
    if size(XSource,1) ~= numel(tSource)
        error( ...
            'Source matrix row count does not match source time vector.');
    end
    if numel(tSource) == numel(tQuery) && ...
            all(abs(tSource-tQuery) <= 1e-12)
        Xquery = ...
            XSource;
        return;
    end
    finiteTimeMask = ...
        isfinite(tSource);
    tSource = ...
        tSource(finiteTimeMask);
    XSource = ...
        XSource(finiteTimeMask,:);
    [tUnique,uniqueIndex] = ...
        unique( ...
            tSource, ...
            'stable');
    XUnique = ...
        XSource( ...
            uniqueIndex, ...
            :);
    if isempty(tUnique)
        error( ...
            'Touchdown source signal contains no finite timestamps.');
    end
    if any(tQuery < tUnique(1)-1e-9) || ...
            any(tQuery > tUnique(end)+1e-9)
        error( ...
            ['Touchdown telemetry time base exceeds one of the ', ...
             'required source-log time intervals.']);
    end
    if numel(tUnique) == 1
        Xquery = ...
            repmat( ...
                XUnique(1,:), ...
                numel(tQuery), ...
                1);
        return;
    end
    Xquery = ...
        NaN( ...
            numel(tQuery), ...
            size(XUnique,2));
    for column = 1:size(XUnique,2)
        sourceColumn = ...
            XUnique(:,column);
        finiteSignalMask = ...
            isfinite(sourceColumn);
        if nnz(finiteSignalMask) == 0
            continue;
        end
        tSignal = ...
            tUnique(finiteSignalMask);
        xSignal = ...
            sourceColumn(finiteSignalMask);
        if numel(tSignal) == 1
            Xquery(:,column) = ...
                xSignal(1);
        else
            Xquery(:,column) = ...
                interp1( ...
                    tSignal, ...
                    xSignal, ...
                    tQuery, ...
                    'linear', ...
                    NaN);
        end
    end
end
function X = timeseriesDataToMatrixTouchdown(data,nt)
    D = ...
        squeeze( ...
            data);
    if isempty(D)
        X = ...
            zeros(0,0);
        return;
    end
    if nt == 1
        X = ...
            reshape( ...
                D, ...
                1, ...
                []);
        return;
    end
    if isvector(D)
        if numel(D) == nt
            X = ...
                D(:);
        else
            error( ...
                'Unable to determine logged signal orientation.');
        end
        return;
    end
    if size(D,1) == nt
        X = ...
            reshape( ...
                D, ...
                nt, ...
                []);
    elseif size(D,2) == nt
        X = ...
            D.';
    elseif size(D,ndims(D)) == nt
        order = [ ...
            ndims(D), ...
            1:(ndims(D)-1)];
        D = ...
            permute( ...
                D, ...
                order);
        X = ...
            reshape( ...
                D, ...
                nt, ...
                []);
    else
        error( ...
            ['Unable to match logged signal dimensions ', ...
             'with its time vector.']);
    end
end
function firstIndex = firstPersistentTrueTouchdown(logicalVector,countRequired)
    logicalVector = ...
        logical( ...
            logicalVector(:));
    countRequired = ...
        max( ...
            1, ...
            round( ...
                countRequired));
    firstIndex = ...
        [];
    if isempty(logicalVector)
        return;
    end
    runCount = ...
        0;
    runStart = ...
        0;
    for k = 1:numel(logicalVector)
        if logicalVector(k)
            if runCount == 0
                runStart = ...
                    k;
            end
            runCount = ...
                runCount + 1;
            if runCount >= countRequired
                firstIndex = ...
                    runStart;
                return;
            end
        else
            runCount = ...
                0;
            runStart = ...
                0;
        end
    end
end
function value = finiteMaximumTouchdown(x)
    x = ...
        x(:);
    x = ...
        x( ...
            isfinite(x));
    if isempty(x)
        value = ...
            NaN;
    else
        value = ...
            max(x);
    end
end
function value = finiteMinimumTouchdown(x)
    x = ...
        x(:);
    x = ...
        x( ...
            isfinite(x));
    if isempty(x)
        value = ...
            NaN;
    else
        value = ...
            min(x);
    end
end
function addTouchdownEventLines( ...
    ax, ...
    landingStartTime, ...
    touchdownTime, ...
    stableTime, ...
    landedArmedTime)
    if isfinite(landingStartTime)
        xline( ...
            ax, ...
            landingStartTime, ...
            ':', ...
            'LAND start', ...
            'LabelVerticalAlignment','bottom', ...
            'HandleVisibility','off');
    end
    if isfinite(touchdownTime)
        xline( ...
            ax, ...
            touchdownTime, ...
            '-', ...
            'Touchdown', ...
            'LabelVerticalAlignment','top', ...
            'HandleVisibility','off');
    end
    if isfinite(stableTime)
        xline( ...
            ax, ...
            stableTime, ...
            '--', ...
            'Stable', ...
            'LabelVerticalAlignment','bottom', ...
            'HandleVisibility','off');
    end
    if isfinite(landedArmedTime)
        xline( ...
            ax, ...
            landedArmedTime, ...
            '-.', ...
            'LANDED ARMED', ...
            'LabelVerticalAlignment','top', ...
            'HandleVisibility','off');
    end
end
function text = formatTimeTouchdown(value)
    if isfinite(value)
        text = ...
            sprintf( ...
                '%.3f s', ...
                value);
    else
        text = ...
            'not detected';
    end
end
function text = formatNumberTouchdown(value)
    if isfinite(value)
        text = ...
            sprintf( ...
                '%.4f', ...
                value);
    else
        text = ...
            'NaN';
    end
end
