A_UAV = struct();
A_UAV.info.vehicle_name = ...
    "Reference Quadrotor";
A_UAV.info.model_level = ...
    "L1 Analytical";
A_UAV.info.model_type = ...
    "Nonlinear Newton-Euler 6-DOF";
A_UAV.info.reference = ...
    "Mahony, Kumar, and Corke, IEEE Robotics & Automation Magazine, 2012";
A_UAV.frame.inertial = ...
    "NED";
A_UAV.frame.body_x = ...
    "Forward";
A_UAV.frame.body_y = ...
    "Right";
A_UAV.frame.body_z = ...
    "Down";
A_UAV.frame.R_body_from_cad = [ ...
     0  0  1;
    -1  0  0;
     0 -1  0];
A_UAV.source.airframe_mass_kg = ...
    1.408410;
A_UAV.source.propeller_mass_kg = ...
    6.887e-3;
A_UAV.source.propeller_count = ...
    4;
A_UAV.source.propeller_diameter_m = ...
    0.2032;
A_UAV.source.airframe_cg_cad_m = [ ...
    0.000256;
    0.044228;
    0.001740];
A_UAV.source.airframe_moments_cad_kgm2 = [ ...
    8.848e-3;
    9.706e-3;
    8.077e-3];
A_UAV.source.airframe_products_cad_kgm2 = [ ...
   -7.2413355e-5;
   -6.3737250e-6;
   -1.2344966e-5];
A_UAV.source.rotor_center_cad_m = [ ...
   -128.933   58.700   128.895;
    128.896   58.700  -128.882;
   -128.916   58.700  -128.863;
    128.923   58.700   128.889] * 1e-3;
A_UAV.source.contact_point_cad_m = [ ...
     70.563  -103.203   44.881;
     70.417  -103.203  -44.928;
    -70.398  -103.203   45.026;
    -70.570  -103.203  -44.892] * 1e-3;
A_UAV.rigid.mass_kg = ...
    A_UAV.source.airframe_mass_kg + ...
    A_UAV.source.propeller_count * ...
    A_UAV.source.propeller_mass_kg;
A_UAV.rigid.airframe_cg_body_m = ...
    A_UAV.frame.R_body_from_cad * ...
    A_UAV.source.airframe_cg_cad_m;
A_UAV.rotor.center_body_m = ...
    ( ...
    A_UAV.frame.R_body_from_cad * ...
    A_UAV.source.rotor_center_cad_m.' ...
    ).';
A_UAV.rigid.cg_body_m = ...
    ( ...
    A_UAV.source.airframe_mass_kg * ...
    A_UAV.rigid.airframe_cg_body_m + ...
    A_UAV.source.propeller_mass_kg * ...
    sum(A_UAV.rotor.center_body_m,1).' ...
    ) ...
    / A_UAV.rigid.mass_kg;
A_UAV.rotor.arm_body_m = ...
    A_UAV.rotor.center_body_m - ...
    A_UAV.rigid.cg_body_m.';
A_UAV.contact.count = ...
    4;
A_UAV.contact.point_body_m = ...
    ( ...
    A_UAV.frame.R_body_from_cad * ...
    A_UAV.source.contact_point_cad_m.' ...
    ).';
A_UAV.contact.arm_body_m = ...
    A_UAV.contact.point_body_m - ...
    A_UAV.rigid.cg_body_m.';
A_UAV.contact.ground_down_m = ...
    0.0;
A_UAV.contact.cg_ground_clearance_m = ...
    max( ...
        A_UAV.contact.arm_body_m(:,3));
A_UAV.contact.stiffness_N_m = ...
    P_ENV.ground.contact.stiffness_N_m;
A_UAV.contact.damping_N_s_m = ...
    P_ENV.ground.contact.damping_N_s_m;
A_UAV.contact.static_friction = ...
    P_ENV.ground.contact.static_friction;
A_UAV.contact.dynamic_friction = ...
    P_ENV.ground.contact.dynamic_friction;
A_UAV.contact.critical_velocity_m_s = ...
    P_ENV.ground.contact.critical_velocity_m_s;
A_UAV_CONTACT = struct();
A_UAV_CONTACT.arm_body_m = ...
    A_UAV.contact.arm_body_m;
A_UAV_CONTACT.ground_down_m = ...
    A_UAV.contact.ground_down_m;
A_UAV_CONTACT.stiffness_N_m = ...
    A_UAV.contact.stiffness_N_m;
A_UAV_CONTACT.damping_N_s_m = ...
    A_UAV.contact.damping_N_s_m;
A_UAV_CONTACT.static_friction = ...
    A_UAV.contact.static_friction;
A_UAV_CONTACT.dynamic_friction = ...
    A_UAV.contact.dynamic_friction;
A_UAV_CONTACT.critical_velocity_m_s = ...
    A_UAV.contact.critical_velocity_m_s;
Ixx = ...
    A_UAV.source.airframe_moments_cad_kgm2(1);
Iyy = ...
    A_UAV.source.airframe_moments_cad_kgm2(2);
Izz = ...
    A_UAV.source.airframe_moments_cad_kgm2(3);
Iyz = ...
    A_UAV.source.airframe_products_cad_kgm2(1);
Izx = ...
    A_UAV.source.airframe_products_cad_kgm2(2);
Ixy = ...
    A_UAV.source.airframe_products_cad_kgm2(3);
I_air_cad = [ ...
    Ixx Ixy Izx;
    Ixy Iyy Iyz;
    Izx Iyz Izz];
I_air_body = ...
    A_UAV.frame.R_body_from_cad * ...
    I_air_cad * ...
    A_UAV.frame.R_body_from_cad.';
r_air = ...
    A_UAV.rigid.airframe_cg_body_m - ...
    A_UAV.rigid.cg_body_m;
A_UAV.rigid.inertia_kgm2 = ...
    I_air_body + ...
    A_UAV.source.airframe_mass_kg * ...
    ( ...
    (r_air.' * r_air) * eye(3) - ...
    r_air * r_air.' ...
    );
Rprop = ...
    A_UAV.source.propeller_diameter_m / 2;
mprop = ...
    A_UAV.source.propeller_mass_kg;
I_prop_center = diag([ ...
    0.25 * mprop * Rprop^2, ...
    0.25 * mprop * Rprop^2, ...
    0.50 * mprop * Rprop^2]);
for k = 1:A_UAV.source.propeller_count
    rk = ...
        A_UAV.rotor.center_body_m(k,:).' - ...
        A_UAV.rigid.cg_body_m;
    A_UAV.rigid.inertia_kgm2 = ...
        A_UAV.rigid.inertia_kgm2 + ...
        I_prop_center + ...
        mprop * ...
        ( ...
        (rk.' * rk) * eye(3) - ...
        rk * rk.' ...
        );
end
A_UAV.rigid.inertia_inverse_1_kgm2 = ...
    inv( ...
        A_UAV.rigid.inertia_kgm2);
A_UAV.rotor.count = ...
    4;
A_UAV.rotor.spin_direction = [ ...
    -1;
    -1;
    +1;
    +1];
A_UAV.rotor.thrust_axis_body = [ ...
     0;
     0;
    -1];
A_UAV.rotor.kT_dimensionless = ...
    0.10;
A_UAV.rotor.kP_dimensionless = ...
    0.05;
A_UAV.env.gravity_m_s2 = ...
    P_ENV.gravity.magnitude_m_s2;
A_UAV.env.air_density_kg_m3 = ...
    1.225;
A_UAV.env.gravity_ned_m_s2 = [ ...
    0;
    0;
    A_UAV.env.gravity_m_s2];
A_UAV.env.reference_gravity_m_s2 = ...
    A_UAV.env.gravity_m_s2;
A_UAV.env.reference_air_density_kg_m3 = ...
    A_UAV.env.air_density_kg_m3;
A_UAV.env.reference_gravity_ned_m_s2 = ...
    A_UAV.env.gravity_ned_m_s2;
A_UAV.aero.translational_drag_model = ...
    "Axis-wise quadratic aerodynamic drag";
A_UAV.aero.CdA_m2 = [ ...
    0.025;
    0.025;
    0.040];
A_UAV.aero.rotational_damping_model = ...
    "Axis-wise linear aerodynamic rotational damping";
A_UAV.aero.angular_damping_Nm_per_rad_s = [ ...
    0.002;
    0.002;
    0.004];
D = ...
    A_UAV.source.propeller_diameter_m;
rho_ref = ...
    A_UAV.env.reference_air_density_kg_m3;
A_UAV.rotor.cT_N_per_rad_s_sq = ...
    A_UAV.rotor.kT_dimensionless * ...
    rho_ref * ...
    D^4 / ...
    (4*pi^2);
A_UAV.rotor.cQ_Nm_per_rad_s_sq = ...
    A_UAV.rotor.kP_dimensionless * ...
    rho_ref * ...
    D^5 / ...
    (8*pi^3);
A_UAV.rotor.actuator_model = ...
    "Ideal rotor speed";
A_UAV.rotor.time_constant_s = ...
    0;
A_UAV.trim.hover_total_thrust_N = ...
    A_UAV.rigid.mass_kg * ...
    A_UAV.env.reference_gravity_m_s2;
A_UAV.trim.hover_thrust_per_rotor_N = ...
    A_UAV.trim.hover_total_thrust_N / ...
    A_UAV.rotor.count;
A_UAV.trim.hover_speed_rad_s = ...
    sqrt( ...
        A_UAV.trim.hover_thrust_per_rotor_N / ...
        A_UAV.rotor.cT_N_per_rad_s_sq);
A_UAV.trim.hover_speed_rpm = ...
    A_UAV.trim.hover_speed_rad_s * ...
    60 / ...
    (2*pi);
xRotor = ...
    A_UAV.rotor.arm_body_m(:,1);
yRotor = ...
    A_UAV.rotor.arm_body_m(:,2);
spinRotor = ...
    A_UAV.rotor.spin_direction;
cT = ...
    A_UAV.rotor.cT_N_per_rad_s_sq;
cQ = ...
    A_UAV.rotor.cQ_Nm_per_rad_s_sq;
A_UAV.trim.allocation_matrix = [ ...
     cT * ones(1,4); ...
    -cT * yRotor.'; ...
     cT * xRotor.'; ...
     cQ * spinRotor.'];
A_UAV.trim.target_wrench = [ ...
    A_UAV.trim.hover_total_thrust_N; ...
    0; ...
    0; ...
    0];
omegaSquaredTrim = ...
    A_UAV.trim.allocation_matrix \ ...
    A_UAV.trim.target_wrench;
if any(omegaSquaredTrim <= 0)
    error( ...
        'QuadrotorFramework:InvalidHoverTrim', ...
        ['Torque-balanced hover trim produced a nonpositive ', ...
         'rotor-speed-squared value.']);
end
A_UAV.trim.hover_omega_rad_s = ...
    sqrt( ...
        omegaSquaredTrim);
A_UAV.trim.hover_omega_rpm = ...
    A_UAV.trim.hover_omega_rad_s * ...
    60 / ...
    (2*pi);
A_UAV.trim.achieved_wrench = ...
    A_UAV.trim.allocation_matrix * ...
    omegaSquaredTrim;
A_UAV.trim.wrench_error = ...
    A_UAV.trim.achieved_wrench - ...
    A_UAV.trim.target_wrench;
A_UAV.init.position_ned_m = [ ...
     0;
     0;
    -A_UAV.contact.cg_ground_clearance_m];
A_UAV.init.velocity_ned_m_s = [ ...
    0;
    0;
    0];
A_UAV.init.body_rate_rad_s = [ ...
    0;
    0;
    0];
A_UAV.init.euler_rad = [ ...
    0;
    0;
    0];
A_UAV.init.quaternion_wxyz = [ ...
    1;
    0;
    0;
    0];
A_UAV.interface.input_omega_name = ...
    "Omega";
A_UAV.interface.input_omega_size = ...
    [4 1];
A_UAV.interface.input_omega_unit = ...
    "rad/s";
A_UAV.interface.input_environment_name = ...
    "Env";
A_UAV.interface.environment_fields_used = [ ...
    "Gravity";
    "Wind.v";
    "Wind.w";
    "Atmosphere.AirDensity"];
A_UAV.interface.output_name = ...
    "States";
A_UAV.interface.output_fields = [ ...
    "Position";
    "Velocity";
    "Acceleration";
    "AngularRate";
    "Attitude.Q";
    "Attitude.Euler"];
clear Ixx Iyy Izz
clear Iyz Izx Ixy
clear I_air_cad
clear I_air_body
clear r_air
clear Rprop
clear mprop
clear I_prop_center
clear rk
clear k
clear D
clear rho_ref
clear xRotor
clear yRotor
clear spinRotor
clear cT
clear cQ
clear omegaSquaredTrim
