B_UAV = struct();
B_UAV.info.vehicle_name = "Reference Quadrotor";
B_UAV.info.model_level = ...
    "L2 Block";
B_UAV.info.model_type = ...
    "Aerospace Blockset Multirotor + 6DOF Quaternion";
B_UAV.frame.inertial = "NED";
B_UAV.frame.body_x = "Forward";
B_UAV.frame.body_y = "Right";
B_UAV.frame.body_z = "Down";
B_UAV.units = "Metric (MKS)";
B_UAV.source.airframe_mass_kg = ...
    1.408410;
B_UAV.source.propeller_mass_kg = ...
    6.887e-3;
B_UAV.source.propeller_count = ...
    4;
B_UAV.source.propeller_diameter_m = ...
    0.2032;
B_UAV.source.airframe_cg_cad_m = [ ...
    0.000256;
    0.044228;
    0.001740];
B_UAV.source.airframe_moments_cad_kgm2 = [ ...
    8.848e-3;
    9.706e-3;
    8.077e-3];
B_UAV.source.airframe_products_cad_kgm2 = [ ...
   -7.2413355e-5;
   -6.3737250e-6;
   -1.2344966e-5];
B_UAV.source.rotor_center_cad_m = [ ...
   -128.933   58.700   128.895;
    128.896   58.700  -128.882;
   -128.916   58.700  -128.863;
    128.923   58.700   128.889] * 1e-3;
B_UAV.source.R_body_from_cad = [ ...
     0  0  1;
    -1  0  0;
     0 -1  0];
B_UAV.rigid.mass_kg = ...
    B_UAV.source.airframe_mass_kg + ...
    B_UAV.source.propeller_count * ...
    B_UAV.source.propeller_mass_kg;
airframe_cg_body = ...
    B_UAV.source.R_body_from_cad * ...
    B_UAV.source.airframe_cg_cad_m;
rotor_center_body = ...
    (B_UAV.source.R_body_from_cad * ...
    B_UAV.source.rotor_center_cad_m.').';
B_UAV.rigid.cg_body_m = ...
    ( ...
    B_UAV.source.airframe_mass_kg * ...
    airframe_cg_body + ...
    B_UAV.source.propeller_mass_kg * ...
    sum(rotor_center_body,1).' ...
    ) ...
    / B_UAV.rigid.mass_kg;
B_UAV.geometry.rotor_arm_body_m = ...
    rotor_center_body - ...
    B_UAV.rigid.cg_body_m.';
B_UAV.source.contact_point_cad_m = [ ...
     70.563  -103.203   44.881;
     70.417  -103.203  -44.928;
    -70.398  -103.203   45.026;
    -70.570  -103.203  -44.892] * 1e-3;
B_UAV.contact.point_body_m = ...
    ( ...
        B_UAV.source.R_body_from_cad * ...
        B_UAV.source.contact_point_cad_m.' ...
    ).';
B_UAV.contact.arm_body_m = ...
    B_UAV.contact.point_body_m - ...
    B_UAV.rigid.cg_body_m.';
B_UAV.contact.ground_down_m = ...
    0.0;
B_UAV.contact.cg_ground_clearance_m = ...
    max( ...
        B_UAV.contact.arm_body_m(:,3));
B_UAV.contact.stiffness_N_m = ...
    P_ENV.ground.contact.stiffness_N_m;
B_UAV.contact.damping_N_s_m = ...
    P_ENV.ground.contact.damping_N_s_m;
B_UAV.contact.static_friction = ...
    P_ENV.ground.contact.static_friction;
B_UAV.contact.dynamic_friction = ...
    P_ENV.ground.contact.dynamic_friction;
B_UAV.contact.critical_velocity_m_s = ...
    P_ENV.ground.contact.critical_velocity_m_s;
B_UAV_CONTACT = ...
    struct();
B_UAV_CONTACT.arm_body_m = ...
    B_UAV.contact.arm_body_m;
B_UAV_CONTACT.ground_down_m = ...
    B_UAV.contact.ground_down_m;
B_UAV_CONTACT.stiffness_N_m = ...
    B_UAV.contact.stiffness_N_m;
B_UAV_CONTACT.damping_N_s_m = ...
    B_UAV.contact.damping_N_s_m;
B_UAV_CONTACT.static_friction = ...
    B_UAV.contact.static_friction;
B_UAV_CONTACT.dynamic_friction = ...
    B_UAV.contact.dynamic_friction;
B_UAV_CONTACT.critical_velocity_m_s = ...
    B_UAV.contact.critical_velocity_m_s;
Ixx = B_UAV.source.airframe_moments_cad_kgm2(1);
Iyy = B_UAV.source.airframe_moments_cad_kgm2(2);
Izz = B_UAV.source.airframe_moments_cad_kgm2(3);
Iyz = B_UAV.source.airframe_products_cad_kgm2(1);
Izx = B_UAV.source.airframe_products_cad_kgm2(2);
Ixy = B_UAV.source.airframe_products_cad_kgm2(3);
I_air_cad = [ ...
    Ixx Ixy Izx;
    Ixy Iyy Iyz;
    Izx Iyz Izz];
I_air_body = ...
    B_UAV.source.R_body_from_cad * ...
    I_air_cad * ...
    B_UAV.source.R_body_from_cad.';
r_air = ...
    airframe_cg_body - ...
    B_UAV.rigid.cg_body_m;
B_UAV.rigid.inertia_kgm2 = ...
    I_air_body + ...
    B_UAV.source.airframe_mass_kg * ...
    ((r_air.'*r_air)*eye(3) - r_air*r_air.');
Rprop = ...
    B_UAV.source.propeller_diameter_m / 2;
mprop = ...
    B_UAV.source.propeller_mass_kg;
I_prop_center = diag([ ...
    0.25*mprop*Rprop^2, ...
    0.25*mprop*Rprop^2, ...
    0.50*mprop*Rprop^2]);
for k = 1:B_UAV.source.propeller_count
    rk = ...
        rotor_center_body(k,:).' - ...
        B_UAV.rigid.cg_body_m;
    B_UAV.rigid.inertia_kgm2 = ...
        B_UAV.rigid.inertia_kgm2 + ...
        I_prop_center + ...
        mprop * ...
        ((rk.'*rk)*eye(3) - rk*rk.');
end
B_UAV.env.gravity_m_s2 = ...
    9.80665;
B_UAV.env.air_density_kg_m3 = ...
    1.225;
B_UAV.env.gravity_ned_m_s2 = [ ...
    0;
    0;
    B_UAV.env.gravity_m_s2];
B_UAV.env.weight_ned_N = ...
    B_UAV.rigid.mass_kg * ...
    B_UAV.env.gravity_ned_m_s2;
B_UAV.env.reference_gravity_m_s2 = ...
    B_UAV.env.gravity_m_s2;
B_UAV.env.reference_air_density_kg_m3 = ...
    B_UAV.env.air_density_kg_m3;
B_UAV.multirotor.configuration = ...
    "Quadcopter X";
B_UAV.multirotor.modeling = ...
    "Without flap effects";
B_UAV.multirotor.ct_cq_source = ...
    "Dialog";
horizontal_radius = sqrt( ...
    B_UAV.geometry.rotor_arm_body_m(:,1).^2 + ...
    B_UAV.geometry.rotor_arm_body_m(:,2).^2);
B_UAV.multirotor.arm_length_m = ...
    mean(horizontal_radius);
B_UAV.multirotor.rotor_height_m = ...
    mean(B_UAV.geometry.rotor_arm_body_m(:,3));
B_UAV.multirotor.radius_m = ...
    B_UAV.source.propeller_diameter_m / 2;
B_UAV.source.simscape_kT = ...
    0.10;
B_UAV.source.simscape_kP = ...
    0.05;
B_UAV.multirotor.CT = ...
    4 * ...
    B_UAV.source.simscape_kT / ...
    pi^3;
B_UAV.multirotor.CQ = ...
    4 * ...
    B_UAV.source.simscape_kP / ...
    pi^4;
B_UAV.rotor.project_to_multirotor_order = ...
    [4 1 3 2];
B_UAV.rotor.spin_project_order = [ ...
    -1;
    -1;
    +1;
    +1];
spin_mr = ...
    B_UAV.rotor.spin_project_order( ...
    B_UAV.rotor.project_to_multirotor_order);
B_UAV.multirotor.omega_sign = ...
    -spin_mr;
B_UAV.sixdof.units = ...
    "Metric (MKS)";
B_UAV.sixdof.mass_type = ...
    "Fixed";
B_UAV.sixdof.mass_kg = ...
    B_UAV.rigid.mass_kg;
B_UAV.sixdof.inertia_kgm2 = ...
    B_UAV.rigid.inertia_kgm2;
B_UAV.sixdof.initial_position_ned_m = [ ...
     0;
     0;
    -B_UAV.contact.cg_ground_clearance_m];
B_UAV.sixdof.initial_velocity_body_m_s = [ ...
    0;
    0;
    0];
B_UAV.sixdof.initial_euler_rad = [ ...
    0;
    0;
    0];
B_UAV.sixdof.initial_body_rates_rad_s = [ ...
    0;
    0;
    0];
B_UAV.sixdof.include_gravity = ...
    true;
B_UAV.aero.model = ...
    "Aerospace Blockset aerodynamic forces and moments";
B_UAV.aero.reference_area_m2 = ...
    0.025;
B_UAV.aero.reference_span_m = ...
    2 * B_UAV.multirotor.arm_length_m;
B_UAV.aero.reference_length_m = ...
    2 * B_UAV.multirotor.arm_length_m;
B_UAV.aero.CD = ...
    1.0;
B_UAV.aero.Cc = ...
    0.0;
B_UAV.aero.CL = ...
    0.0;
B_UAV.aero.Cl = ...
    0.0;
B_UAV.aero.Cm = ...
    0.0;
B_UAV.aero.Cn = ...
    0.0;
B_UAV.aero.coefficients = [ ...
    B_UAV.aero.CD, ...
    B_UAV.aero.Cc, ...
    B_UAV.aero.CL, ...
    B_UAV.aero.Cl, ...
    B_UAV.aero.Cm, ...
    B_UAV.aero.Cn];
B_UAV.aero.cg_body_m = [ ...
    0;
    0;
    0];
B_UAV.aero.cp_body_m = [ ...
    0;
    0;
    0];
B_UAV.aero.angular_damping_Nm_per_rad_s = [ ...
    0.002;
    0.002;
    0.004];
B_UAV.sixdof.force_sources = [ ...
    "Multirotor";
    "Gravity";
    "Aerodynamics";
    "Ground Contact"];
B_UAV.sixdof.moment_sources = [ ...
    "Multirotor";
    "Aerodynamics";
    "Wind rotational damping";
    "Ground Contact"];
B_UAV.trim.total_weight_N = ...
    B_UAV.rigid.mass_kg * ...
    B_UAV.env.reference_gravity_m_s2;
B_UAV.trim.thrust_per_rotor_N = ...
    B_UAV.trim.total_weight_N / ...
    B_UAV.source.propeller_count;
B_UAV.trim.hover_speed_rad_s = sqrt( ...
    B_UAV.trim.thrust_per_rotor_N / ...
    ( ...
    B_UAV.multirotor.CT * ...
    B_UAV.env.reference_air_density_kg_m3 * ...
    pi * ...
    B_UAV.multirotor.radius_m^4 ...
    ));
B_UAV.trim.hover_speed_rpm = ...
    B_UAV.trim.hover_speed_rad_s * ...
    60 / ...
    (2*pi);
B_UAV.interface.input_omega_name = ...
    "Omega";
B_UAV.interface.input_omega_size = ...
    [4 1];
B_UAV.interface.input_omega_unit = ...
    "rad/s";
B_UAV.interface.input_environment_name = ...
    "Env";
B_UAV.interface.environment_fields_used = [ ...
    "Gravity";
    "Wind.v";
    "Wind.w";
    "Atmosphere.AirDensity"];
B_UAV.interface.output_name = ...
    "States";
B_UAV.interface.state_order = [ ...
    "x";
    "vx";
    "y";
    "vy";
    "z";
    "vz";
    "wx";
    "wy";
    "wz";
    "Q";
    "yaw";
    "pitch";
    "roll"];
clear Ixx Iyy Izz
clear Iyz Izx Ixy
clear I_air_cad
clear I_air_body
clear r_air
clear Rprop
clear mprop
clear I_prop_center
clear rk
clear k
clear airframe_cg_body
clear rotor_center_body
clear horizontal_radius
clear spin_mr
