P_UAV = struct();
P_UAV.info.vehicle_name = ...
    "Reference Quadrotor";
P_UAV.info.model_level = ...
    "L3 Physical";
P_UAV.info.model_type = ...
    "Simscape Multibody + Electrical + Aerodynamic Propellers";
P_UAV.frames.body_x = ...
    "Forward";
P_UAV.frames.body_y = ...
    "Right";
P_UAV.frames.body_z = ...
    "Down";
P_UAV.frames.inertial = ...
    "NED";
P_UAV.geometry.wheelbase_m = ...
    0.350;
P_UAV.geometry.dryden_equivalent_span_m = ...
    P_UAV.geometry.wheelbase_m;
P_UAV.mass.airframe_kg = ...
    1.408410;
P_UAV.cg.airframe_m = [ ...
    0.000256 ...
    0.044228 ...
    0.001740];
P_UAV.cg.airframe_body_m = [ ...
     P_UAV.cg.airframe_m(3); ...
    -P_UAV.cg.airframe_m(1); ...
    -P_UAV.cg.airframe_m(2)];
P_UAV.cg.cad_origin_from_cg_body_m = ...
    -P_UAV.cg.airframe_body_m;
P_UAV.inertia.moments_kgm2 = [ ...
    8.848e-3 ...
    9.706e-3 ...
    8.077e-3];
P_UAV.inertia.products_kgm2 = [ ...
   -7.2413355e-5 ...
   -6.3737250e-6 ...
   -1.2344966e-5];
P_UAV.contact.point1_cad_m = ...
    [70.563 -103.203 44.881] * 1e-3;
P_UAV.contact.point2_cad_m = ...
    [70.417 -103.203 -44.928] * 1e-3;
P_UAV.contact.point3_cad_m = ...
    [-70.398 -103.203 45.026] * 1e-3;
P_UAV.contact.point4_cad_m = ...
    [-70.570 -103.203 -44.892] * 1e-3;
P_UAV.contact.points_cad_m = [ ...
    P_UAV.contact.point1_cad_m; ...
    P_UAV.contact.point2_cad_m; ...
    P_UAV.contact.point3_cad_m; ...
    P_UAV.contact.point4_cad_m];
P_UAV.contact.points_body_from_cad_origin_m = [ ...
     P_UAV.contact.points_cad_m(:,3), ...
    -P_UAV.contact.points_cad_m(:,1), ...
    -P_UAV.contact.points_cad_m(:,2)];
P_UAV.contact.arm_body_m = ...
    P_UAV.contact.points_body_from_cad_origin_m - ...
    P_UAV.cg.airframe_body_m.';
P_UAV.contact.cg_ground_clearance_m = ...
    mean( ...
        P_UAV.contact.arm_body_m(:,3));
P_UAV.contact.contact_plane_flatness_m = ...
    max(P_UAV.contact.arm_body_m(:,3)) - ...
    min(P_UAV.contact.arm_body_m(:,3));
P_UAV.contact.ground_down_m = ...
    0.0;
if ~isfinite(P_UAV.contact.cg_ground_clearance_m) || ...
        P_UAV.contact.cg_ground_clearance_m <= 0
    error( ...
        'UAV_simscape:InvalidCGGroundClearance', ...
        ['Derived L3 CG-to-ground clearance must be finite and ', ...
         'strictly positive.']);
end
P_UAV.motor.position1_cad_m = ...
    [-128.933 58.700 128.895] * 1e-3;
P_UAV.motor.position2_cad_m = ...
    [128.896 58.700 -128.882] * 1e-3;
P_UAV.motor.position3_cad_m = ...
    [-128.916 58.700 -128.863] * 1e-3;
P_UAV.motor.position4_cad_m = ...
    [128.923 58.700 128.889] * 1e-3;
P_UAV.motor.positions_cad_m = [ ...
    P_UAV.motor.position1_cad_m; ...
    P_UAV.motor.position2_cad_m; ...
    P_UAV.motor.position3_cad_m; ...
    P_UAV.motor.position4_cad_m];
P_UAV.motor.positions_body_from_cg_m = [ ...
     P_UAV.motor.positions_cad_m(:,3), ...
    -P_UAV.motor.positions_cad_m(:,1), ...
    -P_UAV.motor.positions_cad_m(:,2)] - ...
    P_UAV.cg.airframe_body_m.';
P_UAV.motor.count = ...
    4;
P_UAV.motor.Kv_rpm_per_V = ...
    1300;
P_UAV.motor.max_current_A = ...
    45.1;
P_UAV.motor.max_power_W = ...
    1059;
P_UAV.motor.Kt_Nm_per_A = ...
    60 / ...
    (2*pi*P_UAV.motor.Kv_rpm_per_V);
P_UAV.motor.max_torque_Nm = ...
    P_UAV.motor.Kt_Nm_per_A * ...
    P_UAV.motor.max_current_A;
P_UAV.propeller.diameter_m = ...
    0.2032;
P_UAV.propeller.mass_each_kg = ...
    6.887e-3;
P_UAV.mass.propellers_total_kg = ...
    P_UAV.motor.count * ...
    P_UAV.propeller.mass_each_kg;
P_UAV.mass.multibody_total_kg = ...
    P_UAV.mass.airframe_kg + ...
    P_UAV.mass.propellers_total_kg;
P_UAV.propeller.kT = ...
    0.10;
P_UAV.propeller.kP = ...
    0.05;
P_UAV.drive.max_torque_Nm = ...
    P_UAV.motor.max_torque_Nm;
P_UAV.drive.max_power_W = ...
    P_UAV.motor.max_power_W;
P_UAV.drive.torque_control_time_constant_s = ...
    0.02;
P_UAV.drive.efficiency_percent = ...
    90;
P_UAV.drive.efficiency_speed_rpm = ...
    0.5 * ...
    P_UAV.motor.Kv_rpm_per_V * ...
    22.2;
P_UAV.drive.efficiency_torque_Nm = ...
    0.5 * ...
    P_UAV.drive.max_torque_Nm;
P_UAV.drive.iron_loss_W = ...
    0;
P_UAV.drive.fixed_loss_W = ...
    0;
P_UAV.drive.external_supply_resistance_Ohm = ...
    0;
P_UAV.drive.rotor_inertia_kgm2 = ...
    8.0e-7;
P_UAV.drive.rotor_damping_Nm_s_rad = ...
    0;
P_UAV.drive.initial_speed_rpm = ...
    0;
P_UAV.drive.speed_pi.Kp = ...
    0.00035;
P_UAV.drive.speed_pi.Ki = ...
    0.005;
P_UAV.drive.speed_pi.torque_limit_Nm = ...
    0.25;
P_UAV.battery.capacity_Ah = ...
    3.3;
P_UAV.battery.nominal_voltage_V = ...
    22.2;
P_UAV.battery.full_voltage_V = ...
    25.2;
P_UAV.battery.mass_kg = ...
    0.432165;
P_UAV.battery.ideal_voltage_V = ...
    P_UAV.battery.nominal_voltage_V;
P_UAV.battery.Vnom_V = ...
    P_UAV.battery.full_voltage_V;
P_UAV.battery.internal_resistance_Ohm = ...
    0.020;
P_UAV.battery.V1_V = ...
    22.2;
P_UAV.battery.AH1_Ah = ...
    1.65;
P_UAV.battery.measurement_temperature_K = ...
    298.15;
P_UAV.battery.second_temperature_K = ...
    273.15;
P_UAV.battery.Vnom_second_V = ...
    P_UAV.battery.Vnom_V;
P_UAV.battery.V1_second_V = ...
    P_UAV.battery.V1_V;
P_UAV.battery.internal_resistance_second_Ohm = ...
    P_UAV.battery.internal_resistance_Ohm;
P_UAV.battery.specific_heat_J_kgK = ...
    1000;
P_UAV.battery.thermal_mass_J_K = ...
    P_UAV.battery.mass_kg * ...
    P_UAV.battery.specific_heat_J_kgK;
P_UAV.battery.initial_SOC = ...
    1.0;
P_UAV.battery.initial_charge_Ah = ...
    P_UAV.battery.initial_SOC * ...
    P_UAV.battery.capacity_Ah;
P_UAV.battery.initial_temperature_K = ...
    298.15;
P_UAV.initial_conditions.reference_point = ...
    "Vehicle center of gravity";
P_UAV.initial_conditions.position_ned_m = [ ...
    0; ...
    0; ...
    P_UAV.contact.ground_down_m - ...
    P_UAV.contact.cg_ground_clearance_m];
P_UAV.initial_conditions.velocity_ned_m_s = ...
    zeros(3,1);
P_UAV.initial_conditions.euler_rpy_rad = ...
    zeros(3,1);
P_UAV.initial_conditions.angular_rate_body_rad_s = ...
    zeros(3,1);
P_UAV.initial_conditions.contact_plane_down_m = ...
    P_UAV.initial_conditions.position_ned_m(3) + ...
    P_UAV.contact.cg_ground_clearance_m;
if abs( ...
        P_UAV.initial_conditions.contact_plane_down_m - ...
        P_UAV.contact.ground_down_m) > 1e-9
    error( ...
        'UAV_simscape:InitialGroundContactMismatch', ...
        ['L3 initial CG position is inconsistent with the derived ', ...
         'landing-gear ground clearance.']);
end
P_UAV.aero.reference_length_m = ...
    P_UAV.geometry.wheelbase_m;
P_UAV.aero.reference_area_m2 = ...
    pi * ...
    P_UAV.aero.reference_length_m^2 / ...
    4;
P_UAV.aero.alpha_deg = ...
    -45:5:5;
P_UAV.aero.alpha_rad = ...
    deg2rad(P_UAV.aero.alpha_deg);
alpha = ...
    P_UAV.aero.alpha_rad;
P_UAV.aero.Cx = ...
    0.282*cos(alpha) ...
    - 0.0267*cos(3*alpha) ...
    - 0.0145*cos(7*alpha);
P_UAV.aero.Cz = ...
    0.605*sin(alpha) ...
    - 0.0645;
P_UAV.aero.Cm = ...
    7.50e-3*cos(alpha) ...
    - 4.22e-3*cos(3*alpha) ...
    - 0.0114*sin(2*alpha);
P_UAV.aero.valid_airspeed_m_s = ...
    [0 16];
P_UAV.aero.normalized_velocity_breakpoints = ...
    -1:0.05:1;
P_UAV.aero.Kx = ...
    [3.00 -8.92] * 1e-2;
P_UAV.aero.Ky = ...
    [-0.509 0.400];
P_UAV.aero.Kz = ...
    [0.838 -2.85];
P_UAV.aero.Kl = ...
    [1.17 -0.0498 1.69 -2.65 6.24 -4.57] * 1e-2;
P_UAV.aero.Km = ...
    [-8.46 27.6 10.2 -19.4 3.62 1.98] * 1e-2;
P_UAV.aero.Kn = ...
    [-3.07 7.59 -1.34 -4.51 1.55 -0.572] * 1e-2;
P_UAV.aero.rotational_damping_model = ...
    "Axis-wise linear aerodynamic rotational damping";
P_UAV.aero.angular_damping_Nm_per_rad_s = [ ...
    0.002;
    0.002;
    0.004];
P_UAV.aero.l_m = mean(abs([ ...
    P_UAV.motor.position1_cad_m(3) - P_UAV.cg.airframe_m(3), ...
    P_UAV.motor.position2_cad_m(3) - P_UAV.cg.airframe_m(3), ...
    P_UAV.motor.position3_cad_m(3) - P_UAV.cg.airframe_m(3), ...
    P_UAV.motor.position4_cad_m(3) - P_UAV.cg.airframe_m(3)]));
P_UAV.aero.b_m = mean(abs([ ...
   -(P_UAV.motor.position1_cad_m(1) - P_UAV.cg.airframe_m(1)), ...
   -(P_UAV.motor.position2_cad_m(1) - P_UAV.cg.airframe_m(1)), ...
   -(P_UAV.motor.position3_cad_m(1) - P_UAV.cg.airframe_m(1)), ...
   -(P_UAV.motor.position4_cad_m(1) - P_UAV.cg.airframe_m(1))]));
P_UAV.aero.reference_area_m2 = ...
    4 * ...
    P_UAV.aero.l_m * ...
    P_UAV.aero.b_m;
P_UAV.aero.reference_moment_length_m = ...
    P_UAV.aero.b_m;
P_UAV.aero.lookup.breakpoints = ...
    P_UAV.aero.normalized_velocity_breakpoints;
bp = ...
    P_UAV.aero.lookup.breakpoints;
P_UAV.aero.lookup.Cx = ...
    sign(bp) .* ...
    ( ...
    abs(bp) .* P_UAV.aero.Kx(1) + ...
    bp.^2 .* P_UAV.aero.Kx(2) ...
    );
P_UAV.aero.lookup.Cy = ...
    sign(bp) .* ...
    ( ...
    abs(bp) .* P_UAV.aero.Ky(1) + ...
    bp.^2 .* P_UAV.aero.Ky(2) ...
    );
P_UAV.aero.lookup.Cz = ...
    sign(bp) .* ...
    ( ...
    abs(bp) .* P_UAV.aero.Kz(1) + ...
    bp.^2 .* P_UAV.aero.Kz(2) ...
    );
[Vbar_Cl,Wbar_Cl] = ...
    ndgrid(bp,bp);
P_UAV.aero.lookup.Cl = ...
    sign(Vbar_Cl) .* ...
    ( ...
    abs(Vbar_Cl) .* P_UAV.aero.Kl(1) + ...
    Vbar_Cl.^2 .* P_UAV.aero.Kl(2) + ...
    abs(Vbar_Cl).*Wbar_Cl .* P_UAV.aero.Kl(3) + ...
    abs(Vbar_Cl).^3 .* P_UAV.aero.Kl(4) + ...
    Vbar_Cl.^2.*Wbar_Cl .* P_UAV.aero.Kl(5) + ...
    abs(Vbar_Cl).*Wbar_Cl.^2 .* P_UAV.aero.Kl(6) ...
    ) ...
    / P_UAV.aero.b_m;
[Ubar_Cm,Wbar_Cm] = ...
    ndgrid(bp,bp);
P_UAV.aero.lookup.Cm = ...
    sign(Ubar_Cm) .* ...
    ( ...
    abs(Ubar_Cm) .* P_UAV.aero.Km(1) + ...
    Ubar_Cm.^2 .* P_UAV.aero.Km(2) + ...
    abs(Ubar_Cm).*Wbar_Cm .* P_UAV.aero.Km(3) + ...
    abs(Ubar_Cm).^3 .* P_UAV.aero.Km(4) + ...
    Ubar_Cm.^2.*Wbar_Cm .* P_UAV.aero.Km(5) + ...
    abs(Ubar_Cm).*Wbar_Cm.^2 .* P_UAV.aero.Km(6) ...
    ) ...
    / P_UAV.aero.b_m;
[Ubar_Cn,Vbar_Cn] = ...
    ndgrid(bp,bp);
P_UAV.aero.lookup.Cn = ...
    sign(Ubar_Cn) .* ...
    sign(Vbar_Cn) .* ...
    ( ...
    abs(Vbar_Cn) .* P_UAV.aero.Kn(1) + ...
    Vbar_Cn.^2 .* P_UAV.aero.Kn(2) + ...
    abs(Vbar_Cn).*Ubar_Cn .* P_UAV.aero.Kn(3) + ...
    abs(Vbar_Cn).^3 .* P_UAV.aero.Kn(4) + ...
    Vbar_Cn.^2.*Ubar_Cn .* P_UAV.aero.Kn(5) + ...
    abs(Vbar_Cn).*Ubar_Cn.^2 .* P_UAV.aero.Kn(6) ...
    ) ...
    / P_UAV.aero.b_m;
P_UAV.aero.normalization_epsilon_m_s = ...
    eps;
P_UAV.interface.input_omega_name = ...
    "Omega";
P_UAV.interface.input_omega_size = ...
    [4 1];
P_UAV.interface.input_omega_unit = ...
    "rad/s";
P_UAV.interface.input_environment_name = ...
    "Env";
P_UAV.interface.environment_fields_used = [ ...
    "Wind.v";
    "Wind.w";
    "Atmosphere.AirDensity"];
P_UAV.interface.output_name = ...
    "States";
P_UAV.interface.state_reference_point = ...
    "Vehicle center of gravity";
P_UAV.interface.position_frame = ...
    "NED";
P_UAV.interface.velocity_frame = ...
    "NED";
P_UAV.interface.angular_rate_frame = ...
    "Body";
P_UAV.interface.state_order = [ ...
    "x";
    "vx";
    "y";
    "vy";
    "z";
    "vz";
    "wx";
    "wy";
    "wz";
    "Q";
    "yaw";
    "pitch";
    "roll"];
clear alpha
clear bp
clear Vbar_Cl
clear Wbar_Cl
clear Ubar_Cm
clear Wbar_Cm
clear Ubar_Cn
clear Vbar_Cn
