if ~exist('SENSOR','var')
    error( ...
        'QuadrotorFramework:MissingSensorParameters', ...
        ['SENSOR does not exist. Run UAV_sensors.m before ', ...
         'UAV_state_estimator.m.']);
end
if ~exist('P_ENV','var')
    error( ...
        'QuadrotorFramework:MissingEnvironmentParameters', ...
        ['P_ENV does not exist. Run Environment.m before ', ...
         'UAV_state_estimator.m.']);
end
ESTIMATOR = struct();
tuningSchemaVersion = ...
    1.0;
tuningSourceText = ...
    'TUNED_300EVAL_2026_09_04';
estimatorTuningSilent = ...
    false;
if exist( ...
        'ESTIMATOR_TUNING_SILENT', ...
        'var')
    silentValue = ...
        ESTIMATOR_TUNING_SILENT;
    if ~( ...
            (islogical(silentValue) && isscalar(silentValue)) || ...
            (isnumeric(silentValue) && ...
             isscalar(silentValue) && ...
             isfinite(silentValue) && ...
             (silentValue == 0 || silentValue == 1)) )
        error( ...
            'QuadrotorFramework:InvalidEstimatorTuningSilentFlag', ...
            ['ESTIMATOR_TUNING_SILENT must be a logical scalar ', ...
             'or numeric 0/1.']);
    end
    estimatorTuningSilent = ...
        logical(silentValue);
end
ESTIMATOR.tuning.schemaVersion = ...
    tuningSchemaVersion;
ESTIMATOR.tuning.gyroNoiseScale = ...
    0.008535;
ESTIMATOR.tuning.gyroBiasNoiseScale = ...
    0.001197;
ESTIMATOR.tuning.accelNoiseScale = ...
    0.001169;
ESTIMATOR.tuning.accelBiasNoiseScale = ...
    0.002066;
ESTIMATOR.tuning.magBiasNoiseScale = ...
    0.360029;
ESTIMATOR.tuning.geomagneticVectorNoiseScale = ...
    0.008315;
ESTIMATOR.tuning.gpsPositionRScale_NE = ...
    3.04681;
ESTIMATOR.tuning.gpsVelocityRScale_NE = ...
    31.16415;
ESTIMATOR.tuning.gpsVelocityRScale_D = ...
    2.624673;
ESTIMATOR.tuning.magRScale = ...
    6.746872;
ESTIMATOR.tuning.baroRScale = ...
    4.764613;
ESTIMATOR.tuning.quaternionP0Scale = ...
    0.001018;
ESTIMATOR.tuning.positionP0Scale_NE = ...
    0.023288;
ESTIMATOR.tuning.positionP0Scale_D = ...
    17.644082;
ESTIMATOR.tuning.velocityP0Scale_NE = ...
    0.010597;
ESTIMATOR.tuning.velocityP0Scale_D = ...
    10.351926;
ESTIMATOR.tuning.gyroBiasP0Scale = ...
    0.003397;
ESTIMATOR.tuning.accelBiasP0Scale = ...
    0.086015;
ESTIMATOR.tuning.geomagneticP0Scale = ...
    0.001736;
ESTIMATOR.tuning.magBiasP0Scale = ...
    0.004873;
ESTIMATOR.tuning.robustPositionP0Scale_NE = ...
    0.139149;
ESTIMATOR.tuning.robustPositionP0Scale_D = ...
    0.240655;
ESTIMATOR.tuning.robustVelocityP0Scale_NE = ...
    0.001493;
ESTIMATOR.tuning.robustVelocityP0Scale_D = ...
    0.124664;
tuningParameterNames = { ...
    'gyroNoiseScale', ...
    'gyroBiasNoiseScale', ...
    'accelNoiseScale', ...
    'accelBiasNoiseScale', ...
    'magBiasNoiseScale', ...
    'geomagneticVectorNoiseScale', ...
    'gpsPositionRScale_NE', ...
    'gpsVelocityRScale_NE', ...
    'gpsVelocityRScale_D', ...
    'magRScale', ...
    'baroRScale', ...
    'quaternionP0Scale', ...
    'positionP0Scale_NE', ...
    'positionP0Scale_D', ...
    'velocityP0Scale_NE', ...
    'velocityP0Scale_D', ...
    'gyroBiasP0Scale', ...
    'accelBiasP0Scale', ...
    'geomagneticP0Scale', ...
    'magBiasP0Scale', ...
    'robustPositionP0Scale_NE', ...
    'robustPositionP0Scale_D', ...
    'robustVelocityP0Scale_NE', ...
    'robustVelocityP0Scale_D'};
tuningParameterCount = ...
    numel(tuningParameterNames);
ESTIMATOR.tuning.parameterCount = ...
    double(tuningParameterCount);
nominalTuningVector = ...
    zeros( ...
        1, ...
        tuningParameterCount);
for tuningParameterIndex = ...
        1:tuningParameterCount
    tuningParameterName = ...
        tuningParameterNames{tuningParameterIndex};
    nominalTuningVector(tuningParameterIndex) = ...
        ESTIMATOR.tuning.(tuningParameterName);
end
ESTIMATOR.tuning.nominalVector = ...
    nominalTuningVector;
ESTIMATOR.tuning.overrideActive = ...
    false;
ESTIMATOR.tuning.sourceCode = ...
    0.0;
if exist( ...
        'ESTIMATOR_TUNING_OVERRIDE', ...
        'var')
    if ~isstruct(ESTIMATOR_TUNING_OVERRIDE) || ...
            ~isscalar(ESTIMATOR_TUNING_OVERRIDE)
        error( ...
            'QuadrotorFramework:InvalidEstimatorTuningOverride', ...
            ['ESTIMATOR_TUNING_OVERRIDE must be a scalar ', ...
             'structure.']);
    end
    overrideFieldNames = ...
        fieldnames( ...
            ESTIMATOR_TUNING_OVERRIDE);
    for overrideFieldIndex = ...
            1:numel(overrideFieldNames)
        overrideFieldName = ...
            overrideFieldNames{overrideFieldIndex};
        if ~any( ...
                strcmp( ...
                    overrideFieldName, ...
                    tuningParameterNames))
            error( ...
                'QuadrotorFramework:UnknownEstimatorTuningParameter', ...
                ['Unknown estimator tuning parameter "%s".'], ...
                overrideFieldName);
        end
    end
    for tuningParameterIndex = ...
            1:tuningParameterCount
        tuningParameterName = ...
            tuningParameterNames{tuningParameterIndex};
        if isfield( ...
                ESTIMATOR_TUNING_OVERRIDE, ...
                tuningParameterName)
            ESTIMATOR.tuning.(tuningParameterName) = ...
                ESTIMATOR_TUNING_OVERRIDE.(tuningParameterName);
        end
    end
    ESTIMATOR.tuning.overrideActive = ...
        true;
    ESTIMATOR.tuning.sourceCode = ...
        1.0;
    tuningSourceText = ...
        'ESTIMATOR_TUNING_OVERRIDE';
end
for tuningParameterIndex = ...
        1:tuningParameterCount
    tuningParameterName = ...
        tuningParameterNames{tuningParameterIndex};
    tuningParameterValue = ...
        ESTIMATOR.tuning.(tuningParameterName);
    if ~isscalar(tuningParameterValue) || ...
            ~isnumeric(tuningParameterValue) || ...
            ~isreal(tuningParameterValue) || ...
            ~isfinite(tuningParameterValue) || ...
            tuningParameterValue <= 0
        error( ...
            'QuadrotorFramework:InvalidEstimatorTuningFactor', ...
            ['ESTIMATOR.tuning.%s must be a finite, real, ', ...
             'strictly positive scalar.'], ...
            tuningParameterName);
    end
end
currentTuningVector = ...
    zeros( ...
        1, ...
        tuningParameterCount);
for tuningParameterIndex = ...
        1:tuningParameterCount
    tuningParameterName = ...
        tuningParameterNames{tuningParameterIndex};
    currentTuningVector(tuningParameterIndex) = ...
        ESTIMATOR.tuning.(tuningParameterName);
end
ESTIMATOR.tuning.vector = ...
    currentTuningVector;
ESTIMATOR.tuning.enableAutomaticTuning = ...
    ESTIMATOR.tuning.overrideActive;
ESTIMATOR.rate.imu_Hz = ...
    SENSOR.IMU.sampleRate_Hz;
if ~isscalar(ESTIMATOR.rate.imu_Hz) || ...
        ~isfinite(ESTIMATOR.rate.imu_Hz) || ...
        ESTIMATOR.rate.imu_Hz <= 0
    error( ...
        'QuadrotorFramework:InvalidEstimatorIMURate', ...
        'The estimator IMU rate must be finite and positive.');
end
ESTIMATOR.rate.imuSampleTime_s = ...
    1 / ESTIMATOR.rate.imu_Hz;
ESTIMATOR.rate.gps_Hz = ...
    SENSOR.GPS.sampleRate_Hz;
if ~isscalar(ESTIMATOR.rate.gps_Hz) || ...
        ~isfinite(ESTIMATOR.rate.gps_Hz) || ...
        ESTIMATOR.rate.gps_Hz <= 0
    error( ...
        'QuadrotorFramework:InvalidEstimatorGPSRate', ...
        'The estimator GPS rate must be finite and positive.');
end
ESTIMATOR.rate.gpsSampleTime_s = ...
    1 / ESTIMATOR.rate.gps_Hz;
ESTIMATOR.rate.magFusion_Hz = ...
    20;
ESTIMATOR.rate.magFusionSampleTime_s = ...
    1 / ESTIMATOR.rate.magFusion_Hz;
ESTIMATOR.rate.baro_Hz = ...
    SENSOR.Barometer.sampleRate_Hz;
if ~isscalar(ESTIMATOR.rate.baro_Hz) || ...
        ~isfinite(ESTIMATOR.rate.baro_Hz) || ...
        ESTIMATOR.rate.baro_Hz <= 0
    error( ...
        'QuadrotorFramework:InvalidEstimatorBarometerRate', ...
        'The estimator barometer rate must be finite and positive.');
end
ESTIMATOR.rate.baroSampleTime_s = ...
    1 / ESTIMATOR.rate.baro_Hz;
ESTIMATOR.rate.gpsDivisor = ...
    round( ...
        ESTIMATOR.rate.imu_Hz / ...
        ESTIMATOR.rate.gps_Hz);
ESTIMATOR.rate.magDivisor = ...
    round( ...
        ESTIMATOR.rate.imu_Hz / ...
        ESTIMATOR.rate.magFusion_Hz);
ESTIMATOR.rate.baroDivisor = ...
    round( ...
        ESTIMATOR.rate.imu_Hz / ...
        ESTIMATOR.rate.baro_Hz);
gpsRatio = ...
    ESTIMATOR.rate.imu_Hz / ...
    ESTIMATOR.rate.gps_Hz;
magRatio = ...
    ESTIMATOR.rate.imu_Hz / ...
    ESTIMATOR.rate.magFusion_Hz;
baroRatio = ...
    ESTIMATOR.rate.imu_Hz / ...
    ESTIMATOR.rate.baro_Hz;
if abs( ...
        gpsRatio - ...
        ESTIMATOR.rate.gpsDivisor) > 1e-12
    error( ...
        'QuadrotorFramework:InvalidGPSFusionRate', ...
        'IMU rate must be an integer multiple of GPS rate.');
end
if abs( ...
        magRatio - ...
        ESTIMATOR.rate.magDivisor) > 1e-12
    error( ...
        'QuadrotorFramework:InvalidMagFusionRate', ...
        ['IMU rate must be an integer multiple of ', ...
         'magnetometer fusion rate.']);
end
if abs( ...
        baroRatio - ...
        ESTIMATOR.rate.baroDivisor) > 1e-12
    error( ...
        'QuadrotorFramework:InvalidBarometerFusionRate', ...
        ['IMU rate must be an integer multiple of ', ...
         'barometer rate.']);
end
clear gpsRatio ...
    magRatio ...
    baroRatio;
ESTIMATOR.reference.lla_deg_m = [ ...
    P_ENV.location.latitude_ref_deg, ...
    P_ENV.location.longitude_ref_deg, ...
    P_ENV.location.altitude_ref_m];
if any( ...
        ~isfinite( ...
            ESTIMATOR.reference.lla_deg_m))
    error( ...
        'QuadrotorFramework:InvalidEstimatorReferenceLocation', ...
        'Estimator reference LLA must contain finite values.');
end
ESTIMATOR.gravity.magnitude_m_s2 = ...
    P_ENV.gravity.magnitude_m_s2;
if ~isscalar(ESTIMATOR.gravity.magnitude_m_s2) || ...
        ~isfinite(ESTIMATOR.gravity.magnitude_m_s2) || ...
        ESTIMATOR.gravity.magnitude_m_s2 <= 0
    error( ...
        'QuadrotorFramework:InvalidEstimatorGravity', ...
        'Gravity magnitude must be finite and positive.');
end
ESTIMATOR.gravity.ned_m_s2 = [ ...
    0; ...
    0; ...
    ESTIMATOR.gravity.magnitude_m_s2];
gpsHorizontalStd_m = ...
    SENSOR.GPS.horizontalPositionAccuracy_m;
gpsVerticalStd_m = ...
    SENSOR.GPS.verticalPositionAccuracy_m;
gpsVelocityStd_m_s = ...
    SENSOR.GPS.velocityAccuracy_m_s;
if ~isscalar(gpsHorizontalStd_m) || ...
        ~isfinite(gpsHorizontalStd_m) || ...
        gpsHorizontalStd_m <= 0
    error( ...
        'QuadrotorFramework:InvalidGPSHorizontalAccuracy', ...
        ['SENSOR.GPS.horizontalPositionAccuracy_m must be ', ...
         'finite and positive.']);
end
if ~isscalar(gpsVerticalStd_m) || ...
        ~isfinite(gpsVerticalStd_m) || ...
        gpsVerticalStd_m <= 0
    error( ...
        'QuadrotorFramework:InvalidGPSVerticalAccuracy', ...
        ['SENSOR.GPS.verticalPositionAccuracy_m must be ', ...
         'finite and positive.']);
end
if ~isscalar(gpsVelocityStd_m_s) || ...
        ~isfinite(gpsVelocityStd_m_s) || ...
        gpsVelocityStd_m_s <= 0
    error( ...
        'QuadrotorFramework:InvalidGPSVelocityAccuracy', ...
        ['SENSOR.GPS.velocityAccuracy_m_s must be ', ...
         'finite and positive.']);
end
ESTIMATOR.measurement.RposBase_m2 = ...
    diag([ ...
        gpsHorizontalStd_m^2, ...
        gpsHorizontalStd_m^2, ...
        gpsVerticalStd_m^2]);
ESTIMATOR.measurement.Rpos_m2 = ...
    ESTIMATOR.measurement.RposBase_m2;
ESTIMATOR.measurement.Rpos_m2(1,1) = ...
    ESTIMATOR.tuning.gpsPositionRScale_NE * ...
    ESTIMATOR.measurement.RposBase_m2(1,1);
ESTIMATOR.measurement.Rpos_m2(2,2) = ...
    ESTIMATOR.tuning.gpsPositionRScale_NE * ...
    ESTIMATOR.measurement.RposBase_m2(2,2);
ESTIMATOR.measurement.RvelBase_m2_s2 = ...
    diag([ ...
        gpsVelocityStd_m_s^2, ...
        gpsVelocityStd_m_s^2, ...
        gpsVelocityStd_m_s^2]);
ESTIMATOR.measurement.Rvel_m2_s2 = ...
    ESTIMATOR.measurement.RvelBase_m2_s2;
ESTIMATOR.measurement.Rvel_m2_s2(1,1) = ...
    ESTIMATOR.tuning.gpsVelocityRScale_NE * ...
    ESTIMATOR.measurement.RvelBase_m2_s2(1,1);
ESTIMATOR.measurement.Rvel_m2_s2(2,2) = ...
    ESTIMATOR.tuning.gpsVelocityRScale_NE * ...
    ESTIMATOR.measurement.RvelBase_m2_s2(2,2);
ESTIMATOR.measurement.Rvel_m2_s2(3,3) = ...
    ESTIMATOR.tuning.gpsVelocityRScale_D * ...
    ESTIMATOR.measurement.RvelBase_m2_s2(3,3);
baroNoiseDensity_Pa_sqrtHz = ...
    SENSOR.Barometer.noiseDensity_Pa_sqrtHz;
baroBiasInstabilityStd_Pa = ...
    SENSOR.Barometer.biasInstability_Pa;
if ~isscalar(baroNoiseDensity_Pa_sqrtHz) || ...
        ~isfinite(baroNoiseDensity_Pa_sqrtHz) || ...
        baroNoiseDensity_Pa_sqrtHz < 0
    error( ...
        'QuadrotorFramework:InvalidBarometerNoiseDensity', ...
        'Barometer noise density must be finite and nonnegative.');
end
if ~isscalar(baroBiasInstabilityStd_Pa) || ...
        ~isfinite(baroBiasInstabilityStd_Pa) || ...
        baroBiasInstabilityStd_Pa < 0
    error( ...
        'QuadrotorFramework:InvalidBarometerBiasInstability', ...
        'Barometer bias instability must be finite and nonnegative.');
end
baroWhiteNoiseStd_Pa = ...
    baroNoiseDensity_Pa_sqrtHz * ...
    sqrt( ...
        ESTIMATOR.rate.baro_Hz / 2);
baroPressureStd_Pa = ...
    sqrt( ...
        baroWhiteNoiseStd_Pa^2 + ...
        baroBiasInstabilityStd_Pa^2);
P0_Pa = ...
    101325.0;
T0_K = ...
    288.15;
L_K_m = ...
    0.0065;
g0_m_s2 = ...
    9.80665;
M_kg_mol = ...
    0.0289644;
R_J_mol_K = ...
    8.3144598;
referenceAltitude_m = ...
    ESTIMATOR.reference.lla_deg_m(3);
atmosphereExponent = ...
    (g0_m_s2 * M_kg_mol) / ...
    (R_J_mol_K * L_K_m);
atmosphereBase = ...
    1 - ...
    (L_K_m * referenceAltitude_m / T0_K);
if ~isfinite(atmosphereBase) || ...
        atmosphereBase <= 0
    error( ...
        'QuadrotorFramework:InvalidStandardAtmosphereReference', ...
        ['Reference altitude is outside the valid range of the ', ...
         'configured standard-atmosphere conversion.']);
end
referencePressure_Pa = ...
    P0_Pa * ...
    atmosphereBase^atmosphereExponent;
altitudeSensitivity_m_Pa = ...
    (T0_K / ...
    (L_K_m * atmosphereExponent * P0_Pa)) * ...
    (referencePressure_Pa / P0_Pa)^ ...
    ((1 / atmosphereExponent) - 1);
if ~isfinite(altitudeSensitivity_m_Pa) || ...
        altitudeSensitivity_m_Pa <= 0
    error( ...
        'QuadrotorFramework:InvalidBarometerAltitudeSensitivity', ...
        'Pressure-to-altitude sensitivity must be finite and positive.');
end
baroAltitudeStd_m = ...
    altitudeSensitivity_m_Pa * ...
    baroPressureStd_Pa;
ESTIMATOR.measurement.baroPressureStd_Pa = ...
    baroPressureStd_Pa;
ESTIMATOR.measurement.baroAltitudeSensitivity_m_Pa = ...
    altitudeSensitivity_m_Pa;
ESTIMATOR.measurement.baroStd_m = ...
    baroAltitudeStd_m;
ESTIMATOR.measurement.RbaroBase_m2 = ...
    baroAltitudeStd_m^2;
ESTIMATOR.measurement.Rbaro_m2 = ...
    ESTIMATOR.tuning.baroRScale * ...
    ESTIMATOR.measurement.RbaroBase_m2;
magNoiseDensity_uT_sqrtHz = ...
    reshape( ...
        SENSOR.IMU.mag.whiteNoisePSD_uT_sqrtHz, ...
        1, ...
        3);
if any(~isfinite(magNoiseDensity_uT_sqrtHz)) || ...
        any(magNoiseDensity_uT_sqrtHz < 0)
    error( ...
        'QuadrotorFramework:InvalidMagnetometerNoiseDensity', ...
        ['Magnetometer white-noise density must contain finite ', ...
         'nonnegative values.']);
end
magMeasurementStd_uT = ...
    magNoiseDensity_uT_sqrtHz .* ...
    sqrt( ...
        ESTIMATOR.rate.imu_Hz / 2);
ESTIMATOR.measurement.magStd_uT = ...
    magMeasurementStd_uT;
ESTIMATOR.measurement.RmagBase_uT2 = ...
    diag( ...
        magMeasurementStd_uT.^2);
ESTIMATOR.measurement.Rmag_uT2 = ...
    ESTIMATOR.tuning.magRScale .* ...
    ESTIMATOR.measurement.RmagBase_uT2;
gyroNoiseDensity_rad_s_sqrtHz = ...
    reshape( ...
        SENSOR.IMU.gyro.angleRandomWalk_rad_s_sqrtHz, ...
        1, ...
        3);
gyroMeasurementStd_rad_s = ...
    gyroNoiseDensity_rad_s_sqrtHz .* ...
    sqrt( ...
        ESTIMATOR.rate.imu_Hz / 2);
ESTIMATOR.process.GyroscopeNoiseBase = ...
    gyroMeasurementStd_rad_s.^2;
ESTIMATOR.process.GyroscopeNoise = ...
    ESTIMATOR.tuning.gyroNoiseScale .* ...
    ESTIMATOR.process.GyroscopeNoiseBase;
gyroBiasStd_rad_s = ...
    reshape( ...
        SENSOR.IMU.gyro.biasInstability_rad_s, ...
        1, ...
        3);
ESTIMATOR.process.GyroscopeBiasNoiseBase = [ ...
    1e-16, ...
    1e-16, ...
    1e-16];
ESTIMATOR.process.GyroscopeBiasNoise = ...
    ESTIMATOR.tuning.gyroBiasNoiseScale .* ...
    ESTIMATOR.process.GyroscopeBiasNoiseBase;
accelNoiseDensity_m_s2_sqrtHz = ...
    reshape( ...
        SENSOR.IMU.accel.velocityRandomWalk_m_s2_sqrtHz, ...
        1, ...
        3);
accelMeasurementStd_m_s2 = ...
    accelNoiseDensity_m_s2_sqrtHz .* ...
    sqrt( ...
        ESTIMATOR.rate.imu_Hz / 2);
ESTIMATOR.process.AccelerometerNoiseBase = ...
    accelMeasurementStd_m_s2.^2;
ESTIMATOR.process.AccelerometerNoise = ...
    ESTIMATOR.tuning.accelNoiseScale .* ...
    ESTIMATOR.process.AccelerometerNoiseBase;
accelBiasStd_m_s2 = ...
    reshape( ...
        SENSOR.IMU.accel.biasInstability_m_s2, ...
        1, ...
        3);
ESTIMATOR.process.AccelerometerBiasNoiseBase = [ ...
    2e-4, ...
    2e-4, ...
    2e-4];
ESTIMATOR.process.AccelerometerBiasNoise = ...
    ESTIMATOR.tuning.accelBiasNoiseScale .* ...
    ESTIMATOR.process.AccelerometerBiasNoiseBase;
magBiasStd_uT = ...
    reshape( ...
        SENSOR.IMU.mag.biasInstability_uT, ...
        1, ...
        3);
ESTIMATOR.process.MagnetometerBiasNoiseBase = [ ...
    1e-10, ...
    1e-10, ...
    1e-10];
ESTIMATOR.process.MagnetometerBiasNoise = ...
    ESTIMATOR.tuning.magBiasNoiseScale .* ...
    ESTIMATOR.process.MagnetometerBiasNoiseBase;
ESTIMATOR.process.GeomagneticVectorNoiseBase = [ ...
    1e-12, ...
    1e-12, ...
    1e-12];
ESTIMATOR.process.GeomagneticVectorNoise = ...
    ESTIMATOR.tuning.geomagneticVectorNoiseScale .* ...
    ESTIMATOR.process.GeomagneticVectorNoiseBase;
effectiveNoiseValues = [ ...
    ESTIMATOR.process.GyroscopeNoise(:); ...
    ESTIMATOR.process.GyroscopeBiasNoise(:); ...
    ESTIMATOR.process.AccelerometerNoise(:); ...
    ESTIMATOR.process.AccelerometerBiasNoise(:); ...
    ESTIMATOR.process.MagnetometerBiasNoise(:); ...
    ESTIMATOR.process.GeomagneticVectorNoise(:); ...
    diag(ESTIMATOR.measurement.Rpos_m2); ...
    diag(ESTIMATOR.measurement.Rvel_m2_s2); ...
    diag(ESTIMATOR.measurement.Rmag_uT2); ...
    ESTIMATOR.measurement.Rbaro_m2];
if any(~isfinite(effectiveNoiseValues)) || ...
        any(effectiveNoiseValues < 0)
    error( ...
        'QuadrotorFramework:InvalidEstimatorCovariance', ...
        ['Effective estimator process/measurement covariance ', ...
         'contains invalid values.']);
end
clear effectiveNoiseValues;
ESTIMATOR.initial.state = ...
    zeros(22,1);
ESTIMATOR.initial.state(1:4) = [ ...
    1; ...
    0; ...
    0; ...
    0];
ESTIMATOR.initial.state(5:7) = [ ...
    0; ...
    0; ...
    0];
ESTIMATOR.initial.state(8:10) = [ ...
    0; ...
    0; ...
    0];
gyroConstantBias_rad_s = ...
    reshape( ...
        SENSOR.IMU.gyro.constantBias_rad_s, ...
        3, ...
        1);
ESTIMATOR.initial.state(11:13) = ...
    gyroConstantBias_rad_s ./ ...
    ESTIMATOR.rate.imu_Hz;
accelConstantBias_m_s2 = ...
    reshape( ...
        SENSOR.IMU.accel.constantBias_m_s2, ...
        3, ...
        1);
ESTIMATOR.initial.state(14:16) = ...
    accelConstantBias_m_s2 ./ ...
    ESTIMATOR.rate.imu_Hz;
ESTIMATOR.initial.state(17:19) = ...
    reshape( ...
        SENSOR.IMU.mag.fieldNED_uT, ...
        3, ...
        1);
ESTIMATOR.initial.state(20:22) = ...
    reshape( ...
        SENSOR.IMU.mag.constantBias_uT, ...
        3, ...
        1);
P0Base = ...
    zeros(22,22);
P0Base(1:4,1:4) = ...
    1e-4 * eye(4);
P0Base(5,5) = ...
    gpsHorizontalStd_m^2;
P0Base(6,6) = ...
    gpsHorizontalStd_m^2;
P0Base(7,7) = ...
    ESTIMATOR.measurement.Rbaro_m2;
P0Base(8:10,8:10) = ...
    ESTIMATOR.measurement.Rvel_m2_s2;
deltaAngleBiasStd_rad = ...
    gyroBiasStd_rad_s ./ ...
    ESTIMATOR.rate.imu_Hz;
P0Base(11:13,11:13) = ...
    diag( ...
        deltaAngleBiasStd_rad.^2);
deltaVelocityBiasStd_m_s = ...
    accelBiasStd_m_s2 ./ ...
    ESTIMATOR.rate.imu_Hz;
P0Base(14:16,14:16) = ...
    diag( ...
        deltaVelocityBiasStd_m_s.^2);
P0Base(17:19,17:19) = ...
    ESTIMATOR.measurement.Rmag_uT2;
P0Base(20:22,20:22) = ...
    diag( ...
        magBiasStd_uT.^2);
ESTIMATOR.initial.StateCovarianceBase = ...
    P0Base;
P0 = ...
    P0Base;
P0(1:4,1:4) = ...
    ESTIMATOR.tuning.quaternionP0Scale .* ...
    P0Base(1:4,1:4);
P0(5,5) = ...
    ESTIMATOR.tuning.positionP0Scale_NE * ...
    P0Base(5,5);
P0(6,6) = ...
    ESTIMATOR.tuning.positionP0Scale_NE * ...
    P0Base(6,6);
P0(7,7) = ...
    ESTIMATOR.tuning.positionP0Scale_D * ...
    P0Base(7,7);
P0(8,8) = ...
    ESTIMATOR.tuning.velocityP0Scale_NE * ...
    P0Base(8,8);
P0(9,9) = ...
    ESTIMATOR.tuning.velocityP0Scale_NE * ...
    P0Base(9,9);
P0(10,10) = ...
    ESTIMATOR.tuning.velocityP0Scale_D * ...
    P0Base(10,10);
P0(11:13,11:13) = ...
    ESTIMATOR.tuning.gyroBiasP0Scale .* ...
    P0Base(11:13,11:13);
P0(14:16,14:16) = ...
    ESTIMATOR.tuning.accelBiasP0Scale .* ...
    P0Base(14:16,14:16);
P0(17:19,17:19) = ...
    ESTIMATOR.tuning.geomagneticP0Scale .* ...
    P0Base(17:19,17:19);
P0(20:22,20:22) = ...
    ESTIMATOR.tuning.magBiasP0Scale .* ...
    P0Base(20:22,20:22);
if any(~isfinite(P0(:))) || ...
        any(diag(P0) < 0)
    error( ...
        'QuadrotorFramework:InvalidEstimatorInitialCovariance', ...
        ['ESTIMATOR.initial.StateCovariance contains ', ...
         'invalid values.']);
end
ESTIMATOR.initial.StateCovariance = ...
    P0;
ESTIMATOR.initial.robustCovarianceScale.position_NE = ...
    ESTIMATOR.tuning.robustPositionP0Scale_NE;
ESTIMATOR.initial.robustCovarianceScale.position_D = ...
    ESTIMATOR.tuning.robustPositionP0Scale_D;
ESTIMATOR.initial.robustCovarianceScale.velocity_NE = ...
    ESTIMATOR.tuning.robustVelocityP0Scale_NE;
ESTIMATOR.initial.robustCovarianceScale.velocity_D = ...
    ESTIMATOR.tuning.robustVelocityP0Scale_D;
ESTIMATOR.output.conjugateFilterQuaternion = ...
    false;
ESTIMATOR.output.eulerSelector = [ ...
    3 ...
    2 ...
    1];
ESTIMATOR.acceleration.gravityCompensation = ...
    true;
ESTIMATOR.barometer.enableFusion = ...
    true;
ESTIMATOR.barometer.sampleRate_Hz = ...
    SENSOR.Barometer.sampleRate_Hz;
ESTIMATOR.barometer.sampleTime_s = ...
    SENSOR.Barometer.sampleTime_s;
ESTIMATOR.barometer.referenceAltitude_m = ...
    ESTIMATOR.reference.lla_deg_m(3);
ESTIMATOR.initialization.gpsSamples = ...
    20;
ESTIMATOR.initialization.baroSamples = ...
    20;
if ~isscalar(ESTIMATOR.initialization.gpsSamples) || ...
        ~isfinite(ESTIMATOR.initialization.gpsSamples) || ...
        ESTIMATOR.initialization.gpsSamples < 1 || ...
        ESTIMATOR.initialization.gpsSamples ~= ...
        round(ESTIMATOR.initialization.gpsSamples)
    error( ...
        'QuadrotorFramework:InvalidGPSInitializationSamples', ...
        ['ESTIMATOR.initialization.gpsSamples must be a ', ...
         'positive integer.']);
end
if ~isscalar(ESTIMATOR.initialization.baroSamples) || ...
        ~isfinite(ESTIMATOR.initialization.baroSamples) || ...
        ESTIMATOR.initialization.baroSamples < 1 || ...
        ESTIMATOR.initialization.baroSamples ~= ...
        round(ESTIMATOR.initialization.baroSamples)
    error( ...
        'QuadrotorFramework:InvalidBarometerInitializationSamples', ...
        ['ESTIMATOR.initialization.baroSamples must be a ', ...
         'positive integer.']);
end
ESTIMATOR.initialization.gpsDuration_s = ...
    ESTIMATOR.initialization.gpsSamples / ...
    ESTIMATOR.rate.gps_Hz;
if ESTIMATOR.barometer.enableFusion
    ESTIMATOR.initialization.baroDuration_s = ...
        ESTIMATOR.initialization.baroSamples / ...
        ESTIMATOR.rate.baro_Hz;
else
    ESTIMATOR.initialization.baroDuration_s = ...
        0.0;
end
ESTIMATOR.initialization.robustInitializationTime_s = ...
    max( ...
        ESTIMATOR.initialization.gpsDuration_s, ...
        ESTIMATOR.initialization.baroDuration_s);
ESTIMATOR.validation.warmupTime_s = ...
    0.5;
ESTIMATOR.health.positionStdMax_m = [ ...
    3.0; ...
    3.0; ...
    2.0];
ESTIMATOR.health.velocityStdMax_m_s = [ ...
    0.50; ...
    0.50; ...
    0.50];
ESTIMATOR.health.gpsInnovationSigmaMax = ...
    5.0;
ESTIMATOR.health.magInnovationSigmaMax = ...
    5.0;
ESTIMATOR.health.baroInnovationSigmaMax = ...
    5.0;
ESTIMATOR.health.gpsTimeout_s = ...
    0.50;
ESTIMATOR.health.magTimeout_s = ...
    0.50;
ESTIMATOR.health.baroTimeout_s = ...
    0.50;
ESTIMATOR.health.validConfirmationTime_s = ...
    0.50;
ESTIMATOR.health.invalidConfirmationTime_s = ...
    0.20;
if ~isscalar(ESTIMATOR.validation.warmupTime_s) || ...
        ~isfinite(ESTIMATOR.validation.warmupTime_s) || ...
        ESTIMATOR.validation.warmupTime_s < 0
    error( ...
        'QuadrotorFramework:InvalidEstimatorWarmupTime', ...
        ['ESTIMATOR.validation.warmupTime_s must be a finite ', ...
         'nonnegative scalar.']);
end
if ~isscalar(ESTIMATOR.health.validConfirmationTime_s) || ...
        ~isfinite(ESTIMATOR.health.validConfirmationTime_s) || ...
        ESTIMATOR.health.validConfirmationTime_s < 0
    error( ...
        'QuadrotorFramework:InvalidNavValidConfirmationTime', ...
        ['ESTIMATOR.health.validConfirmationTime_s must be a finite ', ...
         'nonnegative scalar.']);
end
if ~isscalar(ESTIMATOR.health.invalidConfirmationTime_s) || ...
        ~isfinite(ESTIMATOR.health.invalidConfirmationTime_s) || ...
        ESTIMATOR.health.invalidConfirmationTime_s < 0
    error( ...
        'QuadrotorFramework:InvalidNavInvalidConfirmationTime', ...
        ['ESTIMATOR.health.invalidConfirmationTime_s must be a finite ', ...
         'nonnegative scalar.']);
end
ESTIMATOR.validation.expectedNavValidTime_s = ...
    ESTIMATOR.initialization.robustInitializationTime_s + ...
    ESTIMATOR.health.validConfirmationTime_s;
ESTIMATOR.validation.metricStartTime_s = ...
    max( ...
        ESTIMATOR.validation.warmupTime_s, ...
        ESTIMATOR.validation.expectedNavValidTime_s);
if ~isnumeric(ESTIMATOR.tuning.schemaVersion) || ...
        ~isscalar(ESTIMATOR.tuning.schemaVersion)
    error( ...
        'QuadrotorFramework:InvalidEstimatorTuningSchema', ...
        'ESTIMATOR tuning schema must be a numerical scalar.');
end
if ~isnumeric(ESTIMATOR.tuning.parameterCount) || ...
        ~isscalar(ESTIMATOR.tuning.parameterCount) || ...
        ESTIMATOR.tuning.parameterCount ~= 24
    error( ...
        'QuadrotorFramework:InvalidEstimatorTuningParameterCount', ...
        'The estimator tuning contract must contain 24 parameters.');
end
if ~estimatorTuningSilent
    disp(' ');
    disp( ...
        '==============================================================');
    disp( ...
        ' UAV State Estimator parameters loaded.');
    disp( ...
        '==============================================================');
    fprintf( ...
        'Estimator:                insfilterMARG EKF\n');
    fprintf( ...
        'Navigation frame:         NED\n');
    fprintf( ...
        'Tuning schema:            %.1f\n', ...
        tuningSchemaVersion);
    fprintf( ...
        'Tuning source:            %s\n', ...
        tuningSourceText);
    fprintf( ...
        'Tuning override active:   %d\n', ...
        ESTIMATOR.tuning.overrideActive);
    fprintf( ...
        'Tuneable parameters:      %d\n', ...
        ESTIMATOR.tuning.parameterCount);
    fprintf( ...
        'IMU prediction rate:      %.1f Hz\n', ...
        ESTIMATOR.rate.imu_Hz);
    fprintf( ...
        'Mag fusion rate:          %.1f Hz\n', ...
        ESTIMATOR.rate.magFusion_Hz);
    fprintf( ...
        'GPS fusion rate:          %.1f Hz\n', ...
        ESTIMATOR.rate.gps_Hz);
    fprintf( ...
        'Barometer fusion rate:    %.1f Hz\n', ...
        ESTIMATOR.rate.baro_Hz);
    fprintf( ...
        'IMU sample time:          %.6f s\n', ...
        ESTIMATOR.rate.imuSampleTime_s);
    fprintf( ...
        'Reference LLA:            [%.6f %.6f %.2f]\n', ...
        ESTIMATOR.reference.lla_deg_m(1), ...
        ESTIMATOR.reference.lla_deg_m(2), ...
        ESTIMATOR.reference.lla_deg_m(3));
    fprintf( ...
        'GPS init samples:         %d\n', ...
        ESTIMATOR.initialization.gpsSamples);
    fprintf( ...
        'GPS init duration:        %.3f s\n', ...
        ESTIMATOR.initialization.gpsDuration_s);
    fprintf( ...
        'Barometer init samples:   %d\n', ...
        ESTIMATOR.initialization.baroSamples);
    fprintf( ...
        'Barometer init duration:  %.3f s\n', ...
        ESTIMATOR.initialization.baroDuration_s);
    fprintf( ...
        'Robust init time:         %.3f s\n', ...
        ESTIMATOR.initialization.robustInitializationTime_s);
    fprintf( ...
        'NavValid confirmation:    %.3f s\n', ...
        ESTIMATOR.health.validConfirmationTime_s);
    fprintf( ...
        'Expected NavValid time:   %.3f s\n', ...
        ESTIMATOR.validation.expectedNavValidTime_s);
    fprintf( ...
        'Estimator metric start:   %.3f s\n', ...
        ESTIMATOR.validation.metricStartTime_s);
    disp( ...
        '--------------------------------------------------------------');
    fprintf( ...
        'Q gyro noise scale:       %.6g\n', ...
        ESTIMATOR.tuning.gyroNoiseScale);
    fprintf( ...
        'Q gyro-bias scale:        %.6g\n', ...
        ESTIMATOR.tuning.gyroBiasNoiseScale);
    fprintf( ...
        'Q accel noise scale:      %.6g\n', ...
        ESTIMATOR.tuning.accelNoiseScale);
    fprintf( ...
        'Q accel-bias scale:       %.6g\n', ...
        ESTIMATOR.tuning.accelBiasNoiseScale);
    fprintf( ...
        'Q mag-bias scale:         %.6g\n', ...
        ESTIMATOR.tuning.magBiasNoiseScale);
    fprintf( ...
        'Q geomagnetic scale:      %.6g\n', ...
        ESTIMATOR.tuning.geomagneticVectorNoiseScale);
    disp( ...
        '--------------------------------------------------------------');
    fprintf( ...
        'R GPS position NE:        %.6g\n', ...
        ESTIMATOR.tuning.gpsPositionRScale_NE);
    fprintf( ...
        'R GPS velocity NE:        %.6g\n', ...
        ESTIMATOR.tuning.gpsVelocityRScale_NE);
    fprintf( ...
        'R GPS velocity D:         %.6g\n', ...
        ESTIMATOR.tuning.gpsVelocityRScale_D);
    fprintf( ...
        'R magnetometer:           %.6g\n', ...
        ESTIMATOR.tuning.magRScale);
    fprintf( ...
        'R barometer:              %.6g\n', ...
        ESTIMATOR.tuning.baroRScale);
    disp( ...
        '--------------------------------------------------------------');
    fprintf( ...
        'P0 quaternion:            %.6g\n', ...
        ESTIMATOR.tuning.quaternionP0Scale);
    fprintf( ...
        'P0 position NE:           %.6g\n', ...
        ESTIMATOR.tuning.positionP0Scale_NE);
    fprintf( ...
        'P0 position D:            %.6g\n', ...
        ESTIMATOR.tuning.positionP0Scale_D);
    fprintf( ...
        'P0 velocity NE:           %.6g\n', ...
        ESTIMATOR.tuning.velocityP0Scale_NE);
    fprintf( ...
        'P0 velocity D:            %.6g\n', ...
        ESTIMATOR.tuning.velocityP0Scale_D);
    fprintf( ...
        'P0 gyro bias:             %.6g\n', ...
        ESTIMATOR.tuning.gyroBiasP0Scale);
    fprintf( ...
        'P0 accel bias:            %.6g\n', ...
        ESTIMATOR.tuning.accelBiasP0Scale);
    fprintf( ...
        'P0 geomagnetic:           %.6g\n', ...
        ESTIMATOR.tuning.geomagneticP0Scale);
    fprintf( ...
        'P0 magnetometer bias:     %.6g\n', ...
        ESTIMATOR.tuning.magBiasP0Scale);
    disp( ...
        '--------------------------------------------------------------');
    fprintf( ...
        'Robust P0 position NE:    %.6g\n', ...
        ESTIMATOR.tuning.robustPositionP0Scale_NE);
    fprintf( ...
        'Robust P0 position D:     %.6g\n', ...
        ESTIMATOR.tuning.robustPositionP0Scale_D);
    fprintf( ...
        'Robust P0 velocity NE:    %.6g\n', ...
        ESTIMATOR.tuning.robustVelocityP0Scale_NE);
    fprintf( ...
        'Robust P0 velocity D:     %.6g\n', ...
        ESTIMATOR.tuning.robustVelocityP0Scale_D);
    disp( ...
        '--------------------------------------------------------------');
    fprintf( ...
        'GyroBiasNoise effective:  [%.3e %.3e %.3e]\n', ...
        ESTIMATOR.process.GyroscopeBiasNoise(1), ...
        ESTIMATOR.process.GyroscopeBiasNoise(2), ...
        ESTIMATOR.process.GyroscopeBiasNoise(3));
    fprintf( ...
        'AccelBiasNoise effective: [%.3e %.3e %.3e]\n', ...
        ESTIMATOR.process.AccelerometerBiasNoise(1), ...
        ESTIMATOR.process.AccelerometerBiasNoise(2), ...
        ESTIMATOR.process.AccelerometerBiasNoise(3));
    fprintf( ...
        'Barometer EKF fusion:     %d\n', ...
        ESTIMATOR.barometer.enableFusion);
    fprintf( ...
        'Barometer pressure std:   %.4f Pa\n', ...
        ESTIMATOR.measurement.baroPressureStd_Pa);
    fprintf( ...
        'Pressure -> altitude:     %.6f m/Pa\n', ...
        ESTIMATOR.measurement.baroAltitudeSensitivity_m_Pa);
    fprintf( ...
        'Barometer altitude std:   %.4f m\n', ...
        ESTIMATOR.measurement.baroStd_m);
    fprintf( ...
        'Barometer R base:         %.6f m^2\n', ...
        ESTIMATOR.measurement.RbaroBase_m2);
    fprintf( ...
        'Barometer R effective:    %.6f m^2\n', ...
        ESTIMATOR.measurement.Rbaro_m2);
    disp( ...
        '==============================================================');
    disp(' ');
end
clear tuningParameterNames ...
    tuningParameterCount ...
    tuningParameterIndex ...
    tuningParameterName ...
    tuningParameterValue ...
    tuningSchemaVersion ...
    tuningSourceText ...
    estimatorTuningSilent ...
    nominalTuningVector ...
    currentTuningVector ...
    P0 ...
    P0Base ...
    gpsHorizontalStd_m ...
    gpsVerticalStd_m ...
    gpsVelocityStd_m_s ...
    baroNoiseDensity_Pa_sqrtHz ...
    baroBiasInstabilityStd_Pa ...
    baroWhiteNoiseStd_Pa ...
    baroPressureStd_Pa ...
    P0_Pa ...
    T0_K ...
    L_K_m ...
    g0_m_s2 ...
    M_kg_mol ...
    R_J_mol_K ...
    referenceAltitude_m ...
    atmosphereExponent ...
    atmosphereBase ...
    referencePressure_Pa ...
    altitudeSensitivity_m_Pa ...
    baroAltitudeStd_m ...
    magNoiseDensity_uT_sqrtHz ...
    magMeasurementStd_uT ...
    gyroNoiseDensity_rad_s_sqrtHz ...
    gyroMeasurementStd_rad_s ...
    gyroBiasStd_rad_s ...
    accelNoiseDensity_m_s2_sqrtHz ...
    accelMeasurementStd_m_s2 ...
    accelBiasStd_m_s2 ...
    magBiasStd_uT ...
    gyroConstantBias_rad_s ...
    accelConstantBias_m_s2 ...
    deltaAngleBiasStd_rad ...
    deltaVelocityBiasStd_m_s;
if exist('silentValue','var')
    clear silentValue;
end
if exist('overrideFieldNames','var')
    clear overrideFieldNames ...
        overrideFieldIndex ...
        overrideFieldName;
end
