if ~exist('P_ENV','var')
    error( ...
        'QuadrotorFramework:MissingEnvironmentParameters', ...
        ['P_ENV does not exist. Run Environment.m before ', ...
         'UAV_sensors.m.']);
end
SENSOR = struct();
SENSOR.info.reference_vehicle = ...
    "Reference Quadrotor";
SENSOR.info.model_type = ...
    "Common simulated sensor suite";
SENSOR.frame.navigation = ...
    "NED";
SENSOR.frame.body_x = ...
    "Forward";
SENSOR.frame.body_y = ...
    "Right";
SENSOR.frame.body_z = ...
    "Down";
SENSOR.reference.location_lla_deg_m = [ ...
    P_ENV.location.latitude_ref_deg, ...
    P_ENV.location.longitude_ref_deg, ...
    P_ENV.location.altitude_ref_m];
SENSOR.reference.latitude_deg = ...
    SENSOR.reference.location_lla_deg_m(1);
SENSOR.reference.longitude_deg = ...
    SENSOR.reference.location_lla_deg_m(2);
SENSOR.reference.altitude_m = ...
    SENSOR.reference.location_lla_deg_m(3);
SENSOR.IMU.sampleRate_Hz = ...
    200;
SENSOR.IMU.sampleTime_s = ...
    1 / SENSOR.IMU.sampleRate_Hz;
SENSOR.IMU.referenceFrame = ...
    "NED";
SENSOR.IMU.temperature_C = ...
    25;
SENSOR.IMU.seed = ...
    67;
SENSOR.IMU.accel.maximumReading_m_s2 = ...
    16 * 9.80665;
SENSOR.IMU.accel.resolution_m_s2_LSB = ...
    1.0e-3;
SENSOR.IMU.accel.constantBias_m_s2 = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.accel.axesSkew_percent = ...
    100 * eye(3);
SENSOR.IMU.accel.velocityRandomWalk_m_s2_sqrtHz = [ ...
    0.004 ...
    0.004 ...
    0.004];
SENSOR.IMU.accel.biasInstability_m_s2 = [ ...
    0.020 ...
    0.020 ...
    0.020];
SENSOR.IMU.accel.accelerationRandomWalk_m_s2_sqrtHz = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.accel.noiseType = ...
    "double-sided";
SENSOR.IMU.accel.temperatureBias_m_s2_per_C = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.accel.temperatureScaleFactor_percent_per_C = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.gyro.maximumReading_rad_s = ...
    deg2rad(2000);
SENSOR.IMU.gyro.resolution_rad_s_LSB = ...
    deg2rad(0.01);
SENSOR.IMU.gyro.constantBias_rad_s = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.gyro.axesSkew_percent = ...
    100 * eye(3);
SENSOR.IMU.gyro.biasFromAcceleration_rad_s_per_m_s2 = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.gyro.angleRandomWalk_rad_s_sqrtHz = ...
    deg2rad([ ...
    0.02 ...
    0.02 ...
    0.02]);
SENSOR.IMU.gyro.biasInstability_rad_s = ...
    deg2rad([ ...
    0.05 ...
    0.05 ...
    0.05]);
SENSOR.IMU.gyro.rateRandomWalk_rad_s_sqrtHz = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.gyro.noiseType = ...
    "double-sided";
SENSOR.IMU.gyro.temperatureBias_rad_s_per_C = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.gyro.temperatureScaleFactor_percent_per_C = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.mag.model = ...
    "WMM2025";
SENSOR.IMU.mag.modelDecimalYear = ...
    2026.0;
magneticFieldNED_nT = wrldmagm( ...
    SENSOR.reference.altitude_m, ...
    SENSOR.reference.latitude_deg, ...
    SENSOR.reference.longitude_deg, ...
    SENSOR.IMU.mag.modelDecimalYear, ...
    '2025');
SENSOR.IMU.mag.fieldNED_uT = ...
    reshape( ...
        magneticFieldNED_nT, ...
        1, ...
        3) / 1000;
SENSOR.IMU.mag.maximumReading_uT = ...
    1000;
SENSOR.IMU.mag.resolution_uT_LSB = ...
    0.15;
SENSOR.IMU.mag.constantBias_uT = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.mag.axesSkew_percent = ...
    100 * eye(3);
SENSOR.IMU.mag.whiteNoisePSD_uT_sqrtHz = [ ...
    0.05 ...
    0.05 ...
    0.05];
SENSOR.IMU.mag.biasInstability_uT = [ ...
    0.10 ...
    0.10 ...
    0.10];
SENSOR.IMU.mag.randomWalk_uT_sqrtHz = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.mag.noiseType = ...
    "double-sided";
SENSOR.IMU.mag.temperatureBias_uT_per_C = [ ...
    0 ...
    0 ...
    0];
SENSOR.IMU.mag.temperatureScaleFactor_percent_per_C = [ ...
    0 ...
    0 ...
    0];
SENSOR.GPS.sampleRate_Hz = ...
    10;
SENSOR.GPS.sampleTime_s = ...
    1 / SENSOR.GPS.sampleRate_Hz;
SENSOR.GPS.referenceFrame = ...
    "NED";
SENSOR.GPS.positionInputFormat = ...
    "Local";
SENSOR.GPS.referenceLocation_lla_deg_m = ...
    SENSOR.reference.location_lla_deg_m;
SENSOR.GPS.horizontalPositionAccuracy_m = ...
    1.6;
SENSOR.GPS.verticalPositionAccuracy_m = ...
    3.0;
SENSOR.GPS.velocityAccuracy_m_s = ...
    0.1;
SENSOR.GPS.decayFactor = ...
    0;
SENSOR.GPS.seed = ...
    68;
SENSOR.Barometer.sampleRate_Hz = ...
    20;
SENSOR.Barometer.sampleTime_s = ...
    1 / SENSOR.Barometer.sampleRate_Hz;
SENSOR.Barometer.constantBias_Pa = ...
    0;
SENSOR.Barometer.noiseDensity_Pa_sqrtHz = ...
    1;
SENSOR.Barometer.biasInstability_Pa = ...
    1;
SENSOR.Barometer.decayFactor = ...
    0.99;
SENSOR.Barometer.seed = ...
    69;
disp(' ');
disp( ...
    '==============================================================');
disp( ...
    ' UAV Sensor parameters loaded.');
disp( ...
    '==============================================================');
fprintf( ...
    'Reference LLA:            [%.6f %.6f %.2f]\n', ...
    SENSOR.reference.latitude_deg, ...
    SENSOR.reference.longitude_deg, ...
    SENSOR.reference.altitude_m);
fprintf( ...
    'IMU rate:                 %.1f Hz\n', ...
    SENSOR.IMU.sampleRate_Hz);
fprintf( ...
    'GPS rate:                 %.1f Hz\n', ...
    SENSOR.GPS.sampleRate_Hz);
fprintf( ...
    'Barometer rate:           %.1f Hz\n', ...
    SENSOR.Barometer.sampleRate_Hz);
fprintf( ...
    'Magnetic model:           %s\n', ...
    SENSOR.IMU.mag.model);
fprintf( ...
    'Magnetic field NED [uT]:  [%.4f %.4f %.4f]\n', ...
    SENSOR.IMU.mag.fieldNED_uT(1), ...
    SENSOR.IMU.mag.fieldNED_uT(2), ...
    SENSOR.IMU.mag.fieldNED_uT(3));
disp( ...
    '==============================================================');
disp(' ');
