if ~exist('P_ENV','var')
    error( ...
        'QuadrotorFramework:MissingEnvironmentParameters', ...
        ['P_ENV does not exist. Run Environment.m before ', ...
         'UAV_autopilot.m.']);
end
if ~exist('SENSOR','var')
    error( ...
        'QuadrotorFramework:MissingSensorParameters', ...
        ['SENSOR does not exist. Run UAV_sensors.m before ', ...
         'UAV_autopilot.m.']);
end
if ~exist('A_UAV','var')
    error( ...
        'QuadrotorFramework:MissingAnalyticalParameters', ...
        ['A_UAV does not exist. Run UAV_analytical.m before ', ...
         'UAV_autopilot.m.']);
end
AUTOPILOT = ...
    struct();
AUTOPILOT.info.name = ...
    "Common Cascaded Quadrotor Autopilot";
AUTOPILOT.info.vehicle = ...
    "Reference Quadrotor";
AUTOPILOT.info.controller = ...
    "Cascaded P / PI / PD";
AUTOPILOT.info.referenceFrame = ...
    "NED";
AUTOPILOT.info.bodyFrame = ...
    "FRD";
AUTOPILOT.info.parameterSource = ...
    "UAV_autopilot.m";
AUTOPILOT.info.controllerGainSchema = ...
    "2.0";
AUTOPILOT.info.controllerGainSource = ...
    "TUNED_2026-09-04";
AUTOPILOT.info.controllerTuningCampaign = ...
    "Controller_Tuning_2026-09-04_20-48-43";
AUTOPILOT.mode.disarmed = ...
    1;
AUTOPILOT.mode.armed = ...
    2;
AUTOPILOT.mode.stabilized = ...
    3;
AUTOPILOT.mode.altitude = ...
    4;
AUTOPILOT.mode.position = ...
    5;
AUTOPILOT.mode.trajectory = ...
    6;
AUTOPILOT.mode.navFailsafe = ...
    7;
AUTOPILOT.rate.control_Hz = ...
    SENSOR.IMU.sampleRate_Hz;
AUTOPILOT.rate.controlSampleTime_s = ...
    1 / ...
    AUTOPILOT.rate.control_Hz;
AUTOPILOT.rate.position_Hz = ...
    AUTOPILOT.rate.control_Hz;
AUTOPILOT.rate.velocity_Hz = ...
    AUTOPILOT.rate.control_Hz;
AUTOPILOT.rate.attitude_Hz = ...
    AUTOPILOT.rate.control_Hz;
AUTOPILOT.rate.angularRate_Hz = ...
    AUTOPILOT.rate.control_Hz;
AUTOPILOT.supervisor.controlMode = ...
    AUTOPILOT.mode.trajectory;
AUTOPILOT.supervisor.resetWhenDisabled = ...
    true;
AUTOPILOT.gravity.magnitude_m_s2 = ...
    P_ENV.gravity.magnitude_m_s2;
AUTOPILOT.gravity.ned_m_s2 = [ ...
    0;
    0;
    AUTOPILOT.gravity.magnitude_m_s2];
AUTOPILOT.failsafe.navigation.descentRate_m_s = ...
    0.30;
AUTOPILOT.hover.omegaTrim_rad_s = ...
    reshape( ...
        A_UAV.trim.hover_omega_rad_s, ...
        4, ...
        1);
AUTOPILOT.hover.collectiveOmega_rad_s = ...
    mean( ...
        AUTOPILOT.hover.omegaTrim_rad_s);
AUTOPILOT.hover.idleFraction = ...
    0.10;
AUTOPILOT.hover.idleOmega_rad_s = ...
    AUTOPILOT.hover.idleFraction .* ...
    AUTOPILOT.hover.omegaTrim_rad_s;
AUTOPILOT.pid.derivativeFilterCoefficient = ...
    100;
AUTOPILOT.horizontal.position.north.type = ...
    "P";
AUTOPILOT.horizontal.position.north.Kp = ...
    0.630229617983284;
AUTOPILOT.horizontal.position.north.Ki = ...
    0.0;
AUTOPILOT.horizontal.position.north.Kd = ...
    0.0;
AUTOPILOT.horizontal.position.north.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.horizontal.position.east.type = ...
    "P";
AUTOPILOT.horizontal.position.east.Kp = ...
    0.922964403505628;
AUTOPILOT.horizontal.position.east.Ki = ...
    0.0;
AUTOPILOT.horizontal.position.east.Kd = ...
    0.0;
AUTOPILOT.horizontal.position.east.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.horizontal.position.maxVelocity_m_s = ...
    1.0;
AUTOPILOT.horizontal.position.minVelocity_m_s = ...
   -AUTOPILOT.horizontal.position.maxVelocity_m_s;
AUTOPILOT.horizontal.velocity.x.type = ...
    "PD";
AUTOPILOT.horizontal.velocity.x.Kp = ...
    2.27880105953139;
AUTOPILOT.horizontal.velocity.x.Ki = ...
    0.0;
AUTOPILOT.horizontal.velocity.x.Kd = ...
    0.0129600806350967;
AUTOPILOT.horizontal.velocity.x.N = ...
    1.89017452955744;
AUTOPILOT.horizontal.velocity.x.integratorUpperLimit = ...
    0.2;
AUTOPILOT.horizontal.velocity.x.integratorLowerLimit = ...
   -0.2;
AUTOPILOT.horizontal.velocity.y.type = ...
    "P";
AUTOPILOT.horizontal.velocity.y.Kp = ...
    0.957100556136435;
AUTOPILOT.horizontal.velocity.y.Ki = ...
    0.0;
AUTOPILOT.horizontal.velocity.y.Kd = ...
    0.0;
AUTOPILOT.horizontal.velocity.y.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.horizontal.velocity.y.integratorUpperLimit = ...
    0.2;
AUTOPILOT.horizontal.velocity.y.integratorLowerLimit = ...
   -0.2;
AUTOPILOT.horizontal.velocity.maxAcceleration_m_s2 = ...
    3.0;
AUTOPILOT.horizontal.velocity.minAcceleration_m_s2 = ...
   -AUTOPILOT.horizontal.velocity.maxAcceleration_m_s2;
AUTOPILOT.horizontal.accelerationToTiltMethod = ...
    "atan";
AUTOPILOT.horizontal.maxTilt_deg = ...
    20;
AUTOPILOT.horizontal.maxTilt_rad = ...
    deg2rad( ...
        AUTOPILOT.horizontal.maxTilt_deg);
AUTOPILOT.vertical.altitude.type = ...
    "P";
AUTOPILOT.vertical.altitude.Kp = ...
    0.29251183693788;
AUTOPILOT.vertical.altitude.Ki = ...
    0.0;
AUTOPILOT.vertical.altitude.Kd = ...
    0.0;
AUTOPILOT.vertical.altitude.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.vertical.altitude.integratorUpperLimit = ...
    0.1;
AUTOPILOT.vertical.altitude.integratorLowerLimit = ...
   -0.1;
AUTOPILOT.vertical.altitude.maxVelocity_m_s = ...
    0.6;
AUTOPILOT.vertical.altitude.minVelocity_m_s = ...
   -AUTOPILOT.vertical.altitude.maxVelocity_m_s;
AUTOPILOT.vertical.velocity.type = ...
    "P";
AUTOPILOT.vertical.velocity.Kp = ...
    179.235177723946;
AUTOPILOT.vertical.velocity.Ki = ...
    0.0;
AUTOPILOT.vertical.velocity.Kd = ...
    0.0;
AUTOPILOT.vertical.velocity.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.vertical.velocity.integratorUpperLimit = ...
    0.1;
AUTOPILOT.vertical.velocity.integratorLowerLimit = ...
   -0.1;
AUTOPILOT.vertical.velocity.maxAxisCommand_rad_s = ...
    300;
AUTOPILOT.vertical.velocity.minAxisCommand_rad_s = ...
   -AUTOPILOT.vertical.velocity.maxAxisCommand_rad_s;
AUTOPILOT.vertical.velocity.outputUpperLimit = ...
    AUTOPILOT.vertical.velocity.maxAxisCommand_rad_s;
AUTOPILOT.vertical.velocity.outputLowerLimit = ...
    AUTOPILOT.vertical.velocity.minAxisCommand_rad_s;
AUTOPILOT.vertical.velocity.enableTiltCompensation = ...
    true;
AUTOPILOT.vertical.velocity.tiltCompensationOmega_rad_s = ...
    AUTOPILOT.hover.collectiveOmega_rad_s;
AUTOPILOT.yaw.angle.type = ...
    "P";
AUTOPILOT.yaw.angle.Kp = ...
    9.73729968814403;
AUTOPILOT.yaw.angle.Ki = ...
    0.0;
AUTOPILOT.yaw.angle.Kd = ...
    0.0;
AUTOPILOT.yaw.angle.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.yaw.angle.maxYawRate_deg_s = ...
    60;
AUTOPILOT.yaw.angle.maxYawRate_rad_s = ...
    deg2rad( ...
        AUTOPILOT.yaw.angle.maxYawRate_deg_s);
AUTOPILOT.yaw.angle.minYawRate_rad_s = ...
   -AUTOPILOT.yaw.angle.maxYawRate_rad_s;
AUTOPILOT.attitude.roll.type = ...
    "P";
AUTOPILOT.attitude.roll.Kp = ...
    16.2440865261587;
AUTOPILOT.attitude.roll.Ki = ...
    0.0;
AUTOPILOT.attitude.roll.Kd = ...
    0.0;
AUTOPILOT.attitude.roll.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.attitude.pitch.type = ...
    "P";
AUTOPILOT.attitude.pitch.Kp = ...
    15.9794896676744;
AUTOPILOT.attitude.pitch.Ki = ...
    0.0;
AUTOPILOT.attitude.pitch.Kd = ...
    0.0;
AUTOPILOT.attitude.pitch.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.attitude.maxRate_deg_s = ...
    60;
AUTOPILOT.attitude.maxRate_rad_s = ...
    deg2rad( ...
        AUTOPILOT.attitude.maxRate_deg_s);
AUTOPILOT.attitude.minRate_rad_s = ...
   -AUTOPILOT.attitude.maxRate_rad_s;
AUTOPILOT.attitude.outputUpperLimit = ...
    AUTOPILOT.attitude.maxRate_rad_s;
AUTOPILOT.attitude.outputLowerLimit = ...
    AUTOPILOT.attitude.minRate_rad_s;
AUTOPILOT.eulerRateToBodyRate.enable = ...
    true;
AUTOPILOT.angularRate.roll.type = ...
    "PI";
AUTOPILOT.angularRate.roll.Kp = ...
    192.002243650807;
AUTOPILOT.angularRate.roll.Ki = ...
    36.7166740442623;
AUTOPILOT.angularRate.roll.Kd = ...
    0.0;
AUTOPILOT.angularRate.roll.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.angularRate.roll.integratorUpperLimit = ...
    0.2;
AUTOPILOT.angularRate.roll.integratorLowerLimit = ...
   -0.2;
AUTOPILOT.angularRate.pitch.type = ...
    "PI";
AUTOPILOT.angularRate.pitch.Kp = ...
    116.955688320571;
AUTOPILOT.angularRate.pitch.Ki = ...
    324.349522335245;
AUTOPILOT.angularRate.pitch.Kd = ...
    0.0;
AUTOPILOT.angularRate.pitch.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.angularRate.pitch.integratorUpperLimit = ...
    0.2;
AUTOPILOT.angularRate.pitch.integratorLowerLimit = ...
   -0.2;
AUTOPILOT.angularRate.rollPitchLimits.maxAxisCommand_rad_s = ...
    20;
AUTOPILOT.angularRate.rollPitchLimits.minAxisCommand_rad_s = ...
   -AUTOPILOT.angularRate.rollPitchLimits.maxAxisCommand_rad_s;
AUTOPILOT.angularRate.rollPitchLimits.outputUpperLimit = ...
    AUTOPILOT.angularRate.rollPitchLimits.maxAxisCommand_rad_s;
AUTOPILOT.angularRate.rollPitchLimits.outputLowerLimit = ...
    AUTOPILOT.angularRate.rollPitchLimits.minAxisCommand_rad_s;
AUTOPILOT.angularRate.yaw.type = ...
    "PI";
AUTOPILOT.angularRate.yaw.Kp = ...
    513.270796124145;
AUTOPILOT.angularRate.yaw.Ki = ...
    48.9668949194481;
AUTOPILOT.angularRate.yaw.Kd = ...
    0.0;
AUTOPILOT.angularRate.yaw.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.angularRate.yaw.integratorUpperLimit = ...
    0.2;
AUTOPILOT.angularRate.yaw.integratorLowerLimit = ...
   -0.2;
AUTOPILOT.angularRate.yaw.maxAxisCommand_rad_s = ...
    100;
AUTOPILOT.angularRate.yaw.minAxisCommand_rad_s = ...
   -AUTOPILOT.angularRate.yaw.maxAxisCommand_rad_s;
AUTOPILOT.angularRate.yaw.outputUpperLimit = ...
    AUTOPILOT.angularRate.yaw.maxAxisCommand_rad_s;
AUTOPILOT.angularRate.yaw.outputLowerLimit = ...
    AUTOPILOT.angularRate.yaw.minAxisCommand_rad_s;
AUTOPILOT.allocation.effectiveMatrix = [ ...
   -1,  1, -1; ...
    1, -1, -1; ...
   -1, -1,  1; ...
    1,  1,  1];
AUTOPILOT.allocation.collectiveVector = ...
    -ones(4,1);
AUTOPILOT.allocation.useTrimVector = ...
    true;
AUTOPILOT.allocation.omegaTrim_rad_s = ...
    AUTOPILOT.hover.omegaTrim_rad_s;
AUTOPILOT.motor.disarmedOmega_rad_s = ...
    zeros(4,1);
AUTOPILOT.motor.armedIdleOmega_rad_s = ...
    AUTOPILOT.hover.idleOmega_rad_s;
AUTOPILOT.motor.minOmega_rad_s = ...
    0;
AUTOPILOT.motor.maxOmega_rad_s = ...
    inf;
AUTOPILOT.limits.maxHorizontalVelocity_m_s = ...
    AUTOPILOT.horizontal.position.maxVelocity_m_s;
AUTOPILOT.limits.maxVerticalVelocity_m_s = ...
    AUTOPILOT.vertical.altitude.maxVelocity_m_s;
AUTOPILOT.limits.maxHorizontalAcceleration_m_s2 = ...
    AUTOPILOT.horizontal.velocity.maxAcceleration_m_s2;
AUTOPILOT.limits.maxTilt_deg = ...
    AUTOPILOT.horizontal.maxTilt_deg;
AUTOPILOT.limits.maxTilt_rad = ...
    AUTOPILOT.horizontal.maxTilt_rad;
AUTOPILOT.limits.maxYawRate_rad_s = ...
    AUTOPILOT.yaw.angle.maxYawRate_rad_s;
AUTOPILOT.limits.maxRollPitchRate_rad_s = ...
    AUTOPILOT.attitude.maxRate_rad_s;
AUTOPILOT.envelope.maxNorth_m = ...
    1.75;
AUTOPILOT.envelope.maxEast_m = ...
    1.75;
AUTOPILOT.envelope.maxAltitude_m = ...
    2.5;
AUTOPILOT.interface.flightControlOutput = [ ...
    "rollAxis"; ...
    "pitchAxis"; ...
    "yawAxis"; ...
    "thrustAxis"];
AUTOPILOT.interface.flightControlOutputUnits = [ ...
    "rad/s motor differential"; ...
    "rad/s motor differential"; ...
    "rad/s motor differential"; ...
    "rad/s collective correction"];
AUTOPILOT.horizontal.position.Kp = ...
    AUTOPILOT.horizontal.position.north.Kp;
AUTOPILOT.horizontal.position.Ki = ...
    0.0;
AUTOPILOT.horizontal.position.Kd = ...
    0.0;
AUTOPILOT.horizontal.position.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.horizontal.position.integratorLimit = ...
    0.2;
AUTOPILOT.horizontal.velocity.Kp = ...
    AUTOPILOT.horizontal.velocity.x.Kp;
AUTOPILOT.horizontal.velocity.Ki = ...
    0.0;
AUTOPILOT.horizontal.velocity.Kd = ...
    AUTOPILOT.horizontal.velocity.x.Kd;
AUTOPILOT.horizontal.velocity.N = ...
    AUTOPILOT.horizontal.velocity.x.N;
AUTOPILOT.horizontal.velocity.integratorLimit = ...
    0.2;
AUTOPILOT.attitude.rollPitch.Kp = ...
    AUTOPILOT.attitude.roll.Kp;
AUTOPILOT.attitude.rollPitch.Ki = ...
    0.0;
AUTOPILOT.attitude.rollPitch.Kd = ...
    0.0;
AUTOPILOT.attitude.rollPitch.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.attitude.rollPitch.integratorUpperLimit = ...
    0.2;
AUTOPILOT.attitude.rollPitch.integratorLowerLimit = ...
   -0.2;
AUTOPILOT.attitude.rollPitch.maxRate_deg_s = ...
    AUTOPILOT.attitude.maxRate_deg_s;
AUTOPILOT.attitude.rollPitch.maxRate_rad_s = ...
    AUTOPILOT.attitude.maxRate_rad_s;
AUTOPILOT.attitude.rollPitch.minRate_rad_s = ...
    AUTOPILOT.attitude.minRate_rad_s;
AUTOPILOT.attitude.rollPitch.outputUpperLimit = ...
    AUTOPILOT.attitude.outputUpperLimit;
AUTOPILOT.attitude.rollPitch.outputLowerLimit = ...
    AUTOPILOT.attitude.outputLowerLimit;
AUTOPILOT.angularRate.rollPitch.Kp = ...
    AUTOPILOT.angularRate.roll.Kp;
AUTOPILOT.angularRate.rollPitch.Ki = ...
    AUTOPILOT.angularRate.roll.Ki;
AUTOPILOT.angularRate.rollPitch.Kd = ...
    0.0;
AUTOPILOT.angularRate.rollPitch.N = ...
    AUTOPILOT.pid.derivativeFilterCoefficient;
AUTOPILOT.angularRate.rollPitch.integratorUpperLimit = ...
    AUTOPILOT.angularRate.roll.integratorUpperLimit;
AUTOPILOT.angularRate.rollPitch.integratorLowerLimit = ...
    AUTOPILOT.angularRate.roll.integratorLowerLimit;
AUTOPILOT.angularRate.rollPitch.maxAxisCommand_rad_s = ...
    AUTOPILOT.angularRate.rollPitchLimits.maxAxisCommand_rad_s;
AUTOPILOT.angularRate.rollPitch.minAxisCommand_rad_s = ...
    AUTOPILOT.angularRate.rollPitchLimits.minAxisCommand_rad_s;
AUTOPILOT.angularRate.rollPitch.outputUpperLimit = ...
    AUTOPILOT.angularRate.rollPitchLimits.outputUpperLimit;
AUTOPILOT.angularRate.rollPitch.outputLowerLimit = ...
    AUTOPILOT.angularRate.rollPitchLimits.outputLowerLimit;
AUTOPILOT.vertical.position = ...
    AUTOPILOT.vertical.altitude;
AUTOPILOT.rate.rollPitch = ...
    AUTOPILOT.angularRate.rollPitch;
AUTOPILOT.rate.yaw = ...
    AUTOPILOT.angularRate.yaw;
disp(' ');
disp( ...
    '==============================================================');
disp( ...
    ' UAV Autopilot parameters loaded.');
disp( ...
    '==============================================================');
fprintf( ...
    'Controller:                  Cascaded P / PI / PD\n');
fprintf( ...
    'Gain schema:                 %s\n', ...
    AUTOPILOT.info.controllerGainSchema);
fprintf( ...
    'Gain source:                 %s\n', ...
    AUTOPILOT.info.controllerGainSource);
fprintf( ...
    'Control rate:                %.1f Hz\n', ...
    AUTOPILOT.rate.control_Hz);
fprintf( ...
    'Control sample time:         %.6f s\n', ...
    AUTOPILOT.rate.controlSampleTime_s);
fprintf( ...
    'Active flight mode:          Trajectory [%d]\n', ...
    AUTOPILOT.mode.trajectory);
fprintf( ...
    'Maximum tilt:                %.1f deg\n', ...
    AUTOPILOT.limits.maxTilt_deg);
fprintf( ...
    'Maximum horizontal speed:    %.2f m/s\n', ...
    AUTOPILOT.limits.maxHorizontalVelocity_m_s);
fprintf( ...
    'Maximum vertical speed:      %.2f m/s\n', ...
    AUTOPILOT.limits.maxVerticalVelocity_m_s);
fprintf( ...
    'Maximum roll/pitch rate:     %.1f deg/s\n', ...
    AUTOPILOT.attitude.maxRate_deg_s);
fprintf( ...
    'Maximum yaw rate:            %.1f deg/s\n', ...
    AUTOPILOT.yaw.angle.maxYawRate_deg_s);
fprintf( ...
    'Roll/pitch axis authority:   +/-%.1f rad/s\n', ...
    AUTOPILOT.angularRate.rollPitchLimits.maxAxisCommand_rad_s);
fprintf( ...
    'Yaw axis authority:          +/-%.1f rad/s\n', ...
    AUTOPILOT.angularRate.yaw.maxAxisCommand_rad_s);
fprintf( ...
    'Vertical axis authority:     +/-%.1f rad/s\n', ...
    AUTOPILOT.vertical.velocity.maxAxisCommand_rad_s);
fprintf( ...
    'Hover omega [rad/s]:         [%.2f %.2f %.2f %.2f]\n', ...
    AUTOPILOT.hover.omegaTrim_rad_s(1), ...
    AUTOPILOT.hover.omegaTrim_rad_s(2), ...
    AUTOPILOT.hover.omegaTrim_rad_s(3), ...
    AUTOPILOT.hover.omegaTrim_rad_s(4));
disp( ...
    '--------------------------------------------------------------');
fprintf( ...
    'North position P:            Kp = %.6f\n', ...
    AUTOPILOT.horizontal.position.north.Kp);
fprintf( ...
    'East position P:             Kp = %.6f\n', ...
    AUTOPILOT.horizontal.position.east.Kp);
fprintf( ...
    'X velocity PD:               Kp = %.6f | Kd = %.6f | N = %.6f\n', ...
    AUTOPILOT.horizontal.velocity.x.Kp, ...
    AUTOPILOT.horizontal.velocity.x.Kd, ...
    AUTOPILOT.horizontal.velocity.x.N);
fprintf( ...
    'Y velocity P:                Kp = %.6f\n', ...
    AUTOPILOT.horizontal.velocity.y.Kp);
fprintf( ...
    'Vertical position P:         Kp = %.6f\n', ...
    AUTOPILOT.vertical.altitude.Kp);
fprintf( ...
    'Vertical velocity P:         Kp = %.6f\n', ...
    AUTOPILOT.vertical.velocity.Kp);
fprintf( ...
    'Yaw angle P:                 Kp = %.6f\n', ...
    AUTOPILOT.yaw.angle.Kp);
fprintf( ...
    'Roll attitude P:             Kp = %.6f\n', ...
    AUTOPILOT.attitude.roll.Kp);
fprintf( ...
    'Pitch attitude P:            Kp = %.6f\n', ...
    AUTOPILOT.attitude.pitch.Kp);
fprintf( ...
    'Roll rate PI:                Kp = %.6f | Ki = %.6f\n', ...
    AUTOPILOT.angularRate.roll.Kp, ...
    AUTOPILOT.angularRate.roll.Ki);
fprintf( ...
    'Pitch rate PI:               Kp = %.6f | Ki = %.6f\n', ...
    AUTOPILOT.angularRate.pitch.Kp, ...
    AUTOPILOT.angularRate.pitch.Ki);
fprintf( ...
    'Yaw rate PI:                 Kp = %.6f | Ki = %.6f\n', ...
    AUTOPILOT.angularRate.yaw.Kp, ...
    AUTOPILOT.angularRate.yaw.Ki);
disp( ...
    '==============================================================');
disp(' ');
