configurationAvailable = ...
    exist('AUTO_PROTOCOL','var') && ...
    exist('TRAJECTORY_ID','var') && ...
    exist('OPERATOR_MODE','var') && ...
    exist('OPERATOR_MODE_MANUAL','var') && ...
    exist('OPERATOR_MODE_AUTOMATIC','var');

if ~configurationAvailable
    this_file = ...
        mfilename('fullpath');

    if isempty(this_file)
        project_root = ...
            pwd;
    else
        project_root = ...
            fileparts(this_file);
    end

    initialize_file = ...
        fullfile( ...
            project_root, ...
            'initialize_project.m');

    if ~exist(initialize_file,'file')
        error( ...
            'QuadrotorFramework:MissingInitializationFile', ...
            ['initialize_project.m was not found.\n\n', ...
             'Expected location:\n%s'], ...
            initialize_file);
    end

    run(initialize_file);
end

if ~exist('AUTO_PROTOCOL','var') || ...
        ~isstruct(AUTO_PROTOCOL) || ...
        ~isfield(AUTO_PROTOCOL,'schedule_s') || ...
        ~isfield(AUTO_PROTOCOL,'trajectoryNames') || ...
        ~isfield(AUTO_PROTOCOL,'column')
    error( ...
        'QuadrotorFramework:InvalidOperatorProtocolConfiguration', ...
        ['Operator protocol configuration is unavailable or invalid. ', ...
         'Run initialize_project.m.']);
end
