if ~exist('REAL_IMPORT','var') || ...
        ~isstruct(REAL_IMPORT)
    error( ...
        'RealFlight:TLOGNotImported', ...
        ['REAL_IMPORT was not found.\n\n', ...
         'Run:\n\n', ...
         '    initialize_real_flight\n', ...
         '    import_tlog\n\n', ...
         'before running extract_tlog_signals.']);
end
if ~isfield(REAL_IMPORT,'Reader')
    error( ...
        'RealFlight:MissingTLOGReader', ...
        'REAL_IMPORT.Reader was not found.');
end
TLOG_READER = ...
    REAL_IMPORT.Reader;
AUTOPILOT_SYSTEM_ID = ...
    1;
AUTOPILOT_COMPONENT_ID = ...
    1;
GCS_SYSTEM_ID = ...
    255;
GCS_COMPONENT_ID = ...
    190;
REAL_RAW = ...
    struct();
REAL_RAW.Metadata = ...
    struct();
REAL_RAW.Metadata.AutopilotSystemID = ...
    AUTOPILOT_SYSTEM_ID;
REAL_RAW.Metadata.AutopilotComponentID = ...
    AUTOPILOT_COMPONENT_ID;
REAL_RAW.Metadata.GCSSystemID = ...
    GCS_SYSTEM_ID;
REAL_RAW.Metadata.GCSComponentID = ...
    GCS_COMPONENT_ID;
REAL_RAW.Autopilot = ...
    struct();
REAL_RAW.GCS = ...
    struct();
topicDefinitions = { ...
    'ATTITUDE', ...
    'Attitude', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'GLOBAL_POSITION_INT', ...
    'GlobalPositionInt', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'GPS_RAW_INT', ...
    'GPSRawInt', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'VFR_HUD', ...
    'VFRHUD', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'RAW_IMU', ...
    'RawIMU', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'SCALED_IMU2', ...
    'ScaledIMU2', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'SCALED_IMU3', ...
    'ScaledIMU3', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'SCALED_PRESSURE', ...
    'ScaledPressure', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'SERVO_OUTPUT_RAW', ...
    'ServoOutputRaw', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'RC_CHANNELS', ...
    'RCChannels', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'BATTERY_STATUS', ...
    'BatteryStatus', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'SYS_STATUS', ...
    'SystemStatus', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'POWER_STATUS', ...
    'PowerStatus', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'VIBRATION', ...
    'Vibration', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'HEARTBEAT', ...
    'Heartbeat', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'EXTENDED_SYS_STATE', ...
    'ExtendedSystemState', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'MISSION_CURRENT', ...
    'MissionCurrent', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'NAV_CONTROLLER_OUTPUT', ...
    'NavControllerOutput', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'MISSION_ITEM_INT', ...
    'MissionItemInt', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'TERRAIN_REPORT', ...
    'TerrainReport', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'SYSTEM_TIME', ...
    'SystemTime', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID;
    'MANUAL_CONTROL', ...
    'ManualControl', ...
    'GCS', ...
    GCS_SYSTEM_ID, ...
    GCS_COMPONENT_ID;
    'STATUSTEXT', ...
    'StatusText', ...
    'AUTOPILOT', ...
    AUTOPILOT_SYSTEM_ID, ...
    AUTOPILOT_COMPONENT_ID ...
    };
numberOfTopics = ...
    size(topicDefinitions,1);
MessageName = ...
    strings(numberOfTopics,1);
OutputField = ...
    strings(numberOfTopics,1);
Source = ...
    strings(numberOfTopics,1);
SystemID = ...
    zeros(numberOfTopics,1);
ComponentID = ...
    zeros(numberOfTopics,1);
Available = ...
    false(numberOfTopics,1);
NumMessagesReported = ...
    zeros(numberOfTopics,1);
NumSamplesRead = ...
    zeros(numberOfTopics,1);
MAVLinkFields = ...
    strings(numberOfTopics,1);
availableTopics = ...
    REAL_IMPORT.AvailableTopics;
availableMessageNames = ...
    string( ...
        availableTopics.MessageName);
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' EXTRACTING RAW MAVLINK SIGNALS\n');
fprintf('==============================================================\n\n');
for k = 1:numberOfTopics
    messageName = ...
        string(topicDefinitions{k,1});
    outputField = ...
        string(topicDefinitions{k,2});
    sourceName = ...
        string(topicDefinitions{k,3});
    systemID = ...
        double(topicDefinitions{k,4});
    componentID = ...
        double(topicDefinitions{k,5});
    MessageName(k) = ...
        messageName;
    OutputField(k) = ...
        outputField;
    Source(k) = ...
        sourceName;
    SystemID(k) = ...
        systemID;
    ComponentID(k) = ...
        componentID;
    topicMask = ...
        availableMessageNames == messageName & ...
        double(availableTopics.SystemID) == systemID & ...
        double(availableTopics.ComponentID) == componentID;
    if ~any(topicMask)
        fprintf( ...
            '[NOT AVAILABLE] %-24s  source=%s\n', ...
            messageName, ...
            sourceName);
        continue;
    end
    Available(k) = ...
        true;
    NumMessagesReported(k) = ...
        sum( ...
            double( ...
                availableTopics.NumMessages(topicMask)));
    try
        messageTable = ...
            readmsg( ...
                TLOG_READER, ...
                'MessageName', ...
                char(messageName), ...
                'SystemID', ...
                systemID, ...
                'ComponentID', ...
                componentID);
    catch ME
        warning( ...
            'RealFlight:TopicReadFailed', ...
            ['Unable to read message %s from SystemID=%d, ', ...
             'ComponentID=%d.\n%s'], ...
            messageName, ...
            systemID, ...
            componentID, ...
            ME.message);
        Available(k) = ...
            false;
        continue;
    end
    if isempty(messageTable) || ...
            height(messageTable) == 0
        warning( ...
            'RealFlight:EmptyTopic', ...
            'Topic %s exists but readmsg returned no rows.', ...
            messageName);
        Available(k) = ...
            false;
        continue;
    end
    timetableList = ...
        messageTable.Messages;
    messageTimetable = ...
        timetable();
    for j = 1:numel(timetableList)
        currentTimetable = ...
            timetableList{j};
        if isempty(currentTimetable)
            continue;
        end
        if isempty(messageTimetable)
            messageTimetable = ...
                currentTimetable;
        else
            messageTimetable = ...
                [ ...
                    messageTimetable; ...
                    currentTimetable ...
                ]; %#ok<AGROW>
        end
    end
    if isempty(messageTimetable)
        Available(k) = ...
            false;
        continue;
    end
    messageTimetable = ...
        sortrows(messageTimetable);
    NumSamplesRead(k) = ...
        height(messageTimetable);
    variableNames = ...
        string( ...
            messageTimetable.Properties.VariableNames);
    MAVLinkFields(k) = ...
        strjoin( ...
            variableNames, ...
            ", ");
    if sourceName == "AUTOPILOT"
        REAL_RAW.Autopilot.(outputField) = ...
            messageTimetable;
    elseif sourceName == "GCS"
        REAL_RAW.GCS.(outputField) = ...
            messageTimetable;
    else
        error( ...
            'RealFlight:UnknownSignalSource', ...
            'Unknown signal source "%s".', ...
            sourceName);
    end
    fprintf( ...
        '[OK] %-24s  %8d samples\n', ...
        messageName, ...
        NumSamplesRead(k));
end
REAL_SIGNAL_INVENTORY = ...
    table( ...
        MessageName, ...
        OutputField, ...
        Source, ...
        SystemID, ...
        ComponentID, ...
        Available, ...
        NumMessagesReported, ...
        NumSamplesRead, ...
        MAVLinkFields);
numberAvailable = ...
    nnz(Available);
numberUnavailable = ...
    numberOfTopics - ...
    numberAvailable;
fprintf('\n');
fprintf('--------------------------------------------------------------\n');
fprintf(' SIGNAL INVENTORY\n');
fprintf('--------------------------------------------------------------\n\n');
disp( ...
    REAL_SIGNAL_INVENTORY(:, { ...
        'MessageName', ...
        'Source', ...
        'Available', ...
        'NumSamplesRead'}));
fprintf('\n');
fprintf('--------------------------------------------------------------\n');
fprintf(' EXACT MAVLINK FIELDS FOUND\n');
fprintf('--------------------------------------------------------------\n');
for k = 1:height(REAL_SIGNAL_INVENTORY)
    if ~REAL_SIGNAL_INVENTORY.Available(k)
        continue;
    end
    fprintf('\n%s\n', ...
        REAL_SIGNAL_INVENTORY.MessageName(k));
    fprintf('  Source: %s\n', ...
        REAL_SIGNAL_INVENTORY.Source(k));
    fprintf('  Samples: %d\n', ...
        REAL_SIGNAL_INVENTORY.NumSamplesRead(k));
    fprintf('  Fields:\n');
    fieldList = ...
        split( ...
            REAL_SIGNAL_INVENTORY.MAVLinkFields(k), ...
            ", ");
    for j = 1:numel(fieldList)
        fprintf( ...
            '    - %s\n', ...
            fieldList(j));
    end
end
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' RAW SIGNAL EXTRACTION COMPLETE\n');
fprintf('==============================================================\n');
fprintf( ...
    'Requested topics:         %d\n', ...
    numberOfTopics);
fprintf( ...
    'Available topics:         %d\n', ...
    numberAvailable);
fprintf( ...
    'Unavailable topics:       %d\n', ...
    numberUnavailable);
fprintf('\n');
fprintf( ...
    ['REAL_RAW contains the original MAVLink timetables.\n', ...
     'Values are still in native MAVLink units.\n']);
fprintf('\n');
fprintf( ...
    ['REAL_SIGNAL_INVENTORY documents exactly which signals and\n', ...
     'fields are available for the next processing stage.\n']);
fprintf('==============================================================\n');
fprintf('\n');
clear TLOG_READER ...
      AUTOPILOT_SYSTEM_ID ...
      AUTOPILOT_COMPONENT_ID ...
      GCS_SYSTEM_ID ...
      GCS_COMPONENT_ID ...
      topicDefinitions ...
      numberOfTopics ...
      availableTopics ...
      availableMessageNames ...
      messageName ...
      outputField ...
      sourceName ...
      systemID ...
      componentID ...
      topicMask ...
      messageTable ...
      timetableList ...
      messageTimetable ...
      currentTimetable ...
      variableNames ...
      fieldList ...
      numberAvailable ...
      numberUnavailable ...
      MessageName ...
      OutputField ...
      Source ...
      SystemID ...
      ComponentID ...
      Available ...
      NumMessagesReported ...
      NumSamplesRead ...
      MAVLinkFields ...
      k j ME;
