requiredVariables = { ...
    'REAL_IMPORT', ...
    'REAL_TABLES_FOLDER', ...
    'REAL_EXPERIMENT_DATA_FILE'};
for k = 1:numel(requiredVariables)
    if ~exist(requiredVariables{k},'var')
        error( ...
            'RealFlight:MissingRequiredVariable', ...
            ['Required variable "%s" was not found.\n\n', ...
             'Run the previous real-flight processing scripts first.'], ...
            requiredVariables{k});
    end
end
if ~isfield(REAL_IMPORT,'Reader')
    error( ...
        'RealFlight:MissingTLOGReader', ...
        'REAL_IMPORT.Reader is not available.');
end
TLOG_READER = ...
    REAL_IMPORT.Reader;
REAL_AUTOPILOT_PARAMETER_STATUS = ...
    struct();
REAL_AUTOPILOT_PARAMETER_STATUS.Available = ...
    false;
REAL_AUTOPILOT_PARAMETER_STATUS.Source = ...
    "PARAM_VALUE";
REAL_AUTOPILOT_PARAMETER_STATUS.MessageCount = ...
    0;
REAL_AUTOPILOT_PARAMETER_STATUS.UniqueParameterCount = ...
    0;
REAL_AUTOPILOT_PARAMETER_STATUS.ReadSucceeded = ...
    false;
REAL_AUTOPILOT_PARAMETER_STATUS.ReadErrorIdentifier = ...
    "";
REAL_AUTOPILOT_PARAMETER_STATUS.ReadErrorMessage = ...
    "";
REAL_AUTOPILOT_PARAMETER_STATUS.Reason = ...
    "NOT_PROCESSED";
REAL_AUTOPILOT_PARAMETERS = ...
    table( ...
        strings(0,1), ...
        NaN(0,1), ...
        NaN(0,1), ...
        NaN(0,1), ...
        'VariableNames', { ...
            'Parameter', ...
            'Value', ...
            'MAVLinkType', ...
            'LastReceivedTime_s'});
REAL_ACTUATOR_PARAMETERS = ...
    REAL_AUTOPILOT_PARAMETERS;
Channel = ...
    (1:16).';
Function = ...
    NaN(16,1);
MinimumPWM_us = ...
    NaN(16,1);
MaximumPWM_us = ...
    NaN(16,1);
TrimPWM_us = ...
    NaN(16,1);
Reversed = ...
    NaN(16,1);
REAL_SERVO_CONFIGURATION = ...
    table( ...
        Channel, ...
        Function, ...
        MinimumPWM_us, ...
        MaximumPWM_us, ...
        TrimPWM_us, ...
        Reversed);
REAL_CONFIGURED_OUTPUTS = ...
    REAL_SERVO_CONFIGURATION( ...
        false(height(REAL_SERVO_CONFIGURATION),1), ...
        :);
REAL_ACTUATOR_CONFIG = ...
    struct();
REAL_ACTUATOR_CONFIG.Available = ...
    false;
REAL_ACTUATOR_CONFIG.Source = ...
    "PARAM_VALUE_NOT_AVAILABLE";
REAL_ACTUATOR_CONFIG.FrameClass = ...
    NaN;
REAL_ACTUATOR_CONFIG.FrameType = ...
    NaN;
REAL_ACTUATOR_CONFIG.MotorPWMMin_us = ...
    NaN;
REAL_ACTUATOR_CONFIG.MotorPWMMax_us = ...
    NaN;
REAL_ACTUATOR_CONFIG.MotorSpinArm = ...
    NaN;
REAL_ACTUATOR_CONFIG.MotorSpinMin = ...
    NaN;
REAL_ACTUATOR_CONFIG.MotorThrustExpo = ...
    NaN;
REAL_ACTUATOR_CONFIG.ServoConfiguration = ...
    REAL_SERVO_CONFIGURATION;
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' EXTRACTING AUTOPILOT PARAMETERS\n');
fprintf('==============================================================\n\n');
parameterMessages = ...
    [];
parameterReadSucceeded = ...
    false;
try
    parameterMessages = ...
        readmsg( ...
            TLOG_READER, ...
            'MessageName','PARAM_VALUE', ...
            'SystemID',1, ...
            'ComponentID',1);
    parameterReadSucceeded = ...
        true;
    REAL_AUTOPILOT_PARAMETER_STATUS.ReadSucceeded = ...
        true;
catch ME
    REAL_AUTOPILOT_PARAMETER_STATUS.ReadSucceeded = ...
        false;
    REAL_AUTOPILOT_PARAMETER_STATUS.ReadErrorIdentifier = ...
        string(ME.identifier);
    REAL_AUTOPILOT_PARAMETER_STATUS.ReadErrorMessage = ...
        string(ME.message);
    REAL_AUTOPILOT_PARAMETER_STATUS.Reason = ...
        "PARAM_VALUE_READ_FAILED";
    warning( ...
        'RealFlight:ParameterReadUnavailable', ...
        ['Unable to recover PARAM_VALUE messages from this TLOG.\n', ...
         'Autopilot parameter reconstruction will be marked unavailable.\n', ...
         'The real-flight analysis will continue.\n\n', ...
         'MATLAB message:\n%s'], ...
        ME.message);
end
parameterMessagesAvailable = ...
    false;
if parameterReadSucceeded && ...
        ~isempty(parameterMessages)
    try
        parameterMessagesAvailable = ...
            height(parameterMessages) > 0;
    catch
        parameterMessagesAvailable = ...
            false;
    end
end
if ~parameterMessagesAvailable && ...
        REAL_AUTOPILOT_PARAMETER_STATUS.Reason == "NOT_PROCESSED"
    REAL_AUTOPILOT_PARAMETER_STATUS.Reason = ...
        "NO_PARAM_VALUE_MESSAGES";
end
if parameterMessagesAvailable
    timetableList = ...
        parameterMessages.Messages;
    PARAM_TT = ...
        timetable();
    for k = 1:numel(timetableList)
        currentTT = ...
            timetableList{k};
        if isempty(currentTT)
            continue;
        end
        if isempty(PARAM_TT)
            PARAM_TT = ...
                currentTT;
        else
            PARAM_TT = ...
                [ ...
                    PARAM_TT; ...
                    currentTT ...
                ]; %#ok<AGROW>
        end
    end
    if isempty(PARAM_TT)
        parameterMessagesAvailable = ...
            false;
        REAL_AUTOPILOT_PARAMETER_STATUS.Reason = ...
            "PARAM_VALUE_TIMETABLE_EMPTY";
    end
end
if parameterMessagesAvailable
    PARAM_TT = ...
        sortrows(PARAM_TT);
    requiredFields = { ...
        'param_id', ...
        'param_value', ...
        'param_type'};
    missingRequiredField = ...
        false;
    missingFieldName = ...
        "";
    for k = 1:numel(requiredFields)
        if ~ismember( ...
                requiredFields{k}, ...
                PARAM_TT.Properties.VariableNames)
            missingRequiredField = ...
                true;
            missingFieldName = ...
                string(requiredFields{k});
            break;
        end
    end
    if missingRequiredField
        parameterMessagesAvailable = ...
            false;
        REAL_AUTOPILOT_PARAMETER_STATUS.Reason = ...
            "PARAM_VALUE_REQUIRED_FIELD_MISSING";
        REAL_AUTOPILOT_PARAMETER_STATUS.ReadErrorMessage = ...
            "Missing PARAM_VALUE field: " + ...
            missingFieldName;
        warning( ...
            'RealFlight:MissingParameterField', ...
            ['PARAM_VALUE data were present but field "%s" was missing.\n', ...
             'Autopilot parameter reconstruction will be marked unavailable.\n', ...
             'The real-flight analysis will continue.'], ...
            missingFieldName);
    end
end
if parameterMessagesAvailable
    numberOfMessages = ...
        height(PARAM_TT);
    ParamID = ...
        strings(numberOfMessages,1);
    rawParamID = ...
        PARAM_TT.param_id;
    for k = 1:numberOfMessages
        ParamID(k) = ...
            cleanMAVLinkParameterID( ...
                rawParamID, ...
                k);
    end
    ParamValue = ...
        double( ...
            PARAM_TT.param_value);
    ParamType = ...
        double( ...
            PARAM_TT.param_type);
    parameterTime_s = ...
        NaN(numberOfMessages,1);
    rowTimes = ...
        PARAM_TT.Properties.RowTimes;
    if isduration(rowTimes)
        parameterTime_s = ...
            seconds(rowTimes);
    elseif isdatetime(rowTimes)
        parameterTime_s = ...
            seconds( ...
                rowTimes - ...
                REAL_IMPORT.Time.Start);
    elseif isnumeric(rowTimes)
        parameterTime_s = ...
            double(rowTimes);
    end
    parameterTime_s = ...
        double(parameterTime_s(:));
    validParameter = ...
        strlength(ParamID) > 0 & ...
        isfinite(ParamValue);
    ParamID = ...
        ParamID(validParameter);
    ParamValue = ...
        ParamValue(validParameter);
    ParamType = ...
        ParamType(validParameter);
    parameterTime_s = ...
        parameterTime_s(validParameter);
    uniqueIDs = ...
        unique( ...
            ParamID, ...
            'stable');
    numberUniqueParameters = ...
        numel(uniqueIDs);
    FinalParamID = ...
        strings(numberUniqueParameters,1);
    FinalParamValue = ...
        NaN(numberUniqueParameters,1);
    FinalParamType = ...
        NaN(numberUniqueParameters,1);
    FinalTime_s = ...
        NaN(numberUniqueParameters,1);
    for k = 1:numberUniqueParameters
        indices = ...
            find( ...
                ParamID == uniqueIDs(k));
        lastIndex = ...
            indices(end);
        FinalParamID(k) = ...
            ParamID(lastIndex);
        FinalParamValue(k) = ...
            ParamValue(lastIndex);
        FinalParamType(k) = ...
            ParamType(lastIndex);
        FinalTime_s(k) = ...
            parameterTime_s(lastIndex);
    end
    REAL_AUTOPILOT_PARAMETERS = ...
        table( ...
            FinalParamID, ...
            FinalParamValue, ...
            FinalParamType, ...
            FinalTime_s, ...
            'VariableNames', { ...
                'Parameter', ...
                'Value', ...
                'MAVLinkType', ...
                'LastReceivedTime_s'});
    REAL_AUTOPILOT_PARAMETERS = ...
        sortrows( ...
            REAL_AUTOPILOT_PARAMETERS, ...
            'Parameter');
    parameterNames = ...
        REAL_AUTOPILOT_PARAMETERS.Parameter;
    actuatorMask = ...
        startsWith(parameterNames,"SERVO") | ...
        startsWith(parameterNames,"MOT_") | ...
        parameterNames == "FRAME_CLASS" | ...
        parameterNames == "FRAME_TYPE";
    REAL_ACTUATOR_PARAMETERS = ...
        REAL_AUTOPILOT_PARAMETERS( ...
            actuatorMask, ...
            :);
    for channel = 1:16
        functionName = ...
            sprintf( ...
                'SERVO%d_FUNCTION', ...
                channel);
        minName = ...
            sprintf( ...
                'SERVO%d_MIN', ...
                channel);
        maxName = ...
            sprintf( ...
                'SERVO%d_MAX', ...
                channel);
        trimName = ...
            sprintf( ...
                'SERVO%d_TRIM', ...
                channel);
        reverseName = ...
            sprintf( ...
                'SERVO%d_REVERSED', ...
                channel);
        Function(channel) = ...
            parameterValueOrNaN( ...
                REAL_AUTOPILOT_PARAMETERS, ...
                functionName);
        MinimumPWM_us(channel) = ...
            parameterValueOrNaN( ...
                REAL_AUTOPILOT_PARAMETERS, ...
                minName);
        MaximumPWM_us(channel) = ...
            parameterValueOrNaN( ...
                REAL_AUTOPILOT_PARAMETERS, ...
                maxName);
        TrimPWM_us(channel) = ...
            parameterValueOrNaN( ...
                REAL_AUTOPILOT_PARAMETERS, ...
                trimName);
        Reversed(channel) = ...
            parameterValueOrNaN( ...
                REAL_AUTOPILOT_PARAMETERS, ...
                reverseName);
    end
    REAL_SERVO_CONFIGURATION = ...
        table( ...
            Channel, ...
            Function, ...
            MinimumPWM_us, ...
            MaximumPWM_us, ...
            TrimPWM_us, ...
            Reversed);
    REAL_ACTUATOR_CONFIG.Available = ...
        true;
    REAL_ACTUATOR_CONFIG.Source = ...
        "PARAM_VALUE";
    REAL_ACTUATOR_CONFIG.FrameClass = ...
        parameterValueOrNaN( ...
            REAL_AUTOPILOT_PARAMETERS, ...
            'FRAME_CLASS');
    REAL_ACTUATOR_CONFIG.FrameType = ...
        parameterValueOrNaN( ...
            REAL_AUTOPILOT_PARAMETERS, ...
            'FRAME_TYPE');
    REAL_ACTUATOR_CONFIG.MotorPWMMin_us = ...
        parameterValueOrNaN( ...
            REAL_AUTOPILOT_PARAMETERS, ...
            'MOT_PWM_MIN');
    REAL_ACTUATOR_CONFIG.MotorPWMMax_us = ...
        parameterValueOrNaN( ...
            REAL_AUTOPILOT_PARAMETERS, ...
            'MOT_PWM_MAX');
    REAL_ACTUATOR_CONFIG.MotorSpinArm = ...
        parameterValueOrNaN( ...
            REAL_AUTOPILOT_PARAMETERS, ...
            'MOT_SPIN_ARM');
    REAL_ACTUATOR_CONFIG.MotorSpinMin = ...
        parameterValueOrNaN( ...
            REAL_AUTOPILOT_PARAMETERS, ...
            'MOT_SPIN_MIN');
    REAL_ACTUATOR_CONFIG.MotorThrustExpo = ...
        parameterValueOrNaN( ...
            REAL_AUTOPILOT_PARAMETERS, ...
            'MOT_THST_EXPO');
    REAL_ACTUATOR_CONFIG.ServoConfiguration = ...
        REAL_SERVO_CONFIGURATION;
    configuredMask = ...
        isfinite(REAL_SERVO_CONFIGURATION.Function) & ...
        REAL_SERVO_CONFIGURATION.Function ~= 0;
    REAL_CONFIGURED_OUTPUTS = ...
        REAL_SERVO_CONFIGURATION( ...
            configuredMask, ...
            :);
    REAL_AUTOPILOT_PARAMETER_STATUS.Available = ...
        true;
    REAL_AUTOPILOT_PARAMETER_STATUS.MessageCount = ...
        numberOfMessages;
    REAL_AUTOPILOT_PARAMETER_STATUS.UniqueParameterCount = ...
        numberUniqueParameters;
    REAL_AUTOPILOT_PARAMETER_STATUS.Reason = ...
        "AVAILABLE";
else
    numberOfMessages = ...
        0;
    numberUniqueParameters = ...
        0;
    REAL_AUTOPILOT_PARAMETER_STATUS.Available = ...
        false;
    REAL_AUTOPILOT_PARAMETER_STATUS.MessageCount = ...
        0;
    REAL_AUTOPILOT_PARAMETER_STATUS.UniqueParameterCount = ...
        0;
    REAL_ACTUATOR_CONFIG.Available = ...
        false;
    REAL_ACTUATOR_CONFIG.Source = ...
        "PARAM_VALUE_NOT_AVAILABLE";
    REAL_ACTUATOR_CONFIG.ServoConfiguration = ...
        REAL_SERVO_CONFIGURATION;
end
writetable( ...
    REAL_AUTOPILOT_PARAMETERS, ...
    fullfile( ...
        REAL_TABLES_FOLDER, ...
        'Autopilot_Parameters.csv'));
writetable( ...
    REAL_ACTUATOR_PARAMETERS, ...
    fullfile( ...
        REAL_TABLES_FOLDER, ...
        'Actuator_Parameters.csv'));
writetable( ...
    REAL_SERVO_CONFIGURATION, ...
    fullfile( ...
        REAL_TABLES_FOLDER, ...
        'Servo_Configuration.csv'));
save( ...
    REAL_EXPERIMENT_DATA_FILE, ...
    'REAL_AUTOPILOT_PARAMETERS', ...
    'REAL_ACTUATOR_PARAMETERS', ...
    'REAL_SERVO_CONFIGURATION', ...
    'REAL_CONFIGURED_OUTPUTS', ...
    'REAL_ACTUATOR_CONFIG', ...
    'REAL_AUTOPILOT_PARAMETER_STATUS', ...
    '-append');
fprintf( ...
    'PARAM_VALUE available:      %s\n', ...
    localYesNo( ...
        REAL_AUTOPILOT_PARAMETER_STATUS.Available));
fprintf( ...
    'PARAM_VALUE messages:       %d\n', ...
    numberOfMessages);
fprintf( ...
    'Unique parameters:          %d\n', ...
    numberUniqueParameters);
if REAL_AUTOPILOT_PARAMETER_STATUS.Available
    fprintf('\n');
    fprintf( ...
        'FRAME_CLASS:                %.0f\n', ...
        REAL_ACTUATOR_CONFIG.FrameClass);
    fprintf( ...
        'FRAME_TYPE:                 %.0f\n', ...
        REAL_ACTUATOR_CONFIG.FrameType);
    fprintf( ...
        'MOT_PWM_MIN:                %.3f\n', ...
        REAL_ACTUATOR_CONFIG.MotorPWMMin_us);
    fprintf( ...
        'MOT_PWM_MAX:                %.3f\n', ...
        REAL_ACTUATOR_CONFIG.MotorPWMMax_us);
    fprintf( ...
        'MOT_SPIN_ARM:               %.5f\n', ...
        REAL_ACTUATOR_CONFIG.MotorSpinArm);
    fprintf( ...
        'MOT_SPIN_MIN:               %.5f\n', ...
        REAL_ACTUATOR_CONFIG.MotorSpinMin);
    fprintf( ...
        'MOT_THST_EXPO:              %.5f\n', ...
        REAL_ACTUATOR_CONFIG.MotorThrustExpo);
    fprintf('\n');
    fprintf('--------------------------------------------------------------\n');
    fprintf(' CONFIGURED SERVO OUTPUTS\n');
    fprintf('--------------------------------------------------------------\n\n');
    if isempty(REAL_CONFIGURED_OUTPUTS)
        fprintf('No configured SERVOx_FUNCTION values were recovered.\n');
    else
        disp(REAL_CONFIGURED_OUTPUTS);
    end
else
    fprintf('\n');
    fprintf('Autopilot parameter reconstruction: NOT AVAILABLE\n');
    fprintf( ...
        'Reason: %s\n', ...
        REAL_AUTOPILOT_PARAMETER_STATUS.Reason);
    fprintf('\n');
    fprintf( ...
        ['The TLOG does not contain usable PARAM_VALUE telemetry.\n', ...
         'This does NOT invalidate the measured flight-state, IMU,\n', ...
         'position, attitude, PWM, battery, or vibration telemetry.\n']);
    fprintf('\n');
    fprintf( ...
        ['SERVO_OUTPUT_RAW remains available as raw PWM only.\n', ...
         'Motor-channel semantics and PWM normalization parameters\n', ...
         'cannot be reconstructed from this TLOG alone.\n']);
end
fprintf('\n');
fprintf('Files saved:\n');
fprintf('  - Autopilot_Parameters.csv\n');
fprintf('  - Actuator_Parameters.csv\n');
fprintf('  - Servo_Configuration.csv\n');
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' AUTOPILOT PARAMETER EXTRACTION COMPLETE\n');
fprintf('==============================================================\n');
clear requiredVariables ...
      TLOG_READER ...
      parameterMessages ...
      parameterReadSucceeded ...
      parameterMessagesAvailable ...
      timetableList ...
      currentTT ...
      PARAM_TT ...
      requiredFields ...
      missingRequiredField ...
      missingFieldName ...
      numberOfMessages ...
      rawParamID ...
      ParamID ...
      ParamValue ...
      ParamType ...
      parameterTime_s ...
      rowTimes ...
      validParameter ...
      uniqueIDs ...
      numberUniqueParameters ...
      FinalParamID ...
      FinalParamValue ...
      FinalParamType ...
      FinalTime_s ...
      parameterNames ...
      actuatorMask ...
      Channel ...
      Function ...
      MinimumPWM_us ...
      MaximumPWM_us ...
      TrimPWM_us ...
      Reversed ...
      functionName ...
      minName ...
      maxName ...
      trimName ...
      reverseName ...
      configuredMask ...
      indices ...
      lastIndex ...
      channel ...
      k ...
      ME;
function parameterID = cleanMAVLinkParameterID(rawParamID,index)
    parameterID = ...
        "";
    try
        if isstring(rawParamID)
            parameterID = ...
                string(rawParamID(index));
        elseif iscell(rawParamID)
            parameterID = ...
                string(rawParamID{index});
        elseif ischar(rawParamID)
            if size(rawParamID,1) >= index
                parameterID = ...
                    string(rawParamID(index,:));
            end
        elseif isnumeric(rawParamID)
            if ismatrix(rawParamID)
                row = ...
                    rawParamID(index,:);
                row = ...
                    row(row ~= 0);
                parameterID = ...
                    string( ...
                        char(row));
            end
        else
            try
                parameterID = ...
                    string(rawParamID(index));
            catch
                parameterID = ...
                    "";
            end
        end
    catch
        parameterID = ...
            "";
    end
    parameterID = ...
        erase( ...
            parameterID, ...
            char(0));
    parameterID = ...
        strip(parameterID);
    parameterID = ...
        upper(parameterID);
end
function value = parameterValueOrNaN(parameterTable,parameterName)
    value = ...
        NaN;
    if isempty(parameterTable)
        return;
    end
    parameterName = ...
        upper( ...
            string(parameterName));
    index = ...
        find( ...
            upper(parameterTable.Parameter) == parameterName, ...
            1, ...
            'last');
    if isempty(index)
        return;
    end
    candidate = ...
        double( ...
            parameterTable.Value(index));
    if isfinite(candidate)
        value = ...
            candidate;
    end
end
function textValue = localYesNo(value)
    if logical(value)
        textValue = ...
            'YES';
    else
        textValue = ...
            'NO';
    end
end
