if ~exist('REAL_PROJECT_ROOT','var') || ...
        ~exist('REAL_TLOG_PATH','var') || ...
        ~exist('REAL_CONFIG','var')
    error( ...
        'RealFlight:NotInitialized', ...
        ['Real-flight environment has not been initialized.\n\n', ...
         'Run:\n\n', ...
         '    initialize_real_flight\n\n', ...
         'before running import_tlog.']);
end
if exist('mavlinktlog','file') ~= 2
    error( ...
        'RealFlight:MAVLinkTLOGUnavailable', ...
        ['MATLAB function mavlinktlog was not found.\n\n', ...
         'UAV Toolbox with MAVLink TLOG support is required.']);
end
if strlength(REAL_TLOG_PATH) == 0
    error( ...
        'RealFlight:NoTLOGSelected', ...
        ['No TLOG file is currently selected.\n', ...
         'Run initialize_real_flight and select one file.']);
end
if ~isfile(REAL_TLOG_PATH)
    error( ...
        'RealFlight:TLOGFileNotFound', ...
        'Selected TLOG file does not exist:\n%s', ...
        REAL_TLOG_PATH);
end
fileInfo = ...
    dir(REAL_TLOG_PATH);
if isempty(fileInfo)
    error( ...
        'RealFlight:TLOGFileInfoUnavailable', ...
        'Unable to read file information for:\n%s', ...
        REAL_TLOG_PATH);
end
fileSizeBytes = ...
    double(fileInfo.bytes);
fileSizeMB = ...
    fileSizeBytes / ...
    (1024^2);
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' IMPORTING MAVLINK TLOG\n');
fprintf('==============================================================\n');
fprintf('File:\n%s\n\n', REAL_TLOG_PATH);
fprintf('Loading TLOG. Please wait...\n');
try
    TLOG_READER = ...
        mavlinktlog(REAL_TLOG_PATH);
catch ME
    fprintf('\n');
    error( ...
        'RealFlight:TLOGImportFailed', ...
        ['Unable to import the selected TLOG.\n\n', ...
         'Original MATLAB error:\n%s'], ...
        ME.message);
end
fprintf('TLOG loaded successfully.\n');
startTime = ...
    TLOG_READER.StartTime;
endTime = ...
    TLOG_READER.EndTime;
duration_s = ...
    seconds( ...
        endTime - startTime);
numMessages = ...
    double( ...
        TLOG_READER.NumMessages);
numPacketsLost = ...
    double( ...
        TLOG_READER.NumPacketsLost);
availableTopics = ...
    TLOG_READER.AvailableTopics;
if ~istable(availableTopics)
    error( ...
        'RealFlight:InvalidAvailableTopics', ...
        'TLOG_READER.AvailableTopics must be a MATLAB table.');
end
requiredTopicColumns = { ...
    'MessageID', ...
    'MessageName', ...
    'SystemID', ...
    'ComponentID', ...
    'NumMessages'};
for k = 1:numel(requiredTopicColumns)
    if ~ismember( ...
            requiredTopicColumns{k}, ...
            availableTopics.Properties.VariableNames)
        error( ...
            'RealFlight:InvalidTopicTable', ...
            ['AvailableTopics does not contain expected column "%s".'], ...
            requiredTopicColumns{k});
    end
end
totalObservedPackets = ...
    numMessages + ...
    numPacketsLost;
if totalObservedPackets > 0
    packetLoss_percent = ...
        100 * ...
        numPacketsLost / ...
        totalObservedPackets;
else
    packetLoss_percent = ...
        NaN;
end
numberOfTopicRows = ...
    height(availableTopics);
uniqueMessageNames = ...
    unique( ...
        string( ...
            availableTopics.MessageName), ...
        'stable');
numberOfUniqueMessageTypes = ...
    numel(uniqueMessageNames);
uniqueSystemIDs = ...
    unique( ...
        double( ...
            availableTopics.SystemID));
uniqueComponentIDs = ...
    unique( ...
        double( ...
            availableTopics.ComponentID));
availableTopicsSorted = ...
    sortrows( ...
        availableTopics, ...
        'NumMessages', ...
        'descend');
REAL_IMPORT = ...
    struct();
REAL_IMPORT.Source = ...
    struct();
REAL_IMPORT.Source.FileName = ...
    string(fileInfo.name);
REAL_IMPORT.Source.FilePath = ...
    string(REAL_TLOG_PATH);
REAL_IMPORT.Source.FileSizeBytes = ...
    fileSizeBytes;
REAL_IMPORT.Source.FileSizeMB = ...
    fileSizeMB;
REAL_IMPORT.Reader = ...
    TLOG_READER;
REAL_IMPORT.Time = ...
    struct();
REAL_IMPORT.Time.Start = ...
    startTime;
REAL_IMPORT.Time.End = ...
    endTime;
REAL_IMPORT.Time.Duration_s = ...
    duration_s;
REAL_IMPORT.Messages = ...
    struct();
REAL_IMPORT.Messages.NumMessages = ...
    numMessages;
REAL_IMPORT.Messages.NumPacketsLost = ...
    numPacketsLost;
REAL_IMPORT.Messages.PacketLoss_percent = ...
    packetLoss_percent;
REAL_IMPORT.Messages.NumberOfTopicRows = ...
    numberOfTopicRows;
REAL_IMPORT.Messages.NumberOfUniqueMessageTypes = ...
    numberOfUniqueMessageTypes;
REAL_IMPORT.Messages.UniqueMessageNames = ...
    uniqueMessageNames;
REAL_IMPORT.Messages.SystemIDs = ...
    uniqueSystemIDs;
REAL_IMPORT.Messages.ComponentIDs = ...
    uniqueComponentIDs;
REAL_IMPORT.AvailableTopics = ...
    availableTopics;
REAL_IMPORT.AvailableTopicsSorted = ...
    availableTopicsSorted;
fprintf('\n');
fprintf('--------------------------------------------------------------\n');
fprintf(' TLOG SUMMARY\n');
fprintf('--------------------------------------------------------------\n');
fprintf( ...
    'File size:                %.2f MB\n', ...
    fileSizeMB);
fprintf( ...
    'Start time:               %s\n', ...
    string(startTime));
fprintf( ...
    'End time:                 %s\n', ...
    string(endTime));
fprintf( ...
    'Log duration:             %.3f s (%.2f min)\n', ...
    duration_s, ...
    duration_s/60);
fprintf( ...
    'Decoded messages:         %.0f\n', ...
    numMessages);
fprintf( ...
    'Packets lost:             %.0f\n', ...
    numPacketsLost);
fprintf( ...
    'Estimated packet loss:    %.4f %%\n', ...
    packetLoss_percent);
fprintf( ...
    'Unique message types:     %d\n', ...
    numberOfUniqueMessageTypes);
fprintf( ...
    'System IDs:               %s\n', ...
    mat2str(uniqueSystemIDs.'));
fprintf( ...
    'Component IDs:            %s\n', ...
    mat2str(uniqueComponentIDs.'));
fprintf('\n');
fprintf('--------------------------------------------------------------\n');
fprintf(' AVAILABLE MAVLINK TOPICS\n');
fprintf(' Sorted by number of messages\n');
fprintf('--------------------------------------------------------------\n\n');
disp(availableTopicsSorted);
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' TLOG IMPORT COMPLETE\n');
fprintf('==============================================================\n');
fprintf('\n');
fprintf( ...
    ['REAL_IMPORT now contains the raw MAVLink reader, metadata,\n', ...
     'and the complete decoded topic inventory.\n']);
fprintf('\n');
fprintf( ...
    ['No signals, metrics, figures, or result folders have been\n', ...
     'generated yet.\n']);
fprintf('==============================================================\n');
fprintf('\n');
clear fileInfo ...
      fileSizeBytes ...
      fileSizeMB ...
      startTime ...
      endTime ...
      duration_s ...
      numMessages ...
      numPacketsLost ...
      availableTopics ...
      availableTopicsSorted ...
      totalObservedPackets ...
      packetLoss_percent ...
      numberOfTopicRows ...
      uniqueMessageNames ...
      numberOfUniqueMessageTypes ...
      uniqueSystemIDs ...
      uniqueComponentIDs ...
      requiredTopicColumns ...
      k ...
      ME;
