this_file = ...
    mfilename('fullpath');
if isempty(this_file)
    REAL_PROJECT_ROOT = ...
        pwd;
else
    REAL_PROJECT_ROOT = ...
        fileparts(this_file);
end
REAL_RESULTS_ROOT = ...
    fullfile( ...
        REAL_PROJECT_ROOT, ...
        'results');
if ~exist(REAL_RESULTS_ROOT,'dir')
    mkdir(REAL_RESULTS_ROOT);
end
REAL_TLOG_FILES = ...
    dir( ...
        fullfile( ...
            REAL_PROJECT_ROOT, ...
            '*.tlog'));
if isempty(REAL_TLOG_FILES)
    warning( ...
        'RealFlight:NoTLOGFiles', ...
        ['No .tlog files were found in:\n%s'], ...
        REAL_PROJECT_ROOT);
else
    fprintf('\n');
    fprintf('==============================================================\n');
    fprintf(' REAL FLIGHT TLOG ANALYSIS\n');
    fprintf('==============================================================\n');
    fprintf('Project folder:\n%s\n\n', REAL_PROJECT_ROOT);
    fprintf( ...
        'TLOG files found: %d\n\n', ...
        numel(REAL_TLOG_FILES));
    for k = 1:numel(REAL_TLOG_FILES)
        fprintf( ...
            '  [%d] %s\n', ...
            k, ...
            REAL_TLOG_FILES(k).name);
    end
end
REAL_TLOG_FILE = ...
    "";
REAL_TLOG_PATH = ...
    "";
if numel(REAL_TLOG_FILES) == 1
    REAL_TLOG_FILE = ...
        string( ...
            REAL_TLOG_FILES(1).name);
    REAL_TLOG_PATH = ...
        string( ...
            fullfile( ...
                REAL_PROJECT_ROOT, ...
                REAL_TLOG_FILES(1).name));
    fprintf('\n');
    fprintf( ...
        'Selected TLOG:\n%s\n', ...
        REAL_TLOG_FILE);
elseif numel(REAL_TLOG_FILES) > 1
    fprintf('\n');
    fprintf( ...
        ['Multiple TLOG files detected.\n', ...
         'The analysis script will require an explicit selection.\n']);
end
REAL_CONFIG = ...
    struct();
REAL_CONFIG.schemaVersion = ...
    "1.0";
REAL_CONFIG.frames.navigation = ...
    "NED";
REAL_CONFIG.frames.body = ...
    "FRD";
REAL_CONFIG.frames.body_x = ...
    "Forward";
REAL_CONFIG.frames.body_y = ...
    "Right";
REAL_CONFIG.frames.body_z = ...
    "Down";
REAL_CONFIG.units.position = ...
    "m";
REAL_CONFIG.units.velocity = ...
    "m/s";
REAL_CONFIG.units.acceleration = ...
    "m/s^2";
REAL_CONFIG.units.attitude = ...
    "rad";
REAL_CONFIG.units.angularRate = ...
    "rad/s";
REAL_CONFIG.units.motorSpeed = ...
    "rad/s";
REAL_CONFIG.units.pwm = ...
    "us";
REAL_CONFIG.units.voltage = ...
    "V";
REAL_CONFIG.units.current = ...
    "A";
REAL_CONFIG.output.createFigures = ...
    true;
REAL_CONFIG.output.createTables = ...
    true;
REAL_CONFIG.output.saveMAT = ...
    true;
REAL_CONFIG.output.savePNG = ...
    true;
REAL_CONFIG.output.saveCSV = ...
    true;
REAL_CONFIG.metricPolicy.directLabel = ...
    "DIRECT";
REAL_CONFIG.metricPolicy.derivedLabel = ...
    "DERIVED";
REAL_CONFIG.metricPolicy.notAvailableLabel = ...
    "NOT_AVAILABLE";
REAL_CONFIG.output.resultPrefix = ...
    "REAL";
if ~exist(REAL_RESULTS_ROOT,'dir')
    error( ...
        'RealFlight:ResultsFolderCreationFailed', ...
        ['Unable to create results folder:\n%s'], ...
        REAL_RESULTS_ROOT);
end
fprintf('\n');
fprintf('Results folder:\n%s\n', REAL_RESULTS_ROOT);
fprintf('\n');
fprintf('Navigation frame: %s\n', REAL_CONFIG.frames.navigation);
fprintf('Body frame:       %s\n', REAL_CONFIG.frames.body);
fprintf('\n');
fprintf('Real-flight analysis initialization complete.\n');
fprintf('==============================================================\n');
fprintf('\n');
clear this_file k;
