if ~exist('REAL_DATA','var') || ...
        ~isstruct(REAL_DATA)
    error( ...
        'RealFlight:NormalizedDataUnavailable', ...
        ['REAL_DATA was not found.\n\n', ...
         'Run normalize_real_flight_data first.']);
end
INSPECTION = ...
    struct();
INSPECTION.preWindow_s = ...
    5.0;
INSPECTION.postWindow_s = ...
    5.0;
INSPECTION.minimumArmedDuration_s = ...
    1.0;
INSPECTION.minimumAirborneDuration_s = ...
    0.5;
INSPECTION.fallback.enabled = ...
    true;
INSPECTION.fallback.motorLowStateFraction = ...
    0.20;
INSPECTION.fallback.minimumOperationalMotorPWM_us = ...
    1250;
INSPECTION.fallback.motorDeltaPWM_us = ...
    100;
INSPECTION.fallback.motorMergeGap_s = ...
    0.75;
INSPECTION.fallback.minimumFlightDuration_s = ...
    2.0;
INSPECTION.fallback.baselineWindow_s = ...
    5.0;
INSPECTION.fallback.relativeAltitudeThreshold_m = ...
    0.25;
INSPECTION.fallback.groundSpeedThreshold_m_s = ...
    0.35;
INSPECTION.fallback.minimumEvidenceInterval_s = ...
    0.75;
INSPECTION.fallback.minimumIndependentEvidenceDuration_s = ...
    0.75;
INSPECTION.fallback.requireIndependentEvidence = ...
    true;
INSPECTION.fallback.minimumMotorOnlyDuration_s = ...
    5.0;
INSPECTION.fallback.mergeGap_s = ...
    1.0;
INSPECTION.telemetryFallback.enabled = ...
    true;
INSPECTION.telemetryFallback.minimumSourceCount = ...
    2;
INSPECTION.telemetryFallback.minimumWindowDuration_s = ...
    5.0;
logDuration_s = ...
    REAL_DATA.Metadata.LogDuration_s;
REAL_FLIGHT_INSPECTION = ...
    struct();
REAL_ARMED_INTERVALS = ...
    table();
REAL_AIRBORNE_INTERVALS = ...
    table();
REAL_PHYSICAL_FLIGHT_INTERVALS = ...
    table();
REAL_TELEMETRY_FALLBACK_INTERVALS = ...
    table();
REAL_FLIGHT_ATTEMPTS = ...
    table();
PHYSICAL_FALLBACK_DIAGNOSTICS = ...
    struct();
TELEMETRY_FALLBACK_DIAGNOSTICS = ...
    struct();
physicalFallbackUsed = ...
    false;
telemetryFallbackUsed = ...
    false;
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' REAL FLIGHT INSPECTION\n');
fprintf('==============================================================\n\n');
armedAvailable = ...
    isfield(REAL_DATA,'Status') && ...
    isfield(REAL_DATA.Status,'Heartbeat') && ...
    ~isempty(REAL_DATA.Status.Heartbeat);
if armedAvailable
    HB = ...
        REAL_DATA.Status.Heartbeat;
    tArmed = ...
        double(HB.Time_s);
    armedState = ...
        logical(HB.Armed);
    REAL_ARMED_INTERVALS = ...
        logicalIntervals( ...
            tArmed, ...
            armedState, ...
            INSPECTION.minimumArmedDuration_s);
    if ~isempty(REAL_ARMED_INTERVALS)
        REAL_ARMED_INTERVALS.Properties.VariableNames = { ...
            'StartTime_s', ...
            'EndTime_s', ...
            'Duration_s'};
        REAL_ARMED_INTERVALS.Interval = ...
            (1:height(REAL_ARMED_INTERVALS)).';
        REAL_ARMED_INTERVALS = ...
            movevars( ...
                REAL_ARMED_INTERVALS, ...
                'Interval', ...
                'Before',1);
    end
else
    warning( ...
        'RealFlight:ArmedStateUnavailable', ...
        'No valid HEARTBEAT armed-state data were found.');
end
airStateAvailable = ...
    isfield(REAL_DATA,'Status') && ...
    isfield(REAL_DATA.Status,'LandedState') && ...
    ~isempty(REAL_DATA.Status.LandedState);
if airStateAvailable
    LS = ...
        REAL_DATA.Status.LandedState;
    tAir = ...
        double(LS.Time_s);
    landedState = ...
        double(LS.LandedState);
    airborneState = ...
        landedState == 2 | ...
        landedState == 3 | ...
        landedState == 4;
    REAL_AIRBORNE_INTERVALS = ...
        logicalIntervals( ...
            tAir, ...
            airborneState, ...
            INSPECTION.minimumAirborneDuration_s);
    if ~isempty(REAL_AIRBORNE_INTERVALS)
        REAL_AIRBORNE_INTERVALS.Properties.VariableNames = { ...
            'StartTime_s', ...
            'EndTime_s', ...
            'Duration_s'};
        REAL_AIRBORNE_INTERVALS.Interval = ...
            (1:height(REAL_AIRBORNE_INTERVALS)).';
        REAL_AIRBORNE_INTERVALS = ...
            movevars( ...
                REAL_AIRBORNE_INTERVALS, ...
                'Interval', ...
                'Before',1);
    end
else
    warning( ...
        'RealFlight:LandedStateUnavailable', ...
        'No EXTENDED_SYS_STATE data were found.');
end
if ~isempty(REAL_ARMED_INTERVALS)
    numberAttempts = ...
        height(REAL_ARMED_INTERVALS);
    Attempt = ...
        (1:numberAttempts).';
    StartTime_s = ...
        REAL_ARMED_INTERVALS.StartTime_s;
    EndTime_s = ...
        REAL_ARMED_INTERVALS.EndTime_s;
    Duration_s = ...
        REAL_ARMED_INTERVALS.Duration_s;
    AirborneDetected = ...
        false(numberAttempts,1);
    AirborneDuration_s = ...
        zeros(numberAttempts,1);
    TakeoffStateDetected = ...
        false(numberAttempts,1);
    LandingStateDetected = ...
        false(numberAttempts,1);
    for k = 1:numberAttempts
        t0 = ...
            StartTime_s(k);
        t1 = ...
            EndTime_s(k);
        if airStateAvailable
            mask = ...
                LS.Time_s >= t0 & ...
                LS.Time_s <= t1;
            if any(mask)
                statesInside = ...
                    double(LS.LandedState(mask));
                AirborneDetected(k) = ...
                    any( ...
                        statesInside == 2 | ...
                        statesInside == 3 | ...
                        statesInside == 4);
                TakeoffStateDetected(k) = ...
                    any(statesInside == 3);
                LandingStateDetected(k) = ...
                    any(statesInside == 4);
            end
        end
        if ~isempty(REAL_AIRBORNE_INTERVALS)
            totalAirTime = ...
                0;
            for j = 1:height(REAL_AIRBORNE_INTERVALS)
                overlapStart = ...
                    max( ...
                        t0, ...
                        REAL_AIRBORNE_INTERVALS.StartTime_s(j));
                overlapEnd = ...
                    min( ...
                        t1, ...
                        REAL_AIRBORNE_INTERVALS.EndTime_s(j));
                overlapDuration = ...
                    max( ...
                        0, ...
                        overlapEnd - overlapStart);
                totalAirTime = ...
                    totalAirTime + ...
                    overlapDuration;
            end
            AirborneDuration_s(k) = ...
                totalAirTime;
        end
    end
    DetectionSource = ...
        repmat( ...
            "HEARTBEAT_ARMED", ...
            numberAttempts, ...
            1);
    REAL_FLIGHT_ATTEMPTS = ...
        table( ...
            Attempt, ...
            StartTime_s, ...
            EndTime_s, ...
            Duration_s, ...
            AirborneDetected, ...
            AirborneDuration_s, ...
            TakeoffStateDetected, ...
            LandingStateDetected, ...
            DetectionSource);
end
if isempty(REAL_FLIGHT_ATTEMPTS) && ...
        ~isempty(REAL_AIRBORNE_INTERVALS)
    numberAttempts = ...
        height(REAL_AIRBORNE_INTERVALS);
    Attempt = ...
        (1:numberAttempts).';
    StartTime_s = ...
        REAL_AIRBORNE_INTERVALS.StartTime_s;
    EndTime_s = ...
        REAL_AIRBORNE_INTERVALS.EndTime_s;
    Duration_s = ...
        REAL_AIRBORNE_INTERVALS.Duration_s;
    AirborneDetected = ...
        true(numberAttempts,1);
    AirborneDuration_s = ...
        Duration_s;
    TakeoffStateDetected = ...
        false(numberAttempts,1);
    LandingStateDetected = ...
        false(numberAttempts,1);
    DetectionSource = ...
        repmat( ...
            "EXTENDED_SYS_STATE_AIRBORNE", ...
            numberAttempts, ...
            1);
    REAL_FLIGHT_ATTEMPTS = ...
        table( ...
            Attempt, ...
            StartTime_s, ...
            EndTime_s, ...
            Duration_s, ...
            AirborneDetected, ...
            AirborneDuration_s, ...
            TakeoffStateDetected, ...
            LandingStateDetected, ...
            DetectionSource);
end
if isempty(REAL_FLIGHT_ATTEMPTS) && ...
        INSPECTION.fallback.enabled
    [ ...
        REAL_PHYSICAL_FLIGHT_INTERVALS, ...
        PHYSICAL_FALLBACK_DIAGNOSTICS ...
    ] = ...
        localDetectPhysicalFlightIntervals( ...
            REAL_DATA, ...
            INSPECTION.fallback);
    if ~isempty(REAL_PHYSICAL_FLIGHT_INTERVALS)
        physicalFallbackUsed = ...
            true;
        numberAttempts = ...
            height(REAL_PHYSICAL_FLIGHT_INTERVALS);
        Attempt = ...
            (1:numberAttempts).';
        StartTime_s = ...
            REAL_PHYSICAL_FLIGHT_INTERVALS.StartTime_s;
        EndTime_s = ...
            REAL_PHYSICAL_FLIGHT_INTERVALS.EndTime_s;
        Duration_s = ...
            REAL_PHYSICAL_FLIGHT_INTERVALS.Duration_s;
        AirborneDetected = ...
            contains( ...
                REAL_PHYSICAL_FLIGHT_INTERVALS.EvidenceSources, ...
                "ALTITUDE") | ...
            contains( ...
                REAL_PHYSICAL_FLIGHT_INTERVALS.EvidenceSources, ...
                "GROUND_SPEED");
        AirborneDuration_s = ...
            zeros(numberAttempts,1);
        AirborneDuration_s(AirborneDetected) = ...
            Duration_s(AirborneDetected);
        TakeoffStateDetected = ...
            false(numberAttempts,1);
        LandingStateDetected = ...
            false(numberAttempts,1);
        DetectionSource = ...
            repmat( ...
                "PHYSICAL_EVIDENCE_FALLBACK", ...
                numberAttempts, ...
                1);
        PhysicalEvidenceCount = ...
            REAL_PHYSICAL_FLIGHT_INTERVALS.EvidenceCount;
        PhysicalEvidenceSources = ...
            REAL_PHYSICAL_FLIGHT_INTERVALS.EvidenceSources;
        REAL_FLIGHT_ATTEMPTS = ...
            table( ...
                Attempt, ...
                StartTime_s, ...
                EndTime_s, ...
                Duration_s, ...
                AirborneDetected, ...
                AirborneDuration_s, ...
                TakeoffStateDetected, ...
                LandingStateDetected, ...
                DetectionSource, ...
                PhysicalEvidenceCount, ...
                PhysicalEvidenceSources);
    end
end
if isempty(REAL_FLIGHT_ATTEMPTS) && ...
        INSPECTION.telemetryFallback.enabled
    [ ...
        REAL_TELEMETRY_FALLBACK_INTERVALS, ...
        TELEMETRY_FALLBACK_DIAGNOSTICS ...
    ] = ...
        localDetectTelemetryWindow( ...
            REAL_DATA, ...
            INSPECTION.telemetryFallback, ...
            logDuration_s);
    if ~isempty(REAL_TELEMETRY_FALLBACK_INTERVALS)
        telemetryFallbackUsed = ...
            true;
        numberAttempts = ...
            height(REAL_TELEMETRY_FALLBACK_INTERVALS);
        Attempt = ...
            (1:numberAttempts).';
        StartTime_s = ...
            REAL_TELEMETRY_FALLBACK_INTERVALS.StartTime_s;
        EndTime_s = ...
            REAL_TELEMETRY_FALLBACK_INTERVALS.EndTime_s;
        Duration_s = ...
            REAL_TELEMETRY_FALLBACK_INTERVALS.Duration_s;
        AirborneDetected = ...
            false(numberAttempts,1);
        AirborneDuration_s = ...
            zeros(numberAttempts,1);
        TakeoffStateDetected = ...
            false(numberAttempts,1);
        LandingStateDetected = ...
            false(numberAttempts,1);
        DetectionSource = ...
            repmat( ...
                "TELEMETRY_WINDOW_FALLBACK", ...
                numberAttempts, ...
                1);
        TelemetrySourceCount = ...
            REAL_TELEMETRY_FALLBACK_INTERVALS.SourceCount;
        TelemetrySources = ...
            REAL_TELEMETRY_FALLBACK_INTERVALS.Sources;
        REAL_FLIGHT_ATTEMPTS = ...
            table( ...
                Attempt, ...
                StartTime_s, ...
                EndTime_s, ...
                Duration_s, ...
                AirborneDetected, ...
                AirborneDuration_s, ...
                TakeoffStateDetected, ...
                LandingStateDetected, ...
                DetectionSource, ...
                TelemetrySourceCount, ...
                TelemetrySources);
    end
end
if ~isempty(REAL_FLIGHT_ATTEMPTS)
    nAttempts = ...
        height(REAL_FLIGHT_ATTEMPTS);
    MaximumGroundSpeed_m_s = ...
        NaN(nAttempts,1);
    MaximumRelativeAltitude_m = ...
        NaN(nAttempts,1);
    MeanMotorPWM_us = ...
        NaN(nAttempts,1);
    MaximumMotorPWM_us = ...
        NaN(nAttempts,1);
    for k = 1:nAttempts
        t0 = ...
            REAL_FLIGHT_ATTEMPTS.StartTime_s(k);
        t1 = ...
            REAL_FLIGHT_ATTEMPTS.EndTime_s(k);
        if isfield(REAL_DATA,'Navigation') && ...
                isfield(REAL_DATA.Navigation,'VFR')
            VFR = ...
                REAL_DATA.Navigation.VFR;
            mask = ...
                VFR.Time_s >= t0 & ...
                VFR.Time_s <= t1;
            if any(mask)
                MaximumGroundSpeed_m_s(k) = ...
                    max( ...
                        VFR.GroundSpeed_m_s(mask), ...
                        [], ...
                        'omitnan');
            end
        end
        if isfield(REAL_DATA,'State') && ...
                isfield(REAL_DATA.State,'GlobalPosition')
            GP = ...
                REAL_DATA.State.GlobalPosition;
            mask = ...
                GP.Time_s >= t0 & ...
                GP.Time_s <= t1;
            if any(mask)
                MaximumRelativeAltitude_m(k) = ...
                    max( ...
                        GP.RelativeAltitude_m(mask), ...
                        [], ...
                        'omitnan');
            end
        end
        if isfield(REAL_DATA,'Actuator') && ...
                isfield(REAL_DATA.Actuator,'PWM')
            PWM = ...
                REAL_DATA.Actuator.PWM;
            mask = ...
                PWM.Time_s >= t0 & ...
                PWM.Time_s <= t1;
            if any(mask)
                motorPWM = ...
                    [ ...
                        PWM.PWM1_us(mask), ...
                        PWM.PWM2_us(mask), ...
                        PWM.PWM3_us(mask), ...
                        PWM.PWM4_us(mask) ...
                    ];
                validPWM = ...
                    motorPWM( ...
                        isfinite(motorPWM) & ...
                        motorPWM > 0);
                if ~isempty(validPWM)
                    MeanMotorPWM_us(k) = ...
                        mean( ...
                            validPWM, ...
                            'omitnan');
                    MaximumMotorPWM_us(k) = ...
                        max( ...
                            validPWM, ...
                            [], ...
                            'omitnan');
                end
            end
        end
    end
    REAL_FLIGHT_ATTEMPTS.MaximumGroundSpeed_m_s = ...
        MaximumGroundSpeed_m_s;
    REAL_FLIGHT_ATTEMPTS.MaximumRelativeAltitude_m = ...
        MaximumRelativeAltitude_m;
    REAL_FLIGHT_ATTEMPTS.MeanMotorPWM_us = ...
        MeanMotorPWM_us;
    REAL_FLIGHT_ATTEMPTS.MaximumMotorPWM_us = ...
        MaximumMotorPWM_us;
end
primaryAttemptAvailable = ...
    false;
primaryAttemptIndex = ...
    NaN;
selectionReason = ...
    "NONE";
if ~isempty(REAL_FLIGHT_ATTEMPTS)
    airborneCandidates = ...
        find( ...
            REAL_FLIGHT_ATTEMPTS.AirborneDuration_s > 0);
    if ~isempty(airborneCandidates)
        [~,localIndex] = ...
            max( ...
                REAL_FLIGHT_ATTEMPTS.AirborneDuration_s( ...
                    airborneCandidates));
        primaryAttemptIndex = ...
            airborneCandidates(localIndex);
        selectionReason = ...
            "LONGEST_AIRBORNE_INTERVAL";
        primaryAttemptAvailable = ...
            true;
    else
        [~,primaryAttemptIndex] = ...
            max( ...
                REAL_FLIGHT_ATTEMPTS.Duration_s);
        selectionReason = ...
            "LONGEST_ARMED_INTERVAL_NO_AIRBORNE_STATE";
        primaryAttemptAvailable = ...
            true;
    end
    if primaryAttemptAvailable && ...
            ismember( ...
                'DetectionSource', ...
                REAL_FLIGHT_ATTEMPTS.Properties.VariableNames)
        selectedDetectionSource = ...
            string( ...
                REAL_FLIGHT_ATTEMPTS.DetectionSource( ...
                    primaryAttemptIndex));
        if selectedDetectionSource == ...
                "PHYSICAL_EVIDENCE_FALLBACK"
            selectionReason = ...
                "PHYSICAL_EVIDENCE_FALLBACK";
        elseif selectedDetectionSource == ...
                "TELEMETRY_WINDOW_FALLBACK"
            selectionReason = ...
                "TELEMETRY_WINDOW_FALLBACK";
        end
    end
end
coreStart_s = ...
    NaN;
coreEnd_s = ...
    NaN;
inspectionStart_s = ...
    NaN;
inspectionEnd_s = ...
    NaN;
if primaryAttemptAvailable
    coreStart_s = ...
        REAL_FLIGHT_ATTEMPTS.StartTime_s( ...
            primaryAttemptIndex);
    coreEnd_s = ...
        REAL_FLIGHT_ATTEMPTS.EndTime_s( ...
            primaryAttemptIndex);
    inspectionStart_s = ...
        max( ...
            0, ...
            coreStart_s - ...
            INSPECTION.preWindow_s);
    inspectionEnd_s = ...
        min( ...
            logDuration_s, ...
            coreEnd_s + ...
            INSPECTION.postWindow_s);
end
PRIMARY_STATUS_MESSAGES = ...
    table();
if primaryAttemptAvailable && ...
        isfield(REAL_DATA.Status,'Messages')
    MSG = ...
        REAL_DATA.Status.Messages;
    mask = ...
        MSG.Time_s >= inspectionStart_s & ...
        MSG.Time_s <= inspectionEnd_s;
    PRIMARY_STATUS_MESSAGES = ...
        MSG(mask,:);
end
REAL_FLIGHT_INSPECTION.Configuration = ...
    INSPECTION;
REAL_FLIGHT_INSPECTION.ArmedAvailable = ...
    armedAvailable;
REAL_FLIGHT_INSPECTION.AirStateAvailable = ...
    airStateAvailable;
REAL_FLIGHT_INSPECTION.ArmedIntervals = ...
    REAL_ARMED_INTERVALS;
REAL_FLIGHT_INSPECTION.AirborneIntervals = ...
    REAL_AIRBORNE_INTERVALS;
REAL_FLIGHT_INSPECTION.PhysicalFlightIntervals = ...
    REAL_PHYSICAL_FLIGHT_INTERVALS;
REAL_FLIGHT_INSPECTION.PhysicalFallbackUsed = ...
    physicalFallbackUsed;
REAL_FLIGHT_INSPECTION.PhysicalFallbackDiagnostics = ...
    PHYSICAL_FALLBACK_DIAGNOSTICS;
REAL_FLIGHT_INSPECTION.TelemetryFallbackIntervals = ...
    REAL_TELEMETRY_FALLBACK_INTERVALS;
REAL_FLIGHT_INSPECTION.TelemetryFallbackUsed = ...
    telemetryFallbackUsed;
REAL_FLIGHT_INSPECTION.TelemetryFallbackDiagnostics = ...
    TELEMETRY_FALLBACK_DIAGNOSTICS;
REAL_FLIGHT_INSPECTION.Attempts = ...
    REAL_FLIGHT_ATTEMPTS;
REAL_FLIGHT_INSPECTION.PrimaryAttemptAvailable = ...
    primaryAttemptAvailable;
REAL_FLIGHT_INSPECTION.PrimaryAttemptIndex = ...
    primaryAttemptIndex;
REAL_FLIGHT_INSPECTION.SelectionReason = ...
    selectionReason;
REAL_FLIGHT_INSPECTION.CoreStartTime_s = ...
    coreStart_s;
REAL_FLIGHT_INSPECTION.CoreEndTime_s = ...
    coreEnd_s;
REAL_FLIGHT_INSPECTION.InspectionStartTime_s = ...
    inspectionStart_s;
REAL_FLIGHT_INSPECTION.InspectionEndTime_s = ...
    inspectionEnd_s;
REAL_FLIGHT_INSPECTION.StatusMessages = ...
    PRIMARY_STATUS_MESSAGES;
fprintf('--------------------------------------------------------------\n');
fprintf(' ARMED INTERVALS\n');
fprintf('--------------------------------------------------------------\n\n');
if isempty(REAL_ARMED_INTERVALS)
    fprintf('No armed intervals detected.\n\n');
else
    disp(REAL_ARMED_INTERVALS);
end
fprintf('--------------------------------------------------------------\n');
fprintf(' AIRBORNE INTERVALS\n');
fprintf('--------------------------------------------------------------\n\n');
if isempty(REAL_AIRBORNE_INTERVALS)
    fprintf('No airborne intervals detected.\n\n');
else
    disp(REAL_AIRBORNE_INTERVALS);
end
fprintf('--------------------------------------------------------------\n');
fprintf(' PHYSICAL-EVIDENCE FALLBACK\n');
fprintf('--------------------------------------------------------------\n\n');
if physicalFallbackUsed
    fprintf('Fallback status:        USED\n');
    fprintf('Reason:                 No usable Armed/Airborne interval\n\n');
    disp(REAL_PHYSICAL_FLIGHT_INTERVALS);
elseif INSPECTION.fallback.enabled
    fprintf('Fallback status:        NOT USED\n');
    if ~isempty(REAL_ARMED_INTERVALS) || ...
            ~isempty(REAL_AIRBORNE_INTERVALS)
        fprintf('Reason:                 Preferred MAVLink state detection succeeded.\n\n');
    elseif telemetryFallbackUsed
        fprintf('Reason:                 No valid operational physical-evidence interval found.\n\n');
    else
        fprintf('Reason:                 No valid operational physical-evidence interval found.\n\n');
    end
else
    fprintf('Fallback status:        DISABLED\n\n');
end
fprintf('--------------------------------------------------------------\n');
fprintf(' TELEMETRY-WINDOW FALLBACK\n');
fprintf('--------------------------------------------------------------\n\n');
if telemetryFallbackUsed
    fprintf('Fallback status:        USED\n');
    fprintf('Reason:                 No usable state/physical interval\n');
    fprintf('Interpretation:         Analysis window from valid telemetry support\n\n');
    disp(REAL_TELEMETRY_FALLBACK_INTERVALS);
elseif INSPECTION.telemetryFallback.enabled
    fprintf('Fallback status:        NOT USED\n');
    if ~isempty(REAL_FLIGHT_ATTEMPTS)
        fprintf('Reason:                 A higher-priority detector succeeded.\n\n');
    else
        fprintf('Reason:                 No valid telemetry-supported window found.\n\n');
    end
else
    fprintf('Fallback status:        DISABLED\n\n');
end
fprintf('--------------------------------------------------------------\n');
fprintf(' CANDIDATE FLIGHT ATTEMPTS\n');
fprintf('--------------------------------------------------------------\n\n');
if isempty(REAL_FLIGHT_ATTEMPTS)
    fprintf('No candidate flight attempts detected.\n\n');
else
    disp(REAL_FLIGHT_ATTEMPTS);
end
fprintf('--------------------------------------------------------------\n');
fprintf(' PRIMARY ANALYSIS WINDOW\n');
fprintf('--------------------------------------------------------------\n\n');
if primaryAttemptAvailable
    fprintf( ...
        'Selected attempt:       %d\n', ...
        primaryAttemptIndex);
    fprintf( ...
        'Selection reason:       %s\n', ...
        selectionReason);
    fprintf( ...
        'Core start:             %.3f s\n', ...
        coreStart_s);
    fprintf( ...
        'Core end:               %.3f s\n', ...
        coreEnd_s);
    fprintf( ...
        'Core duration:          %.3f s\n', ...
        coreEnd_s-coreStart_s);
    fprintf( ...
        'Inspection start:       %.3f s\n', ...
        inspectionStart_s);
    fprintf( ...
        'Inspection end:         %.3f s\n', ...
        inspectionEnd_s);
    fprintf('\n');
    if REAL_FLIGHT_ATTEMPTS.AirborneDetected( ...
            primaryAttemptIndex)
        if selectionReason == "PHYSICAL_EVIDENCE_FALLBACK"
            fprintf( ...
                ['Physical flight state: INFERRED FROM MEASURED ', ...
                 'PHYSICAL EVIDENCE\n']);
        else
            fprintf( ...
                'Physical flight state: AIRBORNE DETECTED\n');
        end
    else
        if selectionReason == "PHYSICAL_EVIDENCE_FALLBACK"
            fprintf( ...
                ['Physical flight state: MOTOR-ACTIVITY FALLBACK ONLY\n', ...
                 'No MAVLink airborne state was available.\n']);
        elseif selectionReason == "TELEMETRY_WINDOW_FALLBACK"
            fprintf( ...
                ['Physical flight state: NOT DIRECTLY AVAILABLE FROM MAVLink\n', ...
                 'Analysis window: VALID FLIGHT TELEMETRY SUPPORT\n', ...
                 'No armed/airborne claim is inferred from this fallback.\n']);
        else
            fprintf( ...
                ['Physical flight state: NO AIRBORNE STATE DETECTED\n', ...
                 'This appears to be an armed / failed attempt rather than\n', ...
                 'a successful flight.\n']);
        end
    end
else
    fprintf( ...
        'No valid primary analysis window could be selected.\n');
end
if ~isempty(PRIMARY_STATUS_MESSAGES)
    fprintf('\n');
    fprintf('--------------------------------------------------------------\n');
    fprintf(' AUTOPILOT STATUS MESSAGES IN PRIMARY WINDOW\n');
    fprintf('--------------------------------------------------------------\n\n');
    disp(PRIMARY_STATUS_MESSAGES);
end
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' REAL FLIGHT INSPECTION COMPLETE\n');
fprintf('==============================================================\n\n');
clear HB ...
      LS ...
      MSG ...
      VFR ...
      GP ...
      PWM ...
      tArmed ...
      tAir ...
      armedState ...
      airborneState ...
      landedState ...
      numberAttempts ...
      nAttempts ...
      Attempt ...
      StartTime_s ...
      EndTime_s ...
      Duration_s ...
      AirborneDetected ...
      AirborneDuration_s ...
      TakeoffStateDetected ...
      LandingStateDetected ...
      DetectionSource ...
      PhysicalEvidenceCount ...
      PhysicalEvidenceSources ...
      TelemetrySourceCount ...
      TelemetrySources ...
      selectedDetectionSource ...
      MaximumGroundSpeed_m_s ...
      MaximumRelativeAltitude_m ...
      MeanMotorPWM_us ...
      MaximumMotorPWM_us ...
      motorPWM ...
      validPWM ...
      statesInside ...
      totalAirTime ...
      overlapStart ...
      overlapEnd ...
      overlapDuration ...
      airborneCandidates ...
      primaryAttemptAvailable ...
      primaryAttemptIndex ...
      selectionReason ...
      coreStart_s ...
      coreEnd_s ...
      inspectionStart_s ...
      inspectionEnd_s ...
      PRIMARY_STATUS_MESSAGES ...
      armedAvailable ...
      airStateAvailable ...
      physicalFallbackUsed ...
      telemetryFallbackUsed ...
      PHYSICAL_FALLBACK_DIAGNOSTICS ...
      TELEMETRY_FALLBACK_DIAGNOSTICS ...
      logDuration_s ...
      mask ...
      t0 ...
      t1 ...
      k ...
      j ...
      localIndex;
function intervals = logicalIntervals( ...
    time_s, ...
    state, ...
    minimumDuration_s)
    time_s = ...
        double(time_s(:));
    state = ...
        logical(state(:));
    valid = ...
        isfinite(time_s);
    time_s = ...
        time_s(valid);
    state = ...
        state(valid);
    if isempty(time_s)
        intervals = ...
            table();
        return;
    end
    [time_s,order] = ...
        sort(time_s);
    state = ...
        state(order);
    stateExtended = ...
        [false; state; false];
    transitions = ...
        diff(stateExtended);
    startIndices = ...
        find(transitions == 1);
    endIndices = ...
        find(transitions == -1) - 1;
    StartTime_s = ...
        time_s(startIndices);
    EndTime_s = ...
        time_s(endIndices);
    Duration_s = ...
        EndTime_s - ...
        StartTime_s;
    keep = ...
        Duration_s >= ...
        minimumDuration_s;
    StartTime_s = ...
        StartTime_s(keep);
    EndTime_s = ...
        EndTime_s(keep);
    Duration_s = ...
        Duration_s(keep);
    intervals = ...
        table( ...
            StartTime_s, ...
            EndTime_s, ...
            Duration_s);
end
function [intervals,diagnostics] = localDetectPhysicalFlightIntervals( ...
    REAL_DATA, ...
    F)
    intervals = ...
        table();
    diagnostics = ...
        struct();
    diagnostics.SelectionMethod = ...
        "NONE";
    diagnostics.MotorEvidenceAvailable = ...
        false;
    diagnostics.AltitudeEvidenceAvailable = ...
        false;
    diagnostics.GroundSpeedEvidenceAvailable = ...
        false;
    diagnostics.MotorBaselinePWM_us = ...
        NaN;
    diagnostics.MotorThresholdPWM_us = ...
        NaN;
    diagnostics.RelativeAltitudeBaseline_m = ...
        NaN;
    diagnostics.RelativeAltitudeBaselineSource = ...
        "NONE";
    diagnostics.RelativeAltitudeThreshold_m = ...
        F.relativeAltitudeThreshold_m;
    diagnostics.GroundSpeedThreshold_m_s = ...
        F.groundSpeedThreshold_m_s;
    diagnostics.AcceptedIntervals = ...
        0;
    diagnostics.RawMotorIntervals = ...
        table();
    diagnostics.RawAltitudeIntervals = ...
        table();
    diagnostics.RawGroundSpeedIntervals = ...
        table();
    diagnostics.RawEvidenceIntervals = ...
        table();
    tMotor = ...
        zeros(0,1);
    meanPWM = ...
        zeros(0,1);
    motorIntervals = ...
        table();
    altitudeIntervals = ...
        table();
    speedIntervals = ...
        table();
    altitudeSourceAvailable = ...
        false;
    speedSourceAvailable = ...
        false;
    if isfield(REAL_DATA,'Actuator') && ...
            isfield(REAL_DATA.Actuator,'PWM') && ...
            ~isempty(REAL_DATA.Actuator.PWM)
        PWM = ...
            REAL_DATA.Actuator.PWM;
        requiredPWMFields = { ...
            'Time_s', ...
            'PWM1_us', ...
            'PWM2_us', ...
            'PWM3_us', ...
            'PWM4_us'};
        pwmFieldsAvailable = ...
            true;
        for fieldIndex = 1:numel(requiredPWMFields)
            if ~localHasFieldOrVariable( ...
                    PWM, ...
                    requiredPWMFields{fieldIndex})
                pwmFieldsAvailable = ...
                    false;
                break;
            end
        end
        if pwmFieldsAvailable
            tRaw = ...
                double(PWM.Time_s(:));
            motorRaw = [ ...
                double(PWM.PWM1_us(:)), ...
                double(PWM.PWM2_us(:)), ...
                double(PWM.PWM3_us(:)), ...
                double(PWM.PWM4_us(:))];
            validRow = ...
                isfinite(tRaw) & ...
                any(isfinite(motorRaw),2);
            tRaw = ...
                tRaw(validRow);
            motorRaw = ...
                motorRaw(validRow,:);
            if ~isempty(tRaw)
                meanPWMRaw = ...
                    mean( ...
                        motorRaw, ...
                        2, ...
                        'omitnan');
                [tMotor,meanPWM] = ...
                    localSanitizeScalarSeries( ...
                        tRaw, ...
                        meanPWMRaw);
                if numel(tMotor) >= 2
                    lowStatePWM = ...
                        localLowStateBaseline( ...
                            meanPWM, ...
                            F.motorLowStateFraction);
                    thresholdPWM = ...
                        max( ...
                            F.minimumOperationalMotorPWM_us, ...
                            lowStatePWM + ...
                            F.motorDeltaPWM_us);
                    motorActive = ...
                        isfinite(meanPWM) & ...
                        meanPWM >= thresholdPWM;
                    rawMotorIntervals = ...
                        logicalIntervals( ...
                            tMotor, ...
                            motorActive, ...
                            F.minimumEvidenceInterval_s);
                    motorIntervals = ...
                        localMergeSimpleIntervals( ...
                            rawMotorIntervals, ...
                            F.motorMergeGap_s, ...
                            F.minimumFlightDuration_s);
                    diagnostics.MotorBaselinePWM_us = ...
                        lowStatePWM;
                    diagnostics.MotorThresholdPWM_us = ...
                        thresholdPWM;
                    diagnostics.RawMotorIntervals = ...
                        motorIntervals;
                    diagnostics.MotorEvidenceAvailable = ...
                        ~isempty(motorIntervals);
                end
            end
        end
    end
    if isfield(REAL_DATA,'State') && ...
            isfield(REAL_DATA.State,'GlobalPosition') && ...
            ~isempty(REAL_DATA.State.GlobalPosition)
        GP = ...
            REAL_DATA.State.GlobalPosition;
        if localHasFieldOrVariable(GP,'Time_s') && ...
                localHasFieldOrVariable(GP,'RelativeAltitude_m')
            tAltitudeRaw = ...
                double(GP.Time_s(:));
            altitudeRaw = ...
                double(GP.RelativeAltitude_m(:));
            [tAltitude,altitude] = ...
                localSanitizeScalarSeries( ...
                    tAltitudeRaw, ...
                    altitudeRaw);
            if numel(tAltitude) >= 2
                altitudeSourceAvailable = ...
                    true;
                baselineAltitude = ...
                    NaN;
                baselineSource = ...
                    "NONE";
                if numel(tMotor) >= 2 && ...
                        isfinite( ...
                            diagnostics.MotorThresholdPWM_us)
                    pwmAtAltitude = ...
                        interp1( ...
                            tMotor, ...
                            meanPWM, ...
                            tAltitude, ...
                            'previous', ...
                            NaN);
                    lowMotorAltitudeMask = ...
                        isfinite(pwmAtAltitude) & ...
                        pwmAtAltitude < ...
                        diagnostics.MotorThresholdPWM_us & ...
                        isfinite(altitude);
                    lowMotorAltitude = ...
                        altitude(lowMotorAltitudeMask);
                    if numel(lowMotorAltitude) >= 3
                        baselineAltitude = ...
                            median( ...
                                lowMotorAltitude, ...
                                'omitnan');
                        baselineSource = ...
                            "LOW_PWM_ALTITUDE_SAMPLES";
                    end
                end
                if ~isfinite(baselineAltitude)
                    baselineAltitude = ...
                        localInitialBaseline( ...
                            tAltitude, ...
                            altitude, ...
                            F.baselineWindow_s);
                    baselineSource = ...
                        "INITIAL_TIME_BASELINE";
                end
                diagnostics.RelativeAltitudeBaseline_m = ...
                    baselineAltitude;
                diagnostics.RelativeAltitudeBaselineSource = ...
                    baselineSource;
                if isfinite(baselineAltitude)
                    altitudeExcursion = ...
                        abs( ...
                            altitude - ...
                            baselineAltitude);
                    altitudeActive = ...
                        altitudeExcursion >= ...
                        F.relativeAltitudeThreshold_m;
                    altitudeIntervals = ...
                        logicalIntervals( ...
                            tAltitude, ...
                            altitudeActive, ...
                            F.minimumEvidenceInterval_s);
                    diagnostics.RawAltitudeIntervals = ...
                        altitudeIntervals;
                    diagnostics.AltitudeEvidenceAvailable = ...
                        ~isempty(altitudeIntervals);
                end
            end
        end
    end
    if isfield(REAL_DATA,'Navigation') && ...
            isfield(REAL_DATA.Navigation,'VFR') && ...
            ~isempty(REAL_DATA.Navigation.VFR)
        VFR = ...
            REAL_DATA.Navigation.VFR;
        if localHasFieldOrVariable(VFR,'Time_s') && ...
                localHasFieldOrVariable(VFR,'GroundSpeed_m_s')
            tSpeedRaw = ...
                double(VFR.Time_s(:));
            groundSpeedRaw = ...
                double(VFR.GroundSpeed_m_s(:));
            [tSpeed,groundSpeed] = ...
                localSanitizeScalarSeries( ...
                    tSpeedRaw, ...
                    groundSpeedRaw);
            if numel(tSpeed) >= 2
                speedSourceAvailable = ...
                    true;
                speedActive = ...
                    isfinite(groundSpeed) & ...
                    groundSpeed >= ...
                    F.groundSpeedThreshold_m_s;
                speedIntervals = ...
                    logicalIntervals( ...
                        tSpeed, ...
                        speedActive, ...
                        F.minimumEvidenceInterval_s);
                diagnostics.RawGroundSpeedIntervals = ...
                    speedIntervals;
                diagnostics.GroundSpeedEvidenceAvailable = ...
                    ~isempty(speedIntervals);
            end
        end
    end
    if ~isempty(motorIntervals)
        acceptedStart = ...
            zeros(0,1);
        acceptedEnd = ...
            zeros(0,1);
        acceptedSources = ...
            strings(0,1);
        acceptedCount = ...
            zeros(0,1);
        independentSourceExists = ...
            altitudeSourceAvailable || ...
            speedSourceAvailable;
        for k = 1:height(motorIntervals)
            candidateStart = ...
                motorIntervals.StartTime_s(k);
            candidateEnd = ...
                motorIntervals.EndTime_s(k);
            candidateDuration = ...
                candidateEnd - ...
                candidateStart;
            sourceList = ...
                "MOTOR_PWM";
            independentEvidenceCount = ...
                0;
            altitudeOverlap_s = ...
                localTotalOverlapDuration( ...
                    candidateStart, ...
                    candidateEnd, ...
                    altitudeIntervals);
            if altitudeOverlap_s >= ...
                    F.minimumIndependentEvidenceDuration_s
                sourceList(end+1,1) = ...
                    "ALTITUDE"; %#ok<AGROW>
                independentEvidenceCount = ...
                    independentEvidenceCount + 1;
            end
            speedOverlap_s = ...
                localTotalOverlapDuration( ...
                    candidateStart, ...
                    candidateEnd, ...
                    speedIntervals);
            if speedOverlap_s >= ...
                    F.minimumIndependentEvidenceDuration_s
                sourceList(end+1,1) = ...
                    "GROUND_SPEED"; %#ok<AGROW>
                independentEvidenceCount = ...
                    independentEvidenceCount + 1;
            end
            durationValid = ...
                candidateDuration >= ...
                F.minimumFlightDuration_s;
            if F.requireIndependentEvidence && ...
                    independentSourceExists
                evidenceValid = ...
                    independentEvidenceCount >= 1;
            else
                evidenceValid = ...
                    candidateDuration >= ...
                    F.minimumMotorOnlyDuration_s;
            end
            if durationValid && ...
                    evidenceValid
                acceptedStart(end+1,1) = ...
                    candidateStart; %#ok<AGROW>
                acceptedEnd(end+1,1) = ...
                    candidateEnd; %#ok<AGROW>
                acceptedSources(end+1,1) = ...
                    strjoin( ...
                        unique( ...
                            sourceList, ...
                            'stable'), ...
                        "+"); %#ok<AGROW>
                acceptedCount(end+1,1) = ...
                    numel( ...
                        unique(sourceList)); %#ok<AGROW>
            end
        end
        if ~isempty(acceptedStart)
            Interval = ...
                (1:numel(acceptedStart)).';
            StartTime_s = ...
                acceptedStart;
            EndTime_s = ...
                acceptedEnd;
            Duration_s = ...
                acceptedEnd - ...
                acceptedStart;
            EvidenceCount = ...
                acceptedCount;
            EvidenceSources = ...
                acceptedSources;
            intervals = ...
                table( ...
                    Interval, ...
                    StartTime_s, ...
                    EndTime_s, ...
                    Duration_s, ...
                    EvidenceCount, ...
                    EvidenceSources);
            diagnostics.AcceptedIntervals = ...
                height(intervals);
            diagnostics.SelectionMethod = ...
                "PWM_ANCHORED_OPERATIONAL_FLIGHT";
            return;
        end
    end
    evidenceStart = ...
        zeros(0,1);
    evidenceEnd = ...
        zeros(0,1);
    evidenceSource = ...
        strings(0,1);
    if ~isempty(motorIntervals)
        evidenceStart = [ ...
            evidenceStart; ...
            motorIntervals.StartTime_s]; %#ok<AGROW>
        evidenceEnd = [ ...
            evidenceEnd; ...
            motorIntervals.EndTime_s]; %#ok<AGROW>
        evidenceSource = [ ...
            evidenceSource; ...
            repmat( ...
                "MOTOR_PWM", ...
                height(motorIntervals), ...
                1)]; %#ok<AGROW>
    end
    if ~isempty(altitudeIntervals)
        evidenceStart = [ ...
            evidenceStart; ...
            altitudeIntervals.StartTime_s]; %#ok<AGROW>
        evidenceEnd = [ ...
            evidenceEnd; ...
            altitudeIntervals.EndTime_s]; %#ok<AGROW>
        evidenceSource = [ ...
            evidenceSource; ...
            repmat( ...
                "ALTITUDE", ...
                height(altitudeIntervals), ...
                1)]; %#ok<AGROW>
    end
    if ~isempty(speedIntervals)
        evidenceStart = [ ...
            evidenceStart; ...
            speedIntervals.StartTime_s]; %#ok<AGROW>
        evidenceEnd = [ ...
            evidenceEnd; ...
            speedIntervals.EndTime_s]; %#ok<AGROW>
        evidenceSource = [ ...
            evidenceSource; ...
            repmat( ...
                "GROUND_SPEED", ...
                height(speedIntervals), ...
                1)]; %#ok<AGROW>
    end
    if isempty(evidenceStart)
        return;
    end
    evidenceTable = ...
        table( ...
            evidenceStart, ...
            evidenceEnd, ...
            evidenceSource, ...
            'VariableNames',{ ...
                'StartTime_s', ...
                'EndTime_s', ...
                'Source'});
    evidenceTable = ...
        sortrows( ...
            evidenceTable, ...
            'StartTime_s');
    diagnostics.RawEvidenceIntervals = ...
        evidenceTable;
    mergedStart = ...
        zeros(0,1);
    mergedEnd = ...
        zeros(0,1);
    mergedSources = ...
        strings(0,1);
    currentStart = ...
        evidenceTable.StartTime_s(1);
    currentEnd = ...
        evidenceTable.EndTime_s(1);
    currentSources = ...
        string(evidenceTable.Source(1));
    for k = 2:height(evidenceTable)
        nextStart = ...
            evidenceTable.StartTime_s(k);
        nextEnd = ...
            evidenceTable.EndTime_s(k);
        nextSource = ...
            string(evidenceTable.Source(k));
        if nextStart <= ...
                currentEnd + ...
                F.mergeGap_s
            currentEnd = ...
                max( ...
                    currentEnd, ...
                    nextEnd);
            currentSources = ...
                unique( ...
                    [ ...
                        currentSources(:); ...
                        nextSource ...
                    ], ...
                    'stable');
        else
            mergedStart(end+1,1) = ...
                currentStart; %#ok<AGROW>
            mergedEnd(end+1,1) = ...
                currentEnd; %#ok<AGROW>
            mergedSources(end+1,1) = ...
                strjoin( ...
                    currentSources, ...
                    "+"); %#ok<AGROW>
            currentStart = ...
                nextStart;
            currentEnd = ...
                nextEnd;
            currentSources = ...
                nextSource;
        end
    end
    mergedStart(end+1,1) = ...
        currentStart;
    mergedEnd(end+1,1) = ...
        currentEnd;
    mergedSources(end+1,1) = ...
        strjoin( ...
            currentSources, ...
            "+");
    mergedDuration = ...
        mergedEnd - ...
        mergedStart;
    keep = ...
        false(numel(mergedStart),1);
    evidenceCount = ...
        zeros(numel(mergedStart),1);
    for k = 1:numel(mergedStart)
        sourceParts = ...
            split( ...
                mergedSources(k), ...
                "+");
        sourceParts = ...
            unique( ...
                sourceParts( ...
                    strlength(sourceParts) > 0));
        evidenceCount(k) = ...
            numel(sourceParts);
        hasMotor = ...
            any(sourceParts == "MOTOR_PWM");
        hasIndependentEvidence = ...
            any(sourceParts == "ALTITUDE") || ...
            any(sourceParts == "GROUND_SPEED");
        multiEvidenceValid = ...
            evidenceCount(k) >= 2 && ...
            hasIndependentEvidence;
        motorOnlyValid = ...
            hasMotor && ...
            ~altitudeSourceAvailable && ...
            ~speedSourceAvailable && ...
            mergedDuration(k) >= ...
            F.minimumMotorOnlyDuration_s;
        keep(k) = ...
            mergedDuration(k) >= ...
            F.minimumFlightDuration_s && ...
            ( ...
                multiEvidenceValid || ...
                motorOnlyValid ...
            );
    end
    mergedStart = ...
        mergedStart(keep);
    mergedEnd = ...
        mergedEnd(keep);
    mergedDuration = ...
        mergedDuration(keep);
    mergedSources = ...
        mergedSources(keep);
    evidenceCount = ...
        evidenceCount(keep);
    if isempty(mergedStart)
        return;
    end
    Interval = ...
        (1:numel(mergedStart)).';
    StartTime_s = ...
        mergedStart;
    EndTime_s = ...
        mergedEnd;
    Duration_s = ...
        mergedDuration;
    EvidenceCount = ...
        evidenceCount;
    EvidenceSources = ...
        mergedSources;
    intervals = ...
        table( ...
            Interval, ...
            StartTime_s, ...
            EndTime_s, ...
            Duration_s, ...
            EvidenceCount, ...
            EvidenceSources);
    diagnostics.AcceptedIntervals = ...
        height(intervals);
    diagnostics.SelectionMethod = ...
        "GENERIC_MULTI_EVIDENCE_FALLBACK";
end
function tf = localHasFieldOrVariable(node,name)
    tf = ...
        false;
    try
        if isstruct(node)
            tf = ...
                isfield( ...
                    node, ...
                    name);
        elseif istable(node) || ...
                istimetable(node)
            tf = ...
                ismember( ...
                    name, ...
                    node.Properties.VariableNames);
        end
    catch
        tf = ...
            false;
    end
end
function [time_s,data] = localSanitizeScalarSeries( ...
    time_s, ...
    data)
    time_s = ...
        double(time_s(:));
    data = ...
        double(data(:));
    valid = ...
        isfinite(time_s) & ...
        isfinite(data);
    time_s = ...
        time_s(valid);
    data = ...
        data(valid);
    if isempty(time_s)
        return;
    end
    [time_s,order] = ...
        sort(time_s);
    data = ...
        data(order);
    [time_s,uniqueIndex] = ...
        unique( ...
            time_s, ...
            'last');
    data = ...
        data(uniqueIndex);
end
function baseline = localLowStateBaseline( ...
    data, ...
    lowFraction)
    data = ...
        double(data(:));
    data = ...
        data(isfinite(data));
    baseline = ...
        NaN;
    if isempty(data)
        return;
    end
    data = ...
        sort(data);
    lowFraction = ...
        min( ...
            max( ...
                double(lowFraction), ...
                0.05), ...
            0.50);
    nLow = ...
        max( ...
            1, ...
            round( ...
                lowFraction * ...
                numel(data)));
    baseline = ...
        median( ...
            data(1:nLow), ...
            'omitnan');
end
function merged = localMergeSimpleIntervals( ...
    intervals, ...
    mergeGap_s, ...
    minimumDuration_s)
    merged = ...
        table();
    if isempty(intervals)
        return;
    end
    intervals = ...
        sortrows( ...
            intervals, ...
            'StartTime_s');
    starts = ...
        zeros(0,1);
    ends = ...
        zeros(0,1);
    currentStart = ...
        intervals.StartTime_s(1);
    currentEnd = ...
        intervals.EndTime_s(1);
    for k = 2:height(intervals)
        nextStart = ...
            intervals.StartTime_s(k);
        nextEnd = ...
            intervals.EndTime_s(k);
        if nextStart <= ...
                currentEnd + ...
                mergeGap_s
            currentEnd = ...
                max( ...
                    currentEnd, ...
                    nextEnd);
        else
            starts(end+1,1) = ...
                currentStart; %#ok<AGROW>
            ends(end+1,1) = ...
                currentEnd; %#ok<AGROW>
            currentStart = ...
                nextStart;
            currentEnd = ...
                nextEnd;
        end
    end
    starts(end+1,1) = ...
        currentStart;
    ends(end+1,1) = ...
        currentEnd;
    durations = ...
        ends - ...
        starts;
    keep = ...
        durations >= ...
        minimumDuration_s;
    StartTime_s = ...
        starts(keep);
    EndTime_s = ...
        ends(keep);
    Duration_s = ...
        durations(keep);
    merged = ...
        table( ...
            StartTime_s, ...
            EndTime_s, ...
            Duration_s);
end
function totalOverlap_s = localTotalOverlapDuration( ...
    candidateStart_s, ...
    candidateEnd_s, ...
    intervals)
    totalOverlap_s = ...
        0;
    if isempty(intervals)
        return;
    end
    for k = 1:height(intervals)
        overlapStart = ...
            max( ...
                candidateStart_s, ...
                intervals.StartTime_s(k));
        overlapEnd = ...
            min( ...
                candidateEnd_s, ...
                intervals.EndTime_s(k));
        totalOverlap_s = ...
            totalOverlap_s + ...
            max( ...
                0, ...
                overlapEnd - ...
                overlapStart);
    end
end
function [intervals,diagnostics] = localDetectTelemetryWindow( ...
    REAL_DATA, ...
    F, ...
    logDuration_s)
    intervals = ...
        table();
    diagnostics = ...
        struct();
    diagnostics.Enabled = ...
        logical(F.enabled);
    diagnostics.MinimumSourceCount = ...
        double(F.minimumSourceCount);
    diagnostics.MinimumWindowDuration_s = ...
        double(F.minimumWindowDuration_s);
    diagnostics.ValidSourceCount = ...
        0;
    diagnostics.SourceIntervals = ...
        table();
    diagnostics.Accepted = ...
        false;
    diagnostics.SelectionMethod = ...
        "NONE";
    sourceNames = strings(0,1);
    sourceStarts = zeros(0,1);
    sourceEnds = zeros(0,1);
    [sourceNames,sourceStarts,sourceEnds] = ...
        localAppendTelemetrySource( ...
            sourceNames, ...
            sourceStarts, ...
            sourceEnds, ...
            REAL_DATA, ...
            {'State','Attitude'}, ...
            "ATTITUDE");
    [sourceNames,sourceStarts,sourceEnds] = ...
        localAppendTelemetrySource( ...
            sourceNames, ...
            sourceStarts, ...
            sourceEnds, ...
            REAL_DATA, ...
            {'State','GlobalPosition'}, ...
            "GLOBAL_POSITION");
    [sourceNames,sourceStarts,sourceEnds] = ...
        localAppendTelemetrySource( ...
            sourceNames, ...
            sourceStarts, ...
            sourceEnds, ...
            REAL_DATA, ...
            {'State','VelocityNED'}, ...
            "VELOCITY_NED");
    [sourceNames,sourceStarts,sourceEnds] = ...
        localAppendTelemetrySource( ...
            sourceNames, ...
            sourceStarts, ...
            sourceEnds, ...
            REAL_DATA, ...
            {'Navigation','VFR'}, ...
            "VFR");
    [sourceNames,sourceStarts,sourceEnds] = ...
        localAppendTelemetrySource( ...
            sourceNames, ...
            sourceStarts, ...
            sourceEnds, ...
            REAL_DATA, ...
            {'Actuator','PWM'}, ...
            "ACTUATOR_PWM");
    [sourceNames,sourceStarts,sourceEnds] = ...
        localAppendTelemetrySource( ...
            sourceNames, ...
            sourceStarts, ...
            sourceEnds, ...
            REAL_DATA, ...
            {'Sensor','IMU1'}, ...
            "IMU1");
    [sourceNames,sourceStarts,sourceEnds] = ...
        localAppendTelemetrySource( ...
            sourceNames, ...
            sourceStarts, ...
            sourceEnds, ...
            REAL_DATA, ...
            {'State','PositionNED'}, ...
            "POSITION_NED");
    if isempty(sourceNames)
        return;
    end
    sourceDurations = ...
        sourceEnds - ...
        sourceStarts;
    Source = ...
        sourceNames;
    StartTime_s = ...
        sourceStarts;
    EndTime_s = ...
        sourceEnds;
    Duration_s = ...
        sourceDurations;
    diagnostics.SourceIntervals = ...
        table( ...
            Source, ...
            StartTime_s, ...
            EndTime_s, ...
            Duration_s);
    diagnostics.ValidSourceCount = ...
        numel(sourceNames);
    if numel(sourceNames) < ...
            F.minimumSourceCount
        return;
    end
    commonStart = ...
        max(sourceStarts);
    commonEnd = ...
        min(sourceEnds);
    commonDuration = ...
        commonEnd - ...
        commonStart;
    selectedStart = ...
        NaN;
    selectedEnd = ...
        NaN;
    selectedSources = ...
        strings(0,1);
    if isfinite(commonStart) && ...
            isfinite(commonEnd) && ...
            commonDuration >= ...
            F.minimumWindowDuration_s
        selectedStart = ...
            commonStart;
        selectedEnd = ...
            commonEnd;
        selectedSources = ...
            sourceNames;
        diagnostics.SelectionMethod = ...
            "COMMON_SUPPORT_ALL_AVAILABLE_SOURCES";
    else
        bestDuration = ...
            -Inf;
        bestStart = ...
            NaN;
        bestEnd = ...
            NaN;
        bestPair = ...
            zeros(0,1);
        for i = 1:numel(sourceNames)
            for j = i+1:numel(sourceNames)
                pairStart = ...
                    max( ...
                        sourceStarts(i), ...
                        sourceStarts(j));
                pairEnd = ...
                    min( ...
                        sourceEnds(i), ...
                        sourceEnds(j));
                pairDuration = ...
                    pairEnd - ...
                    pairStart;
                if pairDuration > ...
                        bestDuration
                    bestDuration = ...
                        pairDuration;
                    bestStart = ...
                        pairStart;
                    bestEnd = ...
                        pairEnd;
                    bestPair = ...
                        [i;j];
                end
            end
        end
        if isfinite(bestDuration) && ...
                bestDuration >= ...
                F.minimumWindowDuration_s
            selectedStart = ...
                bestStart;
            selectedEnd = ...
                bestEnd;
            spansWindow = ...
                sourceStarts <= selectedStart & ...
                sourceEnds >= selectedEnd;
            selectedSources = ...
                sourceNames(spansWindow);
            if numel(selectedSources) < ...
                    F.minimumSourceCount
                selectedSources = ...
                    sourceNames(bestPair);
            end
            diagnostics.SelectionMethod = ...
                "LONGEST_PAIRWISE_COMMON_SUPPORT";
        end
    end
    if ~isfinite(selectedStart) || ...
            ~isfinite(selectedEnd)
        return;
    end
    selectedStart = ...
        max( ...
            0, ...
            selectedStart);
    if isfinite(logDuration_s) && ...
            logDuration_s > 0
        selectedEnd = ...
            min( ...
                logDuration_s, ...
                selectedEnd);
    end
    selectedDuration = ...
        selectedEnd - ...
        selectedStart;
    if selectedDuration < ...
            F.minimumWindowDuration_s
        return;
    end
    if numel(selectedSources) < ...
            F.minimumSourceCount
        return;
    end
    Interval = ...
        1;
    StartTime_s = ...
        selectedStart;
    EndTime_s = ...
        selectedEnd;
    Duration_s = ...
        selectedDuration;
    SourceCount = ...
        numel(selectedSources);
    Sources = ...
        strjoin( ...
            selectedSources, ...
            "+");
    intervals = ...
        table( ...
            Interval, ...
            StartTime_s, ...
            EndTime_s, ...
            Duration_s, ...
            SourceCount, ...
            Sources);
    diagnostics.Accepted = ...
        true;
    diagnostics.SelectedStartTime_s = ...
        selectedStart;
    diagnostics.SelectedEndTime_s = ...
        selectedEnd;
    diagnostics.SelectedDuration_s = ...
        selectedDuration;
    diagnostics.SelectedSourceCount = ...
        SourceCount;
    diagnostics.SelectedSources = ...
        Sources;
end
function [names,starts,ends] = localAppendTelemetrySource( ...
    names, ...
    starts, ...
    ends, ...
    REAL_DATA, ...
    pathParts, ...
    sourceName)
    node = ...
        REAL_DATA;
    for k = 1:numel(pathParts)
        fieldName = ...
            pathParts{k};
        if ~isstruct(node) || ...
                ~isfield(node,fieldName)
            return;
        end
        node = ...
            node.(fieldName);
    end
    timeVector = ...
        localExtractTimeVector(node);
    timeVector = ...
        double(timeVector(:));
    timeVector = ...
        timeVector( ...
            isfinite(timeVector));
    if numel(timeVector) < 2
        return;
    end
    t0 = ...
        min(timeVector);
    t1 = ...
        max(timeVector);
    if ~isfinite(t0) || ...
            ~isfinite(t1) || ...
            t1 <= t0
        return;
    end
    names(end+1,1) = ...
        string(sourceName);
    starts(end+1,1) = ...
        t0;
    ends(end+1,1) = ...
        t1;
end
function timeVector = localExtractTimeVector(node)
    timeVector = ...
        zeros(0,1);
    try
        if istimetable(node)
            rowTimes = ...
                node.Properties.RowTimes;
            if isduration(rowTimes)
                timeVector = ...
                    seconds(rowTimes);
            elseif isdatetime(rowTimes)
                timeVector = ...
                    seconds( ...
                        rowTimes - ...
                        rowTimes(1));
            else
                timeVector = ...
                    double(rowTimes);
            end
            return;
        end
        if istable(node)
            if ismember( ...
                    'Time_s', ...
                    node.Properties.VariableNames)
                timeVector = ...
                    double(node.Time_s(:));
            end
            return;
        end
        if isstruct(node) && ...
                isfield(node,'Time_s')
            timeVector = ...
                double(node.Time_s(:));
        end
    catch
        timeVector = ...
            zeros(0,1);
    end
end
function baseline = localInitialBaseline( ...
    time_s, ...
    data, ...
    baselineWindow_s)
    time_s = ...
        double(time_s(:));
    data = ...
        double(data(:));
    valid = ...
        isfinite(time_s) & ...
        isfinite(data);
    time_s = ...
        time_s(valid);
    data = ...
        data(valid);
    baseline = ...
        NaN;
    if isempty(data)
        return;
    end
    t0 = ...
        time_s(1);
    baselineMask = ...
        time_s <= ...
        t0 + ...
        baselineWindow_s;
    baselineData = ...
        data(baselineMask);
    if isempty(baselineData)
        baselineData = ...
            data( ...
                1:min( ...
                    numel(data), ...
                    10));
    end
    baseline = ...
        median( ...
            baselineData, ...
            'omitnan');
    if ~isfinite(baseline)
        baseline = ...
            median( ...
                data, ...
                'omitnan');
    end
end
