if ~exist('REAL_RAW','var') || ...
        ~isstruct(REAL_RAW)
    error( ...
        'RealFlight:RawSignalsUnavailable', ...
        ['REAL_RAW was not found.\n\n', ...
         'Run:\n\n', ...
         '    initialize_real_flight\n', ...
         '    import_tlog\n', ...
         '    extract_tlog_signals\n\n', ...
         'before normalize_real_flight_data.']);
end
if ~exist('REAL_IMPORT','var') || ...
        ~isstruct(REAL_IMPORT)
    error( ...
        'RealFlight:ImportMetadataUnavailable', ...
        'REAL_IMPORT was not found.');
end
REAL_DATA = ...
    struct();
REAL_DATA.Metadata = ...
    struct();
REAL_DATA.Metadata.SchemaVersion = ...
    "1.0";
REAL_DATA.Metadata.Source = ...
    "QGroundControl MAVLink TLOG";
REAL_DATA.Metadata.FileName = ...
    REAL_IMPORT.Source.FileName;
REAL_DATA.Metadata.FilePath = ...
    REAL_IMPORT.Source.FilePath;
REAL_DATA.Metadata.NavigationFrame = ...
    "NED";
REAL_DATA.Metadata.BodyFrame = ...
    "FRD";
REAL_DATA.Metadata.LogStartTime = ...
    REAL_IMPORT.Time.Start;
REAL_DATA.Metadata.LogEndTime = ...
    REAL_IMPORT.Time.End;
REAL_DATA.Metadata.LogDuration_s = ...
    REAL_IMPORT.Time.Duration_s;
REAL_DATA.State = ...
    struct();
REAL_DATA.Sensor = ...
    struct();
REAL_DATA.Actuator = ...
    struct();
REAL_DATA.Operator = ...
    struct();
REAL_DATA.Power = ...
    struct();
REAL_DATA.Status = ...
    struct();
REAL_DATA.Navigation = ...
    struct();
REAL_DATA.Mission = ...
    struct();
REAL_DATA.Environment = ...
    struct();
Signal = strings(0,1);
Group = strings(0,1);
Status = strings(0,1);
SourceMessage = strings(0,1);
Units = strings(0,1);
Notes = strings(0,1);
if isfield(REAL_RAW.Autopilot,'Attitude')
    TT = ...
        REAL_RAW.Autopilot.Attitude;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    yawRaw_rad = ...
        double(TT.yaw);
    yawWrapped_rad = ...
        mod( ...
            yawRaw_rad + pi, ...
            2*pi) - pi;
    REAL_DATA.State.Attitude = ...
        table( ...
            t, ...
            double(TT.roll), ...
            double(TT.pitch), ...
            yawWrapped_rad, ...
            'VariableNames', { ...
                'Time_s', ...
                'Roll_rad', ...
                'Pitch_rad', ...
                'Yaw_rad'});
    REAL_DATA.State.AngularRate = ...
        table( ...
            t, ...
            double(TT.rollspeed), ...
            double(TT.pitchspeed), ...
            double(TT.yawspeed), ...
            'VariableNames', { ...
                'Time_s', ...
                'P_rad_s', ...
                'Q_rad_s', ...
                'R_rad_s'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "Attitude", ...
            "State", ...
            "DIRECT", ...
            "ATTITUDE", ...
            "rad", ...
            "MAVLink ATTITUDE roll/pitch; yaw wrapped to [-pi,pi). Raw yaw remains preserved in REAL_RAW.");
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "AngularRate", ...
            "State", ...
            "DIRECT", ...
            "ATTITUDE", ...
            "rad/s", ...
            "Body roll/pitch/yaw rates.");
end
if isfield(REAL_RAW.Autopilot,'GlobalPositionInt')
    TT = ...
        REAL_RAW.Autopilot.GlobalPositionInt;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    latitude_deg = ...
        double(TT.lat) * ...
        1.0e-7;
    longitude_deg = ...
        double(TT.lon) * ...
        1.0e-7;
    altitudeMSL_m = ...
        double(TT.alt) * ...
        1.0e-3;
    relativeAltitude_m = ...
        double(TT.relative_alt) * ...
        1.0e-3;
    velocityNorth_m_s = ...
        double(TT.vx) * ...
        1.0e-2;
    velocityEast_m_s = ...
        double(TT.vy) * ...
        1.0e-2;
    velocityDown_m_s = ...
        double(TT.vz) * ...
        1.0e-2;
    heading_deg = ...
        double(TT.hdg) * ...
        1.0e-2;
    heading_deg( ...
        double(TT.hdg) >= 65535) = ...
        NaN;
    REAL_DATA.State.GlobalPosition = ...
        table( ...
            t, ...
            latitude_deg, ...
            longitude_deg, ...
            altitudeMSL_m, ...
            relativeAltitude_m, ...
            heading_deg, ...
            'VariableNames', { ...
                'Time_s', ...
                'Latitude_deg', ...
                'Longitude_deg', ...
                'AltitudeMSL_m', ...
                'RelativeAltitude_m', ...
                'Heading_deg'});
    REAL_DATA.State.VelocityNED = ...
        table( ...
            t, ...
            velocityNorth_m_s, ...
            velocityEast_m_s, ...
            velocityDown_m_s, ...
            'VariableNames', { ...
                'Time_s', ...
                'North_m_s', ...
                'East_m_s', ...
                'Down_m_s'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "GlobalPosition", ...
            "State", ...
            "DIRECT", ...
            "GLOBAL_POSITION_INT", ...
            "deg,m", ...
            "Latitude/longitude and altitude from autopilot global state.");
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "VelocityNED", ...
            "State", ...
            "DIRECT", ...
            "GLOBAL_POSITION_INT", ...
            "m/s", ...
            "MAVLink vx/vy/vz converted from cm/s to NED m/s.");
end
if isfield(REAL_RAW.Autopilot,'GPSRawInt')
    TT = ...
        REAL_RAW.Autopilot.GPSRawInt;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    latitude_deg = ...
        double(TT.lat) * 1.0e-7;
    longitude_deg = ...
        double(TT.lon) * 1.0e-7;
    altitudeMSL_m = ...
        double(TT.alt) * 1.0e-3;
    altitudeEllipsoid_m = ...
        double(TT.alt_ellipsoid) * 1.0e-3;
    groundSpeed_m_s = ...
        double(TT.vel) * 1.0e-2;
    course_deg = ...
        double(TT.cog) * 1.0e-2;
    horizontalAccuracy_m = ...
        double(TT.h_acc) * 1.0e-3;
    verticalAccuracy_m = ...
        double(TT.v_acc) * 1.0e-3;
    velocityAccuracy_m_s = ...
        double(TT.vel_acc) * 1.0e-3;
    headingAccuracy_deg = ...
        double(TT.hdg_acc) * 1.0e-5;
    gpsYaw_deg = ...
        double(TT.yaw) * 1.0e-2;
    gpsYaw_deg(double(TT.yaw) == 0) = ...
        NaN;
    REAL_DATA.Sensor.GPS = ...
        table( ...
            t, ...
            latitude_deg, ...
            longitude_deg, ...
            altitudeMSL_m, ...
            altitudeEllipsoid_m, ...
            groundSpeed_m_s, ...
            course_deg, ...
            double(TT.fix_type), ...
            double(TT.satellites_visible), ...
            horizontalAccuracy_m, ...
            verticalAccuracy_m, ...
            velocityAccuracy_m_s, ...
            headingAccuracy_deg, ...
            gpsYaw_deg, ...
            'VariableNames', { ...
                'Time_s', ...
                'Latitude_deg', ...
                'Longitude_deg', ...
                'AltitudeMSL_m', ...
                'AltitudeEllipsoid_m', ...
                'GroundSpeed_m_s', ...
                'Course_deg', ...
                'FixType', ...
                'SatellitesVisible', ...
                'HorizontalAccuracy_m', ...
                'VerticalAccuracy_m', ...
                'VelocityAccuracy_m_s', ...
                'HeadingAccuracy_deg', ...
                'Yaw_deg'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "GPS", ...
            "Sensor", ...
            "DIRECT", ...
            "GPS_RAW_INT", ...
            "deg,m,m/s", ...
            "Raw GNSS solution and quality indicators.");
end
HOME_AVAILABLE = ...
    false;
homeLLA = ...
    [NaN NaN NaN];
if isfield(REAL_DATA.State,'GlobalPosition')
    GP = ...
        REAL_DATA.State.GlobalPosition;
    validGlobal = ...
        isfinite(GP.Latitude_deg) & ...
        isfinite(GP.Longitude_deg) & ...
        isfinite(GP.AltitudeMSL_m) & ...
        abs(GP.Latitude_deg) > 1e-8 & ...
        abs(GP.Longitude_deg) > 1e-8;
    validIndices = ...
        find(validGlobal);
    if ~isempty(validIndices)
        useIndices = ...
            validIndices( ...
                1:min(20,numel(validIndices)));
        homeLLA = [ ...
            median(GP.Latitude_deg(useIndices),'omitnan'), ...
            median(GP.Longitude_deg(useIndices),'omitnan'), ...
            median(GP.AltitudeMSL_m(useIndices),'omitnan')];
        HOME_AVAILABLE = ...
            all(isfinite(homeLLA));
    end
end
if ~HOME_AVAILABLE && ...
        isfield(REAL_DATA.Sensor,'GPS')
    GPS = ...
        REAL_DATA.Sensor.GPS;
    validGPS = ...
        GPS.FixType >= 3 & ...
        isfinite(GPS.Latitude_deg) & ...
        isfinite(GPS.Longitude_deg) & ...
        isfinite(GPS.AltitudeMSL_m) & ...
        abs(GPS.Latitude_deg) > 1e-8 & ...
        abs(GPS.Longitude_deg) > 1e-8;
    validIndices = ...
        find(validGPS);
    if ~isempty(validIndices)
        useIndices = ...
            validIndices( ...
                1:min(20,numel(validIndices)));
        homeLLA = [ ...
            median(GPS.Latitude_deg(useIndices),'omitnan'), ...
            median(GPS.Longitude_deg(useIndices),'omitnan'), ...
            median(GPS.AltitudeMSL_m(useIndices),'omitnan')];
        HOME_AVAILABLE = ...
            all(isfinite(homeLLA));
    end
end
REAL_DATA.Metadata.HomeAvailable = ...
    HOME_AVAILABLE;
REAL_DATA.Metadata.HomeLLA_deg_m = ...
    homeLLA;
if HOME_AVAILABLE && ...
        isfield(REAL_DATA.State,'GlobalPosition')
    GP = ...
        REAL_DATA.State.GlobalPosition;
    lla = [ ...
        GP.Latitude_deg, ...
        GP.Longitude_deg, ...
        GP.AltitudeMSL_m];
    PositionNED = ...
        geodeticToLocalNED( ...
            lla, ...
            homeLLA);
    REAL_DATA.State.PositionNED = ...
        table( ...
            GP.Time_s, ...
            PositionNED(:,1), ...
            PositionNED(:,2), ...
            PositionNED(:,3), ...
            'VariableNames', { ...
                'Time_s', ...
                'North_m', ...
                'East_m', ...
                'Down_m'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "PositionNED", ...
            "State", ...
            "DERIVED", ...
            "GLOBAL_POSITION_INT", ...
            "m", ...
            "WGS84 LLA converted to local NED relative to inferred HOME.");
else
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "PositionNED", ...
            "State", ...
            "NOT_AVAILABLE", ...
            "GLOBAL_POSITION_INT / GPS_RAW_INT", ...
            "m", ...
            "No valid geographic HOME could be established.");
end
if isfield(REAL_RAW.Autopilot,'VFRHUD')
    TT = ...
        REAL_RAW.Autopilot.VFRHUD;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    REAL_DATA.Navigation.VFR = ...
        table( ...
            t, ...
            double(TT.airspeed), ...
            double(TT.groundspeed), ...
            double(TT.alt), ...
            double(TT.climb), ...
            double(TT.heading), ...
            double(TT.throttle), ...
            'VariableNames', { ...
                'Time_s', ...
                'Airspeed_m_s', ...
                'GroundSpeed_m_s', ...
                'AltitudeMSL_m', ...
                'ClimbRateUp_m_s', ...
                'Heading_deg', ...
                'Throttle_percent'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "VFR", ...
            "Navigation", ...
            "DIRECT", ...
            "VFR_HUD", ...
            "m/s,m,deg,%", ...
            "HUD navigation quantities.");
end
if isfield(REAL_RAW.Autopilot,'RawIMU')
    TT = ...
        REAL_RAW.Autopilot.RawIMU;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    g0 = ...
        9.80665;
    accelScale = ...
        g0 / 1000;
    gyroScale = ...
        1.0e-3;
    magScale_uT = ...
        0.1;
    REAL_DATA.Sensor.IMU1 = ...
        table( ...
            t, ...
            double(TT.xacc)*accelScale, ...
            double(TT.yacc)*accelScale, ...
            double(TT.zacc)*accelScale, ...
            double(TT.xgyro)*gyroScale, ...
            double(TT.ygyro)*gyroScale, ...
            double(TT.zgyro)*gyroScale, ...
            double(TT.xmag)*magScale_uT, ...
            double(TT.ymag)*magScale_uT, ...
            double(TT.zmag)*magScale_uT, ...
            double(TT.temperature)*0.01, ...
            'VariableNames', { ...
                'Time_s', ...
                'AccelX_m_s2', ...
                'AccelY_m_s2', ...
                'AccelZ_m_s2', ...
                'GyroX_rad_s', ...
                'GyroY_rad_s', ...
                'GyroZ_rad_s', ...
                'MagX_uT', ...
                'MagY_uT', ...
                'MagZ_uT', ...
                'Temperature_C'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "IMU1", ...
            "Sensor", ...
            "DIRECT", ...
            "RAW_IMU", ...
            "m/s^2,rad/s,uT", ...
            "Body-frame IMU converted to SI engineering units.");
end
scaledIMUDefinitions = { ...
    'ScaledIMU2', 'IMU2', 'SCALED_IMU2'; ...
    'ScaledIMU3', 'IMU3', 'SCALED_IMU3'};
for imuIndex = 1:size(scaledIMUDefinitions,1)
    sourceField = ...
        scaledIMUDefinitions{imuIndex,1};
    destinationField = ...
        scaledIMUDefinitions{imuIndex,2};
    sourceMessageName = ...
        scaledIMUDefinitions{imuIndex,3};
    if ~isfield(REAL_RAW.Autopilot,sourceField)
        continue;
    end
    TT = ...
        REAL_RAW.Autopilot.(sourceField);
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    REAL_DATA.Sensor.(destinationField) = ...
        table( ...
            t, ...
            double(TT.xacc)*(9.80665/1000), ...
            double(TT.yacc)*(9.80665/1000), ...
            double(TT.zacc)*(9.80665/1000), ...
            double(TT.xgyro)*1.0e-3, ...
            double(TT.ygyro)*1.0e-3, ...
            double(TT.zgyro)*1.0e-3, ...
            double(TT.xmag)*0.1, ...
            double(TT.ymag)*0.1, ...
            double(TT.zmag)*0.1, ...
            double(TT.temperature)*0.01, ...
            'VariableNames', { ...
                'Time_s', ...
                'AccelX_m_s2', ...
                'AccelY_m_s2', ...
                'AccelZ_m_s2', ...
                'GyroX_rad_s', ...
                'GyroY_rad_s', ...
                'GyroZ_rad_s', ...
                'MagX_uT', ...
                'MagY_uT', ...
                'MagZ_uT', ...
                'Temperature_C'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            string(destinationField), ...
            "Sensor", ...
            "DIRECT", ...
            string(sourceMessageName), ...
            "m/s^2,rad/s,uT", ...
            "Additional onboard IMU.");
end
if isfield(REAL_RAW.Autopilot,'ScaledPressure')
    TT = ...
        REAL_RAW.Autopilot.ScaledPressure;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    REAL_DATA.Sensor.Pressure = ...
        table( ...
            t, ...
            double(TT.press_abs)*100, ...
            double(TT.press_diff)*100, ...
            double(TT.temperature)*0.01, ...
            'VariableNames', { ...
                'Time_s', ...
                'AbsolutePressure_Pa', ...
                'DifferentialPressure_Pa', ...
                'Temperature_C'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "Pressure", ...
            "Sensor", ...
            "DIRECT", ...
            "SCALED_PRESSURE", ...
            "Pa,C", ...
            "Pressure converted from hPa to Pa.");
end
if isfield(REAL_RAW.Autopilot,'ServoOutputRaw')
    TT = ...
        REAL_RAW.Autopilot.ServoOutputRaw;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    PWM = ...
        NaN(height(TT),16);
    for channelIndex = 1:16
        fieldName = ...
            sprintf( ...
                'servo%d_raw', ...
                channelIndex);
        if ismember( ...
                fieldName, ...
                TT.Properties.VariableNames)
            PWM(:,channelIndex) = ...
                double(TT.(fieldName));
        end
    end
    actuatorTable = ...
        array2table( ...
            PWM, ...
            'VariableNames', ...
            compose('PWM%d_us',1:16));
    actuatorTable = ...
        addvars( ...
            actuatorTable, ...
            t, ...
            'Before',1, ...
            'NewVariableNames','Time_s');
    REAL_DATA.Actuator.PWM = ...
        actuatorTable;
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "ActuatorPWM", ...
            "Actuator", ...
            "DIRECT", ...
            "SERVO_OUTPUT_RAW", ...
            "us", ...
            "Raw actuator outputs; not converted to rotor speed.");
end
if isfield(REAL_RAW.Autopilot,'RCChannels')
    TT = ...
        REAL_RAW.Autopilot.RCChannels;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    RC = ...
        NaN(height(TT),18);
    for channelIndex = 1:18
        fieldName = ...
            sprintf( ...
                'chan%d_raw', ...
                channelIndex);
        if ismember( ...
                fieldName, ...
                TT.Properties.VariableNames)
            RC(:,channelIndex) = ...
                double(TT.(fieldName));
        end
    end
    rcTable = ...
        array2table( ...
            RC, ...
            'VariableNames', ...
            compose('Channel%d_us',1:18));
    rcTable = ...
        addvars( ...
            rcTable, ...
            t, ...
            double(TT.rssi), ...
            'Before',1, ...
            'NewVariableNames',{ ...
                'Time_s', ...
                'RSSI_raw'});
    REAL_DATA.Operator.RC = ...
        rcTable;
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "RCChannels", ...
            "Operator", ...
            "DIRECT", ...
            "RC_CHANNELS", ...
            "us", ...
            "Received RC channel PWM values.");
end
if isfield(REAL_RAW.GCS,'ManualControl')
    TT = ...
        REAL_RAW.GCS.ManualControl;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    REAL_DATA.Operator.ManualControl = ...
        table( ...
            t, ...
            double(TT.x), ...
            double(TT.y), ...
            double(TT.z), ...
            double(TT.r), ...
            double(TT.buttons), ...
            'VariableNames', { ...
                'Time_s', ...
                'X_raw', ...
                'Y_raw', ...
                'Z_raw', ...
                'R_raw', ...
                'Buttons'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "ManualControl", ...
            "Operator", ...
            "DIRECT", ...
            "MANUAL_CONTROL", ...
            "raw", ...
            "QGroundControl MANUAL_CONTROL commands retained in native command scale.");
end
if isfield(REAL_RAW.Autopilot,'BatteryStatus')
    TT = ...
        REAL_RAW.Autopilot.BatteryStatus;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    current_A = ...
        double(TT.current_battery) * ...
        0.01;
    current_A(double(TT.current_battery) == -1) = ...
        NaN;
    consumed_mAh = ...
        double(TT.current_consumed);
    consumed_mAh(consumed_mAh < 0) = ...
        NaN;
    batteryRemaining_percent = ...
        double(TT.battery_remaining);
    batteryRemaining_percent( ...
        batteryRemaining_percent < 0) = ...
        NaN;
    packVoltage_V = ...
        batteryPackVoltageFromMAVLink( ...
            TT.voltages);
    REAL_DATA.Power.Battery = ...
        table( ...
            t, ...
            packVoltage_V, ...
            current_A, ...
            consumed_mAh, ...
            batteryRemaining_percent, ...
            'VariableNames', { ...
                'Time_s', ...
                'Voltage_V', ...
                'Current_A', ...
                'ConsumedCapacity_mAh', ...
                'Remaining_percent'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "Battery", ...
            "Power", ...
            "DIRECT", ...
            "BATTERY_STATUS", ...
            "V,A,mAh,%", ...
            "Battery pack quantities converted from MAVLink units.");
end
if isfield(REAL_RAW.Autopilot,'SystemStatus')
    TT = ...
        REAL_RAW.Autopilot.SystemStatus;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    current_A = ...
        double(TT.current_battery)*0.01;
    current_A(double(TT.current_battery) == -1) = ...
        NaN;
    REAL_DATA.Power.System = ...
        table( ...
            t, ...
            double(TT.voltage_battery)*1.0e-3, ...
            current_A, ...
            double(TT.battery_remaining), ...
            double(TT.load)*0.1, ...
            'VariableNames', { ...
                'Time_s', ...
                'Voltage_V', ...
                'Current_A', ...
                'Remaining_percent', ...
                'AutopilotLoad_percent'});
end
if isfield(REAL_RAW.Autopilot,'PowerStatus')
    TT = ...
        REAL_RAW.Autopilot.PowerStatus;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    REAL_DATA.Power.Electronics = ...
        table( ...
            t, ...
            double(TT.Vcc)*1.0e-3, ...
            double(TT.Vservo)*1.0e-3, ...
            double(TT.flags), ...
            'VariableNames', { ...
                'Time_s', ...
                'Vcc_V', ...
                'Vservo_V', ...
                'Flags'});
end
if isfield(REAL_RAW.Autopilot,'Vibration')
    TT = ...
        REAL_RAW.Autopilot.Vibration;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    REAL_DATA.Sensor.Vibration = ...
        table( ...
            t, ...
            double(TT.vibration_x), ...
            double(TT.vibration_y), ...
            double(TT.vibration_z), ...
            double(TT.clipping_0), ...
            double(TT.clipping_1), ...
            double(TT.clipping_2), ...
            'VariableNames', { ...
                'Time_s', ...
                'X_m_s2', ...
                'Y_m_s2', ...
                'Z_m_s2', ...
                'Clipping0', ...
                'Clipping1', ...
                'Clipping2'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "Vibration", ...
            "Sensor", ...
            "DIRECT", ...
            "VIBRATION", ...
            "m/s^2", ...
            "Autopilot vibration metrics.");
end
if isfield(REAL_RAW.Autopilot,'Heartbeat')
    TT = ...
        REAL_RAW.Autopilot.Heartbeat;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    baseMode = ...
        double(TT.base_mode);
    armed = ...
        bitand( ...
            uint8(baseMode), ...
            uint8(128)) ~= 0;
    REAL_DATA.Status.Heartbeat = ...
        table( ...
            t, ...
            double(TT.custom_mode), ...
            baseMode, ...
            double(TT.system_status), ...
            armed, ...
            'VariableNames', { ...
                'Time_s', ...
                'CustomMode', ...
                'BaseMode', ...
                'SystemStatus', ...
                'Armed'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "Armed", ...
            "Status", ...
            "DERIVED", ...
            "HEARTBEAT", ...
            "logical", ...
            "Decoded from MAV_MODE_FLAG_SAFETY_ARMED.");
end
if isfield(REAL_RAW.Autopilot,'ExtendedSystemState')
    TT = ...
        REAL_RAW.Autopilot.ExtendedSystemState;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    landedState = ...
        double(TT.landed_state);
    REAL_DATA.Status.LandedState = ...
        table( ...
            t, ...
            landedState, ...
            landedState == 1, ...
            landedState == 2, ...
            landedState == 3, ...
            landedState == 4, ...
            'VariableNames', { ...
                'Time_s', ...
                'LandedState', ...
                'OnGround', ...
                'InAir', ...
                'TakingOff', ...
                'Landing'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "LandedState", ...
            "Status", ...
            "DIRECT", ...
            "EXTENDED_SYS_STATE", ...
            "enum", ...
            "MAVLink landed-state enumeration.");
end
if isfield(REAL_RAW.Autopilot,'NavControllerOutput')
    TT = ...
        REAL_RAW.Autopilot.NavControllerOutput;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    REAL_DATA.Navigation.Controller = ...
        table( ...
            t, ...
            deg2rad(double(TT.nav_roll)), ...
            deg2rad(double(TT.nav_pitch)), ...
            double(TT.alt_error), ...
            double(TT.aspd_error), ...
            double(TT.xtrack_error), ...
            double(TT.nav_bearing), ...
            double(TT.target_bearing), ...
            double(TT.wp_dist), ...
            'VariableNames', { ...
                'Time_s', ...
                'NavRollCommand_rad', ...
                'NavPitchCommand_rad', ...
                'AltitudeError_m', ...
                'AirspeedError_m_s', ...
                'CrossTrackError_m', ...
                'NavigationBearing_deg', ...
                'TargetBearing_deg', ...
                'WaypointDistance_m'});
    [Signal,Group,Status,SourceMessage,Units,Notes] = ...
        addAvailability( ...
            Signal,Group,Status,SourceMessage,Units,Notes, ...
            "NavigationController", ...
            "Controller", ...
            "DIRECT", ...
            "NAV_CONTROLLER_OUTPUT", ...
            "rad,m,m/s,deg", ...
            "Navigation-level controller outputs available in the TLOG.");
end
if isfield(REAL_RAW.Autopilot,'MissionCurrent')
    TT = ...
        REAL_RAW.Autopilot.MissionCurrent;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    REAL_DATA.Mission.Current = ...
        table( ...
            t, ...
            double(TT.seq), ...
            'VariableNames', { ...
                'Time_s', ...
                'Sequence'});
end
if isfield(REAL_RAW.Autopilot,'TerrainReport')
    TT = ...
        REAL_RAW.Autopilot.TerrainReport;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    REAL_DATA.Environment.Terrain = ...
        table( ...
            t, ...
            double(TT.lat)*1.0e-7, ...
            double(TT.lon)*1.0e-7, ...
            double(TT.terrain_height), ...
            double(TT.current_height), ...
            double(TT.spacing), ...
            'VariableNames', { ...
                'Time_s', ...
                'Latitude_deg', ...
                'Longitude_deg', ...
                'TerrainHeight_m', ...
                'CurrentHeight_m', ...
                'Spacing_m'});
end
if isfield(REAL_RAW.Autopilot,'StatusText')
    TT = ...
        REAL_RAW.Autopilot.StatusText;
    t = ...
        realFlightRelativeTime( ...
            TT, ...
            REAL_IMPORT.Time.Start);
    REAL_DATA.Status.Messages = ...
        table( ...
            t, ...
            double(TT.severity), ...
            string(TT.text), ...
            'VariableNames', { ...
                'Time_s', ...
                'Severity', ...
                'Text'});
end
REAL_DATA_AVAILABILITY = ...
    table( ...
        Signal, ...
        Group, ...
        Status, ...
        SourceMessage, ...
        Units, ...
        Notes);
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' REAL FLIGHT DATA NORMALIZATION COMPLETE\n');
fprintf('==============================================================\n\n');
fprintf( ...
    'Navigation frame:       NED\n');
fprintf( ...
    'Body frame:             FRD\n');
fprintf( ...
    'Geographic HOME valid:  %s\n', ...
    string(HOME_AVAILABLE));
if HOME_AVAILABLE
    fprintf( ...
        'HOME LLA:              [%.8f %.8f %.3f]\n', ...
        homeLLA(1), ...
        homeLLA(2), ...
        homeLLA(3));
else
    fprintf( ...
        ['HOME LLA:              NOT AVAILABLE\n', ...
         'Local NED position cannot be generated for this log.\n']);
end
fprintf('\n');
fprintf('Normalized / derived signal availability:\n\n');
disp(REAL_DATA_AVAILABILITY);
fprintf('\n');
fprintf( ...
    ['REAL_DATA now contains engineering-unit telemetry while preserving\n', ...
     'the native sample timing of every MAVLink signal.\n']);
fprintf('==============================================================\n');
fprintf('\n');
clear TT ...
      t ...
      yawRaw_rad ...
      yawWrapped_rad ...
      GP ...
      GPS ...
      latitude_deg ...
      longitude_deg ...
      altitudeMSL_m ...
      altitudeEllipsoid_m ...
      relativeAltitude_m ...
      velocityNorth_m_s ...
      velocityEast_m_s ...
      velocityDown_m_s ...
      heading_deg ...
      groundSpeed_m_s ...
      course_deg ...
      horizontalAccuracy_m ...
      verticalAccuracy_m ...
      velocityAccuracy_m_s ...
      headingAccuracy_deg ...
      gpsYaw_deg ...
      HOME_AVAILABLE ...
      homeLLA ...
      validGlobal ...
      validGPS ...
      validIndices ...
      useIndices ...
      lla ...
      PositionNED ...
      g0 ...
      accelScale ...
      gyroScale ...
      magScale_uT ...
      scaledIMUDefinitions ...
      imuIndex ...
      sourceField ...
      destinationField ...
      sourceMessageName ...
      PWM ...
      RC ...
      actuatorTable ...
      rcTable ...
      channelIndex ...
      fieldName ...
      current_A ...
      consumed_mAh ...
      batteryRemaining_percent ...
      packVoltage_V ...
      baseMode ...
      armed ...
      landedState;
function t = realFlightRelativeTime(TT, logStart)
    rowTimes = ...
        TT.Properties.RowTimes;
    if isempty(rowTimes)
        error( ...
            'RealFlight:MissingRowTimes', ...
            'MAVLink timetable has no row times.');
    end
    if isdatetime(rowTimes)
        t = ...
            seconds( ...
                rowTimes - logStart);
    elseif isduration(rowTimes)
        t = ...
            seconds(rowTimes);
    elseif isnumeric(rowTimes)
        t = ...
            double(rowTimes(:));
    else
        error( ...
            'RealFlight:UnsupportedRowTimeType', ...
            'Unsupported MAVLink timetable row-time type.');
    end
    t = ...
        double(t(:));
end
function [Signal,Group,Status,SourceMessage,Units,Notes] = ...
    addAvailability( ...
        Signal,Group,Status,SourceMessage,Units,Notes, ...
        signalName,groupName,statusName,messageName,unitName,noteText)
    Signal(end+1,1) = ...
        string(signalName);
    Group(end+1,1) = ...
        string(groupName);
    Status(end+1,1) = ...
        string(statusName);
    SourceMessage(end+1,1) = ...
        string(messageName);
    Units(end+1,1) = ...
        string(unitName);
    Notes(end+1,1) = ...
        string(noteText);
end
function packVoltage_V = batteryPackVoltageFromMAVLink(voltageData)
    voltageData = ...
        double(voltageData);
    numberOfSamples = ...
        size(voltageData,1);
    packVoltage_V = ...
        NaN(numberOfSamples,1);
    for k = 1:numberOfSamples
        row = ...
            voltageData(k,:);
        valid = ...
            isfinite(row) & ...
            row > 0 & ...
            row < 65535;
        if any(valid)
            packVoltage_V(k) = ...
                sum(row(valid)) * ...
                1.0e-3;
        end
    end
end
function ned = geodeticToLocalNED(lla, homeLLA)
    a = ...
        6378137.0;
    f = ...
        1 / 298.257223563;
    e2 = ...
        f * (2 - f);
    xyz = ...
        geodeticToECEFLocal( ...
            lla(:,1), ...
            lla(:,2), ...
            lla(:,3), ...
            a, ...
            e2);
    xyz0 = ...
        geodeticToECEFLocal( ...
            homeLLA(1), ...
            homeLLA(2), ...
            homeLLA(3), ...
            a, ...
            e2);
    delta = ...
        xyz - xyz0;
    lat0 = ...
        deg2rad(homeLLA(1));
    lon0 = ...
        deg2rad(homeLLA(2));
    R = [ ...
        -sin(lat0)*cos(lon0), ...
        -sin(lat0)*sin(lon0), ...
         cos(lat0); ...
        -sin(lon0), ...
         cos(lon0), ...
         0; ...
        -cos(lat0)*cos(lon0), ...
        -cos(lat0)*sin(lon0), ...
        -sin(lat0)];
    ned = ...
        (R * delta.').';
end
function xyz = geodeticToECEFLocal( ...
    latitude_deg,longitude_deg,altitude_m,a,e2)
    latitude_rad = ...
        deg2rad(latitude_deg);
    longitude_rad = ...
        deg2rad(longitude_deg);
    sinLat = ...
        sin(latitude_rad);
    cosLat = ...
        cos(latitude_rad);
    N = ...
        a ./ ...
        sqrt( ...
            1 - ...
            e2 .* ...
            sinLat.^2);
    X = ...
        (N + altitude_m) .* ...
        cosLat .* ...
        cos(longitude_rad);
    Y = ...
        (N + altitude_m) .* ...
        cosLat .* ...
        sin(longitude_rad);
    Z = ...
        (N .* (1-e2) + altitude_m) .* ...
        sinLat;
    xyz = ...
        [X Y Z];
end
