requiredVariables = { ...
    'REAL_MOTOR_PWM_DATA', ...
    'REAL_ACTUATION_RESULTS', ...
    'REAL_ACTUATOR_CONFIG', ...
    'REAL_FIGURES_FOLDER', ...
    'REAL_TABLES_FOLDER', ...
    'REAL_EXPERIMENT_DATA_FILE', ...
    'REAL_DATA_AVAILABILITY'};
for k = 1:numel(requiredVariables)
    if ~exist(requiredVariables{k},'var')
        error( ...
            'RealFlight:MissingRequiredVariable', ...
            ['Required variable "%s" was not found.\n\n', ...
             'Run the previous real-flight processing scripts first.'], ...
            requiredVariables{k});
    end
end
t = ...
    double( ...
        REAL_MOTOR_PWM_DATA.FlightTime_s);
U = [ ...
    double(REAL_MOTOR_PWM_DATA.Motor1_Normalized), ...
    double(REAL_MOTOR_PWM_DATA.Motor2_Normalized), ...
    double(REAL_MOTOR_PWM_DATA.Motor3_Normalized), ...
    double(REAL_MOTOR_PWM_DATA.Motor4_Normalized)];
validRows = ...
    isfinite(t) & ...
    all(isfinite(U),2);
t = ...
    t(validRows);
U = ...
    U(validRows,:);
if numel(t) < 2
    error( ...
        'RealFlight:InsufficientMotorData', ...
        ['Insufficient valid motor-command data exist for ', ...
         'control-axis reconstruction.']);
end
[t,order] = ...
    sort(t);
U = ...
    U(order,:);
u1 = ...
    U(:,1);
u2 = ...
    U(:,2);
u3 = ...
    U(:,3);
u4 = ...
    U(:,4);
thrustAxisProxy = ...
    ( ...
        u1 + ...
        u2 + ...
        u3 + ...
        u4 ...
    ) / 4;
rollAxisProxy = ...
    ( ...
        -u1 + ...
         u2 + ...
         u3 - ...
         u4 ...
    ) / 4;
pitchAxisProxy = ...
    ( ...
         u1 - ...
         u2 + ...
         u3 - ...
         u4 ...
    ) / 4;
yawAxisProxy = ...
    ( ...
         u1 + ...
         u2 - ...
         u3 - ...
         u4 ...
    ) / 4;
REAL_CONTROL_AXES_PROXY = ...
    table( ...
        t, ...
        thrustAxisProxy, ...
        rollAxisProxy, ...
        pitchAxisProxy, ...
        yawAxisProxy, ...
        'VariableNames', { ...
            'FlightTime_s', ...
            'ThrustAxisProxy_norm', ...
            'RollAxisProxy_norm', ...
            'PitchAxisProxy_norm', ...
            'YawAxisProxy_norm'});
ThrustAxisProxyRMS_norm = ...
    sqrt( ...
        mean( ...
            thrustAxisProxy.^2, ...
            'omitnan'));
RollAxisProxyRMS_norm = ...
    sqrt( ...
        mean( ...
            rollAxisProxy.^2, ...
            'omitnan'));
PitchAxisProxyRMS_norm = ...
    sqrt( ...
        mean( ...
            pitchAxisProxy.^2, ...
            'omitnan'));
YawAxisProxyRMS_norm = ...
    sqrt( ...
        mean( ...
            yawAxisProxy.^2, ...
            'omitnan'));
PeakAbsThrustAxisProxy_norm = ...
    max( ...
        abs(thrustAxisProxy), ...
        [], ...
        'omitnan');
PeakAbsRollAxisProxy_norm = ...
    max( ...
        abs(rollAxisProxy), ...
        [], ...
        'omitnan');
PeakAbsPitchAxisProxy_norm = ...
    max( ...
        abs(pitchAxisProxy), ...
        [], ...
        'omitnan');
PeakAbsYawAxisProxy_norm = ...
    max( ...
        abs(yawAxisProxy), ...
        [], ...
        'omitnan');
delete( ...
    findall( ...
        groot, ...
        'Type','figure', ...
        'Tag','RealFlight_ControlAxes'));
fig07 = ...
    figure( ...
        'Name','07 - Real UAV Control Axes', ...
        'Tag','RealFlight_ControlAxes', ...
        'Color','w', ...
        'NumberTitle','off');
tl07 = ...
    tiledlayout( ...
        fig07, ...
        4, ...
        1, ...
        'TileSpacing','compact', ...
        'Padding','compact');
title( ...
    tl07, ...
    ['REAL UAV Control Axes — Derived actuator-space proxy ', ...
     '(not internal controller signals)']);
ax1 = ...
    nexttile(tl07);
plot( ...
    ax1, ...
    t, ...
    thrustAxisProxy, ...
    'LineWidth',1.4);
grid(ax1,'on');
box(ax1,'on');
ylabel( ...
    ax1, ...
    'Normalized [-]');
title( ...
    ax1, ...
    'thrustAxis — DERIVED PROXY');
xlim( ...
    ax1, ...
    [t(1) t(end)]);
ax2 = ...
    nexttile(tl07);
plot( ...
    ax2, ...
    t, ...
    rollAxisProxy, ...
    'LineWidth',1.4);
yline( ...
    ax2, ...
    0, ...
    ':', ...
    'HandleVisibility','off');
grid(ax2,'on');
box(ax2,'on');
ylabel( ...
    ax2, ...
    'Normalized [-]');
title( ...
    ax2, ...
    'rollAxis — DERIVED PROXY');
xlim( ...
    ax2, ...
    [t(1) t(end)]);
ax3 = ...
    nexttile(tl07);
plot( ...
    ax3, ...
    t, ...
    pitchAxisProxy, ...
    'LineWidth',1.4);
yline( ...
    ax3, ...
    0, ...
    ':', ...
    'HandleVisibility','off');
grid(ax3,'on');
box(ax3,'on');
ylabel( ...
    ax3, ...
    'Normalized [-]');
title( ...
    ax3, ...
    'pitchAxis — DERIVED PROXY');
xlim( ...
    ax3, ...
    [t(1) t(end)]);
ax4 = ...
    nexttile(tl07);
plot( ...
    ax4, ...
    t, ...
    yawAxisProxy, ...
    'LineWidth',1.4);
yline( ...
    ax4, ...
    0, ...
    ':', ...
    'HandleVisibility','off');
grid(ax4,'on');
box(ax4,'on');
ylabel( ...
    ax4, ...
    'Normalized [-]');
xlabel( ...
    ax4, ...
    'Time [s]');
title( ...
    ax4, ...
    'yawAxis — DERIVED PROXY');
xlim( ...
    ax4, ...
    [t(1) t(end)]);
allAxes = ...
    findall( ...
        fig07, ...
        'Type','axes');
for iAx = 1:numel(allAxes)
    try
        if ~isempty(allAxes(iAx).Toolbar)
            allAxes(iAx).Toolbar.Visible = ...
                'off';
        end
    catch
    end
end
drawnow;
figure07File = ...
    fullfile( ...
        REAL_FIGURES_FOLDER, ...
        '07_Control_Axes.png');
exportgraphics( ...
    fig07, ...
    figure07File, ...
    'Resolution',300);
writetable( ...
    REAL_CONTROL_AXES_PROXY, ...
    fullfile( ...
        REAL_TABLES_FOLDER, ...
        'Control_Axes_Proxy.csv'));
if exist('ActuationMetrics','var') && ...
        istable(ActuationMetrics)
elseif isfield(REAL_ACTUATION_RESULTS,'ActuationMetrics') && ...
        istable(REAL_ACTUATION_RESULTS.ActuationMetrics)
    ActuationMetrics = ...
        REAL_ACTUATION_RESULTS.ActuationMetrics;
else
    warning( ...
        'RealFlight:ActuationMetricsUnavailable', ...
        ['ActuationMetrics could not be recovered.\n', ...
         'Control-axis proxy metrics will still be saved separately.']);
end
if exist('ActuationMetrics','var') && ...
        istable(ActuationMetrics)
    ActuationMetrics.ControlAxesBasis = ...
        "DERIVED_FROM_MOTOR_PWM_QUADX";
    ActuationMetrics.ThrustAxisProxyRMS_norm = ...
        ThrustAxisProxyRMS_norm;
    ActuationMetrics.RollAxisProxyRMS_norm = ...
        RollAxisProxyRMS_norm;
    ActuationMetrics.PitchAxisProxyRMS_norm = ...
        PitchAxisProxyRMS_norm;
    ActuationMetrics.YawAxisProxyRMS_norm = ...
        YawAxisProxyRMS_norm;
    ActuationMetrics.PeakAbsThrustAxisProxy_norm = ...
        PeakAbsThrustAxisProxy_norm;
    ActuationMetrics.PeakAbsRollAxisProxy_norm = ...
        PeakAbsRollAxisProxy_norm;
    ActuationMetrics.PeakAbsPitchAxisProxy_norm = ...
        PeakAbsPitchAxisProxy_norm;
    ActuationMetrics.PeakAbsYawAxisProxy_norm = ...
        PeakAbsYawAxisProxy_norm;
    writetable( ...
        ActuationMetrics, ...
        fullfile( ...
            REAL_TABLES_FOLDER, ...
            'Actuation_Metrics.csv'));
end
REAL_CONTROL_AXES_RESULTS = ...
    struct();
REAL_CONTROL_AXES_RESULTS.Classification = ...
    "DERIVED_PROXY";
REAL_CONTROL_AXES_RESULTS.Source = ...
    "SERVO_OUTPUT_RAW";
REAL_CONTROL_AXES_RESULTS.FrameClass = ...
    REAL_ACTUATOR_CONFIG.FrameClass;
REAL_CONTROL_AXES_RESULTS.FrameType = ...
    REAL_ACTUATOR_CONFIG.FrameType;
REAL_CONTROL_AXES_RESULTS.Unit = ...
    "normalized dimensionless";
REAL_CONTROL_AXES_RESULTS.ExactControllerAxesAvailable = ...
    false;
REAL_CONTROL_AXES_RESULTS.ProxyInterpretation = ...
    "Actuator-space differential motor-command proxy";
REAL_CONTROL_AXES_RESULTS.Data = ...
    REAL_CONTROL_AXES_PROXY;
REAL_CONTROL_AXES_RESULTS.ThrustAxisProxyRMS_norm = ...
    ThrustAxisProxyRMS_norm;
REAL_CONTROL_AXES_RESULTS.RollAxisProxyRMS_norm = ...
    RollAxisProxyRMS_norm;
REAL_CONTROL_AXES_RESULTS.PitchAxisProxyRMS_norm = ...
    PitchAxisProxyRMS_norm;
REAL_CONTROL_AXES_RESULTS.YawAxisProxyRMS_norm = ...
    YawAxisProxyRMS_norm;
REAL_CONTROL_AXES_RESULTS.PeakAbsThrustAxisProxy_norm = ...
    PeakAbsThrustAxisProxy_norm;
REAL_CONTROL_AXES_RESULTS.PeakAbsRollAxisProxy_norm = ...
    PeakAbsRollAxisProxy_norm;
REAL_CONTROL_AXES_RESULTS.PeakAbsPitchAxisProxy_norm = ...
    PeakAbsPitchAxisProxy_norm;
REAL_CONTROL_AXES_RESULTS.PeakAbsYawAxisProxy_norm = ...
    PeakAbsYawAxisProxy_norm;
availabilitySignal = ...
    "ControlAxes";
availabilityStatus = ...
    "DERIVED";
availabilitySource = ...
    "SERVO_OUTPUT_RAW + Quad-X motor mapping";
availabilityUnits = ...
    "normalized [-]";
availabilityNote = ...
    "Actuator-space thrust/roll/pitch/yaw proxy derived from four motor " + ...
    "commands. Not equivalent to the internal Simulink controlAxesLog.";
availabilityIndex = ...
    find( ...
        REAL_DATA_AVAILABILITY.Signal == ...
        availabilitySignal, ...
        1);
if isempty(availabilityIndex)
    newRow = ...
        table( ...
            string(availabilitySignal), ...
            string("Controller"), ...
            string(availabilityStatus), ...
            string(availabilitySource), ...
            string(availabilityUnits), ...
            string(availabilityNote), ...
            'VariableNames', ...
            REAL_DATA_AVAILABILITY.Properties.VariableNames);
    REAL_DATA_AVAILABILITY = ...
        [ ...
            REAL_DATA_AVAILABILITY; ...
            newRow ...
        ];
else
    REAL_DATA_AVAILABILITY.Status(availabilityIndex) = ...
        string(availabilityStatus);
    REAL_DATA_AVAILABILITY.SourceMessage(availabilityIndex) = ...
        string(availabilitySource);
    REAL_DATA_AVAILABILITY.Units(availabilityIndex) = ...
        string(availabilityUnits);
    REAL_DATA_AVAILABILITY.Notes(availabilityIndex) = ...
        string(availabilityNote);
end
writetable( ...
    REAL_DATA_AVAILABILITY, ...
    fullfile( ...
        REAL_TABLES_FOLDER, ...
        'Metric_Availability.csv'));
save( ...
    REAL_EXPERIMENT_DATA_FILE, ...
    'REAL_CONTROL_AXES_RESULTS', ...
    'REAL_CONTROL_AXES_PROXY', ...
    'REAL_DATA_AVAILABILITY', ...
    '-append');
if exist('ActuationMetrics','var') && ...
        istable(ActuationMetrics)
    save( ...
        REAL_EXPERIMENT_DATA_FILE, ...
        'ActuationMetrics', ...
        '-append');
end
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' REAL CONTROL AXES PROXY GENERATED\n');
fprintf('==============================================================\n\n');
fprintf( ...
    'Data basis:             SERVO_OUTPUT_RAW motor commands\n');
fprintf( ...
    'Classification:         DERIVED_PROXY\n');
fprintf( ...
    'Units:                  normalized [-]\n');
fprintf( ...
    'Samples:                %d\n', ...
    height(REAL_CONTROL_AXES_PROXY));
fprintf('\n');
fprintf( ...
    'Thrust proxy RMS:       %.5f\n', ...
    ThrustAxisProxyRMS_norm);
fprintf( ...
    'Roll proxy RMS:         %.5f\n', ...
    RollAxisProxyRMS_norm);
fprintf( ...
    'Pitch proxy RMS:        %.5f\n', ...
    PitchAxisProxyRMS_norm);
fprintf( ...
    'Yaw proxy RMS:          %.5f\n', ...
    YawAxisProxyRMS_norm);
fprintf('\n');
fprintf( ...
    'Peak |thrust proxy|:    %.5f\n', ...
    PeakAbsThrustAxisProxy_norm);
fprintf( ...
    'Peak |roll proxy|:      %.5f\n', ...
    PeakAbsRollAxisProxy_norm);
fprintf( ...
    'Peak |pitch proxy|:     %.5f\n', ...
    PeakAbsPitchAxisProxy_norm);
fprintf( ...
    'Peak |yaw proxy|:       %.5f\n', ...
    PeakAbsYawAxisProxy_norm);
fprintf('\n');
fprintf( ...
    'Exact internal controller axes available: false\n');
fprintf('\n');
fprintf('Files generated / updated:\n');
fprintf('  - 07_Control_Axes.png\n');
fprintf('  - Control_Axes_Proxy.csv\n');
fprintf('  - Actuation_Metrics.csv\n');
fprintf('  - Metric_Availability.csv\n');
fprintf('  - experiment_data.mat\n');
fprintf('\n');
fprintf('==============================================================\n');
clear requiredVariables ...
      U ...
      validRows ...
      order ...
      u1 ...
      u2 ...
      u3 ...
      u4 ...
      thrustAxisProxy ...
      rollAxisProxy ...
      pitchAxisProxy ...
      yawAxisProxy ...
      ThrustAxisProxyRMS_norm ...
      RollAxisProxyRMS_norm ...
      PitchAxisProxyRMS_norm ...
      YawAxisProxyRMS_norm ...
      PeakAbsThrustAxisProxy_norm ...
      PeakAbsRollAxisProxy_norm ...
      PeakAbsPitchAxisProxy_norm ...
      PeakAbsYawAxisProxy_norm ...
      availabilitySignal ...
      availabilityIndex ...
      availabilityStatus ...
      availabilitySource ...
      availabilityUnits ...
      availabilityNote ...
      newRow ...
      figure07File ...
      allAxes ...
      iAx ...
      ax1 ...
      ax2 ...
      ax3 ...
      ax4 ...
      tl07 ...
      k;
