requiredVariables = { ...
    'REAL_DATA', ...
    'REAL_FLIGHT_INSPECTION', ...
    'REAL_FIGURES_FOLDER', ...
    'REAL_TABLES_FOLDER', ...
    'REAL_EXPERIMENT_DATA_FILE', ...
    'REAL_DATA_AVAILABILITY'};
for k = 1:numel(requiredVariables)
    if ~exist(requiredVariables{k},'var')
        error( ...
            'RealFlight:MissingRequiredVariable', ...
            ['Required variable "%s" was not found.\n\n', ...
             'Run the previous real-flight scripts first.'], ...
            requiredVariables{k});
    end
end
attitudeAvailable = ...
    isfield(REAL_DATA,'State') && ...
    isfield(REAL_DATA.State,'Attitude') && ...
    ~isempty(REAL_DATA.State.Attitude);
navigationControllerAvailable = ...
    isfield(REAL_DATA,'Navigation') && ...
    isfield(REAL_DATA.Navigation,'Controller') && ...
    ~isempty(REAL_DATA.Navigation.Controller);
if ~attitudeAvailable
    error( ...
        'RealFlight:AttitudeUnavailable', ...
        'ATTITUDE telemetry is unavailable.');
end
attitudeCommandAvailable = ...
    navigationControllerAvailable;
if attitudeCommandAvailable
    attitudeCommandAvailabilityReason = ...
        "AVAILABLE";
else
    attitudeCommandAvailabilityReason = ...
        "NAV_CONTROLLER_OUTPUT_NOT_PRESENT";
end
trackingStart_s = ...
    REAL_FLIGHT_INSPECTION.CoreStartTime_s;
trackingEnd_s = ...
    REAL_FLIGHT_INSPECTION.CoreEndTime_s;
trackingWindowSource = ...
    "PRIMARY_ATTEMPT_WINDOW";
if ~isfinite(trackingStart_s) || ...
        ~isfinite(trackingEnd_s) || ...
        trackingEnd_s <= trackingStart_s
    error( ...
        'RealFlight:InvalidAttitudeTrackingWindow', ...
        ['The primary attitude tracking window is invalid. ', ...
         'Check REAL_FLIGHT_INSPECTION.CoreStartTime_s/CoreEndTime_s.']);
end
trackingDuration_s = ...
    trackingEnd_s - ...
    trackingStart_s;
ATT = ...
    REAL_DATA.State.Attitude;
attitudeMask = ...
    ATT.Time_s >= trackingStart_s & ...
    ATT.Time_s <= trackingEnd_s;
if nnz(attitudeMask) < 2
    error( ...
        'RealFlight:InsufficientAttitudeSamples', ...
        'Insufficient ATTITUDE samples exist in the tracking window.');
end
tAttitudeAbsolute = ...
    double( ...
        ATT.Time_s(attitudeMask));
Roll_deg = ...
    rad2deg( ...
        double( ...
            ATT.Roll_rad(attitudeMask)));
Pitch_deg = ...
    rad2deg( ...
        double( ...
            ATT.Pitch_rad(attitudeMask)));
Yaw_deg = ...
    rad2deg( ...
        double( ...
            ATT.Yaw_rad(attitudeMask)));
[tAttitudeAbsolute,order] = ...
    sort(tAttitudeAbsolute);
Roll_deg = ...
    Roll_deg(order);
Pitch_deg = ...
    Pitch_deg(order);
Yaw_deg = ...
    Yaw_deg(order);
[tAttitudeAbsolute,uniqueIndex] = ...
    unique( ...
        tAttitudeAbsolute, ...
        'stable');
Roll_deg = ...
    Roll_deg(uniqueIndex);
Pitch_deg = ...
    Pitch_deg(uniqueIndex);
Yaw_deg = ...
    Yaw_deg(uniqueIndex);
if attitudeCommandAvailable
    NAV = ...
        REAL_DATA.Navigation.Controller;
    commandMask = ...
        NAV.Time_s >= trackingStart_s & ...
        NAV.Time_s <= trackingEnd_s;
    if nnz(commandMask) >= 2
        tCommandAbsolute = ...
            double( ...
                NAV.Time_s(commandMask));
        RollCommand_deg = ...
            rad2deg( ...
                double( ...
                    NAV.NavRollCommand_rad(commandMask)));
        PitchCommand_deg = ...
            rad2deg( ...
                double( ...
                    NAV.NavPitchCommand_rad(commandMask)));
        [tCommandAbsolute,order] = ...
            sort(tCommandAbsolute);
        RollCommand_deg = ...
            RollCommand_deg(order);
        PitchCommand_deg = ...
            PitchCommand_deg(order);
        [tCommandAbsolute,uniqueIndex] = ...
            unique( ...
                tCommandAbsolute, ...
                'stable');
        RollCommand_deg = ...
            RollCommand_deg(uniqueIndex);
        PitchCommand_deg = ...
            PitchCommand_deg(uniqueIndex);
        commonStart_s = ...
            max( ...
                tCommandAbsolute(1), ...
                tAttitudeAbsolute(1));
        commonEnd_s = ...
            min( ...
                tCommandAbsolute(end), ...
                tAttitudeAbsolute(end));
        validCommandTime = ...
            tCommandAbsolute >= commonStart_s & ...
            tCommandAbsolute <= commonEnd_s;
        tMetricAbsolute = ...
            tCommandAbsolute(validCommandTime);
        RollCommandMetric_deg = ...
            RollCommand_deg(validCommandTime);
        PitchCommandMetric_deg = ...
            PitchCommand_deg(validCommandTime);
        if numel(tMetricAbsolute) >= 2
            RollMeasuredMetric_deg = ...
                interp1( ...
                    tAttitudeAbsolute, ...
                    Roll_deg, ...
                    tMetricAbsolute, ...
                    'linear');
            PitchMeasuredMetric_deg = ...
                interp1( ...
                    tAttitudeAbsolute, ...
                    Pitch_deg, ...
                    tMetricAbsolute, ...
                    'linear');
            validMetricRows = ...
                isfinite(tMetricAbsolute) & ...
                isfinite(RollCommandMetric_deg) & ...
                isfinite(PitchCommandMetric_deg) & ...
                isfinite(RollMeasuredMetric_deg) & ...
                isfinite(PitchMeasuredMetric_deg);
            tMetricAbsolute = ...
                tMetricAbsolute(validMetricRows);
            RollCommandMetric_deg = ...
                RollCommandMetric_deg(validMetricRows);
            PitchCommandMetric_deg = ...
                PitchCommandMetric_deg(validMetricRows);
            RollMeasuredMetric_deg = ...
                RollMeasuredMetric_deg(validMetricRows);
            PitchMeasuredMetric_deg = ...
                PitchMeasuredMetric_deg(validMetricRows);
        end
    else
        attitudeCommandAvailable = ...
            false;
        attitudeCommandAvailabilityReason = ...
            "INSUFFICIENT_NAV_CONTROLLER_OUTPUT_SAMPLES";
    end
end
if attitudeCommandAvailable
    if ~exist('tMetricAbsolute','var') || ...
            numel(tMetricAbsolute) < 2
        attitudeCommandAvailable = ...
            false;
        attitudeCommandAvailabilityReason = ...
            "NO_COMMON_COMMAND_ATTITUDE_TIME_SUPPORT";
    end
end
tAttitude = ...
    tAttitudeAbsolute - ...
    trackingStart_s;
if attitudeCommandAvailable
    tCommand = ...
        tCommandAbsolute - ...
        trackingStart_s;
    tMetric = ...
        tMetricAbsolute - ...
        trackingStart_s;
else
    tCommandAbsolute = ...
        zeros(0,1);
    tCommand = ...
        zeros(0,1);
    RollCommand_deg = ...
        NaN(0,1);
    PitchCommand_deg = ...
        NaN(0,1);
    tMetricAbsolute = ...
        tAttitudeAbsolute;
    tMetric = ...
        tAttitude;
    RollCommandMetric_deg = ...
        NaN(size(tMetricAbsolute));
    PitchCommandMetric_deg = ...
        NaN(size(tMetricAbsolute));
    RollMeasuredMetric_deg = ...
        Roll_deg;
    PitchMeasuredMetric_deg = ...
        Pitch_deg;
end
if attitudeCommandAvailable
    RollError_deg = ...
        RollMeasuredMetric_deg - ...
        RollCommandMetric_deg;
    PitchError_deg = ...
        PitchMeasuredMetric_deg - ...
        PitchCommandMetric_deg;
    RollTrackingRMSE_deg = ...
        sqrt( ...
            mean( ...
                RollError_deg.^2, ...
                'omitnan'));
    PitchTrackingRMSE_deg = ...
        sqrt( ...
            mean( ...
                PitchError_deg.^2, ...
                'omitnan'));
    RollTrackingMAE_deg = ...
        mean( ...
            abs(RollError_deg), ...
            'omitnan');
    PitchTrackingMAE_deg = ...
        mean( ...
            abs(PitchError_deg), ...
            'omitnan');
    RollTrackingMaxAbs_deg = ...
        max( ...
            abs(RollError_deg), ...
            [], ...
            'omitnan');
    PitchTrackingMaxAbs_deg = ...
        max( ...
            abs(PitchError_deg), ...
            [], ...
            'omitnan');
    MaxAbsRollCommand_deg = ...
        max( ...
            abs(RollCommandMetric_deg), ...
            [], ...
            'omitnan');
    MaxAbsPitchCommand_deg = ...
        max( ...
            abs(PitchCommandMetric_deg), ...
            [], ...
            'omitnan');
else
    RollError_deg = ...
        NaN(size(tMetricAbsolute));
    PitchError_deg = ...
        NaN(size(tMetricAbsolute));
    RollTrackingRMSE_deg = ...
        NaN;
    PitchTrackingRMSE_deg = ...
        NaN;
    RollTrackingMAE_deg = ...
        NaN;
    PitchTrackingMAE_deg = ...
        NaN;
    RollTrackingMaxAbs_deg = ...
        NaN;
    PitchTrackingMaxAbs_deg = ...
        NaN;
    MaxAbsRollCommand_deg = ...
        NaN;
    MaxAbsPitchCommand_deg = ...
        NaN;
end
YawTrackingRMSE_deg = ...
    NaN;
REAL_ATTITUDE_TRACKING_DATA = ...
    table( ...
        tMetricAbsolute, ...
        tMetric, ...
        RollCommandMetric_deg, ...
        RollMeasuredMetric_deg, ...
        RollError_deg, ...
        PitchCommandMetric_deg, ...
        PitchMeasuredMetric_deg, ...
        PitchError_deg, ...
        'VariableNames', { ...
            'TLOG_Time_s', ...
            'FlightTime_s', ...
            'RollCommand_deg', ...
            'RollMeasured_deg', ...
            'RollError_deg', ...
            'PitchCommand_deg', ...
            'PitchMeasured_deg', ...
            'PitchError_deg'});
delete( ...
    findall( ...
        groot, ...
        'Type','figure', ...
        'Tag','RealFlight_AttitudeTracking'));
fig08 = ...
    figure( ...
        'Name','08 - Real UAV Attitude Tracking', ...
        'Tag','RealFlight_AttitudeTracking', ...
        'Color','w', ...
        'NumberTitle','off');
tl08 = ...
    tiledlayout( ...
        fig08, ...
        3, ...
        1, ...
        'TileSpacing','compact', ...
        'Padding','compact');
title( ...
    tl08, ...
    localAttitudeFigureTitle( ...
        attitudeCommandAvailable));
ax1 = ...
    nexttile(tl08);
hold(ax1,'on');
if attitudeCommandAvailable
    plot( ...
        ax1, ...
        tCommand, ...
        RollCommand_deg, ...
        '--', ...
        'LineWidth',1.3, ...
        'DisplayName','Command');
end
plot( ...
    ax1, ...
    tAttitude, ...
    Roll_deg, ...
    'LineWidth',1.3, ...
    'DisplayName','REAL');
grid(ax1,'on');
box(ax1,'on');
ylabel( ...
    ax1, ...
    'Roll [deg]');
if attitudeCommandAvailable
    title( ...
        ax1, ...
        sprintf( ...
            'Roll Tracking — RMSE %.3f deg', ...
            RollTrackingRMSE_deg));
else
    title( ...
        ax1, ...
        'Roll — command NOT AVAILABLE in TLOG');
end
legend( ...
    ax1, ...
    'Location','best');
xlim( ...
    ax1, ...
    [0 trackingDuration_s]);
ax2 = ...
    nexttile(tl08);
hold(ax2,'on');
if attitudeCommandAvailable
    plot( ...
        ax2, ...
        tCommand, ...
        PitchCommand_deg, ...
        '--', ...
        'LineWidth',1.3, ...
        'DisplayName','Command');
end
plot( ...
    ax2, ...
    tAttitude, ...
    Pitch_deg, ...
    'LineWidth',1.3, ...
    'DisplayName','REAL');
grid(ax2,'on');
box(ax2,'on');
ylabel( ...
    ax2, ...
    'Pitch [deg]');
if attitudeCommandAvailable
    title( ...
        ax2, ...
        sprintf( ...
            'Pitch Tracking — RMSE %.3f deg', ...
            PitchTrackingRMSE_deg));
else
    title( ...
        ax2, ...
        'Pitch — command NOT AVAILABLE in TLOG');
end
legend( ...
    ax2, ...
    'Location','best');
xlim( ...
    ax2, ...
    [0 trackingDuration_s]);
ax3 = ...
    nexttile(tl08);
plot( ...
    ax3, ...
    tAttitude, ...
    Yaw_deg, ...
    'LineWidth',1.3, ...
    'DisplayName','REAL');
grid(ax3,'on');
box(ax3,'on');
ylabel( ...
    ax3, ...
    'Yaw [deg]');
xlabel( ...
    ax3, ...
    'Time [s]');
title( ...
    ax3, ...
    'Yaw — command NOT AVAILABLE in TLOG');
legend( ...
    ax3, ...
    'Location','best');
xlim( ...
    ax3, ...
    [0 trackingDuration_s]);
allAxes = ...
    findall( ...
        fig08, ...
        'Type','axes');
for iAx = 1:numel(allAxes)
    try
        if ~isempty(allAxes(iAx).Toolbar)
            allAxes(iAx).Toolbar.Visible = ...
                'off';
        end
    catch
    end
end
drawnow;
figure08File = ...
    fullfile( ...
        REAL_FIGURES_FOLDER, ...
        '08_Attitude_Tracking.png');
exportgraphics( ...
    fig08, ...
    figure08File, ...
    'Resolution',300);
Mission = ...
    1;
UAVModel = ...
    "REAL";
TrajectoryID = ...
    NaN;
TrajectoryName = ...
    "REAL_TLOG_UNSPECIFIED";
NumWaypoints = ...
    NaN;
NavigationWindowComplete = ...
    false;
FailsafeAborted = ...
    false;
MissionStartTime_s = ...
    trackingStart_s;
NavigationEndTime_s = ...
    trackingEnd_s;
NavigationDuration_s = ...
    trackingDuration_s;
MetricSampleRate_Hz_Column = ...
    NaN;
if attitudeCommandAvailable
    NavigationMetricSamples = ...
        height(REAL_ATTITUDE_TRACKING_DATA);
else
    NavigationMetricSamples = ...
        0;
end
RollSelectedTrackingRMSE_deg = ...
    RollTrackingRMSE_deg;
PitchSelectedTrackingRMSE_deg = ...
    PitchTrackingRMSE_deg;
YawSelectedTrackingRMSE_deg = ...
    NaN;
pSelectedTrackingRMSE_rad_s = ...
    NaN;
qSelectedTrackingRMSE_rad_s = ...
    NaN;
rSelectedTrackingRMSE_rad_s = ...
    NaN;
MaxAbsRollCommand_deg = ...
    MaxAbsRollCommand_deg;
MaxAbsPitchCommand_deg = ...
    MaxAbsPitchCommand_deg;
MaxAbsPCommand_rad_s = ...
    NaN;
MaxAbsQCommand_rad_s = ...
    NaN;
MaxAbsRCommand_rad_s = ...
    NaN;
ControllerDiagnostics = ...
    table( ...
        Mission, ...
        UAVModel, ...
        TrajectoryID, ...
        TrajectoryName, ...
        NumWaypoints, ...
        NavigationWindowComplete, ...
        FailsafeAborted, ...
        MissionStartTime_s, ...
        NavigationEndTime_s, ...
        NavigationDuration_s, ...
        MetricSampleRate_Hz_Column, ...
        NavigationMetricSamples, ...
        RollSelectedTrackingRMSE_deg, ...
        PitchSelectedTrackingRMSE_deg, ...
        YawSelectedTrackingRMSE_deg, ...
        pSelectedTrackingRMSE_rad_s, ...
        qSelectedTrackingRMSE_rad_s, ...
        rSelectedTrackingRMSE_rad_s, ...
        MaxAbsRollCommand_deg, ...
        MaxAbsPitchCommand_deg, ...
        MaxAbsPCommand_rad_s, ...
        MaxAbsQCommand_rad_s, ...
        MaxAbsRCommand_rad_s);
if attitudeCommandAvailable
    ControllerDiagnostics.AttitudeCommandSource = ...
        "NAV_CONTROLLER_OUTPUT";
else
    ControllerDiagnostics.AttitudeCommandSource = ...
        "NOT_AVAILABLE";
end
ControllerDiagnostics.RollCommandAvailable = ...
    attitudeCommandAvailable;
ControllerDiagnostics.PitchCommandAvailable = ...
    attitudeCommandAvailable;
ControllerDiagnostics.AttitudeCommandAvailabilityReason = ...
    attitudeCommandAvailabilityReason;
ControllerDiagnostics.RollTrackingMAE_deg = ...
    RollTrackingMAE_deg;
ControllerDiagnostics.PitchTrackingMAE_deg = ...
    PitchTrackingMAE_deg;
ControllerDiagnostics.RollTrackingMaxAbsError_deg = ...
    RollTrackingMaxAbs_deg;
ControllerDiagnostics.PitchTrackingMaxAbsError_deg = ...
    PitchTrackingMaxAbs_deg;
ControllerDiagnostics.YawCommandAvailable = ...
    false;
writetable( ...
    ControllerDiagnostics, ...
    fullfile( ...
        REAL_TABLES_FOLDER, ...
        'Controller_Diagnostics.csv'));
REAL_ATTITUDE_TRACKING_RESULTS = ...
    struct();
REAL_ATTITUDE_TRACKING_RESULTS.WindowSource = ...
    trackingWindowSource;
REAL_ATTITUDE_TRACKING_RESULTS.StartTime_s = ...
    trackingStart_s;
REAL_ATTITUDE_TRACKING_RESULTS.EndTime_s = ...
    trackingEnd_s;
REAL_ATTITUDE_TRACKING_RESULTS.Duration_s = ...
    trackingDuration_s;
if attitudeCommandAvailable
    REAL_ATTITUDE_TRACKING_RESULTS.CommandSource = ...
        "NAV_CONTROLLER_OUTPUT";
else
    REAL_ATTITUDE_TRACKING_RESULTS.CommandSource = ...
        "NOT_AVAILABLE";
end
REAL_ATTITUDE_TRACKING_RESULTS.StateSource = ...
    "ATTITUDE";
REAL_ATTITUDE_TRACKING_RESULTS.RollCommandAvailable = ...
    attitudeCommandAvailable;
REAL_ATTITUDE_TRACKING_RESULTS.PitchCommandAvailable = ...
    attitudeCommandAvailable;
REAL_ATTITUDE_TRACKING_RESULTS.CommandAvailabilityReason = ...
    attitudeCommandAvailabilityReason;
REAL_ATTITUDE_TRACKING_RESULTS.YawCommandAvailable = ...
    false;
REAL_ATTITUDE_TRACKING_RESULTS.RollTrackingRMSE_deg = ...
    RollTrackingRMSE_deg;
REAL_ATTITUDE_TRACKING_RESULTS.PitchTrackingRMSE_deg = ...
    PitchTrackingRMSE_deg;
REAL_ATTITUDE_TRACKING_RESULTS.YawTrackingRMSE_deg = ...
    NaN;
REAL_ATTITUDE_TRACKING_RESULTS.RollTrackingMAE_deg = ...
    RollTrackingMAE_deg;
REAL_ATTITUDE_TRACKING_RESULTS.PitchTrackingMAE_deg = ...
    PitchTrackingMAE_deg;
REAL_ATTITUDE_TRACKING_RESULTS.Data = ...
    REAL_ATTITUDE_TRACKING_DATA;
availabilitySignals = [ ...
    "RollAttitudeTracking"; ...
    "PitchAttitudeTracking"; ...
    "YawAttitudeTracking"];
if attitudeCommandAvailable
    availabilityStatuses = [ ...
        "DIRECT"; ...
        "DIRECT"; ...
        "NOT_AVAILABLE"];
    availabilitySources = [ ...
        "NAV_CONTROLLER_OUTPUT + ATTITUDE"; ...
        "NAV_CONTROLLER_OUTPUT + ATTITUDE"; ...
        "Yaw command not present in TLOG"];
    availabilityNotes = [ ...
        "Commanded roll compared with ATTITUDE roll at command timestamps."; ...
        "Commanded pitch compared with ATTITUDE pitch at command timestamps."; ...
        "Measured yaw exists, but an equivalent yaw command is unavailable."];
else
    availabilityStatuses = [ ...
        "NOT_AVAILABLE"; ...
        "NOT_AVAILABLE"; ...
        "NOT_AVAILABLE"];
    availabilitySources = [ ...
        "Roll command unavailable in TLOG analysis window"; ...
        "Pitch command unavailable in TLOG analysis window"; ...
        "Yaw command not present in TLOG"];
    availabilityNotes = [ ...
        "Measured roll is available, but commanded roll is unavailable; tracking metrics are NaN."; ...
        "Measured pitch is available, but commanded pitch is unavailable; tracking metrics are NaN."; ...
        "Measured yaw exists, but an equivalent yaw command is unavailable."];
end
availabilityUnits = [ ...
    "deg"; ...
    "deg"; ...
    "deg"];
for k = 1:numel(availabilitySignals)
    availabilityIndex = ...
        find( ...
            REAL_DATA_AVAILABILITY.Signal == ...
            availabilitySignals(k), ...
            1);
    if isempty(availabilityIndex)
        newRow = ...
            table( ...
                availabilitySignals(k), ...
                "Controller", ...
                availabilityStatuses(k), ...
                availabilitySources(k), ...
                availabilityUnits(k), ...
                availabilityNotes(k), ...
                'VariableNames', ...
                REAL_DATA_AVAILABILITY.Properties.VariableNames);
        REAL_DATA_AVAILABILITY = ...
            [ ...
                REAL_DATA_AVAILABILITY; ...
                newRow ...
            ];
    else
        REAL_DATA_AVAILABILITY.Status(availabilityIndex) = ...
            availabilityStatuses(k);
        REAL_DATA_AVAILABILITY.SourceMessage(availabilityIndex) = ...
            availabilitySources(k);
        REAL_DATA_AVAILABILITY.Units(availabilityIndex) = ...
            availabilityUnits(k);
        REAL_DATA_AVAILABILITY.Notes(availabilityIndex) = ...
            availabilityNotes(k);
    end
end
writetable( ...
    REAL_DATA_AVAILABILITY, ...
    fullfile( ...
        REAL_TABLES_FOLDER, ...
        'Metric_Availability.csv'));
save( ...
    REAL_EXPERIMENT_DATA_FILE, ...
    'REAL_ATTITUDE_TRACKING_RESULTS', ...
    'REAL_ATTITUDE_TRACKING_DATA', ...
    'ControllerDiagnostics', ...
    'REAL_DATA_AVAILABILITY', ...
    '-append');
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' REAL ATTITUDE TRACKING RESULTS GENERATED\n');
fprintf('==============================================================\n\n');
fprintf( ...
    'Tracking window source:    %s\n', ...
    trackingWindowSource);
fprintf( ...
    'Duration:                  %.3f s\n', ...
    trackingDuration_s);
fprintf( ...
    'Metric samples:            %d\n', ...
    height(REAL_ATTITUDE_TRACKING_DATA));
fprintf('\n');
if attitudeCommandAvailable
    fprintf( ...
        'Roll tracking RMSE:        %.4f deg\n', ...
        RollTrackingRMSE_deg);
    fprintf( ...
        'Pitch tracking RMSE:       %.4f deg\n', ...
        PitchTrackingRMSE_deg);
    fprintf( ...
        'Yaw tracking RMSE:         NOT AVAILABLE\n');
    fprintf('\n');
    fprintf( ...
        'Roll tracking MAE:         %.4f deg\n', ...
        RollTrackingMAE_deg);
    fprintf( ...
        'Pitch tracking MAE:        %.4f deg\n', ...
        PitchTrackingMAE_deg);
    fprintf('\n');
    fprintf( ...
        'Max |roll command|:        %.4f deg\n', ...
        MaxAbsRollCommand_deg);
    fprintf( ...
        'Max |pitch command|:       %.4f deg\n', ...
        MaxAbsPitchCommand_deg);
else
    fprintf('Roll command available:      false\n');
    fprintf('Pitch command available:     false\n');
    fprintf('Attitude tracking RMSE:      NOT AVAILABLE\n');
    fprintf( ...
        'Reason:                    %s\n', ...
        attitudeCommandAvailabilityReason);
    fprintf('Measured roll/pitch/yaw were preserved and plotted.\n');
end
fprintf('\n');
fprintf('Yaw command available: false\n');
fprintf('\n');
fprintf('Files generated / updated:\n');
fprintf('  - 08_Attitude_Tracking.png\n');
fprintf('  - Controller_Diagnostics.csv\n');
fprintf('  - Metric_Availability.csv\n');
fprintf('  - experiment_data.mat\n');
fprintf('\n');
fprintf('==============================================================\n');
clear requiredVariables ...
      attitudeAvailable ...
      navigationControllerAvailable ...
      attitudeCommandAvailable ...
      attitudeCommandAvailabilityReason ...
      ATT ...
      NAV ...
      attitudeMask ...
      commandMask ...
      tAttitudeAbsolute ...
      tCommandAbsolute ...
      tMetricAbsolute ...
      tAttitude ...
      tCommand ...
      tMetric ...
      Roll_deg ...
      Pitch_deg ...
      Yaw_deg ...
      RollCommand_deg ...
      PitchCommand_deg ...
      RollCommandMetric_deg ...
      PitchCommandMetric_deg ...
      RollMeasuredMetric_deg ...
      PitchMeasuredMetric_deg ...
      RollError_deg ...
      PitchError_deg ...
      commonStart_s ...
      commonEnd_s ...
      validCommandTime ...
      validMetricRows ...
      order ...
      uniqueIndex ...
      figure08File ...
      allAxes ...
      iAx ...
      availabilitySignals ...
      availabilityStatuses ...
      availabilitySources ...
      availabilityUnits ...
      availabilityNotes ...
      availabilityIndex ...
      newRow ...
      Mission ...
      UAVModel ...
      TrajectoryID ...
      TrajectoryName ...
      NumWaypoints ...
      NavigationWindowComplete ...
      FailsafeAborted ...
      MissionStartTime_s ...
      NavigationEndTime_s ...
      NavigationDuration_s ...
      MetricSampleRate_Hz_Column ...
      NavigationMetricSamples ...
      RollSelectedTrackingRMSE_deg ...
      PitchSelectedTrackingRMSE_deg ...
      YawSelectedTrackingRMSE_deg ...
      pSelectedTrackingRMSE_rad_s ...
      qSelectedTrackingRMSE_rad_s ...
      rSelectedTrackingRMSE_rad_s ...
      MaxAbsPCommand_rad_s ...
      MaxAbsQCommand_rad_s ...
      MaxAbsRCommand_rad_s ...
      ax1 ...
      ax2 ...
      ax3 ...
      tl08 ...
      k;
function titleText = localAttitudeFigureTitle(commandAvailable)
    if logical(commandAvailable)
        titleText = ...
            'REAL UAV Attitude Tracking';
    else
        titleText = ...
            ['REAL UAV Measured Attitude — ', ...
             'commands unavailable in TLOG'];
    end
end
