WINDOW_BEFORE_TOUCHDOWN_S = ...
    2.0;
WINDOW_AFTER_TOUCHDOWN_S = ...
    2.0;
STABLE_SPEED_M_S = ...
    0.15;
STABLE_VERTICAL_SPEED_M_S = ...
    0.08;
STABLE_ROLL_DEG = ...
    10;
STABLE_PITCH_DEG = ...
    10;
STABLE_ANGULAR_RATE_RAD_S = ...
    0.35;
STABLE_DURATION_S = ...
    0.50;
RATE_ZERO_TOL_RAD_S = ...
    1.0e-10;
TELEMETRY_TOUCHDOWN = ...
    struct();
TELEMETRY_TOUCHDOWN.Enabled = ...
    true;
TELEMETRY_TOUCHDOWN.SearchTail_s = ...
    20.0;
TELEMETRY_TOUCHDOWN.TerminalBaselineWindow_s = ...
    2.0;
TELEMETRY_TOUCHDOWN.MaxSpeed_m_s = ...
    0.30;
TELEMETRY_TOUCHDOWN.MaxVerticalSpeed_m_s = ...
    0.15;
TELEMETRY_TOUCHDOWN.MaxAltitudeDeviation_m = ...
    0.20;
TELEMETRY_TOUCHDOWN.MaxRoll_deg = ...
    15;
TELEMETRY_TOUCHDOWN.MaxPitch_deg = ...
    15;
TELEMETRY_TOUCHDOWN.MaxAngularRate_rad_s = ...
    0.50;
TELEMETRY_TOUCHDOWN.RateZeroTolerance_rad_s = ...
    RATE_ZERO_TOL_RAD_S;
TELEMETRY_TOUCHDOWN.MinimumStableDuration_s = ...
    0.80;
requiredVariables = { ...
    'REAL_DATA', ...
    'REAL_FLIGHT_INSPECTION', ...
    'REAL_FIGURES_FOLDER', ...
    'REAL_TABLES_FOLDER', ...
    'REAL_EXPERIMENT_DATA_FILE', ...
    'REAL_DATA_AVAILABILITY'};
for k = 1:numel(requiredVariables)
    if ~exist(requiredVariables{k},'var')
        error( ...
            'RealFlight:MissingRequiredVariable', ...
            ['Required variable "%s" was not found.\n\n', ...
             'Run the previous real-flight processing scripts first.'], ...
            requiredVariables{k});
    end
end
attemptStart_s = ...
    double( ...
        REAL_FLIGHT_INSPECTION.CoreStartTime_s);
attemptEnd_s = ...
    double( ...
        REAL_FLIGHT_INSPECTION.CoreEndTime_s);
if ~isfinite(attemptStart_s) || ...
        ~isfinite(attemptEnd_s) || ...
        attemptEnd_s <= attemptStart_s
    error( ...
        'RealFlight:InvalidAttemptWindow', ...
        'The selected real-flight attempt window is invalid.');
end
searchEnd_s = ...
    min( ...
        double(REAL_DATA.Metadata.LogDuration_s), ...
        attemptEnd_s + 5.0);
landedStateAvailable = ...
    isfield(REAL_DATA,'Status') && ...
    isfield(REAL_DATA.Status,'LandedState') && ...
    ~isempty(REAL_DATA.Status.LandedState);
TouchdownDetected = ...
    false;
TouchdownTime_s = ...
    NaN;
TouchdownBasis = ...
    "NOT_CONFIRMED";
LandingPhaseDetected = ...
    false;
LandingStartTime_s = ...
    NaN;
firstAirTime_s = ...
    NaN;
tState = ...
    [];
landedState = ...
    [];
TELEMETRY_TOUCHDOWN_DIAGNOSTICS = ...
    struct();
TELEMETRY_TOUCHDOWN_DIAGNOSTICS.Attempted = ...
    false;
TELEMETRY_TOUCHDOWN_DIAGNOSTICS.Detected = ...
    false;
TELEMETRY_TOUCHDOWN_DIAGNOSTICS.Reason = ...
    "NOT_ATTEMPTED";
if landedStateAvailable
    LS = ...
        REAL_DATA.Status.LandedState;
    stateMask = ...
        LS.Time_s >= attemptStart_s & ...
        LS.Time_s <= searchEnd_s;
    LS = ...
        LS(stateMask,:);
    if height(LS) >= 2
        [tState,landedState] = ...
            sanitizeTimeSeries( ...
                double(LS.Time_s), ...
                double(LS.LandedState));
        airborneState = ...
            landedState == 2 | ...
            landedState == 3 | ...
            landedState == 4;
        firstAirIndex = ...
            find( ...
                airborneState, ...
                1, ...
                'first');
        if ~isempty(firstAirIndex)
            firstAirTime_s = ...
                tState(firstAirIndex);
            candidateLanding = ...
                find( ...
                    landedState == 4 & ...
                    (1:numel(landedState)).' >= firstAirIndex, ...
                    1, ...
                    'first');
            if ~isempty(candidateLanding)
                LandingPhaseDetected = ...
                    true;
                LandingStartTime_s = ...
                    tState(candidateLanding);
            end
            previousState = ...
                [NaN; landedState(1:end-1)];
            groundTransition = ...
                landedState == 1 & ...
                previousState ~= 1;
            candidateTouchdowns = ...
                find( ...
                    groundTransition & ...
                    (1:numel(landedState)).' > firstAirIndex);
            if ~isempty(candidateTouchdowns)
                touchdownIndex = ...
                    candidateTouchdowns(1);
                TouchdownTime_s = ...
                    tState(touchdownIndex);
                TouchdownDetected = ...
                    true;
                TouchdownBasis = ...
                    "EXTENDED_SYS_STATE_ON_GROUND_TRANSITION_PROXY";
            end
        end
    end
end
if ~TouchdownDetected && ...
        TELEMETRY_TOUCHDOWN.Enabled
    TELEMETRY_TOUCHDOWN_DIAGNOSTICS.Attempted = ...
        true;
    [ ...
        fallbackDetected, ...
        fallbackTime_s, ...
        fallbackDiagnostics ...
    ] = ...
        detectTelemetryTouchdownProxy( ...
            REAL_DATA, ...
            attemptStart_s, ...
            attemptEnd_s, ...
            TELEMETRY_TOUCHDOWN);
    TELEMETRY_TOUCHDOWN_DIAGNOSTICS = ...
        fallbackDiagnostics;
    if fallbackDetected
        TouchdownDetected = ...
            true;
        TouchdownTime_s = ...
            fallbackTime_s;
        TouchdownBasis = ...
            "TERMINAL_STABLE_TELEMETRY_PROXY";
    end
end
if TouchdownDetected
    diagnosticCenterTime_s = ...
        TouchdownTime_s;
else
    diagnosticCenterTime_s = ...
        attemptEnd_s;
end
windowStart_s = ...
    max( ...
        attemptStart_s, ...
        diagnosticCenterTime_s - WINDOW_BEFORE_TOUCHDOWN_S);
windowEnd_s = ...
    min( ...
        searchEnd_s, ...
        diagnosticCenterTime_s + WINDOW_AFTER_TOUCHDOWN_S);
velocityAvailable = ...
    isfield(REAL_DATA,'State') && ...
    isfield(REAL_DATA.State,'VelocityNED') && ...
    ~isempty(REAL_DATA.State.VelocityNED);
VerticalContactVelocity_m_s = ...
    NaN;
ContactSpeed_m_s = ...
    NaN;
VEL_WINDOW = ...
    table();
tVelocity = ...
    [];
vN = ...
    [];
vE = ...
    [];
vD = ...
    [];
if velocityAvailable
    VEL = ...
        REAL_DATA.State.VelocityNED;
    [tVelocity,vN,vE,vD] = ...
        sanitizeTimeSeries( ...
            double(VEL.Time_s), ...
            double(VEL.North_m_s), ...
            double(VEL.East_m_s), ...
            double(VEL.Down_m_s));
    velocityWindowMask = ...
        tVelocity >= windowStart_s & ...
        tVelocity <= windowEnd_s;
    VEL_WINDOW = ...
        table( ...
            tVelocity(velocityWindowMask), ...
            vN(velocityWindowMask), ...
            vE(velocityWindowMask), ...
            vD(velocityWindowMask), ...
            'VariableNames',{ ...
                'Time_s', ...
                'North_m_s', ...
                'East_m_s', ...
                'Down_m_s'});
    if TouchdownDetected && ...
            numel(tVelocity) >= 2
        vNContact = ...
            safeInterpLinear( ...
                tVelocity, ...
                vN, ...
                TouchdownTime_s);
        vEContact = ...
            safeInterpLinear( ...
                tVelocity, ...
                vE, ...
                TouchdownTime_s);
        vDContact = ...
            safeInterpLinear( ...
                tVelocity, ...
                vD, ...
                TouchdownTime_s);
        VerticalContactVelocity_m_s = ...
            vDContact;
        ContactSpeed_m_s = ...
            sqrt( ...
                vNContact.^2 + ...
                vEContact.^2 + ...
                vDContact.^2);
    end
end
ACC_WINDOW = ...
    table();
PeakVerticalAcceleration_m_s2 = ...
    NaN;
PeakTotalAcceleration_m_s2 = ...
    NaN;
if velocityAvailable && ...
        numel(tVelocity) >= 3
    aN = ...
        gradient(vN,tVelocity);
    aE = ...
        gradient(vE,tVelocity);
    aD = ...
        gradient(vD,tVelocity);
    accelerationMagnitude = ...
        sqrt( ...
            aN.^2 + ...
            aE.^2 + ...
            aD.^2);
    accelMask = ...
        tVelocity >= windowStart_s & ...
        tVelocity <= windowEnd_s;
    ACC_WINDOW = ...
        table( ...
            tVelocity(accelMask), ...
            aN(accelMask), ...
            aE(accelMask), ...
            aD(accelMask), ...
            accelerationMagnitude(accelMask), ...
            'VariableNames',{ ...
                'Time_s', ...
                'North_m_s2', ...
                'East_m_s2', ...
                'Down_m_s2', ...
                'Magnitude_m_s2'});
    if TouchdownDetected && ...
            ~isempty(ACC_WINDOW)
        PeakVerticalAcceleration_m_s2 = ...
            max( ...
                abs(ACC_WINDOW.Down_m_s2), ...
                [], ...
                'omitnan');
        PeakTotalAcceleration_m_s2 = ...
            max( ...
                ACC_WINDOW.Magnitude_m_s2, ...
                [], ...
                'omitnan');
    end
end
tAtt = ...
    [];
roll_deg = ...
    [];
pitch_deg = ...
    [];
yaw_deg = ...
    [];
if isfield(REAL_DATA,'State') && ...
        isfield(REAL_DATA.State,'Attitude') && ...
        ~isempty(REAL_DATA.State.Attitude)
    ATT = ...
        REAL_DATA.State.Attitude;
    [tAtt,roll_rad,pitch_rad,yaw_rad] = ...
        sanitizeTimeSeries( ...
            double(ATT.Time_s), ...
            double(ATT.Roll_rad), ...
            double(ATT.Pitch_rad), ...
            double(ATT.Yaw_rad));
    roll_deg = ...
        rad2deg(roll_rad);
    pitch_deg = ...
        rad2deg(pitch_rad);
    yaw_deg = ...
        rad2deg(yaw_rad);
end
tRate = ...
    [];
p = ...
    [];
q = ...
    [];
r = ...
    [];
rateMagnitude = ...
    [];
rateTelemetryPresent = ...
    false;
rateTelemetryInformative = ...
    false;
rateTelemetryStatus = ...
    "NOT_AVAILABLE";
rateTelemetryReason = ...
    "ANGULAR_RATE_TELEMETRY_NOT_PRESENT";
if isfield(REAL_DATA,'State') && ...
        isfield(REAL_DATA.State,'AngularRate') && ...
        ~isempty(REAL_DATA.State.AngularRate)
    rateTelemetryPresent = ...
        true;
    RATE = ...
        REAL_DATA.State.AngularRate;
    [tRate,p,q,r] = ...
        sanitizeTimeSeries( ...
            double(RATE.Time_s), ...
            double(RATE.P_rad_s), ...
            double(RATE.Q_rad_s), ...
            double(RATE.R_rad_s));
    rateMagnitude = ...
        sqrt( ...
            p.^2 + ...
            q.^2 + ...
            r.^2);
    if exist('REAL_ANGULAR_RATE_RESULTS','var') && ...
            isstruct(REAL_ANGULAR_RATE_RESULTS) && ...
            isfield( ...
                REAL_ANGULAR_RATE_RESULTS, ...
                'TelemetryInformative')
        rateTelemetryInformative = ...
            logical( ...
                REAL_ANGULAR_RATE_RESULTS.TelemetryInformative);
        if isfield( ...
                REAL_ANGULAR_RATE_RESULTS, ...
                'TelemetryStatus')
            rateTelemetryStatus = ...
                string( ...
                    REAL_ANGULAR_RATE_RESULTS.TelemetryStatus);
        elseif rateTelemetryInformative
            rateTelemetryStatus = ...
                "DIRECT_INFORMATIVE";
        else
            rateTelemetryStatus = ...
                "NON_INFORMATIVE";
        end
        if isfield( ...
                REAL_ANGULAR_RATE_RESULTS, ...
                'TelemetryReason')
            rateTelemetryReason = ...
                string( ...
                    REAL_ANGULAR_RATE_RESULTS.TelemetryReason);
        elseif rateTelemetryInformative
            rateTelemetryReason = ...
                "STAGE14_CLASSIFIED_INFORMATIVE";
        else
            rateTelemetryReason = ...
                "STAGE14_CLASSIFIED_NON_INFORMATIVE";
        end
    else
        maximumAbsoluteRecordedRate_rad_s = ...
            max( ...
                abs( ...
                    [ ...
                        p; ...
                        q; ...
                        r ...
                    ]), ...
                [], ...
                'omitnan');
        if isfinite(maximumAbsoluteRecordedRate_rad_s) && ...
                maximumAbsoluteRecordedRate_rad_s > ...
                RATE_ZERO_TOL_RAD_S
            rateTelemetryInformative = ...
                true;
            rateTelemetryStatus = ...
                "DIRECT_INFORMATIVE";
            rateTelemetryReason = ...
                "LOCAL_DYNAMIC_INFORMATION_CHECK";
        else
            rateTelemetryInformative = ...
                false;
            rateTelemetryStatus = ...
                "NON_INFORMATIVE_CONSTANT_ZERO";
            rateTelemetryReason = ...
                "ATTITUDE_RATE_FIELDS_CONSTANT_ZERO_DURING_FLIGHT_WINDOW";
        end
    end
end
ATT_WINDOW = ...
    table();
PeakAngularRate_rad_s = ...
    NaN;
if ~isempty(tRate)
    rateMask = ...
        tRate >= windowStart_s & ...
        tRate <= windowEnd_s;
    ATT_WINDOW = ...
        table( ...
            tRate(rateMask), ...
            p(rateMask), ...
            q(rateMask), ...
            r(rateMask), ...
            rateMagnitude(rateMask), ...
            'VariableNames',{ ...
                'Time_s', ...
                'P_rad_s', ...
                'Q_rad_s', ...
                'R_rad_s', ...
                'Magnitude_rad_s'});
    if TouchdownDetected && ...
            rateTelemetryInformative && ...
            ~isempty(ATT_WINDOW)
        PeakAngularRate_rad_s = ...
            max( ...
                ATT_WINDOW.Magnitude_rad_s, ...
                [], ...
                'omitnan');
    end
end
PWM_WINDOW = ...
    table();
CONTROL_PROXY_WINDOW = ...
    table();
PeakMotorPWM_us = ...
    NaN;
PeakMotorSpeed_rad_s = ...
    NaN;
PeakAbsThrustAxisProxy_norm = ...
    NaN;
PeakAbsRollAxisProxy_norm = ...
    NaN;
PeakAbsPitchAxisProxy_norm = ...
    NaN;
PeakAbsYawAxisProxy_norm = ...
    NaN;
PeakAbsThrustAxis = ...
    NaN;
PeakAbsRollAxis = ...
    NaN;
PeakAbsPitchAxis = ...
    NaN;
PeakAbsYawAxis = ...
    NaN;
if isfield(REAL_DATA,'Actuator') && ...
        isfield(REAL_DATA.Actuator,'PWM') && ...
        ~isempty(REAL_DATA.Actuator.PWM) && ...
        exist('REAL_ACTUATION_RESULTS','var') && ...
        isfield(REAL_ACTUATION_RESULTS,'MotorChannels')
    PWM = ...
        REAL_DATA.Actuator.PWM;
    pwmMask = ...
        PWM.Time_s >= windowStart_s & ...
        PWM.Time_s <= windowEnd_s;
    PWM_SUB = ...
        PWM(pwmMask,:);
    if ~isempty(PWM_SUB)
        motorChannels = ...
            double( ...
                REAL_ACTUATION_RESULTS.MotorChannels);
        if numel(motorChannels) == 4 && ...
                all(isfinite(motorChannels))
            motorPWM = ...
                NaN(height(PWM_SUB),4);
            pwmFieldsValid = ...
                true;
            for motorIndex = 1:4
                channel = ...
                    motorChannels(motorIndex);
                fieldName = ...
                    sprintf( ...
                        'PWM%d_us', ...
                        channel);
                if ~ismember( ...
                        fieldName, ...
                        PWM_SUB.Properties.VariableNames)
                    pwmFieldsValid = ...
                        false;
                    break;
                end
                motorPWM(:,motorIndex) = ...
                    double( ...
                        PWM_SUB.(fieldName));
            end
            if pwmFieldsValid
                [tPWM,m1PWM,m2PWM,m3PWM,m4PWM] = ...
                    sanitizeTimeSeries( ...
                        double(PWM_SUB.Time_s), ...
                        motorPWM(:,1), ...
                        motorPWM(:,2), ...
                        motorPWM(:,3), ...
                        motorPWM(:,4));
                motorPWM = ...
                    [m1PWM m2PWM m3PWM m4PWM];
                validPWMRows = ...
                    all(isfinite(motorPWM),2) & ...
                    all(motorPWM > 0,2);
                tPWM = ...
                    tPWM(validPWMRows);
                motorPWM = ...
                    motorPWM(validPWMRows,:);
                if ~isempty(motorPWM)
                    if TouchdownDetected
                        PeakMotorPWM_us = ...
                            max( ...
                                motorPWM, ...
                                [], ...
                                'all', ...
                                'omitnan');
                    end
                    if isfield( ...
                            REAL_ACTUATION_RESULTS, ...
                            'PWMNormalizationMin_us')
                        pwmMin = ...
                            double( ...
                                REAL_ACTUATION_RESULTS.PWMNormalizationMin_us);
                    elseif isfield( ...
                            REAL_ACTUATION_RESULTS, ...
                            'MotorPWMMin_us')
                        pwmMin = ...
                            double( ...
                                REAL_ACTUATION_RESULTS.MotorPWMMin_us);
                    elseif isfield( ...
                            REAL_ACTUATION_RESULTS, ...
                            'MotorPWMMinConfigured_us') && ...
                            isfinite( ...
                                REAL_ACTUATION_RESULTS.MotorPWMMinConfigured_us)
                        pwmMin = ...
                            double( ...
                                REAL_ACTUATION_RESULTS.MotorPWMMinConfigured_us);
                    else
                        pwmMin = ...
                            1000;
                    end
                    if isfield( ...
                            REAL_ACTUATION_RESULTS, ...
                            'PWMNormalizationMax_us')
                        pwmMax = ...
                            double( ...
                                REAL_ACTUATION_RESULTS.PWMNormalizationMax_us);
                    elseif isfield( ...
                            REAL_ACTUATION_RESULTS, ...
                            'MotorPWMMax_us')
                        pwmMax = ...
                            double( ...
                                REAL_ACTUATION_RESULTS.MotorPWMMax_us);
                    elseif isfield( ...
                            REAL_ACTUATION_RESULTS, ...
                            'MotorPWMMaxConfigured_us') && ...
                            isfinite( ...
                                REAL_ACTUATION_RESULTS.MotorPWMMaxConfigured_us)
                        pwmMax = ...
                            double( ...
                                REAL_ACTUATION_RESULTS.MotorPWMMaxConfigured_us);
                    else
                        pwmMax = ...
                            2000;
                    end
                    if isfinite(pwmMin) && ...
                            isfinite(pwmMax) && ...
                            pwmMax > pwmMin
                        normalizedPWM = ...
                            (motorPWM-pwmMin) ./ ...
                            (pwmMax-pwmMin);
                        m1 = normalizedPWM(:,1);
                        m2 = normalizedPWM(:,2);
                        m3 = normalizedPWM(:,3);
                        m4 = normalizedPWM(:,4);
                        thrustProxy = ...
                            (m1+m2+m3+m4)/4;
                        rollProxy = ...
                            (-m1+m2+m3-m4)/4;
                        pitchProxy = ...
                            (m1-m2+m3-m4)/4;
                        yawProxy = ...
                            (m1+m2-m3-m4)/4;
                        if TouchdownDetected
                            PeakAbsThrustAxisProxy_norm = ...
                                max(abs(thrustProxy),[],'omitnan');
                            PeakAbsRollAxisProxy_norm = ...
                                max(abs(rollProxy),[],'omitnan');
                            PeakAbsPitchAxisProxy_norm = ...
                                max(abs(pitchProxy),[],'omitnan');
                            PeakAbsYawAxisProxy_norm = ...
                                max(abs(yawProxy),[],'omitnan');
                        end
                        CONTROL_PROXY_WINDOW = ...
                            table( ...
                                tPWM, ...
                                thrustProxy, ...
                                rollProxy, ...
                                pitchProxy, ...
                                yawProxy, ...
                                'VariableNames',{ ...
                                    'Time_s', ...
                                    'ThrustProxy_norm', ...
                                    'RollProxy_norm', ...
                                    'PitchProxy_norm', ...
                                    'YawProxy_norm'});
                    end
                    PWM_WINDOW = ...
                        table( ...
                            tPWM, ...
                            motorPWM(:,1), ...
                            motorPWM(:,2), ...
                            motorPWM(:,3), ...
                            motorPWM(:,4), ...
                            'VariableNames',{ ...
                                'Time_s', ...
                                'Motor1_PWM_us', ...
                                'Motor2_PWM_us', ...
                                'Motor3_PWM_us', ...
                                'Motor4_PWM_us'});
                end
            end
        end
    end
end
ALT_WINDOW = ...
    table();
altitudeProxyAvailable = ...
    false;
AltitudeProxyMin_m = ...
    NaN;
AltitudeProxyMax_m = ...
    NaN;
altitudeBaseline_m = ...
    NaN;
if isfield(REAL_DATA,'State') && ...
        isfield(REAL_DATA.State,'GlobalPosition') && ...
        ~isempty(REAL_DATA.State.GlobalPosition)
    GP = ...
        REAL_DATA.State.GlobalPosition;
    [tGP,relativeAltitude] = ...
        sanitizeTimeSeries( ...
            double(GP.Time_s), ...
            double(GP.RelativeAltitude_m));
    if isfinite(firstAirTime_s)
        baselineEnd_s = ...
            firstAirTime_s;
    else
        baselineEnd_s = ...
            min( ...
                attemptEnd_s, ...
                attemptStart_s + 3.0);
    end
    baselineMask = ...
        tGP >= attemptStart_s & ...
        tGP <= baselineEnd_s & ...
        isfinite(relativeAltitude);
    baselineValues = ...
        relativeAltitude(baselineMask);
    if ~isempty(baselineValues)
        altitudeBaseline_m = ...
            median( ...
                baselineValues, ...
                'omitnan');
        altitudeMask = ...
            tGP >= windowStart_s & ...
            tGP <= windowEnd_s;
        if any(altitudeMask)
            tAltitude = ...
                tGP(altitudeMask);
            AltitudeProxy_m = ...
                relativeAltitude(altitudeMask) - ...
                altitudeBaseline_m;
            ALT_WINDOW = ...
                table( ...
                    tAltitude, ...
                    AltitudeProxy_m, ...
                    'VariableNames',{ ...
                        'Time_s', ...
                        'AltitudeProxy_m'});
            AltitudeProxyMin_m = ...
                min( ...
                    AltitudeProxy_m, ...
                    [], ...
                    'omitnan');
            AltitudeProxyMax_m = ...
                max( ...
                    AltitudeProxy_m, ...
                    [], ...
                    'omitnan');
            altitudeProxyAvailable = ...
                true;
        end
    end
end
armedAtTouchdown = ...
    false;
LandedArmedDetected = ...
    false;
LandedArmedTime_s = ...
    NaN;
tHeartbeat = ...
    [];
armedSignal = ...
    [];
if isfield(REAL_DATA,'Status') && ...
        isfield(REAL_DATA.Status,'Heartbeat') && ...
        ~isempty(REAL_DATA.Status.Heartbeat)
    HB = ...
        REAL_DATA.Status.Heartbeat;
    [tHeartbeat,armedNumeric] = ...
        sanitizeTimeSeries( ...
            double(HB.Time_s), ...
            double(HB.Armed));
    armedSignal = ...
        armedNumeric > 0.5;
    if TouchdownDetected
        armedAtTouchdownNumeric = ...
            safeInterpPrevious( ...
                tHeartbeat, ...
                double(armedSignal), ...
                TouchdownTime_s);
        armedAtTouchdown = ...
            isfinite(armedAtTouchdownNumeric) && ...
            armedAtTouchdownNumeric > 0.5;
    end
    if TouchdownDetected && ...
            landedStateAvailable && ...
            ~isempty(tState)
        armedAtStateTimes = ...
            safeInterpPrevious( ...
                tHeartbeat, ...
                double(armedSignal), ...
                tState);
        landedArmedCandidates = ...
            find( ...
                tState >= TouchdownTime_s & ...
                landedState == 1 & ...
                armedAtStateTimes > 0.5);
        if ~isempty(landedArmedCandidates)
            LandedArmedDetected = ...
                true;
            LandedArmedTime_s = ...
                tState( ...
                    landedArmedCandidates(1));
        end
    end
end
StableDetected = ...
    false;
StableTime_s = ...
    NaN;
if TouchdownDetected && ...
        TouchdownBasis == "TERMINAL_STABLE_TELEMETRY_PROXY"
    StableDetected = ...
        true;
    StableTime_s = ...
        TouchdownTime_s;
elseif TouchdownDetected && ...
        velocityAvailable && ...
        ~isempty(tAtt) && ...
        ~isempty(tRate) && ...
        landedStateAvailable && ...
        ~isempty(tState)
    evaluationStart_s = ...
        TouchdownTime_s;
    evaluationEnd_s = ...
        min( ...
            searchEnd_s, ...
            TouchdownTime_s + 5.0);
    evalMask = ...
        tAtt >= evaluationStart_s & ...
        tAtt <= evaluationEnd_s;
    tEval = ...
        tAtt(evalMask);
    rollEval = ...
        roll_deg(evalMask);
    pitchEval = ...
        pitch_deg(evalMask);
    if numel(tEval) >= 2
        vNEval = ...
            safeInterpLinear( ...
                tVelocity, ...
                vN, ...
                tEval);
        vEEval = ...
            safeInterpLinear( ...
                tVelocity, ...
                vE, ...
                tEval);
        vDEval = ...
            safeInterpLinear( ...
                tVelocity, ...
                vD, ...
                tEval);
        speedEval = ...
            sqrt( ...
                vNEval.^2 + ...
                vEEval.^2 + ...
                vDEval.^2);
        rateEval = ...
            safeInterpLinear( ...
                tRate, ...
                rateMagnitude, ...
                tEval);
        onGroundEval = ...
            safeInterpPrevious( ...
                tState, ...
                double(landedState == 1), ...
                tEval) > 0.5;
        stableCondition = ...
            onGroundEval & ...
            isfinite(speedEval) & ...
            isfinite(rateEval) & ...
            speedEval <= STABLE_SPEED_M_S & ...
            abs(vDEval) <= STABLE_VERTICAL_SPEED_M_S & ...
            abs(rollEval) <= STABLE_ROLL_DEG & ...
            abs(pitchEval) <= STABLE_PITCH_DEG & ...
            rateEval <= STABLE_ANGULAR_RATE_RAD_S;
        stableRelativeIndex = ...
            firstPersistentDurationReal( ...
                stableCondition, ...
                tEval, ...
                STABLE_DURATION_S);
        if ~isempty(stableRelativeIndex)
            StableDetected = ...
                true;
            StableTime_s = ...
                tEval(stableRelativeIndex);
        end
    end
end
if TouchdownDetected && ...
        LandingPhaseDetected
    LandingToTouchdown_s = ...
        TouchdownTime_s - ...
        LandingStartTime_s;
    LandingDuration_s = ...
        LandingToTouchdown_s;
else
    LandingToTouchdown_s = ...
        NaN;
    LandingDuration_s = ...
        NaN;
end
if TouchdownDetected && ...
        StableDetected
    TouchdownToStable_s = ...
        StableTime_s - ...
        TouchdownTime_s;
else
    TouchdownToStable_s = ...
        NaN;
end
if TouchdownDetected && ...
        LandedArmedDetected
    TouchdownToLandedArmed_s = ...
        LandedArmedTime_s - ...
        TouchdownTime_s;
else
    TouchdownToLandedArmed_s = ...
        NaN;
end
if LandingPhaseDetected && ...
        LandedArmedDetected
    LandingToLandedArmed_s = ...
        LandedArmedTime_s - ...
        LandingStartTime_s;
else
    LandingToLandedArmed_s = ...
        NaN;
end
GroundPenetration_m = ...
    NaN;
BounceHeight_m = ...
    NaN;
if exist('REAL_MISSION_RESULTS','var')
    FailsafeAborted = ...
        logical( ...
            REAL_MISSION_RESULTS.FailsafeAborted);
else
    FailsafeAborted = ...
        false;
end
Mission = ...
    1;
UAVModel = ...
    "REAL";
TrajectoryID = ...
    NaN;
TrajectoryName = ...
    "REAL_TLOG_UNSPECIFIED";
NumWaypoints = ...
    NaN;
LandingPhase = ...
    NaN;
CompletePhase = ...
    NaN;
AbortedPhase = ...
    NaN;
TouchdownMetrics = ...
    table( ...
        Mission, ...
        UAVModel, ...
        TrajectoryID, ...
        TrajectoryName, ...
        NumWaypoints, ...
        LandingPhase, ...
        CompletePhase, ...
        AbortedPhase, ...
        FailsafeAborted, ...
        TouchdownDetected, ...
        StableDetected, ...
        LandedArmedDetected, ...
        LandingStartTime_s, ...
        TouchdownTime_s, ...
        StableTime_s, ...
        LandedArmedTime_s, ...
        LandingDuration_s, ...
        LandingToTouchdown_s, ...
        TouchdownToStable_s, ...
        TouchdownToLandedArmed_s, ...
        LandingToLandedArmed_s, ...
        VerticalContactVelocity_m_s, ...
        ContactSpeed_m_s, ...
        PeakVerticalAcceleration_m_s2, ...
        PeakTotalAcceleration_m_s2, ...
        PeakAbsThrustAxis, ...
        PeakAbsRollAxis, ...
        PeakAbsPitchAxis, ...
        PeakAbsYawAxis, ...
        PeakAngularRate_rad_s, ...
        PeakMotorSpeed_rad_s, ...
        GroundPenetration_m, ...
        BounceHeight_m);
TouchdownMetrics.TouchdownBasis = ...
    TouchdownBasis;
TouchdownMetrics.TouchdownIsPhysicalGroundTruth = ...
    false;
TouchdownMetrics.ExtendedSysStateAvailable = ...
    landedStateAvailable;
TouchdownMetrics.TelemetryFallbackAttempted = ...
    logical( ...
        TELEMETRY_TOUCHDOWN_DIAGNOSTICS.Attempted);
TouchdownMetrics.TelemetryFallbackDetected = ...
    logical( ...
        TELEMETRY_TOUCHDOWN_DIAGNOSTICS.Detected);
TouchdownMetrics.ArmedAtTouchdown = ...
    armedAtTouchdown;
TouchdownMetrics.AngularRateTelemetryPresent = ...
    rateTelemetryPresent;
TouchdownMetrics.AngularRateTelemetryInformative = ...
    rateTelemetryInformative;
TouchdownMetrics.AngularRateTelemetryStatus = ...
    rateTelemetryStatus;
TouchdownMetrics.AngularRateTelemetryReason = ...
    rateTelemetryReason;
TouchdownMetrics.AccelerationBasis = ...
    "DERIVED_FROM_NED_VELOCITY";
TouchdownMetrics.ControlAxesBasis = ...
    "DERIVED_PROXY_FROM_ACTUATOR_PWM";
TouchdownMetrics.MotorBasis = ...
    "SERVO_OUTPUT_RAW_PWM";
TouchdownMetrics.PeakMotorPWM_us = ...
    PeakMotorPWM_us;
TouchdownMetrics.PeakAbsThrustAxisProxy_norm = ...
    PeakAbsThrustAxisProxy_norm;
TouchdownMetrics.PeakAbsRollAxisProxy_norm = ...
    PeakAbsRollAxisProxy_norm;
TouchdownMetrics.PeakAbsPitchAxisProxy_norm = ...
    PeakAbsPitchAxisProxy_norm;
TouchdownMetrics.PeakAbsYawAxisProxy_norm = ...
    PeakAbsYawAxisProxy_norm;
TouchdownMetrics.AltitudeProxyAvailable = ...
    altitudeProxyAvailable;
TouchdownMetrics.AltitudeProxyMin_m = ...
    AltitudeProxyMin_m;
TouchdownMetrics.AltitudeProxyMax_m = ...
    AltitudeProxyMax_m;
TouchdownMetrics.GroundPenetrationAvailable = ...
    false;
TouchdownMetrics.BounceHeightAvailable = ...
    false;
delete( ...
    findall( ...
        groot, ...
        'Type','figure', ...
        'Tag','RealFlight_TouchdownDiagnostics'));
fig11 = ...
    figure( ...
        'Name','11 - Real UAV Touchdown Diagnostics', ...
        'Tag','RealFlight_TouchdownDiagnostics', ...
        'Color','w', ...
        'NumberTitle','off');
tl11 = ...
    tiledlayout( ...
        fig11, ...
        4, ...
        2, ...
        'TileSpacing','compact', ...
        'Padding','compact');
if TouchdownDetected
    title( ...
        tl11, ...
        "REAL Touchdown Diagnostics — " + ...
        strrep(TouchdownBasis,"_","\_"));
else
    title( ...
        tl11, ...
        'REAL Touchdown Diagnostics — TOUCHDOWN NOT CONFIRMED');
end
toRelativeTime = ...
    @(x) double(x) - diagnosticCenterTime_s;
ax1 = ...
    nexttile(tl11);
if ~isempty(ALT_WINDOW)
    plot( ...
        ax1, ...
        toRelativeTime(ALT_WINDOW.Time_s), ...
        ALT_WINDOW.AltitudeProxy_m, ...
        'LineWidth',1.4);
    yline(ax1,0,':');
    grid(ax1,'on');
    box(ax1,'on');
    ylabel(ax1,'Altitude [m]');
    title( ...
        ax1, ...
        'Relative-Altitude Proxy');
else
    axis(ax1,'off');
    text( ...
        ax1, ...
        0.5, ...
        0.5, ...
        'Altitude proxy NOT AVAILABLE', ...
        'Units','normalized', ...
        'HorizontalAlignment','center');
end
ax2 = ...
    nexttile(tl11);
if ~isempty(VEL_WINDOW)
    plot( ...
        ax2, ...
        toRelativeTime(VEL_WINDOW.Time_s), ...
        VEL_WINDOW.Down_m_s, ...
        'LineWidth',1.4);
    yline(ax2,0,':');
    grid(ax2,'on');
    box(ax2,'on');
    ylabel(ax2,'V_D [m/s]');
    if TouchdownDetected
        title( ...
            ax2, ...
            sprintf( ...
                'Vertical Velocity — proxy event %.3f m/s', ...
                VerticalContactVelocity_m_s));
    else
        title( ...
            ax2, ...
            'Vertical Velocity — terminal diagnostic window');
    end
else
    axis(ax2,'off');
end
ax3 = ...
    nexttile(tl11);
if ~isempty(ACC_WINDOW)
    hold(ax3,'on');
    plot( ...
        ax3, ...
        toRelativeTime(ACC_WINDOW.Time_s), ...
        ACC_WINDOW.North_m_s2, ...
        'LineWidth',1.1, ...
        'DisplayName','a_N');
    plot( ...
        ax3, ...
        toRelativeTime(ACC_WINDOW.Time_s), ...
        ACC_WINDOW.East_m_s2, ...
        'LineWidth',1.1, ...
        'DisplayName','a_E');
    plot( ...
        ax3, ...
        toRelativeTime(ACC_WINDOW.Time_s), ...
        ACC_WINDOW.Down_m_s2, ...
        'LineWidth',1.2, ...
        'DisplayName','a_D');
    grid(ax3,'on');
    box(ax3,'on');
    ylabel(ax3,'[m/s^2]');
    title( ...
        ax3, ...
        'Derived NED Acceleration');
    legend(ax3,'Location','best');
else
    axis(ax3,'off');
end
ax4 = ...
    nexttile(tl11);
if ~isempty(CONTROL_PROXY_WINDOW)
    hold(ax4,'on');
    plot( ...
        ax4, ...
        toRelativeTime(CONTROL_PROXY_WINDOW.Time_s), ...
        CONTROL_PROXY_WINDOW.ThrustProxy_norm, ...
        'LineWidth',1.1, ...
        'DisplayName','thrust');
    plot( ...
        ax4, ...
        toRelativeTime(CONTROL_PROXY_WINDOW.Time_s), ...
        CONTROL_PROXY_WINDOW.RollProxy_norm, ...
        'LineWidth',1.1, ...
        'DisplayName','roll');
    plot( ...
        ax4, ...
        toRelativeTime(CONTROL_PROXY_WINDOW.Time_s), ...
        CONTROL_PROXY_WINDOW.PitchProxy_norm, ...
        'LineWidth',1.1, ...
        'DisplayName','pitch');
    plot( ...
        ax4, ...
        toRelativeTime(CONTROL_PROXY_WINDOW.Time_s), ...
        CONTROL_PROXY_WINDOW.YawProxy_norm, ...
        'LineWidth',1.1, ...
        'DisplayName','yaw');
    yline(ax4,0,':');
    grid(ax4,'on');
    box(ax4,'on');
    ylabel(ax4,'Normalized [-]');
    title( ...
        ax4, ...
        'Control-Axis DERIVED PROXY');
    legend(ax4,'Location','best');
else
    axis(ax4,'off');
end
ax5 = ...
    nexttile(tl11);
if ~isempty(ATT_WINDOW)
    hold(ax5,'on');
    plot( ...
        ax5, ...
        toRelativeTime(ATT_WINDOW.Time_s), ...
        ATT_WINDOW.P_rad_s, ...
        'LineWidth',1.1, ...
        'DisplayName','p');
    plot( ...
        ax5, ...
        toRelativeTime(ATT_WINDOW.Time_s), ...
        ATT_WINDOW.Q_rad_s, ...
        'LineWidth',1.1, ...
        'DisplayName','q');
    plot( ...
        ax5, ...
        toRelativeTime(ATT_WINDOW.Time_s), ...
        ATT_WINDOW.R_rad_s, ...
        'LineWidth',1.1, ...
        'DisplayName','r');
    yline(ax5,0,':');
    grid(ax5,'on');
    box(ax5,'on');
    ylabel(ax5,'[rad/s]');
    if rateTelemetryInformative
        title(ax5,'Angular Rates');
    else
        title( ...
            ax5, ...
            'Angular Rates — NON-INFORMATIVE TELEMETRY');
    end
    legend(ax5,'Location','best');
else
    axis(ax5,'off');
    text( ...
        ax5, ...
        0.5, ...
        0.5, ...
        'Angular-rate telemetry NOT AVAILABLE', ...
        'Units','normalized', ...
        'HorizontalAlignment','center');
end
ax6 = ...
    nexttile(tl11);
if ~isempty(PWM_WINDOW)
    hold(ax6,'on');
    plot( ...
        ax6, ...
        toRelativeTime(PWM_WINDOW.Time_s), ...
        PWM_WINDOW.Motor1_PWM_us, ...
        'LineWidth',1.0, ...
        'DisplayName','Output 1');
    plot( ...
        ax6, ...
        toRelativeTime(PWM_WINDOW.Time_s), ...
        PWM_WINDOW.Motor2_PWM_us, ...
        'LineWidth',1.0, ...
        'DisplayName','Output 2');
    plot( ...
        ax6, ...
        toRelativeTime(PWM_WINDOW.Time_s), ...
        PWM_WINDOW.Motor3_PWM_us, ...
        'LineWidth',1.0, ...
        'DisplayName','Output 3');
    plot( ...
        ax6, ...
        toRelativeTime(PWM_WINDOW.Time_s), ...
        PWM_WINDOW.Motor4_PWM_us, ...
        'LineWidth',1.0, ...
        'DisplayName','Output 4');
    grid(ax6,'on');
    box(ax6,'on');
    ylabel(ax6,'PWM [\mus]');
    title(ax6,'Actuator PWM');
    legend(ax6,'Location','best');
else
    axis(ax6,'off');
end
ax7 = ...
    nexttile(tl11);
statePlotted = ...
    false;
if landedStateAvailable && ...
        ~isempty(tState)
    stateWindowMask = ...
        tState >= windowStart_s & ...
        tState <= windowEnd_s;
    if any(stateWindowMask)
        yyaxis(ax7,'left');
        stairs( ...
            ax7, ...
            toRelativeTime(tState(stateWindowMask)), ...
            landedState(stateWindowMask), ...
            'LineWidth',1.4);
        ylabel(ax7,'Landed State');
        yticks(ax7,[1 2 3 4]);
        yticklabels( ...
            ax7,{ ...
                'Ground', ...
                'Air', ...
                'Takeoff', ...
                'Landing'});
        statePlotted = ...
            true;
    end
end
if ~isempty(tHeartbeat)
    heartbeatWindowMask = ...
        tHeartbeat >= windowStart_s & ...
        tHeartbeat <= windowEnd_s;
    if any(heartbeatWindowMask)
        if statePlotted
            yyaxis(ax7,'right');
        end
        stairs( ...
            ax7, ...
            toRelativeTime(tHeartbeat(heartbeatWindowMask)), ...
            double(armedSignal(heartbeatWindowMask)), ...
            'LineWidth',1.2);
        ylabel(ax7,'Armed');
        ylim(ax7,[-0.1 1.1]);
        statePlotted = ...
            true;
    end
end
if statePlotted
    grid(ax7,'on');
    box(ax7,'on');
    xlabel( ...
        ax7, ...
        'Time relative to diagnostic center [s]');
    title( ...
        ax7, ...
        'Flight Management State');
else
    axis(ax7,'off');
    text( ...
        ax7, ...
        0.5, ...
        0.5, ...
        ['EXTENDED\_SYS\_STATE unavailable', newline, ...
         'No usable flight-state trace in this window'], ...
        'Units','normalized', ...
        'HorizontalAlignment','center');
end
ax8 = ...
    nexttile(tl11);
axis(ax8,'off');
if TouchdownDetected
    touchdownTimeText = ...
        sprintf('%.3f s',TouchdownTime_s);
    verticalContactText = ...
        sprintf('%.3f m/s',VerticalContactVelocity_m_s);
    contactSpeedText = ...
        sprintf('%.3f m/s',ContactSpeed_m_s);
    peakVerticalAccelText = ...
        sprintf('%.3f m/s^2',PeakVerticalAcceleration_m_s2);
    peakTotalAccelText = ...
        sprintf('%.3f m/s^2',PeakTotalAcceleration_m_s2);
    if rateTelemetryInformative && ...
            isfinite(PeakAngularRate_rad_s)
        peakRateText = ...
            sprintf('%.3f rad/s',PeakAngularRate_rad_s);
    else
        peakRateText = ...
            "NOT AVAILABLE";
    end
    peakPWMText = ...
        sprintf('%.0f us',PeakMotorPWM_us);
else
    touchdownTimeText = ...
        "NOT CONFIRMED";
    verticalContactText = ...
        "NOT AVAILABLE";
    contactSpeedText = ...
        "NOT AVAILABLE";
    peakVerticalAccelText = ...
        "NOT AVAILABLE";
    peakTotalAccelText = ...
        "NOT AVAILABLE";
    peakRateText = ...
        "NOT AVAILABLE";
    peakPWMText = ...
        "NOT AVAILABLE";
end
summaryLines = [ ...
    "Touchdown basis: " + TouchdownBasis; ...
    "Touchdown time: " + touchdownTimeText; ...
    "V_D at proxy: " + verticalContactText; ...
    "3D speed at proxy: " + contactSpeedText; ...
    "Peak |a_D|: " + peakVerticalAccelText; ...
    "Peak ||a||: " + peakTotalAccelText; ...
    "Peak ||rate||: " + peakRateText; ...
    "Peak actuator PWM: " + peakPWMText; ...
    "Stable proxy: " + string(StableDetected); ...
    "Landed armed: " + string(LandedArmedDetected); ...
    "Physical contact truth: NOT AVAILABLE"; ...
    "Ground penetration: NOT AVAILABLE"; ...
    "Bounce height: NOT AVAILABLE"];
text( ...
    ax8, ...
    0.02, ...
    0.98, ...
    summaryLines, ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontName','Consolas', ...
    'FontSize',9);
title( ...
    ax8, ...
    'Diagnostic Summary');
plotAxes = { ...
    ax1, ...
    ax2, ...
    ax3, ...
    ax4, ...
    ax5, ...
    ax6, ...
    ax7};
for kAxis = 1:numel(plotAxes)
    currentAx = ...
        plotAxes{kAxis};
    if ~strcmp(currentAx.Visible,'on')
        continue;
    end
    if TouchdownDetected
        xline( ...
            currentAx, ...
            0, ...
            '--', ...
            'Touchdown proxy', ...
            'HandleVisibility','off');
    else
        xline( ...
            currentAx, ...
            0, ...
            '--', ...
            'Attempt end', ...
            'HandleVisibility','off');
    end
    if TouchdownDetected && ...
            StableDetected && ...
            isfinite(StableTime_s)
        xline( ...
            currentAx, ...
            StableTime_s-diagnosticCenterTime_s, ...
            ':', ...
            'Stable', ...
            'HandleVisibility','off');
    end
    if TouchdownDetected && ...
            LandedArmedDetected && ...
            isfinite(LandedArmedTime_s)
        xline( ...
            currentAx, ...
            LandedArmedTime_s-diagnosticCenterTime_s, ...
            ':', ...
            'Landed armed', ...
            'HandleVisibility','off');
    end
    xlim( ...
        currentAx, ...
        [ ...
            windowStart_s-diagnosticCenterTime_s, ...
            windowEnd_s-diagnosticCenterTime_s ...
        ]);
end
allAxes = ...
    findall( ...
        fig11, ...
        'Type','axes');
for iAx = 1:numel(allAxes)
    try
        if ~isempty(allAxes(iAx).Toolbar)
            allAxes(iAx).Toolbar.Visible = ...
                'off';
        end
    catch
    end
end
drawnow;
figure11File = ...
    fullfile( ...
        REAL_FIGURES_FOLDER, ...
        '11_Touchdown_Diagnostics.png');
exportgraphics( ...
    fig11, ...
    figure11File, ...
    'Resolution',300);
writetable( ...
    TouchdownMetrics, ...
    fullfile( ...
        REAL_TABLES_FOLDER, ...
        'Touchdown_Metrics.csv'));
REAL_TOUCHDOWN_RESULTS = ...
    struct();
REAL_TOUCHDOWN_RESULTS.TouchdownDetected = ...
    TouchdownDetected;
REAL_TOUCHDOWN_RESULTS.TouchdownBasis = ...
    TouchdownBasis;
REAL_TOUCHDOWN_RESULTS.PhysicalGroundTruthAvailable = ...
    false;
REAL_TOUCHDOWN_RESULTS.ExtendedSysStateAvailable = ...
    landedStateAvailable;
REAL_TOUCHDOWN_RESULTS.AngularRateTelemetryPresent = ...
    rateTelemetryPresent;
REAL_TOUCHDOWN_RESULTS.AngularRateTelemetryInformative = ...
    rateTelemetryInformative;
REAL_TOUCHDOWN_RESULTS.AngularRateTelemetryStatus = ...
    rateTelemetryStatus;
REAL_TOUCHDOWN_RESULTS.AngularRateTelemetryReason = ...
    rateTelemetryReason;
REAL_TOUCHDOWN_RESULTS.TouchdownTime_s = ...
    TouchdownTime_s;
REAL_TOUCHDOWN_RESULTS.DiagnosticCenterTime_s = ...
    diagnosticCenterTime_s;
REAL_TOUCHDOWN_RESULTS.WindowStart_s = ...
    windowStart_s;
REAL_TOUCHDOWN_RESULTS.WindowEnd_s = ...
    windowEnd_s;
REAL_TOUCHDOWN_RESULTS.TelemetryFallbackDiagnostics = ...
    TELEMETRY_TOUCHDOWN_DIAGNOSTICS;
REAL_TOUCHDOWN_RESULTS.TouchdownMetrics = ...
    TouchdownMetrics;
REAL_TOUCHDOWN_RESULTS.Altitude = ...
    ALT_WINDOW;
REAL_TOUCHDOWN_RESULTS.Velocity = ...
    VEL_WINDOW;
REAL_TOUCHDOWN_RESULTS.Acceleration = ...
    ACC_WINDOW;
REAL_TOUCHDOWN_RESULTS.ControlAxisProxy = ...
    CONTROL_PROXY_WINDOW;
REAL_TOUCHDOWN_RESULTS.AngularRate = ...
    ATT_WINDOW;
REAL_TOUCHDOWN_RESULTS.MotorPWM = ...
    PWM_WINDOW;
if exist('pwmMin','var') && ...
        exist('pwmMax','var') && ...
        isfinite(pwmMin) && ...
        isfinite(pwmMax)
    REAL_TOUCHDOWN_RESULTS.PWMNormalizationMin_us = ...
        pwmMin;
    REAL_TOUCHDOWN_RESULTS.PWMNormalizationMax_us = ...
        pwmMax;
else
    REAL_TOUCHDOWN_RESULTS.PWMNormalizationMin_us = ...
        NaN;
    REAL_TOUCHDOWN_RESULTS.PWMNormalizationMax_us = ...
        NaN;
end
availabilitySignals = [ ...
    "TouchdownEvent"; ...
    "VerticalContactVelocity"; ...
    "ContactSpeed"; ...
    "TouchdownAcceleration"; ...
    "TouchdownMotorPWM"; ...
    "PhysicalGroundPenetration"; ...
    "PhysicalBounceHeight"];
if TouchdownDetected
    touchdownAvailabilityStatus = ...
        "DERIVED";
    velocityAvailabilityStatus = ...
        "DERIVED";
    accelerationAvailabilityStatus = ...
        "DERIVED";
    if ~isempty(PWM_WINDOW)
        pwmAvailabilityStatus = ...
            "DIRECT";
    else
        pwmAvailabilityStatus = ...
            "NOT_AVAILABLE";
    end
else
    touchdownAvailabilityStatus = ...
        "NOT_AVAILABLE";
    velocityAvailabilityStatus = ...
        "NOT_AVAILABLE";
    accelerationAvailabilityStatus = ...
        "NOT_AVAILABLE";
    pwmAvailabilityStatus = ...
        "NOT_AVAILABLE";
end
availabilityStatuses = [ ...
    touchdownAvailabilityStatus; ...
    velocityAvailabilityStatus; ...
    velocityAvailabilityStatus; ...
    accelerationAvailabilityStatus; ...
    pwmAvailabilityStatus; ...
    "NOT_AVAILABLE"; ...
    "NOT_AVAILABLE"];
availabilitySources = [ ...
    TouchdownBasis; ...
    "GLOBAL_POSITION_INT velocity"; ...
    "GLOBAL_POSITION_INT velocity"; ...
    "Derived from GLOBAL_POSITION_INT velocity"; ...
    "SERVO_OUTPUT_RAW"; ...
    "Independent physical ground position required"; ...
    "Independent physical ground/contact position required"];
availabilityUnits = [ ...
    "s"; ...
    "m/s"; ...
    "m/s"; ...
    "m/s^2"; ...
    "us"; ...
    "m"; ...
    "m"];
if TouchdownDetected
    touchdownNote = ...
        "Touchdown represented by a telemetry-derived proxy; not independent physical contact truth.";
    velocityNote = ...
        "NED velocity interpolated to the selected touchdown proxy timestamp.";
    accelerationNote = ...
        "Acceleration numerically derived from NED velocity inside the touchdown-proxy window.";
    pwmNote = ...
        "Actuator PWM directly recorded from SERVO_OUTPUT_RAW inside the touchdown-proxy window.";
else
    touchdownNote = ...
        "No defensible touchdown event could be confirmed from the available TLOG telemetry.";
    velocityNote = ...
        "Not reported because no touchdown timestamp was confirmed.";
    accelerationNote = ...
        "Terminal acceleration can be visualized, but no touchdown-specific metric is reported.";
    pwmNote = ...
        "Terminal PWM can be visualized, but no touchdown-specific metric is reported.";
end
availabilityNotes = [ ...
    touchdownNote; ...
    velocityNote; ...
    velocityNote; ...
    accelerationNote; ...
    pwmNote; ...
    "Independent physical contact geometry is unavailable."; ...
    "Independent post-contact ground-relative trajectory is unavailable."];
for k = 1:numel(availabilitySignals)
    availabilityIndex = ...
        find( ...
            REAL_DATA_AVAILABILITY.Signal == ...
            availabilitySignals(k), ...
            1);
    if isempty(availabilityIndex)
        newRow = ...
            table( ...
                availabilitySignals(k), ...
                "Touchdown", ...
                availabilityStatuses(k), ...
                availabilitySources(k), ...
                availabilityUnits(k), ...
                availabilityNotes(k), ...
                'VariableNames', ...
                REAL_DATA_AVAILABILITY.Properties.VariableNames);
        REAL_DATA_AVAILABILITY = ...
            [ ...
                REAL_DATA_AVAILABILITY; ...
                newRow ...
            ];
    else
        REAL_DATA_AVAILABILITY.Status(availabilityIndex) = ...
            availabilityStatuses(k);
        REAL_DATA_AVAILABILITY.SourceMessage(availabilityIndex) = ...
            availabilitySources(k);
        REAL_DATA_AVAILABILITY.Units(availabilityIndex) = ...
            availabilityUnits(k);
        REAL_DATA_AVAILABILITY.Notes(availabilityIndex) = ...
            availabilityNotes(k);
    end
end
writetable( ...
    REAL_DATA_AVAILABILITY, ...
    fullfile( ...
        REAL_TABLES_FOLDER, ...
        'Metric_Availability.csv'));
save( ...
    REAL_EXPERIMENT_DATA_FILE, ...
    'REAL_TOUCHDOWN_RESULTS', ...
    'TouchdownMetrics', ...
    'REAL_DATA_AVAILABILITY', ...
    '-append');
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' REAL TOUCHDOWN DIAGNOSTICS GENERATED\n');
fprintf('==============================================================\n\n');
fprintf( ...
    'EXTENDED_SYS_STATE available: %s\n', ...
    localYesNo(landedStateAvailable));
fprintf( ...
    'Touchdown detected:           %s\n', ...
    localYesNo(TouchdownDetected));
fprintf( ...
    'Touchdown basis:              %s\n', ...
    TouchdownBasis);
if TouchdownDetected
    fprintf( ...
        'Touchdown time:               %.3f s\n', ...
        TouchdownTime_s);
else
    fprintf( ...
        'Touchdown time:               NOT CONFIRMED\n');
end
if LandingPhaseDetected
    fprintf( ...
        'Landing-state start:          %.3f s\n', ...
        LandingStartTime_s);
else
    fprintf( ...
        'Landing-state start:          NOT DETECTED\n');
end
if TouchdownDetected
    fprintf( ...
        'Vertical velocity at proxy:   %.4f m/s\n', ...
        VerticalContactVelocity_m_s);
    fprintf( ...
        '3D speed at proxy:            %.4f m/s\n', ...
        ContactSpeed_m_s);
    fprintf( ...
        'Peak |vertical acceleration|: %.4f m/s^2\n', ...
        PeakVerticalAcceleration_m_s2);
    fprintf( ...
        'Peak total acceleration:      %.4f m/s^2\n', ...
        PeakTotalAcceleration_m_s2);
    if rateTelemetryInformative && ...
            isfinite(PeakAngularRate_rad_s)
        fprintf( ...
            'Peak angular-rate norm:       %.4f rad/s\n', ...
            PeakAngularRate_rad_s);
    else
        fprintf( ...
            'Peak angular-rate norm:       NOT AVAILABLE\n');
    end
    fprintf( ...
        'Peak actuator PWM:            %.0f us\n', ...
        PeakMotorPWM_us);
else
    fprintf( ...
        'Contact-specific metrics:     NOT AVAILABLE\n');
end
fprintf( ...
    'Stable proxy detected:        %s\n', ...
    string(StableDetected));
fprintf( ...
    'Landed armed detected:        %s\n', ...
    string(LandedArmedDetected));
fprintf( ...
    'Angular-rate telemetry:       %s\n', ...
    rateTelemetryStatus);
fprintf( ...
    'Angular-rate informative:     %s\n', ...
    string(rateTelemetryInformative));
if TELEMETRY_TOUCHDOWN_DIAGNOSTICS.Attempted
    fprintf('\n');
    fprintf('Telemetry fallback attempted:  true\n');
    fprintf( ...
        'Telemetry fallback result:     %s\n', ...
        localYesNo( ...
            TELEMETRY_TOUCHDOWN_DIAGNOSTICS.Detected));
    if isfield( ...
            TELEMETRY_TOUCHDOWN_DIAGNOSTICS, ...
            'Reason')
        fprintf( ...
            'Telemetry fallback reason:     %s\n', ...
            TELEMETRY_TOUCHDOWN_DIAGNOSTICS.Reason);
    end
end
fprintf('\n');
fprintf('Physical rotor speed:          NOT AVAILABLE\n');
fprintf('Physical contact ground truth: NOT AVAILABLE\n');
fprintf('Ground penetration:            NOT AVAILABLE\n');
fprintf('Bounce height:                 NOT AVAILABLE\n');
fprintf('\n');
fprintf('Files generated / updated:\n');
fprintf('  - 11_Touchdown_Diagnostics.png\n');
fprintf('  - Touchdown_Metrics.csv\n');
fprintf('  - Metric_Availability.csv\n');
fprintf('  - experiment_data.mat\n');
fprintf('\n');
fprintf('==============================================================\n');
function [detected,touchdownTime_s,diagnostics] = ...
    detectTelemetryTouchdownProxy( ...
        REAL_DATA, ...
        attemptStart_s, ...
        attemptEnd_s, ...
        F)
    detected = ...
        false;
    touchdownTime_s = ...
        NaN;
    diagnostics = ...
        struct();
    diagnostics.Attempted = ...
        true;
    diagnostics.Detected = ...
        false;
    diagnostics.Reason = ...
        "NO_VALID_TERMINAL_STABILITY_INTERVAL";
    diagnostics.VelocityAvailable = ...
        false;
    diagnostics.AltitudeAvailable = ...
        false;
    diagnostics.AttitudeAvailable = ...
        false;
    diagnostics.AngularRateAvailable = ...
        false;
    diagnostics.AngularRateInformative = ...
        false;
    diagnostics.AngularRateReason = ...
        "NOT_EVALUATED";
    diagnostics.TerminalAltitude_m = ...
        NaN;
    diagnostics.TerminalMedianSpeed_m_s = ...
        NaN;
    diagnostics.TerminalMedianVerticalSpeed_m_s = ...
        NaN;
    diagnostics.CandidateStartTime_s = ...
        NaN;
    diagnostics.SearchStartTime_s = ...
        max( ...
            attemptStart_s, ...
            attemptEnd_s - F.SearchTail_s);
    diagnostics.SearchEndTime_s = ...
        attemptEnd_s;
    if ~isfield(REAL_DATA,'State') || ...
            ~isfield(REAL_DATA.State,'VelocityNED') || ...
            isempty(REAL_DATA.State.VelocityNED)
        diagnostics.Reason = ...
            "VELOCITY_UNAVAILABLE";
        return;
    end
    VEL = ...
        REAL_DATA.State.VelocityNED;
    [tVel,vN,vE,vD] = ...
        sanitizeTimeSeries( ...
            double(VEL.Time_s), ...
            double(VEL.North_m_s), ...
            double(VEL.East_m_s), ...
            double(VEL.Down_m_s));
    if numel(tVel) < 5
        diagnostics.Reason = ...
            "INSUFFICIENT_VELOCITY_SAMPLES";
        return;
    end
    diagnostics.VelocityAvailable = ...
        true;
    searchMask = ...
        tVel >= diagnostics.SearchStartTime_s & ...
        tVel <= diagnostics.SearchEndTime_s;
    if nnz(searchMask) < 5
        diagnostics.Reason = ...
            "INSUFFICIENT_TERMINAL_VELOCITY_SUPPORT";
        return;
    end
    tEval = ...
        tVel(searchMask);
    vNEval = ...
        vN(searchMask);
    vEEval = ...
        vE(searchMask);
    vDEval = ...
        vD(searchMask);
    speedEval = ...
        sqrt( ...
            vNEval.^2 + ...
            vEEval.^2 + ...
            vDEval.^2);
    if ~isfield(REAL_DATA.State,'GlobalPosition') || ...
            isempty(REAL_DATA.State.GlobalPosition)
        diagnostics.Reason = ...
            "RELATIVE_ALTITUDE_UNAVAILABLE";
        return;
    end
    GP = ...
        REAL_DATA.State.GlobalPosition;
    [tAlt,relativeAltitude] = ...
        sanitizeTimeSeries( ...
            double(GP.Time_s), ...
            double(GP.RelativeAltitude_m));
    if numel(tAlt) < 2
        diagnostics.Reason = ...
            "INSUFFICIENT_ALTITUDE_SAMPLES";
        return;
    end
    diagnostics.AltitudeAvailable = ...
        true;
    terminalBaselineStart_s = ...
        max( ...
            attemptStart_s, ...
            attemptEnd_s - F.TerminalBaselineWindow_s);
    terminalAltitudeMask = ...
        tAlt >= terminalBaselineStart_s & ...
        tAlt <= attemptEnd_s & ...
        isfinite(relativeAltitude);
    if nnz(terminalAltitudeMask) < 2
        diagnostics.Reason = ...
            "TERMINAL_ALTITUDE_BASELINE_UNAVAILABLE";
        return;
    end
    terminalAltitude_m = ...
        median( ...
            relativeAltitude(terminalAltitudeMask), ...
            'omitnan');
    diagnostics.TerminalAltitude_m = ...
        terminalAltitude_m;
    altitudeEval = ...
        safeInterpLinear( ...
            tAlt, ...
            relativeAltitude, ...
            tEval);
    terminalVelocityMask = ...
        tEval >= terminalBaselineStart_s & ...
        tEval <= attemptEnd_s;
    if nnz(terminalVelocityMask) < 2
        diagnostics.Reason = ...
            "TERMINAL_VELOCITY_BASELINE_UNAVAILABLE";
        return;
    end
    diagnostics.TerminalMedianSpeed_m_s = ...
        median( ...
            speedEval(terminalVelocityMask), ...
            'omitnan');
    diagnostics.TerminalMedianVerticalSpeed_m_s = ...
        median( ...
            abs(vDEval(terminalVelocityMask)), ...
            'omitnan');
    if ~isfinite(diagnostics.TerminalMedianSpeed_m_s) || ...
            diagnostics.TerminalMedianSpeed_m_s > F.MaxSpeed_m_s
        diagnostics.Reason = ...
            "LOG_END_NOT_TRANSLATIONALLY_STABLE";
        return;
    end
    if ~isfinite(diagnostics.TerminalMedianVerticalSpeed_m_s) || ...
            diagnostics.TerminalMedianVerticalSpeed_m_s > ...
            F.MaxVerticalSpeed_m_s
        diagnostics.Reason = ...
            "LOG_END_NOT_VERTICALLY_STABLE";
        return;
    end
    stableCondition = ...
        isfinite(speedEval) & ...
        isfinite(vDEval) & ...
        isfinite(altitudeEval) & ...
        speedEval <= F.MaxSpeed_m_s & ...
        abs(vDEval) <= F.MaxVerticalSpeed_m_s & ...
        abs(altitudeEval-terminalAltitude_m) <= ...
        F.MaxAltitudeDeviation_m;
    if isfield(REAL_DATA.State,'Attitude') && ...
            ~isempty(REAL_DATA.State.Attitude)
        ATT = ...
            REAL_DATA.State.Attitude;
        [tAtt,rollRad,pitchRad] = ...
            sanitizeTimeSeries( ...
                double(ATT.Time_s), ...
                double(ATT.Roll_rad), ...
                double(ATT.Pitch_rad));
        if numel(tAtt) >= 2
            rollEval = ...
                rad2deg( ...
                    safeInterpLinear( ...
                        tAtt, ...
                        rollRad, ...
                        tEval));
            pitchEval = ...
                rad2deg( ...
                    safeInterpLinear( ...
                        tAtt, ...
                        pitchRad, ...
                        tEval));
            attitudeFinite = ...
                isfinite(rollEval) & ...
                isfinite(pitchEval);
            if any(attitudeFinite)
                diagnostics.AttitudeAvailable = ...
                    true;
                stableCondition = ...
                    stableCondition & ...
                    ( ...
                        ~attitudeFinite | ...
                        ( ...
                            abs(rollEval) <= F.MaxRoll_deg & ...
                            abs(pitchEval) <= F.MaxPitch_deg ...
                        ) ...
                    );
            end
        end
    end
    if isfield(REAL_DATA.State,'AngularRate') && ...
            ~isempty(REAL_DATA.State.AngularRate)
        RATE = ...
            REAL_DATA.State.AngularRate;
        [tRate,pRate,qRate,rRate] = ...
            sanitizeTimeSeries( ...
                double(RATE.Time_s), ...
                double(RATE.P_rad_s), ...
                double(RATE.Q_rad_s), ...
                double(RATE.R_rad_s));
        if numel(tRate) >= 2
            diagnostics.AngularRateAvailable = ...
                true;
            maximumAbsoluteRate_rad_s = ...
                max( ...
                    abs( ...
                        [ ...
                            pRate; ...
                            qRate; ...
                            rRate ...
                        ]), ...
                    [], ...
                    'omitnan');
            if isfinite(maximumAbsoluteRate_rad_s) && ...
                    maximumAbsoluteRate_rad_s > ...
                    F.RateZeroTolerance_rad_s
                diagnostics.AngularRateInformative = ...
                    true;
                diagnostics.AngularRateReason = ...
                    "DYNAMIC_RATE_INFORMATION_AVAILABLE";
                rateMagnitude = ...
                    sqrt( ...
                        pRate.^2 + ...
                        qRate.^2 + ...
                        rRate.^2);
                rateEval = ...
                    safeInterpLinear( ...
                        tRate, ...
                        rateMagnitude, ...
                        tEval);
                rateFinite = ...
                    isfinite(rateEval);
                if any(rateFinite)
                    stableCondition = ...
                        stableCondition & ...
                        ( ...
                            ~rateFinite | ...
                            rateEval <= F.MaxAngularRate_rad_s ...
                        );
                end
            else
                diagnostics.AngularRateInformative = ...
                    false;
                diagnostics.AngularRateReason = ...
                    "CONSTANT_ZERO_NON_INFORMATIVE";
            end
        else
            diagnostics.AngularRateReason = ...
                "INSUFFICIENT_RATE_SAMPLES";
        end
    else
        diagnostics.AngularRateReason = ...
            "ANGULAR_RATE_TELEMETRY_NOT_PRESENT";
    end
    stableStartIndex = ...
        firstPersistentDurationReal( ...
            stableCondition, ...
            tEval, ...
            F.MinimumStableDuration_s);
    if isempty(stableStartIndex)
        diagnostics.Reason = ...
            "NO_PERSISTENT_TERMINAL_STABILITY_INTERVAL";
        return;
    end
    touchdownTime_s = ...
        tEval(stableStartIndex);
    detected = ...
        true;
    diagnostics.Detected = ...
        true;
    diagnostics.CandidateStartTime_s = ...
        touchdownTime_s;
    diagnostics.Reason = ...
        "PERSISTENT_TERMINAL_STABILITY_NEAR_TERMINAL_ALTITUDE";
end
function varargout = sanitizeTimeSeries(time_s,varargin)
    time_s = ...
        double(time_s(:));
    n = ...
        numel(time_s);
    validTime = ...
        isfinite(time_s);
    time_s = ...
        time_s(validTime);
    data = ...
        cell(size(varargin));
    for i = 1:numel(varargin)
        x = ...
            varargin{i};
        x = ...
            x(:);
        if numel(x) ~= n
            error( ...
                'RealFlight:TimeSeriesSizeMismatch', ...
                'Time and data vectors must have equal lengths.');
        end
        data{i} = ...
            x(validTime);
    end
    [time_s,sortIndex] = ...
        sort(time_s);
    for i = 1:numel(data)
        data{i} = ...
            data{i}(sortIndex);
    end
    [time_s,uniqueIndex] = ...
        unique( ...
            time_s, ...
            'last');
    for i = 1:numel(data)
        data{i} = ...
            data{i}(uniqueIndex);
    end
    varargout = ...
        cell(1,1+numel(data));
    varargout{1} = ...
        time_s;
    for i = 1:numel(data)
        varargout{i+1} = ...
            data{i};
    end
end
function yq = safeInterpLinear(time_s,data,queryTime)
    [time_s,data] = ...
        sanitizeTimeSeries( ...
            time_s, ...
            data);
    if numel(time_s) < 2
        yq = ...
            NaN(size(queryTime));
        return;
    end
    yq = ...
        interp1( ...
            time_s, ...
            double(data), ...
            queryTime, ...
            'linear', ...
            NaN);
end
function yq = safeInterpPrevious(time_s,data,queryTime)
    [time_s,data] = ...
        sanitizeTimeSeries( ...
            time_s, ...
            data);
    if isempty(time_s)
        yq = ...
            NaN(size(queryTime));
        return;
    end
    if numel(time_s) == 1
        yq = ...
            NaN(size(queryTime));
        valid = ...
            queryTime >= time_s(1);
        yq(valid) = ...
            data(1);
        return;
    end
    yq = ...
        interp1( ...
            time_s, ...
            double(data), ...
            queryTime, ...
            'previous', ...
            NaN);
end
function firstIndex = firstPersistentDurationReal( ...
    condition, ...
    time_s, ...
    duration_s)
    firstIndex = ...
        [];
    condition = ...
        logical(condition(:));
    time_s = ...
        double(time_s(:));
    n = ...
        numel(condition);
    for i = 1:n
        if ~condition(i)
            continue;
        end
        j = ...
            i;
        while j < n && ...
                condition(j+1)
            j = ...
                j + 1;
        end
        if time_s(j) - ...
                time_s(i) >= duration_s
            firstIndex = ...
                i;
            return;
        end
    end
end
function textValue = localYesNo(value)
    if logical(value)
        textValue = ...
            'YES';
    else
        textValue = ...
            'NO';
    end
end
