RATE_ZERO_TOL_RAD_S = ...
    1.0e-10;
requiredVariables = { ...
    'REAL_DATA', ...
    'REAL_FLIGHT_INSPECTION', ...
    'REAL_FIGURES_FOLDER', ...
    'REAL_TABLES_FOLDER', ...
    'REAL_EXPERIMENT_DATA_FILE', ...
    'REAL_DATA_AVAILABILITY'};
for k = 1:numel(requiredVariables)
    if ~exist(requiredVariables{k},'var')
        error( ...
            'RealFlight:MissingRequiredVariable', ...
            ['Required variable "%s" was not found.\n\n', ...
             'Run the previous real-flight processing scripts first.'], ...
            requiredVariables{k});
    end
end
rateTelemetryPresent = ...
    isfield(REAL_DATA,'State') && ...
    isfield(REAL_DATA.State,'AngularRate') && ...
    ~isempty(REAL_DATA.State.AngularRate);
if exist('REAL_TRAJECTORY_RESULTS','var') && ...
        isfield(REAL_TRAJECTORY_RESULTS,'StartTime_s') && ...
        isfinite(REAL_TRAJECTORY_RESULTS.StartTime_s)
    trackingStart_s = ...
        REAL_TRAJECTORY_RESULTS.StartTime_s;
    trackingEnd_s = ...
        REAL_TRAJECTORY_RESULTS.EndTime_s;
    trackingWindowSource = ...
        "TRAJECTORY_PHYSICAL_WINDOW";
else
    trackingStart_s = ...
        REAL_FLIGHT_INSPECTION.CoreStartTime_s;
    trackingEnd_s = ...
        REAL_FLIGHT_INSPECTION.CoreEndTime_s;
    trackingWindowSource = ...
        "PRIMARY_ATTEMPT_WINDOW";
end
trackingDuration_s = ...
    trackingEnd_s - ...
    trackingStart_s;
if ~isfinite(trackingStart_s) || ...
        ~isfinite(trackingEnd_s) || ...
        trackingEnd_s <= trackingStart_s
    error( ...
        'RealFlight:InvalidAngularRateWindow', ...
        'The angular-rate analysis window is invalid.');
end
tAbsolute = ...
    zeros(0,1);
t = ...
    zeros(0,1);
p_rad_s = ...
    zeros(0,1);
q_rad_s = ...
    zeros(0,1);
r_rad_s = ...
    zeros(0,1);
rateTelemetryInformative = ...
    false;
rateTelemetryStatus = ...
    "NOT_AVAILABLE";
rateTelemetryReason = ...
    "ANGULAR_RATE_TELEMETRY_NOT_PRESENT";
constantZeroTelemetry = ...
    false;
validRateSampleCount = ...
    0;
if rateTelemetryPresent
    RATE = ...
        REAL_DATA.State.AngularRate;
    mask = ...
        RATE.Time_s >= trackingStart_s & ...
        RATE.Time_s <= trackingEnd_s;
    if nnz(mask) >= 2
        tAbsolute = ...
            double( ...
                RATE.Time_s(mask));
        p_rad_s = ...
            double( ...
                RATE.P_rad_s(mask));
        q_rad_s = ...
            double( ...
                RATE.Q_rad_s(mask));
        r_rad_s = ...
            double( ...
                RATE.R_rad_s(mask));
        [tAbsolute,order] = ...
            sort(tAbsolute);
        p_rad_s = ...
            p_rad_s(order);
        q_rad_s = ...
            q_rad_s(order);
        r_rad_s = ...
            r_rad_s(order);
        [tAbsolute,uniqueIndex] = ...
            unique( ...
                tAbsolute, ...
                'stable');
        p_rad_s = ...
            p_rad_s(uniqueIndex);
        q_rad_s = ...
            q_rad_s(uniqueIndex);
        r_rad_s = ...
            r_rad_s(uniqueIndex);
        validRows = ...
            isfinite(tAbsolute) & ...
            isfinite(p_rad_s) & ...
            isfinite(q_rad_s) & ...
            isfinite(r_rad_s);
        tAbsolute = ...
            tAbsolute(validRows);
        p_rad_s = ...
            p_rad_s(validRows);
        q_rad_s = ...
            q_rad_s(validRows);
        r_rad_s = ...
            r_rad_s(validRows);
        validRateSampleCount = ...
            numel(tAbsolute);
        if validRateSampleCount >= 2
            t = ...
                tAbsolute - ...
                trackingStart_s;
            maximumAbsoluteRecordedRate_rad_s = ...
                max( ...
                    abs( ...
                        [ ...
                            p_rad_s; ...
                            q_rad_s; ...
                            r_rad_s ...
                        ]), ...
                    [], ...
                    'omitnan');
            constantZeroTelemetry = ...
                isfinite(maximumAbsoluteRecordedRate_rad_s) && ...
                maximumAbsoluteRecordedRate_rad_s <= ...
                RATE_ZERO_TOL_RAD_S;
            if constantZeroTelemetry
                rateTelemetryInformative = ...
                    false;
                rateTelemetryStatus = ...
                    "NON_INFORMATIVE_CONSTANT_ZERO";
                rateTelemetryReason = ...
                    "ATTITUDE_RATE_FIELDS_CONSTANT_ZERO_DURING_FLIGHT_WINDOW";
            else
                rateTelemetryInformative = ...
                    true;
                rateTelemetryStatus = ...
                    "DIRECT_INFORMATIVE";
                rateTelemetryReason = ...
                    "ATTITUDE_RATE_FIELDS_CONTAIN_DYNAMIC_INFORMATION";
            end
        else
            rateTelemetryStatus = ...
                "NOT_AVAILABLE";
            rateTelemetryReason = ...
                "INSUFFICIENT_VALID_ANGULAR_RATE_SAMPLES";
        end
    else
        rateTelemetryStatus = ...
            "NOT_AVAILABLE";
        rateTelemetryReason = ...
            "INSUFFICIENT_ANGULAR_RATE_SAMPLES_IN_FLIGHT_WINDOW";
    end
end
if rateTelemetryInformative
    pRMS_rad_s = ...
        sqrt( ...
            mean( ...
                p_rad_s.^2, ...
                'omitnan'));
    qRMS_rad_s = ...
        sqrt( ...
            mean( ...
                q_rad_s.^2, ...
                'omitnan'));
    rRMS_rad_s = ...
        sqrt( ...
            mean( ...
                r_rad_s.^2, ...
                'omitnan'));
    pPeakAbs_rad_s = ...
        max( ...
            abs(p_rad_s), ...
            [], ...
            'omitnan');
    qPeakAbs_rad_s = ...
        max( ...
            abs(q_rad_s), ...
            [], ...
            'omitnan');
    rPeakAbs_rad_s = ...
        max( ...
            abs(r_rad_s), ...
            [], ...
            'omitnan');
else
    pRMS_rad_s = ...
        NaN;
    qRMS_rad_s = ...
        NaN;
    rRMS_rad_s = ...
        NaN;
    pPeakAbs_rad_s = ...
        NaN;
    qPeakAbs_rad_s = ...
        NaN;
    rPeakAbs_rad_s = ...
        NaN;
end
pTrackingRMSE_rad_s = ...
    NaN;
qTrackingRMSE_rad_s = ...
    NaN;
rTrackingRMSE_rad_s = ...
    NaN;
MaxAbsPCommand_rad_s = ...
    NaN;
MaxAbsQCommand_rad_s = ...
    NaN;
MaxAbsRCommand_rad_s = ...
    NaN;
REAL_ANGULAR_RATE_DATA = ...
    table( ...
        tAbsolute, ...
        t, ...
        p_rad_s, ...
        q_rad_s, ...
        r_rad_s, ...
        'VariableNames', { ...
            'TLOG_Time_s', ...
            'FlightTime_s', ...
            'P_rad_s', ...
            'Q_rad_s', ...
            'R_rad_s'});
delete( ...
    findall( ...
        groot, ...
        'Type','figure', ...
        'Tag','RealFlight_AngularRateTracking'));
fig09 = ...
    figure( ...
        'Name','09 - Real UAV Angular Rate Tracking', ...
        'Tag','RealFlight_AngularRateTracking', ...
        'Color','w', ...
        'NumberTitle','off');
tl09 = ...
    tiledlayout( ...
        fig09, ...
        3, ...
        1, ...
        'TileSpacing','compact', ...
        'Padding','compact');
if rateTelemetryInformative
    title( ...
        tl09, ...
        ['REAL UAV Angular Rates — commands unavailable ', ...
         'in current TLOG']);
elseif constantZeroTelemetry
    title( ...
        tl09, ...
        ['REAL UAV Angular Rates — ATTITUDE rate fields are ', ...
         'NON-INFORMATIVE (constant zero)']);
else
    title( ...
        tl09, ...
        'REAL UAV Angular Rates — telemetry NOT AVAILABLE');
end
ax1 = ...
    nexttile(tl09);
if ~isempty(t)
    plot( ...
        ax1, ...
        t, ...
        p_rad_s, ...
        'LineWidth',1.3, ...
        'DisplayName','Raw TLOG');
    yline( ...
        ax1, ...
        0, ...
        ':', ...
        'HandleVisibility','off');
    grid(ax1,'on');
    box(ax1,'on');
    ylabel( ...
        ax1, ...
        'p [rad/s]');
    if rateTelemetryInformative
        title( ...
            ax1, ...
            sprintf( ...
                ['Roll Rate p — command NOT AVAILABLE ', ...
                 '| RMS %.3f rad/s'], ...
                pRMS_rad_s));
    else
        title( ...
            ax1, ...
            'Roll Rate p — NON-INFORMATIVE / metric NOT AVAILABLE');
    end
    legend( ...
        ax1, ...
        'Location','best');
    xlim( ...
        ax1, ...
        [0 trackingDuration_s]);
else
    axis(ax1,'off');
    text( ...
        ax1, ...
        0.5, ...
        0.5, ...
        'p telemetry NOT AVAILABLE', ...
        'Units','normalized', ...
        'HorizontalAlignment','center');
end
ax2 = ...
    nexttile(tl09);
if ~isempty(t)
    plot( ...
        ax2, ...
        t, ...
        q_rad_s, ...
        'LineWidth',1.3, ...
        'DisplayName','Raw TLOG');
    yline( ...
        ax2, ...
        0, ...
        ':', ...
        'HandleVisibility','off');
    grid(ax2,'on');
    box(ax2,'on');
    ylabel( ...
        ax2, ...
        'q [rad/s]');
    if rateTelemetryInformative
        title( ...
            ax2, ...
            sprintf( ...
                ['Pitch Rate q — command NOT AVAILABLE ', ...
                 '| RMS %.3f rad/s'], ...
                qRMS_rad_s));
    else
        title( ...
            ax2, ...
            'Pitch Rate q — NON-INFORMATIVE / metric NOT AVAILABLE');
    end
    legend( ...
        ax2, ...
        'Location','best');
    xlim( ...
        ax2, ...
        [0 trackingDuration_s]);
else
    axis(ax2,'off');
    text( ...
        ax2, ...
        0.5, ...
        0.5, ...
        'q telemetry NOT AVAILABLE', ...
        'Units','normalized', ...
        'HorizontalAlignment','center');
end
ax3 = ...
    nexttile(tl09);
if ~isempty(t)
    plot( ...
        ax3, ...
        t, ...
        r_rad_s, ...
        'LineWidth',1.3, ...
        'DisplayName','Raw TLOG');
    yline( ...
        ax3, ...
        0, ...
        ':', ...
        'HandleVisibility','off');
    grid(ax3,'on');
    box(ax3,'on');
    ylabel( ...
        ax3, ...
        'r [rad/s]');
    xlabel( ...
        ax3, ...
        'Time [s]');
    if rateTelemetryInformative
        title( ...
            ax3, ...
            sprintf( ...
                ['Yaw Rate r — command NOT AVAILABLE ', ...
                 '| RMS %.3f rad/s'], ...
                rRMS_rad_s));
    else
        title( ...
            ax3, ...
            'Yaw Rate r — NON-INFORMATIVE / metric NOT AVAILABLE');
    end
    legend( ...
        ax3, ...
        'Location','best');
    xlim( ...
        ax3, ...
        [0 trackingDuration_s]);
else
    axis(ax3,'off');
    text( ...
        ax3, ...
        0.5, ...
        0.5, ...
        'r telemetry NOT AVAILABLE', ...
        'Units','normalized', ...
        'HorizontalAlignment','center');
end
allAxes = ...
    findall( ...
        fig09, ...
        'Type','axes');
for iAx = 1:numel(allAxes)
    try
        if ~isempty(allAxes(iAx).Toolbar)
            allAxes(iAx).Toolbar.Visible = ...
                'off';
        end
    catch
    end
end
drawnow;
figure09File = ...
    fullfile( ...
        REAL_FIGURES_FOLDER, ...
        '09_Angular_Rate_Tracking.png');
exportgraphics( ...
    fig09, ...
    figure09File, ...
    'Resolution',300);
if exist('ControllerDiagnostics','var') && ...
        istable(ControllerDiagnostics)
else
    diagnosticsFile = ...
        fullfile( ...
            REAL_TABLES_FOLDER, ...
            'Controller_Diagnostics.csv');
    if isfile(diagnosticsFile)
        ControllerDiagnostics = ...
            readtable( ...
                diagnosticsFile, ...
                'TextType','string');
    end
end
if exist('ControllerDiagnostics','var') && ...
        istable(ControllerDiagnostics)
    if ismember( ...
            'pSelectedTrackingRMSE_rad_s', ...
            ControllerDiagnostics.Properties.VariableNames)
        ControllerDiagnostics.pSelectedTrackingRMSE_rad_s(:) = ...
            NaN;
    end
    if ismember( ...
            'qSelectedTrackingRMSE_rad_s', ...
            ControllerDiagnostics.Properties.VariableNames)
        ControllerDiagnostics.qSelectedTrackingRMSE_rad_s(:) = ...
            NaN;
    end
    if ismember( ...
            'rSelectedTrackingRMSE_rad_s', ...
            ControllerDiagnostics.Properties.VariableNames)
        ControllerDiagnostics.rSelectedTrackingRMSE_rad_s(:) = ...
            NaN;
    end
    if ismember( ...
            'MaxAbsPCommand_rad_s', ...
            ControllerDiagnostics.Properties.VariableNames)
        ControllerDiagnostics.MaxAbsPCommand_rad_s(:) = ...
            NaN;
    end
    if ismember( ...
            'MaxAbsQCommand_rad_s', ...
            ControllerDiagnostics.Properties.VariableNames)
        ControllerDiagnostics.MaxAbsQCommand_rad_s(:) = ...
            NaN;
    end
    if ismember( ...
            'MaxAbsRCommand_rad_s', ...
            ControllerDiagnostics.Properties.VariableNames)
        ControllerDiagnostics.MaxAbsRCommand_rad_s(:) = ...
            NaN;
    end
    ControllerDiagnostics.AngularRateCommandAvailable = ...
        false;
    ControllerDiagnostics.AngularRateTelemetryPresent = ...
        rateTelemetryPresent;
    ControllerDiagnostics.AngularRateTelemetryInformative = ...
        rateTelemetryInformative;
    ControllerDiagnostics.AngularRateTelemetryStatus = ...
        rateTelemetryStatus;
    ControllerDiagnostics.AngularRateTelemetryReason = ...
        rateTelemetryReason;
    ControllerDiagnostics.AngularRateStateSource = ...
        "ATTITUDE";
    ControllerDiagnostics.MeasuredPRMS_rad_s = ...
        pRMS_rad_s;
    ControllerDiagnostics.MeasuredQRMS_rad_s = ...
        qRMS_rad_s;
    ControllerDiagnostics.MeasuredRRMS_rad_s = ...
        rRMS_rad_s;
    ControllerDiagnostics.PeakAbsPMeasured_rad_s = ...
        pPeakAbs_rad_s;
    ControllerDiagnostics.PeakAbsQMeasured_rad_s = ...
        qPeakAbs_rad_s;
    ControllerDiagnostics.PeakAbsRMeasured_rad_s = ...
        rPeakAbs_rad_s;
    writetable( ...
        ControllerDiagnostics, ...
        fullfile( ...
            REAL_TABLES_FOLDER, ...
            'Controller_Diagnostics.csv'));
else
    warning( ...
        'RealFlight:ControllerDiagnosticsUnavailable', ...
        ['Controller_Diagnostics.csv could not be updated, ', ...
         'but angular-rate availability was documented.']);
end
REAL_ANGULAR_RATE_RESULTS = ...
    struct();
REAL_ANGULAR_RATE_RESULTS.WindowSource = ...
    trackingWindowSource;
REAL_ANGULAR_RATE_RESULTS.StartTime_s = ...
    trackingStart_s;
REAL_ANGULAR_RATE_RESULTS.EndTime_s = ...
    trackingEnd_s;
REAL_ANGULAR_RATE_RESULTS.Duration_s = ...
    trackingDuration_s;
REAL_ANGULAR_RATE_RESULTS.StateSource = ...
    "ATTITUDE";
REAL_ANGULAR_RATE_RESULTS.TelemetryPresent = ...
    rateTelemetryPresent;
REAL_ANGULAR_RATE_RESULTS.TelemetryInformative = ...
    rateTelemetryInformative;
REAL_ANGULAR_RATE_RESULTS.TelemetryStatus = ...
    rateTelemetryStatus;
REAL_ANGULAR_RATE_RESULTS.TelemetryReason = ...
    rateTelemetryReason;
REAL_ANGULAR_RATE_RESULTS.ConstantZeroTelemetry = ...
    constantZeroTelemetry;
REAL_ANGULAR_RATE_RESULTS.ZeroTolerance_rad_s = ...
    RATE_ZERO_TOL_RAD_S;
REAL_ANGULAR_RATE_RESULTS.ValidSampleCount = ...
    validRateSampleCount;
REAL_ANGULAR_RATE_RESULTS.CommandAvailable = ...
    false;
REAL_ANGULAR_RATE_RESULTS.pTrackingRMSE_rad_s = ...
    pTrackingRMSE_rad_s;
REAL_ANGULAR_RATE_RESULTS.qTrackingRMSE_rad_s = ...
    qTrackingRMSE_rad_s;
REAL_ANGULAR_RATE_RESULTS.rTrackingRMSE_rad_s = ...
    rTrackingRMSE_rad_s;
REAL_ANGULAR_RATE_RESULTS.pRMS_rad_s = ...
    pRMS_rad_s;
REAL_ANGULAR_RATE_RESULTS.qRMS_rad_s = ...
    qRMS_rad_s;
REAL_ANGULAR_RATE_RESULTS.rRMS_rad_s = ...
    rRMS_rad_s;
REAL_ANGULAR_RATE_RESULTS.pPeakAbs_rad_s = ...
    pPeakAbs_rad_s;
REAL_ANGULAR_RATE_RESULTS.qPeakAbs_rad_s = ...
    qPeakAbs_rad_s;
REAL_ANGULAR_RATE_RESULTS.rPeakAbs_rad_s = ...
    rPeakAbs_rad_s;
REAL_ANGULAR_RATE_RESULTS.Data = ...
    REAL_ANGULAR_RATE_DATA;
availabilitySignals = [ ...
    "AngularRateState"; ...
    "AngularRateCommand"; ...
    "AngularRateTracking"];
if rateTelemetryInformative
    angularRateStateStatus = ...
        "DIRECT";
    angularRateStateSource = ...
        "ATTITUDE";
    angularRateStateNote = ...
        ['Measured/estimated body angular rates p/q/r are directly ', ...
         'available and contain dynamic information.'];
elseif rateTelemetryPresent && ...
        constantZeroTelemetry
    angularRateStateStatus = ...
        "NON_INFORMATIVE";
    angularRateStateSource = ...
        "ATTITUDE";
    angularRateStateNote = ...
        ['ATTITUDE p/q/r fields are present but constant zero over the ', ...
         'selected physical-flight window; they are not used as real ', ...
         'angular-rate performance metrics.'];
else
    angularRateStateStatus = ...
        "NOT_AVAILABLE";
    angularRateStateSource = ...
        "ATTITUDE";
    angularRateStateNote = ...
        ['No sufficient informative p/q/r angular-rate telemetry exists ', ...
         'inside the selected physical-flight window.'];
end
availabilityStatuses = [ ...
    angularRateStateStatus; ...
    "NOT_AVAILABLE"; ...
    "NOT_AVAILABLE"];
availabilitySources = [ ...
    angularRateStateSource; ...
    "No equivalent message in current TLOG"; ...
    "Angular-rate command required"];
availabilityUnits = [ ...
    "rad/s"; ...
    "rad/s"; ...
    "rad/s"];
availabilityNotes = [ ...
    angularRateStateNote; ...
    "Equivalent p/q/r controller commands are not present in the TLOG."; ...
    ['Tracking error cannot be calculated without angular-rate commands; ', ...
     'constant-zero state telemetry is also not interpreted as perfect tracking.']];
for k = 1:numel(availabilitySignals)
    availabilityIndex = ...
        find( ...
            REAL_DATA_AVAILABILITY.Signal == ...
            availabilitySignals(k), ...
            1);
    if isempty(availabilityIndex)
        newRow = ...
            table( ...
                availabilitySignals(k), ...
                "Controller", ...
                availabilityStatuses(k), ...
                availabilitySources(k), ...
                availabilityUnits(k), ...
                availabilityNotes(k), ...
                'VariableNames', ...
                REAL_DATA_AVAILABILITY.Properties.VariableNames);
        REAL_DATA_AVAILABILITY = ...
            [ ...
                REAL_DATA_AVAILABILITY; ...
                newRow ...
            ];
    else
        REAL_DATA_AVAILABILITY.Status(availabilityIndex) = ...
            availabilityStatuses(k);
        REAL_DATA_AVAILABILITY.SourceMessage(availabilityIndex) = ...
            availabilitySources(k);
        REAL_DATA_AVAILABILITY.Units(availabilityIndex) = ...
            availabilityUnits(k);
        REAL_DATA_AVAILABILITY.Notes(availabilityIndex) = ...
            availabilityNotes(k);
    end
end
writetable( ...
    REAL_DATA_AVAILABILITY, ...
    fullfile( ...
        REAL_TABLES_FOLDER, ...
        'Metric_Availability.csv'));
save( ...
    REAL_EXPERIMENT_DATA_FILE, ...
    'REAL_ANGULAR_RATE_RESULTS', ...
    'REAL_ANGULAR_RATE_DATA', ...
    'REAL_DATA_AVAILABILITY', ...
    '-append');
if exist('ControllerDiagnostics','var') && ...
        istable(ControllerDiagnostics)
    save( ...
        REAL_EXPERIMENT_DATA_FILE, ...
        'ControllerDiagnostics', ...
        '-append');
end
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' REAL ANGULAR RATE RESULTS GENERATED\n');
fprintf('==============================================================\n\n');
fprintf( ...
    'Tracking window source:       %s\n', ...
    trackingWindowSource);
fprintf( ...
    'Duration:                     %.3f s\n', ...
    trackingDuration_s);
fprintf( ...
    'Raw samples preserved:        %d\n', ...
    height(REAL_ANGULAR_RATE_DATA));
fprintf( ...
    'Angular-rate telemetry:       %s\n', ...
    rateTelemetryStatus);
fprintf( ...
    'Telemetry informative:        %s\n', ...
    string(rateTelemetryInformative));
fprintf( ...
    'Reason:                       %s\n', ...
    rateTelemetryReason);
fprintf('\n');
if rateTelemetryInformative
    fprintf( ...
        'p RMS:                        %.4f rad/s\n', ...
        pRMS_rad_s);
    fprintf( ...
        'q RMS:                        %.4f rad/s\n', ...
        qRMS_rad_s);
    fprintf( ...
        'r RMS:                        %.4f rad/s\n', ...
        rRMS_rad_s);
    fprintf('\n');
    fprintf( ...
        'Peak |p|:                     %.4f rad/s\n', ...
        pPeakAbs_rad_s);
    fprintf( ...
        'Peak |q|:                     %.4f rad/s\n', ...
        qPeakAbs_rad_s);
    fprintf( ...
        'Peak |r|:                     %.4f rad/s\n', ...
        rPeakAbs_rad_s);
else
    fprintf('Measured p/q/r RMS:         NOT AVAILABLE\n');
    fprintf('Measured p/q/r peaks:       NOT AVAILABLE\n');
end
fprintf('\n');
fprintf('Angular-rate command available: false\n');
fprintf('p/q/r tracking RMSE:            NOT AVAILABLE\n');
if constantZeroTelemetry
    fprintf( ...
        ['Interpretation:                ATTITUDE p/q/r fields are ', ...
         'constant zero and are NOT treated as perfect flight performance.\n']);
end
fprintf('\n');
fprintf('Files generated / updated:\n');
fprintf('  - 09_Angular_Rate_Tracking.png\n');
fprintf('  - Controller_Diagnostics.csv\n');
fprintf('  - Metric_Availability.csv\n');
fprintf('  - experiment_data.mat\n');
fprintf('\n');
fprintf('==============================================================\n');
clear requiredVariables ...
      RATE ...
      mask ...
      tAbsolute ...
      t ...
      p_rad_s ...
      q_rad_s ...
      r_rad_s ...
      order ...
      uniqueIndex ...
      validRows ...
      maximumAbsoluteRecordedRate_rad_s ...
      pTrackingRMSE_rad_s ...
      qTrackingRMSE_rad_s ...
      rTrackingRMSE_rad_s ...
      MaxAbsPCommand_rad_s ...
      MaxAbsQCommand_rad_s ...
      MaxAbsRCommand_rad_s ...
      figure09File ...
      allAxes ...
      iAx ...
      diagnosticsFile ...
      availabilitySignals ...
      availabilityStatuses ...
      availabilitySources ...
      availabilityUnits ...
      availabilityNotes ...
      availabilityIndex ...
      newRow ...
      angularRateStateStatus ...
      angularRateStateSource ...
      angularRateStateNote ...
      rateTelemetryPresent ...
      rateTelemetryInformative ...
      rateTelemetryStatus ...
      rateTelemetryReason ...
      constantZeroTelemetry ...
      validRateSampleCount ...
      ax1 ...
      ax2 ...
      ax3 ...
      tl09 ...
      k;
