function REAL_BATCH_SUMMARY = run_real_flight_analysis()
masterFile = ...
    mfilename('fullpath');
if strlength(string(masterFile)) == 0
    masterFolder = ...
        pwd;
else
    masterFolder = ...
        fileparts(masterFile);
end
BATCH_TLOG_FILES = [ ...
    "Trajectory_1.tlog"; ...
    "Trajectory_2.tlog"];
BATCH_TRAJECTORY_LABELS = [ ...
    "T1"; ...
    "T2"];
BATCH_RESULT_NAMES = [ ...
    "REAL_T1"; ...
    "REAL_T2"];
numFlights = ...
    numel(BATCH_TLOG_FILES);
requiredScripts = [ ...
    "initialize_real_flight.m"; ...
    "import_tlog.m"; ...
    "extract_tlog_signals.m"; ...
    "normalize_real_flight_data.m"; ...
    "inspect_real_flight.m"; ...
    "prepare_real_results.m"; ...
    "plot_real_state_results.m"; ...
    "plot_real_estimator_results.m"; ...
    "plot_real_trajectory_3d.m"; ...
    "extract_real_autopilot_parameters.m"; ...
    "plot_real_actuation_results.m"; ...
    "plot_real_control_axes.m"; ...
    "plot_real_attitude_tracking.m"; ...
    "plot_real_angular_rate_tracking.m"; ...
    "plot_real_mission_results.m"; ...
    "plot_real_touchdown_diagnostics.m"];
for fileIndex = 1:numel(requiredScripts)
    requiredPath = ...
        fullfile( ...
            masterFolder, ...
            char(requiredScripts(fileIndex)));
    if ~isfile(requiredPath)
        error( ...
            'RealFlightBatch:MissingPipelineScript', ...
            'Required pipeline file was not found:\n%s', ...
            requiredPath);
    end
end
for flightIndex = 1:numFlights
    tlogPath = ...
        fullfile( ...
            masterFolder, ...
            char(BATCH_TLOG_FILES(flightIndex)));
    if ~isfile(tlogPath)
        error( ...
            'RealFlightBatch:MissingTLOG', ...
            ['Required real-flight TLOG was not found:\n%s\n\n', ...
             'Place both Trajectory_1.tlog and Trajectory_2.tlog ', ...
             'in the Real_Flight_TLOG folder before running the batch.'], ...
            tlogPath);
    end
end
batchResultsRoot = ...
    fullfile( ...
        masterFolder, ...
        'results');
if ~exist(batchResultsRoot,'dir')
    mkdir(batchResultsRoot);
end
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' REAL FLIGHT TWO-TRAJECTORY ANALYSIS\n');
fprintf('==============================================================\n\n');
fprintf('Folder:\n%s\n\n',masterFolder);
fprintf('Flights to process:\n');
for flightIndex = 1:numFlights
    fprintf( ...
        '  %s  ->  %s  ->  %s\n', ...
        BATCH_TLOG_FILES(flightIndex), ...
        BATCH_TRAJECTORY_LABELS(flightIndex), ...
        BATCH_RESULT_NAMES(flightIndex));
end
fprintf('\n');
batchWallClock = ...
    tic;
BatchResult = ...
    repmat( ...
        emptyBatchResult(), ...
        numFlights, ...
        1);
for flightIndex = 1:numFlights
    tlogFile = ...
        BATCH_TLOG_FILES(flightIndex);
    trajectoryLabel = ...
        BATCH_TRAJECTORY_LABELS(flightIndex);
    resultName = ...
        BATCH_RESULT_NAMES(flightIndex);
    fprintf('\n\n');
    fprintf('##############################################################\n');
    fprintf(' PROCESSING %s — %s\n',trajectoryLabel,tlogFile);
    fprintf('##############################################################\n\n');
    BatchResult(flightIndex) = ...
        runSingleRealFlight( ...
            masterFolder, ...
            tlogFile, ...
            trajectoryLabel, ...
            resultName);
end
REAL_BATCH_SUMMARY = ...
    struct2table(BatchResult);
batchSummaryCsv = ...
    fullfile( ...
        batchResultsRoot, ...
        'REAL_Batch_Summary.csv');
batchSummaryMat = ...
    fullfile( ...
        batchResultsRoot, ...
        'REAL_Batch_Summary.mat');
writetable( ...
    REAL_BATCH_SUMMARY, ...
    batchSummaryCsv);
save( ...
    batchSummaryMat, ...
    'REAL_BATCH_SUMMARY', ...
    'BatchResult', ...
    'BATCH_TLOG_FILES', ...
    'BATCH_TRAJECTORY_LABELS', ...
    'BATCH_RESULT_NAMES');
assignin( ...
    'base', ...
    'REAL_BATCH_SUMMARY', ...
    REAL_BATCH_SUMMARY);
assignin( ...
    'base', ...
    'REAL_BATCH_RESULTS', ...
    BatchResult);
batchElapsed_s = ...
    toc(batchWallClock);
fprintf('\n\n');
fprintf('==============================================================\n');
fprintf(' REAL FLIGHT BATCH COMPLETE\n');
fprintf('==============================================================\n\n');
disp(REAL_BATCH_SUMMARY);
fprintf('\n');
fprintf( ...
    'Successful flights: %d / %d\n', ...
    nnz(REAL_BATCH_SUMMARY.Success), ...
    height(REAL_BATCH_SUMMARY));
fprintf( ...
    'Total batch time:   %.2f s\n', ...
    batchElapsed_s);
fprintf('\nBatch summary CSV:\n%s\n',batchSummaryCsv);
fprintf('\nBatch summary MAT:\n%s\n',batchSummaryMat);
fprintf('\nExpected current result folders:\n');
fprintf( ...
    '  T1: %s\n', ...
    fullfile(batchResultsRoot,'REAL_T1'));
fprintf( ...
    '  T2: %s\n', ...
    fullfile(batchResultsRoot,'REAL_T2'));
fprintf('\n');
fprintf('==============================================================\n');
end
function RESULT = runSingleRealFlight( ...
    masterFolder, ...
    tlogFile, ...
    trajectoryLabel, ...
    requestedResultName)
close all;
flightWallClock = ...
    tic;
RESULT = ...
    emptyBatchResult();
RESULT.Trajectory = ...
    string(trajectoryLabel);
RESULT.TLOGFile = ...
    string(tlogFile);
RESULT.ResultName = ...
    string(requestedResultName);
REAL_PIPELINE = ...
    struct();
REAL_PIPELINE.Version = ...
    "2.0_TWO_TRAJECTORY";
REAL_PIPELINE.Trajectory = ...
    string(trajectoryLabel);
REAL_PIPELINE.TLOGFile = ...
    string(tlogFile);
REAL_PIPELINE.StartTime = ...
    datetime('now');
REAL_PIPELINE.Success = ...
    false;
REAL_PIPELINE.FailedStage = ...
    "";
REAL_PIPELINE.ErrorMessage = ...
    "";
REAL_PIPELINE.Stages = ...
    strings(0,1);
REAL_PIPELINE.StageStatus = ...
    strings(0,1);
REAL_PIPELINE.StageDuration_s = ...
    zeros(0,1);
STAGE_NAMES = [ ...
    "01_INITIALIZATION"; ...
    "02_TLOG_IMPORT"; ...
    "03_SIGNAL_EXTRACTION"; ...
    "04_NORMALIZATION"; ...
    "05_FLIGHT_INSPECTION"; ...
    "06_PREPARE_RESULTS"; ...
    "07_STATE_RESULTS"; ...
    "08_ESTIMATOR_RESULTS"; ...
    "09_3D_TRAJECTORY"; ...
    "10_AUTOPILOT_PARAMETERS"; ...
    "11_ACTUATION_RESULTS"; ...
    "12_CONTROL_AXES"; ...
    "13_ATTITUDE_TRACKING"; ...
    "14_ANGULAR_RATE"; ...
    "15_MISSION_RESULTS"; ...
    "16_TOUCHDOWN_DIAGNOSTICS"];
STAGE_FILES = [ ...
    "initialize_real_flight.m"; ...
    "import_tlog.m"; ...
    "extract_tlog_signals.m"; ...
    "normalize_real_flight_data.m"; ...
    "inspect_real_flight.m"; ...
    "prepare_real_results.m"; ...
    "plot_real_state_results.m"; ...
    "plot_real_estimator_results.m"; ...
    "plot_real_trajectory_3d.m"; ...
    "extract_real_autopilot_parameters.m"; ...
    "plot_real_actuation_results.m"; ...
    "plot_real_control_axes.m"; ...
    "plot_real_attitude_tracking.m"; ...
    "plot_real_angular_rate_tracking.m"; ...
    "plot_real_mission_results.m"; ...
    "plot_real_touchdown_diagnostics.m"];
try
    for batchStageIndex = 1:numel(STAGE_NAMES)
        stageName = ...
            STAGE_NAMES(batchStageIndex);
        stageFile = ...
            fullfile( ...
                masterFolder, ...
                char(STAGE_FILES(batchStageIndex)));
        fprintf('\n');
        fprintf('--------------------------------------------------------------\n');
        fprintf(' %s\n',stageName);
        fprintf('--------------------------------------------------------------\n');
        stageTimer = ...
            tic;
        try
            run(stageFile);
            if batchStageIndex == 1
                REAL_TLOG_FILE = ...
                    string(tlogFile);
                REAL_TLOG_PATH = ...
                    string( ...
                        fullfile( ...
                            REAL_PROJECT_ROOT, ...
                            char(tlogFile)));
                if ~isfile(REAL_TLOG_PATH)
                    error( ...
                        'RealFlightBatch:SelectedTLOGMissing', ...
                        'Selected TLOG does not exist:\n%s', ...
                        REAL_TLOG_PATH);
                end
                REAL_CONFIG.batch = ...
                    struct();
                REAL_CONFIG.batch.enabled = ...
                    true;
                REAL_CONFIG.batch.trajectoryLabel = ...
                    string(trajectoryLabel);
                REAL_CONFIG.batch.resultName = ...
                    string(requestedResultName);
                REAL_CONFIG.batch.tlogFile = ...
                    string(tlogFile);
                fprintf('\n');
                fprintf('Batch-selected TLOG:\n%s\n',REAL_TLOG_PATH);
            end
            if batchStageIndex == 4
                if ~isfield(REAL_DATA,'Metadata') || ...
                        ~isstruct(REAL_DATA.Metadata)
                    REAL_DATA.Metadata = ...
                        struct();
                end
                REAL_DATA.Metadata.TrajectoryLabel = ...
                    string(trajectoryLabel);
                REAL_DATA.Metadata.BatchResultName = ...
                    string(requestedResultName);
            end
            if batchStageIndex == 6
                [ ...
                    REAL_RESULT_NAME, ...
                    REAL_RUN_FOLDER_NAME, ...
                    REAL_RUN_FOLDER, ...
                    REAL_FIGURES_FOLDER, ...
                    REAL_TABLES_FOLDER, ...
                    REAL_EXPERIMENT_DATA_FILE, ...
                    ExperimentMetadata] = ...
                    installDeterministicResultFolder( ...
                        REAL_RESULTS_ROOT, ...
                        REAL_RUN_FOLDER, ...
                        requestedResultName, ...
                        trajectoryLabel, ...
                        ExperimentMetadata);
                Trajectory = ...
                    string(trajectoryLabel);
                TLOGFile = ...
                    string(tlogFile);
                ResultName = ...
                    string(requestedResultName);
                TrajectoryIdentity = ...
                    table( ...
                        Trajectory, ...
                        TLOGFile, ...
                        ResultName);
                writetable( ...
                    TrajectoryIdentity, ...
                    fullfile( ...
                        REAL_TABLES_FOLDER, ...
                        'Trajectory_Identity.csv'));
                save( ...
                    REAL_EXPERIMENT_DATA_FILE, ...
                    'TrajectoryIdentity', ...
                    'REAL_CONFIG', ...
                    '-append');
            end
            REAL_PIPELINE.Stages(end+1,1) = ...
                stageName;
            REAL_PIPELINE.StageStatus(end+1,1) = ...
                "OK";
            REAL_PIPELINE.StageDuration_s(end+1,1) = ...
                toc(stageTimer);
        catch ME
            REAL_PIPELINE = ...
                registerPipelineFailure( ...
                    REAL_PIPELINE, ...
                    stageName, ...
                    stageTimer, ...
                    ME);
            rethrow(ME);
        end
    end
    REAL_PIPELINE.Success = ...
        true;
    REAL_PIPELINE.EndTime = ...
        datetime('now');
    REAL_PIPELINE.TotalWallClock_s = ...
        toc(flightWallClock);
    PipelineStageSummary = ...
        table( ...
            REAL_PIPELINE.Stages, ...
            REAL_PIPELINE.StageStatus, ...
            REAL_PIPELINE.StageDuration_s, ...
            'VariableNames',{ ...
                'Stage', ...
                'Status', ...
                'ProcessingTime_s'});
    writetable( ...
        PipelineStageSummary, ...
        fullfile( ...
            REAL_TABLES_FOLDER, ...
            'Processing_Pipeline_Summary.csv'));
    save( ...
        REAL_EXPERIMENT_DATA_FILE, ...
        'REAL_PIPELINE', ...
        'PipelineStageSummary', ...
        '-append');
    figureFiles = ...
        dir( ...
            fullfile( ...
                REAL_FIGURES_FOLDER, ...
                '*.png'));
    tableFiles = ...
        dir( ...
            fullfile( ...
                REAL_TABLES_FOLDER, ...
                '*.csv'));
    RESULT.Success = ...
        true;
    RESULT.FailedStage = ...
        "";
    RESULT.ErrorMessage = ...
        "";
    RESULT.ResultFolder = ...
        string(REAL_RUN_FOLDER);
    RESULT.FiguresFolder = ...
        string(REAL_FIGURES_FOLDER);
    RESULT.TablesFolder = ...
        string(REAL_TABLES_FOLDER);
    RESULT.ExperimentDataFile = ...
        string(REAL_EXPERIMENT_DATA_FILE);
    RESULT.FiguresGenerated = ...
        numel(figureFiles);
    RESULT.CSVTablesGenerated = ...
        numel(tableFiles);
    RESULT.ProcessingTime_s = ...
        REAL_PIPELINE.TotalWallClock_s;
    fprintf('\n\n');
    fprintf('==============================================================\n');
    fprintf(' REAL FLIGHT ANALYSIS COMPLETE — %s\n',trajectoryLabel);
    fprintf('==============================================================\n\n');
    fprintf( ...
        'TLOG:                     %s\n', ...
        REAL_IMPORT.Source.FileName);
    fprintf( ...
        'Selected attempt:         %d\n', ...
        REAL_FLIGHT_INSPECTION.PrimaryAttemptIndex);
    fprintf( ...
        'Selection reason:         %s\n', ...
        REAL_FLIGHT_INSPECTION.SelectionReason);
    fprintf( ...
        'Figures generated:        %d\n', ...
        RESULT.FiguresGenerated);
    fprintf( ...
        'CSV tables generated:     %d\n', ...
        RESULT.CSVTablesGenerated);
    fprintf( ...
        'Processing time:          %.2f s\n', ...
        RESULT.ProcessingTime_s);
    fprintf('\nResult folder:\n%s\n',REAL_RUN_FOLDER);
    fprintf('\nExperiment data:\n%s\n',REAL_EXPERIMENT_DATA_FILE);
    fprintf('\n');
    fprintf('==============================================================\n');
catch ME
    RESULT.Success = ...
        false;
    RESULT.FailedStage = ...
        REAL_PIPELINE.FailedStage;
    RESULT.ErrorMessage = ...
        string(ME.message);
    RESULT.ProcessingTime_s = ...
        toc(flightWallClock);
    if exist('REAL_RUN_FOLDER','var')
        RESULT.ResultFolder = ...
            string(REAL_RUN_FOLDER);
    end
    if exist('REAL_FIGURES_FOLDER','var')
        RESULT.FiguresFolder = ...
            string(REAL_FIGURES_FOLDER);
    end
    if exist('REAL_TABLES_FOLDER','var')
        RESULT.TablesFolder = ...
            string(REAL_TABLES_FOLDER);
    end
    if exist('REAL_EXPERIMENT_DATA_FILE','var')
        RESULT.ExperimentDataFile = ...
            string(REAL_EXPERIMENT_DATA_FILE);
    end
    try
        if exist('REAL_TABLES_FOLDER','var') && ...
                isfolder(REAL_TABLES_FOLDER)
            PipelineStageSummary = ...
                table( ...
                    REAL_PIPELINE.Stages, ...
                    REAL_PIPELINE.StageStatus, ...
                    REAL_PIPELINE.StageDuration_s, ...
                    'VariableNames',{ ...
                        'Stage', ...
                        'Status', ...
                        'ProcessingTime_s'});
            writetable( ...
                PipelineStageSummary, ...
                fullfile( ...
                    REAL_TABLES_FOLDER, ...
                    'Processing_Pipeline_Summary.csv'));
        end
        if exist('REAL_EXPERIMENT_DATA_FILE','var') && ...
                isfile(REAL_EXPERIMENT_DATA_FILE)
            REAL_PIPELINE.EndTime = ...
                datetime('now');
            REAL_PIPELINE.TotalWallClock_s = ...
                RESULT.ProcessingTime_s;
            save( ...
                REAL_EXPERIMENT_DATA_FILE, ...
                'REAL_PIPELINE', ...
                '-append');
        end
    catch
    end
    fprintf('\n');
    fprintf('==============================================================\n');
    fprintf(' REAL FLIGHT FAILED — %s\n',trajectoryLabel);
    fprintf('==============================================================\n');
    fprintf( ...
        'TLOG:  %s\n', ...
        tlogFile);
    fprintf( ...
        'Stage: %s\n', ...
        RESULT.FailedStage);
    fprintf( ...
        'Error:\n%s\n', ...
        RESULT.ErrorMessage);
    fprintf('==============================================================\n');
end
close all;
end
function [ ...
    REAL_RESULT_NAME, ...
    REAL_RUN_FOLDER_NAME, ...
    REAL_RUN_FOLDER, ...
    REAL_FIGURES_FOLDER, ...
    REAL_TABLES_FOLDER, ...
    REAL_EXPERIMENT_DATA_FILE, ...
    ExperimentMetadata] = ...
    installDeterministicResultFolder( ...
        resultsRoot, ...
        temporaryRunFolder, ...
        requestedResultName, ...
        trajectoryLabel, ...
        ExperimentMetadata)
REAL_RESULT_NAME = ...
    string(requestedResultName);
REAL_RUN_FOLDER_NAME = ...
    char(REAL_RESULT_NAME);
targetFolder = ...
    fullfile( ...
        resultsRoot, ...
        REAL_RUN_FOLDER_NAME);
if isfolder(targetFolder)
    backupFolder = ...
        uniqueBackupFolder(targetFolder);
    fprintf('\n');
    fprintf('Existing result found.\n');
    fprintf('Archiving:\n%s\n',targetFolder);
    fprintf('To:\n%s\n\n',backupFolder);
    [archiveOK,archiveMessage] = ...
        movefile( ...
            targetFolder, ...
            backupFolder);
    if ~archiveOK
        error( ...
            'RealFlightBatch:ArchiveFailed', ...
            ['Unable to archive existing result folder.\n', ...
             'Source: %s\n', ...
             'Target: %s\n', ...
             'Reason: %s'], ...
            targetFolder, ...
            backupFolder, ...
            archiveMessage);
    end
end
[moveOK,moveMessage] = ...
    movefile( ...
        temporaryRunFolder, ...
        targetFolder);
if ~moveOK
    error( ...
        'RealFlightBatch:ResultFolderRenameFailed', ...
        ['Unable to install deterministic result folder.\n', ...
         'Source: %s\n', ...
         'Target: %s\n', ...
         'Reason: %s'], ...
        temporaryRunFolder, ...
        targetFolder, ...
        moveMessage);
end
REAL_RUN_FOLDER = ...
    targetFolder;
REAL_FIGURES_FOLDER = ...
    fullfile( ...
        REAL_RUN_FOLDER, ...
        'figures');
REAL_TABLES_FOLDER = ...
    fullfile( ...
        REAL_RUN_FOLDER, ...
        'tables');
REAL_EXPERIMENT_DATA_FILE = ...
    fullfile( ...
        REAL_RUN_FOLDER, ...
        'experiment_data.mat');
ExperimentMetadata.resultName = ...
    REAL_RESULT_NAME;
ExperimentMetadata.trajectoryLabel = ...
    string(trajectoryLabel);
ExperimentMetadata.resultsFolder = ...
    string(REAL_RUN_FOLDER);
ExperimentMetadata.figuresFolder = ...
    string(REAL_FIGURES_FOLDER);
ExperimentMetadata.tablesFolder = ...
    string(REAL_TABLES_FOLDER);
save( ...
    REAL_EXPERIMENT_DATA_FILE, ...
    'ExperimentMetadata', ...
    '-append');
fprintf('\n');
fprintf('Deterministic result folder installed:\n%s\n',REAL_RUN_FOLDER);
end
function backupFolder = uniqueBackupFolder(targetFolder)
timestampText = ...
    char( ...
        datetime( ...
            'now', ...
            'Format','yyyy-MM-dd_HH-mm-ss'));
baseBackup = ...
    sprintf( ...
        '%s_previous_%s', ...
        targetFolder, ...
        timestampText);
backupFolder = ...
    baseBackup;
counter = ...
    1;
while isfolder(backupFolder)
    backupFolder = ...
        sprintf( ...
            '%s_%02d', ...
            baseBackup, ...
            counter);
    counter = ...
        counter + 1;
end
end
function PIPELINE = registerPipelineFailure( ...
    PIPELINE, ...
    stageName, ...
    stageTimer, ...
    ME)
PIPELINE.Stages(end+1,1) = ...
    string(stageName);
PIPELINE.StageStatus(end+1,1) = ...
    "FAILED";
PIPELINE.StageDuration_s(end+1,1) = ...
    toc(stageTimer);
PIPELINE.Success = ...
    false;
PIPELINE.FailedStage = ...
    string(stageName);
PIPELINE.ErrorMessage = ...
    string(ME.message);
end
function RESULT = emptyBatchResult()
RESULT = ...
    struct();
RESULT.Trajectory = ...
    "";
RESULT.TLOGFile = ...
    "";
RESULT.ResultName = ...
    "";
RESULT.Success = ...
    false;
RESULT.FailedStage = ...
    "";
RESULT.ErrorMessage = ...
    "";
RESULT.ResultFolder = ...
    "";
RESULT.FiguresFolder = ...
    "";
RESULT.TablesFolder = ...
    "";
RESULT.ExperimentDataFile = ...
    "";
RESULT.FiguresGenerated = ...
    0;
RESULT.CSVTablesGenerated = ...
    0;
RESULT.ProcessingTime_s = ...
    NaN;
end
