function CFG = estimator_tuning_config()
CFG = struct();
CFG.schemaVersion = ...
    1.2;
CFG.modelName = ...
    'Quadrotor_Framework';
CFG.estimatorParameterFile = ...
    'UAV_state_estimator.m';
CFG.parameterNames = { ...
    'gyroNoiseScale'; ...
    'gyroBiasNoiseScale'; ...
    'accelNoiseScale'; ...
    'accelBiasNoiseScale'; ...
    'magBiasNoiseScale'; ...
    'geomagneticVectorNoiseScale'; ...
    'gpsPositionRScale_NE'; ...
    'gpsVelocityRScale_NE'; ...
    'gpsVelocityRScale_D'; ...
    'magRScale'; ...
    'baroRScale'; ...
    'quaternionP0Scale'; ...
    'positionP0Scale_NE'; ...
    'positionP0Scale_D'; ...
    'velocityP0Scale_NE'; ...
    'velocityP0Scale_D'; ...
    'gyroBiasP0Scale'; ...
    'accelBiasP0Scale'; ...
    'geomagneticP0Scale'; ...
    'magBiasP0Scale'; ...
    'robustPositionP0Scale_NE'; ...
    'robustPositionP0Scale_D'; ...
    'robustVelocityP0Scale_NE'; ...
    'robustVelocityP0Scale_D'};
CFG.numberOfParameters = ...
    numel( ...
        CFG.parameterNames);
if CFG.numberOfParameters ~= 24
    error( ...
        'QuadrotorFramework:EstimatorTuningParameterCount', ...
        'Estimator tuning must contain exactly 24 parameters.');
end
if numel( ...
        unique( ...
            CFG.parameterNames)) ~= ...
        CFG.numberOfParameters
    error( ...
        'QuadrotorFramework:EstimatorTuningDuplicateParameter', ...
        'Estimator tuning parameter names must be unique.');
end
Q_lower = ...
    -3 * ...
    ones( ...
        6, ...
        1);
Q_upper = ...
     3 * ...
    ones( ...
        6, ...
        1);
R_lower = ...
    -2 * ...
    ones( ...
        5, ...
        1);
R_upper = ...
     2 * ...
    ones( ...
        5, ...
        1);
P0_lower = ...
    -3 * ...
    ones( ...
        9, ...
        1);
P0_upper = ...
     3 * ...
    ones( ...
        9, ...
        1);
robustP0_lower = ...
    -3 * ...
    ones( ...
        4, ...
        1);
robustP0_upper = ...
     3 * ...
    ones( ...
        4, ...
        1);
CFG.lowerBounds = [ ...
    Q_lower; ...
    R_lower; ...
    P0_lower; ...
    robustP0_lower];
CFG.upperBounds = [ ...
    Q_upper; ...
    R_upper; ...
    P0_upper; ...
    robustP0_upper];
CFG.initialPoint = ...
    zeros( ...
        CFG.numberOfParameters, ...
        1);
if numel(CFG.lowerBounds) ~= ...
        CFG.numberOfParameters || ...
        numel(CFG.upperBounds) ~= ...
        CFG.numberOfParameters || ...
        numel(CFG.initialPoint) ~= ...
        CFG.numberOfParameters
    error( ...
        'QuadrotorFramework:EstimatorTuningBounds', ...
        ['Tuning bounds and initial point must match the ', ...
         '24-parameter contract.']);
end
if any(~isfinite(CFG.lowerBounds)) || ...
        any(~isfinite(CFG.upperBounds)) || ...
        any(~isfinite(CFG.initialPoint))
    error( ...
        'QuadrotorFramework:EstimatorTuningBoundsFinite', ...
        'Estimator tuning bounds and initial point must be finite.');
end
if any( ...
        CFG.lowerBounds >= ...
        CFG.upperBounds)
    error( ...
        'QuadrotorFramework:EstimatorTuningBoundsOrder', ...
        'Every estimator lower bound must be smaller than its upper bound.');
end
if any( ...
        CFG.initialPoint < ...
        CFG.lowerBounds) || ...
        any( ...
            CFG.initialPoint > ...
            CFG.upperBounds)
    error( ...
        'QuadrotorFramework:EstimatorTuningInitialPoint', ...
        'Estimator tuning initial point lies outside the search bounds.');
end
CFG.training.uavModel = ...
    1;
CFG.training.disturbancesEnabled = ...
    false;
CFG.training.operatorMode = ...
    uint8(1);
CFG.training.trajectoryID = ...
    [];
CFG.training.seedOffsets = [ ...
    0; ...
    37; ...
    91];
CFG.validation.seedOffsets = [ ...
    151; ...
    307; ...
    509];
if isempty( ...
        CFG.training.seedOffsets)
    error( ...
        'QuadrotorFramework:EstimatorTuningTrainingSeeds', ...
        'At least one estimator training seed is required.');
end
if isempty( ...
        CFG.validation.seedOffsets)
    error( ...
        'QuadrotorFramework:EstimatorTuningValidationSeeds', ...
        'At least one independent validation seed is required.');
end
trainingSeeds = ...
    double( ...
        CFG.training.seedOffsets(:));
validationSeeds = ...
    double( ...
        CFG.validation.seedOffsets(:));
if any(~isfinite(trainingSeeds)) || ...
        any(~isfinite(validationSeeds))
    error( ...
        'QuadrotorFramework:EstimatorTuningSeedFinite', ...
        'Training and validation seed offsets must be finite.');
end
if numel(unique(trainingSeeds)) ~= ...
        numel(trainingSeeds)
    error( ...
        'QuadrotorFramework:EstimatorTuningDuplicateTrainingSeed', ...
        'Training seed offsets must be unique.');
end
if numel(unique(validationSeeds)) ~= ...
        numel(validationSeeds)
    error( ...
        'QuadrotorFramework:EstimatorTuningDuplicateValidationSeed', ...
        'Validation seed offsets must be unique.');
end
if any( ...
        ismember( ...
            trainingSeeds, ...
            validationSeeds))
    error( ...
        'QuadrotorFramework:EstimatorTuningSeedLeakage', ...
        ['Training and validation seed offsets must be ', ...
         'independent and non-overlapping.']);
end
CFG.simulation.metricSampleRate_Hz = ...
    200;
CFG.simulation.disablePacing = ...
    true;
CFG.simulation.useAutomaticProtocolStopTime = ...
    true;
CFG.simulation.stopTime_s = ...
    [];
if ~isscalar( ...
        CFG.simulation.metricSampleRate_Hz) || ...
        ~isfinite( ...
            CFG.simulation.metricSampleRate_Hz) || ...
        CFG.simulation.metricSampleRate_Hz <= 0
    error( ...
        'QuadrotorFramework:EstimatorTuningMetricRate', ...
        'Estimator metric sample rate must be positive and finite.');
end
if ~isempty( ...
        CFG.simulation.stopTime_s)
    if ~isscalar( ...
            CFG.simulation.stopTime_s) || ...
            ~isfinite( ...
                CFG.simulation.stopTime_s) || ...
            CFG.simulation.stopTime_s <= 0
        error( ...
            'QuadrotorFramework:EstimatorTuningStopTimeConfig', ...
            'Configured estimator tuning Stop Time must be positive.');
    end
end
CFG.simulation.requireTrueFeedback = ...
    true;
CFG.simulation.trueFeedbackTolerance_m = ...
    1e-6;
if ~isscalar( ...
        CFG.simulation.trueFeedbackTolerance_m) || ...
        ~isfinite( ...
            CFG.simulation.trueFeedbackTolerance_m) || ...
        CFG.simulation.trueFeedbackTolerance_m <= 0
    error( ...
        'QuadrotorFramework:EstimatorTuningTrueFeedbackTolerance', ...
        'TRUE-feedback tolerance must be positive and finite.');
end
CFG.cost.weight.positionRMSE = ...
    0.25;
CFG.cost.weight.horizontalPositionRMSE = ...
    0.15;
CFG.cost.weight.velocityRMSE = ...
    0.20;
CFG.cost.weight.attitudeRMSE = ...
    0.15;
CFG.cost.weight.angularRateRMSE = ...
    0.05;
CFG.cost.weight.accelerationRMSE = ...
    0.05;
CFG.cost.weight.positionP95 = ...
    0.10;
CFG.cost.weight.attitudeP95 = ...
    0.05;
totalWeight = ...
    CFG.cost.weight.positionRMSE + ...
    CFG.cost.weight.horizontalPositionRMSE + ...
    CFG.cost.weight.velocityRMSE + ...
    CFG.cost.weight.attitudeRMSE + ...
    CFG.cost.weight.angularRateRMSE + ...
    CFG.cost.weight.accelerationRMSE + ...
    CFG.cost.weight.positionP95 + ...
    CFG.cost.weight.attitudeP95;
if abs( ...
        totalWeight - ...
        1.0) > ...
        1e-12
    error( ...
        'QuadrotorFramework:EstimatorTuningWeights', ...
        'Estimator tuning metric weights must sum to exactly 1.');
end
CFG.cost.seedStandardDeviationWeight = ...
    0.10;
CFG.cost.worstSeedWeight = ...
    0.10;
CFG.cost.parameterRegularizationWeight = ...
    0.005;
CFG.cost.failurePenalty = ...
    1e4;
CFG.cost.minimumNormalization = ...
    1e-12;
costScalars = [ ...
    CFG.cost.seedStandardDeviationWeight; ...
    CFG.cost.worstSeedWeight; ...
    CFG.cost.parameterRegularizationWeight; ...
    CFG.cost.failurePenalty; ...
    CFG.cost.minimumNormalization];
if any(~isfinite(costScalars)) || ...
        any(costScalars < 0)
    error( ...
        'QuadrotorFramework:EstimatorTuningCostConfiguration', ...
        'Estimator tuning cost parameters must be finite and nonnegative.');
end
if CFG.cost.failurePenalty <= 1
    error( ...
        'QuadrotorFramework:EstimatorTuningFailurePenalty', ...
        'Estimator tuning failure penalty must be greater than 1.');
end
if CFG.cost.minimumNormalization <= 0
    error( ...
        'QuadrotorFramework:EstimatorTuningMinimumNormalization', ...
        'Minimum metric normalization must be strictly positive.');
end
CFG.optimizer.method = ...
    'surrogateopt';
CFG.optimizer.maxFunctionEvaluations = ...
    300;
CFG.optimizer.minSurrogatePoints = ...
    48;
CFG.optimizer.display = ...
    'iter';
CFG.optimizer.useParallel = ...
    true;
CFG.optimizer.batchSize = ...
    5;
CFG.optimizer.parallelUseFastRestart = ...
    false;
CFG.optimizer.randomSeed = ...
    2027;
CFG.optimizer.swarmSize = ...
    40;
if ~strcmpi( ...
        CFG.optimizer.method, ...
        'surrogateopt')
    error( ...
        'QuadrotorFramework:EstimatorTuningOptimizerMethod', ...
        ['The definitive EKF tuning configuration must use ', ...
         'surrogateopt.']);
end
if isempty( ...
        which( ...
            'surrogateopt'))
    error( ...
        'QuadrotorFramework:EstimatorTuningSurrogateOptUnavailable', ...
        [ ...
        'surrogateopt is not available on the MATLAB path. ', ...
        'Install/enable Global Optimization Toolbox before running ', ...
        'estimator tuning.']);
end
if ~isscalar( ...
        CFG.optimizer.maxFunctionEvaluations) || ...
        ~isfinite( ...
            CFG.optimizer.maxFunctionEvaluations) || ...
        CFG.optimizer.maxFunctionEvaluations < 1 || ...
        CFG.optimizer.maxFunctionEvaluations ~= ...
            floor( ...
                CFG.optimizer.maxFunctionEvaluations)
    error( ...
        'QuadrotorFramework:EstimatorTuningEvaluationBudget', ...
        'MaxFunctionEvaluations must be a positive integer.');
end
if ~isscalar( ...
        CFG.optimizer.minSurrogatePoints) || ...
        ~isfinite( ...
            CFG.optimizer.minSurrogatePoints) || ...
        CFG.optimizer.minSurrogatePoints < ...
            CFG.numberOfParameters + 1 || ...
        CFG.optimizer.minSurrogatePoints ~= ...
            floor( ...
                CFG.optimizer.minSurrogatePoints)
    error( ...
        'QuadrotorFramework:EstimatorTuningMinSurrogatePoints', ...
        ['MinSurrogatePoints must be an integer greater than or equal ', ...
         'to numberOfParameters + 1.']);
end
if CFG.optimizer.minSurrogatePoints > ...
        CFG.optimizer.maxFunctionEvaluations
    error( ...
        'QuadrotorFramework:EstimatorTuningSurrogateBudget', ...
        ['MinSurrogatePoints cannot exceed ', ...
         'MaxFunctionEvaluations.']);
end
if ~isscalar( ...
        CFG.optimizer.batchSize) || ...
        ~isfinite( ...
            CFG.optimizer.batchSize) || ...
        CFG.optimizer.batchSize < 1 || ...
        CFG.optimizer.batchSize ~= ...
            floor( ...
                CFG.optimizer.batchSize)
    error( ...
        'QuadrotorFramework:EstimatorTuningBatchSize', ...
        'Optimizer batchSize must be a positive integer.');
end
if CFG.optimizer.batchSize > ...
        CFG.optimizer.maxFunctionEvaluations
    error( ...
        'QuadrotorFramework:EstimatorTuningBatchBudget', ...
        'Optimizer batchSize cannot exceed MaxFunctionEvaluations.');
end
if ~isscalar( ...
        CFG.optimizer.parallelUseFastRestart)
    error( ...
        'QuadrotorFramework:EstimatorTuningFastRestartFlag', ...
        'parallelUseFastRestart must be a scalar logical value.');
end
CFG.optimizer.parallelUseFastRestart = ...
    logical( ...
        CFG.optimizer.parallelUseFastRestart);
if ~isscalar( ...
        CFG.optimizer.randomSeed) || ...
        ~isfinite( ...
            CFG.optimizer.randomSeed) || ...
        CFG.optimizer.randomSeed < 0 || ...
        CFG.optimizer.randomSeed ~= ...
            floor( ...
                CFG.optimizer.randomSeed)
    error( ...
        'QuadrotorFramework:EstimatorTuningRandomSeed', ...
        'Optimizer random seed must be a nonnegative integer.');
end
if ~isscalar( ...
        CFG.optimizer.useParallel)
    error( ...
        'QuadrotorFramework:EstimatorTuningParallelFlag', ...
        'Optimizer UseParallel configuration must be scalar.');
end
CFG.optimizer.useParallel = ...
    logical( ...
        CFG.optimizer.useParallel);
CFG.output.rootFolder = ...
    'Estimator_Tuning_Results';
CFG.output.resultFile = ...
    'Estimator_Tuning_Result.mat';
CFG.output.parameterTableFile = ...
    'Estimator_Tuning_Best_Parameters.csv';
CFG.output.validationFile = ...
    'Estimator_Tuning_Validation.mat';
CFG.output.checkpointFile = ...
    'Estimator_Tuning_Checkpoint.mat';
requiredOutputNames = { ...
    CFG.output.rootFolder; ...
    CFG.output.resultFile; ...
    CFG.output.parameterTableFile; ...
    CFG.output.validationFile; ...
    CFG.output.checkpointFile};
for nameIndex = ...
        1:numel(requiredOutputNames)
    if isempty( ...
            requiredOutputNames{nameIndex})
        error( ...
            'QuadrotorFramework:EstimatorTuningOutputName', ...
            'Estimator tuning output names cannot be empty.');
    end
end
end
