function J = evaluate_estimator_candidates_parallel( ...
    Z, ...
    CFG, ...
    nominalVector, ...
    baselineMetrics)

narginchk(4,4);

if ~isstruct(CFG)
    error( ...
        'QuadrotorFramework:EstimatorParallelInvalidConfiguration', ...
        'CFG must be a structure.');
end

if ~isfield(CFG,'numberOfParameters') || ...
        CFG.numberOfParameters ~= 24
    error( ...
        'QuadrotorFramework:EstimatorParallelParameterCount', ...
        'Estimator tuning requires exactly 24 parameters.');
end

nominalVector = double(nominalVector(:));

if numel(nominalVector) ~= 24 || ...
        any(~isfinite(nominalVector)) || ...
        any(nominalVector <= 0)
    error( ...
        'QuadrotorFramework:EstimatorParallelNominalVector', ...
        'nominalVector must contain 24 finite positive values.');
end

if isempty(baselineMetrics)
    error( ...
        'QuadrotorFramework:EstimatorParallelBaselineMissing', ...
        'baselineMetrics cannot be empty.');
end

Z = double(Z);

if isvector(Z)
    if numel(Z) ~= 24
        error( ...
            'QuadrotorFramework:EstimatorParallelCandidateSize', ...
            'A candidate must contain exactly 24 parameters.');
    end

    Z = reshape(Z,1,24);

elseif size(Z,2) ~= 24
    error( ...
        'QuadrotorFramework:EstimatorParallelCandidateMatrix', ...
        'Z must be N-by-24.');
end

if any(~isfinite(Z(:)))
    error( ...
        'QuadrotorFramework:EstimatorParallelCandidateFinite', ...
        'Z contains NaN or Inf.');
end

numberOfCandidates = size(Z,1);

[J,RESULT] = evaluate_estimator_candidate( ...
    Z, ...
    CFG, ...
    nominalVector, ...
    baselineMetrics, ...
    'parallel');

J = double(J(:));

if numel(J) ~= numberOfCandidates
    error( ...
        'QuadrotorFramework:EstimatorParallelObjectiveSize', ...
        'Expected %d costs but received %d.', ...
        numberOfCandidates, ...
        numel(J));
end

if numel(RESULT) ~= numberOfCandidates
    error( ...
        'QuadrotorFramework:EstimatorParallelResultSize', ...
        'Expected %d result structures but received %d.', ...
        numberOfCandidates, ...
        numel(RESULT));
end

if any(~isfinite(J))
    error( ...
        'QuadrotorFramework:EstimatorParallelObjectiveFinite', ...
        'Parallel objective returned NaN or Inf.');
end

J = reshape(J,numberOfCandidates,1);

end