function [J, RESULT] = evaluate_estimator_candidate( ...
    z, ...
    CFG, ...
    nominalVector, ...
    baselineMetrics, ...
    executionMode)
if nargin < 4
    baselineMetrics = [];
end
if nargin < 5 || isempty(executionMode)
    executionMode = 'auto';
end
validateConfigurationContract(CFG);
nominalVector = double(nominalVector(:));
if numel(nominalVector) ~= CFG.numberOfParameters
    error( ...
        'QuadrotorFramework:EstimatorNominalVectorSize', ...
        'Nominal estimator vector must contain exactly 24 parameters.');
end
if any(~isfinite(nominalVector)) || any(nominalVector <= 0)
    error( ...
        'QuadrotorFramework:EstimatorNominalVectorValues', ...
        'Nominal estimator parameters must be finite and positive.');
end
Z = normalizeCandidateMatrix( ...
    z, ...
    CFG.numberOfParameters);
numberOfCandidates = size(Z,1);
mode = lower(strtrim(char(executionMode)));
validModes = { ...
    'auto', ...
    'serial', ...
    'parallel'};
if ~ismember(mode,validModes)
    error( ...
        'QuadrotorFramework:EstimatorCandidateExecutionMode', ...
        'executionMode must be auto, serial, or parallel.');
end
switch mode
    case 'serial'
        if numberOfCandidates ~= 1
            error( ...
                'QuadrotorFramework:EstimatorSerialCandidateCount', ...
                'Serial estimator evaluation accepts exactly one candidate.');
        end
        [J,RESULT] = evaluateSingleCandidate( ...
            Z(1,:).', ...
            CFG, ...
            nominalVector, ...
            baselineMetrics);
    case 'parallel'
        [J,RESULT] = evaluateCandidateBatchParallel( ...
            Z, ...
            CFG, ...
            nominalVector, ...
            baselineMetrics);
    otherwise
        if numberOfCandidates == 1
            [J,RESULT] = evaluateSingleCandidate( ...
                Z(1,:).', ...
                CFG, ...
                nominalVector, ...
                baselineMetrics);
        else
            [J,RESULT] = evaluateCandidateBatchParallel( ...
                Z, ...
                CFG, ...
                nominalVector, ...
                baselineMetrics);
        end
end
end
function validateConfigurationContract(CFG)
requiredTopFields = { ...
    'numberOfParameters', ...
    'parameterNames', ...
    'lowerBounds', ...
    'upperBounds', ...
    'training', ...
    'simulation', ...
    'cost', ...
    'modelName', ...
    'estimatorParameterFile'};
for fieldIndex = 1:numel(requiredTopFields)
    if ~isfield(CFG,requiredTopFields{fieldIndex})
        error( ...
            'QuadrotorFramework:EstimatorTuningConfiguration', ...
            'Missing CFG.%s.', ...
            requiredTopFields{fieldIndex});
    end
end
if CFG.numberOfParameters ~= 24
    error( ...
        'QuadrotorFramework:EstimatorTuningParameterCount', ...
        'Estimator tuning requires exactly 24 parameters.');
end
if numel(CFG.parameterNames) ~= CFG.numberOfParameters
    error( ...
        'QuadrotorFramework:EstimatorTuningParameterNames', ...
        'Estimator parameter-name count does not match configuration.');
end
if numel(unique(CFG.parameterNames)) ~= CFG.numberOfParameters
    error( ...
        'QuadrotorFramework:EstimatorTuningParameterNamesUnique', ...
        'Estimator parameter names must be unique.');
end
lowerBounds = double(CFG.lowerBounds(:));
upperBounds = double(CFG.upperBounds(:));
if numel(lowerBounds) ~= CFG.numberOfParameters || ...
        numel(upperBounds) ~= CFG.numberOfParameters
    error( ...
        'QuadrotorFramework:EstimatorTuningBoundsSize', ...
        'Estimator tuning bounds do not match parameter count.');
end
if any(~isfinite(lowerBounds)) || ...
        any(~isfinite(upperBounds)) || ...
        any(lowerBounds >= upperBounds)
    error( ...
        'QuadrotorFramework:EstimatorTuningBoundsValues', ...
        'Estimator tuning bounds are invalid.');
end
if ~isfield(CFG.training,'seedOffsets') || ...
        isempty(CFG.training.seedOffsets)
    error( ...
        'QuadrotorFramework:EstimatorTuningSeeds', ...
        'At least one estimator tuning seed is required.');
end
seedOffsets = double(CFG.training.seedOffsets(:));
if any(~isfinite(seedOffsets))
    error( ...
        'QuadrotorFramework:EstimatorTuningSeedFinite', ...
        'Estimator seed offsets must be finite.');
end
if numel(unique(seedOffsets)) ~= numel(seedOffsets)
    error( ...
        'QuadrotorFramework:EstimatorTuningSeedUnique', ...
        'Estimator seed offsets must be unique.');
end
if ~isfield(CFG.cost,'failurePenalty') || ...
        ~isscalar(CFG.cost.failurePenalty) || ...
        ~isfinite(CFG.cost.failurePenalty) || ...
        CFG.cost.failurePenalty <= 1
    error( ...
        'QuadrotorFramework:EstimatorTuningFailurePenalty', ...
        'Estimator failure penalty must be finite and greater than one.');
end
if ~isfield(CFG.cost,'minimumNormalization') || ...
        ~isscalar(CFG.cost.minimumNormalization) || ...
        ~isfinite(CFG.cost.minimumNormalization) || ...
        CFG.cost.minimumNormalization <= 0
    error( ...
        'QuadrotorFramework:EstimatorTuningNormalization', ...
        'Minimum normalization must be positive and finite.');
end
end
function Z = normalizeCandidateMatrix( ...
    z, ...
    numberOfParameters)
z = double(z);
if isempty(z)
    error( ...
        'QuadrotorFramework:EstimatorCandidateEmpty', ...
        'Estimator candidate input cannot be empty.');
end
if isvector(z)
    if numel(z) ~= numberOfParameters
        error( ...
            'QuadrotorFramework:EstimatorCandidateSize', ...
            'Candidate must contain exactly %d parameters.', ...
            numberOfParameters);
    end
    Z = reshape(z,1,numberOfParameters);
    return;
end
if size(z,2) == numberOfParameters
    Z = z;
elseif size(z,1) == numberOfParameters && ...
        size(z,2) ~= numberOfParameters
    Z = z.';
else
    error( ...
        'QuadrotorFramework:EstimatorCandidateMatrixSize', ...
        ['Candidate matrix must contain one candidate per row ', ...
         'with exactly %d columns.'], ...
        numberOfParameters);
end
end
function [J,RESULT] = evaluateSingleCandidate( ...
    z, ...
    CFG, ...
    nominalVector, ...
    baselineMetrics)
z = double(z(:));
if ~candidateWithinBounds(z,CFG)
    [J,RESULT] = invalidCandidateResult( ...
        z, ...
        CFG, ...
        nominalVector, ...
        baselineMetrics, ...
        'Candidate is nonfinite or outside configured bounds.');
    return;
end
CONTEXT = getSimulationContext(CFG);
try
    CANDIDATE = buildCandidateDefinition( ...
        z, ...
        CFG, ...
        nominalVector, ...
        CONTEXT);
catch ME
    [J,RESULT] = invalidCandidateResult( ...
        z, ...
        CFG, ...
        nominalVector, ...
        baselineMetrics, ...
        sprintf( ...
            '%s: %s', ...
            ME.identifier, ...
            ME.message));
    return;
end
seedOffsets = double(CFG.training.seedOffsets(:));
numberOfSeeds = numel(seedOffsets);
RUN = repmat( ...
    emptyMetricStructure(), ...
    numberOfSeeds, ...
    1);
runSucceeded = false(numberOfSeeds,1);
messages = cell(numberOfSeeds,1);
for seedIndex = 1:numberOfSeeds
    try
        simIn = buildSimulationInput( ...
            CANDIDATE.ESTIMATOR, ...
            CANDIDATE.override, ...
            seedOffsets(seedIndex), ...
            CONTEXT, ...
            CFG);
        out = sim(simIn);
        if ~isempty(out.ErrorMessage)
            error( ...
                'QuadrotorFramework:EstimatorSimulationError', ...
                '%s', ...
                out.ErrorMessage);
        end
        RUN(seedIndex) = extractMetrics( ...
            out, ...
            CANDIDATE.ESTIMATOR, ...
            CFG);
        RUN(seedIndex).SeedOffset = seedOffsets(seedIndex);
        RUN(seedIndex).success = true;
        runSucceeded(seedIndex) = true;
        messages{seedIndex} = 'OK';
    catch ME
        runSucceeded(seedIndex) = false;
        messages{seedIndex} = sprintf( ...
            '%s: %s', ...
            ME.identifier, ...
            ME.message);
    end
end
[J,RESULT] = finalizeCandidateEvaluation( ...
    CANDIDATE, ...
    RUN, ...
    runSucceeded, ...
    messages, ...
    baselineMetrics, ...
    CFG);
end
function [J,RESULT] = evaluateCandidateBatchParallel( ...
    Z, ...
    CFG, ...
    nominalVector, ...
    baselineMetrics)
if isempty(which('parsim'))
    error( ...
        'QuadrotorFramework:EstimatorParallelParsimMissing', ...
        ['parsim is not available on the MATLAB path. ', ...
         'Simulink is required for parallel estimator optimization.']);
end
if ~license('test','Simulink')
    error( ...
        'QuadrotorFramework:EstimatorParallelSimulinkLicense', ...
        'A valid Simulink license is required for PARSIM.');
end
if ~license('test','Distrib_Computing_Toolbox')
    error( ...
        'QuadrotorFramework:EstimatorParallelToolboxLicense', ...
        ['A valid Parallel Computing Toolbox license is required ', ...
         'for parallel estimator optimization.']);
end
if isempty(which('parpool')) || ...
        isempty(which('gcp'))
    error( ...
        'QuadrotorFramework:EstimatorParallelToolboxMissing', ...
        ['Parallel Computing Toolbox functions parpool/gcp ', ...
         'are not available on the MATLAB path.']);
end
parallelPool = gcp('nocreate');
if ~isempty(parallelPool) && ...
        isa(parallelPool,'parallel.ThreadPool')
    warning( ...
        'QuadrotorFramework:EstimatorParallelThreadPoolRestart', ...
        ['A thread-based parallel pool is active. It will be ', ...
         'replaced by a process-based pool for estimator tuning.']);
    delete(parallelPool);
    parallelPool = [];
end
if isempty(parallelPool)
    try
        parallelPool = parpool('Processes');
    catch ME
        error( ...
            'QuadrotorFramework:EstimatorParallelPoolCreation', ...
            ['Could not create a process-based parallel pool. ', ...
             'Original error: %s'], ...
            ME.message);
    end
end
if isempty(parallelPool) || ...
        ~isvalid(parallelPool) || ...
        parallelPool.NumWorkers < 1
    error( ...
        'QuadrotorFramework:EstimatorParallelWorkers', ...
        'Parallel pool is invalid or contains no workers.');
end
numberOfCandidates = size(Z,1);
seedOffsets = double(CFG.training.seedOffsets(:));
numberOfSeeds = numel(seedOffsets);
J = CFG.cost.failurePenalty * ...
    ones(numberOfCandidates,1);
RESULT = repmat( ...
    emptyCandidateResult(), ...
    numberOfCandidates, ...
    1);
CONTEXT = getSimulationContext(CFG);
if strcmp( ...
        get_param(CONTEXT.modelName,'Dirty'), ...
        'on')
    error( ...
        'QuadrotorFramework:EstimatorParallelUnsavedModel', ...
        ['The model %s has unsaved changes. Save the model before ', ...
         'parallel estimator evaluation.'], ...
        CONTEXT.modelName);
end
candidateValid = false(numberOfCandidates,1);
candidateDefinition = cell(numberOfCandidates,1);
candidateBuildMessage = cell(numberOfCandidates,1);
for candidateIndex = 1:numberOfCandidates
    currentZ = double(Z(candidateIndex,:).');
    if ~candidateWithinBounds(currentZ,CFG)
        candidateBuildMessage{candidateIndex} = ...
            'Candidate is nonfinite or outside configured bounds.';
        [ ...
            J(candidateIndex), ...
            RESULT(candidateIndex)] = ...
            invalidCandidateResult( ...
                currentZ, ...
                CFG, ...
                nominalVector, ...
                baselineMetrics, ...
                candidateBuildMessage{candidateIndex});
        continue;
    end
    try
        candidateDefinition{candidateIndex} = ...
            buildCandidateDefinition( ...
                currentZ, ...
                CFG, ...
                nominalVector, ...
                CONTEXT);
        candidateValid(candidateIndex) = true;
        candidateBuildMessage{candidateIndex} = 'OK';
    catch ME
        candidateBuildMessage{candidateIndex} = sprintf( ...
            '%s: %s', ...
            ME.identifier, ...
            ME.message);
        [ ...
            J(candidateIndex), ...
            RESULT(candidateIndex)] = ...
            invalidCandidateResult( ...
                currentZ, ...
                CFG, ...
                nominalVector, ...
                baselineMetrics, ...
                candidateBuildMessage{candidateIndex});
    end
end
validCandidateIndices = find(candidateValid);
if isempty(validCandidateIndices)
    return;
end
numberOfParallelRuns = ...
    numel(validCandidateIndices) * numberOfSeeds;
simIn(1,numberOfParallelRuns) = ...
    Simulink.SimulationInput(CONTEXT.modelName);
runCandidateIndex = zeros(numberOfParallelRuns,1);
runSeedIndex = zeros(numberOfParallelRuns,1);
runCounter = 0;
for validIndex = 1:numel(validCandidateIndices)
    candidateIndex = validCandidateIndices(validIndex);
    CANDIDATE = candidateDefinition{candidateIndex};
    for seedIndex = 1:numberOfSeeds
        runCounter = runCounter + 1;
        simIn(runCounter) = buildSimulationInput( ...
            CANDIDATE.ESTIMATOR, ...
            CANDIDATE.override, ...
            seedOffsets(seedIndex), ...
            CONTEXT, ...
            CFG);
        runCandidateIndex(runCounter) = candidateIndex;
        runSeedIndex(runCounter) = seedIndex;
    end
end
simOut = executeParallelSimulations( ...
    simIn, ...
    CONTEXT, ...
    CFG);
if numel(simOut) ~= numberOfParallelRuns
    error( ...
        'QuadrotorFramework:EstimatorParallelOutputCount', ...
        ['parsim returned %d outputs for %d requested simulations.'], ...
        numel(simOut), ...
        numberOfParallelRuns);
end
candidateRuns = cell(numberOfCandidates,1);
candidateRunSucceeded = cell(numberOfCandidates,1);
candidateMessages = cell(numberOfCandidates,1);
for validIndex = 1:numel(validCandidateIndices)
    candidateIndex = validCandidateIndices(validIndex);
    candidateRuns{candidateIndex} = repmat( ...
        emptyMetricStructure(), ...
        numberOfSeeds, ...
        1);
    candidateRunSucceeded{candidateIndex} = ...
        false(numberOfSeeds,1);
    candidateMessages{candidateIndex} = ...
        cell(numberOfSeeds,1);
end
for runIndex = 1:numberOfParallelRuns
    candidateIndex = runCandidateIndex(runIndex);
    seedIndex = runSeedIndex(runIndex);
    CANDIDATE = candidateDefinition{candidateIndex};
    out = simOut(runIndex);
    if ~isempty(out.ErrorMessage)
        candidateRunSucceeded{candidateIndex}(seedIndex) = false;
        candidateMessages{candidateIndex}{seedIndex} = ...
            sprintf( ...
                'Simulink:SimulationError: %s', ...
                out.ErrorMessage);
        continue;
    end
    try
        currentMetric = extractMetrics( ...
            out, ...
            CANDIDATE.ESTIMATOR, ...
            CFG);
        currentMetric.SeedOffset = seedOffsets(seedIndex);
        currentMetric.success = true;
        candidateRuns{candidateIndex}(seedIndex) = ...
            currentMetric;
        candidateRunSucceeded{candidateIndex}(seedIndex) = ...
            true;
        candidateMessages{candidateIndex}{seedIndex} = ...
            'OK';
    catch ME
        candidateRunSucceeded{candidateIndex}(seedIndex) = ...
            false;
        candidateMessages{candidateIndex}{seedIndex} = ...
            sprintf( ...
                '%s: %s', ...
                ME.identifier, ...
                ME.message);
    end
end
for validIndex = 1:numel(validCandidateIndices)
    candidateIndex = validCandidateIndices(validIndex);
    [ ...
        J(candidateIndex), ...
        RESULT(candidateIndex)] = ...
        finalizeCandidateEvaluation( ...
            candidateDefinition{candidateIndex}, ...
            candidateRuns{candidateIndex}, ...
            candidateRunSucceeded{candidateIndex}, ...
            candidateMessages{candidateIndex}, ...
            baselineMetrics, ...
            CFG);
end
J = double(J(:));
end
function simOut = executeParallelSimulations( ...
    simIn, ...
    CONTEXT, ...
    CFG)
persistent fastRestartUnsupported
if isempty(fastRestartUnsupported)
    fastRestartUnsupported = false;
end
useFastRestart = false;
if isfield(CFG,'optimizer') && ...
        isfield(CFG.optimizer,'parallelUseFastRestart') && ...
        ~isempty(CFG.optimizer.parallelUseFastRestart)
    useFastRestart = logical( ...
        CFG.optimizer.parallelUseFastRestart);
end
if fastRestartUnsupported
    useFastRestart = false;
end
setupFcn = @() parallelWorkerSetup( ...
    CONTEXT.projectRoot, ...
    CONTEXT.tuningFolder);
commonArguments = { ...
    'ShowProgress', ...
    'off', ...
    ...
    'ShowSimulationManager', ...
    'off', ...
    ...
    'TransferBaseWorkspaceVariables', ...
    'off', ...
    ...
    'ManageDependencies', ...
    'on', ...
    ...
    'StopOnError', ...
    'off', ...
    ...
    'SetupFcn', ...
    setupFcn};
if useFastRestart
    try
        simOut = parsim( ...
            simIn, ...
            commonArguments{:}, ...
            'UseFastRestart', ...
            'on');
        return;
    catch ME
        fastRestartUnsupported = true;
        warning( ...
            'QuadrotorFramework:EstimatorParallelFastRestartDisabled', ...
            [ ...
            'Fast Restart failed during estimator tuning and will ', ...
            'be disabled for subsequent batches.\nReason: %s'], ...
            ME.message);
    end
end
simOut = parsim( ...
    simIn, ...
    commonArguments{:}, ...
    'UseFastRestart', ...
    'off');
end
function parallelWorkerSetup( ...
    projectRoot, ...
    tuningFolder)
if exist(projectRoot,'dir') == 7
    addpath(projectRoot);
end
if exist(tuningFolder,'dir') == 7
    addpath(tuningFolder);
end
try
    cd(projectRoot);
catch
end
rehash;
end
function CONTEXT = getSimulationContext(CFG)
thisFile = mfilename('fullpath');
tuningFolder = fileparts(thisFile);
projectRoot = fileparts(tuningFolder);
requiredVariables = { ...
    'P_ENV', ...
    'SENSOR', ...
    'AUTO_PROTOCOL', ...
    'TRAJECTORY_ID'};
for variableIndex = 1:numel(requiredVariables)
    variableName = requiredVariables{variableIndex};
    if ~evalin( ...
            'base', ...
            sprintf( ...
                'exist(''%s'',''var'')', ...
                variableName))
        error( ...
            'QuadrotorFramework:EstimatorTuningNotInitialized', ...
            'Missing base-workspace variable %s.', ...
            variableName);
    end
end
CONTEXT = struct();
CONTEXT.projectRoot = projectRoot;
CONTEXT.tuningFolder = tuningFolder;
CONTEXT.modelName = CFG.modelName;
CONTEXT.P_ENV = evalin('base','P_ENV');
CONTEXT.SENSOR = evalin('base','SENSOR');
CONTEXT.AUTO_PROTOCOL = evalin('base','AUTO_PROTOCOL');
CONTEXT.TRAJECTORY_ID = evalin('base','TRAJECTORY_ID');
if ~isempty(CFG.training.trajectoryID)
    CONTEXT.TRAJECTORY_ID = ...
        uint8(CFG.training.trajectoryID);
end
CONTEXT.modelFile = fullfile( ...
    projectRoot, ...
    [CFG.modelName '.slx']);
if ~isfile(CONTEXT.modelFile)
    error( ...
        'QuadrotorFramework:EstimatorTuningModelMissing', ...
        'Could not find model file %s.', ...
        CONTEXT.modelFile);
end
if ~bdIsLoaded(CFG.modelName)
    load_system(CONTEXT.modelFile);
end
if ~strcmp( ...
        get_param(CFG.modelName,'SimulationStatus'), ...
        'stopped')
    error( ...
        'QuadrotorFramework:EstimatorTuningModelRunning', ...
        'Stop the Simulink model before estimator tuning.');
end
if ~isempty(CFG.simulation.stopTime_s)
    CONTEXT.stopTime_s = ...
        double(CFG.simulation.stopTime_s);
elseif CFG.simulation.useAutomaticProtocolStopTime
    trajectoryRow = ...
        double(CONTEXT.TRAJECTORY_ID);
    stopColumn = ...
        double(CONTEXT.AUTO_PROTOCOL.column.stop);
    CONTEXT.stopTime_s = ...
        double( ...
            CONTEXT.AUTO_PROTOCOL.schedule_s( ...
                trajectoryRow, ...
                stopColumn));
else
    CONTEXT.stopTime_s = ...
        str2double( ...
            get_param( ...
                CFG.modelName, ...
                'StopTime'));
end
if ~isscalar(CONTEXT.stopTime_s) || ...
        ~isfinite(CONTEXT.stopTime_s) || ...
        CONTEXT.stopTime_s <= 0
    error( ...
        'QuadrotorFramework:EstimatorTuningStopTime', ...
        'Estimator tuning simulation Stop Time is invalid.');
end
end
function CANDIDATE = buildCandidateDefinition( ...
    z, ...
    CFG, ...
    nominalVector, ...
    CONTEXT)
z = double(z(:));
multipliers = 10.^z;
tunedVector = nominalVector .* multipliers;
if any(~isfinite(multipliers)) || ...
        any(multipliers <= 0) || ...
        any(~isfinite(tunedVector)) || ...
        any(tunedVector <= 0)
    error( ...
        'QuadrotorFramework:EstimatorCandidateValues', ...
        'Candidate estimator parameters are invalid.');
end
override = struct();
for parameterIndex = 1:CFG.numberOfParameters
    parameterName = CFG.parameterNames{parameterIndex};
    override.(parameterName) = tunedVector(parameterIndex);
end
ESTIMATOR = buildCandidateEstimator( ...
    override, ...
    tunedVector, ...
    CONTEXT, ...
    CFG);
CANDIDATE = struct();
CANDIDATE.z = z;
CANDIDATE.multipliers = multipliers;
CANDIDATE.tunedVector = tunedVector;
CANDIDATE.override = override;
CANDIDATE.ESTIMATOR = ESTIMATOR;
end
function ESTIMATOR = buildCandidateEstimator( ...
    override, ...
    requestedVector, ...
    CONTEXT, ...
    CFG)
P_ENV = CONTEXT.P_ENV; %#ok<NASGU>
SENSOR = CONTEXT.SENSOR; %#ok<NASGU>
ESTIMATOR_TUNING_OVERRIDE = override; %#ok<NASGU>
ESTIMATOR_TUNING_SILENT = true; %#ok<NASGU>
estimatorFile = fullfile( ...
    CONTEXT.projectRoot, ...
    CFG.estimatorParameterFile);
if ~isfile(estimatorFile)
    error( ...
        'QuadrotorFramework:MissingEstimatorParameterFile', ...
        'Could not find %s.', ...
        estimatorFile);
end
run(estimatorFile);
if ~exist('ESTIMATOR','var') || ...
        ~isstruct(ESTIMATOR)
    error( ...
        'QuadrotorFramework:EstimatorCandidateBuild', ...
        'Candidate ESTIMATOR could not be constructed.');
end
if ~isfield(ESTIMATOR,'tuning') || ...
        ~isstruct(ESTIMATOR.tuning) || ...
        ~isfield(ESTIMATOR.tuning,'vector')
    error( ...
        'QuadrotorFramework:EstimatorCandidateVectorMissing', ...
        'Candidate ESTIMATOR does not contain ESTIMATOR.tuning.vector.');
end
candidateVectorBuilt = ...
    double(ESTIMATOR.tuning.vector(:));
requestedVector = ...
    double(requestedVector(:));
if numel(candidateVectorBuilt) ~= CFG.numberOfParameters
    error( ...
        'QuadrotorFramework:EstimatorCandidateBuiltVectorSize', ...
        'Built estimator tuning vector has incorrect dimension.');
end
absoluteError = abs( ...
    candidateVectorBuilt - requestedVector);
allowedError = ...
    1e-12 .* ...
    max( ...
        1.0, ...
        abs(requestedVector));
if any(~isfinite(candidateVectorBuilt)) || ...
        any(absoluteError > allowedError)
    error( ...
        'QuadrotorFramework:EstimatorCandidateOverrideFailed', ...
        ['UAV_state_estimator.m did not construct the exact ', ...
         'requested tuning vector.']);
end
end
function simIn = buildSimulationInput( ...
    ESTIMATOR, ...
    override, ...
    seedOffset, ...
    CONTEXT, ...
    CFG)
SENSOR = applySensorSeedOffset( ...
    CONTEXT.SENSOR, ...
    seedOffset);
simIn = ...
    Simulink.SimulationInput(CONTEXT.modelName);
simIn = simIn.setVariable( ...
    'P_ENV', ...
    CONTEXT.P_ENV);
simIn = simIn.setVariable( ...
    'SENSOR', ...
    SENSOR);
simIn = simIn.setVariable( ...
    'ESTIMATOR', ...
    ESTIMATOR);
simIn = simIn.setVariable( ...
    'AUTO_PROTOCOL', ...
    CONTEXT.AUTO_PROTOCOL);
simIn = simIn.setVariable( ...
    'TRAJECTORY_ID', ...
    uint8(CONTEXT.TRAJECTORY_ID));
simIn = simIn.setVariable( ...
    'UAV_MODEL', ...
    CFG.training.uavModel);
simIn = simIn.setVariable( ...
    'DIST_ENABLE', ...
    logical(CFG.training.disturbancesEnabled));
simIn = simIn.setVariable( ...
    'OPERATOR_MODE', ...
    uint8(CFG.training.operatorMode));
simIn = simIn.setVariable( ...
    'ESTIMATOR_TUNING_OVERRIDE', ...
    override);
simIn = simIn.setVariable( ...
    'ESTIMATOR_TUNING_SILENT', ...
    true);
simIn = simIn.setModelParameter( ...
    'StopTime', ...
    sprintf( ...
        '%.15g', ...
        CONTEXT.stopTime_s), ...
    ...
    'ReturnWorkspaceOutputs', ...
    'on');
if CFG.simulation.disablePacing
    try
        simIn = simIn.setModelParameter( ...
            'EnablePacing', ...
            'off');
    catch
    end
end
end
function SENSOR = applySensorSeedOffset( ...
    SENSOR, ...
    seedOffset)
seedOffset = double(seedOffset);
if ~isscalar(seedOffset) || ...
        ~isfinite(seedOffset)
    error( ...
        'QuadrotorFramework:EstimatorTuningSeedOffset', ...
        'Sensor seed offset must be a finite scalar.');
end
SENSOR.IMU.seed = round( ...
    double(SENSOR.IMU.seed) + seedOffset);
SENSOR.GPS.seed = round( ...
    double(SENSOR.GPS.seed) + seedOffset);
SENSOR.Barometer.seed = round( ...
    double(SENSOR.Barometer.seed) + seedOffset);
seedValues = [ ...
    SENSOR.IMU.seed, ...
    SENSOR.GPS.seed, ...
    SENSOR.Barometer.seed];
if any(~isfinite(seedValues)) || ...
        any(seedValues < 0)
    error( ...
        'QuadrotorFramework:EstimatorTuningSeed', ...
        'Generated sensor seed is invalid.');
end
end
function valid = candidateWithinBounds( ...
    z, ...
    CFG)
z = double(z(:));
lowerBounds = double(CFG.lowerBounds(:));
upperBounds = double(CFG.upperBounds(:));
valid = ...
    numel(z) == CFG.numberOfParameters && ...
    all(isfinite(z)) && ...
    all(z >= lowerBounds) && ...
    all(z <= upperBounds);
end
function [J,RESULT] = finalizeCandidateEvaluation( ...
    CANDIDATE, ...
    RUN, ...
    runSucceeded, ...
    messages, ...
    baselineMetrics, ...
    CFG)
numberOfSeeds = numel(runSucceeded);
if numel(RUN) ~= numberOfSeeds
    error( ...
        'QuadrotorFramework:EstimatorCandidateMetricCount', ...
        'Candidate metric count does not match seed count.');
end
if isempty(baselineMetrics)
    J = NaN;
    RESULT = emptyCandidateResult();
    RESULT.success = ...
        all(runSucceeded);
    RESULT.cost = NaN;
    RESULT.z = CANDIDATE.z;
    RESULT.multipliers = CANDIDATE.multipliers;
    RESULT.tunedVector = CANDIDATE.tunedVector;
    RESULT.metrics = RUN;
    RESULT.runSucceeded = runSucceeded;
    RESULT.messages = messages;
    RESULT.runCost = NaN(numberOfSeeds,1);
    RESULT.meanMetrics = ...
        meanMetrics(RUN,runSucceeded);
    return;
end
if numel(baselineMetrics) ~= numberOfSeeds
    error( ...
        'QuadrotorFramework:EstimatorBaselineSeedCount', ...
        'Baseline seed count does not match candidate seed count.');
end
runCost = ...
    CFG.cost.failurePenalty * ...
    ones(numberOfSeeds,1);
for seedIndex = 1:numberOfSeeds
    if ~runSucceeded(seedIndex)
        continue;
    end
    B = baselineMetrics(seedIndex);
    M = RUN(seedIndex);
    if ~isfield(B,'success') || ...
            ~B.success
        error( ...
            'QuadrotorFramework:InvalidEstimatorBaseline', ...
            'Nominal estimator baseline contains a failed seed.');
    end
    runCost(seedIndex) = normalizedCost( ...
        M, ...
        B, ...
        CFG);
end
meanCost = mean(runCost);
stdCost = std(runCost);
worstCost = max(runCost);
regularization = ...
    CFG.cost.parameterRegularizationWeight * ...
    mean(CANDIDATE.z.^2);
candidateObjectiveValid = ...
    all(runSucceeded) && ...
    all(isfinite(runCost)) && ...
    all(runCost < CFG.cost.failurePenalty);
if candidateObjectiveValid
    J = ...
        meanCost + ...
        CFG.cost.seedStandardDeviationWeight * stdCost + ...
        CFG.cost.worstSeedWeight * ...
            max( ...
                0, ...
                worstCost - meanCost) + ...
        regularization;
    if ~isfinite(J) || ...
            J < 0 || ...
            J >= CFG.cost.failurePenalty
        J = CFG.cost.failurePenalty;
        candidateObjectiveValid = false;
    end
else
    J = CFG.cost.failurePenalty;
end
RESULT = emptyCandidateResult();
RESULT.success = ...
    candidateObjectiveValid;
RESULT.cost = J;
RESULT.z = CANDIDATE.z;
RESULT.multipliers = CANDIDATE.multipliers;
RESULT.tunedVector = CANDIDATE.tunedVector;
RESULT.metrics = RUN;
RESULT.runSucceeded = runSucceeded;
RESULT.messages = messages;
RESULT.runCost = runCost;
RESULT.meanCost = meanCost;
RESULT.stdCost = stdCost;
RESULT.worstCost = worstCost;
RESULT.regularization = regularization;
RESULT.meanMetrics = ...
    meanMetrics(RUN,runSucceeded);
end
function [J,RESULT] = invalidCandidateResult( ...
    z, ...
    CFG, ...
    nominalVector, ...
    baselineMetrics, ...
    message)
z = double(z(:));
if isempty(baselineMetrics)
    J = NaN;
else
    J = CFG.cost.failurePenalty;
end
RESULT = emptyCandidateResult();
RESULT.success = false;
RESULT.cost = J;
RESULT.z = z;
if numel(z) == CFG.numberOfParameters && ...
        all(isfinite(z))
    RESULT.multipliers = 10.^z;
    RESULT.tunedVector = ...
        nominalVector .* RESULT.multipliers;
end
numberOfSeeds = ...
    numel(CFG.training.seedOffsets);
RESULT.metrics = repmat( ...
    emptyMetricStructure(), ...
    numberOfSeeds, ...
    1);
RESULT.runSucceeded = false(numberOfSeeds,1);
RESULT.messages = repmat( ...
    {message}, ...
    numberOfSeeds, ...
    1);
RESULT.runCost = ...
    CFG.cost.failurePenalty * ...
    ones(numberOfSeeds,1);
RESULT.meanCost = ...
    CFG.cost.failurePenalty;
RESULT.stdCost = 0;
RESULT.worstCost = ...
    CFG.cost.failurePenalty;
RESULT.regularization = NaN;
RESULT.meanMetrics = ...
    meanMetrics( ...
        RESULT.metrics, ...
        RESULT.runSucceeded);
end
function J = normalizedCost(M,B,CFG)
minimumNormalization = ...
    CFG.cost.minimumNormalization;
ratioPosition = ...
    M.PositionRMSE_m / ...
    max( ...
        B.PositionRMSE_m, ...
        minimumNormalization);
ratioHorizontal = ...
    M.HorizontalPositionRMSE_m / ...
    max( ...
        B.HorizontalPositionRMSE_m, ...
        minimumNormalization);
ratioVelocity = ...
    M.VelocityRMSE_m_s / ...
    max( ...
        B.VelocityRMSE_m_s, ...
        minimumNormalization);
ratioAttitude = ...
    M.AttitudeRMSE_deg / ...
    max( ...
        B.AttitudeRMSE_deg, ...
        minimumNormalization);
ratioRate = ...
    M.AngularRateRMSE_rad_s / ...
    max( ...
        B.AngularRateRMSE_rad_s, ...
        minimumNormalization);
ratioAcceleration = ...
    M.AccelerationRMSE_m_s2 / ...
    max( ...
        B.AccelerationRMSE_m_s2, ...
        minimumNormalization);
ratioPositionP95 = ...
    M.PositionP95_m / ...
    max( ...
        B.PositionP95_m, ...
        minimumNormalization);
ratioAttitudeP95 = ...
    M.AttitudeP95_deg / ...
    max( ...
        B.AttitudeP95_deg, ...
        minimumNormalization);
W = CFG.cost.weight;
J = ...
    W.positionRMSE * ratioPosition + ...
    W.horizontalPositionRMSE * ratioHorizontal + ...
    W.velocityRMSE * ratioVelocity + ...
    W.attitudeRMSE * ratioAttitude + ...
    W.angularRateRMSE * ratioRate + ...
    W.accelerationRMSE * ratioAcceleration + ...
    W.positionP95 * ratioPositionP95 + ...
    W.attitudeP95 * ratioAttitudeP95;
if ~isfinite(J) || J < 0
    J = CFG.cost.failurePenalty;
end
end
function M = extractMetrics( ...
    out, ...
    ESTIMATOR, ...
    CFG)
if ~isa(out,'Simulink.SimulationOutput')
    error( ...
        'QuadrotorFramework:EstimatorTuningOutput', ...
        'Simulation did not return a SimulationOutput object.');
end
availableLogs = who(out);
requiredLogs = { ...
    'estimatorComparisonLog', ...
    'liveTelemetryLog'};
for logIndex = 1:numel(requiredLogs)
    if ~ismember( ...
            requiredLogs{logIndex}, ...
            availableLogs)
        error( ...
            'QuadrotorFramework:EstimatorTuningMissingLog', ...
            'Missing out.%s.', ...
            requiredLogs{logIndex});
    end
end
COMP = out.estimatorComparisonLog;
LIVE = out.liveTelemetryLog;
if isfield(COMP,'Errors')
    ERR = COMP.Errors;
elseif isfield(COMP,'Erros')
    ERR = COMP.Erros;
else
    error( ...
        'QuadrotorFramework:EstimatorTuningErrorsBus', ...
        'EstimatorComparison does not contain Errors.');
end
if ~isfield(COMP,'Norms')
    error( ...
        'QuadrotorFramework:EstimatorTuningNormsBus', ...
        'EstimatorComparison does not contain Norms.');
end
NORMS = COMP.Norms;
[tPositionError,PositionError] = ...
    signalMatrix(ERR.PositionError);
[tVelocityError,VelocityError] = ...
    signalMatrix(ERR.VelocityError);
[tEulerError,EulerError] = ...
    signalMatrix(ERR.EulerError);
[tAngularRateError,AngularRateError] = ...
    signalMatrix(ERR.AngularRateError);
[tAccelerationError,AccelerationError] = ...
    signalMatrix(ERR.AccelerationError);
[tPositionNorm,PositionNorm] = ...
    signalMatrix(NORMS.PositionErrorNorm);
[tVelocityNorm,VelocityNorm] = ...
    signalMatrix(NORMS.VelocityErrorNorm);
[tAttitudeNorm,AttitudeNorm] = ...
    signalMatrix(NORMS.AttitudeErrorNorm);
[tAngularRateNorm,AngularRateNorm] = ...
    signalMatrix(NORMS.AngularRateErrorNorm);
[tAccelerationNorm,AccelerationNorm] = ...
    signalMatrix(NORMS.AccelerationErrorNorm);
[tTelemetry,Telemetry] = ...
    signalMatrix(LIVE);
if size(Telemetry,2) < 8
    error( ...
        'QuadrotorFramework:EstimatorTuningTelemetrySize', ...
        'Telemetry must contain at least eight columns.');
end
Phase = ...
    round(double(Telemetry(:,2)));
CGSComplete = ...
    double(Telemetry(:,4)) > 0.5;
Landed = ...
    double(Telemetry(:,8)) > 0.5;
previousPhase = [ ...
    NaN; ...
    Phase(1:end-1)];
missionStartIndex = find( ...
    Phase == 1 & ...
    previousPhase ~= 1, ...
    1, ...
    'first');
if isempty(missionStartIndex)
    error( ...
        'QuadrotorFramework:EstimatorTuningNoMission', ...
        'No TAKEOFF phase was detected.');
end
if size(Telemetry,2) >= 59
    numWaypointsTrace = ...
        double( ...
            Telemetry( ...
                missionStartIndex:end, ...
                59));
    validNumWaypoints = ...
        isfinite(numWaypointsTrace) & ...
        numWaypointsTrace >= 3 & ...
        abs( ...
            numWaypointsTrace - ...
            round(numWaypointsTrace)) <= 1e-9;
    firstValidNumWaypoints = ...
        find( ...
            validNumWaypoints, ...
            1, ...
            'first');
    if isempty(firstValidNumWaypoints)
        error( ...
            'QuadrotorFramework:EstimatorTuningInvalidNumWaypoints', ...
            ['Telemetry(59) did not contain a finite integer ', ...
             'NumWaypoints >= 3 after mission start.']);
    end
    missionNumWaypoints = ...
        round( ...
            numWaypointsTrace( ...
                firstValidNumWaypoints));
else
    missionNumWaypoints = 7;
end
completePhase = ...
    2 * missionNumWaypoints - 2;
abortedPhase = ...
    2 * missionNumWaypoints - 1;
postStartIndices = ...
    missionStartIndex:numel(Phase);
relativeAbortIndex = find( ...
    Phase(postStartIndices) == abortedPhase, ...
    1, ...
    'first');
if ~isempty(relativeAbortIndex)
    abortIndex = ...
        postStartIndices(relativeAbortIndex);
    error( ...
        'QuadrotorFramework:EstimatorTuningMissionAborted', ...
        ['Candidate entered generic ABORTED / navigation-failsafe ', ...
         'phase %d at t = %.6f s.'], ...
        abortedPhase, ...
        tTelemetry(abortIndex));
end
landedAfterMissionStart = ...
    Landed(missionStartIndex:end);
firstAirborneRelativeIndex = find( ...
    ~landedAfterMissionStart, ...
    1, ...
    'first');
if isempty(firstAirborneRelativeIndex)
    error( ...
        'QuadrotorFramework:EstimatorTuningNoAirborneState', ...
        ['Candidate never transitioned from Landed=true ', ...
         'to Landed=false after mission start.']);
end
firstAirborneIndex = ...
    missionStartIndex + ...
    firstAirborneRelativeIndex - 1;
landingSearchStart = ...
    firstAirborneRelativeIndex + 1;
if landingSearchStart > ...
        numel(landedAfterMissionStart)
    error( ...
        'QuadrotorFramework:EstimatorTuningNoLanding', ...
        'Candidate became airborne but no final landing was detected.');
end
landingRisingEdge = find( ...
    landedAfterMissionStart(landingSearchStart:end) & ...
    ~landedAfterMissionStart(landingSearchStart-1:end-1), ...
    1, ...
    'first');
if isempty(landingRisingEdge)
    error( ...
        'QuadrotorFramework:EstimatorTuningNoLanding', ...
        ['Candidate became airborne but did not produce a ', ...
         'subsequent Landed false-to-true transition.']);
end
relativeLandingIndex = ...
    landingSearchStart + ...
    landingRisingEdge - 1;
landingIndex = ...
    missionStartIndex + ...
    relativeLandingIndex - 1;
missionIndices = ...
    missionStartIndex:landingIndex;
completionSearchIndices = ...
    firstAirborneIndex:landingIndex;
cgsCompleteRising = ...
    CGSComplete & ...
    ~[ ...
        false; ...
        CGSComplete(1:end-1)];
relativeCompleteIndex = find( ...
    cgsCompleteRising(completionSearchIndices), ...
    1, ...
    'first');
if isempty(relativeCompleteIndex)
    error( ...
        'QuadrotorFramework:EstimatorTuningMissionIncomplete', ...
        ['Candidate landed without reaching a new CGS Complete event ', ...
         'after becoming airborne. Incomplete or failsafe missions ', ...
         'are invalid for estimator tuning.']);
end
navigationCompleteIndex = ...
    completionSearchIndices(relativeCompleteIndex);
navigationCompleteTime = ...
    tTelemetry(navigationCompleteIndex);
completePhaseSeen = any( ...
    Phase(missionIndices) == completePhase);
missionStartTime = ...
    tTelemetry(missionStartIndex);
missionEndTime = ...
    tTelemetry(landingIndex);
readinessTime = ...
    double( ...
        ESTIMATOR.validation.metricStartTime_s);
commonStart = max([ ...
    tPositionError(1), ...
    tVelocityError(1), ...
    tEulerError(1), ...
    tAngularRateError(1), ...
    tAccelerationError(1), ...
    tPositionNorm(1), ...
    tVelocityNorm(1), ...
    tAttitudeNorm(1), ...
    tAngularRateNorm(1), ...
    tAccelerationNorm(1)]);
commonEnd = min([ ...
    tPositionError(end), ...
    tVelocityError(end), ...
    tEulerError(end), ...
    tAngularRateError(end), ...
    tAccelerationError(end), ...
    tPositionNorm(end), ...
    tVelocityNorm(end), ...
    tAttitudeNorm(end), ...
    tAngularRateNorm(end), ...
    tAccelerationNorm(end)]);
metricStart = max([ ...
    missionStartTime, ...
    readinessTime, ...
    commonStart]);
metricEnd = min( ...
    missionEndTime, ...
    commonEnd);
if metricEnd <= metricStart
    error( ...
        'QuadrotorFramework:EstimatorTuningEmptyWindow', ...
        [ ...
        'Estimator metric window is empty. ', ...
        'MissionStart=%.6f s, MissionEnd=%.6f s, ', ...
        'NavigationComplete=%.6f s, ', ...
        'Readiness=%.6f s, CommonStart=%.6f s, ', ...
        'CommonEnd=%.6f s, MetricStart=%.6f s, ', ...
        'MetricEnd=%.6f s.'], ...
        missionStartTime, ...
        missionEndTime, ...
        navigationCompleteTime, ...
        readinessTime, ...
        commonStart, ...
        commonEnd, ...
        metricStart, ...
        metricEnd);
end
Fs = CFG.simulation.metricSampleRate_Hz;
metricTime = ( ...
    metricStart: ...
    1/Fs: ...
    metricEnd).';
if isempty(metricTime)
    error( ...
        'QuadrotorFramework:EstimatorTuningMetricGrid', ...
        'Estimator metric time grid is empty.');
end
if metricTime(end) < ...
        metricEnd - 0.25/Fs
    metricTime(end+1,1) = metricEnd;
end
PositionError = interpSignal( ...
    tPositionError, ...
    PositionError, ...
    metricTime);
VelocityError = interpSignal( ...
    tVelocityError, ...
    VelocityError, ...
    metricTime);
EulerError_deg = rad2deg( ...
    interpSignal( ...
        tEulerError, ...
        EulerError, ...
        metricTime));
AngularRateError = interpSignal( ...
    tAngularRateError, ...
    AngularRateError, ...
    metricTime);
AccelerationError = interpSignal( ...
    tAccelerationError, ...
    AccelerationError, ...
    metricTime);
PositionNorm = interpSignal( ...
    tPositionNorm, ...
    PositionNorm, ...
    metricTime);
VelocityNorm = interpSignal( ...
    tVelocityNorm, ...
    VelocityNorm, ...
    metricTime);
AttitudeNorm_deg = rad2deg( ...
    interpSignal( ...
        tAttitudeNorm, ...
        AttitudeNorm, ...
        metricTime));
AngularRateNorm = interpSignal( ...
    tAngularRateNorm, ...
    AngularRateNorm, ...
    metricTime);
AccelerationNorm = interpSignal( ...
    tAccelerationNorm, ...
    AccelerationNorm, ...
    metricTime);
M = emptyMetricStructure();
M.success = true;
M.PositionRMSE_m = ...
    rmsValue(PositionNorm);
M.HorizontalPositionRMSE_m = ...
    sqrt( ...
        mean( ...
            PositionError(:,1).^2 + ...
            PositionError(:,2).^2));
M.VelocityRMSE_m_s = ...
    rmsValue(VelocityNorm);
M.AttitudeRMSE_deg = ...
    rmsValue(AttitudeNorm_deg);
M.AngularRateRMSE_rad_s = ...
    rmsValue(AngularRateNorm);
M.AccelerationRMSE_m_s2 = ...
    rmsValue(AccelerationNorm);
M.PositionP95_m = ...
    percentile95(abs(PositionNorm));
M.AttitudeP95_deg = ...
    percentile95(abs(AttitudeNorm_deg));
M.PositionAxisRMSE_m = ...
    sqrt(mean(PositionError.^2,1));
M.VelocityAxisRMSE_m_s = ...
    sqrt(mean(VelocityError.^2,1));
M.EulerAxisRMSE_deg = ...
    sqrt(mean(EulerError_deg.^2,1));
M.AngularRateAxisRMSE_rad_s = ...
    sqrt(mean(AngularRateError.^2,1));
M.AccelerationAxisRMSE_m_s2 = ...
    sqrt(mean(AccelerationError.^2,1));
M.MissionStartTime_s = ...
    missionStartTime;
M.MissionEndTime_s = ...
    missionEndTime;
M.MetricStartTime_s = ...
    metricStart;
M.MetricEndTime_s = ...
    metricEnd;
M.MetricSamples = ...
    numel(metricTime);
M.NavigationCompleted = true;
M.NavigationCompleteTime_s = ...
    navigationCompleteTime;
M.LandedConfirmed = true;
M.FailsafeAborted = false;
M.NumWaypoints = ...
    missionNumWaypoints;
M.CompletePhase = ...
    completePhase;
M.CompletePhaseObserved = ...
    completePhaseSeen;
M.AbortedPhase = ...
    abortedPhase;
M.TrueFeedbackVerified = false;
M.SelectedVsTrueRMSE_m = NaN;
M.SelectedVsTrueZeroLagRMSE_m = NaN;
M.SelectedVsEstRMSE_m = NaN;
M.TrueFeedbackBestLag_samples = NaN;
M.EstFeedbackBestLag_samples = NaN;
if size(Telemetry,2) >= 58
    selectedPosition = ...
        double(Telemetry(:,12:14));
    truePosition = ...
        double(Telemetry(:,50:52));
    estPosition = ...
        double(Telemetry(:,56:58));
    missionMask = ...
        tTelemetry >= missionStartTime & ...
        tTelemetry <= missionEndTime;
    selectedMission = ...
        selectedPosition(missionMask,:);
    trueMission = ...
        truePosition(missionMask,:);
    estMission = ...
        estPosition(missionMask,:);
    finiteTrueZeroLag = ...
        all(isfinite(selectedMission),2) & ...
        all(isfinite(trueMission),2);
    if any(finiteTrueZeroLag)
        zeroLagDifference = ...
            selectedMission(finiteTrueZeroLag,:) - ...
            trueMission(finiteTrueZeroLag,:);
        M.SelectedVsTrueZeroLagRMSE_m = ...
            sqrt( ...
                mean( ...
                    sum( ...
                        zeroLagDifference.^2, ...
                        2)));
    end
    telemetryDt = diff( ...
        tTelemetry(missionMask));
    telemetryDt = telemetryDt( ...
        isfinite(telemetryDt) & ...
        telemetryDt > 0);
    if isempty(telemetryDt)
        maxLagSamples = 10;
    else
        nominalTelemetryDt = ...
            median(telemetryDt);
        maxLagSamples = ...
            max( ...
                2, ...
                ceil( ...
                    0.050 / ...
                    nominalTelemetryDt));
        maxLagSamples = ...
            min( ...
                maxLagSamples, ...
                20);
    end
    maxPossibleLag = ...
        max( ...
            0, ...
            floor( ...
                (size(selectedMission,1)-20) / 2));
    maxLagSamples = ...
        min( ...
            maxLagSamples, ...
            maxPossibleLag);
    [ ...
        M.SelectedVsTrueRMSE_m, ...
        M.TrueFeedbackBestLag_samples] = ...
        bestAlignedRMSE( ...
            selectedMission, ...
            trueMission, ...
            maxLagSamples);
    [ ...
        M.SelectedVsEstRMSE_m, ...
        M.EstFeedbackBestLag_samples] = ...
        bestAlignedRMSE( ...
            selectedMission, ...
            estMission, ...
            maxLagSamples);
    strictTrueMatch = ...
        isfinite(M.SelectedVsTrueRMSE_m) && ...
        M.SelectedVsTrueRMSE_m <= ...
            CFG.simulation.trueFeedbackTolerance_m;
    decisiveTrueMatch = ...
        isfinite(M.SelectedVsTrueRMSE_m) && ...
        isfinite(M.SelectedVsEstRMSE_m) && ...
        M.SelectedVsEstRMSE_m > 0 && ...
        M.SelectedVsTrueRMSE_m <= ...
            0.05 * M.SelectedVsEstRMSE_m;
    M.TrueFeedbackVerified = ...
        strictTrueMatch || ...
        decisiveTrueMatch;
end
if CFG.simulation.requireTrueFeedback && ...
        ~M.TrueFeedbackVerified
    error( ...
        'QuadrotorFramework:EstimatorTuningRequiresTrueFeedback', ...
        [ ...
        'Estimator tuning requires TRUE feedback. ', ...
        'Delay-aware verification failed. ', ...
        'Operational-vs-TRUE RMSE = %.6g m ', ...
        '(zero-lag %.6g m, best lag %.0f samples); ', ...
        'Operational-vs-EST RMSE = %.6g m ', ...
        '(best lag %.0f samples).'], ...
        M.SelectedVsTrueRMSE_m, ...
        M.SelectedVsTrueZeroLagRMSE_m, ...
        M.TrueFeedbackBestLag_samples, ...
        M.SelectedVsEstRMSE_m, ...
        M.EstFeedbackBestLag_samples);
end
end
function [t,x] = signalMatrix(signal)
if isa(signal,'Simulink.SimulationData.Signal')
    signal = signal.Values;
end
if isa(signal,'timeseries')
    t = double(signal.Time(:));
    x = double(signal.Data);
elseif isstruct(signal) && ...
        isfield(signal,'Time') && ...
        isfield(signal,'Data')
    t = double(signal.Time(:));
    x = double(signal.Data);
else
    error( ...
        'QuadrotorFramework:EstimatorTuningSignalType', ...
        'Unsupported logged signal type.');
end
x = squeeze(x);
if isvector(x)
    x = x(:);
elseif size(x,1) ~= numel(t) && ...
        size(x,2) == numel(t)
    x = x.';
end
if size(x,1) ~= numel(t)
    error( ...
        'QuadrotorFramework:EstimatorTuningSignalDimensions', ...
        'Signal data and time dimensions do not agree.');
end
finiteTime = isfinite(t);
t = t(finiteTime);
x = x(finiteTime,:);
if isempty(t)
    error( ...
        'QuadrotorFramework:EstimatorTuningSignalEmpty', ...
        'Logged signal contains no finite timestamps.');
end
[t,uniqueIndex] = unique( ...
    t, ...
    'stable');
x = x(uniqueIndex,:);
if numel(t) < 2
    error( ...
        'QuadrotorFramework:EstimatorTuningSignalSamples', ...
        'Logged signal contains fewer than two unique samples.');
end
end
function xq = interpSignal(t,x,tq)
xq = interp1( ...
    t, ...
    x, ...
    tq, ...
    'linear');
if any(~isfinite(xq(:)))
    error( ...
        'QuadrotorFramework:EstimatorTuningInterpolation', ...
        'Interpolation generated NaN or Inf.');
end
end
function [bestRMSE,bestLag] = ...
    bestAlignedRMSE( ...
        selected, ...
        reference, ...
        maxLagSamples)
selected = double(selected);
reference = double(reference);
bestRMSE = Inf;
bestLag = NaN;
numberOfSamples = min( ...
    size(selected,1), ...
    size(reference,1));
selected = selected( ...
    1:numberOfSamples, ...
    :);
reference = reference( ...
    1:numberOfSamples, ...
    :);
if numberOfSamples < 2
    bestRMSE = NaN;
    return;
end
maxLagSamples = ...
    max( ...
        0, ...
        min( ...
            round(maxLagSamples), ...
            numberOfSamples-2));
for lag = -maxLagSamples:maxLagSamples
    if lag > 0
        selectedAligned = ...
            selected(1+lag:end,:);
        referenceAligned = ...
            reference(1:end-lag,:);
    elseif lag < 0
        shift = -lag;
        selectedAligned = ...
            selected(1:end-shift,:);
        referenceAligned = ...
            reference(1+shift:end,:);
    else
        selectedAligned = selected;
        referenceAligned = reference;
    end
    finiteRows = ...
        all(isfinite(selectedAligned),2) & ...
        all(isfinite(referenceAligned),2);
    if nnz(finiteRows) < 20
        continue;
    end
    difference = ...
        selectedAligned(finiteRows,:) - ...
        referenceAligned(finiteRows,:);
    currentRMSE = ...
        sqrt( ...
            mean( ...
                sum( ...
                    difference.^2, ...
                    2)));
    if isfinite(currentRMSE) && ...
            currentRMSE < bestRMSE
        bestRMSE = currentRMSE;
        bestLag = lag;
    end
end
if ~isfinite(bestRMSE)
    bestRMSE = NaN;
    bestLag = NaN;
end
end
function value = rmsValue(x)
x = double(x(:));
x = x(isfinite(x));
if isempty(x)
    value = NaN;
    return;
end
value = sqrt(mean(x.^2));
end
function value = percentile95(x)
x = double(x(:));
x = x(isfinite(x));
x = sort(x);
if isempty(x)
    value = NaN;
    return;
end
if numel(x) == 1
    value = x(1);
    return;
end
location = ...
    1 + ...
    0.95 * ...
    (numel(x)-1);
lowerIndex = floor(location);
upperIndex = ceil(location);
if lowerIndex == upperIndex
    value = x(lowerIndex);
else
    fraction = ...
        location - lowerIndex;
    value = ...
        (1-fraction) * x(lowerIndex) + ...
        fraction * x(upperIndex);
end
end
function RESULT = emptyCandidateResult()
RESULT = struct();
RESULT.success = false;
RESULT.cost = NaN;
RESULT.z = [];
RESULT.multipliers = [];
RESULT.tunedVector = [];
RESULT.metrics = repmat( ...
    emptyMetricStructure(), ...
    0, ...
    1);
RESULT.runSucceeded = false(0,1);
RESULT.messages = cell(0,1);
RESULT.runCost = [];
RESULT.meanCost = NaN;
RESULT.stdCost = NaN;
RESULT.worstCost = NaN;
RESULT.regularization = NaN;
RESULT.meanMetrics = ...
    emptyMetricStructure();
end
function M = emptyMetricStructure()
M = struct();
M.success = false;
M.PositionRMSE_m = NaN;
M.HorizontalPositionRMSE_m = NaN;
M.VelocityRMSE_m_s = NaN;
M.AttitudeRMSE_deg = NaN;
M.AngularRateRMSE_rad_s = NaN;
M.AccelerationRMSE_m_s2 = NaN;
M.PositionP95_m = NaN;
M.AttitudeP95_deg = NaN;
M.PositionAxisRMSE_m = NaN(1,3);
M.VelocityAxisRMSE_m_s = NaN(1,3);
M.EulerAxisRMSE_deg = NaN(1,3);
M.AngularRateAxisRMSE_rad_s = NaN(1,3);
M.AccelerationAxisRMSE_m_s2 = NaN(1,3);
M.MissionStartTime_s = NaN;
M.MissionEndTime_s = NaN;
M.MetricStartTime_s = NaN;
M.MetricEndTime_s = NaN;
M.MetricSamples = NaN;
M.NavigationCompleted = false;
M.NavigationCompleteTime_s = NaN;
M.LandedConfirmed = false;
M.FailsafeAborted = false;
M.NumWaypoints = NaN;
M.CompletePhase = NaN;
M.CompletePhaseObserved = false;
M.AbortedPhase = NaN;
M.TrueFeedbackVerified = false;
M.SelectedVsTrueRMSE_m = NaN;
M.SelectedVsTrueZeroLagRMSE_m = NaN;
M.SelectedVsEstRMSE_m = NaN;
M.TrueFeedbackBestLag_samples = NaN;
M.EstFeedbackBestLag_samples = NaN;
M.SeedOffset = NaN;
end
function M = meanMetrics(RUN,success)
M = emptyMetricStructure();
success = logical(success(:));
if isempty(success) || ...
        ~any(success)
    return;
end
R = RUN(success);
M.success = true;
M.PositionRMSE_m = ...
    mean([R.PositionRMSE_m]);
M.HorizontalPositionRMSE_m = ...
    mean([R.HorizontalPositionRMSE_m]);
M.VelocityRMSE_m_s = ...
    mean([R.VelocityRMSE_m_s]);
M.AttitudeRMSE_deg = ...
    mean([R.AttitudeRMSE_deg]);
M.AngularRateRMSE_rad_s = ...
    mean([R.AngularRateRMSE_rad_s]);
M.AccelerationRMSE_m_s2 = ...
    mean([R.AccelerationRMSE_m_s2]);
M.PositionP95_m = ...
    mean([R.PositionP95_m]);
M.AttitudeP95_deg = ...
    mean([R.AttitudeP95_deg]);
M.PositionAxisRMSE_m = ...
    mean( ...
        vertcat(R.PositionAxisRMSE_m), ...
        1);
M.VelocityAxisRMSE_m_s = ...
    mean( ...
        vertcat(R.VelocityAxisRMSE_m_s), ...
        1);
M.EulerAxisRMSE_deg = ...
    mean( ...
        vertcat(R.EulerAxisRMSE_deg), ...
        1);
M.AngularRateAxisRMSE_rad_s = ...
    mean( ...
        vertcat(R.AngularRateAxisRMSE_rad_s), ...
        1);
M.AccelerationAxisRMSE_m_s2 = ...
    mean( ...
        vertcat(R.AccelerationAxisRMSE_m_s2), ...
        1);
M.MissionStartTime_s = ...
    mean([R.MissionStartTime_s]);
M.MissionEndTime_s = ...
    mean([R.MissionEndTime_s]);
M.MetricStartTime_s = ...
    mean([R.MetricStartTime_s]);
M.MetricEndTime_s = ...
    mean([R.MetricEndTime_s]);
M.MetricSamples = ...
    mean([R.MetricSamples]);
M.NavigationCompleted = ...
    all([R.NavigationCompleted]);
M.NavigationCompleteTime_s = ...
    mean([R.NavigationCompleteTime_s]);
M.LandedConfirmed = ...
    all([R.LandedConfirmed]);
M.FailsafeAborted = ...
    any([R.FailsafeAborted]);
M.NumWaypoints = ...
    mean([R.NumWaypoints]);
M.CompletePhase = ...
    mean([R.CompletePhase]);
M.CompletePhaseObserved = ...
    all([R.CompletePhaseObserved]);
M.AbortedPhase = ...
    mean([R.AbortedPhase]);
M.TrueFeedbackVerified = ...
    all([R.TrueFeedbackVerified]);
M.SelectedVsTrueRMSE_m = ...
    mean([R.SelectedVsTrueRMSE_m]);
M.SelectedVsTrueZeroLagRMSE_m = ...
    mean([R.SelectedVsTrueZeroLagRMSE_m]);
M.SelectedVsEstRMSE_m = ...
    mean([R.SelectedVsEstRMSE_m]);
M.TrueFeedbackBestLag_samples = ...
    mean([R.TrueFeedbackBestLag_samples]);
M.EstFeedbackBestLag_samples = ...
    mean([R.EstFeedbackBestLag_samples]);
end
