clc
requiredVariables = { ...
    'ESTIMATOR', ...
    'SENSOR', ...
    'P_ENV', ...
    'AUTO_PROTOCOL', ...
    'TRAJECTORY_ID'};
projectInitialized = true;
for k = 1:numel(requiredVariables)
    if ~evalin('base', ...
            sprintf('exist(''%s'',''var'')',requiredVariables{k}))
        projectInitialized = false;
        break;
    end
end
if ~projectInitialized
    fprintf('Project not initialized. Running initialize_project...\n');
    initialize_project;
end
clear evaluate_estimator_candidate
clear evaluate_estimator_candidates_parallel
rehash
CFG = estimator_tuning_config;
nominalVector = ...
    ESTIMATOR.tuning.nominalVector(:);
tunerFile = ...
    which('tune_state_estimator');
assert(~isempty(tunerFile), ...
    'Could not locate tune_state_estimator.m');
tuningFolder = ...
    fileparts(tunerFile);
projectRoot = ...
    fileparts(tuningFolder);
resultsRoot = ...
    fullfile( ...
        projectRoot, ...
        CFG.output.rootFolder);
D = ...
    dir( ...
        fullfile( ...
            resultsRoot, ...
            'EKF_Tuning_*'));
assert(~isempty(D), ...
    'No EKF tuning result folders were found.');
[~,idx] = ...
    max([D.datenum]);
runFolder = ...
    fullfile( ...
        D(idx).folder, ...
        D(idx).name);
checkpointFile = ...
    fullfile( ...
        runFolder, ...
        CFG.output.checkpointFile);
assert(isfile(checkpointFile), ...
    'Checkpoint file not found: %s', ...
    checkpointFile);
fprintf('\n========================================\n');
fprintf(' SAVED CANDIDATE SCREEN\n');
fprintf('========================================\n');
fprintf('Run folder:\n%s\n\n', ...
    runFolder);
fprintf('Recovering surrogateopt trials...\n');
[~,~,~,~,trials] = ...
    surrogateopt( ...
        checkpointFile);
assert(isfield(trials,'X'), ...
    'surrogateopt trials do not contain X.');
assert(isfield(trials,'Fval'), ...
    'surrogateopt trials do not contain Fval.');
X = ...
    double( ...
        trials.X);
Ftrain = ...
    double( ...
        trials.Fval(:));
assert(size(X,1) == numel(Ftrain), ...
    'Trial candidate and cost counts do not agree.');
validTrial = ...
    all(isfinite(X),2) & ...
    isfinite(Ftrain) & ...
    Ftrain < CFG.cost.failurePenalty;
X = ...
    X(validTrial,:);
Ftrain = ...
    Ftrain(validTrial);
[Ftrain,order] = ...
    sort( ...
        Ftrain, ...
        'ascend');
X = ...
    X(order,:);
[X,uniqueIndex] = ...
    unique( ...
        X, ...
        'rows', ...
        'stable');
Ftrain = ...
    Ftrain(uniqueIndex);
fprintf('Valid unique training candidates: %d\n', ...
    size(X,1));
firstCandidate = 33;
lastCandidate  = min(64,size(X,1));
assert(firstCandidate <= size(X,1), ...
    ['There are only %d valid saved candidates. ', ...
     'Cannot start screening at candidate 33.'], ...
    size(X,1));
Xscreen = ...
    X( ...
        firstCandidate:lastCandidate, ...
        :);
FtrainScreen = ...
    Ftrain( ...
        firstCandidate:lastCandidate);
numberToValidate = ...
    size( ...
        Xscreen, ...
        1);
fprintf('Candidate ranks:                  %d-%d\n', ...
    firstCandidate, ...
    lastCandidate);
fprintf('Candidates to validate:           %d\n', ...
    numberToValidate);
validationCFG = ...
    CFG;
validationCFG.training.seedOffsets = ...
    CFG.validation.seedOffsets;
fprintf('Validation seeds:                 %s\n', ...
    mat2str( ...
        validationCFG.training.seedOffsets.'));
fprintf('\nEvaluating nominal validation baseline...\n');
zNominal = ...
    zeros( ...
        CFG.numberOfParameters, ...
        1);
[~,validationBaseline] = ...
    evaluate_estimator_candidate( ...
        zNominal, ...
        validationCFG, ...
        nominalVector, ...
        [], ...
        'serial');
if ~validationBaseline.success
    fprintf('\nNominal validation failed:\n');
    for k = 1:numel(validationBaseline.messages)
        fprintf( ...
            'Seed %g: %s\n', ...
            validationCFG.training.seedOffsets(k), ...
            validationBaseline.messages{k});
    end
    error( ...
        'Nominal validation baseline must succeed.');
end
fprintf('Nominal validation baseline:      OK\n');
fprintf('\nValidating candidates %d-%d...\n', ...
    firstCandidate, ...
    lastCandidate);
screenTimer = ...
    tic;
[Jvalidation,validationResults] = ...
    evaluate_estimator_candidate( ...
        Xscreen, ...
        validationCFG, ...
        nominalVector, ...
        validationBaseline.metrics, ...
        'parallel');
screenElapsed_s = ...
    toc(screenTimer);
Jvalidation = ...
    double( ...
        Jvalidation(:));
candidateSuccess = ...
    reshape( ...
        [validationResults.success], ...
        [], ...
        1);
numberOfSeeds = ...
    numel( ...
        validationCFG.training.seedOffsets);
seedSuccessCount = ...
    zeros( ...
        numberOfSeeds, ...
        1);
for candidateIndex = ...
        1:numberToValidate
    currentSuccess = ...
        logical( ...
            validationResults(candidateIndex).runSucceeded(:));
    for seedIndex = ...
            1:numberOfSeeds
        if currentSuccess(seedIndex)
            seedSuccessCount(seedIndex) = ...
                seedSuccessCount(seedIndex) + 1;
        end
    end
end
robustIndices = ...
    find( ...
        candidateSuccess & ...
        isfinite(Jvalidation) & ...
        Jvalidation < CFG.cost.failurePenalty);
fprintf('\n========================================\n');
fprintf(' ROBUST CANDIDATE SCREEN\n');
fprintf('========================================\n');
fprintf('Candidate ranks tested:  %d-%d\n', ...
    firstCandidate, ...
    lastCandidate);
fprintf('Candidates tested:       %d\n', ...
    numberToValidate);
fprintf('Validation successful:   %d\n', ...
    numel(robustIndices));
fprintf('Elapsed time:            %.2f min\n', ...
    screenElapsed_s / 60);
fprintf('\nPER-SEED SUCCESS\n');
for seedIndex = ...
        1:numberOfSeeds
    fprintf( ...
        'Seed %g: %d / %d candidates successful\n', ...
        validationCFG.training.seedOffsets(seedIndex), ...
        seedSuccessCount(seedIndex), ...
        numberToValidate);
end
if isempty(robustIndices)
    fprintf('\nNO robust candidate found in ranks %d-%d.\n', ...
        firstCandidate, ...
        lastCandidate);
    seed509Index = ...
        find( ...
            validationCFG.training.seedOffsets == 509, ...
            1);
    if ~isempty(seed509Index)
        fprintf('\nSeed 509 failure summary:\n');
        failureMessages = ...
            cell( ...
                numberToValidate, ...
                1);
        for candidateIndex = ...
                1:numberToValidate
            failureMessages{candidateIndex} = ...
                validationResults(candidateIndex).messages{seed509Index};
        end
        [uniqueMessages,~,messageGroup] = ...
            unique( ...
                failureMessages);
        for messageIndex = ...
                1:numel(uniqueMessages)
            count = ...
                nnz( ...
                    messageGroup == messageIndex);
            fprintf( ...
                '  %d x %s\n', ...
                count, ...
                uniqueMessages{messageIndex});
        end
    end
else
    [bestValidationCost,relativeBestIndex] = ...
        min( ...
            Jvalidation(robustIndices));
    bestIndex = ...
        robustIndices(relativeBestIndex);
    originalRank = ...
        firstCandidate + ...
        bestIndex - ...
        1;
    bestRobustZ = ...
        Xscreen(bestIndex,:).';
    bestRobustTrainingCost = ...
        FtrainScreen(bestIndex);
    bestRobustResult = ...
        validationResults(bestIndex);
    fprintf('\nBEST ROBUST CANDIDATE\n');
    fprintf('Saved candidate rank:     %d\n', ...
        originalRank);
    fprintf('Training cost:            %.6f\n', ...
        bestRobustTrainingCost);
    fprintf('Validation cost:          %.6f\n', ...
        bestValidationCost);
    fprintf('Validation improvement:   %.2f %%\n', ...
        100 * ...
        (1 - bestValidationCost));
    fprintf('\nVALIDATION METRICS\n');
    fprintf( ...
        'Position RMSE:            %.6f -> %.6f m\n', ...
        validationBaseline.meanMetrics.PositionRMSE_m, ...
        bestRobustResult.meanMetrics.PositionRMSE_m);
    fprintf( ...
        'Horizontal Position RMSE: %.6f -> %.6f m\n', ...
        validationBaseline.meanMetrics.HorizontalPositionRMSE_m, ...
        bestRobustResult.meanMetrics.HorizontalPositionRMSE_m);
    fprintf( ...
        'Velocity RMSE:            %.6f -> %.6f m/s\n', ...
        validationBaseline.meanMetrics.VelocityRMSE_m_s, ...
        bestRobustResult.meanMetrics.VelocityRMSE_m_s);
    fprintf( ...
        'Attitude RMSE:            %.6f -> %.6f deg\n', ...
        validationBaseline.meanMetrics.AttitudeRMSE_deg, ...
        bestRobustResult.meanMetrics.AttitudeRMSE_deg);
    ROBUST_SCREEN = ...
        struct();
    ROBUST_SCREEN.CandidateRank = ...
        originalRank;
    ROBUST_SCREEN.BestZ = ...
        bestRobustZ;
    ROBUST_SCREEN.BestMultiplier = ...
        10.^bestRobustZ;
    ROBUST_SCREEN.BestTunedVector = ...
        nominalVector .* ...
        ROBUST_SCREEN.BestMultiplier;
    ROBUST_SCREEN.TrainingCost = ...
        bestRobustTrainingCost;
    ROBUST_SCREEN.ValidationCost = ...
        bestValidationCost;
    ROBUST_SCREEN.ValidationResult = ...
        bestRobustResult;
    ROBUST_SCREEN.ValidationBaseline = ...
        validationBaseline;
    ROBUST_SCREEN.CandidateRanksTested = ...
        [firstCandidate lastCandidate];
    save( ...
        fullfile( ...
            runFolder, ...
            'Estimator_Robust_Candidate_Screen.mat'), ...
        ...
        'ROBUST_SCREEN', ...
        '-v7.3');
    assignin( ...
        'base', ...
        'ESTIMATOR_ROBUST_SCREEN', ...
        ROBUST_SCREEN);
    fprintf('\nRobust candidate saved successfully.\n');
end
fprintf('========================================\n');
