function TUNING_RESULT = tune_state_estimator()
thisFile = ...
    mfilename( ...
        'fullpath');
tuningFolder = ...
    fileparts( ...
        thisFile);
projectRoot = ...
    fileparts( ...
        tuningFolder);
addpath( ...
    tuningFolder);
addpath( ...
    projectRoot);
rehash;
CFG = ...
    estimator_tuning_config();
requiredOptimizerFields = { ...
    'method', ...
    'maxFunctionEvaluations', ...
    'minSurrogatePoints', ...
    'useParallel', ...
    'batchSize', ...
    'parallelUseFastRestart', ...
    'randomSeed', ...
    'display'};
if ~isfield(CFG,'optimizer') || ...
        ~isstruct(CFG.optimizer)
    error( ...
        'QuadrotorFramework:EstimatorTuningOptimizerConfig', ...
        'CFG.optimizer is missing or invalid.');
end
for fieldIndex = ...
        1:numel(requiredOptimizerFields)
    fieldName = ...
        requiredOptimizerFields{fieldIndex};
    if ~isfield( ...
            CFG.optimizer, ...
            fieldName)
        error( ...
            'QuadrotorFramework:EstimatorTuningOptimizerConfig', ...
            'Missing CFG.optimizer.%s.', ...
            fieldName);
    end
end
if ~strcmpi( ...
        CFG.optimizer.method, ...
        'surrogateopt')
    error( ...
        'QuadrotorFramework:EstimatorTuningOptimizerRequired', ...
        ['The 24-parameter EKF tuning campaign must use ', ...
         'surrogateopt.']);
end
if CFG.numberOfParameters ~= 24
    error( ...
        'QuadrotorFramework:EstimatorTuningParameterCount', ...
        'Estimator tuning requires exactly 24 parameters.');
end
surrogateoptPath = ...
    which( ...
        'surrogateopt');
if isempty(surrogateoptPath)
    error( ...
        'QuadrotorFramework:EstimatorTuningSurrogateUnavailable', ...
        ['surrogateopt is unavailable. Global Optimization Toolbox ', ...
         'must be installed and licensed.']);
end
activeConfigFile = ...
    which( ...
        'estimator_tuning_config');
activeEvaluatorFile = ...
    which( ...
        'evaluate_estimator_candidate');
if isempty(activeConfigFile)
    error( ...
        'QuadrotorFramework:EstimatorTuningConfigMissing', ...
        'Could not locate estimator_tuning_config.m.');
end
if isempty(activeEvaluatorFile)
    error( ...
        'QuadrotorFramework:EstimatorTuningEvaluatorMissing', ...
        'Could not locate evaluate_estimator_candidate.m.');
end
if ~strcmpi( ...
        fileparts(activeConfigFile), ...
        tuningFolder)
    error( ...
        'QuadrotorFramework:EstimatorTuningConfigShadowed', ...
        [ ...
        'The active estimator_tuning_config.m is not located in the ', ...
        'current Estimator_Tuning folder:\n%s'], ...
        activeConfigFile);
end
if ~strcmpi( ...
        fileparts(activeEvaluatorFile), ...
        tuningFolder)
    error( ...
        'QuadrotorFramework:EstimatorTuningEvaluatorShadowed', ...
        [ ...
        'The active evaluate_estimator_candidate.m is not located in ', ...
        'the current Estimator_Tuning folder:\n%s'], ...
        activeEvaluatorFile);
end
requiredVariables = { ...
    'ESTIMATOR', ...
    'SENSOR', ...
    'P_ENV', ...
    'AUTO_PROTOCOL', ...
    'TRAJECTORY_ID'};
for variableIndex = ...
        1:numel(requiredVariables)
    variableName = ...
        requiredVariables{variableIndex};
    if ~evalin( ...
            'base', ...
            sprintf( ...
                'exist(''%s'',''var'')', ...
                variableName))
        error( ...
            'QuadrotorFramework:EstimatorTuningNotInitialized', ...
            ['Missing %s. Run initialize_project.m ', ...
             'before tuning.'], ...
            variableName);
    end
end
modelFile = ...
    fullfile( ...
        projectRoot, ...
        [CFG.modelName '.slx']);
if ~isfile(modelFile)
    error( ...
        'QuadrotorFramework:EstimatorTuningModelMissing', ...
        'Could not find model file:\n%s', ...
        modelFile);
end
if ~bdIsLoaded(CFG.modelName)
    load_system( ...
        modelFile);
end
if ~strcmp( ...
        get_param( ...
            CFG.modelName, ...
            'SimulationStatus'), ...
        'stopped')
    error( ...
        'QuadrotorFramework:EstimatorTuningModelRunning', ...
        'Stop the Simulink model before estimator tuning.');
end
if strcmp( ...
        get_param( ...
            CFG.modelName, ...
            'Dirty'), ...
        'on')
    error( ...
        'QuadrotorFramework:EstimatorTuningUnsavedModel', ...
        [ ...
        'The model %s contains unsaved changes. ', ...
        'Save the model before starting estimator tuning.'], ...
        CFG.modelName);
end
ESTIMATOR = ...
    evalin( ...
        'base', ...
        'ESTIMATOR');
if ~isfield(ESTIMATOR,'tuning') || ...
        ~isstruct(ESTIMATOR.tuning) || ...
        ~isfield(ESTIMATOR.tuning,'nominalVector') || ...
        ~isfield(ESTIMATOR.tuning,'parameterCount')
    error( ...
        'QuadrotorFramework:EstimatorTuningInterface', ...
        ['The required UAV_state_estimator.m tuning interface ', ...
         'was not found.']);
end
if double(ESTIMATOR.tuning.parameterCount) ~= ...
        CFG.numberOfParameters
    error( ...
        'QuadrotorFramework:EstimatorTuningInterfaceCount', ...
        ['ESTIMATOR.tuning.parameterCount does not match the ', ...
         '24-parameter tuning configuration.']);
end
if isfield(ESTIMATOR.tuning,'overrideActive') && ...
        logical(ESTIMATOR.tuning.overrideActive)
    error( ...
        'QuadrotorFramework:EstimatorTuningAlreadyOverridden', ...
        [ ...
        'Start tuning from the nominal estimator. Clear ', ...
        'ESTIMATOR_TUNING_OVERRIDE and rerun initialize_project.m ', ...
        'or UAV_state_estimator.m.']);
end
nominalVector = ...
    double( ...
        ESTIMATOR.tuning.nominalVector(:));
if numel(nominalVector) ~= ...
        CFG.numberOfParameters
    error( ...
        'QuadrotorFramework:EstimatorTuningNominalVector', ...
        'Nominal vector must contain exactly 24 parameters.');
end
if any(~isfinite(nominalVector)) || ...
        any(nominalVector <= 0)
    error( ...
        'QuadrotorFramework:EstimatorTuningNominalVectorValues', ...
        ['All nominal estimator tuning parameters must be ', ...
         'finite and positive.']);
end
lowerBounds = ...
    double( ...
        CFG.lowerBounds(:).');
upperBounds = ...
    double( ...
        CFG.upperBounds(:).');
initialPoint = ...
    double( ...
        CFG.initialPoint(:).');
if numel(lowerBounds) ~= ...
        CFG.numberOfParameters || ...
        numel(upperBounds) ~= ...
        CFG.numberOfParameters || ...
        numel(initialPoint) ~= ...
        CFG.numberOfParameters
    error( ...
        'QuadrotorFramework:EstimatorTuningSearchSpace', ...
        'Search-space dimensions do not match the 24 parameters.');
end
if any(~isfinite(lowerBounds)) || ...
        any(~isfinite(upperBounds)) || ...
        any(lowerBounds >= upperBounds)
    error( ...
        'QuadrotorFramework:EstimatorTuningSearchBounds', ...
        'Estimator tuning search bounds are invalid.');
end
if any(initialPoint < lowerBounds) || ...
        any(initialPoint > upperBounds)
    error( ...
        'QuadrotorFramework:EstimatorTuningInitialPoint', ...
        'Initial estimator tuning point lies outside the bounds.');
end
requestedMaxEvaluations = ...
    double( ...
        CFG.optimizer.maxFunctionEvaluations);
minSurrogatePoints = ...
    double( ...
        CFG.optimizer.minSurrogatePoints);
requestedBatchSize = ...
    double( ...
        CFG.optimizer.batchSize);
if ~isscalar(requestedMaxEvaluations) || ...
        ~isfinite(requestedMaxEvaluations) || ...
        requestedMaxEvaluations < 1 || ...
        requestedMaxEvaluations ~= floor(requestedMaxEvaluations)
    error( ...
        'QuadrotorFramework:EstimatorTuningEvaluationBudget', ...
        'Maximum function evaluations must be a positive integer.');
end
if ~isscalar(minSurrogatePoints) || ...
        ~isfinite(minSurrogatePoints) || ...
        minSurrogatePoints < CFG.numberOfParameters + 1 || ...
        minSurrogatePoints ~= floor(minSurrogatePoints)
    error( ...
        'QuadrotorFramework:EstimatorTuningMinSurrogatePoints', ...
        ['MinSurrogatePoints must be an integer >= ', ...
         'numberOfParameters + 1.']);
end
if minSurrogatePoints > requestedMaxEvaluations
    error( ...
        'QuadrotorFramework:EstimatorTuningSurrogateBudget', ...
        ['MinSurrogatePoints (%d) exceeds ', ...
         'MaxFunctionEvaluations (%d).'], ...
        minSurrogatePoints, ...
        requestedMaxEvaluations);
end
if ~isscalar(requestedBatchSize) || ...
        ~isfinite(requestedBatchSize) || ...
        requestedBatchSize < 1 || ...
        requestedBatchSize ~= floor(requestedBatchSize)
    error( ...
        'QuadrotorFramework:EstimatorTuningBatchSize', ...
        'Optimizer batchSize must be a positive integer.');
end
effectiveMaxEvaluations = ...
    requestedMaxEvaluations;
resultsRoot = ...
    fullfile( ...
        projectRoot, ...
        CFG.output.rootFolder);
if exist(resultsRoot,'dir') ~= 7
    mkdir( ...
        resultsRoot);
end
timestamp = ...
    datestr( ...
        now, ...
        'yyyy-mm-dd_HH-MM-SS');
runFolder = ...
    fullfile( ...
        resultsRoot, ...
        ['EKF_Tuning_' timestamp]);
if exist(runFolder,'dir') == 7
    error( ...
        'QuadrotorFramework:EstimatorTuningRunFolderExists', ...
        'Estimator tuning run folder already exists.');
end
mkdir( ...
    runFolder);
parallelRequested = ...
    logical( ...
        CFG.optimizer.useParallel);
parallelPool = ...
    [];
parallelWorkers = ...
    0;
batchSize = ...
    1;
parsimPath = ...
    '';
parallelEvaluatorName = ...
    'evaluate_estimator_candidates_parallel';
parallelEvaluatorPath = ...
    '';
if parallelRequested
    parpoolPath = ...
        which( ...
            'parpool');
    parsimPath = ...
        which( ...
            'parsim');
    parallelEvaluatorPath = ...
        which( ...
            parallelEvaluatorName);
    if isempty(parpoolPath)
        error( ...
            'QuadrotorFramework:EstimatorTuningParallelUnavailable', ...
            ['Parallel Computing Toolbox is required for ', ...
             'parallel estimator tuning.']);
    end
    if isempty(parsimPath)
        error( ...
            'QuadrotorFramework:EstimatorTuningParsimUnavailable', ...
            'parsim is required for parallel estimator tuning.');
    end
    if isempty(parallelEvaluatorPath)
        error( ...
            'QuadrotorFramework:EstimatorTuningParallelEvaluatorMissing', ...
            'Parallel tuning requires %s.m.', ...
            parallelEvaluatorName);
    end
    if ~strcmpi( ...
            fileparts(parallelEvaluatorPath), ...
            tuningFolder)
        error( ...
            'QuadrotorFramework:EstimatorTuningParallelEvaluatorShadowed', ...
            [ ...
            'The active %s.m is not located in the current ', ...
            'Estimator_Tuning folder:\n%s'], ...
            parallelEvaluatorName, ...
            parallelEvaluatorPath);
    end
    if license('test','Simulink') ~= 1
        error( ...
            'QuadrotorFramework:EstimatorTuningSimulinkLicense', ...
            'A valid Simulink license is required.');
    end
    if license( ...
            'test', ...
            'Distrib_Computing_Toolbox') ~= 1
        error( ...
            'QuadrotorFramework:EstimatorTuningParallelLicense', ...
            'A valid Parallel Computing Toolbox license is required.');
    end
    parallelPool = ...
        gcp( ...
            'nocreate');
    if ~isempty(parallelPool) && ...
            isa( ...
                parallelPool, ...
                'parallel.ThreadPool')
        fprintf( ...
            ['Existing thread-based parallel pool detected. ', ...
             'Restarting as a process-based pool...\n']);
        delete( ...
            parallelPool);
        parallelPool = ...
            [];
    end
    if isempty(parallelPool)
        fprintf( ...
            'Starting process-based parallel pool...\n');
        parallelPool = ...
            parpool( ...
                'Processes');
    end
    if isempty(parallelPool) || ...
            ~isvalid(parallelPool)
        error( ...
            'QuadrotorFramework:EstimatorTuningParallelPool', ...
            'Parallel pool creation failed.');
    end
    parallelWorkers = ...
        double( ...
            parallelPool.NumWorkers);
    if parallelWorkers < 1
        error( ...
            'QuadrotorFramework:EstimatorTuningParallelWorkers', ...
            'Parallel pool contains no workers.');
    end
    batchSize = ...
        min( ...
            requestedBatchSize, ...
            effectiveMaxEvaluations);
    if batchSize < 1 || ...
            ~isfinite(batchSize)
        error( ...
            'QuadrotorFramework:EstimatorTuningBatchSize', ...
            'Effective vectorized batch size is invalid.');
    end
end
rngStateBeforeTuning = ...
    rng;
optimizerRNGStateStart = ...
    [];
configurationSnapshotFile = ...
    fullfile( ...
        runFolder, ...
        'Estimator_Tuning_Configuration.mat');
save( ...
    configurationSnapshotFile, ...
    ...
    'CFG', ...
    'nominalVector', ...
    'requestedMaxEvaluations', ...
    'effectiveMaxEvaluations', ...
    'minSurrogatePoints', ...
    'parallelRequested', ...
    'parallelWorkers', ...
    'batchSize', ...
    'rngStateBeforeTuning', ...
    '-v7.3');
snapshotFiles = { ...
    fullfile( ...
        tuningFolder, ...
        'estimator_tuning_config.m'), ...
    ...
    thisFile, ...
    ...
    fullfile( ...
        tuningFolder, ...
        'evaluate_estimator_candidate.m')};
if parallelRequested
    snapshotFiles{end+1} = ...
        fullfile( ...
            tuningFolder, ...
            [parallelEvaluatorName '.m']);
end
codeSnapshotFolder = ...
    fullfile( ...
        runFolder, ...
        'code_snapshot');
if exist(codeSnapshotFolder,'dir') ~= 7
    mkdir( ...
        codeSnapshotFolder);
end
for snapshotIndex = ...
        1:numel(snapshotFiles)
    sourceFile = ...
        snapshotFiles{snapshotIndex};
    if isfile(sourceFile)
        try
            copyfile( ...
                sourceFile, ...
                codeSnapshotFolder);
        catch ME
            warning( ...
                'QuadrotorFramework:EstimatorTuningCodeSnapshot', ...
                'Unable to snapshot %s: %s', ...
                sourceFile, ...
                ME.message);
        end
    end
end
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' EKF GLOBAL AUTOMATIC TUNING\n');
fprintf('==============================================================\n');
fprintf( ...
    'Parameters:                %d\n', ...
    CFG.numberOfParameters);
fprintf( ...
    'Optimizer:                 surrogateopt\n');
fprintf( ...
    'Training backend:          L%d\n', ...
    CFG.training.uavModel);
fprintf( ...
    'Training sensor seeds:     %s\n', ...
    mat2str( ...
        CFG.training.seedOffsets.'));
fprintf( ...
    'Validation sensor seeds:   %s\n', ...
    mat2str( ...
        CFG.validation.seedOffsets.'));
fprintf( ...
    'Requested evaluations:     %d\n', ...
    requestedMaxEvaluations);
fprintf( ...
    'Effective evaluations:     %d\n', ...
    effectiveMaxEvaluations);
fprintf( ...
    'Min surrogate points:      %d\n', ...
    minSurrogatePoints);
fprintf( ...
    'Parallel simulations:      %d\n', ...
    parallelRequested);
if parallelRequested
    fprintf( ...
        'Parallel workers:          %d\n', ...
        parallelWorkers);
    fprintf( ...
        'Vectorized batch size:     %d\n', ...
        batchSize);
    fprintf( ...
        'Fast Restart:              %d\n', ...
        logical( ...
            CFG.optimizer.parallelUseFastRestart));
    fprintf( ...
        'Parallel engine:           parsim\n');
end
fprintf( ...
    'Result folder:\n%s\n', ...
    runFolder);
fprintf('\nIMPORTANT: controller feedback must be TRUE.\n');
fprintf('Candidate missions must complete without ABORT.\n');
fprintf('Production estimator will NOT be overwritten.\n');
fprintf('==============================================================\n\n');
totalTimer = ...
    tic;
fprintf( ...
    'Evaluating nominal EKF training baseline...\n');
zNominal = ...
    zeros( ...
        CFG.numberOfParameters, ...
        1);
[~,trainingBaseline] = ...
    evaluate_estimator_candidate( ...
        zNominal, ...
        CFG, ...
        nominalVector, ...
        [], ...
        'serial');
if ~trainingBaseline.success
    fprintf('\nNominal training baseline FAILED:\n');
    printRunMessages( ...
        trainingBaseline, ...
        CFG.training.seedOffsets);
    baselineFailureFile = ...
        fullfile( ...
            runFolder, ...
            'Estimator_Tuning_Baseline_Failure.mat');
    save( ...
        baselineFailureFile, ...
        ...
        'CFG', ...
        'trainingBaseline', ...
        'nominalVector', ...
        '-v7.3');
    error( ...
        'QuadrotorFramework:EstimatorTuningBaselineFailed', ...
        ['Nominal estimator baseline must successfully complete ', ...
         'all training missions before optimization.']);
end
baselineMetrics = ...
    trainingBaseline.metrics;
fprintf('\nNominal training baseline: OK\n');
printMeanMetrics( ...
    trainingBaseline.meanMetrics);
save( ...
    fullfile( ...
        runFolder, ...
        'Estimator_Tuning_Training_Baseline.mat'), ...
    ...
    'trainingBaseline', ...
    'baselineMetrics', ...
    '-v7.3');
if parallelRequested
    fprintf( ...
        '\nRunning parallel objective preflight...\n');
    preflightCost = ...
        feval( ...
            parallelEvaluatorName, ...
            zNominal.', ...
            CFG, ...
            nominalVector, ...
            baselineMetrics);
    preflightCost = ...
        double( ...
            preflightCost(:));
    if numel(preflightCost) ~= 1 || ...
            ~isfinite(preflightCost(1)) || ...
            preflightCost(1) >= ...
                CFG.cost.failurePenalty
        error( ...
            'QuadrotorFramework:EstimatorTuningParallelPreflight', ...
            ['Parallel objective preflight failed. ', ...
             'Optimization was not started.']);
    end
    fprintf( ...
        'Parallel preflight cost:  %.6f\n', ...
        preflightCost(1));
    fprintf( ...
        'Parallel objective path:  OK\n');
else
    preflightCost = ...
        NaN;
end
if parallelRequested
    objective = ...
        @(Z) feval( ...
            parallelEvaluatorName, ...
            Z, ...
            CFG, ...
            nominalVector, ...
            baselineMetrics);
else
    objective = ...
        @(z) evaluate_estimator_candidate( ...
            z, ...
            CFG, ...
            nominalVector, ...
            baselineMetrics, ...
            'serial');
end
checkpointFile = ...
    fullfile( ...
        runFolder, ...
        CFG.output.checkpointFile);
if parallelRequested
    options = ...
        optimoptions( ...
            'surrogateopt', ...
            ...
            'MaxFunctionEvaluations', ...
            effectiveMaxEvaluations, ...
            ...
            'MinSurrogatePoints', ...
            minSurrogatePoints, ...
            ...
            'Display', ...
            CFG.optimizer.display, ...
            ...
            'UseParallel', ...
            false, ...
            ...
            'UseVectorized', ...
            true, ...
            ...
            'BatchUpdateInterval', ...
            batchSize, ...
            ...
            'InitialPoints', ...
            initialPoint, ...
            ...
            'CheckpointFile', ...
            checkpointFile);
else
    options = ...
        optimoptions( ...
            'surrogateopt', ...
            ...
            'MaxFunctionEvaluations', ...
            effectiveMaxEvaluations, ...
            ...
            'MinSurrogatePoints', ...
            minSurrogatePoints, ...
            ...
            'Display', ...
            CFG.optimizer.display, ...
            ...
            'UseParallel', ...
            false, ...
            ...
            'UseVectorized', ...
            false, ...
            ...
            'InitialPoints', ...
            initialPoint, ...
            ...
            'CheckpointFile', ...
            checkpointFile);
end
rng( ...
    CFG.optimizer.randomSeed, ...
    'twister');
optimizerRNGStateStart = ...
    rng;
fprintf( ...
    '\nStarting surrogate optimization...\n\n');
optimizationTimer = ...
    tic;
try
    [ ...
        bestZ, ...
        optimizerReportedCost, ...
        exitFlag, ...
        optimizerOutput, ...
        optimizerTrials] = ...
        surrogateopt( ...
            objective, ...
            lowerBounds, ...
            upperBounds, ...
            options);
catch ME
    optimizationElapsed_s = ...
        toc( ...
            optimizationTimer);
    failureFile = ...
        fullfile( ...
            runFolder, ...
            'Estimator_Tuning_Failure.mat');
    try
        save( ...
            failureFile, ...
            ...
            'ME', ...
            'CFG', ...
            'nominalVector', ...
            'trainingBaseline', ...
            'baselineMetrics', ...
            'checkpointFile', ...
            'requestedMaxEvaluations', ...
            'effectiveMaxEvaluations', ...
            'minSurrogatePoints', ...
            'parallelRequested', ...
            'parallelWorkers', ...
            'batchSize', ...
            'optimizerRNGStateStart', ...
            'optimizationElapsed_s', ...
            '-v7.3');
    catch
    end
    fprintf( ...
        '\nEstimator tuning stopped with an error.\n');
    fprintf( ...
        'Checkpoint file:\n%s\n', ...
        checkpointFile);
    fprintf( ...
        'Failure snapshot:\n%s\n', ...
        failureFile);
    rethrow(ME);
end
optimizationElapsed_s = ...
    toc( ...
        optimizationTimer);
bestZ = ...
    double( ...
        bestZ(:));
if numel(bestZ) ~= CFG.numberOfParameters || ...
        any(~isfinite(bestZ))
    error( ...
        'QuadrotorFramework:EstimatorTuningInvalidSolution', ...
        'surrogateopt returned an invalid tuning vector.');
end
if any(bestZ < CFG.lowerBounds(:)) || ...
        any(bestZ > CFG.upperBounds(:))
    error( ...
        'QuadrotorFramework:EstimatorTuningSolutionBounds', ...
        'surrogateopt returned a solution outside configured bounds.');
end
if ~isfinite(optimizerReportedCost)
    error( ...
        'QuadrotorFramework:EstimatorTuningInvalidCost', ...
        'surrogateopt returned a nonfinite objective value.');
end
optimizerTrialCount = ...
    NaN;
optimizerValidEvaluationCount = ...
    NaN;
optimizerFailedEvaluationCount = ...
    NaN;
optimizerValidEvaluationFraction = ...
    NaN;
optimizerPenaltyEvaluationCount = ...
    NaN;
optimizerNonfiniteEvaluationCount = ...
    NaN;
if isstruct(optimizerTrials) && ...
        isfield(optimizerTrials,'Fval')
    trialCosts = ...
        double( ...
            optimizerTrials.Fval(:));
    optimizerTrialCount = ...
        numel( ...
            trialCosts);
    finiteTrials = ...
        isfinite( ...
            trialCosts);
    validTrials = ...
        finiteTrials & ...
        trialCosts < ...
            CFG.cost.failurePenalty;
    penaltyTrials = ...
        finiteTrials & ...
        trialCosts >= ...
            CFG.cost.failurePenalty;
    optimizerValidEvaluationCount = ...
        nnz( ...
            validTrials);
    optimizerPenaltyEvaluationCount = ...
        nnz( ...
            penaltyTrials);
    optimizerNonfiniteEvaluationCount = ...
        nnz( ...
            ~finiteTrials);
    optimizerFailedEvaluationCount = ...
        optimizerTrialCount - ...
        optimizerValidEvaluationCount;
    if optimizerTrialCount > 0
        optimizerValidEvaluationFraction = ...
            optimizerValidEvaluationCount / ...
            optimizerTrialCount;
    end
end
fprintf('\nOPTIMIZER TRIAL DIAGNOSTICS\n');
fprintf( ...
    'Evaluations recorded:      %g\n', ...
    optimizerTrialCount);
fprintf( ...
    'Valid mission candidates:  %g\n', ...
    optimizerValidEvaluationCount);
fprintf( ...
    'Failed candidates:         %g\n', ...
    optimizerFailedEvaluationCount);
fprintf( ...
    'Failure-penalty trials:    %g\n', ...
    optimizerPenaltyEvaluationCount);
fprintf( ...
    'Nonfinite trials:          %g\n', ...
    optimizerNonfiniteEvaluationCount);
if isfinite(optimizerValidEvaluationFraction)
    fprintf( ...
        'Valid fraction:           %.1f %%\n', ...
        100 * optimizerValidEvaluationFraction);
end
fprintf( ...
    '\nRe-evaluating best candidate on training seeds...\n');
[bestCostCheck,bestTraining] = ...
    evaluate_estimator_candidate( ...
        bestZ, ...
        CFG, ...
        nominalVector, ...
        baselineMetrics, ...
        'serial');
if ~bestTraining.success || ...
        ~isfinite(bestCostCheck) || ...
        bestCostCheck >= CFG.cost.failurePenalty
    fprintf('\nBest training candidate FAILED re-evaluation:\n');
    printRunMessages( ...
        bestTraining, ...
        CFG.training.seedOffsets);
    bestFailureFile = ...
        fullfile( ...
            runFolder, ...
            'Estimator_Tuning_Best_Training_Failure.mat');
    save( ...
        bestFailureFile, ...
        ...
        'CFG', ...
        'bestZ', ...
        'optimizerReportedCost', ...
        'bestCostCheck', ...
        'bestTraining', ...
        'optimizerTrials', ...
        '-v7.3');
    error( ...
        'QuadrotorFramework:EstimatorTuningBestCandidateFailed', ...
        ['Best surrogateopt candidate failed deterministic ', ...
         'training re-evaluation.']);
end
fprintf( ...
    'Best training candidate:   OK\n');
costDifference = ...
    abs( ...
        double(optimizerReportedCost) - ...
        double(bestCostCheck));
costScale = ...
    max( ...
        1, ...
        abs( ...
            double(bestCostCheck)));
if costDifference > ...
        1e-5 * costScale
    warning( ...
        'QuadrotorFramework:EstimatorTuningCostMismatch', ...
        ['Optimizer-reported cost %.9g differs from final ', ...
         're-evaluation cost %.9g.'], ...
        optimizerReportedCost, ...
        bestCostCheck);
end
bestMultipliers = ...
    10.^bestZ;
bestTunedVector = ...
    nominalVector .* ...
    bestMultipliers;
if any(~isfinite(bestMultipliers)) || ...
        any(bestMultipliers <= 0) || ...
        any(~isfinite(bestTunedVector)) || ...
        any(bestTunedVector <= 0)
    error( ...
        'QuadrotorFramework:EstimatorTuningBestParameters', ...
        'Tuned estimator parameters must be finite and positive.');
end
bestOverride = ...
    struct();
for parameterIndex = ...
        1:CFG.numberOfParameters
    parameterName = ...
        CFG.parameterNames{parameterIndex};
    bestOverride.(parameterName) = ...
        bestTunedVector(parameterIndex);
end
fprintf( ...
    '\nRunning independent validation...\n');
validationCFG = ...
    CFG;
validationCFG.training.seedOffsets = ...
    CFG.validation.seedOffsets;
[~,validationBaseline] = ...
    evaluate_estimator_candidate( ...
        zNominal, ...
        validationCFG, ...
        nominalVector, ...
        [], ...
        'serial');
validationBaselinePassed = ...
    logical( ...
        validationBaseline.success);
validationCost = ...
    NaN;
validationPassed = ...
    false;
validationImproved = ...
    false;
if validationBaselinePassed
    fprintf( ...
        'Nominal validation baseline: OK\n');
    [validationCost,bestValidation] = ...
        evaluate_estimator_candidate( ...
            bestZ, ...
            validationCFG, ...
            nominalVector, ...
            validationBaseline.metrics, ...
            'serial');
    validationCost = ...
        double( ...
            validationCost);
    validationPassed = ...
        bestValidation.success && ...
        isfinite(validationCost) && ...
        validationCost < ...
            CFG.cost.failurePenalty;
    validationImproved = ...
        validationPassed && ...
        validationCost < 1.0;
    if validationPassed
        fprintf( ...
            'Tuned validation:         OK\n');
    else
        fprintf( ...
            '\nTuned validation:         FAILED\n');
        printRunMessages( ...
            bestValidation, ...
            validationCFG.training.seedOffsets);
    end
else
    fprintf( ...
        '\nNominal validation baseline: FAILED\n');
    printRunMessages( ...
        validationBaseline, ...
        validationCFG.training.seedOffsets);
    [~,bestValidation] = ...
        evaluate_estimator_candidate( ...
            bestZ, ...
            validationCFG, ...
            nominalVector, ...
            [], ...
            'serial');
    fprintf( ...
        ['Validation cost cannot be computed because the nominal ', ...
         'validation baseline was invalid.\n']);
end
save( ...
    fullfile( ...
        runFolder, ...
        CFG.output.validationFile), ...
    ...
    'validationCFG', ...
    'validationBaseline', ...
    'validationBaselinePassed', ...
    'bestValidation', ...
    'validationCost', ...
    'validationPassed', ...
    'validationImproved', ...
    '-v7.3');
Parameter = ...
    CFG.parameterNames;
NominalValue = ...
    nominalVector;
Log10Multiplier = ...
    bestZ;
Multiplier = ...
    bestMultipliers;
TunedValue = ...
    bestTunedVector;
AtLowerBound = ...
    abs( ...
        bestZ - ...
        CFG.lowerBounds(:)) <= ...
    1e-8;
AtUpperBound = ...
    abs( ...
        bestZ - ...
        CFG.upperBounds(:)) <= ...
    1e-8;
ParameterTable = ...
    table( ...
        Parameter, ...
        NominalValue, ...
        Log10Multiplier, ...
        Multiplier, ...
        TunedValue, ...
        AtLowerBound, ...
        AtUpperBound);
writetable( ...
    ParameterTable, ...
    fullfile( ...
        runFolder, ...
        CFG.output.parameterTableFile));
save( ...
    fullfile( ...
        runFolder, ...
        'Estimator_Tuning_Optimizer_Trials.mat'), ...
    ...
    'optimizerTrials', ...
    'optimizerTrialCount', ...
    'optimizerValidEvaluationCount', ...
    'optimizerFailedEvaluationCount', ...
    'optimizerValidEvaluationFraction', ...
    'optimizerPenaltyEvaluationCount', ...
    'optimizerNonfiniteEvaluationCount', ...
    '-v7.3');
totalElapsed_s = ...
    toc( ...
        totalTimer);
TUNING_RESULT = ...
    struct();
TUNING_RESULT.SchemaVersion = ...
    3.0;
TUNING_RESULT.Timestamp = ...
    timestamp;
TUNING_RESULT.ProjectRoot = ...
    projectRoot;
TUNING_RESULT.RunFolder = ...
    runFolder;
TUNING_RESULT.Optimizer = ...
    'surrogateopt';
TUNING_RESULT.ParallelRequested = ...
    parallelRequested;
if parallelRequested
    TUNING_RESULT.ParallelEngine = ...
        'parsim';
else
    TUNING_RESULT.ParallelEngine = ...
        'serial';
end
TUNING_RESULT.ParallelWorkers = ...
    parallelWorkers;
TUNING_RESULT.BatchSize = ...
    batchSize;
TUNING_RESULT.MinSurrogatePoints = ...
    minSurrogatePoints;
TUNING_RESULT.RequestedMaxFunctionEvaluations = ...
    requestedMaxEvaluations;
TUNING_RESULT.EffectiveMaxFunctionEvaluations = ...
    effectiveMaxEvaluations;
TUNING_RESULT.CheckpointFile = ...
    checkpointFile;
TUNING_RESULT.ExitFlag = ...
    exitFlag;
TUNING_RESULT.OptimizerOutput = ...
    optimizerOutput;
TUNING_RESULT.OptimizerTrials = ...
    optimizerTrials;
TUNING_RESULT.OptimizerReportedCost = ...
    optimizerReportedCost;
TUNING_RESULT.OptimizerTrialCount = ...
    optimizerTrialCount;
TUNING_RESULT.OptimizerValidEvaluationCount = ...
    optimizerValidEvaluationCount;
TUNING_RESULT.OptimizerFailedEvaluationCount = ...
    optimizerFailedEvaluationCount;
TUNING_RESULT.OptimizerValidEvaluationFraction = ...
    optimizerValidEvaluationFraction;
TUNING_RESULT.OptimizerPenaltyEvaluationCount = ...
    optimizerPenaltyEvaluationCount;
TUNING_RESULT.OptimizerNonfiniteEvaluationCount = ...
    optimizerNonfiniteEvaluationCount;
TUNING_RESULT.FinalTrainingCost = ...
    bestCostCheck;
TUNING_RESULT.OptimizerCostDifference = ...
    costDifference;
TUNING_RESULT.NominalVector = ...
    nominalVector;
TUNING_RESULT.BestLog10Multiplier = ...
    bestZ;
TUNING_RESULT.BestMultiplier = ...
    bestMultipliers;
TUNING_RESULT.BestTunedVector = ...
    bestTunedVector;
TUNING_RESULT.BestOverride = ...
    bestOverride;
TUNING_RESULT.TrainingBaseline = ...
    trainingBaseline;
TUNING_RESULT.BestTraining = ...
    bestTraining;
TUNING_RESULT.ValidationBaseline = ...
    validationBaseline;
TUNING_RESULT.ValidationBaselinePassed = ...
    validationBaselinePassed;
TUNING_RESULT.BestValidation = ...
    bestValidation;
TUNING_RESULT.ValidationCost = ...
    validationCost;
TUNING_RESULT.ValidationPassed = ...
    validationPassed;
TUNING_RESULT.ValidationImproved = ...
    validationImproved;
TUNING_RESULT.ParameterTable = ...
    ParameterTable;
TUNING_RESULT.ParallelPreflightCost = ...
    preflightCost;
TUNING_RESULT.OptimizationElapsed_s = ...
    optimizationElapsed_s;
TUNING_RESULT.TotalElapsed_s = ...
    totalElapsed_s;
TUNING_RESULT.Configuration = ...
    CFG;
TUNING_RESULT.RNGStateBeforeTuning = ...
    rngStateBeforeTuning;
TUNING_RESULT.OptimizerRNGStateStart = ...
    optimizerRNGStateStart;
TUNING_RESULT.RNGStateAfterTuning = ...
    rng;
save( ...
    fullfile( ...
        runFolder, ...
        CFG.output.resultFile), ...
    ...
    'TUNING_RESULT', ...
    '-v7.3');
assignin( ...
    'base', ...
    'ESTIMATOR_TUNING_RESULT', ...
    TUNING_RESULT);
fprintf('\n');
fprintf('==============================================================\n');
fprintf(' EKF GLOBAL TUNING COMPLETE\n');
fprintf('==============================================================\n');
fprintf( ...
    'Optimizer:                 surrogateopt\n');
fprintf( ...
    'Requested evaluations:     %d\n', ...
    requestedMaxEvaluations);
fprintf( ...
    'Min surrogate points:      %d\n', ...
    minSurrogatePoints);
fprintf( ...
    'Parallel simulations:      %d\n', ...
    parallelRequested);
if parallelRequested
    fprintf( ...
        'Parallel workers:          %d\n', ...
        parallelWorkers);
    fprintf( ...
        'Vectorized batch size:     %d\n', ...
        batchSize);
end
if isfield(optimizerOutput,'funccount')
    fprintf( ...
        'Function evaluations:      %d\n', ...
        optimizerOutput.funccount);
end
fprintf( ...
    'Recorded trials:            %g\n', ...
    optimizerTrialCount);
fprintf( ...
    'Valid mission candidates:   %g\n', ...
    optimizerValidEvaluationCount);
fprintf( ...
    'Failed candidates:          %g\n', ...
    optimizerFailedEvaluationCount);
if isfinite(optimizerValidEvaluationFraction)
    fprintf( ...
        'Valid candidate fraction: %.1f %%\n', ...
        100 * ...
        optimizerValidEvaluationFraction);
end
fprintf( ...
    'Optimizer reported cost:    %.6f\n', ...
    optimizerReportedCost);
fprintf( ...
    'Training cost check:        %.6f\n', ...
    bestCostCheck);
fprintf( ...
    'Validation baseline passed: %d\n', ...
    validationBaselinePassed);
fprintf( ...
    'Validation passed:          %d\n', ...
    validationPassed);
if isfinite(validationCost)
    fprintf( ...
        'Validation cost:           %.6f\n', ...
        validationCost);
else
    fprintf( ...
        'Validation cost:           N/A\n');
end
fprintf( ...
    'Validation improved:        %d\n', ...
    validationImproved);
fprintf( ...
    'Optimization time:          %.2f h\n', ...
    optimizationElapsed_s / 3600);
fprintf( ...
    'Total tuning time:          %.2f h\n', ...
    totalElapsed_s / 3600);
fprintf('\nTRAINING:\n');
fprintf( ...
    'Position RMSE:              %.6f -> %.6f m\n', ...
    trainingBaseline.meanMetrics.PositionRMSE_m, ...
    bestTraining.meanMetrics.PositionRMSE_m);
fprintf( ...
    'Horizontal Position RMSE:   %.6f -> %.6f m\n', ...
    trainingBaseline.meanMetrics.HorizontalPositionRMSE_m, ...
    bestTraining.meanMetrics.HorizontalPositionRMSE_m);
fprintf( ...
    'Velocity RMSE:              %.6f -> %.6f m/s\n', ...
    trainingBaseline.meanMetrics.VelocityRMSE_m_s, ...
    bestTraining.meanMetrics.VelocityRMSE_m_s);
fprintf( ...
    'Attitude RMSE:              %.6f -> %.6f deg\n', ...
    trainingBaseline.meanMetrics.AttitudeRMSE_deg, ...
    bestTraining.meanMetrics.AttitudeRMSE_deg);
fprintf('\nVALIDATION:\n');
if validationPassed
    fprintf( ...
        'Position RMSE:              %.6f -> %.6f m\n', ...
        validationBaseline.meanMetrics.PositionRMSE_m, ...
        bestValidation.meanMetrics.PositionRMSE_m);
    fprintf( ...
        'Horizontal Position RMSE:   %.6f -> %.6f m\n', ...
        validationBaseline.meanMetrics.HorizontalPositionRMSE_m, ...
        bestValidation.meanMetrics.HorizontalPositionRMSE_m);
    fprintf( ...
        'Velocity RMSE:              %.6f -> %.6f m/s\n', ...
        validationBaseline.meanMetrics.VelocityRMSE_m_s, ...
        bestValidation.meanMetrics.VelocityRMSE_m_s);
    fprintf( ...
        'Attitude RMSE:              %.6f -> %.6f deg\n', ...
        validationBaseline.meanMetrics.AttitudeRMSE_deg, ...
        bestValidation.meanMetrics.AttitudeRMSE_deg);
else
    fprintf( ...
        'Independent validation did NOT pass all seeds.\n');
    fprintf( ...
        ['The optimization result was saved anyway so that the ', ...
         'failure can be diagnosed without losing the campaign.\n']);
end
fprintf( ...
    '\nResults:\n%s\n', ...
    runFolder);
fprintf( ...
    '\nIMPORTANT: production estimator was NOT overwritten.\n');
fprintf('==============================================================\n\n');
end
function printMeanMetrics(M)
fprintf( ...
    '  Position RMSE:            %.6f m\n', ...
    M.PositionRMSE_m);
fprintf( ...
    '  Horizontal Position RMSE: %.6f m\n', ...
    M.HorizontalPositionRMSE_m);
fprintf( ...
    '  Velocity RMSE:            %.6f m/s\n', ...
    M.VelocityRMSE_m_s);
fprintf( ...
    '  Attitude RMSE:            %.6f deg\n', ...
    M.AttitudeRMSE_deg);
fprintf( ...
    '  Angular Rate RMSE:        %.6f rad/s\n', ...
    M.AngularRateRMSE_rad_s);
fprintf( ...
    '  Acceleration RMSE:        %.6f m/s^2\n', ...
    M.AccelerationRMSE_m_s2);
end
function printRunMessages( ...
    RESULT, ...
    seedOffsets)
seedOffsets = ...
    double( ...
        seedOffsets(:));
numberOfSeeds = ...
    numel( ...
        seedOffsets);
for seedIndex = ...
        1:numberOfSeeds
    message = ...
        'No result';
    if isfield(RESULT,'messages') && ...
            numel(RESULT.messages) >= seedIndex && ...
            ~isempty(RESULT.messages{seedIndex})
        message = ...
            RESULT.messages{seedIndex};
    end
    fprintf( ...
        '  Seed %g: %s\n', ...
        seedOffsets(seedIndex), ...
        message);
end
end
