function [J, RESULT] = evaluate_controller_candidate( ...
    z, ...
    CFG, ...
    STAGE, ...
    frozenAutopilot, ...
    baselineMetrics, ...
    executionMode, ...
    seedOffsets, ...
    missionPolicy)
narginchk(4,8);
if nargin < 5
    baselineMetrics = ...
        [];
end
if nargin < 6 || ...
        isempty(executionMode)
    executionMode = ...
        'auto';
end
if nargin < 7 || ...
        isempty(seedOffsets)
    seedOffsets = ...
        CFG.experiment.optimizationSeedOffset;
end
if nargin < 8 || ...
        isempty(missionPolicy)
    missionPolicy = ...
        'strict';
end
missionPolicy = ...
    lower( ...
        strtrim( ...
            char( ...
                string(missionPolicy))));
if ~ismember( ...
        missionPolicy, ...
        {'strict','baseline'})
    error( ...
        'QuadrotorFramework:ControllerTuningMissionPolicy', ...
        'missionPolicy must be strict or baseline.');
end
seedOffsets = ...
    double( ...
        seedOffsets(:));
if isempty(seedOffsets) || ...
        any(~isfinite(seedOffsets))
    error( ...
        'QuadrotorFramework:ControllerTuningSeedOffsets', ...
        'seedOffsets must contain finite values.');
end
if numel(unique(seedOffsets)) ~= ...
        numel(seedOffsets)
    error( ...
        'QuadrotorFramework:ControllerTuningDuplicateSeeds', ...
        'seedOffsets must be unique.');
end
validateConfiguration( ...
    CFG, ...
    STAGE, ...
    frozenAutopilot);
numberOfParameters = ...
    STAGE.numberOfParameters;
Z = ...
    normalizeCandidateMatrix( ...
        z, ...
        numberOfParameters);
numberOfCandidates = ...
    size( ...
        Z, ...
        1);
mode = ...
    lower( ...
        strtrim( ...
            char(executionMode)));
if ~ismember( ...
        mode, ...
        {'auto','serial','parallel'})
    error( ...
        'QuadrotorFramework:ControllerTuningExecutionMode', ...
        'executionMode must be auto, serial, or parallel.');
end
parallelEnabled = ...
    false;
if isfield(CFG,'optimizer') && ...
        isfield(CFG.optimizer,'useParallel')
    parallelEnabled = ...
        logical( ...
            CFG.optimizer.useParallel);
end
if strcmp(mode,'auto')
    if parallelEnabled && ...
            numberOfCandidates > 1
        mode = ...
            'parallel';
    else
        mode = ...
            'serial';
    end
end
switch mode
    case 'serial'
        if numberOfCandidates == 1
            [J,RESULT] = ...
                evaluateSingleCandidate( ...
                    Z(1,:).', ...
                    CFG, ...
                    STAGE, ...
                    frozenAutopilot, ...
                    baselineMetrics, ...
                    seedOffsets, ...
                    missionPolicy);
        else
            [J,RESULT] = ...
                evaluateCandidateBatchSerial( ...
                    Z, ...
                    CFG, ...
                    STAGE, ...
                    frozenAutopilot, ...
                    baselineMetrics, ...
                    seedOffsets, ...
                    missionPolicy);
        end
    case 'parallel'
        if ~parallelEnabled
            error( ...
                'QuadrotorFramework:ControllerParallelDisabled', ...
                [ ...
                'Parallel controller evaluation was requested, but ', ...
                'CFG.optimizer.useParallel is false.']);
        end
        [J,RESULT] = ...
            evaluateCandidateBatchParallel( ...
                Z, ...
                CFG, ...
                STAGE, ...
                frozenAutopilot, ...
                baselineMetrics, ...
                seedOffsets, ...
                missionPolicy);
end
end
function validateConfiguration( ...
    CFG, ...
    STAGE, ...
    frozenAutopilot)
if ~isstruct(CFG) || ~isstruct(STAGE) || ~isstruct(frozenAutopilot)
    error('QuadrotorFramework:ControllerTuningConfiguration','CFG, STAGE and frozenAutopilot must be structures.');
end
requiredStageFields = {'id','name','objectiveType','parameterPaths','numberOfParameters','lowerLog10Multiplier','upperLog10Multiplier'};
for k = 1:numel(requiredStageFields)
    if ~isfield(STAGE,requiredStageFields{k})
        error('QuadrotorFramework:ControllerStageConfiguration','Missing STAGE.%s.',requiredStageFields{k});
    end
end
if numel(STAGE.parameterPaths) ~= STAGE.numberOfParameters
    error('QuadrotorFramework:ControllerStageParameterCount','Stage parameter count is inconsistent.');
end
requiredSimulationFields = {'metricSampleRate_Hz';'disablePacing';'useAutomaticProtocolStopTime';'requireMissionCompletion';'requireLanded';'rejectFailsafe'};
for k = 1:numel(requiredSimulationFields)
    if ~isfield(CFG.simulation,requiredSimulationFields{k})
        error('QuadrotorFramework:ControllerSimulationConfiguration','Missing CFG.simulation.%s.',requiredSimulationFields{k});
    end
end
requiredExperimentFields = {'controllerSet';'plantModels';'plantWeights';'disturbancesEnabled';'operatorMode';'trajectoryID';'feedbackSource';'metricStateSource';'requireEstimatedFeedback';'estimatedFeedbackTolerance_m';'estimatedFeedbackRelativeTolerance';'estimatedFeedbackMaximumLag_s'};
for k = 1:numel(requiredExperimentFields)
    if ~isfield(CFG.experiment,requiredExperimentFields{k})
        error('QuadrotorFramework:ControllerExperimentConfiguration','Missing CFG.experiment.%s.',requiredExperimentFields{k});
    end
end
controllerSet = upper(string(CFG.experiment.controllerSet));
if ~ismember(controllerSet,["C1","C2"])
    error('QuadrotorFramework:ControllerSet','CFG.experiment.controllerSet must be C1 or C2.');
end
plantModels = double(CFG.experiment.plantModels(:));
plantWeights = double(CFG.experiment.plantWeights(:));
if isempty(plantModels) || any(~ismember(plantModels,[1 2 3])) || numel(unique(plantModels)) ~= numel(plantModels)
    error('QuadrotorFramework:ControllerPlantModels','CFG.experiment.plantModels must contain unique values from [1 2 3].');
end
if numel(plantWeights) ~= numel(plantModels) || any(~isfinite(plantWeights)) || any(plantWeights < 0) || abs(sum(plantWeights)-1) > 1e-12
    error('QuadrotorFramework:ControllerPlantWeights','CFG.experiment.plantWeights must be finite, nonnegative, match plantModels, and sum to one.');
end
if controllerSet == "C1" && ~isequal(plantModels(:).',[1 2])
    error('QuadrotorFramework:C1PlantModels','C1 tuning must evaluate L1 and L2 jointly.');
end
if controllerSet == "C2" && ~isequal(plantModels(:).',3)
    error('QuadrotorFramework:C2PlantModels','C2 tuning must evaluate L3.');
end
trajectoryID = double(CFG.experiment.trajectoryID);
if ~isscalar(trajectoryID) || ~isfinite(trajectoryID) || trajectoryID ~= round(trajectoryID) || trajectoryID < 1
    error('QuadrotorFramework:ControllerTrajectoryID','CFG.experiment.trajectoryID must be a positive integer.');
end
feedbackSource = upper(string(CFG.experiment.feedbackSource));
if ~ismember(feedbackSource,["TRUE","EST"])
    error('QuadrotorFramework:ControllerFeedbackSource','CFG.experiment.feedbackSource must be TRUE or EST.');
end
metricStateSource = upper(string(CFG.experiment.metricStateSource));
if metricStateSource ~= "TRUE"
    error('QuadrotorFramework:ControllerMetricStateSource','Controller tuning metrics must use TRUE physical states.');
end
if CFG.experiment.requireEstimatedFeedback && feedbackSource ~= "EST"
    error('QuadrotorFramework:ControllerEstimatedFeedbackRequired','requireEstimatedFeedback requires feedbackSource = EST.');
end
if CFG.experiment.estimatedFeedbackTolerance_m < 0 || CFG.experiment.estimatedFeedbackRelativeTolerance < 0 || CFG.experiment.estimatedFeedbackMaximumLag_s < 0
    error('QuadrotorFramework:ControllerFeedbackTolerance','Estimated-feedback verification tolerances must be nonnegative.');
end
controller_tuning_gain_table(frozenAutopilot,STAGE.parameterPaths);
end
function Z = normalizeCandidateMatrix( ...
    z, ...
    numberOfParameters)
z = ...
    double(z);
if isempty(z)
    error( ...
        'QuadrotorFramework:ControllerCandidateEmpty', ...
        'Controller candidate cannot be empty.');
end
if isvector(z)
    if numel(z) ~= ...
            numberOfParameters
        error( ...
            'QuadrotorFramework:ControllerCandidateSize', ...
            'Candidate must contain %d parameters.', ...
            numberOfParameters);
    end
    Z = ...
        reshape( ...
            z, ...
            1, ...
            numberOfParameters);
elseif size(z,2) == ...
        numberOfParameters
    Z = ...
        z;
elseif size(z,1) == ...
        numberOfParameters
    Z = ...
        z.';
else
    error( ...
        'QuadrotorFramework:ControllerCandidateMatrix', ...
        'Candidate matrix must be N-by-%d.', ...
        numberOfParameters);
end
if any(~isfinite(Z),'all')
    error( ...
        'QuadrotorFramework:ControllerCandidateNonfinite', ...
        'Controller candidate matrix contains NaN or Inf.');
end
end
function [J,RESULT] = evaluateSingleCandidate( ...
    z, ...
    CFG, ...
    STAGE, ...
    frozenAutopilot, ...
    baselineMetrics, ...
    seedOffsets, ...
    missionPolicy)
z = double(z(:));
if ~candidateWithinBounds(z,STAGE)
    [J,RESULT] = invalidCandidateResult(z,CFG,STAGE,'Candidate is nonfinite or outside configured bounds.');
    return;
end
try
    CANDIDATE = buildCandidate(z,STAGE,frozenAutopilot);
catch ME
    [J,RESULT] = invalidCandidateResult(z,CFG,STAGE,sprintf('%s: %s',ME.identifier,ME.message));
    return;
end
CONTEXT = getSimulationContext(CFG);
plantModels = double(CFG.experiment.plantModels(:));
numberOfPlants = numel(plantModels);
numberOfSeeds = numel(seedOffsets);
allowSoftBaseline = strcmp(missionPolicy,'baseline');
RUN = repmat(emptyMetricStructure(),numberOfPlants,numberOfSeeds);
runSucceeded = false(numberOfPlants,numberOfSeeds);
strictRunSucceeded = false(numberOfPlants,numberOfSeeds);
metricsAvailable = false(numberOfPlants,numberOfSeeds);
softBaselineAccepted = false(numberOfPlants,numberOfSeeds);
messages = cell(numberOfPlants,numberOfSeeds);
for seedIndex = 1:numberOfSeeds
    for plantIndex = 1:numberOfPlants
        plantModel = plantModels(plantIndex);
        try
            simIn = buildSimulationInput(CANDIDATE.AUTOPILOT,seedOffsets(seedIndex),plantModel,CONTEXT,CFG);
            out = sim(simIn);
            [M,MISSION_STATUS] = extractControllerMetrics(out,CANDIDATE.AUTOPILOT,CFG,STAGE);
            M.SeedOffset = seedOffsets(seedIndex);
            M.PlantModel = plantModel;
            M.success = true;
            RUN(plantIndex,seedIndex) = M;
            metricsAvailable(plantIndex,seedIndex) = true;
            strictRunSucceeded(plantIndex,seedIndex) = MISSION_STATUS.accepted;
            if MISSION_STATUS.accepted
                runSucceeded(plantIndex,seedIndex) = true;
                messages{plantIndex,seedIndex} = 'OK';
            elseif allowSoftBaseline && MISSION_STATUS.softFailure
                runSucceeded(plantIndex,seedIndex) = true;
                softBaselineAccepted(plantIndex,seedIndex) = true;
                messages{plantIndex,seedIndex} = MISSION_STATUS.message;
            else
                runSucceeded(plantIndex,seedIndex) = false;
                messages{plantIndex,seedIndex} = MISSION_STATUS.message;
            end
        catch ME
            runSucceeded(plantIndex,seedIndex) = false;
            strictRunSucceeded(plantIndex,seedIndex) = false;
            metricsAvailable(plantIndex,seedIndex) = false;
            softBaselineAccepted(plantIndex,seedIndex) = false;
            messages{plantIndex,seedIndex} = sprintf('%s: %s',ME.identifier,ME.message);
        end
    end
end
[J,RESULT] = finalizeCandidate(CANDIDATE,RUN,runSucceeded,strictRunSucceeded,metricsAvailable,softBaselineAccepted,messages,baselineMetrics,CFG,STAGE,missionPolicy);
end
function [J,RESULT] = evaluateCandidateBatchSerial( ...
    Z, ...
    CFG, ...
    STAGE, ...
    frozenAutopilot, ...
    baselineMetrics, ...
    seedOffsets, ...
    missionPolicy)
numberOfCandidates = ...
    size( ...
        Z, ...
        1);
J = ...
    CFG.cost.failurePenalty .* ...
    ones( ...
        numberOfCandidates, ...
        1);
RESULT = ...
    repmat( ...
        emptyCandidateResult(), ...
        numberOfCandidates, ...
        1);
for candidateIndex = 1:numberOfCandidates
    [ ...
        J(candidateIndex), ...
        RESULT(candidateIndex)] = ...
        evaluateSingleCandidate( ...
            Z(candidateIndex,:).', ...
            CFG, ...
            STAGE, ...
            frozenAutopilot, ...
            baselineMetrics, ...
            seedOffsets, ...
            missionPolicy);
end
end
function [J,RESULT] = evaluateCandidateBatchParallel( ...
    Z, ...
    CFG, ...
    STAGE, ...
    frozenAutopilot, ...
    baselineMetrics, ...
    seedOffsets, ...
    missionPolicy)
[J,RESULT] = evaluateCandidateBatchSerial(Z,CFG,STAGE,frozenAutopilot,baselineMetrics,seedOffsets,missionPolicy);
end
function CANDIDATE = buildCandidate( ...
    z, ...
    STAGE, ...
    frozenAutopilot)
[baselineTable,~] = ...
    controller_tuning_gain_table( ...
        frozenAutopilot, ...
        STAGE.parameterPaths);
baselineValues = ...
    double( ...
        baselineTable.EffectiveValue);
multipliers = ...
    10 .^ ...
    double(z(:));
candidateValues = ...
    baselineValues .* ...
    multipliers;
[gainTable,AUTOPILOT] = ...
    controller_tuning_gain_table( ...
        frozenAutopilot, ...
        STAGE.parameterPaths, ...
        candidateValues);
CANDIDATE = ...
    struct();
CANDIDATE.z = ...
    double(z(:));
CANDIDATE.multipliers = ...
    multipliers;
CANDIDATE.baselineValues = ...
    baselineValues;
CANDIDATE.gainValues = ...
    candidateValues;
CANDIDATE.gainTable = ...
    gainTable;
CANDIDATE.AUTOPILOT = ...
    AUTOPILOT;
end
function valid = candidateWithinBounds( ...
    z, ...
    STAGE)
z = ...
    double(z(:));
lower = ...
    double( ...
        STAGE.lowerLog10Multiplier(:));
upper = ...
    double( ...
        STAGE.upperLog10Multiplier(:));
valid = ...
    numel(z) == STAGE.numberOfParameters && ...
    numel(lower) == STAGE.numberOfParameters && ...
    numel(upper) == STAGE.numberOfParameters && ...
    all(isfinite(z)) && ...
    all(z >= lower) && ...
    all(z <= upper);
end
function CONTEXT = getSimulationContext(CFG)
requiredVariables = {'P_ENV','SENSOR','ESTIMATOR','AUTO_PROTOCOL','TRAJECTORY_LIBRARY','MAX_WAYPOINTS'};
for k = 1:numel(requiredVariables)
    variableName = requiredVariables{k};
    if ~evalin('base',sprintf('exist(''%s'',''var'')',variableName))
        error('QuadrotorFramework:ControllerTuningMissingWorkspaceVariable',['Missing base-workspace variable %s. Run initialize_project first.'],variableName);
    end
end
CONTEXT = struct();
CONTEXT.modelName = CFG.modelName;
CONTEXT.P_ENV = evalin('base','P_ENV');
CONTEXT.SENSOR = evalin('base','SENSOR');
CONTEXT.ESTIMATOR = evalin('base','ESTIMATOR');
CONTEXT.AUTO_PROTOCOL = evalin('base','AUTO_PROTOCOL');
CONTEXT.TRAJECTORY_LIBRARY = evalin('base','TRAJECTORY_LIBRARY');
CONTEXT.MAX_WAYPOINTS = evalin('base','MAX_WAYPOINTS');
trajectoryID = double(CFG.experiment.trajectoryID);
if trajectoryID < 1 || trajectoryID > numel(CONTEXT.TRAJECTORY_LIBRARY)
    error('QuadrotorFramework:ControllerTuningTrajectoryID','Requested trajectory %d is outside TRAJECTORY_LIBRARY.',trajectoryID);
end
selectedTrajectory = CONTEXT.TRAJECTORY_LIBRARY(trajectoryID);
CONTEXT.TRAJECTORY_ID = uint8(trajectoryID);
CONTEXT.TRAJECTORY_CONFIG = struct();
CONTEXT.TRAJECTORY_CONFIG.numberOfTrajectories = numel(CONTEXT.TRAJECTORY_LIBRARY);
CONTEXT.TRAJECTORY_CONFIG.maxWaypoints = CONTEXT.MAX_WAYPOINTS;
CONTEXT.TRAJECTORY_CONFIG.selectedID = CONTEXT.TRAJECTORY_ID;
CONTEXT.TRAJECTORY_CONFIG.selectedName = selectedTrajectory.name;
CONTEXT.TRAJECTORY_CONFIG.selectedNumWaypoints = selectedTrajectory.numWaypoints;
CONTEXT.TRAJECTORY_CONFIG.numberOfWaypointsPerTrajectory = arrayfun(@(x) double(x.numWaypoints),CONTEXT.TRAJECTORY_LIBRARY);
CONTEXT.TRAJECTORY_CONFIG.selectedPassThroughIntermediate = logical(selectedTrajectory.passThroughIntermediate);
CONTEXT.TRAJECTORY_CONFIG.selectedMissionPlanBuffer = zeros(4,double(CONTEXT.MAX_WAYPOINTS));
CONTEXT.TRAJECTORY_CONFIG.selectedMissionPlanBuffer(:,1:double(selectedTrajectory.numWaypoints)) = selectedTrajectory.missionPlanRelative;
protocolRow = trajectoryID;
CONTEXT.AUTO_PROTOCOL.selected.armTime_s = CONTEXT.AUTO_PROTOCOL.schedule_s(protocolRow,CONTEXT.AUTO_PROTOCOL.column.arm);
CONTEXT.AUTO_PROTOCOL.selected.runTime_s = CONTEXT.AUTO_PROTOCOL.schedule_s(protocolRow,CONTEXT.AUTO_PROTOCOL.column.run);
CONTEXT.AUTO_PROTOCOL.selected.disarmTime_s = CONTEXT.AUTO_PROTOCOL.schedule_s(protocolRow,CONTEXT.AUTO_PROTOCOL.column.disarm);
CONTEXT.AUTO_PROTOCOL.selected.stopTime_s = CONTEXT.AUTO_PROTOCOL.schedule_s(protocolRow,CONTEXT.AUTO_PROTOCOL.column.stop);
CONTEXT.AUTO_PROTOCOL.selected.name = char(selectedTrajectory.name);
if CFG.simulation.useAutomaticProtocolStopTime
    CONTEXT.stopTime_s = double(CONTEXT.AUTO_PROTOCOL.selected.stopTime_s);
else
    CONTEXT.stopTime_s = double(CFG.simulation.stopTime_s);
end
if ~isscalar(CONTEXT.stopTime_s) || ~isfinite(CONTEXT.stopTime_s) || CONTEXT.stopTime_s <= 0
    error('QuadrotorFramework:ControllerTuningStopTimeValue','Controller tuning Stop Time must be finite and positive.');
end
feedbackSource = upper(string(CFG.experiment.feedbackSource));
if feedbackSource == "TRUE"
    CONTEXT.feedbackSwitchSetting = '1';
elseif feedbackSource == "EST"
    CONTEXT.feedbackSwitchSetting = '0';
else
    error('QuadrotorFramework:ControllerFeedbackSource','Unknown feedback source.');
end
CONTEXT.feedbackSwitchPath = [CONTEXT.modelName '/Manual Switch'];
if ~bdIsLoaded(CONTEXT.modelName)
    load_system(CONTEXT.modelName);
end
simulationStatus = get_param(CONTEXT.modelName,'SimulationStatus');
if ~strcmpi(simulationStatus,'stopped')
    error('QuadrotorFramework:ControllerEvaluationModelRunning','Model must be stopped before evaluating a controller candidate.');
end
end
function simIn = buildSimulationInput( ...
    AUTOPILOT, ...
    seedOffset, ...
    plantModel, ...
    CONTEXT, ...
    CFG)
SENSOR = applySensorSeedOffset(CONTEXT.SENSOR,seedOffset);
AUTOPILOT.info.activeController = char(upper(string(CFG.experiment.controllerSet)));
simIn = Simulink.SimulationInput(CONTEXT.modelName);
simIn = simIn.setVariable('P_ENV',CONTEXT.P_ENV);
simIn = simIn.setVariable('SENSOR',SENSOR);
simIn = simIn.setVariable('ESTIMATOR',CONTEXT.ESTIMATOR);
simIn = simIn.setVariable('AUTOPILOT',AUTOPILOT);
simIn = simIn.setVariable('AUTO_PROTOCOL',CONTEXT.AUTO_PROTOCOL);
simIn = simIn.setVariable('TRAJECTORY_ID',CONTEXT.TRAJECTORY_ID);
simIn = simIn.setVariable('TRAJECTORY_CONFIG',CONTEXT.TRAJECTORY_CONFIG);
simIn = simIn.setVariable('MAX_WAYPOINTS',CONTEXT.MAX_WAYPOINTS);
simIn = simIn.setVariable('UAV_MODEL',uint8(plantModel));
simIn = simIn.setVariable('DIST_ENABLE',logical(CFG.experiment.disturbancesEnabled));
simIn = simIn.setVariable('OPERATOR_MODE',uint8(CFG.experiment.operatorMode));
simIn = simIn.setVariable('ESTIMATOR_TUNING_OVERRIDE',[]);
simIn = simIn.setVariable('ESTIMATOR_TUNING_SILENT',true);
simIn = simIn.setVariable('CONTROLLER_TUNING_ACTIVE',true);
simIn = simIn.setBlockParameter(CONTEXT.feedbackSwitchPath,'CurrentSetting',CONTEXT.feedbackSwitchSetting);
simIn = simIn.setModelParameter('StopTime',sprintf('%.15g',CONTEXT.stopTime_s),'ReturnWorkspaceOutputs','on');
if CFG.simulation.disablePacing
    try
        simIn = simIn.setModelParameter('EnablePacing','off');
    catch
    end
end
end
function SENSOR = applySensorSeedOffset( ...
    SENSOR, ...
    seedOffset)
seedOffset = ...
    double(seedOffset);
if ~isscalar(seedOffset) || ...
        ~isfinite(seedOffset)
    error( ...
        'QuadrotorFramework:ControllerTuningSeedOffset', ...
        'Sensor seed offset must be finite.');
end
seedFields = { ...
    {'IMU','seed'}; ...
    {'GPS','seed'}; ...
    {'Barometer','seed'}};
for k = 1:numel(seedFields)
    path = ...
        seedFields{k};
    if isfield(SENSOR,path{1}) && ...
            isfield(SENSOR.(path{1}),path{2})
        SENSOR.(path{1}).(path{2}) = ...
            round( ...
                double( ...
                    SENSOR.(path{1}).(path{2})) + ...
                seedOffset);
    end
end
end
function [M,MISSION_STATUS] = extractControllerMetrics( ...
    out, ...
    AUTOPILOT, ...
    CFG, ...
    STAGE)
availableLogs = ...
    who(out);
requiredLogs = { ...
    'omegaLog', ...
    'controlAxesLog', ...
    'cmdAttitudeLog', ...
    'cmdAngularRateLog', ...
    'cgsLog', ...
    'trueStatesLog', ...
    'liveTelemetryLog'};
for k = 1:numel(requiredLogs)
    if ~ismember( ...
            requiredLogs{k}, ...
            availableLogs)
        error( ...
            'QuadrotorFramework:ControllerTuningMissingLog', ...
            'Missing simulation output out.%s.', ...
            requiredLogs{k});
    end
end
CGS = ...
    out.cgsLog;
TRUE = ...
    out.trueStatesLog;
LIVE = ...
    out.liveTelemetryLog;
[tTelemetry,Telemetry] = ...
    signalMatrix( ...
        LIVE);
MISSION = ...
    evaluateMissionAcceptance( ...
        tTelemetry, ...
        Telemetry);
if CFG.experiment.requireEstimatedFeedback
    verifyEstimatedFeedback(Telemetry,CFG);
end
MISSION_STATUS = ...
    evaluateMissionRequirementStatus( ...
        MISSION, ...
        CFG);
tStart = ...
    MISSION.MissionStartTime_s;
if MISSION.NavigationCompleted && ...
        isfinite(MISSION.NavigationCompleteTime_s)
    tEnd = ...
        MISSION.NavigationCompleteTime_s;
else
    finiteTelemetryTime = ...
        tTelemetry( ...
            isfinite(tTelemetry));
    if isempty(finiteTelemetryTime)
        error( ...
            'QuadrotorFramework:ControllerTuningTelemetryTime', ...
            'No finite telemetry time is available for partial-mission metrics.');
    end
    tEnd = ...
        finiteTelemetryTime(end);
end
if ~isfinite(tStart) || ...
        ~isfinite(tEnd) || ...
        tEnd <= tStart
    error( ...
        'QuadrotorFramework:ControllerTuningMetricWindow', ...
        'No valid mission metric window is available.');
end
[tOmega,Omega] = ...
    signalMatrix( ...
        out.omegaLog);
if size(Omega,2) ~= 4
    error( ...
        'QuadrotorFramework:ControllerTuningOmegaSize', ...
        'omegaLog must contain four motor speeds.');
end
omegaMask = ...
    windowMask( ...
        tOmega, ...
        tStart, ...
        tEnd);
OmegaWindow = ...
    Omega(omegaMask,:);
omegaVariation = ...
    derivativeRMS( ...
        tOmega(omegaMask), ...
        OmegaWindow);
[tRollAxis,rollAxis] = ...
    extractBusField( ...
        out.controlAxesLog, ...
        {'rollAxis'});
[tPitchAxis,pitchAxis] = ...
    extractBusField( ...
        out.controlAxesLog, ...
        {'pitchAxis'});
[tYawAxis,yawAxis] = ...
    extractBusField( ...
        out.controlAxesLog, ...
        {'yawAxis'});
[tThrustAxis,thrustAxis] = ...
    extractBusField( ...
        out.controlAxesLog, ...
        {'thrustAxis'});
rollAxis = ...
    rollAxis(:,1);
pitchAxis = ...
    pitchAxis(:,1);
yawAxis = ...
    yawAxis(:,1);
thrustAxis = ...
    thrustAxis(:,1);
[tCmdAttitude,CmdAttitude] = ...
    signalMatrix( ...
        out.cmdAttitudeLog);
[tEuler,Euler] = extractBusField(TRUE,{'Attitude','Euler'});
if size(CmdAttitude,2) ~= 2 || size(Euler,2) ~= 3
    error('QuadrotorFramework:ControllerTuningAttitudeLogSize','Invalid TRUE attitude log dimensions.');
end
[tCmdRate,CmdRate] = ...
    signalMatrix( ...
        out.cmdAngularRateLog);
[tRate,Rate] = extractBusField(TRUE,{'AngularRate'});
if size(CmdRate,2) ~= 3 || size(Rate,2) ~= 3
    error('QuadrotorFramework:ControllerTuningRateLogSize','Invalid TRUE angular-rate log dimensions.');
end
[tTruePosition,TruePosition] = ...
    extractBusField( ...
        TRUE, ...
        {'Position'});
[tTrueVelocity,TrueVelocity] = ...
    extractBusField( ...
        TRUE, ...
        {'Velocity'});
if size(TruePosition,2) ~= 3 || ...
        size(TrueVelocity,2) ~= 3
    error( ...
        'QuadrotorFramework:ControllerTuningTrueStateSize', ...
        'TRUE Position/Velocity must contain [N E D].');
end
[tPositionRef,PositionRef] = ...
    extractBusField( ...
        CGS, ...
        {'Position_ref'});
[tYawRef,YawRef] = ...
    extractBusField( ...
        CGS, ...
        {'Yaw_ref'});
YawRef = ...
    YawRef(:,1);
if size(PositionRef,2) ~= 3
    error( ...
        'QuadrotorFramework:ControllerPositionReferenceSize', ...
        'CGS Position_ref must contain [N E D].');
end
VelocityRef = [];
tVelocityRef = [];
if strcmpi( ...
        char(STAGE.objectiveType), ...
        'horizontal_velocity') || ...
        strcmpi( ...
        char(STAGE.objectiveType), ...
        'vertical_velocity')
    [tVelocityRef,VelocityRef] = ...
        extractBusField( ...
            CGS, ...
            {'Velocity_ref'});
    if size(VelocityRef,2) ~= 3
        error( ...
            'QuadrotorFramework:ControllerVelocityReferenceSize', ...
            'CGS Velocity_ref must contain [V_N V_E V_D].');
    end
end
M = ...
    emptyMetricStructure();
M.MissionStartTime_s = ...
    tStart;
M.NavigationCompleteTime_s = ...
    tEnd;
M.LandingTime_s = ...
    MISSION.LandingTime_s;
M.NavigationCompleted = ...
    MISSION.NavigationCompleted;
M.LandedConfirmed = ...
    MISSION.LandedConfirmed;
M.FailsafeAborted = ...
    MISSION.FailsafeAborted;
M.Completed = ...
    MISSION.Completed;
M.NumWaypoints = ...
    MISSION.NumWaypoints;
M.MetricWindowEndTime_s = ...
    tEnd;
M.MissionAccepted = ...
    MISSION_STATUS.accepted;
M.MotorVariationRMS_rad_s2 = ...
    omegaVariation;
objectiveType = ...
    lower( ...
        char(STAGE.objectiveType));
switch objectiveType
    case 'rate_pitch'
        command = ...
            interp1( ...
                tCmdRate, ...
                CmdRate(:,2), ...
                tRate, ...
                'linear', ...
                'extrap');
        errorSignal = ...
            Rate(:,2) - ...
            command;
        mask = ...
            windowMask( ...
                tRate, ...
                tStart, ...
                tEnd);
        pitchMask = ...
            windowMask( ...
                tPitchAxis, ...
                tStart, ...
                tEnd);
        effort = ...
            rmsFinite( ...
                pitchAxis(pitchMask));
        variation = ...
            derivativeRMS( ...
                tPitchAxis(pitchMask), ...
                pitchAxis(pitchMask));
        limit = ...
            AUTOPILOT.angularRate.rollPitchLimits. ...
            maxAxisCommand_rad_s;
        saturation = ...
            mean( ...
                abs(pitchAxis(pitchMask)) >= ...
                0.995*limit);
        M = ...
            assignTrackingMetrics( ...
                M, ...
                abs(errorSignal(mask)), ...
                effort, ...
                variation, ...
                saturation);
    case 'rate_roll_pitch'
        command = ...
            interpolateMatrix( ...
                tCmdRate, ...
                CmdRate(:,1:2), ...
                tRate);
        errorMatrix = ...
            Rate(:,1:2) - ...
            command;
        errorNorm = ...
            sqrt( ...
                sum( ...
                    errorMatrix.^2, ...
                    2));
        mask = ...
            windowMask( ...
                tRate, ...
                tStart, ...
                tEnd);
        effort = ...
            pairedSignalRMS( ...
                tRollAxis, ...
                rollAxis, ...
                tPitchAxis, ...
                pitchAxis, ...
                tStart, ...
                tEnd, ...
                CFG.simulation.metricSampleRate_Hz);
        variation = ...
            pairedDerivativeRMS( ...
                tRollAxis, ...
                rollAxis, ...
                tPitchAxis, ...
                pitchAxis, ...
                tStart, ...
                tEnd, ...
                CFG.simulation.metricSampleRate_Hz);
        limit = ...
            AUTOPILOT.angularRate.rollPitchLimits. ...
            maxAxisCommand_rad_s;
        saturation = ...
            pairedSaturationFraction( ...
                rollAxis, ...
                tRollAxis, ...
                pitchAxis, ...
                tPitchAxis, ...
                limit, ...
                tStart, ...
                tEnd, ...
                CFG.simulation.metricSampleRate_Hz);
        M = ...
            assignTrackingMetrics( ...
                M, ...
                errorNorm(mask), ...
                effort, ...
                variation, ...
                saturation);
    case 'rate_yaw'
        command = ...
            interpolateMatrix( ...
                tCmdRate, ...
                CmdRate(:,3), ...
                tRate);
        errorSignal = ...
            Rate(:,3) - ...
            command;
        mask = ...
            windowMask( ...
                tRate, ...
                tStart, ...
                tEnd);
        axisMask = ...
            windowMask( ...
                tYawAxis, ...
                tStart, ...
                tEnd);
        effort = ...
            rmsFinite( ...
                yawAxis(axisMask));
        variation = ...
            derivativeRMS( ...
                tYawAxis(axisMask), ...
                yawAxis(axisMask));
        limit = ...
            AUTOPILOT.angularRate.yaw.maxAxisCommand_rad_s;
        saturation = ...
            mean( ...
                abs(yawAxis(axisMask)) >= ...
                0.995*limit);
        M = ...
            assignTrackingMetrics( ...
                M, ...
                abs(errorSignal(mask)), ...
                effort, ...
                variation, ...
                saturation);
    case 'attitude_pitch'
        command = ...
            interp1( ...
                tCmdAttitude, ...
                CmdAttitude(:,2), ...
                tEuler, ...
                'linear', ...
                'extrap');
        errorSignal = ...
            Euler(:,2) - ...
            command;
        mask = ...
            windowMask( ...
                tEuler, ...
                tStart, ...
                tEnd);
        rateMask = ...
            windowMask( ...
                tCmdRate, ...
                tStart, ...
                tEnd);
        effort = ...
            rmsFinite( ...
                CmdRate(rateMask,2));
        variation = ...
            derivativeRMS( ...
                tCmdRate(rateMask), ...
                CmdRate(rateMask,2));
        limit = ...
            AUTOPILOT.attitude.maxRate_rad_s;
        saturation = ...
            mean( ...
                abs(CmdRate(rateMask,2)) >= ...
                0.995*limit);
        M = ...
            assignTrackingMetrics( ...
                M, ...
                abs(errorSignal(mask)), ...
                effort, ...
                variation, ...
                saturation);
    case 'attitude_roll_pitch'
        command = ...
            interpolateMatrix( ...
                tCmdAttitude, ...
                CmdAttitude, ...
                tEuler);
        errorMatrix = ...
            Euler(:,1:2) - ...
            command;
        errorNorm = ...
            sqrt( ...
                sum( ...
                    errorMatrix.^2, ...
                    2));
        mask = ...
            windowMask( ...
                tEuler, ...
                tStart, ...
                tEnd);
        rateMask = ...
            windowMask( ...
                tCmdRate, ...
                tStart, ...
                tEnd);
        effortSignal = ...
            sqrt( ...
                sum( ...
                    CmdRate(rateMask,1:2).^2, ...
                    2));
        effort = ...
            rmsFinite( ...
                effortSignal);
        variation = ...
            derivativeRMS( ...
                tCmdRate(rateMask), ...
                CmdRate(rateMask,1:2));
        limit = ...
            AUTOPILOT.attitude.maxRate_rad_s;
        saturation = ...
            mean( ...
                any( ...
                    abs(CmdRate(rateMask,1:2)) >= ...
                    0.995*limit, ...
                    2));
        M = ...
            assignTrackingMetrics( ...
                M, ...
                errorNorm(mask), ...
                effort, ...
                variation, ...
                saturation);
    case 'joint_roll_pitch'
        rateCommand = ...
            interpolateMatrix( ...
                tCmdRate, ...
                CmdRate(:,1:2), ...
                tRate);
        rateErrorMatrix = ...
            Rate(:,1:2) - ...
            rateCommand;
        rateErrorNorm = ...
            sqrt( ...
                sum( ...
                    rateErrorMatrix.^2, ...
                    2));
        rateMask = ...
            windowMask( ...
                tRate, ...
                tStart, ...
                tEnd);
        rateEffort = ...
            pairedSignalRMS( ...
                tRollAxis, ...
                rollAxis, ...
                tPitchAxis, ...
                pitchAxis, ...
                tStart, ...
                tEnd, ...
                CFG.simulation.metricSampleRate_Hz);
        rateVariation = ...
            pairedDerivativeRMS( ...
                tRollAxis, ...
                rollAxis, ...
                tPitchAxis, ...
                pitchAxis, ...
                tStart, ...
                tEnd, ...
                CFG.simulation.metricSampleRate_Hz);
        axisLimit = ...
            AUTOPILOT.angularRate.rollPitchLimits. ...
            maxAxisCommand_rad_s;
        rateSaturation = ...
            pairedSaturationFraction( ...
                rollAxis, ...
                tRollAxis, ...
                pitchAxis, ...
                tPitchAxis, ...
                axisLimit, ...
                tStart, ...
                tEnd, ...
                CFG.simulation.metricSampleRate_Hz);
        attitudeCommand = ...
            interpolateMatrix( ...
                tCmdAttitude, ...
                CmdAttitude, ...
                tEuler);
        attitudeErrorMatrix = ...
            Euler(:,1:2) - ...
            attitudeCommand;
        attitudeErrorNorm = ...
            sqrt( ...
                sum( ...
                    attitudeErrorMatrix.^2, ...
                    2));
        attitudeMask = ...
            windowMask( ...
                tEuler, ...
                tStart, ...
                tEnd);
        commandRateMask = ...
            windowMask( ...
                tCmdRate, ...
                tStart, ...
                tEnd);
        attitudeEffortSignal = ...
            sqrt( ...
                sum( ...
                    CmdRate(commandRateMask,1:2).^2, ...
                    2));
        attitudeEffort = ...
            rmsFinite( ...
                attitudeEffortSignal);
        attitudeVariation = ...
            derivativeRMS( ...
                tCmdRate(commandRateMask), ...
                CmdRate(commandRateMask,1:2));
        attitudeRateLimit = ...
            AUTOPILOT.attitude.maxRate_rad_s;
        attitudeSaturation = ...
            mean( ...
                any( ...
                    abs(CmdRate(commandRateMask,1:2)) >= ...
                    0.995*attitudeRateLimit, ...
                    2));
        M.RateTrackingRMSE = ...
            rmsFinite( ...
                rateErrorNorm(rateMask));
        M.RateTrackingP95 = ...
            percentileFinite( ...
                rateErrorNorm(rateMask), ...
                95);
        M.RateControlEffort = ...
            rateEffort;
        M.RateControlVariation = ...
            rateVariation;
        M.RateSaturationFraction = ...
            rateSaturation;
        M.AttitudeTrackingRMSE = ...
            rmsFinite( ...
                attitudeErrorNorm(attitudeMask));
        M.AttitudeTrackingP95 = ...
            percentileFinite( ...
                attitudeErrorNorm(attitudeMask), ...
                95);
        M.AttitudeControlEffort = ...
            attitudeEffort;
        M.AttitudeControlVariation = ...
            attitudeVariation;
        M.AttitudeSaturationFraction = ...
            attitudeSaturation;
    case 'yaw_angle'
        yawCommand = ...
            interp1( ...
                tYawRef, ...
                YawRef, ...
                tEuler, ...
                'linear', ...
                'extrap');
        yawError = ...
            wrapToPiLocal( ...
                Euler(:,3) - ...
                yawCommand);
        mask = ...
            windowMask( ...
                tEuler, ...
                tStart, ...
                tEnd);
        rateMask = ...
            windowMask( ...
                tCmdRate, ...
                tStart, ...
                tEnd);
        effort = ...
            rmsFinite( ...
                CmdRate(rateMask,3));
        variation = ...
            derivativeRMS( ...
                tCmdRate(rateMask), ...
                CmdRate(rateMask,3));
        limit = ...
            AUTOPILOT.yaw.angle.maxYawRate_rad_s;
        saturation = ...
            mean( ...
                abs(CmdRate(rateMask,3)) >= ...
                0.995*limit);
        M = ...
            assignTrackingMetrics( ...
                M, ...
                abs(yawError(mask)), ...
                effort, ...
                variation, ...
                saturation);
    case 'vertical_velocity'
        ref = ...
            interp1( ...
                tVelocityRef, ...
                VelocityRef(:,3), ...
                tTrueVelocity, ...
                'linear', ...
                'extrap');
        velocityError = ...
            TrueVelocity(:,3) - ...
            ref;
        mask = ...
            windowMask( ...
                tTrueVelocity, ...
                tStart, ...
                tEnd);
        thrustMask = ...
            windowMask( ...
                tThrustAxis, ...
                tStart, ...
                tEnd);
        effort = ...
            rmsFinite( ...
                thrustAxis(thrustMask));
        variation = ...
            derivativeRMS( ...
                tThrustAxis(thrustMask), ...
                thrustAxis(thrustMask));
        limit = ...
            AUTOPILOT.vertical.velocity.maxAxisCommand_rad_s;
        saturation = ...
            mean( ...
                abs(thrustAxis(thrustMask)) >= ...
                0.995*limit);
        M = ...
            assignTrackingMetrics( ...
                M, ...
                abs(velocityError(mask)), ...
                effort, ...
                variation, ...
                saturation);
    case 'horizontal_velocity'
        ref = ...
            interpolateMatrix( ...
                tVelocityRef, ...
                VelocityRef(:,1:2), ...
                tTrueVelocity);
        velocityError = ...
            TrueVelocity(:,1:2) - ...
            ref;
        velocityErrorNorm = ...
            sqrt( ...
                sum( ...
                    velocityError.^2, ...
                    2));
        mask = ...
            windowMask( ...
                tTrueVelocity, ...
                tStart, ...
                tEnd);
        attitudeMask = ...
            windowMask( ...
                tCmdAttitude, ...
                tStart, ...
                tEnd);
        effortSignal = ...
            sqrt( ...
                sum( ...
                    CmdAttitude(attitudeMask,:).^2, ...
                    2));
        effort = ...
            rmsFinite( ...
                effortSignal);
        variation = ...
            derivativeRMS( ...
                tCmdAttitude(attitudeMask), ...
                CmdAttitude(attitudeMask,:));
        tiltMagnitude = ...
            sqrt( ...
                sum( ...
                    CmdAttitude(attitudeMask,:).^2, ...
                    2));
        saturation = ...
            mean( ...
                tiltMagnitude >= ...
                0.995 * ...
                AUTOPILOT.horizontal.maxTilt_rad);
        M = ...
            assignTrackingMetrics( ...
                M, ...
                velocityErrorNorm(mask), ...
                effort, ...
                variation, ...
                saturation);
    case 'vertical_position'
        reference = ...
            interp1( ...
                tPositionRef, ...
                PositionRef(:,3), ...
                tTruePosition, ...
                'linear', ...
                'extrap');
        positionError = ...
            TruePosition(:,3) - ...
            reference;
        mask = ...
            windowMask( ...
                tTruePosition, ...
                tStart, ...
                tEnd);
        WP = ...
            waypointMetrics( ...
                Telemetry, ...
                'vertical');
        M = ...
            assignPositionMetrics( ...
                M, ...
                abs(positionError(mask)), ...
                WP, ...
                omegaVariation);
    case 'horizontal_position'
        reference = ...
            interpolateMatrix( ...
                tPositionRef, ...
                PositionRef(:,1:2), ...
                tTruePosition);
        positionError = ...
            TruePosition(:,1:2) - ...
            reference;
        positionErrorNorm = ...
            sqrt( ...
                sum( ...
                    positionError.^2, ...
                    2));
        mask = ...
            windowMask( ...
                tTruePosition, ...
                tStart, ...
                tEnd);
        WP = ...
            waypointMetrics( ...
                Telemetry, ...
                'horizontal');
        M = ...
            assignPositionMetrics( ...
                M, ...
                positionErrorNorm(mask), ...
                WP, ...
                omegaVariation);
    otherwise
        error( ...
            'QuadrotorFramework:ControllerTuningUnknownObjective', ...
            'Unknown controller objective "%s".', ...
            STAGE.objectiveType);
end
end
function M = assignTrackingMetrics( ...
    M, ...
    errorSignal, ...
    effort, ...
    variation, ...
    saturation)
errorSignal = ...
    errorSignal( ...
        isfinite(errorSignal));
if isempty(errorSignal)
    error( ...
        'QuadrotorFramework:ControllerTuningEmptyError', ...
        'No valid tracking-error samples were available.');
end
if ~isfinite(effort) || ...
        ~isfinite(variation) || ...
        ~isfinite(saturation)
    error( ...
        'QuadrotorFramework:ControllerTuningInvalidTrackingMetric', ...
        'Controller tracking metric is NaN or Inf.');
end
M.TrackingRMSE = ...
    sqrt( ...
        mean( ...
            errorSignal.^2));
M.TrackingP95 = ...
    percentileFinite( ...
        errorSignal, ...
        95);
M.ControlEffort = ...
    effort;
M.ControlVariation = ...
    variation;
M.SaturationFraction = ...
    saturation;
end
function M = assignPositionMetrics( ...
    M, ...
    errorSignal, ...
    WP, ...
    controlVariation)
errorSignal = ...
    errorSignal( ...
        isfinite(errorSignal));
if isempty(errorSignal)
    error( ...
        'QuadrotorFramework:ControllerTuningEmptyPositionError', ...
        'No valid position-error samples were available.');
end
if ~isfinite(controlVariation)
    error( ...
        'QuadrotorFramework:ControllerTuningInvalidPositionControl', ...
        'Position-loop control variation is NaN or Inf.');
end
M.PositionRMSE = ...
    sqrt( ...
        mean( ...
            errorSignal.^2));
M.PositionP95 = ...
    percentileFinite( ...
        errorSignal, ...
        95);
M.PositionMaximumError = ...
    max( ...
        errorSignal);
M.WaypointArrivalMean = ...
    WP.ArrivalMean;
M.HoldRMSEMean = ...
    WP.HoldRMSEMean;
M.OvershootMaximum = ...
    WP.OvershootMaximum;
M.ControlVariation = ...
    controlVariation;
end
function MISSION = evaluateMissionAcceptance( ...
    t, ...
    Telemetry)
if size(Telemetry,2) < 8
    error( ...
        'QuadrotorFramework:ControllerTelemetrySize', ...
        'Telemetry must contain at least eight columns.');
end
Phase = ...
    round( ...
        double( ...
            Telemetry(:,2)));
CGSComplete = ...
    double( ...
        Telemetry(:,4)) > ...
    0.5;
Landed = ...
    double( ...
        Telemetry(:,8)) > ...
    0.5;
previousPhase = [ ...
    NaN; ...
    Phase(1:end-1)];
missionStartIndex = ...
    find( ...
        Phase == 1 & ...
        previousPhase ~= 1, ...
        1, ...
        'first');
if isempty(missionStartIndex)
    error( ...
        'QuadrotorFramework:ControllerNoTakeoff', ...
        'No TAKEOFF phase was detected.');
end
if size(Telemetry,2) >= 59
    values = ...
        Telemetry( ...
            missionStartIndex:end, ...
            59);
    valid = ...
        isfinite(values) & ...
        values >= 3 & ...
        abs(values-round(values)) < 1e-9;
    firstValid = ...
        find( ...
            valid, ...
            1, ...
            'first');
    if isempty(firstValid)
        error( ...
            'QuadrotorFramework:ControllerInvalidNumWaypoints', ...
            'No valid NumWaypoints value was found.');
    end
    N = ...
        round( ...
            values(firstValid));
else
    N = ...
        7;
end
completePhase = ...
    2*N - 2;
abortedPhase = ...
    2*N - 1;
airborneRelative = ...
    find( ...
        ~Landed(missionStartIndex:end), ...
        1, ...
        'first');
if isempty(airborneRelative)
    error( ...
        'QuadrotorFramework:ControllerNoAirborneState', ...
        'Vehicle never became airborne.');
end
airborneIndex = ...
    missionStartIndex + ...
    airborneRelative - ...
    1;
completeRelative = ...
    find( ...
        CGSComplete(airborneIndex:end), ...
        1, ...
        'first');
NavigationCompleted = ...
    ~isempty(completeRelative);
if NavigationCompleted
    navigationCompleteIndex = ...
        airborneIndex + ...
        completeRelative - ...
        1;
else
    navigationCompleteIndex = ...
        NaN;
end
FailsafeAborted = ...
    any( ...
        Phase(missionStartIndex:end) == ...
        abortedPhase);
LandedConfirmed = ...
    false;
landingIndex = ...
    NaN;
if NavigationCompleted
    landedAfterComplete = ...
        Landed(navigationCompleteIndex:end);
    previousLanded = [ ...
        Landed(max( ...
            missionStartIndex, ...
            navigationCompleteIndex-1)); ...
        landedAfterComplete(1:end-1)];
    landingRelative = ...
        find( ...
            landedAfterComplete & ...
            ~previousLanded, ...
            1, ...
            'first');
    if ~isempty(landingRelative)
        landingIndex = ...
            navigationCompleteIndex + ...
            landingRelative - ...
            1;
        LandedConfirmed = ...
            true;
    elseif Landed(end)
        landingIndex = ...
            find( ...
                Landed, ...
                1, ...
                'last');
        LandedConfirmed = ...
            true;
    end
end
MISSION = ...
    struct();
MISSION.NumWaypoints = ...
    N;
MISSION.CompletePhase = ...
    completePhase;
MISSION.AbortedPhase = ...
    abortedPhase;
MISSION.NavigationCompleted = ...
    NavigationCompleted;
MISSION.LandedConfirmed = ...
    LandedConfirmed;
MISSION.FailsafeAborted = ...
    FailsafeAborted;
MISSION.Completed = ...
    NavigationCompleted && ...
    LandedConfirmed && ...
    ~FailsafeAborted;
MISSION.MissionStartTime_s = ...
    t(missionStartIndex);
if NavigationCompleted
    MISSION.NavigationCompleteTime_s = ...
        t(navigationCompleteIndex);
else
    MISSION.NavigationCompleteTime_s = ...
        NaN;
end
if LandedConfirmed
    MISSION.LandingTime_s = ...
        t(landingIndex);
else
    MISSION.LandingTime_s = ...
        NaN;
end
end
function STATUS = evaluateMissionRequirementStatus( ...
    MISSION, ...
    CFG)
identifiers = ...
    strings( ...
        0, ...
        1);
messages = ...
    strings( ...
        0, ...
        1);
if CFG.simulation.requireMissionCompletion && ...
        ~MISSION.NavigationCompleted
    identifiers(end+1,1) = ...
        "QuadrotorFramework:ControllerTuningMissionIncomplete";
    messages(end+1,1) = ...
        "CGS Complete was not reached.";
end
if CFG.simulation.requireLanded && ...
        ~MISSION.LandedConfirmed
    identifiers(end+1,1) = ...
        "QuadrotorFramework:ControllerTuningNoLanding";
    messages(end+1,1) = ...
        "Final physical landing was not confirmed.";
end
if CFG.simulation.rejectFailsafe && ...
        MISSION.FailsafeAborted
    identifiers(end+1,1) = ...
        "QuadrotorFramework:ControllerTuningFailsafe";
    messages(end+1,1) = ...
        "Mission entered the generic ABORTED/failsafe phase.";
end
STATUS = ...
    struct();
STATUS.accepted = ...
    isempty(identifiers);
STATUS.softFailure = ...
    ~STATUS.accepted;
STATUS.identifiers = ...
    identifiers;
STATUS.messages = ...
    messages;
if STATUS.accepted
    STATUS.message = ...
        'OK';
else
    parts = ...
        strings( ...
            numel(identifiers), ...
            1);
    for k = 1:numel(identifiers)
        parts(k) = ...
            identifiers(k) + ...
            ": " + ...
            messages(k);
    end
    STATUS.message = ...
        char( ...
            strjoin( ...
                parts, ...
                ' | '));
end
end
function verifyEstimatedFeedback( ...
    Telemetry, ...
    CFG)
if size(Telemetry,2) < 58
    error('QuadrotorFramework:ControllerEstimatedFeedbackTelemetry','Telemetry does not contain TRUE/EST feedback channels.');
end
Selected = double(Telemetry(:,12:14));
True = double(Telemetry(:,50:52));
Estimated = double(Telemetry(:,56:58));
valid = all(isfinite(Selected),2) & all(isfinite(True),2) & all(isfinite(Estimated),2);
Selected = Selected(valid,:);
True = True(valid,:);
Estimated = Estimated(valid,:);
if size(Selected,1) < 10
    error('QuadrotorFramework:ControllerEstimatedFeedbackSamples','Insufficient telemetry for EST-feedback verification.');
end
maximumLagSamples = max(1,round(CFG.experiment.estimatedFeedbackMaximumLag_s * CFG.simulation.metricSampleRate_Hz));
selectedVsEst = bestAlignedRMSE(Selected,Estimated,maximumLagSamples);
selectedVsTrue = bestAlignedRMSE(Selected,True,maximumLagSamples);
strictPass = selectedVsEst <= CFG.experiment.estimatedFeedbackTolerance_m;
relativePass = selectedVsEst <= CFG.experiment.estimatedFeedbackRelativeTolerance * max(selectedVsTrue,CFG.experiment.estimatedFeedbackTolerance_m);
if ~(strictPass || relativePass)
    error('QuadrotorFramework:ControllerTuningNotEstimatedFeedback',['Controller feedback does not appear to be EST. Selected-vs-EST RMSE = %.6g m, Selected-vs-TRUE RMSE = %.6g m.'],selectedVsEst,selectedVsTrue);
end
end
function bestRMSE = bestAlignedRMSE( ...
    A, ...
    B, ...
    maximumLag)
bestRMSE = ...
    inf;
for lag = -maximumLag:maximumLag
    if lag >= 0
        indexA = ...
            (1+lag):size(A,1);
        indexB = ...
            1:(size(B,1)-lag);
    else
        lagAbs = ...
            abs(lag);
        indexA = ...
            1:(size(A,1)-lagAbs);
        indexB = ...
            (1+lagAbs):size(B,1);
    end
    if numel(indexA) < 5 || ...
            numel(indexB) < 5
        continue;
    end
    D = ...
        A(indexA,:) - ...
        B(indexB,:);
    value = ...
        sqrt( ...
            mean( ...
                sum( ...
                    D.^2, ...
                    2), ...
                'omitnan'));
    if isfinite(value)
        bestRMSE = ...
            min( ...
                bestRMSE, ...
                value);
    end
end
end
function WP = waypointMetrics( ...
    Telemetry, ...
    directionMode)
Phase = ...
    round( ...
        Telemetry(:,2));
PositionTrue = ...
    double( ...
        Telemetry(:,50:52));
[MissionPlan,N] = ...
    decodeMissionPlan( ...
        Telemetry);
arrival = [];
holdRMSE = [];
overshoot = [];
for pointIndex = 2:(N-1)
    movePhase = ...
        2*pointIndex - 3;
    holdPhase = ...
        movePhase + 1;
    moveStart = ...
        find( ...
            Phase == movePhase, ...
            1, ...
            'first');
    holdIndices = ...
        find( ...
            Phase == holdPhase);
    if isempty(moveStart) || ...
            isempty(holdIndices)
        continue;
    end
    holdStart = ...
        holdIndices(1);
    holdEnd = ...
        holdIndices(end);
    target = ...
        MissionPlan(1:3,pointIndex).';
    previous = ...
        MissionPlan(1:3,pointIndex-1).';
    segment = ...
        target - ...
        previous;
    switch lower(directionMode)
        case 'vertical'
            if abs(segment(3)) <= 1e-8
                continue;
            end
            arrivalError = ...
                abs( ...
                    PositionTrue(holdStart,3) - ...
                    target(3));
            holdError = ...
                abs( ...
                    PositionTrue(holdIndices,3) - ...
                    target(3));
            signDirection = ...
                sign(segment(3));
            projected = ...
                ( ...
                PositionTrue(moveStart:holdEnd,3) - ...
                target(3)) .* ...
                signDirection;
        case 'horizontal'
            horizontalSegment = ...
                segment(1:2);
            distance = ...
                norm(horizontalSegment);
            if distance <= 1e-8
                continue;
            end
            arrivalError = ...
                norm( ...
                    PositionTrue(holdStart,1:2) - ...
                    target(1:2));
            holdError = ...
                sqrt( ...
                    sum( ...
                        ( ...
                        PositionTrue(holdIndices,1:2) - ...
                        target(1:2)).^2, ...
                        2));
            directionUnit = ...
                horizontalSegment / ...
                distance;
            projected = ...
                ( ...
                PositionTrue(moveStart:holdEnd,1:2) - ...
                target(1:2)) * ...
                directionUnit.';
        otherwise
            error( ...
                'QuadrotorFramework:ControllerWaypointMetricMode', ...
                'Unknown waypoint metric mode.');
    end
    arrival(end+1,1) = ...
        arrivalError;
    holdRMSE(end+1,1) = ...
        sqrt( ...
            mean( ...
                holdError.^2, ...
                'omitnan'));
    overshoot(end+1,1) = ...
        max( ...
            0, ...
            max( ...
                projected, ...
                [], ...
                'omitnan'));
end
WP = ...
    struct();
if isempty(arrival)
    WP.ArrivalMean = ...
        0;
    WP.HoldRMSEMean = ...
        0;
    WP.OvershootMaximum = ...
        0;
else
    WP.ArrivalMean = ...
        mean( ...
            arrival, ...
            'omitnan');
    WP.HoldRMSEMean = ...
        mean( ...
            holdRMSE, ...
            'omitnan');
    WP.OvershootMaximum = ...
        max( ...
            overshoot, ...
            [], ...
            'omitnan');
end
end
function [MissionPlan,N] = decodeMissionPlan(Telemetry)
telemetryLength = ...
    size( ...
        Telemetry, ...
        2);
if telemetryLength == 58
    N = ...
        7;
    MissionPlan = ...
        zeros( ...
            4, ...
            7);
    sample = ...
        Telemetry(1,:);
    MissionPlan(1,:) = sample(15:21);
    MissionPlan(2,:) = sample(22:28);
    MissionPlan(3,:) = sample(29:35);
    MissionPlan(4,:) = sample(36:42);
    return;
end
if telemetryLength < 71 || ...
        mod(telemetryLength-59,4) ~= 0
    error( ...
        'QuadrotorFramework:ControllerMissionPlanTelemetry', ...
        'Invalid generic telemetry size.');
end
M = ...
    (telemetryLength-59) / ...
    4;
rawN = ...
    Telemetry(:,59);
validN = ...
    isfinite(rawN) & ...
    rawN >= 3 & ...
    rawN <= M & ...
    abs(rawN-round(rawN)) < 1e-9;
index = ...
    find( ...
        validN, ...
        1, ...
        'first');
if isempty(index)
    error( ...
        'QuadrotorFramework:ControllerMissionPlanNumWaypoints', ...
        'Unable to determine NumWaypoints.');
end
N = ...
    round( ...
        rawN(index));
sample = ...
    Telemetry(index,:);
northStart = 60;
eastStart  = 60 + M;
downStart  = 60 + 2*M;
yawStart   = 60 + 3*M;
MissionPlan = ...
    zeros( ...
        4, ...
        N);
MissionPlan(1,:) = ...
    sample( ...
        northStart : ...
        northStart+N-1);
MissionPlan(2,:) = ...
    sample( ...
        eastStart : ...
        eastStart+N-1);
MissionPlan(3,:) = ...
    sample( ...
        downStart : ...
        downStart+N-1);
MissionPlan(4,:) = ...
    sample( ...
        yawStart : ...
        yawStart+N-1);
end
function [J,RESULT] = finalizeCandidate( ...
    CANDIDATE, ...
    RUN, ...
    runSucceeded, ...
    strictRunSucceeded, ...
    metricsAvailable, ...
    softBaselineAccepted, ...
    messages, ...
    baselineMetrics, ...
    CFG, ...
    STAGE, ...
    missionPolicy)
RESULT = emptyCandidateResult();
RESULT.z = CANDIDATE.z;
RESULT.multipliers = CANDIDATE.multipliers;
RESULT.gainValues = CANDIDATE.gainValues;
RESULT.gainTable = CANDIDATE.gainTable;
RESULT.metrics = RUN;
RESULT.runSucceeded = runSucceeded;
RESULT.strictRunSucceeded = strictRunSucceeded;
RESULT.metricsAvailable = metricsAvailable;
RESULT.softBaselineAccepted = softBaselineAccepted;
RESULT.missionPolicy = string(missionPolicy);
RESULT.messages = messages;
RESULT.stageID = STAGE.id;
RESULT.stageName = STAGE.name;
RESULT.plantModels = double(CFG.experiment.plantModels(:));
RESULT.plantWeights = double(CFG.experiment.plantWeights(:));
RESULT.controllerSet = string(CFG.experiment.controllerSet);
RESULT.trajectoryID = double(CFG.experiment.trajectoryID);
RESULT.feedbackSource = string(CFG.experiment.feedbackSource);
RESULT.metricStateSource = string(CFG.experiment.metricStateSource);
if isempty(baselineMetrics)
    RESULT.success = all(runSucceeded(:)) && all(metricsAvailable(:));
    RESULT.strictMissionSuccess = all(strictRunSucceeded(:));
    RESULT.softBaselineUsed = any(softBaselineAccepted(:));
    RESULT.cost = NaN;
    RESULT.runCosts = [];
    J = NaN;
    return;
end
RESULT.strictMissionSuccess = all(strictRunSucceeded(:));
RESULT.softBaselineUsed = any(softBaselineAccepted(:));
if strcmp(missionPolicy,'strict')
    candidateRunsUsable = ...
        all(runSucceeded(:)) && ...
        all(strictRunSucceeded(:)) && ...
        all(metricsAvailable(:));
else
    candidateRunsUsable = ...
        all(runSucceeded(:)) && ...
        all(metricsAvailable(:));
end
if ~candidateRunsUsable
    J = CFG.cost.failurePenalty;
    RESULT.success = false;
    RESULT.cost = J;
    RESULT.runCosts = [];
    return;
end
numberOfPlants = numel(CFG.experiment.plantModels);
if size(RUN,1) ~= numberOfPlants
    error('QuadrotorFramework:ControllerRunPlantCount','Candidate metrics do not match configured plant count.');
end
if isscalar(baselineMetrics) && numel(RUN) > 1
    baselineMetrics = repmat(baselineMetrics,size(RUN));
end
if numel(baselineMetrics) ~= numel(RUN)
    error('QuadrotorFramework:ControllerBaselineMetricCount',['Baseline metric count (%d) does not match candidate run count (%d).'],numel(baselineMetrics),numel(RUN));
end
if ~isequal(size(baselineMetrics),size(RUN))
    baselineMetrics = reshape(baselineMetrics,size(RUN));
end
runCost = zeros(size(RUN));
for runIndex = 1:numel(RUN)
    runCost(runIndex) = stageCost(RUN(runIndex),baselineMetrics(runIndex),CFG,STAGE);
end
softMissionPenalty = ...
    2.0;
if isfield(CFG,'cost') && ...
        isstruct(CFG.cost) && ...
        isfield(CFG.cost,'softMissionPenalty')
    softMissionPenalty = ...
        double( ...
            CFG.cost.softMissionPenalty);
end
if ~isscalar(softMissionPenalty) || ...
        ~isfinite(softMissionPenalty) || ...
        softMissionPenalty < 0
    error( ...
        'QuadrotorFramework:ControllerSoftMissionPenalty', ...
        'CFG.cost.softMissionPenalty must be a finite nonnegative scalar.');
end
if strcmp(missionPolicy,'baseline') && ...
        any(softBaselineAccepted(:))
    runCost = ...
        runCost + ...
        softMissionPenalty * ...
        double(softBaselineAccepted);
end
if any(~isfinite(runCost(:))) || any(runCost(:) >= CFG.cost.failurePenalty)
    J = CFG.cost.failurePenalty;
    RESULT.success = false;
    RESULT.cost = J;
    RESULT.runCosts = runCost;
    return;
end
plantWeights = double(CFG.experiment.plantWeights(:));
seedMeanCost = mean(runCost,2);
switch lower(char(CFG.experiment.plantAggregation))
    case 'weighted_mean'
        J = sum(plantWeights .* seedMeanCost);
    case 'worst_case'
        J = max(seedMeanCost);
    otherwise
        error('QuadrotorFramework:ControllerPlantAggregation','Unknown plant aggregation "%s".',CFG.experiment.plantAggregation);
end
J = J + CFG.cost.parameterRegularizationWeight * mean(CANDIDATE.z.^2);
if ~isfinite(J) || J < 0
    J = CFG.cost.failurePenalty;
end
RESULT.success = J < CFG.cost.failurePenalty;
RESULT.cost = J;
RESULT.runCosts = runCost;
RESULT.plantMeanCosts = seedMeanCost;
end
function J = stageCost( ...
    M, ...
    B, ...
    CFG, ...
    STAGE)
minimum = ...
    CFG.cost.minimumNormalization;
objectiveType = ...
    lower( ...
        char(STAGE.objectiveType));
if strcmp(objectiveType,'joint_roll_pitch')
    rateCost = ...
        trackingMetricCost( ...
            M.RateTrackingRMSE, ...
            M.RateTrackingP95, ...
            M.RateControlEffort, ...
            M.RateControlVariation, ...
            M.RateSaturationFraction, ...
            B.RateTrackingRMSE, ...
            B.RateTrackingP95, ...
            B.RateControlEffort, ...
            B.RateControlVariation, ...
            B.RateSaturationFraction, ...
            CFG.cost.tracking, ...
            minimum);
    attitudeCost = ...
        trackingMetricCost( ...
            M.AttitudeTrackingRMSE, ...
            M.AttitudeTrackingP95, ...
            M.AttitudeControlEffort, ...
            M.AttitudeControlVariation, ...
            M.AttitudeSaturationFraction, ...
            B.AttitudeTrackingRMSE, ...
            B.AttitudeTrackingP95, ...
            B.AttitudeControlEffort, ...
            B.AttitudeControlVariation, ...
            B.AttitudeSaturationFraction, ...
            CFG.cost.tracking, ...
            minimum);
    rateWeight = ...
        0.5;
    attitudeWeight = ...
        0.5;
    if isfield(CFG.cost,'joint') && ...
            isstruct(CFG.cost.joint)
        if isfield(CFG.cost.joint,'rateWeight')
            rateWeight = ...
                double(CFG.cost.joint.rateWeight);
        end
        if isfield(CFG.cost.joint,'attitudeWeight')
            attitudeWeight = ...
                double(CFG.cost.joint.attitudeWeight);
        end
    end
    if ~isscalar(rateWeight) || ...
            ~isscalar(attitudeWeight) || ...
            ~isfinite(rateWeight) || ...
            ~isfinite(attitudeWeight) || ...
            rateWeight < 0 || ...
            attitudeWeight < 0 || ...
            abs(rateWeight+attitudeWeight-1) > 1e-12
        error( ...
            'QuadrotorFramework:ControllerJointObjectiveWeights', ...
            'Joint roll-pitch objective weights must be finite, nonnegative, and sum to one.');
    end
    J = ...
        rateWeight*rateCost + ...
        attitudeWeight*attitudeCost;
elseif ismember( ...
        objectiveType, ...
        { ...
        'rate_pitch', ...
        'rate_roll_pitch', ...
        'rate_yaw', ...
        'attitude_pitch', ...
        'attitude_roll_pitch', ...
        'yaw_angle', ...
        'vertical_velocity', ...
        'horizontal_velocity'})
    J = ...
        trackingMetricCost( ...
            M.TrackingRMSE, ...
            M.TrackingP95, ...
            M.ControlEffort, ...
            M.ControlVariation, ...
            M.SaturationFraction, ...
            B.TrackingRMSE, ...
            B.TrackingP95, ...
            B.ControlEffort, ...
            B.ControlVariation, ...
            B.SaturationFraction, ...
            CFG.cost.tracking, ...
            minimum);
else
    W = ...
        CFG.cost.position;
    J = ...
        W.rmse * ...
        ratioMetric( ...
            M.PositionRMSE, ...
            B.PositionRMSE, ...
            minimum) + ...
        W.p95 * ...
        ratioMetric( ...
            M.PositionP95, ...
            B.PositionP95, ...
            minimum) + ...
        W.maximumError * ...
        ratioMetric( ...
            M.PositionMaximumError, ...
            B.PositionMaximumError, ...
            minimum) + ...
        W.waypointArrival * ...
        ratioMetric( ...
            M.WaypointArrivalMean, ...
            B.WaypointArrivalMean, ...
            minimum) + ...
        W.holdRMSE * ...
        ratioMetric( ...
            M.HoldRMSEMean, ...
            B.HoldRMSEMean, ...
            minimum) + ...
        W.overshoot * ...
        ratioMetric( ...
            M.OvershootMaximum, ...
            B.OvershootMaximum, ...
            minimum) + ...
        W.controlVariation * ...
        ratioMetric( ...
            M.MotorVariationRMS_rad_s2, ...
            B.MotorVariationRMS_rad_s2, ...
            minimum);
end
end
function J = trackingMetricCost( ...
    rmseValue, ...
    p95Value, ...
    effortValue, ...
    variationValue, ...
    saturationValue, ...
    baselineRMSE, ...
    baselineP95, ...
    baselineEffort, ...
    baselineVariation, ...
    baselineSaturation, ...
    W, ...
    minimum)
J = ...
    W.rmse * ...
    ratioMetric( ...
        rmseValue, ...
        baselineRMSE, ...
        minimum) + ...
    W.p95 * ...
    ratioMetric( ...
        p95Value, ...
        baselineP95, ...
        minimum) + ...
    W.controlEffort * ...
    ratioMetric( ...
        effortValue, ...
        baselineEffort, ...
        minimum) + ...
    W.controlVariation * ...
    ratioMetric( ...
        variationValue, ...
        baselineVariation, ...
        minimum) + ...
    W.saturation * ...
    saturationCost( ...
        saturationValue, ...
        baselineSaturation, ...
        minimum);
end
function r = ratioMetric( ...
    value, ...
    baseline, ...
    minimum)
value = ...
    double(value);
baseline = ...
    double(baseline);
if ~isfinite(value) || ...
        value < 0 || ...
        ~isfinite(baseline) || ...
        baseline < 0
    r = ...
        inf;
    return;
end
if baseline <= minimum
    if value <= minimum
        r = ...
            1;
    else
        r = ...
            1 + ...
            value / ...
            minimum;
    end
else
    r = ...
        value / ...
        baseline;
end
end
function r = saturationCost( ...
    value, ...
    baseline, ...
    minimum)
if ~isfinite(value) || ...
        value < 0 || ...
        ~isfinite(baseline) || ...
        baseline < 0
    r = ...
        inf;
    return;
end
if baseline <= minimum && ...
        value <= minimum
    r = ...
        1;
    return;
end
r = ...
    ratioMetric( ...
        value, ...
        baseline, ...
        minimum);
end
function [J,RESULT] = invalidCandidateResult( ...
    z, ...
    CFG, ...
    STAGE, ...
    message)
J = ...
    CFG.cost.failurePenalty;
RESULT = ...
    emptyCandidateResult();
RESULT.success = ...
    false;
RESULT.cost = ...
    J;
RESULT.z = ...
    double(z(:));
RESULT.stageID = ...
    STAGE.id;
RESULT.stageName = ...
    STAGE.name;
RESULT.messages = ...
    {message};
RESULT.plantModels = double(CFG.experiment.plantModels(:));
RESULT.plantWeights = double(CFG.experiment.plantWeights(:));
RESULT.controllerSet = string(CFG.experiment.controllerSet);
RESULT.trajectoryID = double(CFG.experiment.trajectoryID);
RESULT.feedbackSource = string(CFG.experiment.feedbackSource);
RESULT.metricStateSource = string(CFG.experiment.metricStateSource);
end
function M = emptyMetricStructure()
M = struct('success',false,'SeedOffset',NaN,'PlantModel',NaN,'TrackingRMSE',NaN,'TrackingP95',NaN,'ControlEffort',NaN,'ControlVariation',NaN,'SaturationFraction',NaN,'RateTrackingRMSE',NaN,'RateTrackingP95',NaN,'RateControlEffort',NaN,'RateControlVariation',NaN,'RateSaturationFraction',NaN,'AttitudeTrackingRMSE',NaN,'AttitudeTrackingP95',NaN,'AttitudeControlEffort',NaN,'AttitudeControlVariation',NaN,'AttitudeSaturationFraction',NaN,'PositionRMSE',NaN,'PositionP95',NaN,'PositionMaximumError',NaN,'WaypointArrivalMean',NaN,'HoldRMSEMean',NaN,'OvershootMaximum',NaN,'MotorVariationRMS_rad_s2',NaN,'MissionStartTime_s',NaN,'MetricWindowEndTime_s',NaN,'NavigationCompleteTime_s',NaN,'LandingTime_s',NaN,'NavigationCompleted',false,'LandedConfirmed',false,'FailsafeAborted',false,'Completed',false,'MissionAccepted',false,'NumWaypoints',NaN);
end
function R = emptyCandidateResult()
R = ...
    struct( ...
    ...
    'success',false, ...
    'cost',NaN, ...
    'stageID',NaN, ...
    'stageName',"", ...
    'z',[], ...
    'multipliers',[], ...
    'gainValues',[], ...
    'gainTable',table(), ...
    'metrics',[], ...
    'runSucceeded',[], ...
    'strictRunSucceeded',[], ...
    'metricsAvailable',[], ...
    'softBaselineAccepted',[], ...
    'strictMissionSuccess',false, ...
    'softBaselineUsed',false, ...
    'missionPolicy',"", ...
    'messages',{{}}, ...
    'seedCosts',[], ...
    'plantModels',[], ...
    'plantWeights',[], ...
    'runCosts',[], ...
    'plantMeanCosts',[], ...
    'controllerSet',"", ...
    'trajectoryID',NaN, ...
    'feedbackSource',"", ...
    'metricStateSource',"");
end
function [t,X] = signalMatrix(signal)
if isa( ...
        signal, ...
        'Simulink.SimulationData.Signal')
    signal = ...
        signal.Values;
end
if ~isa(signal,'timeseries')
    error( ...
        'QuadrotorFramework:ControllerSignalType', ...
        'Expected a logged timeseries signal.');
end
t = ...
    double( ...
        signal.Time(:));
D = ...
    squeeze( ...
        signal.Data);
nt = ...
    numel(t);
if nt == 1
    X = ...
        reshape( ...
            D, ...
            1, ...
            []);
elseif isvector(D)
    if numel(D) ~= nt
        error( ...
            'QuadrotorFramework:ControllerSignalOrientation', ...
            'Unable to determine signal orientation.');
    end
    X = ...
        D(:);
elseif size(D,1) == nt
    X = ...
        reshape( ...
            D, ...
            nt, ...
            []);
elseif size(D,2) == nt
    X = ...
        D.';
elseif size(D,ndims(D)) == nt
    order = [ ...
        ndims(D), ...
        1:(ndims(D)-1)];
    D = ...
        permute( ...
            D, ...
            order);
    X = ...
        reshape( ...
            D, ...
            nt, ...
            []);
else
    error( ...
        'QuadrotorFramework:ControllerSignalDimensions', ...
        'Unable to match signal dimensions with time.');
end
X = ...
    double(X);
end
function [t,X] = extractBusField( ...
    bus, ...
    path)
value = ...
    bus;
for k = 1:numel(path)
    fieldName = ...
        path{k};
    if isa( ...
            value, ...
            'Simulink.SimulationData.Signal')
        value = ...
            value.Values;
    end
    if isstruct(value)
        if ~isfield(value,fieldName)
            error( ...
                'QuadrotorFramework:ControllerMissingBusField', ...
                'Logged bus does not contain "%s".', ...
                fieldName);
        end
        value = ...
            value.(fieldName);
    elseif isobject(value)
        if ~isprop(value,fieldName)
            error( ...
                'QuadrotorFramework:ControllerMissingBusProperty', ...
                'Logged bus does not contain "%s".', ...
                fieldName);
        end
        value = ...
            value.(fieldName);
    else
        error( ...
            'QuadrotorFramework:ControllerBusAccess', ...
            'Unable to access logged field "%s".', ...
            fieldName);
    end
end
[t,X] = ...
    signalMatrix( ...
        value);
end
function Y = interpolateMatrix( ...
    sourceTime, ...
    sourceData, ...
    targetTime)
Y = ...
    zeros( ...
        numel(targetTime), ...
        size(sourceData,2));
for column = 1:size(sourceData,2)
    Y(:,column) = ...
        interp1( ...
            sourceTime, ...
            sourceData(:,column), ...
            targetTime, ...
            'linear', ...
            'extrap');
end
end
function mask = windowMask( ...
    t, ...
    tStart, ...
    tEnd)
mask = ...
    isfinite(t) & ...
    t >= tStart & ...
    t <= tEnd;
if ~any(mask)
    error( ...
        'QuadrotorFramework:ControllerEmptyMetricWindow', ...
        'No samples exist inside the controller metric window.');
end
end
function value = rmsFinite(x)
x = ...
    double(x);
x = ...
    x( ...
        isfinite(x));
if isempty(x)
    value = ...
        inf;
else
    value = ...
        sqrt( ...
            mean( ...
                x.^2));
end
end
function value = derivativeRMS( ...
    t, ...
    X)
t = ...
    double(t(:));
X = ...
    double(X);
if numel(t) < 2 || ...
        size(X,1) < 2
    value = ...
        inf;
    return;
end
if size(X,1) ~= ...
        numel(t)
    error( ...
        'QuadrotorFramework:ControllerDerivativeDimensions', ...
        'Derivative signal and time dimensions do not agree.');
end
dt = ...
    diff(t);
dX = ...
    diff( ...
        X, ...
        1, ...
        1);
valid = ...
    isfinite(dt) & ...
    dt > 0;
if ~any(valid)
    value = ...
        inf;
    return;
end
dX = ...
    dX(valid,:);
dt = ...
    dt(valid);
derivative = ...
    dX ./ ...
    dt;
validRows = ...
    all( ...
        isfinite(derivative), ...
        2);
derivative = ...
    derivative(validRows,:);
if isempty(derivative)
    value = ...
        inf;
    return;
end
normDerivative = ...
    sqrt( ...
        sum( ...
            derivative.^2, ...
            2));
value = ...
    rmsFinite( ...
        normDerivative);
end
function commonTime = pairCommonTime( ...
    t1, ...
    t2, ...
    tStart, ...
    tEnd, ...
    sampleRate_Hz)
actualStart = ...
    max( ...
        [ ...
        tStart, ...
        min(t1), ...
        min(t2)]);
actualEnd = ...
    min( ...
        [ ...
        tEnd, ...
        max(t1), ...
        max(t2)]);
if ~isfinite(actualStart) || ...
        ~isfinite(actualEnd) || ...
        actualEnd <= actualStart
    error( ...
        'QuadrotorFramework:ControllerPairWindow', ...
        'No common time interval exists for paired controller signals.');
end
numberOfSamples = ...
    max( ...
        2, ...
        round( ...
            (actualEnd-actualStart) * ...
            sampleRate_Hz) + ...
        1);
commonTime = ...
    linspace( ...
        actualStart, ...
        actualEnd, ...
        numberOfSamples).';
end
function value = pairedSignalRMS( ...
    t1, ...
    x1, ...
    t2, ...
    x2, ...
    tStart, ...
    tEnd, ...
    sampleRate_Hz)
commonTime = ...
    pairCommonTime( ...
        t1, ...
        t2, ...
        tStart, ...
        tEnd, ...
        sampleRate_Hz);
a = ...
    interp1( ...
        t1, ...
        x1, ...
        commonTime, ...
        'linear');
b = ...
    interp1( ...
        t2, ...
        x2, ...
        commonTime, ...
        'linear');
valid = ...
    isfinite(a) & ...
    isfinite(b);
value = ...
    rmsFinite( ...
        sqrt( ...
            a(valid).^2 + ...
            b(valid).^2));
end
function value = pairedDerivativeRMS( ...
    t1, ...
    x1, ...
    t2, ...
    x2, ...
    tStart, ...
    tEnd, ...
    sampleRate_Hz)
commonTime = ...
    pairCommonTime( ...
        t1, ...
        t2, ...
        tStart, ...
        tEnd, ...
        sampleRate_Hz);
a = ...
    interp1( ...
        t1, ...
        x1, ...
        commonTime, ...
        'linear');
b = ...
    interp1( ...
        t2, ...
        x2, ...
        commonTime, ...
        'linear');
valid = ...
    isfinite(a) & ...
    isfinite(b);
commonTime = ...
    commonTime(valid);
X = [ ...
    a(valid), ...
    b(valid)];
value = ...
    derivativeRMS( ...
        commonTime, ...
        X);
end
function value = pairedSaturationFraction( ...
    x1, ...
    t1, ...
    x2, ...
    t2, ...
    limit, ...
    tStart, ...
    tEnd, ...
    sampleRate_Hz)
commonTime = ...
    pairCommonTime( ...
        t1, ...
        t2, ...
        tStart, ...
        tEnd, ...
        sampleRate_Hz);
a = ...
    interp1( ...
        t1, ...
        x1, ...
        commonTime, ...
        'linear');
b = ...
    interp1( ...
        t2, ...
        x2, ...
        commonTime, ...
        'linear');
valid = ...
    isfinite(a) & ...
    isfinite(b);
if ~any(valid)
    value = ...
        inf;
    return;
end
value = ...
    mean( ...
        abs(a(valid)) >= ...
        0.995*limit | ...
        abs(b(valid)) >= ...
        0.995*limit);
end
function value = percentileFinite( ...
    x, ...
    percentile)
x = ...
    sort( ...
        x( ...
            isfinite(x)));
if isempty(x)
    value = ...
        inf;
    return;
end
if numel(x) == 1
    value = ...
        x(1);
    return;
end
position = ...
    1 + ...
    (percentile/100) * ...
    (numel(x)-1);
lowerIndex = ...
    floor(position);
upperIndex = ...
    ceil(position);
if lowerIndex == upperIndex
    value = ...
        x(lowerIndex);
else
    fraction = ...
        position - ...
        lowerIndex;
    value = ...
        x(lowerIndex) + ...
        fraction * ...
        ( ...
        x(upperIndex) - ...
        x(lowerIndex));
end
end
function wrapped = wrapToPiLocal(angle)
wrapped = ...
    mod( ...
        angle + pi, ...
        2*pi) - ...
    pi;
end
