function CONTROLLER_TUNING_RESULT = tune_controller_from_scratch()
totalTimer = ...
    tic;
fprintf('\n');
fprintf( ...
    '==============================================================\n');
fprintf( ...
    ' AUTOMATIC CASCADED CONTROLLER TUNING — C2 / L3 / SCHEMA 3.0\n');
fprintf( ...
    '==============================================================\n');
CFG = ...
    controller_tuning_config();
modelName = ...
    CFG.modelName;
if ~isfield(CFG,'schemaVersion') || ...
        double(CFG.schemaVersion) < 3.0
    error( ...
        'QuadrotorFramework:ControllerTuningOldConfigurationSchema', ...
        ['controller_tuning_config.m must use controller gain ', ...
         'schema 3.0 or newer.']);
end
if ~isfield(CFG,'totalTunableGains') || ...
        CFG.totalTunableGains ~= 6
    error( ...
        'QuadrotorFramework:ControllerTuningGainCount', ...
        ['The final local C2/L3 campaign requires exactly ', ...
         '6 unique tunable gains.']);
end
if ~isfield(CFG,'numberOfStages') || ...
        CFG.numberOfStages ~= 3
    error( ...
        'QuadrotorFramework:ControllerTuningStageCount', ...
        'The final local C2/L3 campaign requires exactly 3 stages.');
end
if ~isfield(CFG,'totalStageParameters') || ...
        CFG.totalStageParameters ~= 9
    error( ...
        'QuadrotorFramework:ControllerTuningStageParameterCount', ...
        ['The final local C2/L3 campaign requires exactly ', ...
         '9 stage parameter entries across 6 unique gains.']);
end
if ~isfield(CFG,'policy') || ...
        ~isstruct(CFG.policy) || ...
        ~isfield(CFG.policy,'allowSequentialRetuning') || ...
        ~logical(CFG.policy.allowSequentialRetuning)
    error( ...
        'QuadrotorFramework:ControllerTuningSequentialRetuningDisabled', ...
        ['The final local C2/L3 campaign requires ', ...
         'CFG.policy.allowSequentialRetuning = true.']);
end
if ~isfield(CFG,'experiment') || ~isstruct(CFG.experiment)
    error('QuadrotorFramework:ControllerTuningExperimentConfig','CFG.experiment is required.');
end
if ~isfield(CFG.experiment,'controllerSet') || ~strcmpi(string(CFG.experiment.controllerSet),"C2")
    error('QuadrotorFramework:ControllerTuningControllerSet','This tuning campaign must target controller set C2.');
end
if ~isfield(CFG.experiment,'plantModels') || ~isequal(double(CFG.experiment.plantModels(:).'),3)
    error('QuadrotorFramework:ControllerTuningPlantModels','C2 tuning must evaluate L3 only.');
end
if ~isfield(CFG.experiment,'trajectoryID') || double(CFG.experiment.trajectoryID) ~= 2
    error('QuadrotorFramework:ControllerTuningTrajectory','C2 tuning must use trajectory 2.');
end
if ~isfield(CFG.experiment,'feedbackSource') || ~strcmpi(string(CFG.experiment.feedbackSource),"EST")
    error('QuadrotorFramework:ControllerTuningFeedback','C2 tuning must use EST controller feedback.');
end
if ~isfield(CFG.experiment,'metricStateSource') || ~strcmpi(string(CFG.experiment.metricStateSource),"TRUE")
    error('QuadrotorFramework:ControllerTuningMetricState','Controller performance metrics must use TRUE state.');
end
if CFG.optimizer.useParallel
    fprintf('\n');
    fprintf( ...
        ['NOTE: CFG.optimizer.useParallel was true. ', ...
         'It is being overridden to false for this campaign.\n']);
end
CFG.optimizer.useParallel = ...
    false;
CFG.runtime = ...
    struct();
CFG.runtime.executionMode = ...
    "SERIAL_SAFE";
CFG.runtime.parallelDisabled = ...
    true;
CFG.runtime.parallelDisabledReason = ...
    "PARSIM initialization instability";
CFG.runtime.resumeAllowed = ...
    false;
CFG.runtime.controllerGainSchema = ...
    "3.0";
if ~evalin( ...
        'base', ...
        'exist(''AUTOPILOT'',''var'')')
    error( ...
        'QuadrotorFramework:ControllerTuningMissingAutopilot', ...
        ['AUTOPILOT does not exist in the base workspace. ', ...
         'Run initialize_project before tune_controller_from_scratch.']);
end
AUTOPILOT_INITIAL = ...
    evalin( ...
        'base', ...
        'AUTOPILOT');
if ~isstruct(AUTOPILOT_INITIAL)
    error( ...
        'QuadrotorFramework:ControllerTuningInvalidAutopilot', ...
        'Base-workspace AUTOPILOT must be a structure.');
end
if ~isfield(AUTOPILOT_INITIAL,'info') || ~isstruct(AUTOPILOT_INITIAL.info) || ~isfield(AUTOPILOT_INITIAL.info,'activeController')
    error('QuadrotorFramework:ControllerTuningMissingActiveController','AUTOPILOT.info.activeController is required.');
end
if ~strcmpi(string(AUTOPILOT_INITIAL.info.activeController),"C2")
    error('QuadrotorFramework:ControllerTuningWrongActiveController','Initialize the project with L3 so that controller set C2 is active before tuning.');
end
if isfield(AUTOPILOT_INITIAL,'info') && ...
        isstruct(AUTOPILOT_INITIAL.info) && ...
        isfield( ...
            AUTOPILOT_INITIAL.info, ...
            'controllerGainSchema')
    autopilotSchema = ...
        string( ...
            AUTOPILOT_INITIAL.info.controllerGainSchema);
    if autopilotSchema ~= "3.0"
        error( ...
            'QuadrotorFramework:ControllerTuningAutopilotSchema', ...
            ['AUTOPILOT reports controller gain schema "%s". ', ...
             'Schema 3.0 is required.'], ...
            autopilotSchema);
    end
end
estimatorOverrideExists = ...
    evalin( ...
        'base', ...
        'exist(''ESTIMATOR_TUNING_OVERRIDE'',''var'')');
if estimatorOverrideExists
    estimatorOverride = ...
        evalin( ...
            'base', ...
            'ESTIMATOR_TUNING_OVERRIDE');
    if ~isempty(estimatorOverride)
        error( ...
            'QuadrotorFramework:ControllerTuningEstimatorOverride', ...
            ['ESTIMATOR_TUNING_OVERRIDE is currently active. ', ...
             'Clear it and run initialize_project before controller ', ...
             'tuning.']);
    end
end
if ~bdIsLoaded(modelName)
    load_system( ...
        modelName);
end
simulationStatus = ...
    get_param( ...
        modelName, ...
        'SimulationStatus');
if ~strcmpi( ...
        simulationStatus, ...
        'stopped')
    error( ...
        'QuadrotorFramework:ControllerTuningModelRunning', ...
        'Model "%s" must be stopped before tuning.', ...
        modelName);
end
modelDirty = ...
    get_param( ...
        modelName, ...
        'Dirty');
if strcmpi( ...
        modelDirty, ...
        'on')
    error( ...
        'QuadrotorFramework:ControllerTuningDirtyModel', ...
        ['Model "%s" contains unsaved changes. ', ...
         'Save the model before starting controller tuning.'], ...
        modelName);
end
INITIAL_GAIN_TABLE = ...
    controller_tuning_gain_table( ...
        AUTOPILOT_INITIAL);
if height(INITIAL_GAIN_TABLE) ~= 16
    error( ...
        'QuadrotorFramework:ControllerTuningInitialGainCount', ...
        ['controller_tuning_gain_table returned %d active C2 gains. ', ...
         'Exactly 16 are required by controller gain schema 3.0.'], ...
        height(INITIAL_GAIN_TABLE));
end
if isfield(CFG,'baseline') && isstruct(CFG.baseline) && isfield(CFG.baseline,'expectedC2')
    expectedBaseline = CFG.baseline.expectedC2;
    localCheckExpectedGain(INITIAL_GAIN_TABLE,"angularRate.roll.Kp",expectedBaseline.rollRateKp);
    localCheckExpectedGain(INITIAL_GAIN_TABLE,"angularRate.roll.Ki",expectedBaseline.rollRateKi);
    localCheckExpectedGain(INITIAL_GAIN_TABLE,"attitude.roll.Kp",expectedBaseline.rollAttitudeKp);
    localCheckExpectedGain(INITIAL_GAIN_TABLE,"angularRate.pitch.Kp",expectedBaseline.pitchRateKp);
    localCheckExpectedGain(INITIAL_GAIN_TABLE,"angularRate.pitch.Ki",expectedBaseline.pitchRateKi);
    localCheckExpectedGain(INITIAL_GAIN_TABLE,"attitude.pitch.Kp",expectedBaseline.pitchAttitudeKp);
end
configuredPaths = ...
    strings( ...
        0, ...
        1);
expectedStageObjectives = [ ...
    "rate_pitch"; ...
    "attitude_pitch"; ...
    "joint_roll_pitch"];
expectedStagePaths = { ...
    ["angularRate.pitch.Kp";"angularRate.pitch.Ki"]; ...
    "attitude.pitch.Kp"; ...
    ["angularRate.roll.Kp";"angularRate.roll.Ki";"attitude.roll.Kp";"angularRate.pitch.Kp";"angularRate.pitch.Ki";"attitude.pitch.Kp"]};
for stageIndex = 1:CFG.numberOfStages
    STAGE = ...
        CFG.stages(stageIndex);
    if lower(string(STAGE.objectiveType)) ~= expectedStageObjectives(stageIndex)
        error( ...
            'QuadrotorFramework:ControllerTuningStageObjectiveContract', ...
            'Stage %d has an invalid objectiveType for the final local C2/L3 campaign.', ...
            stageIndex);
    end
    stagePaths = ...
        string( ...
            STAGE.parameterPaths(:));
    expectedPaths = ...
        string( ...
            expectedStagePaths{stageIndex}(:));
    if numel(stagePaths) ~= numel(expectedPaths) || ...
            ~all(stagePaths == expectedPaths)
        error( ...
            'QuadrotorFramework:ControllerTuningStagePathContract', ...
            'Stage %d gain paths do not match the final local C2/L3 campaign.', ...
            stageIndex);
    end
    controller_tuning_gain_table( ...
        AUTOPILOT_INITIAL, ...
        STAGE.parameterPaths);
    configuredPaths = [ ...
        configuredPaths; ...
        string( ...
            STAGE.parameterPaths(:))];
end
if numel(configuredPaths) ~= CFG.totalStageParameters
    error( ...
        'QuadrotorFramework:ControllerTuningConfiguredStageParameterCount', ...
        ['The configured tuning stages contain %d parameter entries, ', ...
         'but CFG.totalStageParameters is %d.'], ...
        numel(configuredPaths), ...
        CFG.totalStageParameters);
end
uniqueConfiguredPaths = ...
    unique( ...
        configuredPaths, ...
        'stable');
if numel(uniqueConfiguredPaths) ~= CFG.totalTunableGains
    error( ...
        'QuadrotorFramework:ControllerTuningUniqueGainCount', ...
        ['The configured tuning stages contain %d unique gains, ', ...
         'but CFG.totalTunableGains is %d.'], ...
        numel(uniqueConfiguredPaths), ...
        CFG.totalTunableGains);
end
expectedUniquePaths = [ ...
    "angularRate.roll.Kp"; ...
    "angularRate.roll.Ki"; ...
    "attitude.roll.Kp"; ...
    "angularRate.pitch.Kp"; ...
    "angularRate.pitch.Ki"; ...
    "attitude.pitch.Kp"];
if ~all(ismember(expectedUniquePaths,uniqueConfiguredPaths)) || ...
        ~all(ismember(uniqueConfiguredPaths,expectedUniquePaths))
    error( ...
        'QuadrotorFramework:ControllerTuningGainContractMismatch', ...
        ['The final local C2/L3 campaign must tune exactly the ', ...
         'three roll and three pitch gains defined by the campaign.']);
end
pathCounts = ...
    zeros( ...
        numel(expectedUniquePaths), ...
        1);
for pathIndex = 1:numel(expectedUniquePaths)
    pathCounts(pathIndex) = ...
        nnz( ...
            configuredPaths == ...
            expectedUniquePaths(pathIndex));
end
expectedPathCounts = [1;1;1;2;2;2];
if ~isequal(pathCounts,expectedPathCounts)
    error( ...
        'QuadrotorFramework:ControllerTuningSequentialRetuningContract', ...
        ['The final local campaign requires roll gains once and ', ...
         'pitch gains twice across the three sequential stages.']);
end
authoritativePaths = ...
    string( ...
        INITIAL_GAIN_TABLE.ParameterPath);
if ~all(ismember(uniqueConfiguredPaths,authoritativePaths))
    error( ...
        'QuadrotorFramework:ControllerTuningGainContractMismatch', ...
        ['At least one configured C2 tuning gain is not present in ', ...
         'controller_tuning_gain_table.']);
end
fprintf('\n');
fprintf('Verified active controller gains:\n\n');
disp( ...
    INITIAL_GAIN_TABLE(:, ...
    {'Stage','Label','EffectiveValue'}));
tuningFlagPreviouslyExisted = ...
    evalin( ...
        'base', ...
        'exist(''CONTROLLER_TUNING_ACTIVE'',''var'')');
if tuningFlagPreviouslyExisted
    previousTuningFlagValue = ...
        evalin( ...
            'base', ...
            'CONTROLLER_TUNING_ACTIVE');
else
    previousTuningFlagValue = ...
        [];
end
assignin( ...
    'base', ...
    'CONTROLLER_TUNING_ACTIVE', ...
    true);
tuningFlagCleanup = ...
    onCleanup( ...
        @() localRestoreControllerTuningFlag( ...
            tuningFlagPreviouslyExisted, ...
            previousTuningFlagValue));
fprintf('\n');
fprintf( ...
    'Base CONTROLLER_TUNING_ACTIVE: TRUE\n');
controllerTuningFolder = ...
    fileparts( ...
        mfilename( ...
            'fullpath'));
projectRoot = ...
    fileparts( ...
        fileparts( ...
            controllerTuningFolder));
configuredRootFolder = ...
    char( ...
        string( ...
            CFG.output.rootFolder));
[~,resultsFolderName,resultsFolderExtension] = ...
    fileparts( ...
        configuredRootFolder);
resultsFolderName = ...
    [ ...
    resultsFolderName, ...
    resultsFolderExtension];
if isempty(resultsFolderName)
    resultsFolderName = ...
        'Results_C2';
end
rootFolder = ...
    fullfile( ...
        controllerTuningFolder, ...
        resultsFolderName);
if ~exist(rootFolder,'dir')
    [mkdirStatus,mkdirMessage] = ...
        mkdir( ...
            rootFolder);
    if ~mkdirStatus
        error( ...
            'QuadrotorFramework:ControllerTuningResultsFolder', ...
            'Unable to create controller tuning results folder "%s". %s', ...
            rootFolder, ...
            mkdirMessage);
    end
end
timestamp = ...
    char( ...
        datetime( ...
            'now', ...
            'Format', ...
            'yyyy-MM-dd_HH-mm-ss'));
runFolder = ...
    fullfile( ...
        rootFolder, ...
        [ ...
        'Controller_Tuning_C2_', ...
        timestamp]);
if exist(runFolder,'dir')
    error( ...
        'QuadrotorFramework:ControllerTuningRunFolderExists', ...
        'Controller tuning run folder already exists.');
end
mkdir( ...
    runFolder);
fprintf('\n');
fprintf( ...
    'NEW campaign. Resume is disabled.\n');
fprintf( ...
    'Results folder:\n%s\n\n', ...
    runFolder);
resultFile = ...
    fullfile( ...
        runFolder, ...
        CFG.output.resultFile);
stageResultsFile = ...
    fullfile( ...
        runFolder, ...
        CFG.output.stageResultsFile);
gainTableFile = ...
    fullfile( ...
        runFolder, ...
        CFG.output.gainTableFile);
validationFile = ...
    fullfile( ...
        runFolder, ...
        CFG.output.validationFile);
configurationFile = ...
    fullfile( ...
        runFolder, ...
        'Controller_Tuning_Config.mat');
partialResultFile = ...
    fullfile( ...
        runFolder, ...
        'Controller_Tuning_Partial.mat');
save( ...
    configurationFile, ...
    'CFG', ...
    '-v7.3');
snapshotFolder = ...
    fullfile( ...
        runFolder, ...
        'Code_Snapshot');
if ~exist(snapshotFolder,'dir')
    mkdir( ...
        snapshotFolder);
end
snapshotFiles = { ...
    'UAV_autopilot.m'; ...
    'controller_tuning_config.m'; ...
    'controller_tuning_gain_table.m'; ...
    'evaluate_controller_candidate.m'; ...
    'evaluate_controller_candidates_parallel.m'; ...
    'tune_controller_stage.m'; ...
    'tune_controller_from_scratch.m'; ...
    'tune_controller.m'; ...
    'apply_controller_tuning_result.m'};
for fileIndex = 1:numel(snapshotFiles)
    sourceFile = ...
        which( ...
            snapshotFiles{fileIndex});
    if isempty(sourceFile)
        warning( ...
            'QuadrotorFramework:ControllerTuningSnapshotMissing', ...
            'Snapshot source file not found: %s', ...
            snapshotFiles{fileIndex});
        continue;
    end
    try
        copyfile( ...
            sourceFile, ...
            fullfile( ...
                snapshotFolder, ...
                snapshotFiles{fileIndex}));
    catch ME
        warning( ...
            'QuadrotorFramework:ControllerTuningSnapshot', ...
            'Unable to snapshot %s: %s', ...
            snapshotFiles{fileIndex}, ...
            ME.message);
    end
end
METADATA = ...
    struct();
METADATA.StartTimestamp = ...
    timestamp;
METADATA.MATLABVersion = ...
    version;
METADATA.ModelName = ...
    modelName;
METADATA.ControllerGainSchema = ...
    "3.0";
METADATA.CampaignProfile = ...
    CFG.campaignProfile;
METADATA.ExecutionMode = ...
    CFG.runtime.executionMode;
METADATA.ControllerSet = ...
    string(CFG.experiment.controllerSet);
METADATA.PlantModels = ...
    double(CFG.experiment.plantModels(:).');
METADATA.PlantWeights = ...
    double(CFG.experiment.plantWeights(:).');
METADATA.TrajectoryID = ...
    double(CFG.experiment.trajectoryID);
METADATA.FeedbackSource = ...
    string(CFG.experiment.feedbackSource);
METADATA.MetricStateSource = ...
    string(CFG.experiment.metricStateSource);
METADATA.DisturbancesEnabled = ...
    CFG.experiment.disturbancesEnabled;
METADATA.OperatorMode = ...
    CFG.experiment.operatorMode;
METADATA.TotalTunableGains = ...
    CFG.totalTunableGains;
METADATA.TotalRequestedEvaluations = ...
    CFG.totalRequestedFunctionEvaluations;
METADATA.NumberOfStages = ...
    CFG.numberOfStages;
METADATA.RunFolder = ...
    runFolder;
METADATA.ProjectRoot = ...
    projectRoot;
METADATA.Resumed = ...
    false;
METADATA.ResumeAllowed = ...
    false;
STAGE_RESULTS = ...
    repmat( ...
        localEmptyStageSummary(), ...
        CFG.numberOfStages, ...
        1);
STAGE_RESULTS_FULL = ...
    cell( ...
        CFG.numberOfStages, ...
        1);
FROZEN_AUTOPILOT = ...
    AUTOPILOT_INITIAL;
completedStages = ...
    0;
controller_tuning_gain_table( ...
    FROZEN_AUTOPILOT);
fprintf('\n');
fprintf( ...
    '==============================================================\n');
fprintf( ...
    ' STARTING NEW INSIDE-OUT CONTROLLER TUNING CAMPAIGN\n');
fprintf( ...
    '==============================================================\n');
fprintf( ...
    'Controller schema:         3.0\n');
fprintf( ...
    'Controller set:            %s\n', ...
    string(CFG.experiment.controllerSet));
plantModelText = ...
    strjoin( ...
        compose( ...
            "L%d", ...
            double(CFG.experiment.plantModels(:).')), ...
        " + ");
fprintf( ...
    'Plant models:              %s\n', ...
    char(plantModelText));
fprintf( ...
    'Trajectory ID:             %d\n', ...
    CFG.experiment.trajectoryID);
fprintf( ...
    'Controller feedback:       %s\n', ...
    string(CFG.experiment.feedbackSource));
fprintf( ...
    'Metric state source:       %s\n', ...
    string(CFG.experiment.metricStateSource));
fprintf( ...
    'Execution:                 SERIAL SAFE\n');
fprintf( ...
    'Active tunable gains:      %d\n', ...
    CFG.totalTunableGains);
fprintf( ...
    'Requested candidate evals: %d\n', ...
    CFG.totalRequestedFunctionEvaluations);
fprintf( ...
    'Stage validation:          1-SEED MISSION GATE + FINAL 3-SEED STRICT\n');
fprintf( ...
    'Max global degradation:    %.1f %%\n', ...
    100 * CFG.policy.maximumMissionCostDegradationFraction);
fprintf( ...
    'Max worst-plant degrade:   %.1f %%\n', ...
    100 * CFG.policy.maximumWorstPlantCostDegradationFraction);
fprintf( ...
    'Resume:                    DISABLED\n');
fprintf( ...
    'Starting stage:            1 — %s\n', ...
    CFG.stages(1).name);
fprintf( ...
    '==============================================================\n\n');
for stageIndex = 1:CFG.numberOfStages
    STAGE = ...
        CFG.stages(stageIndex);
    fprintf('\n');
    fprintf( ...
        '##############################################################\n');
    fprintf( ...
        ' STAGE %d/%d — %s\n', ...
        stageIndex, ...
        CFG.numberOfStages, ...
        STAGE.name);
    fprintf( ...
        '##############################################################\n');
    try
        PRE_STAGE_AUTOPILOT = ...
            FROZEN_AUTOPILOT;
        [ ...
            currentStageResult, ...
            stageAutopilotOut] = ...
            tune_controller_stage( ...
                CFG, ...
                STAGE, ...
                PRE_STAGE_AUTOPILOT, ...
                runFolder);
        [stageSafetyContractPass,stageSafetyMode] = ...
            localStageAcceptanceContract( ...
                currentStageResult, ...
                stageIndex);
        if currentStageResult.accepted
            if ~stageSafetyContractPass
                error( ...
                    'QuadrotorFramework:ControllerStageAcceptedWithoutSafetyPass', ...
                    ['Stage %d was marked accepted but its mission-safety ', ...
                     'contract is internally inconsistent.'], ...
                    stageIndex);
            end
            FROZEN_AUTOPILOT = ...
                stageAutopilotOut;
            fprintf( ...
                'Stage acceptance mode:      %s\n', ...
                char(stageSafetyMode));
        else
            FROZEN_AUTOPILOT = ...
                PRE_STAGE_AUTOPILOT;
        end
        controller_tuning_gain_table( ...
            FROZEN_AUTOPILOT);
        STAGE_RESULTS(stageIndex) = ...
            localStageSummaryFromResult( ...
                currentStageResult);
        STAGE_RESULTS_FULL{stageIndex} = ...
            currentStageResult;
        completedStages = ...
            stageIndex;
        save( ...
            stageResultsFile, ...
            'STAGE_RESULTS', ...
            'STAGE_RESULTS_FULL', ...
            'completedStages', ...
            '-v7.3');
        PARTIAL_RESULT = ...
            localBuildPartialResult( ...
                completedStages, ...
                FROZEN_AUTOPILOT, ...
                STAGE_RESULTS, ...
                STAGE_RESULTS_FULL, ...
                runFolder);
        save( ...
            partialResultFile, ...
            'PARTIAL_RESULT', ...
            '-v7.3');
        fprintf('\n');
        if currentStageResult.accepted
            fprintf( ...
                ['Stage %d accepted, mission-safety validated, ', ...
                 'and FROZEN.\n'], ...
                stageIndex);
        else
            fprintf( ...
                ['Stage %d rejected. Last globally valid controller ', ...
                 'was restored and kept.\n'], ...
                stageIndex);
        end
    catch ME
        fprintf('\n');
        fprintf( ...
            '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n');
        fprintf( ...
            ' CONTROLLER TUNING STOPPED\n');
        fprintf( ...
            '!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n');
        fprintf( ...
            'Failed stage: %d — %s\n', ...
            stageIndex, ...
            STAGE.name);
        fprintf( ...
            'Identifier:   %s\n', ...
            ME.identifier);
        fprintf( ...
            'Message:      %s\n', ...
            ME.message);
        FAILURE = ...
            struct();
        FAILURE.schemaVersion = ...
            3.0;
        FAILURE.ControllerGainSchema = ...
            "3.0";
        FAILURE.Timestamp = ...
            char( ...
                datetime( ...
                    'now', ...
                    'Format', ...
                    'yyyy-MM-dd_HH-mm-ss'));
        FAILURE.StageIndex = ...
            stageIndex;
        FAILURE.Stage = ...
            STAGE;
        FAILURE.CompletedStages = ...
            completedStages;
        FAILURE.LastFrozenAutopilot = ...
            FROZEN_AUTOPILOT;
        FAILURE.Identifier = ...
            ME.identifier;
        FAILURE.Message = ...
            ME.message;
        FAILURE.Stack = ...
            ME.stack;
        FAILURE.RunFolder = ...
            runFolder;
        FAILURE.ResumeAllowed = ...
            false;
        save( ...
            fullfile( ...
                runFolder, ...
                'Controller_Tuning_FAILURE.mat'), ...
            'FAILURE', ...
            '-v7.3');
        save( ...
            stageResultsFile, ...
            'STAGE_RESULTS', ...
            'STAGE_RESULTS_FULL', ...
            'completedStages', ...
            '-v7.3');
        PARTIAL_RESULT = ...
            localBuildPartialResult( ...
                completedStages, ...
                FROZEN_AUTOPILOT, ...
                STAGE_RESULTS, ...
                STAGE_RESULTS_FULL, ...
                runFolder);
        save( ...
            partialResultFile, ...
            'PARTIAL_RESULT', ...
            '-v7.3');
        fprintf('\n');
        fprintf( ...
            ['A progress snapshot was saved for diagnostics only.\n', ...
             'The next tune_controller_from_scratch invocation will start a NEW ', ...
             'campaign from Stage 1.\n\n']);
        rethrow(ME);
    end
end
FINAL_GAIN_TABLE_RAW = ...
    controller_tuning_gain_table( ...
        FROZEN_AUTOPILOT);
if height(FINAL_GAIN_TABLE_RAW) ~= ...
        height(INITIAL_GAIN_TABLE)
    error( ...
        'QuadrotorFramework:ControllerTuningFinalGainCount', ...
        'Final controller gain table must preserve the complete controller gain contract.');
end
if ~all(ismember(uniqueConfiguredPaths,string(FINAL_GAIN_TABLE_RAW.ParameterPath)))
    error( ...
        'QuadrotorFramework:ControllerTuningFinalConfiguredGains', ...
        'The final controller no longer contains every configured C2 tuning gain.');
end
if ~all( ...
        INITIAL_GAIN_TABLE.ParameterPath == ...
        FINAL_GAIN_TABLE_RAW.ParameterPath)
    error( ...
        'QuadrotorFramework:ControllerTuningFinalGainOrder', ...
        'Initial and final controller gain contracts do not match.');
end
ParameterPath = ...
    INITIAL_GAIN_TABLE.ParameterPath;
Label = ...
    INITIAL_GAIN_TABLE.Label;
Stage = ...
    INITIAL_GAIN_TABLE.Stage;
InitialValue = ...
    INITIAL_GAIN_TABLE.EffectiveValue;
TunedValue = ...
    FINAL_GAIN_TABLE_RAW.EffectiveValue;
Multiplier = ...
    TunedValue ./ ...
    InitialValue;
Log10Multiplier = ...
    log10( ...
        Multiplier);
Changed = ...
    abs( ...
        TunedValue - ...
        InitialValue) > ...
    max( ...
        1e-14, ...
        eps( ...
            max( ...
                abs(InitialValue), ...
                1)));
FINAL_GAIN_TABLE = ...
    table( ...
        ParameterPath, ...
        Label, ...
        Stage, ...
        InitialValue, ...
        TunedValue, ...
        Multiplier, ...
        Log10Multiplier, ...
        Changed);
targetGainMask = ...
    ismember( ...
        ParameterPath, ...
        uniqueConfiguredPaths);
if any(Changed(~targetGainMask))
    changedNonTarget = ...
        ParameterPath( ...
            Changed & ~targetGainMask);
    error( ...
        'QuadrotorFramework:ControllerTuningNonTargetGainChanged', ...
        'A gain outside the six-gain C2/L3 tuning set changed: %s', ...
        strjoin( ...
            cellstr(changedNonTarget), ...
            ', '));
end
writetable( ...
    FINAL_GAIN_TABLE, ...
    gainTableFile);
StageID = ...
    zeros( ...
        CFG.numberOfStages, ...
        1);
StageName = ...
    strings( ...
        CFG.numberOfStages, ...
        1);
Accepted = ...
    false( ...
        CFG.numberOfStages, ...
        1);
BaselineCost = ...
    NaN( ...
        CFG.numberOfStages, ...
        1);
BestSerialCost = ...
    NaN( ...
        CFG.numberOfStages, ...
        1);
OptimizationImprovement_percent = ...
    NaN( ...
        CFG.numberOfStages, ...
        1);
StageValidationPerformed = ...
    false( ...
        CFG.numberOfStages, ...
        1);
MissionValidationPerformed = ...
    false( ...
        CFG.numberOfStages, ...
        1);
MissionValidationCost = ...
    NaN( ...
        CFG.numberOfStages, ...
        1);
MissionSafetyPass = ...
    false( ...
        CFG.numberOfStages, ...
        1);
MissionCostPass = ...
    false( ...
        CFG.numberOfStages, ...
        1);
WorstPlantPass = ...
    false( ...
        CFG.numberOfStages, ...
        1);
OptimizationTime_min = ...
    NaN( ...
        CFG.numberOfStages, ...
        1);
Decision = ...
    strings( ...
        CFG.numberOfStages, ...
        1);
for stageIndex = 1:CFG.numberOfStages
    R = ...
        STAGE_RESULTS(stageIndex);
    StageID(stageIndex) = ...
        R.stageID;
    StageName(stageIndex) = ...
        R.stageName;
    Accepted(stageIndex) = ...
        R.accepted;
    BaselineCost(stageIndex) = ...
        R.baselineCost;
    BestSerialCost(stageIndex) = ...
        R.bestSerialCost;
    OptimizationImprovement_percent(stageIndex) = ...
        100 * ...
        R.optimizationImprovementFraction;
    StageValidationPerformed(stageIndex) = ...
        R.stageValidationPerformed;
    MissionValidationPerformed(stageIndex) = ...
        R.missionValidationPerformed;
    MissionValidationCost(stageIndex) = ...
        R.missionValidationCost;
    MissionSafetyPass(stageIndex) = ...
        R.missionSafetyPass;
    MissionCostPass(stageIndex) = ...
        R.missionCostPass;
    WorstPlantPass(stageIndex) = ...
        R.worstPlantPass;
    OptimizationTime_min(stageIndex) = ...
        R.optimizationTime_s / ...
        60;
    Decision(stageIndex) = ...
        R.decision;
end
STAGE_SUMMARY_TABLE = ...
    table( ...
        StageID, ...
        StageName, ...
        Accepted, ...
        BaselineCost, ...
        BestSerialCost, ...
        OptimizationImprovement_percent, ...
        StageValidationPerformed, ...
        MissionValidationPerformed, ...
        MissionValidationCost, ...
        MissionSafetyPass, ...
        MissionCostPass, ...
        WorstPlantPass, ...
        OptimizationTime_min, ...
        Decision);
writetable( ...
    STAGE_SUMMARY_TABLE, ...
    fullfile( ...
        runFolder, ...
        'Controller_Tuning_Stage_Summary.csv'));
fprintf('\n');
fprintf( ...
    '==============================================================\n');
fprintf( ...
    ' FINAL MISSION-LEVEL CONTROLLER VALIDATION\n');
fprintf( ...
    '==============================================================\n');
VALIDATION_STAGE = ...
    localMissionValidationStage( ...
        CFG);
validationSeeds = ...
    localValidatedSeedOffsets( ...
        CFG.validation.finalSeedOffsets, ...
        'final validation');
zValidation = ...
    zeros( ...
        VALIDATION_STAGE.numberOfParameters, ...
        1);
fprintf( ...
    'Validation objective:      %s\n', ...
    VALIDATION_STAGE.name);
fprintf( ...
    'Validation seeds:          %s\n', ...
    mat2str( ...
        validationSeeds.'));
fprintf( ...
    'Execution mode:            SERIAL\n');
fprintf( ...
    'Validation policy:         STRICT CANDIDATE / SOFT-BASELINE AWARE\n');
fprintf('\n');
fprintf( ...
    'Running INITIAL C2 baseline on final validation seeds...\n');
[~,FINAL_BASELINE_VALIDATION] = ...
    evaluate_controller_candidate( ...
        zValidation, ...
        CFG, ...
        VALIDATION_STAGE, ...
        AUTOPILOT_INITIAL, ...
        [], ...
        'serial', ...
        validationSeeds, ...
        'baseline');
finalBaselineUsableMask = ...
    localUsableRunMask( ...
        FINAL_BASELINE_VALIDATION, ...
        numel(validationSeeds));
finalBaselineStrictMask = ...
    localStrictRunMask( ...
        FINAL_BASELINE_VALIDATION, ...
        numel(validationSeeds));
finalBaselineUsable = ...
    all(finalBaselineUsableMask);
finalBaselineAnyUsable = ...
    any(finalBaselineUsableMask);
finalBaselineStrictPass = ...
    all(finalBaselineStrictMask);
finalBaselineStrictSeeds = ...
    validationSeeds(finalBaselineStrictMask);
finalBaselineFailedSeeds = ...
    validationSeeds(~finalBaselineStrictMask);
fprintf( ...
    'Initial baseline usable:   %d/%d seeds\n', ...
    nnz(finalBaselineUsableMask), ...
    numel(validationSeeds));
fprintf( ...
    'Initial baseline strict:   %d/%d seeds\n', ...
    nnz(finalBaselineStrictMask), ...
    numel(validationSeeds));
if ~finalBaselineUsable
    fprintf('\n');
    fprintf( ...
        'Initial-controller baseline has nonrecoverable validation failures.\n');
    displayValidationMessages( ...
        FINAL_BASELINE_VALIDATION);
end
fprintf('\n');
fprintf( ...
    'Running FINAL C2 controller in strict mode on all final validation seeds...\n');
[~,FINAL_TUNED_FEASIBILITY] = ...
    evaluate_controller_candidate( ...
        zValidation, ...
        CFG, ...
        VALIDATION_STAGE, ...
        FROZEN_AUTOPILOT, ...
        [], ...
        'serial', ...
        validationSeeds, ...
        'strict');
finalTunedStrictPass = ...
    FINAL_TUNED_FEASIBILITY.success && ...
    isfield(FINAL_TUNED_FEASIBILITY,'strictMissionSuccess') && ...
    logical(FINAL_TUNED_FEASIBILITY.strictMissionSuccess);
finalValidationCost = ...
    NaN;
finalValidationImprovementFraction = ...
    NaN;
finalComparisonAvailable = ...
    any(finalBaselineStrictMask);
FINAL_TUNED_VALIDATION = ...
    FINAL_TUNED_FEASIBILITY;
if finalTunedStrictPass && ...
        finalComparisonAvailable
    comparisonSeeds = ...
        validationSeeds(finalBaselineStrictMask);
    comparisonBaselineMetrics = ...
        FINAL_BASELINE_VALIDATION.metrics(finalBaselineStrictMask);
    if isempty(comparisonBaselineMetrics) || ...
            numel(comparisonBaselineMetrics) ~= numel(comparisonSeeds)
        error( ...
            'QuadrotorFramework:ControllerFinalComparisonBaselineMetrics', ...
            ['Strict baseline seeds were identified but the corresponding ', ...
             'baseline metrics are unavailable or inconsistent.']);
    end
    fprintf('\n');
    fprintf( ...
        'Comparing FINAL C2 against baseline on %d strict baseline seeds...\n', ...
        numel(comparisonSeeds));
    [finalValidationCost,FINAL_TUNED_COMPARISON] = ...
        evaluate_controller_candidate( ...
            zValidation, ...
            CFG, ...
            VALIDATION_STAGE, ...
            FROZEN_AUTOPILOT, ...
            comparisonBaselineMetrics, ...
            'serial', ...
            comparisonSeeds, ...
            'strict');
    if FINAL_TUNED_COMPARISON.success && ...
            isfinite(finalValidationCost) && ...
            finalValidationCost < CFG.cost.failurePenalty
        finalValidationImprovementFraction = ...
            1 - ...
            finalValidationCost;
    end
else
    FINAL_TUNED_COMPARISON = ...
        [];
end
finalMissionMaximumDegradationFraction = ...
    double( ...
        CFG.policy.maximumMissionCostDegradationFraction);
finalWorstPlantMaximumDegradationFraction = ...
    double( ...
        CFG.policy.maximumWorstPlantCostDegradationFraction);
if finalComparisonAvailable
    finalMissionCostPass = ...
        finalTunedStrictPass && ...
        ~isempty(FINAL_TUNED_COMPARISON) && ...
        FINAL_TUNED_COMPARISON.success && ...
        isfinite(finalValidationCost) && ...
        finalValidationCost < CFG.cost.failurePenalty && ...
        finalValidationCost <= ...
        1 + ...
        finalMissionMaximumDegradationFraction;
    finalWorstPlantPass = ...
        finalMissionCostPass && ...
        finalValidationCost <= ...
        1 + ...
        finalWorstPlantMaximumDegradationFraction;
    finalPlantMeanCosts = ...
        finalValidationCost;
else
    finalMissionCostPass = ...
        finalTunedStrictPass;
    finalWorstPlantPass = ...
        finalTunedStrictPass;
    finalPlantMeanCosts = ...
        NaN;
end
overallValidationPass = ...
    finalTunedStrictPass && ...
    finalMissionCostPass && ...
    finalWorstPlantPass;
if overallValidationPass
    if finalComparisonAvailable
        finalDecision = ...
            "PASS";
    else
        finalDecision = ...
            "PASS_FEASIBILITY_BOOTSTRAP";
    end
else
    finalDecision = ...
        "FAIL";
end
FINAL_VALIDATION = ...
    localBuildFinalValidation( ...
        overallValidationPass, ...
        FINAL_BASELINE_VALIDATION, ...
        FINAL_TUNED_VALIDATION, ...
        FINAL_TUNED_COMPARISON, ...
        finalValidationCost, ...
        finalValidationImprovementFraction, ...
        finalDecision, ...
        finalBaselineUsable, ...
        finalBaselineStrictPass, ...
        finalTunedStrictPass, ...
        finalComparisonAvailable, ...
        validationSeeds, ...
        finalBaselineStrictSeeds, ...
        finalBaselineFailedSeeds);
FINAL_VALIDATION.baselineAnyUsable = ...
    logical(finalBaselineAnyUsable);
FINAL_VALIDATION.baselineUsableSeedCount = ...
    nnz(finalBaselineUsableMask);
FINAL_VALIDATION.baselineStrictSeedCount = ...
    nnz(finalBaselineStrictMask);
FINAL_VALIDATION.validationMode = ...
    string(finalDecision);
FINAL_VALIDATION.missionCostPass = ...
    logical(finalMissionCostPass);
FINAL_VALIDATION.worstPlantPass = ...
    logical(finalWorstPlantPass);
fprintf('\n');
fprintf( ...
    'Final strict candidate:    %s\n', ...
    localPassFail( ...
        finalTunedStrictPass));
if finalComparisonAvailable
    fprintf( ...
        'Final normalized cost:    %.6f\n', ...
        finalValidationCost);
    fprintf( ...
        'Final improvement:        %+.2f %%\n', ...
        100 * ...
        finalValidationImprovementFraction);
else
    fprintf( ...
        'Final normalized cost:    N/A — feasibility bootstrap mode\n');
    fprintf( ...
        'Final improvement:        N/A — no strict baseline seed available\n');
end
fprintf( ...
    'Final mission-cost gate:  %s\n', ...
    localPassFail( ...
        finalMissionCostPass));
fprintf( ...
    'Final worst-plant gate:   %s\n', ...
    localPassFail( ...
        finalWorstPlantPass));
fprintf( ...
    'Final mission validation: %s\n', ...
    localPassFail( ...
        overallValidationPass));
save( ...
    validationFile, ...
    'FINAL_VALIDATION', ...
    'overallValidationPass', ...
    '-v7.3');
totalTime_s = ...
    toc( ...
        totalTimer);
CONTROLLER_TUNING_RESULT = ...
    struct();
CONTROLLER_TUNING_RESULT.schemaVersion = ...
    3.0;
CONTROLLER_TUNING_RESULT.ControllerGainSchema = ...
    "3.0";
CONTROLLER_TUNING_RESULT.Metadata = ...
    METADATA;
CONTROLLER_TUNING_RESULT.Config = ...
    CFG;
CONTROLLER_TUNING_RESULT.ControllerSet = ...
    string(CFG.experiment.controllerSet);
CONTROLLER_TUNING_RESULT.PlantModels = ...
    double(CFG.experiment.plantModels(:).');
CONTROLLER_TUNING_RESULT.TrajectoryID = ...
    double(CFG.experiment.trajectoryID);
CONTROLLER_TUNING_RESULT.FeedbackSource = ...
    string(CFG.experiment.feedbackSource);
CONTROLLER_TUNING_RESULT.MetricStateSource = ...
    string(CFG.experiment.metricStateSource);
CONTROLLER_TUNING_RESULT.InitialAutopilot = ...
    AUTOPILOT_INITIAL;
CONTROLLER_TUNING_RESULT.FinalAutopilot = ...
    FROZEN_AUTOPILOT;
CONTROLLER_TUNING_RESULT.InitialGainTable = ...
    INITIAL_GAIN_TABLE;
CONTROLLER_TUNING_RESULT.FinalGainTable = ...
    FINAL_GAIN_TABLE;
CONTROLLER_TUNING_RESULT.StageResults = ...
    STAGE_RESULTS;
CONTROLLER_TUNING_RESULT.StageResultsFull = ...
    STAGE_RESULTS_FULL;
CONTROLLER_TUNING_RESULT.StageSummaryTable = ...
    STAGE_SUMMARY_TABLE;
CONTROLLER_TUNING_RESULT.FinalValidation = ...
    FINAL_VALIDATION;
CONTROLLER_TUNING_RESULT.FinalValidationPassed = ...
    overallValidationPass;
CONTROLLER_TUNING_RESULT.FinalBaselineUsable = ...
    finalBaselineUsable;
CONTROLLER_TUNING_RESULT.FinalBaselineAnyUsable = ...
    finalBaselineAnyUsable;
CONTROLLER_TUNING_RESULT.FinalBaselineStrictPassed = ...
    finalBaselineStrictPass;
CONTROLLER_TUNING_RESULT.FinalCandidateStrictPassed = ...
    finalTunedStrictPass;
CONTROLLER_TUNING_RESULT.FinalComparisonAvailable = ...
    finalComparisonAvailable;
CONTROLLER_TUNING_RESULT.FinalValidationMode = ...
    string(finalDecision);
CONTROLLER_TUNING_RESULT.FinalValidationSeeds = ...
    validationSeeds;
CONTROLLER_TUNING_RESULT.FinalMissionCostPass = ...
    finalMissionCostPass;
CONTROLLER_TUNING_RESULT.FinalWorstPlantPass = ...
    finalWorstPlantPass;
CONTROLLER_TUNING_RESULT.FinalPlantMeanCosts = ...
    finalPlantMeanCosts;
CONTROLLER_TUNING_RESULT.FinalMissionMaximumDegradationFraction = ...
    finalMissionMaximumDegradationFraction;
CONTROLLER_TUNING_RESULT.FinalWorstPlantMaximumDegradationFraction = ...
    finalWorstPlantMaximumDegradationFraction;
CONTROLLER_TUNING_RESULT.CompletedStages = ...
    completedStages;
CONTROLLER_TUNING_RESULT.TotalTime_s = ...
    totalTime_s;
CONTROLLER_TUNING_RESULT.RunFolder = ...
    runFolder;
CONTROLLER_TUNING_RESULT.ResultFile = ...
    resultFile;
CONTROLLER_TUNING_RESULT.GainTableFile = ...
    gainTableFile;
CONTROLLER_TUNING_RESULT.ValidationFile = ...
    validationFile;
save( ...
    resultFile, ...
    'CONTROLLER_TUNING_RESULT', ...
    '-v7.3');
if exist(partialResultFile,'file')
    try
        delete( ...
            partialResultFile);
    catch ME
        warning( ...
            'QuadrotorFramework:ControllerPartialCleanup', ...
            'Unable to remove partial tuning file: %s', ...
            ME.message);
    end
end
fprintf('\n');
fprintf( ...
    '==============================================================\n');
fprintf( ...
    ' CONTROLLER TUNING COMPLETE — C2 / SCHEMA 3.0\n');
fprintf( ...
    '==============================================================\n');
fprintf( ...
    'Completed stages:          %d / %d\n', ...
    completedStages, ...
    CFG.numberOfStages);
fprintf( ...
    'Active tunable gains:      %d\n', ...
    CFG.totalTunableGains);
fprintf( ...
    'Accepted tuned stages:     %d / %d\n', ...
    sum(Accepted), ...
    CFG.numberOfStages);
fprintf( ...
    'Final validation:          %s\n', ...
    localPassFail( ...
        overallValidationPass));
fprintf( ...
    'Execution mode:            SERIAL SAFE\n');
fprintf( ...
    'Resume:                    DISABLED\n');
fprintf( ...
    'Total campaign time:       %.2f h\n', ...
    totalTime_s / ...
    3600);
fprintf('\n');
fprintf('Final controller gains:\n\n');
disp( ...
    FINAL_GAIN_TABLE(:, ...
    { ...
    'Stage', ...
    'Label', ...
    'InitialValue', ...
    'TunedValue', ...
    'Multiplier'}));
fprintf('\n');
fprintf('Stage summary:\n\n');
disp( ...
    STAGE_SUMMARY_TABLE);
if isfinite(finalValidationCost)
    fprintf('\n');
    fprintf( ...
        'Final mission-level cost: %.6f\n', ...
        finalValidationCost);
end
fprintf('\n');
fprintf( ...
    'Results folder:\n%s\n', ...
    runFolder);
fprintf('\n');
if overallValidationPass
    fprintf( ...
        ['FINAL CONTROLLER VALIDATION PASSED.\n', ...
         'The candidate controller is stored in:\n', ...
         'CONTROLLER_TUNING_RESULT.FinalAutopilot\n']);
else
    fprintf( ...
        ['WARNING: FINAL CONTROLLER VALIDATION FAILED.\n', ...
         'Do NOT install the tuned controller.\n']);
end
fprintf( ...
    '==============================================================\n\n');
end
function [pass,mode] = localStageAcceptanceContract(R,stageIndex)
requiredFields = { ...
    'accepted'; ...
    'missionValidationPerformed'; ...
    'missionComparisonAvailable'; ...
    'candidateMissionFeasibilityPass'; ...
    'missionValidationValid'; ...
    'missionCostPass'; ...
    'worstPlantPass'; ...
    'missionSafetyPass'};
if ~isstruct(R)
    error( ...
        'QuadrotorFramework:ControllerStageSafetyContract', ...
        'Stage %d did not return a structure.', ...
        stageIndex);
end
for fieldIndex = 1:numel(requiredFields)
    if ~isfield(R,requiredFields{fieldIndex})
        error( ...
            'QuadrotorFramework:ControllerStageSafetyContract', ...
            'Stage %d did not return required safety field "%s".', ...
            stageIndex, ...
            requiredFields{fieldIndex});
    end
end
accepted = ...
    localLogicalScalar( ...
        R.accepted, ...
        'accepted', ...
        stageIndex);
missionValidationPerformed = ...
    localLogicalScalar( ...
        R.missionValidationPerformed, ...
        'missionValidationPerformed', ...
        stageIndex);
comparisonAvailable = ...
    localLogicalScalar( ...
        R.missionComparisonAvailable, ...
        'missionComparisonAvailable', ...
        stageIndex);
candidateMissionFeasibilityPass = ...
    localLogicalScalar( ...
        R.candidateMissionFeasibilityPass, ...
        'candidateMissionFeasibilityPass', ...
        stageIndex);
missionValidationValid = ...
    localLogicalScalar( ...
        R.missionValidationValid, ...
        'missionValidationValid', ...
        stageIndex);
missionCostPass = ...
    localLogicalScalar( ...
        R.missionCostPass, ...
        'missionCostPass', ...
        stageIndex);
worstPlantPass = ...
    localLogicalScalar( ...
        R.worstPlantPass, ...
        'worstPlantPass', ...
        stageIndex);
missionSafetyPass = ...
    localLogicalScalar( ...
        R.missionSafetyPass, ...
        'missionSafetyPass', ...
        stageIndex);
if comparisonAvailable
    mode = ...
        "NORMALIZED_COMPARISON";
    pass = ...
        missionValidationPerformed && ...
        candidateMissionFeasibilityPass && ...
        missionValidationValid && ...
        missionCostPass && ...
        worstPlantPass && ...
        missionSafetyPass;
else
    mode = ...
        "FEASIBILITY_BOOTSTRAP";
    pass = ...
        missionValidationPerformed && ...
        candidateMissionFeasibilityPass && ...
        missionSafetyPass;
end
if accepted && ~pass
    error( ...
        'QuadrotorFramework:ControllerStageSafetyContractInconsistent', ...
        ['Stage %d reports accepted=true but its %s safety contract ', ...
         'does not pass.'], ...
        stageIndex, ...
        char(mode));
end
end
function value = localLogicalScalar(rawValue,fieldName,stageIndex)
if ~(islogical(rawValue) || isnumeric(rawValue)) || ...
        ~isscalar(rawValue) || ...
        ~isfinite(double(rawValue))
    error( ...
        'QuadrotorFramework:ControllerStageSafetyFieldType', ...
        'Stage %d safety field "%s" must be a finite logical scalar.', ...
        stageIndex, ...
        fieldName);
end
value = ...
    logical(rawValue);
end
function P = localBuildPartialResult( ...
    completedStages, ...
    frozenAutopilot, ...
    stageResults, ...
    stageResultsFull, ...
    runFolder)
P = ...
    struct();
P.schemaVersion = ...
    3.0;
P.ControllerGainSchema = ...
    "3.0";
P.CompletedStages = ...
    completedStages;
P.CurrentFrozenAutopilot = ...
    frozenAutopilot;
P.StageResults = ...
    stageResults;
P.StageResultsFull = ...
    stageResultsFull;
P.RunFolder = ...
    runFolder;
P.ResumeAllowed = ...
    false;
P.LastUpdateTimestamp = ...
    char( ...
        datetime( ...
            'now', ...
            'Format', ...
            'yyyy-MM-dd_HH-mm-ss'));
end
function R = localEmptyStageSummary()
R = ...
    struct( ...
    ...
    'stageID',NaN, ...
    'stageName',"", ...
    'accepted',false, ...
    'decision',"NOT_RUN", ...
    'baselineCost',NaN, ...
    'bestSerialCost',NaN, ...
    'optimizationImprovementFraction',NaN, ...
    'stageValidationPerformed',false, ...
    'validationCost',NaN, ...
    'validationImprovementFraction',NaN, ...
    'missionValidationPerformed',false, ...
    'missionValidationCost',NaN, ...
    'missionSafetyPass',false, ...
    'missionCostPass',false, ...
    'worstPlantPass',false, ...
    'optimizationTime_s',NaN);
end
function S = localStageSummaryFromResult(R)
S = ...
    localEmptyStageSummary();
S.stageID = ...
    R.stageID;
S.stageName = ...
    R.stageName;
S.accepted = ...
    R.accepted;
S.decision = ...
    R.decision;
S.baselineCost = ...
    R.baselineOptimizationCost;
S.bestSerialCost = ...
    R.bestSerialCost;
S.optimizationImprovementFraction = ...
    R.optimizationImprovementFraction;
S.stageValidationPerformed = ...
    R.stageValidationPerformed;
S.validationCost = ...
    R.validationCost;
S.validationImprovementFraction = ...
    R.validationImprovementFraction;
S.missionValidationPerformed = ...
    R.missionValidationPerformed;
S.missionValidationCost = ...
    R.missionValidationCost;
S.missionSafetyPass = ...
    R.missionSafetyPass;
S.missionCostPass = ...
    R.missionCostPass;
S.worstPlantPass = ...
    R.worstPlantPass;
S.optimizationTime_s = ...
    R.optimizationTime_s;
end
function V = localBuildFinalValidation( ...
    passed, ...
    baselineResult, ...
    tunedResult, ...
    tunedComparisonResult, ...
    normalizedCost, ...
    improvementFraction, ...
    decision, ...
    baselineUsable, ...
    baselineStrictPassed, ...
    candidateStrictPassed, ...
    comparisonAvailable, ...
    validationSeeds, ...
    baselineStrictSeeds, ...
    baselineFailedSeeds)
V = ...
    struct();
V.schemaVersion = ...
    3.0;
V.ControllerGainSchema = ...
    "3.0";
V.success = ...
    logical(passed);
V.decision = ...
    string(decision);
V.objective = ...
    "Trajectory 2 Mission-Level Objective with EST Controller Feedback and TRUE-State Metrics";
V.baselineResult = ...
    baselineResult;
V.tunedResult = ...
    tunedResult;
V.tunedComparisonResult = ...
    tunedComparisonResult;
V.normalizedCost = ...
    normalizedCost;
V.improvementFraction = ...
    improvementFraction;
V.baselineUsable = ...
    logical(baselineUsable);
V.baselineStrictPassed = ...
    logical(baselineStrictPassed);
V.candidateStrictPassed = ...
    logical(candidateStrictPassed);
V.comparisonAvailable = ...
    logical(comparisonAvailable);
V.validationSeeds = ...
    double(validationSeeds(:));
V.baselineStrictSeeds = ...
    double(baselineStrictSeeds(:));
V.baselineFailedSeeds = ...
    double(baselineFailedSeeds(:));
end
function VALIDATION_STAGE = localMissionValidationStage(CFG)
if ~isfield(CFG,'stages') || isempty(CFG.stages)
    error( ...
        'QuadrotorFramework:ControllerFinalValidationConfiguration', ...
        'CFG.stages is required for final mission validation.');
end
VALIDATION_STAGE = ...
    CFG.stages(end);
VALIDATION_STAGE.id = ...
    9000;
VALIDATION_STAGE.name = ...
    "Mission-Level Safety Validation";
VALIDATION_STAGE.key = ...
    "mission_level_validation";
VALIDATION_STAGE.objectiveType = ...
    "horizontal_position";
VALIDATION_STAGE.initialPoint = ...
    zeros( ...
        VALIDATION_STAGE.numberOfParameters, ...
        1);
end
function seeds = localValidatedSeedOffsets(rawSeeds,label)
seeds = ...
    double( ...
        rawSeeds(:));
if isempty(seeds)
    error( ...
        'QuadrotorFramework:ControllerFinalValidationSeeds', ...
        '%s requires at least one seed.', ...
        label);
end
if any(~isfinite(seeds))
    error( ...
        'QuadrotorFramework:ControllerFinalValidationSeeds', ...
        '%s seeds must be finite.', ...
        label);
end
if numel(unique(seeds)) ~= numel(seeds)
    error( ...
        'QuadrotorFramework:ControllerFinalValidationSeeds', ...
        '%s seeds must be unique.', ...
        label);
end
end
function mask = localUsableRunMask(R,numberOfSeeds)
mask = ...
    false( ...
        numberOfSeeds, ...
        1);
if isempty(R) || ...
        ~isstruct(R) || ...
        ~isfield(R,'metricsAvailable') || ...
        isempty(R.metricsAvailable) || ...
        ~isfield(R,'runSucceeded') || ...
        isempty(R.runSucceeded)
    return;
end
available = ...
    logical( ...
        R.metricsAvailable);
succeeded = ...
    logical( ...
        R.runSucceeded);
if size(available,2) ~= numberOfSeeds || ...
        size(succeeded,2) ~= numberOfSeeds
    return;
end
mask = ...
    all(available,1).' & ...
    all(succeeded,1).';
end
function mask = localStrictRunMask(R,numberOfSeeds)
mask = ...
    false( ...
        numberOfSeeds, ...
        1);
if isempty(R) || ...
        ~isstruct(R) || ...
        ~isfield(R,'strictRunSucceeded') || ...
        isempty(R.strictRunSucceeded)
    return;
end
strict = ...
    logical( ...
        R.strictRunSucceeded);
if size(strict,2) ~= numberOfSeeds
    return;
end
mask = ...
    all(strict,1).';
end
function displayValidationMessages(R)
if isempty(R) || ...
        ~isstruct(R)
    fprintf( ...
        '  No validation diagnostics available.\n');
    return;
end
if ~isfield(R,'messages') || ...
        isempty(R.messages)
    fprintf( ...
        '  No validation diagnostics available.\n');
    return;
end
messages = ...
    R.messages;
if ischar(messages) || ...
        isstring(messages)
    messages = ...
        cellstr( ...
            string(messages));
end
for k = 1:numel(messages)
    if isempty(messages{k})
        continue;
    end
    fprintf( ...
        '  [%d] %s\n', ...
        k, ...
        char( ...
            string(messages{k})));
end
end
function localRestoreControllerTuningFlag( ...
    previouslyExisted, ...
    previousValue)
try
    if previouslyExisted
        assignin( ...
            'base', ...
            'CONTROLLER_TUNING_ACTIVE', ...
            previousValue);
    else
        evalin( ...
            'base', ...
            'clear(''CONTROLLER_TUNING_ACTIVE'')');
    end
catch
end
end
function localCheckExpectedGain(T,path,expectedValue)
row = ...
    find( ...
        string(T.ParameterPath) == ...
        string(path), ...
        1, ...
        'first');
if isempty(row)
    error( ...
        'QuadrotorFramework:ControllerTuningExpectedBaselinePath', ...
        'Expected baseline gain "%s" is missing from the active C2 gain table.', ...
        path);
end
actualValue = ...
    double( ...
        T.EffectiveValue(row));
tolerance = ...
    max( ...
        1e-12, ...
        1e-10*max(abs(double(expectedValue)),1));
if ~isfinite(actualValue) || ...
        abs(actualValue-double(expectedValue)) > tolerance
    error( ...
        'QuadrotorFramework:ControllerTuningExpectedBaselineMismatch', ...
        'Baseline gain "%s" is %.15g but the final local campaign expects %.15g.', ...
        path, ...
        actualValue, ...
        double(expectedValue));
end
end
function output = localPassFail(flag)
if flag
    output = ...
        'PASS';
else
    output = ...
        'FAIL';
end
end
