function [STAGE_RESULT, frozenAutopilotOut] = tune_controller_stage( ...
    CFG, ...
    STAGE, ...
    frozenAutopilotIn, ...
    runFolder)
narginchk(3,4);
if nargin < 4 || ...
        isempty(runFolder)
    runFolder = ...
        fullfile( ...
            pwd, ...
            CFG.output.rootFolder);
end
if ~isstruct(CFG)
    error( ...
        'QuadrotorFramework:ControllerStageInvalidCFG', ...
        'CFG must be a structure.');
end
if ~isstruct(STAGE)
    error( ...
        'QuadrotorFramework:ControllerStageInvalidStage', ...
        'STAGE must be a structure.');
end
if ~isstruct(frozenAutopilotIn)
    error( ...
        'QuadrotorFramework:ControllerStageInvalidAutopilot', ...
        'frozenAutopilotIn must be a structure.');
end
if ~isfield(CFG,'schemaVersion') || double(CFG.schemaVersion) < 3.0
    error('QuadrotorFramework:ControllerStageSchema','Controller tuning requires configuration schema 3.0 or newer.');
end
if ~isfield(CFG,'experiment') || ~isstruct(CFG.experiment)
    error('QuadrotorFramework:ControllerStageExperiment','CFG.experiment is required.');
end
if ~isfield(CFG.experiment,'controllerSet') || ~strcmpi(string(CFG.experiment.controllerSet),"C2")
    error('QuadrotorFramework:ControllerStageControllerSet','This stage tuner is configured for controller set C2.');
end
if ~isfield(CFG.experiment,'plantModels') || ~isequal(double(CFG.experiment.plantModels(:).'),3)
    error('QuadrotorFramework:ControllerStagePlantModels','C2 tuning must evaluate L3 only.');
end
if ~isfield(CFG.experiment,'trajectoryID') || double(CFG.experiment.trajectoryID) ~= 2
    error('QuadrotorFramework:ControllerStageTrajectory','C2 tuning must use trajectory 2.');
end
if ~isfield(CFG.experiment,'feedbackSource') || ~strcmpi(string(CFG.experiment.feedbackSource),"EST")
    error('QuadrotorFramework:ControllerStageFeedback','C2 tuning must use EST controller feedback.');
end
if ~isfield(CFG.experiment,'metricStateSource') || ~strcmpi(string(CFG.experiment.metricStateSource),"TRUE")
    error('QuadrotorFramework:ControllerStageMetricState','Controller performance metrics must use TRUE state.');
end
if ~isfield(frozenAutopilotIn,'info') || ~isstruct(frozenAutopilotIn.info) || ~isfield(frozenAutopilotIn.info,'controllerGainSchema') || string(frozenAutopilotIn.info.controllerGainSchema) ~= "3.0"
    error('QuadrotorFramework:ControllerStageAutopilotSchema','frozenAutopilotIn must use controller gain schema 3.0.');
end
if ~isfield(frozenAutopilotIn.info,'activeController') || ~strcmpi(string(frozenAutopilotIn.info.activeController),"C2")
    error('QuadrotorFramework:ControllerStageActiveController','frozenAutopilotIn must have controller set C2 active.');
end
requestedLowerLog10Multiplier = double(STAGE.lowerLog10Multiplier(:));
requestedUpperLog10Multiplier = double(STAGE.upperLog10Multiplier(:));
[STAGE,SAFETY_BOUNDS] = localApplySafetyBounds(STAGE,CFG);
requiredStageFields = { ...
    'id'; ...
    'name'; ...
    'key'; ...
    'objectiveType'; ...
    'parameterPaths'; ...
    'parameterLabels'; ...
    'numberOfParameters'; ...
    'lowerLog10Multiplier'; ...
    'upperLog10Multiplier'; ...
    'initialPoint'; ...
    'minSurrogatePoints'; ...
    'maxFunctionEvaluations'};
for fieldIndex = 1:numel(requiredStageFields)
    fieldName = ...
        requiredStageFields{fieldIndex};
    if ~isfield(STAGE,fieldName)
        error( ...
            'QuadrotorFramework:ControllerStageMissingField', ...
            'STAGE.%s is required.', ...
            fieldName);
    end
end
numberOfParameters = ...
    double( ...
        STAGE.numberOfParameters);
if ~isscalar(numberOfParameters) || ...
        ~isfinite(numberOfParameters) || ...
        numberOfParameters < 1 || ...
        numberOfParameters ~= floor(numberOfParameters)
    error( ...
        'QuadrotorFramework:ControllerStageParameterCount', ...
        'STAGE.numberOfParameters must be a positive integer.');
end
if numel(STAGE.parameterPaths) ~= ...
        numberOfParameters
    error( ...
        'QuadrotorFramework:ControllerStageParameterPathCount', ...
        ['Stage "%s" declares %d parameters but contains %d ', ...
         'parameter paths.'], ...
        STAGE.name, ...
        numberOfParameters, ...
        numel(STAGE.parameterPaths));
end
if numel(STAGE.parameterLabels) ~= ...
        numberOfParameters
    error( ...
        'QuadrotorFramework:ControllerStageParameterLabelCount', ...
        ['Stage "%s" declares %d parameters but contains %d ', ...
         'parameter labels.'], ...
        STAGE.name, ...
        numberOfParameters, ...
        numel(STAGE.parameterLabels));
end
localValidateFinalLocalStageContract( ...
    STAGE);
if ~isfield(CFG,'policy') || ...
        ~isstruct(CFG.policy)
    error( ...
        'QuadrotorFramework:ControllerStagePolicy', ...
        'CFG.policy is required.');
end
requiredPolicyFields = { ...
    'runParallelPreflightEachStage'; ...
    'validateEachStage'; ...
    'serialBestCheckEachStage'; ...
    'keepBaselineIfNoImprovement'; ...
    'minimumImprovementFraction'};
for fieldIndex = 1:numel(requiredPolicyFields)
    fieldName = ...
        requiredPolicyFields{fieldIndex};
    if ~isfield(CFG.policy,fieldName)
        error( ...
            'QuadrotorFramework:ControllerStageMissingPolicy', ...
            'CFG.policy.%s is required.', ...
            fieldName);
    end
end
if ~isfield(CFG,'optimizer') || ...
        ~isstruct(CFG.optimizer)
    error( ...
        'QuadrotorFramework:ControllerStageOptimizer', ...
        'CFG.optimizer is required.');
end
requiredOptimizerFields = { ...
    'useParallel'; ...
    'batchSize'; ...
    'display'; ...
    'randomSeed'};
for fieldIndex = 1:numel(requiredOptimizerFields)
    fieldName = ...
        requiredOptimizerFields{fieldIndex};
    if ~isfield(CFG.optimizer,fieldName)
        error( ...
            'QuadrotorFramework:ControllerStageMissingOptimizerField', ...
            'CFG.optimizer.%s is required.', ...
            fieldName);
    end
end
try
    initialGainTable = ...
        controller_tuning_gain_table( ...
            frozenAutopilotIn, ...
            STAGE.parameterPaths);
catch ME
    error( ...
        'QuadrotorFramework:ControllerStageGainContract', ...
        ['Stage "%s" is not compatible with the current ', ...
         'controller gain schema.\n\n%s'], ...
        STAGE.name, ...
        ME.message);
end
if ~exist(runFolder,'dir')
    mkdir(runFolder);
end
stageKey = ...
    char( ...
        STAGE.key);
stageFolder = ...
    fullfile( ...
        runFolder, ...
        sprintf( ...
            'Stage_%02d_%s', ...
            STAGE.id, ...
            stageKey));
if ~exist(stageFolder,'dir')
    mkdir(stageFolder);
end
stageResultFile = ...
    fullfile( ...
        stageFolder, ...
        'Stage_Result.mat');
checkpointFile = ...
    fullfile( ...
        stageFolder, ...
        'SurrogateOpt_Checkpoint.mat');
if exist(checkpointFile,'file')
    delete(checkpointFile);
end
fprintf('\n');
fprintf( ...
    '==============================================================\n');
fprintf( ...
    ' CONTROLLER FAST TUNING — STAGE %d/%d\n', ...
    STAGE.id, ...
    CFG.numberOfStages);
fprintf( ...
    '==============================================================\n');
fprintf( ...
    'Stage:                     %s\n', ...
    STAGE.name);
fprintf( ...
    'Controller set:            %s\n', ...
    string(CFG.experiment.controllerSet));
plantModelText = ...
    strjoin( ...
        compose( ...
            "L%d", ...
            double(CFG.experiment.plantModels(:).')), ...
        " + ");
fprintf( ...
    'Plant models:              %s\n', ...
    char(plantModelText));
fprintf( ...
    'Trajectory ID:             %d\n', ...
    CFG.experiment.trajectoryID);
fprintf( ...
    'Feedback:                  %s\n', ...
    string(CFG.experiment.feedbackSource));
fprintf( ...
    'Metric state source:       %s\n', ...
    string(CFG.experiment.metricStateSource));
fprintf( ...
    'Parameters:                %d\n', ...
    numberOfParameters);
fprintf( ...
    'Function evaluations:      %d\n', ...
    STAGE.maxFunctionEvaluations);
fprintf( ...
    'Safety multiplier range:   [%.3f, %.3f]\n', ...
    SAFETY_BOUNDS.minimumMultiplier, ...
    SAFETY_BOUNDS.maximumMultiplier);
fprintf( ...
    'Min surrogate points:      %d\n', ...
    STAGE.minSurrogatePoints);
fprintf( ...
    'Optimization seed offset:  %g\n', ...
    CFG.experiment.optimizationSeedOffset);
fprintf( ...
    'Batch preflight:           %d\n', ...
    CFG.policy.runParallelPreflightEachStage);
fprintf( ...
    'Stage multi-seed validate: %d\n', ...
    CFG.policy.validateEachStage);
fprintf( ...
    'Serial best check:         %d\n', ...
    CFG.policy.serialBestCheckEachStage);
fprintf( ...
    'Baseline feasibility mode: SOFT MISSION FAILURES RECOVERABLE\n');
fprintf( ...
    'Optimizer mission policy:  SOFT-COST / STRICT BEST-CANDIDATE CHECK\n');
fprintf( ...
    '--------------------------------------------------------------\n');
fprintf('\nCurrent frozen gains:\n\n');
disp( ...
    initialGainTable(:, ...
    {'Label','EffectiveValue'}));
z0 = ...
    zeros( ...
        numberOfParameters, ...
        1);
fprintf('\n');
fprintf('Evaluating optimization baseline...\n');
requestedOptimizationSeedOffset = ...
    double( ...
        CFG.experiment.optimizationSeedOffset);
optimizationSeedCandidates = ...
    requestedOptimizationSeedOffset;
stageValidationSeedsConfigured = ...
    localStageSeedOffsets( ...
        CFG);
if ~isempty(stageValidationSeedsConfigured)
    optimizationSeedCandidates = [ ...
        optimizationSeedCandidates; ...
        stageValidationSeedsConfigured(:)];
end
optimizationSeedCandidates = ...
    unique( ...
        optimizationSeedCandidates(:), ...
        'stable');
if any(~isfinite(optimizationSeedCandidates))
    error( ...
        'QuadrotorFramework:ControllerStageOptimizationSeeds', ...
        'Optimization seed candidates must be finite.');
end
BASELINE_OPT = ...
    [];
optimizationSeedOffsetUsed = ...
    NaN;
baselineOptimizationAttempts = ...
    repmat( ...
        struct( ...
            'seedOffset',NaN, ...
            'success',false, ...
            'softFailureOnly',false, ...
            'messages',{{}}), ...
        numel(optimizationSeedCandidates), ...
        1);
for seedCandidateIndex = 1:numel(optimizationSeedCandidates)
    currentSeedOffset = ...
        optimizationSeedCandidates(seedCandidateIndex);
    [~,BASELINE_TRIAL] = ...
        evaluate_controller_candidate( ...
            z0, ...
            CFG, ...
            STAGE, ...
            frozenAutopilotIn, ...
            [], ...
            'serial', ...
            currentSeedOffset, ...
            'baseline');
    baselineOptimizationAttempts(seedCandidateIndex).seedOffset = ...
        currentSeedOffset;
    baselineOptimizationAttempts(seedCandidateIndex).success = ...
        logical(BASELINE_TRIAL.success);
    baselineOptimizationAttempts(seedCandidateIndex).messages = ...
        BASELINE_TRIAL.messages;
    baselineOptimizationAttempts(seedCandidateIndex).softFailureOnly = ...
        localSoftBaselineFailureOnly( ...
            BASELINE_TRIAL);
    if BASELINE_TRIAL.success
        BASELINE_OPT = ...
            BASELINE_TRIAL;
        optimizationSeedOffsetUsed = ...
            currentSeedOffset;
        break;
    end
    fprintf( ...
        '\nOptimization baseline seed %g did not complete the strict mission.\n', ...
        currentSeedOffset);
    displayMessages( ...
        BASELINE_TRIAL.messages);
    if ~localSoftBaselineFailureOnly(BASELINE_TRIAL)
        error( ...
            'QuadrotorFramework:ControllerStageBaselineHardFailure', ...
            ['Optimization baseline failed for stage "%s" because of a ', ...
             'nonrecoverable simulation, logging, configuration, or numerical error.'], ...
            STAGE.name);
    end
end
if isempty(BASELINE_OPT) || ...
        ~isfinite(optimizationSeedOffsetUsed)
    error( ...
        'QuadrotorFramework:ControllerStageNoUsableBaselineSeed', ...
        ['No deterministic seed produced a complete baseline mission for stage "%s". ', ...
         'A finite successful baseline metric is required to normalize the optimizer. ', ...
         'Soft mission failures are recoverable in validation, but the optimization ', ...
         'objective itself requires at least one successful baseline seed.'], ...
        STAGE.name);
end
OPTIMIZATION_CFG = ...
    CFG;
OPTIMIZATION_CFG.experiment.optimizationSeedOffset = ...
    optimizationSeedOffsetUsed;
CFG.experiment.optimizationSeedOffset = ...
    optimizationSeedOffsetUsed;
baselineOptimizationRecoverable = ...
    optimizationSeedOffsetUsed ~= ...
    requestedOptimizationSeedOffset || ...
    ( ...
    isfield(BASELINE_OPT,'softBaselineUsed') && ...
    logical(BASELINE_OPT.softBaselineUsed));
baselineOptimizationUsable = ...
    true;
baselineOptimizationMetrics = ...
    BASELINE_OPT.metrics;
baselineOptimizationCost = ...
    1.0;
fprintf( ...
    'Optimization baseline seed: %g\n', ...
    optimizationSeedOffsetUsed);
if optimizationSeedOffsetUsed ~= requestedOptimizationSeedOffset
    fprintf( ...
        'Baseline seed fallback:    USED (requested %g)\n', ...
        requestedOptimizationSeedOffset);
else
    fprintf( ...
        'Baseline seed fallback:    NOT NEEDED\n');
end
if isfield(BASELINE_OPT,'softBaselineUsed') && ...
        logical(BASELINE_OPT.softBaselineUsed)
    fprintf( ...
        'Baseline mission status:   PARTIAL/SOFT — METRICS USED FOR NORMALIZATION\n');
else
    fprintf( ...
        'Baseline mission status:   STRICT PASS\n');
end
fprintf( ...
    'Baseline normalized cost:  %.6f\n', ...
    baselineOptimizationCost);
fprintf( ...
    'Optimizer seed actually used: %g\n', ...
    optimizationSeedOffsetUsed);
PREFLIGHT = ...
    struct();
PREFLIGHT.performed = ...
    false;
PREFLIGHT.success = ...
    true;
PREFLIGHT.cost = ...
    NaN;
PREFLIGHT.result = ...
    [];
if CFG.policy.runParallelPreflightEachStage
    fprintf('\n');
    fprintf('Running batch-objective preflight...\n');
    [preflightCost,preflightResult] = ...
        evaluate_controller_candidates_parallel( ...
            z0.', ...
            OPTIMIZATION_CFG, ...
            STAGE, ...
            frozenAutopilotIn, ...
            baselineOptimizationMetrics);
    preflightValid = ...
        ~isempty(preflightCost) && ...
        isfinite(preflightCost(1)) && ...
        preflightCost(1) < CFG.cost.failurePenalty && ...
        preflightResult(1).success;
    PREFLIGHT.performed = ...
        true;
    PREFLIGHT.success = ...
        preflightValid;
    PREFLIGHT.cost = ...
        preflightCost(1);
    PREFLIGHT.result = ...
        preflightResult;
    if ~preflightValid
        error( ...
            'QuadrotorFramework:ControllerStageBatchPreflight', ...
            ['Batch objective preflight failed for stage "%s".'], ...
            STAGE.name);
    end
    fprintf( ...
        'Batch preflight cost:      %.6f\n', ...
        preflightCost(1));
    fprintf( ...
        'Batch preflight:           OK\n');
else
    fprintf( ...
        'Batch preflight:           SKIPPED (fast campaign)\n');
end
lowerBounds = ...
    double( ...
        STAGE.lowerLog10Multiplier(:));
upperBounds = ...
    double( ...
        STAGE.upperLog10Multiplier(:));
initialPoint = ...
    double( ...
        STAGE.initialPoint(:).');
if numel(lowerBounds) ~= ...
        numberOfParameters || ...
        numel(upperBounds) ~= ...
        numberOfParameters
    error( ...
        'QuadrotorFramework:ControllerStageOptimizerBounds', ...
        'Stage optimizer bounds have incorrect dimensions.');
end
if numel(initialPoint) ~= ...
        numberOfParameters
    error( ...
        'QuadrotorFramework:ControllerStageInitialPoint', ...
        'Stage initial point has incorrect dimensions.');
end
if any(~isfinite(lowerBounds)) || ...
        any(~isfinite(upperBounds)) || ...
        any(lowerBounds >= upperBounds)
    error( ...
        'QuadrotorFramework:ControllerStageInvalidOptimizerBounds', ...
        'Stage optimizer bounds are invalid.');
end
if any(~isfinite(initialPoint)) || ...
        any(initialPoint(:) < lowerBounds) || ...
        any(initialPoint(:) > upperBounds)
    error( ...
        'QuadrotorFramework:ControllerStageInvalidInitialPoint', ...
        'Stage initial point is outside the configured bounds.');
end
useVectorizedObjective = ...
    logical( ...
        CFG.optimizer.useParallel);
if useVectorizedObjective
    options = ...
        optimoptions( ...
            'surrogateopt', ...
            ...
            'MaxFunctionEvaluations', ...
            STAGE.maxFunctionEvaluations, ...
            ...
            'MinSurrogatePoints', ...
            STAGE.minSurrogatePoints, ...
            ...
            'UseParallel', ...
            false, ...
            ...
            'UseVectorized', ...
            true, ...
            ...
            'BatchUpdateInterval', ...
            CFG.optimizer.batchSize, ...
            ...
            'InitialPoints', ...
            initialPoint, ...
            ...
            'CheckpointFile', ...
            checkpointFile, ...
            ...
            'Display', ...
            CFG.optimizer.display);
    objectiveFunction = ...
        @(Z) controllerObjectiveBatch( ...
            Z, ...
            OPTIMIZATION_CFG, ...
            STAGE, ...
            frozenAutopilotIn, ...
            baselineOptimizationMetrics);
else
    options = ...
        optimoptions( ...
            'surrogateopt', ...
            ...
            'MaxFunctionEvaluations', ...
            STAGE.maxFunctionEvaluations, ...
            ...
            'MinSurrogatePoints', ...
            STAGE.minSurrogatePoints, ...
            ...
            'UseParallel', ...
            false, ...
            ...
            'UseVectorized', ...
            false, ...
            ...
            'InitialPoints', ...
            initialPoint, ...
            ...
            'CheckpointFile', ...
            checkpointFile, ...
            ...
            'Display', ...
            CFG.optimizer.display);
    objectiveFunction = ...
        @(z) controllerObjectiveSerial( ...
            z, ...
            OPTIMIZATION_CFG, ...
            STAGE, ...
            frozenAutopilotIn, ...
            baselineOptimizationMetrics);
end
options.PlotFcn = [];
options.OutputFcn = [];
stageRandomSeed = ...
    double( ...
        CFG.optimizer.randomSeed) + ...
    double( ...
        STAGE.id) - ...
    1;
rng( ...
    stageRandomSeed, ...
    'twister');
fprintf('\n');
if useVectorizedObjective
    fprintf( ...
        'Starting surrogateopt — vectorized batch objective...\n\n');
else
    fprintf( ...
        'Starting surrogateopt — SERIAL objective...\n\n');
end
optimizationStart = ...
    tic;
[ ...
    bestZ, ...
    optimizerCost, ...
    exitFlag, ...
    optimizerOutput, ...
    trials] = ...
    surrogateopt( ...
        objectiveFunction, ...
        lowerBounds, ...
        upperBounds, ...
        options);
optimizationTime_s = ...
    toc( ...
        optimizationStart);
bestZ = ...
    double( ...
        bestZ(:));
optimizerCost = ...
    double( ...
        optimizerCost);
fprintf('\n');
fprintf('Optimization completed.\n');
fprintf( ...
    'Optimizer reported cost:   %.6f\n', ...
    optimizerCost);
fprintf( ...
    'Optimization time:         %.2f min\n', ...
    optimizationTime_s/60);
BEST_SERIAL = ...
    [];
bestSerialCost = ...
    CFG.cost.failurePenalty;
bestSerialValid = ...
    false;
if CFG.policy.serialBestCheckEachStage
    fprintf('\n');
    fprintf('Serially re-evaluating best candidate...\n');
    [bestSerialCost,BEST_SERIAL] = ...
        evaluate_controller_candidate( ...
            bestZ, ...
            OPTIMIZATION_CFG, ...
            STAGE, ...
            frozenAutopilotIn, ...
            baselineOptimizationMetrics, ...
            'serial', ...
            optimizationSeedOffsetUsed, ...
            'strict');
    bestSerialValid = ...
        BEST_SERIAL.success && ...
        isfinite(bestSerialCost) && ...
        bestSerialCost < ...
        CFG.cost.failurePenalty;
else
    error( ...
        'QuadrotorFramework:ControllerSerialBestRequired', ...
        ['serialBestCheckEachStage=false is not supported for the ', ...
         'current scientific tuning workflow.']);
end
if ~bestSerialValid
    fprintf('\n');
    fprintf('Best candidate serial check FAILED.\n');
    displayMessages( ...
        BEST_SERIAL.messages);
end
fprintf( ...
    'Serial best cost:          %.6f\n', ...
    bestSerialCost);
if bestSerialValid
    [bestGainTable,tunedAutopilot] = ...
        controller_tuning_gain_table( ...
            frozenAutopilotIn, ...
            STAGE.parameterPaths, ...
            BEST_SERIAL.gainValues);
else
    bestGainTable = ...
        initialGainTable;
    tunedAutopilot = ...
        frozenAutopilotIn;
end
minimumImprovement = ...
    double( ...
        CFG.policy.minimumImprovementFraction);
if bestSerialValid
    optimizationImprovementFraction = ...
        1 - ...
        bestSerialCost / ...
        baselineOptimizationCost;
else
    optimizationImprovementFraction = ...
        -Inf;
end
optimizationFeasibilityBootstrap = ...
    bestSerialValid && ...
    isfield(BASELINE_OPT,'softBaselineUsed') && ...
    logical(BASELINE_OPT.softBaselineUsed);
optimizationImproved = ...
    bestSerialValid && ...
    ( ...
    optimizationImprovementFraction >= ...
    minimumImprovement || ...
    optimizationFeasibilityBootstrap);
if optimizationFeasibilityBootstrap
    fprintf( ...
        'Optimization decision:      FEASIBILITY BOOTSTRAP ENABLED\n');
end
BASELINE_VALIDATION = ...
    localNotPerformedValidation( ...
        'Stage-level validation disabled by configuration.');
TUNED_VALIDATION = ...
    localNotPerformedValidation( ...
        'Normalized stage validation was not performed.');
TUNED_VALIDATION_FEASIBILITY = ...
    localNotPerformedValidation( ...
        'Strict stage feasibility validation was not performed.');
baselineValidationValid = ...
    NaN;
baselineValidationRecoverable = ...
    false;
baselineValidationUsable = ...
    NaN;
baselineValidationComparableSeeds = ...
    [];
baselineValidationSuccessfulSeeds = ...
    [];
baselineValidationFailedSeeds = ...
    [];
validationComparisonAvailable = ...
    false;
tunedValidationValid = ...
    NaN;
stageValidationFeasibilityPass = ...
    NaN;
stageValidationPass = ...
    true;
validationCost = ...
    NaN;
validationImprovementFraction = ...
    NaN;
validationImproved = ...
    NaN;
stageValidationPerformed = ...
    false;
if CFG.policy.validateEachStage
    stageValidationPerformed = ...
        true;
    validationSeeds = ...
        localValidatedSeedOffsets( ...
            localStageSeedOffsets(CFG), ...
            'stage validation');
    fprintf('\n');
    fprintf( ...
        'Evaluating stage baseline on %d validation seeds...\n', ...
        numel(validationSeeds));
    [~,BASELINE_VALIDATION] = ...
        evaluate_controller_candidate( ...
            z0, ...
            CFG, ...
            STAGE, ...
            frozenAutopilotIn, ...
            [], ...
            'serial', ...
            validationSeeds, ...
            'baseline');
    baselineValidationUsableMask = ...
        localSuccessfulRunMask( ...
            BASELINE_VALIDATION, ...
            numel(validationSeeds));
    baselineValidationMask = ...
        localStrictRunMask( ...
            BASELINE_VALIDATION, ...
            numel(validationSeeds));
    baselineValidationValid = ...
        all(baselineValidationMask);
    baselineValidationSuccessfulSeeds = ...
        validationSeeds(baselineValidationMask);
    baselineValidationFailedSeeds = ...
        validationSeeds(~baselineValidationMask);
    baselineValidationUsable = ...
        any(baselineValidationUsableMask);
    baselineValidationRecoverable = ...
        ~baselineValidationValid && ...
        all(baselineValidationUsableMask);
    if ~baselineValidationValid
        fprintf('\nStage validation baseline messages:\n');
        displayMessages( ...
            BASELINE_VALIDATION.messages);
        if ~baselineValidationRecoverable
            error( ...
                'QuadrotorFramework:ControllerStageValidationBaselineHardFailure', ...
                ['Validation baseline failed for stage "%s" because at least one ', ...
                 'seed did not provide usable metrics.'], ...
                STAGE.name);
        end
        fprintf( ...
            'Stage baseline status:     SOFT MISSION FAILURE(S) — RECOVERABLE\n');
    end
    fprintf( ...
        'Baseline strict seeds:       %d/%d\n', ...
        nnz(baselineValidationMask), ...
        numel(validationSeeds));
    fprintf( ...
        'Baseline usable seeds:       %d/%d\n', ...
        nnz(baselineValidationUsableMask), ...
        numel(validationSeeds));
    validationComparisonAvailable = ...
        any(baselineValidationMask);
    if bestSerialValid && ...
            validationComparisonAvailable
        baselineValidationComparableSeeds = ...
            validationSeeds(baselineValidationMask);
        baselineValidationMetrics = ...
            BASELINE_VALIDATION.metrics(baselineValidationMask);
        fprintf( ...
            'Evaluating tuned candidate on %d comparable validation seeds...\n', ...
            numel(baselineValidationComparableSeeds));
        [validationCost,TUNED_VALIDATION] = ...
            evaluate_controller_candidate( ...
                bestZ, ...
                CFG, ...
                STAGE, ...
                frozenAutopilotIn, ...
                baselineValidationMetrics, ...
                'serial', ...
                baselineValidationComparableSeeds);
        tunedValidationValid = ...
            TUNED_VALIDATION.success && ...
            isfinite(validationCost) && ...
            validationCost < ...
            CFG.cost.failurePenalty;
        if tunedValidationValid
            validationImprovementFraction = ...
                1 - ...
                validationCost;
            validationImproved = ...
                validationImprovementFraction >= ...
                minimumImprovement;
        else
            validationImprovementFraction = ...
                -Inf;
            validationImproved = ...
                false;
        end
    elseif ~validationComparisonAvailable
        fprintf( ...
            'Normalized stage comparison: UNAVAILABLE (no successful baseline validation seed)\n');
    end
    if bestSerialValid
        if validationComparisonAvailable && ...
                all(baselineValidationMask) && ...
                tunedValidationValid
            TUNED_VALIDATION_FEASIBILITY = ...
                TUNED_VALIDATION;
            stageValidationFeasibilityPass = ...
                true;
        else
            fprintf( ...
                'Running strict tuned-candidate feasibility check on all validation seeds...\n');
            [~,TUNED_VALIDATION_FEASIBILITY] = ...
                evaluate_controller_candidate( ...
                    bestZ, ...
                    CFG, ...
                    STAGE, ...
                    frozenAutopilotIn, ...
                    [], ...
                    'serial', ...
                    validationSeeds, ...
                    'strict');
            stageValidationFeasibilityPass = ...
                logical( ...
                    TUNED_VALIDATION_FEASIBILITY.success);
        end
    else
        stageValidationFeasibilityPass = ...
            false;
    end
    stageValidationPass = ...
        bestSerialValid && ...
        logical(stageValidationFeasibilityPass) && ...
        ( ...
        ~validationComparisonAvailable || ...
        ( ...
        logical(tunedValidationValid) && ...
        logical(validationImproved)));
    fprintf( ...
        'Stage strict feasibility:   %s\n', ...
        localPassFail( ...
            stageValidationFeasibilityPass));
    if validationComparisonAvailable
        fprintf( ...
            'Stage normalized gate:     %s\n', ...
            localPassFail( ...
                tunedValidationValid && ...
                validationImproved));
    else
        fprintf( ...
            'Stage normalized gate:     N/A — feasibility bootstrap mode\n');
    end
    fprintf( ...
        'Stage validation gate:     %s\n', ...
        localPassFail( ...
            stageValidationPass));
end
MISSION_VALIDATION_STAGE = ...
    localMissionValidationStage( ...
        CFG);
missionValidationSeeds = ...
    localValidatedSeedOffsets( ...
        localStageSeedOffsets(CFG), ...
        'mission validation');
zMission = ...
    zeros( ...
        MISSION_VALIDATION_STAGE.numberOfParameters, ...
        1);
fprintf('\n');
fprintf( ...
    'Running mandatory mission-level safety gate on %d validation seeds...\n', ...
    numel(missionValidationSeeds));
[~,BASELINE_MISSION_VALIDATION] = ...
    evaluate_controller_candidate( ...
        zMission, ...
        CFG, ...
        MISSION_VALIDATION_STAGE, ...
        frozenAutopilotIn, ...
        [], ...
        'serial', ...
        missionValidationSeeds, ...
        'baseline');
baselineMissionUsableMask = ...
    localSuccessfulRunMask( ...
        BASELINE_MISSION_VALIDATION, ...
        numel(missionValidationSeeds));
baselineMissionMask = ...
    localStrictRunMask( ...
        BASELINE_MISSION_VALIDATION, ...
        numel(missionValidationSeeds));
baselineMissionValid = ...
    all(baselineMissionMask);
baselineMissionRecoverable = ...
    ~baselineMissionValid && ...
    all(baselineMissionUsableMask);
baselineMissionUsable = ...
    any(baselineMissionUsableMask);
baselineMissionSuccessfulSeeds = ...
    missionValidationSeeds(baselineMissionMask);
baselineMissionFailedSeeds = ...
    missionValidationSeeds(~baselineMissionMask);
if ~baselineMissionValid
    fprintf('\nMission-level baseline messages:\n');
    displayMessages( ...
        BASELINE_MISSION_VALIDATION.messages);
    if ~baselineMissionRecoverable
        error( ...
            'QuadrotorFramework:ControllerStageMissionBaselineHardFailure', ...
            ['Mission-level baseline failed for stage "%s" because at least one ', ...
             'validation seed did not provide usable metrics.'], ...
            STAGE.name);
    end
    fprintf( ...
        'Mission baseline status:   SOFT MISSION FAILURE(S) — RECOVERABLE\n');
end
fprintf( ...
    'Mission baseline strict:     %d/%d seeds\n', ...
    nnz(baselineMissionMask), ...
    numel(missionValidationSeeds));
fprintf( ...
    'Mission baseline usable:     %d/%d seeds\n', ...
    nnz(baselineMissionUsableMask), ...
    numel(missionValidationSeeds));
missionComparisonAvailable = ...
    any(baselineMissionMask);
TUNED_MISSION_VALIDATION = ...
    localNotPerformedValidation( ...
        'Normalized tuned mission validation was not performed.');
TUNED_MISSION_FEASIBILITY = ...
    localNotPerformedValidation( ...
        'Strict tuned mission feasibility validation was not performed.');
missionValidationCost = ...
    NaN;
missionImprovementFraction = ...
    NaN;
missionValidationValid = ...
    false;
candidateMissionFeasibilityPass = ...
    false;
missionCostPass = ...
    false;
worstPlantPass = ...
    false;
missionPlantMeanCosts = ...
    NaN( ...
        numel(CFG.experiment.plantModels), ...
        1);
missionMaximumDegradationFraction = ...
    0.01;
worstPlantMaximumDegradationFraction = ...
    0.05;
if isfield(CFG.policy,'maximumMissionCostDegradationFraction')
    missionMaximumDegradationFraction = ...
        double( ...
            CFG.policy.maximumMissionCostDegradationFraction);
end
if isfield(CFG.policy,'maximumWorstPlantCostDegradationFraction')
    worstPlantMaximumDegradationFraction = ...
        double( ...
            CFG.policy.maximumWorstPlantCostDegradationFraction);
end
if ~isscalar(missionMaximumDegradationFraction) || ...
        ~isfinite(missionMaximumDegradationFraction) || ...
        missionMaximumDegradationFraction < 0
    error( ...
        'QuadrotorFramework:ControllerStageMissionDegradationLimit', ...
        'maximumMissionCostDegradationFraction must be a finite nonnegative scalar.');
end
if ~isscalar(worstPlantMaximumDegradationFraction) || ...
        ~isfinite(worstPlantMaximumDegradationFraction) || ...
        worstPlantMaximumDegradationFraction < 0
    error( ...
        'QuadrotorFramework:ControllerStageWorstPlantDegradationLimit', ...
        'maximumWorstPlantCostDegradationFraction must be a finite nonnegative scalar.');
end
if bestSerialValid && ...
        missionComparisonAvailable
    missionComparableSeeds = ...
        missionValidationSeeds(baselineMissionMask);
    baselineMissionMetrics = ...
        BASELINE_MISSION_VALIDATION.metrics(baselineMissionMask);
    [missionValidationCost,TUNED_MISSION_VALIDATION] = ...
        evaluate_controller_candidate( ...
            zMission, ...
            CFG, ...
            MISSION_VALIDATION_STAGE, ...
            tunedAutopilot, ...
            baselineMissionMetrics, ...
            'serial', ...
            missionComparableSeeds, ...
            'strict');
    missionValidationValid = ...
        TUNED_MISSION_VALIDATION.success && ...
        isfinite(missionValidationCost) && ...
        missionValidationCost < ...
        CFG.cost.failurePenalty;
    if missionValidationValid
        missionImprovementFraction = ...
            1 - ...
            missionValidationCost;
        missionCostPass = ...
            missionValidationCost <= ...
            1 + ...
            missionMaximumDegradationFraction;
        if isfield(TUNED_MISSION_VALIDATION,'plantMeanCosts') && ...
                ~isempty(TUNED_MISSION_VALIDATION.plantMeanCosts)
            missionPlantMeanCosts = ...
                double( ...
                    TUNED_MISSION_VALIDATION.plantMeanCosts(:));
        elseif isfield(TUNED_MISSION_VALIDATION,'runCosts') && ...
                ~isempty(TUNED_MISSION_VALIDATION.runCosts)
            missionPlantMeanCosts = ...
                mean( ...
                    double(TUNED_MISSION_VALIDATION.runCosts), ...
                    2);
        elseif numel(CFG.experiment.plantModels) == 1
            missionPlantMeanCosts = ...
                missionValidationCost;
        end
        if numel(CFG.experiment.plantModels) == 1
            worstPlantPass = ...
                missionValidationCost <= ...
                1 + ...
                worstPlantMaximumDegradationFraction;
        else
            worstPlantPass = ...
                numel(missionPlantMeanCosts) == numel(CFG.experiment.plantModels) && ...
                all(isfinite(missionPlantMeanCosts)) && ...
                all( ...
                    missionPlantMeanCosts <= ...
                    1 + ...
                    worstPlantMaximumDegradationFraction);
        end
    end
end
if bestSerialValid
    if missionComparisonAvailable && ...
            all(baselineMissionMask) && ...
            missionValidationValid
        TUNED_MISSION_FEASIBILITY = ...
            TUNED_MISSION_VALIDATION;
        candidateMissionFeasibilityPass = ...
            true;
    else
        fprintf( ...
            'Running strict tuned mission feasibility check on all validation seeds...\n');
        [~,TUNED_MISSION_FEASIBILITY] = ...
            evaluate_controller_candidate( ...
                zMission, ...
                CFG, ...
                MISSION_VALIDATION_STAGE, ...
                tunedAutopilot, ...
                [], ...
                'serial', ...
                missionValidationSeeds, ...
                'strict');
        candidateMissionFeasibilityPass = ...
            logical( ...
                TUNED_MISSION_FEASIBILITY.success);
    end
end
if ~missionComparisonAvailable
    missionCostPass = ...
        candidateMissionFeasibilityPass;
    worstPlantPass = ...
        candidateMissionFeasibilityPass;
end
missionSafetyPass = ...
    bestSerialValid && ...
    candidateMissionFeasibilityPass && ...
    ( ...
    ~missionComparisonAvailable || ...
    ( ...
    missionValidationValid && ...
    missionCostPass && ...
    worstPlantPass));
if missionComparisonAvailable
    fprintf( ...
        'Mission normalized cost:   %.6f\n', ...
        missionValidationCost);
    fprintf( ...
        'Mission improvement:       %+.2f %%\n', ...
        100 * ...
        missionImprovementFraction);
    fprintf( ...
        'Mission cost gate:         %s\n', ...
        localPassFail( ...
            missionCostPass));
    fprintf( ...
        'Worst-plant gate:          %s\n', ...
        localPassFail( ...
            worstPlantPass));
else
    fprintf( ...
        'Mission normalized cost:   N/A — no successful baseline mission seed\n');
    fprintf( ...
        'Mission cost gate:         N/A — feasibility bootstrap mode\n');
    fprintf( ...
        'Worst-plant gate:          N/A — single-plant feasibility bootstrap mode\n');
end
fprintf( ...
    'Candidate strict mission:   %s\n', ...
    localPassFail( ...
        candidateMissionFeasibilityPass));
fprintf( ...
    'Mission safety gate:       %s\n', ...
    localPassFail( ...
        missionSafetyPass));
if CFG.policy.validateEachStage
    candidatePass = ...
        bestSerialValid && ...
        optimizationImproved && ...
        logical(stageValidationPass) && ...
        missionSafetyPass;
else
    candidatePass = ...
        bestSerialValid && ...
        optimizationImproved && ...
        missionSafetyPass;
end
if CFG.policy.keepBaselineIfNoImprovement
    accepted = ...
        candidatePass;
else
    if CFG.policy.validateEachStage
        accepted = ...
            bestSerialValid && ...
            logical(stageValidationPass) && ...
            missionSafetyPass;
    else
        accepted = ...
            bestSerialValid && ...
            missionSafetyPass;
    end
end
if accepted
    frozenAutopilotOut = ...
        tunedAutopilot;
    finalGainTable = ...
        bestGainTable;
    decision = ...
        "ACCEPTED_AND_FROZEN";
else
    frozenAutopilotOut = ...
        frozenAutopilotIn;
    finalGainTable = ...
        initialGainTable;
    decision = ...
        "REJECTED_BASELINE_KEPT";
end
verifiedFinalGainTable = ...
    controller_tuning_gain_table( ...
        frozenAutopilotOut, ...
        STAGE.parameterPaths);
if height(verifiedFinalGainTable) ~= ...
        numberOfParameters
    error( ...
        'QuadrotorFramework:ControllerStageFrozenGainCount', ...
        'Frozen controller gain verification returned an invalid size.');
end
optimizerDiagnostics = ...
    struct();
optimizerDiagnostics.requestedEvaluations = ...
    STAGE.maxFunctionEvaluations;
optimizerDiagnostics.optimizerCost = ...
    optimizerCost;
optimizerDiagnostics.exitFlag = ...
    exitFlag;
optimizerDiagnostics.optimizationTime_s = ...
    optimizationTime_s;
optimizerDiagnostics.vectorizedObjective = ...
    useVectorizedObjective;
optimizerDiagnostics.batchSize = ...
    CFG.optimizer.batchSize;
optimizerDiagnostics.minSurrogatePoints = ...
    STAGE.minSurrogatePoints;
optimizerDiagnostics.randomSeed = ...
    stageRandomSeed;
optimizerDiagnostics.requestedOptimizationSeedOffset = ...
    requestedOptimizationSeedOffset;
optimizerDiagnostics.optimizationSeedOffsetUsed = ...
    optimizationSeedOffsetUsed;
optimizerDiagnostics.numberOfParameters = ...
    numberOfParameters;
optimizerDiagnostics.controllerSet = ...
    string(CFG.experiment.controllerSet);
optimizerDiagnostics.plantModels = ...
    double(CFG.experiment.plantModels(:).');
optimizerDiagnostics.trajectoryID = ...
    double(CFG.experiment.trajectoryID);
optimizerDiagnostics.feedbackSource = ...
    string(CFG.experiment.feedbackSource);
optimizerDiagnostics.metricStateSource = ...
    string(CFG.experiment.metricStateSource);
STAGE_RESULT = ...
    struct();
STAGE_RESULT.schemaVersion = ...
    3.0;
STAGE_RESULT.controllerGainSchema = ...
    "3.0";
STAGE_RESULT.campaignProfile = ...
    CFG.campaignProfile;
STAGE_RESULT.controllerSet = ...
    string(CFG.experiment.controllerSet);
STAGE_RESULT.plantModels = ...
    double(CFG.experiment.plantModels(:).');
STAGE_RESULT.plantWeights = ...
    double(CFG.experiment.plantWeights(:).');
STAGE_RESULT.trajectoryID = ...
    double(CFG.experiment.trajectoryID);
STAGE_RESULT.feedbackSource = ...
    string(CFG.experiment.feedbackSource);
STAGE_RESULT.metricStateSource = ...
    string(CFG.experiment.metricStateSource);
STAGE_RESULT.stageID = ...
    STAGE.id;
STAGE_RESULT.stageName = ...
    STAGE.name;
STAGE_RESULT.stageKey = ...
    STAGE.key;
STAGE_RESULT.objectiveType = ...
    STAGE.objectiveType;
STAGE_RESULT.numberOfParameters = ...
    numberOfParameters;
STAGE_RESULT.parameterPaths = ...
    STAGE.parameterPaths;
STAGE_RESULT.parameterLabels = ...
    STAGE.parameterLabels;
STAGE_RESULT.initialGainTable = ...
    initialGainTable;
STAGE_RESULT.bestGainTable = ...
    bestGainTable;
STAGE_RESULT.finalGainTable = ...
    finalGainTable;
STAGE_RESULT.verifiedFinalGainTable = ...
    verifiedFinalGainTable;
STAGE_RESULT.bestLog10Multipliers = ...
    bestZ;
STAGE_RESULT.bestMultipliers = ...
    10.^bestZ;
STAGE_RESULT.optimizerReportedCost = ...
    optimizerCost;
STAGE_RESULT.bestSerialCost = ...
    bestSerialCost;
STAGE_RESULT.baselineOptimizationCost = ...
    baselineOptimizationCost;
STAGE_RESULT.optimizationImprovementFraction = ...
    optimizationImprovementFraction;
STAGE_RESULT.optimizationFeasibilityBootstrap = ...
    optimizationFeasibilityBootstrap;
STAGE_RESULT.optimizationImproved = ...
    optimizationImproved;
STAGE_RESULT.bestSerialValid = ...
    bestSerialValid;
STAGE_RESULT.stageValidationPerformed = ...
    stageValidationPerformed;
STAGE_RESULT.validationCost = ...
    validationCost;
STAGE_RESULT.validationImprovementFraction = ...
    validationImprovementFraction;
STAGE_RESULT.validationImproved = ...
    validationImproved;
STAGE_RESULT.baselineValidationValid = ...
    baselineValidationValid;
if stageValidationPerformed
    STAGE_RESULT.baselineValidationRecoverable = ...
        baselineValidationRecoverable;
    STAGE_RESULT.baselineValidationUsable = ...
        baselineValidationUsable;
else
    STAGE_RESULT.baselineValidationRecoverable = ...
        false;
    STAGE_RESULT.baselineValidationUsable = ...
        NaN;
end
STAGE_RESULT.tunedValidationValid = ...
    tunedValidationValid;
STAGE_RESULT.validationComparisonAvailable = ...
    validationComparisonAvailable;
STAGE_RESULT.baselineValidationComparableSeeds = ...
    baselineValidationComparableSeeds;
STAGE_RESULT.baselineValidationSuccessfulSeeds = ...
    baselineValidationSuccessfulSeeds;
STAGE_RESULT.baselineValidationFailedSeeds = ...
    baselineValidationFailedSeeds;
STAGE_RESULT.tunedValidationFeasibility = ...
    TUNED_VALIDATION_FEASIBILITY;
STAGE_RESULT.stageValidationFeasibilityPass = ...
    stageValidationFeasibilityPass;
STAGE_RESULT.stageValidationPass = ...
    stageValidationPass;
STAGE_RESULT.accepted = ...
    accepted;
STAGE_RESULT.decision = ...
    decision;
STAGE_RESULT.baselineOptimization = ...
    BASELINE_OPT;
STAGE_RESULT.baselineOptimizationRecoverable = ...
    baselineOptimizationRecoverable;
STAGE_RESULT.baselineOptimizationUsable = ...
    baselineOptimizationUsable;
STAGE_RESULT.requestedOptimizationSeedOffset = ...
    requestedOptimizationSeedOffset;
STAGE_RESULT.optimizationSeedOffsetUsed = ...
    optimizationSeedOffsetUsed;
STAGE_RESULT.baselineOptimizationAttempts = ...
    baselineOptimizationAttempts;
STAGE_RESULT.bestSerial = ...
    BEST_SERIAL;
STAGE_RESULT.batchPreflight = ...
    PREFLIGHT;
STAGE_RESULT.parallelPreflight = ...
    PREFLIGHT;
STAGE_RESULT.baselineValidation = ...
    BASELINE_VALIDATION;
STAGE_RESULT.tunedValidation = ...
    TUNED_VALIDATION;
STAGE_RESULT.missionValidationPerformed = ...
    true;
STAGE_RESULT.missionValidationStage = ...
    MISSION_VALIDATION_STAGE;
STAGE_RESULT.missionValidationSeeds = ...
    missionValidationSeeds;
STAGE_RESULT.baselineMissionValidation = ...
    BASELINE_MISSION_VALIDATION;
STAGE_RESULT.tunedMissionValidation = ...
    TUNED_MISSION_VALIDATION;
STAGE_RESULT.tunedMissionFeasibility = ...
    TUNED_MISSION_FEASIBILITY;
STAGE_RESULT.missionComparisonAvailable = ...
    missionComparisonAvailable;
STAGE_RESULT.baselineMissionSuccessfulSeeds = ...
    baselineMissionSuccessfulSeeds;
STAGE_RESULT.baselineMissionFailedSeeds = ...
    baselineMissionFailedSeeds;
STAGE_RESULT.candidateMissionFeasibilityPass = ...
    candidateMissionFeasibilityPass;
STAGE_RESULT.baselineMissionValid = ...
    baselineMissionValid;
STAGE_RESULT.baselineMissionRecoverable = ...
    baselineMissionRecoverable;
STAGE_RESULT.baselineMissionUsable = ...
    baselineMissionUsable;
STAGE_RESULT.commonRandomNumbers = ...
    true;
STAGE_RESULT.missionValidationValid = ...
    missionValidationValid;
STAGE_RESULT.missionValidationCost = ...
    missionValidationCost;
STAGE_RESULT.missionImprovementFraction = ...
    missionImprovementFraction;
STAGE_RESULT.missionMaximumDegradationFraction = ...
    missionMaximumDegradationFraction;
STAGE_RESULT.worstPlantMaximumDegradationFraction = ...
    worstPlantMaximumDegradationFraction;
STAGE_RESULT.missionPlantMeanCosts = ...
    missionPlantMeanCosts;
STAGE_RESULT.missionCostPass = ...
    missionCostPass;
STAGE_RESULT.worstPlantPass = ...
    worstPlantPass;
STAGE_RESULT.missionSafetyPass = ...
    missionSafetyPass;
STAGE_RESULT.requestedLowerLog10Multiplier = ...
    requestedLowerLog10Multiplier;
STAGE_RESULT.requestedUpperLog10Multiplier = ...
    requestedUpperLog10Multiplier;
STAGE_RESULT.effectiveLowerLog10Multiplier = ...
    double( ...
        STAGE.lowerLog10Multiplier(:));
STAGE_RESULT.effectiveUpperLog10Multiplier = ...
    double( ...
        STAGE.upperLog10Multiplier(:));
STAGE_RESULT.safetyBounds = ...
    SAFETY_BOUNDS;
STAGE_RESULT.exitFlag = ...
    exitFlag;
STAGE_RESULT.optimizerOutput = ...
    optimizerOutput;
STAGE_RESULT.trials = ...
    trials;
STAGE_RESULT.optimizerDiagnostics = ...
    optimizerDiagnostics;
STAGE_RESULT.optimizationTime_s = ...
    optimizationTime_s;
STAGE_RESULT.optimizerRandomSeed = ...
    stageRandomSeed;
STAGE_RESULT.stageFolder = ...
    stageFolder;
STAGE_RESULT.checkpointFile = ...
    checkpointFile;
save( ...
    stageResultFile, ...
    'STAGE_RESULT', ...
    '-v7.3');
gainTableFile = ...
    fullfile( ...
        stageFolder, ...
        'Stage_Gains.csv');
writetable( ...
    finalGainTable, ...
    gainTableFile);
fprintf('\n');
fprintf( ...
    '--------------------------------------------------------------\n');
fprintf( ...
    ' STAGE RESULT\n');
fprintf( ...
    '--------------------------------------------------------------\n');
fprintf( ...
    'Baseline cost:             %.6f\n', ...
    baselineOptimizationCost);
fprintf( ...
    'Best serial cost:          %.6f\n', ...
    bestSerialCost);
fprintf( ...
    'Optimization improvement:  %+.2f %%\n', ...
    100 * ...
    optimizationImprovementFraction);
if stageValidationPerformed
    if validationComparisonAvailable
        fprintf( ...
            'Validation cost:           %.6f\n', ...
            validationCost);
        fprintf( ...
            'Validation improvement:    %+.2f %%\n', ...
            100 * ...
            validationImprovementFraction);
    else
        fprintf( ...
            'Validation cost:           N/A — feasibility bootstrap mode\n');
    end
    fprintf( ...
        'Stage validation gate:     %s\n', ...
        localPassFail( ...
            stageValidationPass));
else
    fprintf( ...
        'Local multi-seed validation: SKIPPED\n');
end
if missionComparisonAvailable
    fprintf( ...
        'Mission validation cost:   %.6f\n', ...
        missionValidationCost);
else
    fprintf( ...
        'Mission validation cost:   N/A — feasibility bootstrap mode\n');
end
fprintf( ...
    'Mission safety gate:       %s\n', ...
    localPassFail( ...
        missionSafetyPass));
fprintf( ...
    'Decision:                  %s\n', ...
    decision);
fprintf('\nFinal stage gains:\n\n');
disp( ...
    finalGainTable(:, ...
    {'Label','BaselineValue','EffectiveValue','Multiplier'}));
fprintf( ...
    '==============================================================\n\n');
end
function J = controllerObjectiveBatch( ...
    Z, ...
    CFG, ...
    STAGE, ...
    frozenAutopilot, ...
    baselineMetrics)
[J,~] = ...
    evaluate_controller_candidates_parallel( ...
        Z, ...
        CFG, ...
        STAGE, ...
        frozenAutopilot, ...
        baselineMetrics);
J = ...
    double( ...
        J(:));
invalid = ...
    ~isfinite(J) | ...
    J < 0;
J(invalid) = ...
    CFG.cost.failurePenalty;
end
function J = controllerObjectiveSerial( ...
    z, ...
    CFG, ...
    STAGE, ...
    frozenAutopilot, ...
    baselineMetrics)
[J,~] = ...
    evaluate_controller_candidate( ...
        z, ...
        CFG, ...
        STAGE, ...
        frozenAutopilot, ...
        baselineMetrics, ...
        'serial', ...
        CFG.experiment.optimizationSeedOffset, ...
        'baseline');
J = ...
    double(J);
if ~isscalar(J) || ...
        ~isfinite(J) || ...
        J < 0
    J = ...
        CFG.cost.failurePenalty;
end
end
function localValidateFinalLocalStageContract(STAGE)
stageId = ...
    double(STAGE.id);
objectiveType = ...
    lower( ...
        string(STAGE.objectiveType));
paths = ...
    string(STAGE.parameterPaths(:));
switch stageId
    case 1
        expectedObjective = ...
            "rate_pitch";
        expectedPaths = [ ...
            "angularRate.pitch.Kp"; ...
            "angularRate.pitch.Ki"];
    case 2
        expectedObjective = ...
            "attitude_pitch";
        expectedPaths = ...
            "attitude.pitch.Kp";
    case 3
        expectedObjective = ...
            "joint_roll_pitch";
        expectedPaths = [ ...
            "angularRate.roll.Kp"; ...
            "angularRate.roll.Ki"; ...
            "attitude.roll.Kp"; ...
            "angularRate.pitch.Kp"; ...
            "angularRate.pitch.Ki"; ...
            "attitude.pitch.Kp"];
    otherwise
        error( ...
            'QuadrotorFramework:ControllerStageFinalLocalStageID', ...
            'Final local C2/L3 tuning supports exactly stages 1, 2, and 3.');
end
if objectiveType ~= expectedObjective
    error( ...
        'QuadrotorFramework:ControllerStageObjectiveContract', ...
        'Stage %d must use objectiveType "%s", not "%s".', ...
        stageId, ...
        expectedObjective, ...
        objectiveType);
end
if numel(paths) ~= numel(expectedPaths) || ...
        ~all(paths == expectedPaths)
    error( ...
        'QuadrotorFramework:ControllerStageParameterContract', ...
        'Stage %d parameter paths do not match the final local C2/L3 campaign contract.', ...
        stageId);
end
if numel(unique(paths)) ~= numel(paths)
    error( ...
        'QuadrotorFramework:ControllerStageDuplicateParameter', ...
        'Stage %d contains duplicate gain paths.', ...
        stageId);
end
end
function V = localNotPerformedValidation(message)
V = ...
    struct();
V.performed = ...
    false;
V.success = ...
    NaN;
V.cost = ...
    NaN;
V.messages = ...
    {message};
V.metrics = ...
    [];
end
function [STAGE,INFO] = localApplySafetyBounds(STAGE,CFG)
if double(STAGE.id) <= 2
    minimumMultiplier = ...
        0.5;
    maximumMultiplier = ...
        2.0;
    if isfield(CFG,'policy') && ...
            isstruct(CFG.policy) && ...
            isfield(CFG.policy,'innerLoopGainLowerMultiplier') && ...
            isfield(CFG.policy,'innerLoopGainUpperMultiplier')
        minimumMultiplier = ...
            double( ...
                CFG.policy.innerLoopGainLowerMultiplier);
        maximumMultiplier = ...
            double( ...
                CFG.policy.innerLoopGainUpperMultiplier);
    end
else
    minimumMultiplier = ...
        2/3;
    maximumMultiplier = ...
        1.5;
    if isfield(CFG,'policy') && ...
            isstruct(CFG.policy) && ...
            isfield(CFG.policy,'outerLoopGainLowerMultiplier') && ...
            isfield(CFG.policy,'outerLoopGainUpperMultiplier')
        minimumMultiplier = ...
            double( ...
                CFG.policy.outerLoopGainLowerMultiplier);
        maximumMultiplier = ...
            double( ...
                CFG.policy.outerLoopGainUpperMultiplier);
    end
end
if ~isscalar(minimumMultiplier) || ...
        ~isscalar(maximumMultiplier) || ...
        ~isfinite(minimumMultiplier) || ...
        ~isfinite(maximumMultiplier) || ...
        minimumMultiplier <= 0 || ...
        maximumMultiplier <= minimumMultiplier
    error( ...
        'QuadrotorFramework:ControllerStageSafetyMultiplierPolicy', ...
        'Configured safety multiplier bounds are invalid.');
end
safeLower = ...
    log10( ...
        minimumMultiplier);
safeUpper = ...
    log10( ...
        maximumMultiplier);
requestedLower = ...
    double( ...
        STAGE.lowerLog10Multiplier(:));
requestedUpper = ...
    double( ...
        STAGE.upperLog10Multiplier(:));
effectiveLower = ...
    max( ...
        requestedLower, ...
        safeLower);
effectiveUpper = ...
    min( ...
        requestedUpper, ...
        safeUpper);
if any(effectiveLower >= effectiveUpper)
    error( ...
        'QuadrotorFramework:ControllerStageSafetyBounds', ...
        'Safety-clipped optimizer bounds are invalid for stage "%s".', ...
        STAGE.name);
end
STAGE.lowerLog10Multiplier = ...
    reshape( ...
        effectiveLower, ...
        size(STAGE.lowerLog10Multiplier));
STAGE.upperLog10Multiplier = ...
    reshape( ...
        effectiveUpper, ...
        size(STAGE.upperLog10Multiplier));
initialPoint = ...
    double( ...
        STAGE.initialPoint(:));
initialPoint = ...
    min( ...
        max( ...
            initialPoint, ...
            effectiveLower), ...
        effectiveUpper);
STAGE.initialPoint = ...
    reshape( ...
        initialPoint, ...
        size(STAGE.initialPoint));
INFO = ...
    struct();
INFO.minimumMultiplier = ...
    minimumMultiplier;
INFO.maximumMultiplier = ...
    maximumMultiplier;
INFO.requestedLowerLog10Multiplier = ...
    requestedLower;
INFO.requestedUpperLog10Multiplier = ...
    requestedUpper;
INFO.effectiveLowerLog10Multiplier = ...
    effectiveLower;
INFO.effectiveUpperLog10Multiplier = ...
    effectiveUpper;
INFO.boundsWereClipped = ...
    any(abs(effectiveLower-requestedLower) > 1e-12) || ...
    any(abs(effectiveUpper-requestedUpper) > 1e-12);
end
function tf = localSoftBaselineFailureOnly(RESULT)
tf = ...
    true;
if ~isstruct(RESULT)
    tf = ...
        false;
    return;
end
if isfield(RESULT,'success') && ...
        logical(RESULT.success)
    return;
end
numberOfMessages = ...
    0;
if isfield(RESULT,'messages') && ...
        ~isempty(RESULT.messages)
    messages = ...
        RESULT.messages;
    if ischar(messages) || ...
            isstring(messages)
        messages = ...
            cellstr( ...
                string(messages));
    end
    if ~iscell(messages)
        tf = ...
            false;
        return;
    end
    failedMask = ...
        [];
    if isfield(RESULT,'runSucceeded') && ...
            ~isempty(RESULT.runSucceeded)
        failedMask = ...
            ~logical( ...
                RESULT.runSucceeded(:));
    end
    for messageIndex = 1:numel(messages)
        if ~isempty(failedMask) && ...
                numel(failedMask) == numel(messages) && ...
                ~failedMask(messageIndex)
            continue;
        end
        currentMessage = ...
            string( ...
                messages{messageIndex});
        if strlength(strtrim(currentMessage)) == 0 || ...
                strcmpi(strtrim(currentMessage),"OK")
            continue;
        end
        numberOfMessages = ...
            numberOfMessages + ...
            1;
        if ~localIsSoftBaselineMessage(currentMessage)
            tf = ...
                false;
            return;
        end
    end
else
    tf = ...
        false;
    return;
end
if numberOfMessages == 0
    tf = ...
        false;
end
end
function tf = localIsSoftBaselineMessage(messageText)
messageText = ...
    string( ...
        messageText);
softPatterns = [ ...
    "QuadrotorFramework:ControllerTuningMissionIncomplete"; ...
    "CGS Complete was not reached"; ...
    "QuadrotorFramework:ControllerTuningNoLanding"; ...
    "Final physical landing was not confirmed"; ...
    "QuadrotorFramework:ControllerTuningFailsafe"; ...
    "Mission entered the generic ABORTED/failsafe phase"; ...
    "QuadrotorFramework:ControllerNoTakeoff"; ...
    "No TAKEOFF phase was detected"; ...
    "QuadrotorFramework:ControllerNoAirborneState"; ...
    "Vehicle never became airborne"];
tf = ...
    false;
for patternIndex = 1:numel(softPatterns)
    if contains( ...
            messageText, ...
            softPatterns(patternIndex), ...
            'IgnoreCase', ...
            true)
        tf = ...
            true;
        return;
    end
end
end
function mask = localSuccessfulRunMask(RESULT,expectedCount)
mask = ...
    false( ...
        expectedCount, ...
        1);
if ~isstruct(RESULT)
    return;
end
if isfield(RESULT,'runSucceeded') && ...
        ~isempty(RESULT.runSucceeded)
    candidateMask = ...
        logical( ...
            RESULT.runSucceeded(:));
    if numel(candidateMask) == expectedCount
        mask = ...
            candidateMask;
        return;
    end
end
if isfield(RESULT,'success') && ...
        logical(RESULT.success)
    mask(:) = ...
        true;
end
end
function mask = localStrictRunMask(RESULT,expectedCount)
mask = ...
    false( ...
        expectedCount, ...
        1);
if ~isstruct(RESULT)
    return;
end
if isfield(RESULT,'strictRunSucceeded') && ...
        ~isempty(RESULT.strictRunSucceeded)
    candidateMask = ...
        logical( ...
            RESULT.strictRunSucceeded(:));
    if numel(candidateMask) == expectedCount
        mask = ...
            candidateMask;
        return;
    end
end
if isfield(RESULT,'strictMissionSuccess') && ...
        logical(RESULT.strictMissionSuccess)
    mask(:) = ...
        true;
end
end
function seeds = localStageSeedOffsets(CFG)
seeds = ...
    [];
if isfield(CFG,'validation') && ...
        isstruct(CFG.validation)
    if isfield(CFG.validation,'stageSeedOffsets') && ...
            ~isempty(CFG.validation.stageSeedOffsets)
        seeds = ...
            double( ...
                CFG.validation.stageSeedOffsets(:));
    elseif isfield(CFG.validation,'seedOffsets') && ...
            ~isempty(CFG.validation.seedOffsets)
        seeds = ...
            double( ...
                CFG.validation.seedOffsets(:));
    end
end
end
function seeds = localValidatedSeedOffsets(rawSeeds,label)
seeds = ...
    double( ...
        rawSeeds(:));
if isempty(seeds)
    error( ...
        'QuadrotorFramework:ControllerStageValidationSeeds', ...
        '%s requires at least one seed.', ...
        label);
end
if any(~isfinite(seeds))
    error( ...
        'QuadrotorFramework:ControllerStageValidationSeeds', ...
        '%s seeds must be finite.', ...
        label);
end
seeds = ...
    unique( ...
        seeds, ...
        'stable');
end
function VALIDATION_STAGE = localMissionValidationStage(CFG)
if ~isfield(CFG,'stages') || isempty(CFG.stages)
    error( ...
        'QuadrotorFramework:ControllerStageMissionValidationConfiguration', ...
        'CFG.stages is required for mission-level validation.');
end
VALIDATION_STAGE = ...
    CFG.stages(end);
VALIDATION_STAGE.id = ...
    9000;
VALIDATION_STAGE.name = ...
    "Mission-Level Safety Validation";
VALIDATION_STAGE.key = ...
    "mission_level_validation";
VALIDATION_STAGE.objectiveType = ...
    "horizontal_position";
VALIDATION_STAGE.initialPoint = ...
    zeros( ...
        VALIDATION_STAGE.numberOfParameters, ...
        1);
end
function text = localPassFail(value)
if logical(value)
    text = ...
        'PASS';
else
    text = ...
        'FAIL';
end
end
function displayMessages(messages)
if isempty(messages)
    fprintf( ...
        '  No diagnostic message available.\n');
    return;
end
if ischar(messages) || ...
        isstring(messages)
    messages = ...
        cellstr( ...
            string(messages));
end
for messageIndex = 1:numel(messages)
    currentMessage = ...
        messages{messageIndex};
    if isempty(currentMessage)
        continue;
    end
    fprintf( ...
        '  [%d] %s\n', ...
        messageIndex, ...
        char( ...
            string(currentMessage)));
end
end
