clear;
clc;
close all;
scriptDir = fileparts(mfilename('fullpath'));
if isempty(scriptDir)
    scriptDir = pwd;
end
csvFile = fullfile( ...
    scriptDir, ...
    'accuracy_cost_pareto_data_updated.csv');
if ~isfile(csvFile)
    error( ...
        ['Updated Pareto CSV not found:\n%s\n\n', ...
         'Place accuracy_cost_pareto_data_updated.csv in the same ', ...
         'folder as this script.'], ...
        csvFile);
end
T = readtable( ...
    csvFile, ...
    'VariableNamingRule','preserve');
requiredColumns = { ...
    'Level', ...
    'Mean execution time [s]', ...
    'Mean Path RMSE discrepancy [%]', ...
    'Mean Body-rate RMSE discrepancy [%]', ...
    'Mean Rotor-speed command discrepancy [%]'};
for k = 1:numel(requiredColumns)
    if ~ismember(requiredColumns{k},T.Properties.VariableNames)
        error( ...
            'CSV is missing required column: %s', ...
            requiredColumns{k});
    end
end
levels = ["L1","L2","L3"];
levelColumn = string(T.("Level"));
rowOrder = zeros(3,1);
for i = 1:3
    idx = find(levelColumn == levels(i));
    if numel(idx) ~= 1
        error( ...
            'Expected exactly one row for %s; found %d.', ...
            levels(i), ...
            numel(idx));
    end
    rowOrder(i) = idx;
end
T = T(rowOrder,:);
meanTime = double(T.("Mean execution time [s]"));
pathDisc = double(T.("Mean Path RMSE discrepancy [
bodyDisc = double(T.("Mean Body-rate RMSE discrepancy [
rotorDisc = double(T.("Mean Rotor-speed command discrepancy [
if any(~isfinite(meanTime)) || any(meanTime <= 0)
    error('Mean execution times must be finite and positive.');
end
if any(~isfinite(pathDisc)) || ...
   any(~isfinite(bodyDisc)) || ...
   any(~isfinite(rotorDisc))
    error('Discrepancy values must be finite.');
end
fprintf('\n=====================================================\n');
fprintf(' CROSS-FIDELITY DISCREPANCY - COST SUMMARY\n');
fprintf('=====================================================\n\n');
fprintf('Mean execution time:\n');
fprintf('L1 = %.6f s\n',meanTime(1));
fprintf('L2 = %.6f s\n',meanTime(2));
fprintf('L3 = %.6f s\n\n',meanTime(3));
fprintf('Mean discrepancy relative to L3:\n\n');
fprintf('Path RMSE:\n');
fprintf('L1 = %.4f %%\n',pathDisc(1));
fprintf('L2 = %.4f %%\n\n',pathDisc(2));
fprintf('Body-rate RMSE:\n');
fprintf('L1 = %.4f %%\n',bodyDisc(1));
fprintf('L2 = %.4f %%\n\n',bodyDisc(2));
fprintf('Rotor-speed command:\n');
fprintf('L1 = %.4f %%\n',rotorDisc(1));
fprintf('L2 = %.4f %%\n\n',rotorDisc(2));
fig = figure( ...
    'Color','w', ...
    'Position',[100 100 1180 720]);
ax = axes(fig);
hold(ax,'on');
box(ax,'on');
p1 = plot( ...
    ax, ...
    meanTime, ...
    pathDisc, ...
    '--o', ...
    'LineWidth',1.8, ...
    'MarkerSize',9);
p2 = plot( ...
    ax, ...
    meanTime, ...
    bodyDisc, ...
    '--s', ...
    'LineWidth',1.8, ...
    'MarkerSize',9);
p3 = plot( ...
    ax, ...
    meanTime, ...
    rotorDisc, ...
    '--^', ...
    'LineWidth',1.8, ...
    'MarkerSize',10);
set( ...
    ax, ...
    'XScale','log', ...
    'FontSize',13, ...
    'LineWidth',1.15);
xlabel( ...
    ax, ...
    'Mean execution time [s] (log scale)', ...
    'FontSize',15);
ylabel( ...
    ax, ...
    'Mean discrepancy relative to L3 [%]', ...
    'FontSize',15);
xMin = min(meanTime) * 0.82;
xMax = max(meanTime) * 1.25;
yMaxData = max([pathDisc; bodyDisc; rotorDisc]);
yMaxPlot = max(86,ceil((yMaxData + 4)/5)*5);
xlim(ax,[xMin xMax]);
ylim(ax,[-2 yMaxPlot]);
ax.XGrid = 'on';
ax.YGrid = 'on';
ax.XMinorGrid = 'on';
ax.YMinorGrid = 'on';
ax.GridLineStyle = '-';
ax.MinorGridLineStyle = ':';
ax.GridAlpha = 0.22;
ax.MinorGridAlpha = 0.18;
legend( ...
    ax, ...
    [p1 p2 p3], ...
    {'Path RMSE', ...
     'Body-rate RMSE', ...
     'Rotor-speed command'}, ...
    'Location','northeast', ...
    'FontSize',12);
labelFS = 10.5;
labelBG = 'w';
labelMargin = 1;
text( ...
    ax, ...
    meanTime(1)*1.035, ...
    bodyDisc(1)+1.6, ...
    sprintf('L1: %.2f s, %.1f%%', ...
    meanTime(1),bodyDisc(1)), ...
    'FontSize',labelFS, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'BackgroundColor',labelBG, ...
    'Margin',labelMargin);
text( ...
    ax, ...
    meanTime(2)*1.035, ...
    bodyDisc(2)-1.6, ...
    sprintf('L2: %.2f s, %.1f%%', ...
    meanTime(2),bodyDisc(2)), ...
    'FontSize',labelFS, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'BackgroundColor',labelBG, ...
    'Margin',labelMargin);
text( ...
    ax, ...
    meanTime(1)*0.97, ...
    pathDisc(1)+2.6, ...
    sprintf('L1: %.2f s, %.1f%%', ...
    meanTime(1),pathDisc(1)), ...
    'FontSize',labelFS, ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'BackgroundColor',labelBG, ...
    'Margin',labelMargin);
text( ...
    ax, ...
    meanTime(2)*1.045, ...
    pathDisc(2)+2.2, ...
    sprintf('L2: %.2f s, %.1f%%', ...
    meanTime(2),pathDisc(2)), ...
    'FontSize',labelFS, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'BackgroundColor',labelBG, ...
    'Margin',labelMargin);
text( ...
    ax, ...
    meanTime(1)*0.97, ...
    rotorDisc(1)-0.55, ...
    sprintf('L1: %.2f s, %.1f%%', ...
    meanTime(1),rotorDisc(1)), ...
    'FontSize',labelFS, ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','top', ...
    'BackgroundColor',labelBG, ...
    'Margin',labelMargin);
text( ...
    ax, ...
    meanTime(2)*1.045, ...
    rotorDisc(2)-0.55, ...
    sprintf('L2: %.2f s, %.1f%%', ...
    meanTime(2),rotorDisc(2)), ...
    'FontSize',labelFS, ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','top', ...
    'BackgroundColor',labelBG, ...
    'Margin',labelMargin);
text( ...
    ax, ...
    meanTime(3)*0.97, ...
    4.6, ...
    sprintf('L3: %.2f s, 0%%',meanTime(3)), ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'BackgroundColor','w', ...
    'Margin',1);
drawnow;
fprintf('Exporting figure...\n');
set(fig,'Renderer','painters');
set(fig,'PaperPositionMode','auto');
pdfFile = fullfile( ...
    scriptDir, ...
    'ICRA2027_Discrepancy_Cost_Plot.pdf');
pngFile = fullfile( ...
    scriptDir, ...
    'ICRA2027_Discrepancy_Cost_Plot.png');
print( ...
    fig, ...
    pdfFile, ...
    '-dpdf', ...
    '-painters', ...
    '-bestfit');
fprintf('PDF exported successfully.\n');
print( ...
    fig, ...
    pngFile, ...
    '-dpng', ...
    '-r300');
fprintf('PNG exported successfully.\n');
fprintf('\n=====================================================\n');
fprintf(' FIGURE EXPORT COMPLETE\n');
fprintf('=====================================================\n');
fprintf('PDF: %s\n',pdfFile);
fprintf('PNG: %s\n',pngFile);
fprintf('=====================================================\n');
